### ISSUE TITLE
ExoPlayer (vs Media3) versioning

### ISSUE THREAD

**Issue by moneytoo** [androidx/media#1]
When migrating from standalone ExoPlayer to this Media3, is there any information on what is the respective ExoPlayer release for each Media3 release? Does the current Media3 `1.0.0-alpha01` matches ExoPlayer `2.15.1` (for API compatibility when migrating, applying patches etc.)? I think this could be useful information in release notes.

**Comment by icbaker** [comment]
There's currently no direct correlation between media3 and exoplayer2 releases. The exoplayer2 `dev-v2` branch is roughly in sync with the `main` branch in this repository. However, in addition to the package prefix change, there are a number of symbols that have moved around - so directly migrating from exoplayer2 to media3 will likely necessitate some code changes in apps.

The media3 1.0.0-alpha01 release was built from the `main` branch, meaning it contains commits not present in ExoPlayer 2.15.1. ExoPlayer 2.16.0 (releasing soon) will contain some commits not present in 1.0.0-alpha01 (though only about a week's worth). Future alpha, beta and stable releases of media3 will likely contain commits not present in ExoPlayer 2.16.0.

We plan to align future media3 and exoplayer2 releases, but it's possible this won't happen in lockstep (e.g. there may sometimes be releases of one without the other) - we're still working out the precise details of this.
