### ISSUE TITLE
The music progress bar in notification has not been updated

### ISSUE THREAD

**Issue by re-ovo** [androidx/media#10]
video: https://streamable.com/asqane

It seems that it is updated only after being clicked

**Comment by marcbaechinger** [comment]
I can not reproduce this. I tried with a `MediaSessionService` and a `MediaLibraryService` and in both cases the progress bar notification is updated immediately when skipping to the next or previous item. 

Can you give me some more details in how you have setup your app that is playing in the video above? What service are you using when you produce the notification that does not have the duration? Is the media playing normally in the `StyledPlayerView` within the app?

**Comment by spun** [comment]
Hi @marcbaechinger, can you try again with different media? Is difficult to reproduce (when it works it always works) but it's happening to me more or less consistently when playing `Jazz & Blues` or `Rock` from the `Genre Folder` (demo-session app from repo)

[video](https://i.imgur.com/vLwQSsq.mp4) (Android Emulator API 29)
 
I don't know if it helps but, since the progress bar appears immediately after pausing, I thought that the notification was getting posted too soon. I modified `MediaNotificationHandler` to be able to force a notification update at different times and this is what I got when the seekbar started showing consistently.
 
**Logs for default behavior (progress bar bug):**
```
D/PlaybackService: Event 0/5: EVENT_TIMELINE_CHANGED
D/PlaybackService: Event 1/5: EVENT_MEDIA_ITEM_TRANSITION
D/PlaybackService: Event 2/5: EVENT_PLAYBACK_STATE_CHANGED
D/PlaybackService: Event 3/5: EVENT_PLAY_WHEN_READY_CHANGED
D/PlaybackService: Event 4/5: EVENT_AVAILABLE_COMMANDS_CHANGED
D/PlaybackService: Event 5/5: EVENT_MEDIA_METADATA_CHANGED
D/PlaybackService: onUpdateNotification
D/PlaybackService: Event 0/1: EVENT_TIMELINE_CHANGED
D/PlaybackService: Event 1/1: EVENT_IS_LOADING_CHANGED
D/PlaybackService: Event 0/1: EVENT_TIMELINE_CHANGED
D/PlaybackService: Event 1/1: EVENT_AVAILABLE_COMMANDS_CHANGED
D/PlaybackService: Event 0/0: EVENT_TRACKS_CHANGED
D/PlaybackService: Event 0/1: EVENT_PLAYBACK_STATE_CHANGED
D/PlaybackService: Event 1/1: EVENT_IS_PLAYING_CHANGED
D/PlaybackService: Event 0/0: EVENT_IS_LOADING_CHANGED
...
```
 
**Logs with forced notification update (progress bar always appears):**
```
D/PlaybackService: Event 0/5: EVENT_TIMELINE_CHANGED
D/PlaybackService: Event 1/5: EVENT_MEDIA_ITEM_TRANSITION
D/PlaybackService: Event 2/5: EVENT_PLAYBACK_STATE_CHANGED
D/PlaybackService: Event 3/5: EVENT_PLAY_WHEN_READY_CHANGED
D/PlaybackService: Event 4/5: EVENT_AVAILABLE_COMMANDS_CHANGED
D/PlaybackService: Event 5/5: EVENT_MEDIA_METADATA_CHANGED
D/PlaybackService: onUpdateNotification
D/PlaybackService: Event 0/1: EVENT_TIMELINE_CHANGED
D/PlaybackService: Event 1/1: EVENT_IS_LOADING_CHANGED
D/PlaybackService: Event 0/1: EVENT_TIMELINE_CHANGED
D/PlaybackService: Event 1/1: EVENT_AVAILABLE_COMMANDS_CHANGED
D/PlaybackService: Event 0/0: EVENT_TRACKS_CHANGED
D/PlaybackService: forceNotificationUpdate
D/PlaybackService: onUpdateNotification
D/PlaybackService: Event 0/1: EVENT_PLAYBACK_STATE_CHANGED
D/PlaybackService: Event 1/1: EVENT_IS_PLAYING_CHANGED
D/PlaybackService: Event 0/0: EVENT_IS_LOADING_CHANGED
...
```

**Comment by re-ovo** [comment]
> I can not reproduce this. I tried with a `MediaSessionService` and a `MediaLibraryService` and in both cases the progress bar notification is updated immediately when skipping to the next or previous item.
> 
> Can you give me some more details in how you have setup your app that is playing in the video above? What service are you using when you produce the notification that does not have the duration? Is the media playing normally in the `StyledPlayerView` within the app?

It's just a music app, so there is no StyledPlayerView, it's just a MediaLibraryService

**Comment by re-ovo** [comment]
> 嘿@re-ovo。我们需要更多信息来解决此问题，但 14 个工作日内没有更新。我将这个问题标记为过时，如果在接下来的 7 天内没有新的更新，我将自动关闭它。
> 
> 如果您有更多信息可以帮助我们深入了解这一点，请添加评论！

...

**Comment by re-ovo** [comment]
?

**Comment by re-ovo** [comment]
It has been fixed now after testing new version of media3
