### ISSUE TITLE
MediaMetaData returns null values if player is set to Player.REPEAT_MODE_ONE (Same as Legacy issue #9458 at ExoPlayer repository)

### ISSUE THREAD

**Issue by amirkazemzade** [androidx/media#1007]
### Version

Media3 1.2.1

### Devices that reproduce the issue

AVD Pixel 8 Pro API 34
AVD Pixel 8 Pro API 33
AVD Pixel 3a API 28
Galaxy A50 with Android 11

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Open `PlayerActivity` at `androidx/media3/demo/main/PlayerActivity.java`
2. Add `player.setRepeatMode(Player.REPEAT_MODE_ONE);`  after `player = playerBuilder.build();` at line `279`
3. Build and run the demo app
4. Go down to `Misc` list
5. Press `Google Play (MP3)` to play
6. Seek the seek-bar to the almost end of it ( for example at the `00:56` )
7. Let the playback continue to end the current item and then repeat the playback.

### Expected result

The artwork picture of the item remains the same.

### Actual result

The artwork disappears. As I inspected in debug mode, all metadata values but the title are null in the second playback.

### Media

https://github.com/androidx/media/assets/76568952/810032e7-74da-4e21-85ec-17250fb41191

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by tonihei** [comment]
Thanks for reporting! We'll fix that (again) for the upcoming 1.3.0 release.
