### ISSUE TITLE
How would a standalone MediaSessionService ask for permissions?

### ISSUE THREAD

**Issue by aljohnston112** [androidx/media#1020]
The use case would be a MediaSessionService that uses user local data (READ_MEDIA_AUDIO) to serve content to MediaControllers but does not have an Activity.

**Comment by tonihei** [comment]
To ask for permission, you usually need to have an `Activity` at some point. I don't know what kind of app you are writing, but I would expect that all apps show a visible `Activity` the first time they are started after install. This is probably the best time to ask for these permissions. Once they are granted, you do not have to ask for them again. If they are not granted, and you want to ask for them later, I think you then need to start a new Activity to request this from the user.

**Comment by aljohnston112** [comment]
That makes sense. Thank you!
