### ISSUE TITLE
When ```setMediaItems``` is called ```playerCommandsFromPlayer``` does not include commands included via ```getAvailableCommands``` of ```ForwardingPlayer```

### ISSUE THREAD

**Issue by aljohnston112** [androidx/media#1021]
### Version

Media3 1.2.1

### Devices that reproduce the issue

Samsung Galaxy A12 SM-A125U

### Reproducible in the demo app?

Not tested

### Reproduction steps

Create a ```ForwardingPlayer``` like so

```kt
class MyPlayer(
    private var context: Context,
) : ForwardingPlayer(
    ExoPlayer.Builder(context)
        .setSkipSilenceEnabled(true)
        .setSeekParameters(SeekParameters.EXACT)
        .build()
) {

    override fun seekToNextMediaItem() {
        // custom behavior
    }

}
```

Create a ```MediaLibrarySession``` like so
```kt
        mediaSession = MediaLibraryService.MediaLibrarySession.Builder(
            service,
            player,
            callback
        ).build()
```
Create a ```MediaBrowser``` like so:
```kt
            browser = MediaBrowser.Builder(applicationContext, sessionToken)
                .buildAsync()
                .await()
```
Then call ```MediaBrowser.seekToNextMediaItem()```
```kt
browser.seekToNextMediaItem()
```
and notice that ```ForwardingPlayer.seekToNextMediaItem()``` is not called.

### Expected result

For the ```ForwardingPlayer``` to get the ```seekToNextMediaItem()``` call.

### Actual result

The ```seekToNextMediaItem()``` method of the ```ForwardingPlayer``` is not called.

### Media

Not applicable

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by aljohnston112** [comment]
This was a misunderstanding on my part. ```COMMAND_SEEK_TO_NEXT_MEDIA_ITEM``` was not an available player command.

**Comment by aljohnston112** [comment]
Actually, there still is no call when I add these methods to the ForwardingPlayer implementation

```kt
    override fun getAvailableCommands(): Player.Commands {
        return super.getAvailableCommands().buildUpon().add(COMMAND_SEEK_TO_NEXT_MEDIA_ITEM).build()
    }

    override fun isCommandAvailable(command: Int): Boolean {
        return super.isCommandAvailable(command) || command == COMMAND_SEEK_TO_NEXT_MEDIA_ITEM
    }
```

**Comment by aljohnston112** [comment]
The ```intersectedPlayerCommands``` of the ```MediaControllerImplBase``` does not get the commands set in ```getAvailableCommands``` of the ```ForwardingPlayer```

**Comment by aljohnston112** [comment]
What's weird is that I put breakpoints on the 4 writes of ```intersectedPlayerCommands``` in ```MediaControllerImplBase```, and before the ```MediaBrowser``` calls ```seekToNextMediaItem``` the ```COMMAND_SEEK_TO_NEXT_MEDIA_ITEM``` flag is included in ```intersectedPlayerCommands```

**Comment by aljohnston112** [comment]
Ok, so it looks like ``` setMediaItems``` is not getting flags set by the ```ForwardingPlayer```

**Comment by aljohnston112** [comment]
Is there some way to force an update of the flags after ```ExoPlayerImpl``` overwrites them?

**Comment by tonihei** [comment]
Can you explain a bit more what you'd like to achieve? If it's just about changing the available commands for media controllers, the recommended way is to configure that in `MediaSession.Callback.onConnect` as shown here: https://developer.android.com/media/media3/session/background-playback#media-notification-controller

**Comment by aljohnston112** [comment]
I was trying to get ```MyPlayer``` to overwrite the available commands after ```setMediaItems``` is called because the next media item may not be known until the playing of the current media item is done.

Setting the ```COMMAND_SEEK_TO_NEXT_MEDIA_ITEM``` in the ```onConnect``` callback did not work. This is what I tried.

```kt
        @OptIn(UnstableApi::class)
        override fun onConnect(
            session: MediaSession,
            controller: MediaSession.ControllerInfo
        ): MediaSession.ConnectionResult {
            val playerCommands =
                session.player.availableCommands.buildUpon()
                    .add(COMMAND_SEEK_TO_NEXT_MEDIA_ITEM)
                    .build()
            return MediaSession.ConnectionResult.AcceptedResultBuilder(session)
                .setAvailablePlayerCommands(playerCommands)
                .build()
        }
```

I then thought instead that I could add a next media item to the playlist, and of course, since ExoPlayer sees a next media item, it makes the command available. 

This works, but it seems as though the commands made available through the ```onConnect``` callback, the ```onAvailableCommandsChanged``` callback, the ```ForwardingPlayer.getAvailableCommands```, and the ```ForwardingPlayer.isCommandAvailable``` are not enough to make a command, that ExoPlayer does not make available, available which seems like a bug to me.

**Comment by tonihei** [comment]
I tested this out and I think there may be some confusion around `COMMAND_SEEK_TO_NEXT_MEDIA_ITEM` and `COMMAND_SEEK_TO_NEXT`. If both are available, the button click in the System notification maps to `seekToNext()` whereas `seekToNextMediaItem()` is used as a fallback. They may have different behaviors depending on the media (e.g. `seekToNext` in a live stream skips forward to the live edge. Can you try overriding `COMMAND_SEEK_TO_NEXT`/`seekToNext()` only?

**Comment by aljohnston112** [comment]
That makes sense, but the seek to next command is still overwritten by ExoPlayer when setMediaItem is called.

**Comment by tonihei** [comment]
This may be related to you override the listener. If all listener calls get intercepted, then the you always overwrite whatever commands ExoPlayer makes available.

**Comment by aljohnston112** [comment]
It is the other way around. ExoPlayer is overwriting the commands I tried to make available via the listener.

**Comment by tonihei** [comment]
If you feel something is broken, please provide a more complete example that allows us to reproduce the issue. Otherwise I think there must be some missing piece in your forwarding player somewhere.
