### ISSUE TITLE
Is it possible to start an EditedMediaItemSequence delayed?

### ISSUE THREAD

**Issue by AradiPatrik** [androidx/media#1023]
I would like to play an EditedMediaItemSequence in the background, and let's say at the 1 second mark start playing another edited media item sequence on top and let's say at the 2 second mark I would like to start playing another (overlayed on top of both).

I managed to do this by adding a transparent image as the first item in the EditedMediaItemSequence and set the duration to 2 seconds and added another EditedMediaItem afterwards. The problem with this is the looping behavior is broken (transparent image gets shown again after the second media item stops playing)

I would like to write something like this:
```
EditedMediaItemSequence sequence = ...
sequence.setInitialDelayMs(2000)
```
Is something similar possible?

**Comment by droid-girl** [comment]
@AradiPatrik delays are currently not supported. We are looking to add more support to build complex compositions and this is one of the use cases on our roadmap.
I want to clarify the looping behaviour problem. Do you have 2 `EditedMediaItemSequence` where one of them is set isLooping to true? Are both `EditedMediaItemSequence` contain a list of video files?

**Comment by AradiPatrik** [comment]
@droid-girl Thank you for the response I can't wait to see these more complex composition features in the library!

My use-case is:
Delay 5 seconds, then start looping a 3 second video

I achieved the delay by creating and `EditedMediaItemSequence(transparentImageEditedItem, clipToLoopEditedItem, isLooping = true)` but it's not exactly what I want because it will start over the whole sequence (I just want to loop the clipToLoopEditedItem).

I understand this is not supported easily at the moment. Could you think of any workaround to achieve my use-case given the capabilities of the library now?

**Comment by dway123** [comment]
For now, we don't support the delay as you've mentioned. 

In the meantime, the best I can think of to emulate delay+looping is to have an EditedMediaItemSequence starting with a transparent image shown for 5 seconds, followed by the 3-second video's MediaItem repeated N times, where N is the amount of times you'd like it to loop

**Comment by AradiPatrik** [comment]
Thanks for the suggestion @dway123! I think this is a good workaround for now, after the z-ordering issue is fixed I will use this technique to implement delay+loop.
