### ISSUE TITLE
How do you intercept commands with a ```ForwardingPlayer```?

### ISSUE THREAD

**Issue by aljohnston112** [androidx/media#1026]
It seemed pretty straightforward to me, but it is not working as expected.

I have a ```MediaBrowser``` that I am using as a ```MediaController``` for a ```MediaLibraryService.MediaLibrarySession```

I set up the ```ForwardingPlayer``` like so
```kt
class MyPlayer(
    private var context: Context?,
    private val mediaItemCreator: MediaItemCreator
) : ForwardingPlayer(
    ExoPlayer.Builder(context!!)
        .setSkipSilenceEnabled(true)
        .setSeekParameters(SeekParameters.EXACT)
        .build()
) {

    private lateinit var _playlist: ProbabilityMap<MusicFile>

    fun setPlaylist(playlist: ProbabilityMap<MusicFile>) {
        _playlist = playlist
    }

    override fun getAvailableCommands(): Player.Commands {
        return super.getAvailableCommands()
            .buildUpon()
            .add(COMMAND_SEEK_TO_NEXT_MEDIA_ITEM)
            .add(COMMAND_SEEK_TO_NEXT)
            .build()
    }

    override fun isCommandAvailable(command: Int): Boolean {
        return availableCommands.contains(command)
    }

    override fun setMediaItem(mediaItem: MediaItem) {
        val next = mediaItemCreator.getMediaItem(
            context!!,
            _playlist.sample().id
        )
        super.setMediaItems(listOf(mediaItem, next))
    }

    override fun seekToNextMediaItem() {
        if(::_playlist.isInitialized) {
            val next = mediaItemCreator.getMediaItem(
                context!!,
                _playlist.sample().id
            )
            replaceMediaItem(mediaItemCount - 1, next)
            seekTo(
                currentMediaItemIndex + 1,
                C.TIME_UNSET
            )
            val afterNext = mediaItemCreator.getMediaItem(
                context!!,
                _playlist.sample().id
            )
            addMediaItem(afterNext)
        }
    }

    override fun release() {
        super.release()
        context = null
    }

}
```

The command methods do get called, but ```COMMAND_SEEK_TO_NEXT_MEDIA_ITEM``` is not always available to the controller.

Then when the controller method ```setMediaItem``` is called, the ```MyPlayer.setMediaItem``` method is not called. 

This issue I made earlier has more details:
https://github.com/androidx/media/issues/1021

**Comment by aljohnston112** [comment]
I did some more debugging and it turns out the mappings from controller calls to player calls are not one-to-one and there is no mapping in the docs: https://developer.android.com/reference/androidx/media3/session/MediaController#setMediaItem(androidx.media3.common.MediaItem)

In particular, ```setMediaItem``` from the controller calls ```setMediaItems``` in the player. Are there mappings for this type of thing documented somewhere? Are these subject to change?

**Comment by tonihei** [comment]
> Are the mappings for this type of thing documented somewhere? Are they consistent? Are these subject to change?

We attempt to call the same `Player` method as far as possible, but sometimes need to change it slightly depending on the available commands and parameters we need to pass in. I think from your perspective, it's best to implement all the methods you declare as available via the commands without making assumptions which one is called exactly. 

> I expect to be able to know which ForwardingPlayer overrides I will need to provide for said command

All these command codes fully list the methods that need to be implemented for this code. Example: https://developer.android.com/reference/androidx/media3/common/Player#COMMAND_SET_SPEED_AND_PITCH() explains how `COMMAND_SET_SPEED_AND_PITCH maps to `setPlaybackParameters` and `setPlaybackSpeed`.

**Comment by aljohnston112** [comment]
Thank you so much for the explanation! That page looks like a fantastic resource for this.
