### ISSUE TITLE
Cannot override DefaultMediaNotificationProvider.handleCustomCommand

### ISSUE THREAD

**Issue by kevinguitar** [androidx/media#103]
Hi media team 👋 

I was trying to extend your `DefaultMediaNotificationProvider` and use our internal `BitmapLoader` implementation, but turns out the `handleCustomCommand` function is final and can't be overridden.

I'm wondering is that intended for some reason? I would like to use your notification provider implementation which contains nice bitmap/ notification builder handling, but I need to provide some custom actions.

Looking forward to your answers, thanks!

**media3 Version**: 1.0.0-beta01

**Comment by marcbaechinger** [comment]
You can receive the custom command on `MediaSession.Callback.onCustomCommand'. Why do you want to receive them on the provider? If your app is running with compileApiLevel 32 and on Android 14, the custom command is sent from the SystemUI notification directly to the session `MediaSession.Callback.onCustomCommand'. So you would have to handle it for Android 13 on the session and for API levels before Android 13 on the `DefaultMediaNotificationProvider`. 

So I think you want to override `MediaSession.Callback.onCustomCommand` instead so you only have to do this once.

**Comment by kevinguitar** [comment]
@marcbaechinger  Thanks for the quick response! And yes, that's definitely what I need, closing the issue, thanks!

**Comment by marcbaechinger** [comment]
Great! Thanks for confirming! 

We should document this better. I added the documentation candidate and re-open this issue for tracking this.

**Comment by kevinguitar** [comment]
Yeah, I guess I was confused by the methods' documentation in `MediaNotification.ActionFactory` 😅
