### ISSUE TITLE
How to add volume filter in ffmpeg_jni.cc

### ISSUE THREAD

**Issue by lijmin** [androidx/media#1030]

**Comment by tonihei** [comment]
If this is about configuring FFMPEG, then it's outside the scope of this issue tracker and it's better to ask these questions elsewhere. If you want to change the volume during playback, you can use `player.setVolume`. And if you want to apply more advanced audio processing of the output, you can write a custom [audio processor](https://developer.android.com/reference/androidx/media3/common/audio/AudioProcessor).
