### ISSUE TITLE
MediaController addListener receives a Player.Listener which has a onSkipSilenceEnabledChanged, but it doesn't get called

### ISSUE THREAD

**Issue by Digipom** [androidx/media#1034]
### Version

Media3 1.2.1

### More version details

Not applicable

### Devices that reproduce the issue

Not applicable

### Devices that do not reproduce the issue

Not applicable

### Reproducible in the demo app?

Not applicable

### Reproduction steps

If you call exoPlayer.addListener(...) and your listener implements onSkipSilenceEnabledChanged, then that will be called whenever you change the value of exoPlayer.skipSilenceEnabled.

However, if you have a media controller, which you obtain as follows: ```private val controllerFuture = MediaController.Builder(
        context,
        SessionToken(context, ComponentName(context, PlaybackService::class.java))
    ).buildAsync()```
And you implement onSkipSilenceEnabledChanged in ```controller.addListener(listener)```, the method will never be called.

### Expected result

The method is called. 

### Actual result

The method is *not* called.

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by oceanjules** [comment]
Hi @Digipom,

As you rightly pointed out, https://github.com/androidx/media/issues/1027 is a related issue and, in fact, they are completely dependent. So I will close this issue as a duplicate and leave the other one as an enhancement tracker.

To give you more context:

When a setter is called on Exoplayer, the new value is passed to all the listeners as `listener.onSkipSilenceEnabledChanged`

https://github.com/androidx/media/blob/b930b40a16c06318e43c81771fa2b1024bdb3f29/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/ExoPlayerImpl.java#L1549-L1560


Similarly, if `Player` interface had its own `setSkipSilenceEnabled` method (i.e. what you wanted in https://github.com/androidx/media/issues/1027), it would be overriden-implemented by `MediaController` (or specifically in [MediaControllerImplBase](https://github.com/androidx/media/blob/b930b40a16c06318e43c81771fa2b1024bdb3f29/libraries/session/src/main/java/androidx/media3/session/MediaControllerImplBase.java)) in a similar way to ExoPlayer above. You can take a look at that class to see how other setters have code like

```
listeners.queueEvent(
          /* eventFlag= */ Player.EVENT_SOMETHING_CHANGED,
          listener -> listener.onSOMETHINGChanged(SOMETHING));
```


Even though the `Player.Listener` interface currently has a `onSkipSilenceEnabledChanged` method, it will not be triggered inside MediaController until `MediaController.setSkipSilenceEnabled` exists and for that we need `Player` interface to get its own `setSkipSilenceEnabled` method.

**Comment by Digipom** [comment]
Thanks, for now I worked around using media session extras. It seems the API is halfway to being fully implemented, so having it fully connected will be nice. :)

**Comment by anonym24** [comment]
@Digipom can you please provide an example or how to send "setSilence" command from UI to MediaSession Service?

**Comment by Digipom** [comment]
Certainly. 
1) Service:

<pre>
        session =
            MediaSession.Builder(this, player)
                <b>.setCallback(CustomMediaSessionCallback(player))</b>
                .build()
</pre>
```
companion object {
        const val ENABLE_SKIP_SILENCE = "ENABLE_SKIP_SILENCE"
        const val DISABLE_SKIP_SILENCE = "DISABLE_SKIP_SILENCE"
        const val EXTRA_IS_SKIP_SILENCE_ENABLED = "EXTRA_IS_SKIP_SILENCE_ENABLED"
    }
```
2) Callback:

```
@androidx.media3.common.util.UnstableApi
private class CustomMediaSessionCallback(private var exoPlayer: ExoPlayer) : MediaSession.Callback {
    override fun onConnect(
        session: MediaSession,
        controller: MediaSession.ControllerInfo
    ): MediaSession.ConnectionResult {
        val sessionCommands = MediaSession.ConnectionResult.DEFAULT_SESSION_COMMANDS.buildUpon()
            .add(SessionCommand(ENABLE_SKIP_SILENCE, Bundle.EMPTY))
            .add(SessionCommand(DISABLE_SKIP_SILENCE, Bundle.EMPTY))
            .build()

        return MediaSession.ConnectionResult.AcceptedResultBuilder(session)
            .setAvailableSessionCommands(sessionCommands)
            .setSessionExtras(Bundle().apply {
                putBoolean(EXTRA_IS_SKIP_SILENCE_ENABLED, exoPlayer.skipSilenceEnabled)
            })
            .build()
    }

    override fun onCustomCommand(
        session: MediaSession,
        controller: MediaSession.ControllerInfo,
        customCommand: SessionCommand,
        args: Bundle
    ): ListenableFuture<SessionResult> {
        return when (customCommand.customAction) {
            ENABLE_SKIP_SILENCE -> {
                exoPlayer.skipSilenceEnabled = true
                Futures.immediateFuture(SessionResult(SessionResult.RESULT_SUCCESS))
            }

            DISABLE_SKIP_SILENCE -> {
                exoPlayer.skipSilenceEnabled = false
                Futures.immediateFuture(SessionResult(SessionResult.RESULT_SUCCESS))
            }

            else -> {
                super.onCustomCommand(session, controller, customCommand, args)
            }
        }
    }
}
```

3) Controller:
```
private val mediaControllerListener = MediaControllerListener(
        onSkipSilenceUpdate = { skipSilenceEnabled ->
            if (DEBUG_LOGGING_ON) {
                Logger.d("Updating is skip silence enabled to $skipSilenceEnabled")
            }
            _skipSilenceEnabled.update { skipSilenceEnabled }
        }
    )

private val controllerFuture = MediaController.Builder(
        context,
        SessionToken(context, ComponentName(context, PlaybackService::class.java))
    ).setListener(mediaControllerListener)
        .buildAsync()

private val _skipSilenceEnabled = MutableStateFlow(false)
val skipSilenceEnabled = _skipSilenceEnabled.asStateFlow()

suspend fun setSkipSilenceEnabled(skipSilenceEnabled: Boolean) {
        if (DEBUG_LOGGING_ON) {
            Logger.v("setSkipSilenceEnabled($skipSilenceEnabled)")
        }
        obtainController()?.apply {
            sendCustomCommand(
                SessionCommand(
                    when (skipSilenceEnabled) {
                        true -> PlaybackService.ENABLE_SKIP_SILENCE
                        false -> PlaybackService.DISABLE_SKIP_SILENCE
                    }, Bundle.EMPTY
                ), Bundle.EMPTY
            )
        }
    }
```
