### ISSUE TITLE
In Media3 Transformer add ability to set GL_FLOAT_VEC4 as uniform (for rgba values)

### ISSUE THREAD

**Issue by AradiPatrik** [androidx/media#1039]
When filing a feature request:
-----------------------
### [REQUIRED] Use case description
I would like to create a shader program extending `BaseGlShaderProgram` that accepts a vec4 uniform color. Currently I get `java.lang.IllegalStateException: Unexpected uniform type: 35666`.

### Proposed solution
In `GlProgram.java: GlProgram.Uniform.bind` there should be a case for `GL_FLOAT_VEC4`.

### Alternatives considered
We could go around the issue and extend `GlShaderProgram` (base of `BaseGlShaderProgram`) add a try catch for this case and set the uniform manually using the GLES20 api, but it would be much more convenient if this was supported by GlProgram)

**Comment by dway123** [comment]
Thanks for the report. I have a draft change to fix this and will link it after it's out
