### ISSUE TITLE
FMP4 Multiple Media Sources Seamless seek

### ISSUE THREAD

**Issue by mljivanovic** [androidx/media#1057]
I want to customize the player to play multiple fmp4 videos consecutively like a playback or concatenate media source, with seamless transitions between videos and the ability to seek seamlessly to any point. The video source is external storage attached to the device. The files have an mp4 extension, are fragmented, and do not have an sidx box. Could this work if I added an sidx box?

**Comment by oceanjules** [comment]
Have you taken a look at https://developer.android.com/media/media3/exoplayer/media-sources#advanced-media-source-composition? 

It might help to have a [ConcatenatingMediaSource](https://developer.android.com/reference/androidx/media3/exoplayer/source/ConcatenatingMediaSource2) or [a playlist](https://developer.android.com/media/media3/exoplayer/playlists) instead.

**Comment by mljivanovic** [comment]
Will seek work through all files with concatinatingmediasource of fm4 files? For example if we have 2 files of 15 minutes and at the beginning user seeks from file one to the end of file 2 before seek map of second file is extracted?

**Comment by tonihei** [comment]
The setup you are describing sounds like you'd need a DASH manifest or HLS playlist around your fMP4 files to define the media structure. This assumes you already know the durations of each item.

Using `ConcatenatingMediaSource2` or the playlist API as mentioned above also works, but the player will only load the seek maps (if they exist) and the durations once it reaches each individual file.
