### ISSUE TITLE
Battery 

### ISSUE THREAD

**Issue by Lucky390163** [androidx/media#1060]
Really it uses much battery.My phone is 6000mah and compared to vlc it is bad

**Comment by icbaker** [comment]
Hi! Please provide complete information as requested in the question template. 

Unfortunately we can't answer unclear issues or those with insufficient information.

**Comment by Lucky390163** [comment]
The apps msde from this codevare using much battery whike watching videos offline in compared to Samsung default video player.I don't no why but it needs some improvements.

**Comment by icbaker** [comment]
Closing because insufficient information has been provided to make this actionable.
