### ISSUE TITLE
Loading custom shaders in media player?

### ISSUE THREAD

**Issue by tjasmin111** [androidx/media#1061]
I want to see if I can load some custom shaders and apply to media player in Android. Apparently we should use [libplacebo ]( https://github.com/haasn/libplacebo) to run them. But does Android media player support that through its APIs so we won't have to use libplacebo?

libplacebo page says:
A pluggable, extensible [custom shader system](http://libplacebo.org/custom-shaders/). This can be used to arbitrarily extend the range of custom shaders to include popular user shaders like RAVU, FSRCNNX, or Anime4K. See the [mpv wiki on user scripts](https://github.com/mpv-player/mpv/wiki/User-Scripts#user-shaders) for more information.

**Comment by droid-girl** [comment]
Hi @tjasmin111,
You can use `ExoPlayer` if you want to apply custom shaders. You can create a custom [`GlEffect`](https://github.com/androidx/media/blob/release/libraries/effect/src/main/java/androidx/media3/effect/GlEffect.java) and preview it in `ExoPlayer`, using `ExoPlayer.setVideoEffects`.
