### ISSUE TITLE
CMCD data as query parameter is url-encoded twice

### ISSUE THREAD

**Issue by sobbe81** [androidx/media#1075]
### Version

Media3 1.2.1

### Devices that reproduce the issue

All devices

### Reproducible in the demo app?

Not tested

### Reproduction steps

1.  Enable CMCD as query-parameter
2. Play something 

### Expected result

CMCD data included in the url as query-parameters and url-encoded

### Actual result

This is an example of a CMCD query-parameter.

CMCD=bl%253D20200%252Cbr%253D6000%252Cd%253D3840%252Cdl%253D20200%252Cmtp%253D57500%252Cot%253Dv%252Csf%253Dd%252Cst%253Dl%252Ctb%253D6000

Is seems like it's url-encoded twice.  Is that done intentially?

### Media

N/A

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment]
Thanks for spotting, I can reproduce this behaviour, I'll send a fix for review.
