### ISSUE TITLE
How to pass request headers for HttpDataSource dynamically

### ISSUE THREAD

**Issue by JyothiPAsapu** [androidx/media#1076]
I've instantiated an ExoPlayer class with a DefaultHttpDataSource.Factory -> DefaultDataSource.Factory -> CacheDataSource.Factory -> DefaultMediaSourceFactory. I aim to use this instance throughout the app. While most URLs play without any issues, a few require special request parameters. Currently, since DefaultRequestProPerties is tied with DefaultHttpDataSource.Factory, I'm unable to change dynamically for each video played on Exoplayer.

Is there an existing method to achieve this? If not, can we implement a solution for it?

**Comment by JyothiPAsapu** [comment]
Certainly, a potential solution is to create two DefaultMediaSourceFactory instances and set the different source factories using ExoPlayer.setMediaSource(). However, with this approach, there's a need to maintain or create two CacheDataSource.Factory instances. Is there a way to minimize code duplication in this scenario?

**Comment by icbaker** [comment]
Have you tried using [`ResolvingDataSource`](https://developer.android.com/reference/androidx/media3/datasource/ResolvingDataSource)? It lets you add headers to the `DataSpec` before the request is forwarded to the delegate `DataSource` instance.

**Comment by JyothiPAsapu** [comment]
Thanks @icbaker. With [ResolvingDataSource](https://developer.android.com/reference/androidx/media3/datasource/ResolvingDataSource), I am able to pass RequestProperties.
