### ISSUE TITLE
Media3 ExoPlayer PlayerView UI - seekbar doesn't work (to change position) and rewind/fast forward buttons are disabled

### ISSUE THREAD

**Issue by HelgeApps** [androidx/media#1082]
### Version

Media3 1.2.1

### More version details

I'm trying to play `.m4a` audio file (DocumentProvider/SAF URI, e.g: `content://com.android.externalstorage.documents/tree/primary%3AVoiceRecorder/document/primary%3AVoiceRecorder%2F2024-02-09%2017h%2016m%2040s.m4a`) but I can't change position using seekbar and rewind/fast forward buttons are disabled for some reason. Why?

    val player = ExoPlayer.Builder(context).build()
    player.setMediaItem(MediaItem.fromUri(audioFileUri))
    player.playWhenReady = true
    player.prepare()

ui:

    AndroidView(
        modifier = Modifier
            .fillMaxSize(),
        factory = {
            // androidx.media3.ui.PlayerView
            PlayerView(it).also { playerView ->
                playerView.controllerHideOnTouch = false
                playerView.controllerAutoShow = true
                playerView.controllerShowTimeoutMs = 0
                playerView.player = player
                playerView.setShowRewindButton(true)
                playerView.setShowFastForwardButton(true)
                playerView.showController()
            }
        },
    )

[![enter image description here][1]][1]

    val media3Version = "1.2.1"
    implementation("androidx.media3:media3-exoplayer:$media3Version")
    implementation("androidx.media3:media3-session:$media3Version")
    implementation("androidx.media3:media3-ui:$media3Version")

  [1]: https://i.stack.imgur.com/fsxGq.png

### Devices that reproduce the issue

Samsung S10 (Android 12), Samsung S22 (Android 14)

### Reproducible in the demo app?

Yes

### Reproduction steps

play a sample audio file .m4a

### Expected result

seeking is working

### Actual result

seeking not working

### Media

https://fex.net/s/nx8f9ss

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by HelgeApps** [comment]
Fixed by settings [setConstantBitrateSeekingEnabled][1]:

    val player = ExoPlayer.Builder(context)
        .setMediaSourceFactory(
            DefaultMediaSourceFactory(
                /* context = */ context,
                /* extractorsFactory = */ DefaultExtractorsFactory().apply {
                    setConstantBitrateSeekingEnabled(true)
                }
            )
        )
        .build()


  [1]: https://developer.android.com/reference/androidx/media3/extractor/DefaultExtractorsFactory#setConstantBitrateSeekingEnabled(boolean)

**Comment by tvenam** [comment]
using: androidx.media3:media3-exoplayer:1.3.0
 @HelgeApps  Mentioned solution does not work. Please let me know if there are any else to fix it.
