### ISSUE TITLE
Opening the app, when notification is clicked

### ISSUE THREAD

**Issue by brahmkshatriya** [androidx/media#1083]
I am using this, to create my notification for the PlayerService
```
val provider = DefaultMediaNotificationProvider.Builder(this).build()
provider.setSmallIcon(R.drawable.ic_mono) 
```
this creates the notification successfully, but how do I make the notification to open the app when the notification is clicked?

Do I need to create a custom MediaNotification.Provider? If so, how do I make it identical to DefaultMediaNotification & how does one implement the on click of the notification?

**Comment by marcbaechinger** [comment]
I think tapping the no notification is supposed to get the user to  `MediaSession.getSessionActivity()`  which is a pending intent that you can set on the session when building it. You can later also use a getter to change the pending intent of the session activity.

This is implemented like this for `DefaultmediaNotificationProvider` that creates the notification on API below 32. Starting from 32 System UI creates a UMO notification and uses the same pending intent that the provider uses. If you want to have this consistently working in the same way, then I believe just leaving it as it is implemented makes what you want. Any difference in implementation would be inconsistent across API levels.

**Comment by marcbaechinger** [comment]
That's right! I have created a change to document this. Just to double check whether I'd add this to the right place: what page(s) would you have considered to look for this information?

**Comment by marcbaechinger** [comment]
Documented here: https://developer.android.com/media/implement/surfaces/mobile
