### ISSUE TITLE
Detect supported offload codec

### ISSUE THREAD

**Issue by Tolriq** [androidx/media#1093]
I'd like to know if there's any API or efficient way to know what codec a given device support for offload playback.

The context is using that information to decide to what format the media should be transcoded to for offline playback on a watch where battery usage is very important.

Android docs says that MP3/AAC and Opus offload **may** be supported but not must be supported, so I supposed this is up to the OEM and hence why I'm looking for a way to detect it.

**Comment by microkatz** [comment]
Hello @Tolriq,

Thank you for posting your question. There are specific Android APIs to determine playback offload support on the device. ExoPlayer calls these APIs through a [DefaultAudioOffloadSupportProvider](https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/audio/DefaultAudioOffloadSupportProvider.java) in DefaultAudioSink. These APIs are provided by [AudioManager](https://developer.android.com/reference/android/media/AudioManager). Depending on the API level of your device you might call [getDirectPlaybackSupport](https://developer.android.com/reference/android/media/AudioManager#getDirectPlaybackSupport(android.media.AudioFormat,%20android.media.AudioAttributes)) , [getPlaybackOffloadSupport](https://developer.android.com/reference/android/media/AudioManager#getPlaybackOffloadSupport(android.media.AudioFormat,%20android.media.AudioAttributes)), etc.

Hope that answers your question!

**Comment by Tolriq** [comment]
Thanks DefaultAudioOffloadSupportProvider have everything I need including conversion of format from Media3 to Android ones.

If there any risk directly using that class ? (I mean risk of making this private in the future)

**Comment by microkatz** [comment]
There are not guarantees as it in @UnstableAPI of course. 

However, the purpose of that class is to query the AudioManager for offload capabilities and be that provider for DefaultAudioSink. It was designed as a default in case application wish to provide their own or wrap the default to edit etc. As a result it is unlikely we make this class private. In the future, we may update the class to report support of other offload attribute capabilities, use newer Android APIs etc.

Glad the class had what you needed. I'll close the issue. Please reopen or create a new one if you have additional questions.
