### ISSUE TITLE
currentMediaItem.mediaId is empty during playback

### ISSUE THREAD

**Issue by andycass** [androidx/media#11]
After assigning a mediaId to a mediaItem, during playback the currentMediaItem.mediaId is at first there then it is empty, I require the mediaItem mediaId as i am playing media from different sources and this identifies them

**Comment by andycass** [comment]
I didn't build upon the current media item in MediaItemFiller i created a new instance of the media item and forgot the mediaId

    class CustomMediaItemFiller : MediaSession.MediaItemFiller {
        override fun fillInLocalConfiguration(
            session: MediaSession,
            controller: MediaSession.ControllerInfo,
            mediaItem: MediaItem
        ): MediaItem {
            // Return the media item that it will be played
            return mediaItem.buildUpon()
                .setMediaId(mediaItem.mediaId)
                .setUri(mediaItem.mediaMetadata.mediaUri)
                .setMediaMetadata(mediaItem.mediaMetadata)
                .build()
        }
    }

**Comment by marcbaechinger** [comment]
I understand this is solved after having set the `mediaId` in the builder when filling the item. 
I'll close this issue. Please reopen if you thing there is still a problem.

**Comment by marcbaechinger** [comment]
I understand this is solved after having set the `mediaId` in the builder when filling the item. 
I'll close this issue. Please reopen if you thing there is still a problem.
