### ISSUE TITLE
Android Auto Grid Layout with Media3

### ISSUE THREAD

**Issue by zeroed-tech** [androidx/media#1112]
I'm attempting to get a super basic Android Auto application up and runnning via Media3. I've managed to convert most of the steps outlined in https://developer.android.com/training/cars/media over to Media3 however the one thing I cannot get working is changing the layout of my application so it shows a Grid of playable MediaItems rather than a list.

The above link suggests this can be achieved with the legacy library through
```
public BrowserRoot onGetRoot(
    @NonNull String clientPackageName,
    int clientUid,
    @Nullable Bundle rootHints) {
    Bundle extras = new Bundle();
    extras.putInt(
        MediaConstants.DESCRIPTION_EXTRAS_KEY_CONTENT_STYLE_BROWSABLE,
        MediaConstants.DESCRIPTION_EXTRAS_VALUE_CONTENT_STYLE_GRID_ITEM);
    extras.putInt(
        MediaConstants.DESCRIPTION_EXTRAS_KEY_CONTENT_STYLE_PLAYABLE,
        MediaConstants.DESCRIPTION_EXTRAS_VALUE_CONTENT_STYLE_LIST_ITEM);
    return new BrowserRoot(ROOT_ID, extras);
}
```

I believe the media3 equivilant should be this but nothing I do has any effect on my layout.
```
public ListenableFuture<LibraryResult<MediaItem>> onGetLibraryRoot(MediaLibrarySession session, MediaSession.ControllerInfo browser, LibraryParams params) {

    params.extras.putInt(
                    MediaConstants.EXTRAS_KEY_CONTENT_STYLE_BROWSABLE,
                    MediaConstants.EXTRAS_VALUE_CONTENT_STYLE_GRID_ITEM
            );
   params.extras.putInt(
                    MediaConstants.EXTRAS_KEY_CONTENT_STYLE_PLAYABLE,
                    MediaConstants.EXTRAS_VALUE_CONTENT_STYLE_GRID_ITEM
            );
    return Futures.immediateFuture(LibraryResult.ofItem(rootNode, params));
}
```
I've tried setting these values at both the MediaItem and the global levels but nothings working.
![image](https://github.com/androidx/media/assets/3313484/04296d18-7201-4e72-96cf-974c7bd78d34)

Can anyone shed some light on what I might be doing wrong?
Thanks

**Comment by marcbaechinger** [comment]
Thanks for reporting!

This works for me with the session demo:

```
  @OptIn(UnstableApi::class)
  override fun onGetLibraryRoot(
    session: MediaLibraryService.MediaLibrarySession,
    browser: MediaSession.ControllerInfo,
    params: MediaLibraryService.LibraryParams?,
  ): ListenableFuture<LibraryResult<MediaItem>> {
    val rootExtras =
      Bundle().apply {
        putInt(
          MediaConstants.EXTRAS_KEY_CONTENT_STYLE_BROWSABLE,
          MediaConstants.EXTRAS_VALUE_CONTENT_STYLE_CATEGORY_GRID_ITEM,
        )
        putInt(
          MediaConstants.EXTRAS_KEY_CONTENT_STYLE_PLAYABLE,
          MediaConstants.EXTRAS_VALUE_CONTENT_STYLE_CATEGORY_GRID_ITEM,
        )
      }
    return Futures.immediateFuture(
      LibraryResult.ofItem(
        MediaItemTree.getRootItem(),
        MediaLibraryService.LibraryParams.Builder().setExtras(rootExtras).build(),
      )
    )
  }
```

The only difference to your code I see is that the library params are created newly with `MediaLibraryService.LibraryParams.Builder().setExtras(rootExtras).build()`, but I don't think this should make a difference.

The same works [with the media3 branch of UAMP](https://github.com/android/uamp/blob/media3/common/src/main/java/com/example/android/uamp/media/MusicService.kt#L320) that isn't using the same constants but the values that are used are the same.

**Comment by zeroed-tech** [comment]
Got it working!

It apears you can't style songs directly under your library root, i.e. 

```
Root
  |-Song
  |-Song
  |-Song
```
They need to be under a container media item (i.e. an Album, artis, playlist, madeup container type)

```
Root
  |-Playlist
    |-Song
    |-Song
```
Thanks again for the help

**Comment by marcbaechinger** [comment]
Glad it's working and thanks for the update why it wasn't!
