### ISSUE TITLE
Non-Exoplayer TimeBar with Exoplayer Function

### ISSUE THREAD

**Issue by Mintakaaaa** [androidx/media#1130]
Hi, I've been trying to implement Exoplayer through PlayerView with completely custom controls.
I have got a rewind, play/pause, and fast forward button working. By this I mean, I have buttons separate from Exoplayer, that call a function that activates some Exoplayer functionality like play or pause.
The problem I have now is that I want to create a completely separate TimeBar that can control Exoplayer playback, but the TimeBar does not show a scrubber (circle thing), and it has no functionality, despite me adding an OnScrubListener to the TimeBar. I believe I'm missing another link between the Exoplayer and the TimeBar, as the TimeBar does not reflect the playback of the Exoplayer.

**So my question is**, how do I implement a custom TimeBar that is not inside the Exoplayer view? Thank you!

My XML looks like this, if that helps: 
```
<androidx.media3.ui.PlayerView
    android:id="@+id/video_view"
    android:layout_width="match_parent"
    android:layout_height="0dp"
    app:layout_constraintDimensionRatio="w,1:1"
    android:layout_marginStart="20dp"
    android:layout_marginTop="20dp"
    android:layout_marginEnd="20dp"
    android:layout_marginBottom="20dp"
    app:controller_layout_id="@layout/empty_file"
    app:default_artwork="@drawable/png_music"
    app:hide_on_touch="false"
    app:show_timeout="0"
    app:use_artwork="true"
    tools:ignore="MissingConstraints" />

... (buttons and other in between...)

<androidx.media3.ui.DefaultTimeBar
    android:id="@+id/time_bar"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_marginEnd="10dp"
    android:layout_marginStart="10dp">
</androidx.media3.ui.DefaultTimeBar>
```
Note: the "empty_file" contains invisible rewind, ffwd, and play/pause buttons. I did this to hide them.
And the video player activity:
```
timeBarTB.addListener(new TimeBar.OnScrubListener() {
    @Override
    public void onScrubStart(TimeBar timeBar, long position) {
        player.pause();
    }

    @Override
    public void onScrubMove(TimeBar timeBar, long position) {
        player.seekTo(position);
    }

    @Override
    public void onScrubStop(TimeBar timeBar, long position, boolean canceled) {
        player.play();
    }
});
```

**Comment by oceanjules** [comment]
It's been a while and maybe you have figured it out in the end. But just for the sake of anyone stumbling upon this:

* You can see how the listener callbacks are used in PlayerControlView (interacting with the Player only in "onStop")

https://github.com/androidx/media/blob/c35a9d62baec57118ea898e271ac66819399649b/libraries/ui/src/main/java/androidx/media3/ui/PlayerControlView.java#L1838-L1860

The 2 important places where timebar gets position/duration (which are useful pieces for drawing the scrubbing circle in the correct place proportionally to the screen width) are actually encapsulated in functions that are called quite often/with a delay/in different logical places:

* `updateProgress()`
https://github.com/androidx/media/blob/c35a9d62baec57118ea898e271ac66819399649b/libraries/ui/src/main/java/androidx/media3/ui/PlayerControlView.java#L1453-L1455

* `updateTimeline()`
https://github.com/androidx/media/blob/c35a9d62baec57118ea898e271ac66819399649b/libraries/ui/src/main/java/androidx/media3/ui/PlayerControlView.java#L1424-L1425
