### ISSUE TITLE
Automatically play when network is restored

### ISSUE THREAD

**Issue by Potato-66** [androidx/media#1140]
I use exoplayer play hls(live-m3u8), when the network is interrupted, the player throw an exception "ERROR_CODE_IO_NETWORK_CONNECTION_FAILED", but after network is restored, the player does not continue to play, I need register network listener and setPlayWhenReady(true)?

**Comment by marcbaechinger** [comment]
> I need register network listener and setPlayWhenReady(true)?

Yes, this sounds about right to me. You'd have to call `prepare()` though, as `playWhenReady` does not change when an playback exception occurs.

You can configure the load error handling by setting a configured or custom `LoadErrorHandlingPolicy`. There a [section in the developer guide](https://developer.android.com/media/media3/exoplayer/customization#configuring-the-network-stack) about this.

By default the load error handling policy will retry a couple of times. The player continues to play out the available buffered media and then transitions into `STATE_IDLE` with a playback exception.

In the case you are describing, an app can call `prepare()` again when the network is restored. 

I don't think that ExoPlayer should resolve a playback error itself by guessing the reason being network outage that came back again. One reason is that ExoPlayer actually doesn't know from where media is loaded. This can be the network, a local file, the local cache or other sources. Simply listening to network availability wouldn't generally work I think - an app can handle this better.

**Comment by Potato-66** [comment]
> > I need register network listener and setPlayWhenReady(true)?我需要注册网络监听器和setPlayWhenReady（true）？
> 
> Yes, this sounds about right to me. You'd have to call `prepare()` though, as `playWhenReady` does not change when an playback exception occurs.是的，这听起来对我来说是正确的。但是你必须调用 `prepare()` ，因为当播放异常发生时 `playWhenReady` 不会改变。
> 
> You can configure the load error handling by setting a configured or custom `LoadErrorHandlingPolicy`. There a [section in the developer guide](https://developer.android.com/media/media3/exoplayer/customization#configuring-the-network-stack) about this.您可以通过设置已配置或自定义的 `LoadErrorHandlingPolicy` 来配置加载错误处理。在开发者指南中有一节是关于这个的。
> 
> By default the load error handling policy will retry a couple of times. The player continues to play out the available buffered media and then transitions into `STATE_IDLE` with a playback exception.默认情况下，加载错误处理策略将重试几次。播放器继续播放可用的缓冲媒体，然后转换到 `STATE_IDLE` ，但出现播放异常。
> 
> In the case you are describing, an app can call `prepare()` again when the network is restored.在您所描述的情况下，当网络恢复时，应用可以再次调用 `prepare()` 。
> 
> I don't think that ExoPlayer should resolve a playback error itself by guessing the reason being network outage that came back again. One reason is that ExoPlayer actually doesn't know from where media is loaded. This can be the network, a local file, the local cache or other sources. Simply listening to network availability wouldn't generally work I think - an app can handle this better.我不认为ExoPlayer应该通过猜测网络中断的原因来解决播放错误。一个原因是ExoPlayer实际上不知道媒体从哪里加载。这可以是网络、本地文件、本地缓存或其他源。我认为，简单地听取网络可用性通常不会起作用-一个应用程序可以更好地处理这一点。

Thank you for providing the imformation;it has given me a clearer understanding of the issue.
