### ISSUE TITLE
HLS Iframe only track can't be played since 1.2.0.alpha01

### ISSUE THREAD

**Issue by zgzong** [androidx/media#1150]
### Version

Media3 1.2.0

### More version details

The HLS IFrame only track can be played on r1.1.1, same track can't be played since media3 r1.2.0-alpha01. 

### Devices that reproduce the issue

On android mobile, tablet and STB. 

Tested on mobile: pixel 7, pixel tablet. amazon fireTV 4k stb. 

### Reproducible in the demo app?

Yes

### Reproduction steps

Add Iframe only track stream into demo media.exolist.json, and play the demo app to play the iframe only track. 
Any version before (include) r1.1.1, can play IFrame only track. 
But since r1.2.0-alpha01, the stream can't be played, and no exception to throw. 

### Expected result

The IFrame only track can be played.

### Actual result

Segment downloaded, but nothing rendered.

### Media

[iframe_only_xmap.zip](https://github.com/androidx/media/files/14497931/iframe_only_xmap.zip)
[iframe_only.zip](https://github.com/androidx/media/files/14497959/iframe_only.zip)
Here are two Iframe only tracks.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment]
CC @dsparano (author of https://github.com/androidx/media/pull/419)

The specific comment thread where we discussed HLS in the context of that PR is here: https://github.com/androidx/media/pull/419#discussion_r1217890240

**Comment by dsparano** [comment]
Let me take a look at this.

**Comment by dsparano** [comment]
Sorry for the delay. I think I've got a solution for H264 which would include general cases of byterange and I-Frame only HLS streams, which I had not personally tested when on https://github.com/androidx/media/pull/419.
However, I think I should test with the other readers (H262, H263 and H265) as well and for them I should have some streams available soon (if anyone has some valid streams pls share), after which I should be able to open a PR.

If an interim solution is required asap, then I suggest to disable "Send a synthesised empty pusi" if mode==MODE_HLS, @icbaker please let me know.

**Comment by dsparano** [comment]
@icbaker possible fix here https://github.com/v-novaltd/androidx-media/tree/dsparano-exo245 shall I open a PR?

**Comment by tonihei** [comment]
@dsparano Given the update seems to fix all reported issues, please go ahead and open the PR. We can continue any further detailed discussion in there.

**Comment by dsparano** [comment]
@tonihei yes, I already opened this PR: https://github.com/androidx/media/pull/1189

**Comment by tonihei** [comment]
Sorry, ignore me, thanks for the PR ;)

**Comment by rohitjoins** [comment]
Hi @zgzong,

https://github.com/androidx/media/pull/419 has been rolled back and the issue should be resolved now.
