### ISSUE TITLE
DRM session error java.lang.IllegalArgumentException: {}: BAD_VALUE

### ISSUE THREAD

**Issue by bartmejia18** [androidx/media#1151]
### Version

Media3 1.1.1 / ExoPlayer 2.19.1

### Devices that reproduce the issue

Does not play content on the following androidstudio emulators

Android 14.0 UpsideDownCake
Android 14.0 UpsideDownCakePrivacySandbox
Android 14 VanillaIceCream

Does not play content on physical Google Pixel device with Android 14

![WhatsApp Image 2024-03-05 at 18 32 18](https://github.com/androidx/media/assets/14446375/df4db0db-c994-4c1f-8fb0-b9d5554ed463)

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Open the Media3 demo app and play the specified Widevine-DASH video

### Expected result

play content with drm widevine

### Actual result

`DRM session error
java.lang.IllegalArgumentException: {}: BAD_VALUE
cdm err: 0, oem err: 0, ctx: 0
============================== Beginning of DRM Plugin Log ==============================
03-05 18:10:02.025 I No hidl drm factories found
03-05 18:10:02.025 E Failed to find passthrough drm factories
03-05 18:10:03.791 I [cdm_usage_table.cpp(203):RestoreTable] Found usage table to restore: entry_count = 0
03-05 18:10:03.801 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:10:03.809 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:10:03.810 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:10:03.810 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:10:03.813 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:10:03.814 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:10:03.816 I [cdm_engine.cpp(216):OpenSession] New session: session_id = sid4
03-05 18:10:03.816 I [cdm_engine.cpp(1050):QueryOemCryptoSessionId] session_id = sid4
03-05 18:10:03.820 I [cdm_engine.cpp(955):QuerySessionStatus] session_id = sid4
03-05 18:10:03.821 I [cdm_engine.cpp(2264):SetPlaybackId] session_id = sid4, playback_id = -ClkpG8-bj95hhbL
03-05 18:10:03.841 I [cdm_engine.cpp(303):GenerateKeyRequest] session_id = sid4, key_set_id = <empty>, license_type = Streaming
03-05 18:10:03.841 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:10:03.841 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:10:03.901 I [cdm_engine.cpp(1089):IsSecurityLevelSupported] level = L1
03-05 18:10:03.903 I [cdm_engine.cpp(955):QuerySessionStatus] session_id = sid4
03-05 18:10:04.075 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:10:04.076 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:10:04.076 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:10:04.077 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:10:04.077 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:10:04.078 I [cdm_engine.cpp(1050):QueryOemCryptoSessionId] session_id = sid5
03-05 18:10:04.078 I [cdm_engine.cpp(216):OpenSession] New session: session_id = sid5
03-05 18:10:04.079 I [cdm_engine.cpp(955):QuerySessionStatus] session_id = sid5
03-05 18:10:04.080 I [cdm_engine.cpp(2264):SetPlaybackId] session_id = sid5, playback_id = -ClkpG8-bj95hhbL
03-05 18:10:04.082 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:10:04.082 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:10:04.082 I [cdm_engine.cpp(303):GenerateKeyRequest] session_id = sid5, key_set_id = <empty>, license_type = Streaming
03-05 18:10:04.122 I [cdm_engine.cpp(1089):IsSecurityLevelSupported] level = L1
03-05 18:10:04.688 I [cdm_engine.cpp(261):CloseSession] session_id = sid4
03-05 18:10:04.689 I [cdm_engine.cpp(261):CloseSession] session_id = sid5
03-05 18:10:04.695 I [(0):] L3 Terminate.
03-05 18:10:04.695 I [oemcrypto_adapter_dynamic.cpp(897):Level1Terminate] L1 Terminate
03-05 18:14:01.668 I [(0):] Level3 Library 28613 May  1 2023 06:32:58
03-05 18:14:01.668 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:14:01.668 I [oemcrypto_adapter_dynamic.cpp(837):Initialize] Level 3 Build Info (v18): {"soc_vendor":"L3_28613","soc_model":"ARM 64 bit","ta_ver":"18.1.0+May  1 2023_06:32:58_","uses_opk":false,"tee_os":"none","tee_os_ver":"0.0.0","form_factor":"L3","implementer":"Widevine","fused":false}
03-05 18:14:01.670 I [oemcrypto_adapter_dynamic.cpp(851):Initialize] L3 Initialized. Trying L1.
03-05 18:14:01.678 W [oemcrypto_adapter_dynamic.cpp(1013):LoadLevel1] Could not load L1 _oecc90.
03-05 18:14:01.678 W [oemcrypto_adapter_dynamic.cpp(1008):LoadLevel1] Could not load L1 _oecc27.
03-05 18:14:01.678 W [oemcrypto_adapter_dynamic.cpp(996):LoadLevel1] Could not load L1 _oecc105.
03-05 18:14:01.678 W [oemcrypto_adapter_dynamic.cpp(1005):LoadLevel1] Could not load L1 _oecc25.
03-05 18:14:01.678 W [oemcrypto_adapter_dynamic.cpp(1006):LoadLevel1] Could not load L1 _oecc24.
03-05 18:14:01.678 W [oemcrypto_adapter_dynamic.cpp(1007):LoadLevel1] Could not load L1 _oecc26.
03-05 18:14:01.679 W [oemcrypto_adapter_dynamic.cpp(1039):LoadLevel1] Could not load L1 _oecc23.
03-05 18:14:01.679 W [oemcrypto_adapter_dynamic.cpp(1041):LoadLevel1] Could not load L1 _oecc81.
03-05 18:14:01.679 W [oemcrypto_adapter_dynamic.cpp(1021):LoadLevel1] Could not load L1 _oecc06.
03-05 18:14:01.682 I [oemcrypto_adapter_dynamic.cpp(885):Initialize] Level 1 Build Info (v18): {"soc_vendor":"GOOGLE","soc_model":"GS101","ta_ver":"18.4.0+Nov 20 202315:03:28","uses_opk":true,"tee_os":"TRUSTY","tee_os_ver":"0_0","form_factor":"PHONE+TABLET","implementer":"WIDEVINE","is_factory_build":"false","fused":true,"is_debug":false}
03-05 18:14:01.683 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:14:01.683 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:14:01.688 I [cdm_usage_table.cpp(203):RestoreTable] Found usage table to restore: entry_count = 0
03-05 18:14:01.694 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:14:01.696 E [wv_content_decryption_module.cpp(563):GetCurrentMetricsInternal] Cdm Identifier not found
03-05 18:14:01.698 E [wv_content_decryption_module.cpp(646):CloseCdm] Cdm Identifier not found
03-05 18:14:01.700 I [(0):] L3 Terminate.
03-05 18:14:01.700 I [oemcrypto_adapter_dynamic.cpp(897):Level1Terminate] L1 Terminate
03-05 18:38:20.437 I No hidl drm factories found
03-05 18:38:20.438 E Failed to find passthrough drm factories
03-05 18:38:20.441 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:38:20.441 I [oemcrypto_adapter_dynamic.cpp(837):Initialize] Level 3 Build Info (v18): {"soc_vendor":"L3_28613","soc_model":"ARM 64 bit","ta_ver":"18.1.0+May  1 2023_06:32:58_","uses_opk":false,"tee_os":"none","tee_os_ver":"0.0.0","form_factor":"L3","implementer":"Widevine","fused":false}
03-05 18:38:20.441 I [(0):] Level3 Library 28613 May  1 2023 06:32:58
03-05 18:38:20.444 I [oemcrypto_adapter_dynamic.cpp(851):Initialize] L3 Initialized. Trying L1.
03-05 18:38:20.457 W [oemcrypto_adapter_dynamic.cpp(996):LoadLevel1] Could not load L1 _oecc105.
03-05 18:38:20.457 W [oemcrypto_adapter_dynamic.cpp(1005):LoadLevel1] Could not load L1 _oecc25.
03-05 18:38:20.457 W [oemcrypto_adapter_dynamic.cpp(1006):LoadLevel1] Could not load L1 _oecc24.
03-05 18:38:20.457 W [oemcrypto_adapter_dynamic.cpp(1007):LoadLevel1] Could not load L1 _oecc26.
03-05 18:38:20.457 W [oemcrypto_adapter_dynamic.cpp(1008):LoadLevel1] Could not load L1 _oecc27.
03-05 18:38:20.457 W [oemcrypto_adapter_dynamic.cpp(1013):LoadLevel1] Could not load L1 _oecc90.
03-05 18:38:20.457 W [oemcrypto_adapter_dynamic.cpp(1021):LoadLevel1] Could not load L1 _oecc06.
03-05 18:38:20.457 W [oemcrypto_adapter_dynamic.cpp(1039):LoadLevel1] Could not load L1 _oecc23.
03-05 18:38:20.457 W [oemcrypto_adapter_dynamic.cpp(1041):LoadLevel1] Could not load L1 _oecc81.
03-05 18:38:20.462 I [oemcrypto_adapter_dynamic.cpp(885):Initialize] Level 1 Build Info (v18): {"soc_vendor":"GOOGLE","soc_model":"GS101","ta_ver":"18.4.0+Nov 20 202315:03:28","uses_opk":true,"tee_os":"TRUSTY","tee_os_ver":"0_0","form_factor":"PHONE+TABLET","implementer":"WIDEVINE","is_factory_build":"false","fused":true,"is_debug":false}
03-05 18:38:20.462 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:38:20.463 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:38:21.678 I [cdm_usage_table.cpp(203):RestoreTable] Found usage table to restore: entry_count = 0
03-05 18:38:21.692 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:38:21.703 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:38:21.703 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:38:21.704 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:38:21.707 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:38:21.708 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:38:21.709 I [cdm_engine.cpp(216):OpenSession] New session: session_id = sid6
03-05 18:38:21.710 I [cdm_engine.cpp(1050):QueryOemCryptoSessionId] session_id = sid6
03-05 18:38:21.712 I [cdm_engine.cpp(955):QuerySessionStatus] session_id = sid6
03-05 18:38:21.713 I [cdm_engine.cpp(2264):SetPlaybackId] session_id = sid6, playback_id = Zd5nElDfUXhEsQn0
03-05 18:38:21.726 I [cdm_engine.cpp(303):GenerateKeyRequest] session_id = sid6, key_set_id = <empty>, license_type = Streaming
03-05 18:38:21.726 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:38:21.726 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:38:21.789 I [cdm_engine.cpp(1089):IsSecurityLevelSupported] level = L1
03-05 18:38:21.830 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:38:21.831 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:38:21.831 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:38:21.832 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:38:21.832 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:38:21.833 I [cdm_engine.cpp(216):OpenSession] New session: session_id = sid7
03-05 18:38:21.833 I [cdm_engine.cpp(1050):QueryOemCryptoSessionId] session_id = sid7
 03-05 18:38:21.834 I [cdm_engine.cpp(955):QuerySessionStatus] session_id = sid7
03-05 18:38:21.835 I [cdm_engine.cpp(2264):SetPlaybackId] session_id = sid7, playback_id = Zd5nElDfUXhEsQn0
03-05 18:38:21.836 I [cdm_engine.cpp(303):GenerateKeyRequest] session_id = sid7, key_set_id = <empty>, license_type = Streaming
03-05 18:38:21.837 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:38:21.837 I [file_utils.cpp(38):Exists] stat failed: ENOENT
03-05 18:38:21.869 I [cdm_engine.cpp(1089):IsSecurityLevelSupported] level = L1
03-05 18:38:21.869 I [cdm_engine.cpp(955):QuerySessionStatus] session_id = sid7
============================== End of DRM Plugin Log ==============================
at android.media.MediaDrm.provideKeyResponse(Native Method)
at com.google.android.exoplayer2.drm.FrameworkMediaDrm.provideKeyResponse(FrameworkMediaDrm.java:247)
at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(DefaultDrmSession.java:507)
at com.google.android.exoplayer2.drm.DefaultDrmSession.access$100(DefaultDrmSession.java:61)
at com.google.android.exoplayer2.drm.DefaultDrmSession$ResponseHandler.handleMessage(DefaultDrmSession.java:584)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.os.HandlerThread.run(HandlerThread.java:68)`

### Media

The media url is sent to the email

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by bartmejia18** [comment]
Thank you very much for the reply. 

What seems curious to me is if it were a key ID error, there would be no playback on any device, but we have only detected the error on a Google Pixel 6 Pro with Android 14 and on a Samsung S23 ultra with Android 14. In addition, there is no playback. in the emulators mentioned above (Android 14.0 UpsideDownCake, Android 14.0 UpsideDownCakePrivacySandbox, Android 14 VanillaIceCream)

**Comment by rrfrias** [comment]
When trying to repro, we are unable to acquire a license. The license requests are being rejected with an HTTP 403

**Comment by YoucefBen47** [comment]
Hi @bartmejia18 @rrfrias was there a solution for this issue? We use the React Native Bitmovin player and we started getting this error in our React Native app when playing some movies on the Pixel 7 Pro Android 14:
```
{“code”: 1001, “message”: “A general error occurred: ERROR_DRM_UNKNOWN: ERROR_DRM_UNKNOWN
cdm err: 1, oem err: 29, ctx: 23
============================== Beginning of DRM Plugin Log ==============================
05-22 18:23:55.785 I No hidl drm factories found
05-22 18:23:55.809 E Failed to find passthrough drm factories
05-22 18:25:14.816 I No hidl drm factories found
05-22 18:25:14.823 E Failed to find passthrough drm factories
05-22 18:25:35.728 I No hidl drm factories found
05-22 18:25:35.730 E Failed to find passthrough drm factories
05-22 18:37:03.641 I No hidl drm factories found
05-22 18:37:03.656 E Failed to find passthrough drm factories
05-22 18:37:05.606 I [cdm_engine.cpp(382):AddKey] session_id = sid6, key_set_id =
05-22 18:37:05.736 E [crypto_session.cpp(1804):Decrypt] OEMCrypto_DecryptCENC failed: oec_session_id = 3, security_level = Default, status = 29
05-22 18:37:05.736 E [cdm_session.cpp(734):Decrypt] Decryption failed: sid = sid6, status = 1
05-22 18:37:05.860 I [cdm_engine.cpp(261):CloseSession] session_id = sid6
05-22 18:37:21.830 I No hidl drm factories found
05-22 18:37:21.834 E Failed to find passthrough drm factories
05-22 18:37:22.127 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:37:22.129 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:37:22.129 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:37:22.130 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:37:22.130 I [cdm_engine.cpp(216):OpenSession] New session: session_id = sid7
05-22 18:37:22.130 I [cdm_engine.cpp(1032):QueryOemCryptoSessionId] session_id = sid7
05-22 18:37:22.134 I [cdm_engine.cpp(937):QuerySessionStatus] session_id = sid7
05-22 18:37:22.135 I [cdm_engine.cpp(2218):SetPlaybackId] session_id = sid7, playback_id = k8Tz9yNhan_OsT-C
05-22 18:37:22.139 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:37:22.139 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:37:22.139 I [cdm_engine.cpp(303):GenerateKeyRequest] session_id = sid7, key_set_id = , license_type = Streaming
05-22 18:37:22.214 I [cdm_engine.cpp(1043):IsSecurityLevelSupported] level = L1
05-22 18:37:22.491 I [cdm_engine.cpp(1043):IsSecurityLevelSupported] level = L1
05-22 18:37:22.492 I [cdm_engine.cpp(937):QuerySessionStatus] session_id = sid7
05-22 18:37:22.634 I [cdm_engine.cpp(382):AddKey] session_id = sid7, key_set_id =
05-22 18:37:32.871 I [cdm_engine.cpp(261):CloseSession] session_id = sid7
05-22 18:37:39.040 I No hidl drm factories found
05-22 18:37:39.042 E Failed to find passthrough drm factories
05-22 18:37:39.220 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:37:39.221 I [cdm_engine.cpp(216):OpenSession] New session: session_id = sid8
05-22 18:37:39.221 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:37:39.221 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:37:39.221 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:37:39.221 I [cdm_engine.cpp(1032):QueryOemCryptoSessionId] session_id = sid8
05-22 18:37:39.225 I [cdm_engine.cpp(937):QuerySessionStatus] session_id = sid8
05-22 18:37:39.226 I [cdm_engine.cpp(2218):SetPlaybackId] session_id = sid8, playback_id = k3ikybzdFZ8wVzpd
05-22 18:37:39.228 I [cdm_engine.cpp(303):GenerateKeyRequest] session_id = sid8, key_set_id = , license_type = Streaming
05-22 18:37:39.228 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:37:39.228 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:37:39.310 I [cdm_engine.cpp(1043):IsSecurityLevelSupported] level = L1
05-22 18:37:39.414 I [cdm_engine.cpp(1043):IsSecurityLevelSupported] level = L1
05-22 18:37:39.419 I [cdm_engine.cpp(937):QuerySessionStatus] session_id = sid8
05-22 18:37:39.574 I [cdm_engine.cpp(382):AddKey] session_id = sid8, key_set_id =
05-22 18:37:39.699 E [crypto_session.cpp(1804):Decrypt] OEMCrypto_DecryptCENC failed: oec_session_id = 3, security_level = L3, status = 29
05-22 18:37:39.699 E [cdm_session.cpp(734):Decrypt] Decryption failed: sid = sid8, status = 1
05-22 18:37:39.938 I [cdm_engine.cpp(261):CloseSession] session_id = sid8
05-22 18:37:53.996 I No hidl drm factories found
05-22 18:37:54.004 E Failed to find passthrough drm factories
05-22 18:37:54.185 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:37:54.185 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:37:54.186 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:37:54.186 I [cdm_engine.cpp(216):OpenSession] New session: session_id = sid9
05-22 18:37:54.186 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:37:54.186 I [cdm_engine.cpp(1032):QueryOemCryptoSessionId] session_id = sid9
05-22 18:37:54.190 I [cdm_engine.cpp(937):QuerySessionStatus] session_id = sid9
05-22 18:37:54.191 I [cdm_engine.cpp(2218):SetPlaybackId] session_id = sid9, playback_id = Ch12asMh-Tb6MfLa
05-22 18:37:54.196 I [cdm_engine.cpp(303):GenerateKeyRequest] session_id = sid9, key_set_id = , license_type = Streaming
05-22 18:37:54.196 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:37:54.196 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:37:54.262 I [cdm_engine.cpp(1043):IsSecurityLevelSupported] level = L1
05-22 18:37:54.263 I [cdm_engine.cpp(937):QuerySessionStatus] session_id = sid9
05-22 18:37:54.356 I [cdm_engine.cpp(1043):IsSecurityLevelSupported] level = L1
05-22 18:37:54.472 I [cdm_engine.cpp(382):AddKey] session_id = sid9, key_set_id =
05-22 18:37:54.547 E [cdm_session.cpp(734):Decrypt] Decryption failed: sid = sid9, status = 1
05-22 18:37:54.547 E [crypto_session.cpp(1804):Decrypt] OEMCrypto_DecryptCENC failed: oec_session_id = 3, security_level = L3, status = 29
05-22 18:37:54.682 I [cdm_engine.cpp(261):CloseSession] session_id = sid9
05-22 18:38:18.788 I No hidl drm factories found
05-22 18:38:18.798 E Failed to find passthrough drm factories
05-22 18:38:19.068 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:38:19.069 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:38:19.069 I [cdm_engine.cpp(1032):QueryOemCryptoSessionId] session_id = sid10
05-22 18:38:19.069 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:38:19.069 I [cdm_engine.cpp(216):OpenSession] New session: session_id = sid10
05-22 18:38:19.074 I [cdm_engine.cpp(937):QuerySessionStatus] session_id = sid10
05-22 18:38:19.075 I [cdm_engine.cpp(2218):SetPlaybackId] session_id = sid10, playback_id = ayC1ui8WKPCxQSam
05-22 18:38:19.078 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:38:19.078 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:38:19.078 I [cdm_engine.cpp(303):GenerateKeyRequest] session_id = sid10, key_set_id = , license_type = Streaming
05-22 18:38:19.148 I [cdm_engine.cpp(1043):IsSecurityLevelSupported] level = L1
05-22 18:38:19.149 I [cdm_engine.cpp(937):QuerySessionStatus] session_id = sid10
05-22 18:38:19.255 I [cdm_engine.cpp(1043):IsSecurityLevelSupported] level = L1
05-22 18:38:19.503 I [cdm_engine.cpp(382):AddKey] session_id = sid10, key_set_id =
05-22 18:38:37.707 I No hidl drm factories found
05-22 18:38:37.709 E Failed to find passthrough drm factories
05-22 18:38:37.948 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:38:37.950 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:38:37.950 I [cdm_engine.cpp(216):OpenSession] New session: session_id = sid11
05-22 18:38:37.950 I [cdm_engine.cpp(1032):QueryOemCryptoSessionId] session_id = sid11
05-22 18:38:37.950 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:38:37.955 I [cdm_engine.cpp(937):QuerySessionStatus] session_id = sid11
05-22 18:38:37.956 I [cdm_engine.cpp(2218):SetPlaybackId] session_id = sid11, playback_id = UB8gMrvn33MERKcS
05-22 18:38:37.957 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:38:37.957 I [cdm_engine.cpp(303):GenerateKeyRequest] session_id = sid11, key_set_id = , license_type = Streaming
05-22 18:38:37.957 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:38:38.026 I [cdm_engine.cpp(1043):IsSecurityLevelSupported] level = L1
05-22 18:38:38.027 I [cdm_engine.cpp(937):QuerySessionStatus] session_id = sid11
05-22 18:38:38.136 I [cdm_engine.cpp(1043):IsSecurityLevelSupported] level = L1
05-22 18:38:38.237 I [cdm_engine.cpp(382):AddKey] session_id = sid11, key_set_id =
05-22 18:42:37.657 I No hidl drm factories found
05-22 18:42:37.681 E Failed to find passthrough drm factories
05-22 18:42:37.940 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:42:37.943 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:42:37.943 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:42:37.943 I [cdm_engine.cpp(216):OpenSession] New session: session_id = sid12
05-22 18:42:37.945 I [cdm_engine.cpp(1032):QueryOemCryptoSessionId] session_id = sid12
05-22 18:42:37.958 I [cdm_engine.cpp(937):QuerySessionStatus] session_id = sid12
05-22 18:42:37.962 I [cdm_engine.cpp(2218):SetPlaybackId] session_id = sid12, playback_id = E3OSvuOaFJdnxmeH
05-22 18:42:37.967 I [cdm_engine.cpp(303):GenerateKeyRequest] session_id = sid12, key_set_id = , license_type = Streaming
05-22 18:42:37.967 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:42:37.967 I [file_utils.cpp(38):Exists] stat failed: ENOENT
05-22 18:42:38.059 I [cdm_engine.cpp(1043):IsSecurityLevelSupported] level = L1
05-22 18:42:38.061 I [cdm_engine.cpp(937):QuerySessionStatus] session_id = sid12
05-22 18:42:38.253 I [cdm_engine.cpp(1043):IsSecurityLevelSupported] level = L1
05-22 18:42:39.061 I [cdm_engine.cpp(382):AddKey] session_id = sid12, key_set_id =
05-22 18:42:39.142 E [crypto_session.cpp(1804):Decrypt] OEMCrypto_DecryptCENC failed: oec_session_id = 5, security_level = Default, status = 29
05-22 18:42:39.142 E [cdm_session.cpp(734):Decrypt] Decryption failed: sid = sid12, status = 1
============================== End of DRM Plugin Log ==============================”, “name”: “onPlayerError”, “timestamp”: 1716399759483}
```

**Comment by rrfrias** [comment]
@YoucefBen47 This looks like a different issue. Can you open a new github tracker?

> Hi @bartmejia18 @rrfrias was there a solution for this issue?

We were not able to reproduce or root cause the original issue.
