### ISSUE TITLE
media codec

### ISSUE THREAD

**Issue by inspeero** [androidx/media#1153]
### Version

Media3 1.2.1

### More version details

android.media.MediaCodec$CodecException: Error 0xffffffff
android.media.MediaCodec.error_neg_1

getting this error while playing drm video in android version 13

### Devices that reproduce the issue

Redmi note 9 pro

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Play drm video

### Expected result

play drm content

### Actual result

Throwing exception

### Media

NA

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by tianyif** [comment]
Hi @inspeero,

We haven't received your bug report, could you please email it to us? Also, it will be really helpful if you can share the media with us, you can include the media in the email to [android-media-github@google.com](mailto:android-media-github@google.com), if it can not be disclosed publicly.
