### ISSUE TITLE
I want to reduce the size of the video by using media3 transformer library

### ISSUE THREAD

**Issue by NagaMoto57** [androidx/media#1154]
Hi Team,

I want to reduce the size of the video by using media3 transformer library. I tried by setting the Presentation.createForHeight(360). Still I could see the size is more, when compare with other library compression. 

As I compared both the compressed videos (media3 transformed video and other library compressed video), I could notice the Data rate and Total bitrate is high in media3 transformer library.

Please suggest what are the approaches, I need to do to reduce the video size EX : Bitrate, etc..

I am using androidx.media3:media3-transformer:1.2.1, androidx.media3:media3-effect:1.2.1 and androidx.media3:media3-common:1.2.1

**Comment by droid-girl** [comment]
Hi @NagaMoto57,
You can set bitrate with VideoEncoderSettings when creating `Transformer` by setting `EncoderFactory` like this:  

```
transformerBuilder.setEncoderFactory(
          new DefaultEncoderFactory.Builder(/* context= */ this )
              .setRequestedVideoEncoderSettings(
                  new VideoEncoderSettings.Builder()
                      .setBitrate(BITRATE_VALUE)
                      .build())
              .build());
```

**Comment by NagaMoto57** [comment]
Hi Team,

Thanks for the update, Can you please provide the information for below.
1. Along with passing height and bitrate what else I can do to reduce the video size without losing quality much using the media3 library. 
2. Is their any approach to know what should be the bitrate value to set for losing the size.

Thanks.

**Comment by droid-girl** [comment]
@ychaparov could you help here?

**Comment by claincly** [comment]
> Along with passing height and bitrate what else I can do to reduce the video size without losing quality much using the media3 library.

`VideoEncoderSettings` also supports setting encoding profile and level. Higher profile enables more advanced encoding techniques so it's likely you can reduce video size there, but the caveat is, a device may not support the higher encoding profile.

> Is their any approach to know what should be the bitrate value to set for losing the size.

What we have used internally previously was a method called *Kush gauge*, it's a crude way to calculating the bitrate to use given resolution and frame rate. It's basically

$$
\text{Bitrate} = \text{width}\times\text{height}\times\text{frame rate}\times\text{coefficient}
$$

Where you can tune the $\text{coefficient}$ to a specific quality. You can find more about how to tune this coefficient online.

**Comment by ychaparov** [comment]
Hi @NagaMoto57 !

We're aware of some issues with the output quality of Transformer, and we'd like your feedback to prioritize the most visible issues first.

Can you please share more details about the videos you're trying to process?

Information such as codec, width, height, SDR or HDR, etc. would be helpful. You can get this via `ffmpeg` or MediaInfo (also available online https://mediaarea.net/MediaInfoOnline ).

Were those videos recorded on the phone running Transformer or do they come from another source?

Is there anything specific about the videos? (animated content? Social media content? Video with text overlay?)
