### ISSUE TITLE
Black screen on ABR changes

### ISSUE THREAD

**Issue by zubcoco** [androidx/media#1158]
### Version

Media3 main branch

### More version details

Issue appear with version 1.1.0 (OK with version 1.0.2)
Same on ExoPlayer, present on v2.19.0 and not with v.2.17.0

### Devices that reproduce the issue

Problem is on our Box Vantiva/Technicolor (broadcom) but also reproduced on 2 differents Sony TVs.

### Devices that do not reproduce the issue

Problem is not reproduced on Google TV, not on Nvidia Shield and not on Android Studio Emulator.
And also not reproduced on Samsung mobiles.

### Reproducible in the demo app?

Yes

### Reproduction steps

1. In the demo app, we need to set the initial bitrate estimate to 1 MBPs (to ensure the player will change profile after a while). I use the default band width meter that we can pass to the exoplayer builder.
2. Play the stream that I sent you by mail

### Expected result

The media start with a low profile. After a while it play with the highest profile and the transition should be fluent.

### Actual result

The media start with a low profile. After a while it play with the highest profile but during the transition we have a black screen.

### Media

I'll send you the media to test.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by zubcoco** [comment]
Hello,
I've found the problematic commit: https://github.com/androidx/media/commit/8a73d8d3fe2290a11c86a414dd000632589b6215.

If I compile a version and I revert all lines of this commit, the problem is solve.

Would you like me to do some special tests to help your analysis?

**Comment by zubcoco** [comment]
The problem is in NalUnitUtil class, in parseSpsNalUnitPayload function.
When I comment these lines :
`      if (data.readBit()) { // overscan_info_present_flag
        data.skipBit(); // overscan_appropriate_flag
      }
      if (data.readBit()) { // video_signal_type_present_flag
        data.skipBits(3); // video_format
        colorRange =
            data.readBit() ? C.COLOR_RANGE_FULL : C.COLOR_RANGE_LIMITED; // video_full_range_flag
        if (data.readBit()) { // colour_description_present_flag
          int colorPrimaries = data.readBits(8); // colour_primaries
          int transferCharacteristics = data.readBits(8); // transfer_characteristics
          data.skipBits(8); // matrix_coeffs

          colorSpace = ColorInfo.isoColorPrimariesToColorSpace(colorPrimaries);
          colorTransfer =
              ColorInfo.isoTransferCharacteristicsToColorTransfer(transferCharacteristics);
        }
      }
`
the problem no longer appears.

**Comment by zubcoco** [comment]
Mail sent with requested informations.
Thanks a lot.

**Comment by tonihei** [comment]
Thanks. Assuming you still have the local checkout, could you try to comment out all four `maybeSet...` calls in this method: https://github.com/androidx/media/blob/d13a0f4ec62ca092b79746a5725b62a3244cc5b4/libraries/common/src/main/java/androidx/media3/common/util/MediaFormatUtil.java#L256 to see if that fixes your problem?

**Comment by zubcoco** [comment]
No, the problem stills occur with these commented lines.

**Comment by tonihei** [comment]
Thanks for the confirmation and sharing the bugreports! I think I see the problem now and will share another fix proposal soon (sorry for constantly asking to test things out, but I don't have a reproduction setup myself).

**Comment by tonihei** [comment]
The commit linked above should fix the problem. Could you verify this again with your setup? Thanks!

**Comment by zubcoco** [comment]
Yes, if I compile on the main branch I don't see the problem. Thanks a lot !
