### ISSUE TITLE
Video is not filling Player view when there is Resolution drop in a playlist [Amazon Fire Stick]

### ISSUE THREAD

**Issue by ShrirakshaRShetty** [androidx/media#1161]
Video is not filling Player view when VideoSize is changed in a playlist [Amazon Fire Stick]

I'm using media3 Exoplayer player (androidx.media3:media3-exoplayer:1.2.1) building a media player android TV app, however, if there is a playlist of several videos with different resolutions I see a weird behaviour on the display explained below. **Only Happens on Amazon FireStick (FireOs 6 & 7), works good on other Android TVs**

- All Videos have 16:9 ratio

- Some Videos have resolution of 1920x1080 and others are say 720x480.

- When ExoPlayer starts to play the playlist seems it locks the player view to the first frame size which is 1920x1080 for instance.It is working fine until now.So when next video is played and  if it is of lower resolution say 720x480, it occupies only a part of the screen and the last frame of the previous video is still filling the rest of the screen as shown in the following image. And the the second video will start to play in that small section.
![CN5yw](https://github.com/androidx/media/assets/162569187/7c20c858-425d-4d4c-9039-6093471e05dc)

This exact issue is mentioned here but no  response yet
Stackoverflow link : https://stackoverflow.com/questions/74888540/video-is-not-filling-exoplayer-view-when-videosize-is-changed-in-a-playlist-ama

**Comment by ShrirakshaRShetty** [comment]
Every time when next l=channel is clicked createPlayer() function is hit.
    
  
    @OptIn(UnstableApi::class)
    private fun createPlayer() {

        releasePlayer()
        if (player == null) {
            trackSelector = DefaultTrackSelector(context)
            player = ExoPlayer.Builder(context)
                .setTrackSelector(trackSelector!!)
                .build()
            player?.addAnalyticsListener(EventLogger(trackSelector))
            player?.addListener(this)
            binding.playerView.player = player
        }

        loadMediaItem()
        showPlayer()
    }

    private fun loadMediaItem() {
        val mediaItem = MediaItem.fromUri(channel?.videoSourceURL ?: "")
        player?.setMediaItem(mediaItem)
        player?.prepare()
        player?.play()
    }

    private fun showPlayer() {
        binding.playerView.visibility = View.VISIBLE
        binding.tvPlayerError.visibility = View.GONE
        binding.pbPlayerProgress.visibility = View.VISIBLE
    }

    private fun releasePlayer() {
        player?.release()
        player = null
        trackSelector = null
    }

**Comment by tianyif** [comment]
Hi @ShrirakshaRShetty,

Thanks for reporting! Given this issue is only reproducible on Amazon device, we highly recommend you to report a bug to Amazon, as currently we can hardly see it is a library problem. I'm labelling this as a device specific issue for now.
