### ISSUE TITLE
Support for Media3 notification controls

### ISSUE THREAD

**Issue by devedelie** [androidx/media#1163]
My app is targeting API 34 and I'm currently migrating to Media3. I was looking for answer all over the web, but couldn't find a concrete solution regarding the setup of media-notification with Media3.
Many answers out there are from 2022, and probably things has changed since then.
I have noticed some differences between the media notification on devices running on Android 12 and below, and Android 13 and above, which is also a big issue for many devs and I was wondering if a **little guide is planned to be released soon** ?

**With Default Setup:**
While I don't set any notification parameters and use the default API setup by Media3 and MediaLibraryService, the notification shows a progress bar (seek-bar) on devices with Android 13 and above, but on the other hand, on Android 12 and below, it shows only 3 controls
 [ Prev | play/pause | next ] but without a progress bar (This was also reproduced with UAMP demo app).
 Is there any special parameters or setup for some API levels in order to show seek bar on devices running on Android 12 and below ?
 Android14 on the left vs Android 10 on the right:
 
![Screenshot_20240308_095554_UAMP](https://github.com/androidx/media/assets/46728015/ad1e047b-7562-4a83-a2dd-c806ec343eae)

 
 **With Custom Actions**
 Another issue, is when I extend [DefaultMediaNotificationProvider](https://developer.android.com/reference/androidx/media3/session/DefaultMediaNotificationProvider) , and add custom action (ex: like/unlike button), the behavior is different again, as on Android 13 and above the media controls are derived from [PlaybackState](https://developer.android.com/about/versions/13/behavior-changes-13#playback-controls), so the question is, should I create a Compat setup for old devices prior Android 13 and create a custom notification ?
Because I saw in some forums that Media3 is handling all API levels with media notification, so I'm a bit confused.

I was following the answer by @marcbaechinger  on #216 , #38 & #213 but couldn't solve this issue.

**Comment by tonihei** [comment]
Thanks for the analysis. I think the most important thing to highlight is that the media notifications just look different on different Android versions. Media3 does its best to align the user-visible output across versions, but the actual notification design changed a lot over the years and they will all be slightly different no matter what you do.

> Is there any special parameters or setup for some API levels in order to show seek bar on devices running on Android 12 and below ?

When I use the Media3 session demo app on Android 10, the notification is shown with a seek bar by default. I'm not sure what's different in your app, but one thing to check is whether you allow the media notification controller access to all relevant `Player.Commands` in `MediaSession.Callback.onConnect`. If you can reproduce this issue, could you provide more detailed reproduction steps (ideally in the demo app) for us to check if everything is working as intended?

> extend [DefaultMediaNotificationProvider](https://developer.android.com/reference/androidx/media3/session/DefaultMediaNotificationProvider) , and add custom action

Media3 handles all the compat layers for you and there should ideally be no need to add custom buttons in the `DefaultMediaNotificationProvider` directly. Instead please declare the custom commands and the custom layouts as explained [here](https://developer.android.com/media/media3/session/control-playback?_gl=1*1x7ewtf*_up*MQ..*_ga*NjkwOTc0MzM3LjE3MTAxNTE0Nzc.*_ga_6HH9YJMN9M*MTcxMDE1MTQ3Ny4xLjAuMTcxMDE1MTQ3Ny4wLjAuMA..#commands) and Media3 will take care of setting the appropriate values depending on the API version.

**Comment by devedelie** [comment]
Thanks for replying @tonihei   (-:

Well, the different look on each android device/version is not an issue at all for me.

> could you provide more detailed reproduction steps (ideally in the demo app)

Technically speaking, the images I uploaded, were taken from the UAMP demo app "as-is" on the 'Media3' branch (no changes at all).
The devices I was using with an older API versions were Samsung's: Note 9(Android 10) & Galaxy 8+(Android 8), but for verification, there was no seek-bar also when running the app on an Emulator with Pixel device on API 26 for example, while before, with `MediaBrowserServiceCompat` and `NotificationManager` I had the seek-bar on all devices and emulators.
Is there any other demo app rather than UAMP that I was missing ?

> there should ideally be no need to add custom buttons in the DefaultMediaNotificationProvider

Yes I understand, and at first I was doing exactly as explained on the url you shared above, but I needed to control the appearance of the favorite icon(on/off), so at first I tried with calling for `player.replaceMediaItem(currentIndex, newItem)` which for my knowledge is supposed to refresh the notification (whenever the url wasn't changed) but it worked only on old devices, so I was extending `'DefaultMediaNotificationProvider` in order to switch the favorite icon regarding the Rating value of the current `MediaMetadata` and called for `setCustomLayout()` which did the job.
Maybe it is not the right approach, but for sure I was struggling with it for a while now.
This is the reason I'm not releasing my app to production, unless I'll find a solution for the media notification.

**Comment by tonihei** [comment]
> Is there any other demo app rather than UAMP that I was missing ?

I was actually talking about the Media3 Session demo app that is part of this repository :) See https://github.com/androidx/media/tree/release/demos/session.  

UAMP is maintained by the Android Developer Relations team and may not have been updated to the latest version or may have bugs. When it comes to finding issues, it's probably best to try our session demo app first because we use it regularly to verify the default behavior of our APIs is working as it should. 

> in order to switch the favorite icon regarding the Rating value of the current MediaMetadata and then called for setCustomLayout() which did the job for me.

This sounds like the right approach and if I understand correctly it also works as you would expect? This is also the recommended approach I linked above from our [guide pages](https://developer.android.com/media/media3/session/control-playback?_gl=1*1x7ewtf*_up*MQ..*_ga*NjkwOTc0MzM3LjE3MTAxNTE0Nzc.*_ga_6HH9YJMN9M*MTcxMDE1MTQ3Ny4xLjAuMTcxMDE1MTQ3Ny4wLjAuMA..#display-controls). I see though that our guide doesn't really explain nicely how to toggle buttons in response to a user interaction, so maybe we should explain that a bit better. We also have plans to make the handling of toggle buttons a bit easier by declaring them once so that you don't need complicated logic to listen to updates.

**Comment by devedelie** [comment]
Thanks again @tonihei , I tried also with the demo app, but having the same issue with no seek-bar as you can see :

![Untitled](https://github.com/androidx/media/assets/46728015/f33637b5-bbeb-4f31-8052-fc9c63abdfef)

It was tested on the same devices I mentioned above including the Pixel emulator.

**Comment by tonihei** [comment]
I'm afraid I can't reproduce this still. I tested Media3 1.2.0 / 1.3.0 and the main branch on a Pixel 3 emulator running API 29.

You said it reproduces on a Pixel emulator for you. Could you highlight exactly which API version this emulator is running and which Media3 version you are testing with?

**Comment by devedelie** [comment]
> Could you highlight exactly which API version this emulator is running and which Media3 version you are testing with?

Sure, I was using Pixel 4XL and also Pixel 6 Pro emulators on API 26, both had no seek-bar. 
Same issue on Media3 version" 1.2.1  and 1.3.0
