### ISSUE TITLE
Call `ExoPlayer#setVideoEffects(List<Effect>)` may cause playbackState stuck on buffering state after seeking(both forward/backward)

### ISSUE THREAD

**Issue by how8570** [androidx/media#1166]
### Version

Media3 pre-release (alpha, beta or RC not in this list)

### More version details

- released `1.3.0-rc01` on my custom app
- [ExoPlayer release-v2 branch](https://github.com/google/ExoPlayer) demo app
  - when testing, last commit on branch is [243e6c29](https://github.com/google/ExoPlayer/commit/243e6c292ac88307263e3974152d125345c3e5c4)

### Devices that reproduce the issue

CCwGTV - Android 12

### Devices that do not reproduce the issue

(Not found yet)

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Edit demo app, go `PlayerActivity.java`(com.google.android.exoplayer2.demo) and edit it.
2. setting player effects like this (line 288~292)
   ```
   if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
        ArrayList<Effect> effects = new ArrayList<>();
        // effects.add(new Brightness(0.0f)); // or put any effects here
        player.setVideoEffects(effects);
   }
   ```
    ![image](https://github.com/androidx/media/assets/16633155/91012583-cf9e-4aef-ad2e-d09bdd5ec614)

3. Build demo app and launch, pick any one video to play.
4. Seek forward/backward (via Player controller view UI on it), it stuck on buffering state.

---

I was created a [ExoPlayer issue #11038](https://github.com/google/ExoPlayer/issues/11038) before,
and I get the workaround to adding this part of code (`player.setVideoEffects({empty_list})`) to workaround it.

But since that may casue seeking stuck,
dose there another workaround can solve both of those issue?

### Expected result

on Step (4.), Expected it will buffer and play, won't stuck.

### Actual result

stuck on buffering state like this.
![image](https://github.com/androidx/media/assets/16633155/07d953ef-7d56-4b9d-a8af-8efc163ccb47)

### Media

All videos on demo app probably can reproduce.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by how8570-syno-dev** [comment]
this issue seems deuplicate with https://github.com/androidx/media/issues/1139 ?

**Comment by how8570** [comment]
this issue seems deuplicate with https://github.com/androidx/media/issues/1139 ?

**Comment by claincly** [comment]
Thanks for bringing up the issue. I tried to reproduce the issue with a `Contrast` effect and some `TextOverlay`, I tried aggressively tapping the seek buttons and the scrub bars, but I wasn't able to reproduce this. Do you see this freeze only when using multiple effects, or when using complexed effects?

**Comment by how8570** [comment]
I just put empty Effect list can repoduce that, no need add lots effects, 

But I'm not tring this on mobile yet, maybe this issue is only can reproduce on TV?

**Comment by steelbytes** [comment]
found the cause for me, see my comment https://github.com/androidx/media/issues/1139#issuecomment-1987724651

**Comment by steelbytes** [comment]
google has gone silent.  I think I'll fork and also comment out numberOfFramesToDropOnBecomingAvailable>0.  I prefer a plater error than a freeze.

**Comment by how8570** [comment]
Same here, but still not acceptable just a simply seeking make the player error 😢

**Comment by claincly** [comment]
Hey @how8570, we've recently pushed a patch, please see if it fixes your issue!

https://github.com/androidx/media/issues/1139

**Comment by how8570** [comment]
I already tried with this comment here XDD
https://github.com/androidx/media/issues/1139#issuecomment-2123812295

Or there is more futher chages on extreme cases?
(seeking forward/backward rapidly and repeatedly that one)
