### ISSUE TITLE
MediaSessionService Calls onDestroy When App Triggers onStop

### ISSUE THREAD

**Issue by DolaKrishnan08** [androidx/media#1167]
Version
Media3 1.2.1

Once User Select a Song I Initialize MediaController and start service to play music even in Background,
Now When I try to close the app The service should not stop but still need to run and player should continue to play.

But Actucally after initializing the MediaController in ACtivity The Service start to run, Now when I try to Close the App i can see onDestroy is being triggered in MediaSessionService.

```
Activity 
   private fun initializeController() {
        controllerFuture =
            MediaController.Builder(
                this,
                SessionToken(this, ComponentName(this, YourMusicService::class.java))
            ).buildAsync()
        controllerFuture.addListener({ setController() }, MoreExecutors.directExecutor())
    }

    override fun onStop() {
        super.onStop()
        releaseController()
    }

    private fun releaseController() {
        MediaController.releaseFuture(controllerFuture)
    }
    
    Service 
    class YourMusicService : MediaSessionService() {

    @Inject
    lateinit var mediaSession: MediaSession
    
    override fun onDestroy() {
    super.onDestroy()
      mediasession.run {
      player.release
      release
      }
    }
    
    }

**Comment by marcbaechinger** [comment]
Our session demo is behaving like you describe. When the app is removed from the recent tasks during playback, the service continues to play in the background as a foreground service.

There is a [section in the developer guide about the service lifecycle](https://developer.android.com/media/media3/session/background-playback#service-lifecycle) that explains how this is implemented. Take a look at `onTaskRemoved()` that isn't implemented in the code sample above.

If this doesn't help, can you please do a [bug report](https://developer.android.com/studio/debug/bug-report) right after you have terminated the app and then upload it here so we can take a look?  If you're unable to share bug reports or test content publicly, please send them to android-media-github@google.com using a subject in the format "Issue #1167". Please also update this issue to indicate you’ve done this.
