### ISSUE TITLE
Using MediaCodec PARAMETER_KEY_TUNNEL_PEEK parameters

### ISSUE THREAD

**Issue by zubcoco** [androidx/media#1169]
Currently, when we are using tunneled mode, when we do a seek in pause state, the player could not decode a video frame.
This is not a very good experience for users.

Since Android API level 31, there is a new parameter PARAMETER_KEY_TUNNEL_PEEK. This should fix the actual issue.

Here is the documentation :
 - https://developer.android.com/reference/android/media/MediaCodec#PARAMETER_KEY_TUNNEL_PEEK
 - https://source.android.com/docs/devices/tv/multimedia-tunneling#behavior

Is it planned to add this feature in a future version of media3 to enhance user experience ?

**Comment by tonihei** [comment]
According it its documentation, the default value of the parameter is already "enabled", see https://developer.android.com/reference/android/media/MediaCodec#PARAMETER_KEY_TUNNEL_PEEK (as you linked already). Are you saying that your device is not assuming this parameter is enabled by default? 

We may just set the parameter anyway if we cannot rely on the default, given we want this behavior in all cases.
