### ISSUE TITLE
Text tracks are not detected in latest versions

### ISSUE THREAD

**Issue by im12345dev** [androidx/media#1171]
### Version

Media3 main branch

### Devices that reproduce the issue

Any device

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Play the attached video
2. Search for Closed Captions tracks

### Expected result

Find 1 closed captions track

### Actual result

Migrating from ExoPlayer 2.11.8 to the latest MediaX 1.3.0 result in a lose of text tracks detection in a lot of streams, these text tracks are detected in ExoPlayer 2.11.8 but are not detected in the latest Media 1.3.0

### Media

https://www.dropbox.com/scl/fi/5xt9qx0dytr41nmbpk9uq/closed-captions-test.ts?rlkey=n0rp2s1i6376fr9liz5wckizq&dl=1

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by im12345dev** [comment]
Upon further investigating the issue, following https://github.com/google/ExoPlayer/issues/10175#issuecomment-1098206520 seems to resolve the issue, but it feels more of a hack then an actual solution

**Comment by tonihei** [comment]
Please see [this guide](https://developer.android.com/media/media3/exoplayer/troubleshooting?_gl=1*rq03ke*_up*MQ..*_ga*NTcxMjAxMzExLjE3MTAxNDgyMzg.*_ga_6HH9YJMN9M*MTcxMDE0ODIzNy4xLjAuMTcxMDE0ODIzOC4wLjAuMA..#why-are-subtitles-not-found-in-some-mpeg-ts-files), which works to enable the subtitles in your example stream.
