### ISSUE TITLE
Google assistant problem

### ISSUE THREAD

**Issue by Kyant0** [androidx/media#1173]
I can correctly play specific songs with Google assistant, but `onSetMediaItems` will also be called even if the search result is empty (but Google assistant still shows title which is not in my app, it's weird), I have to return `MediaItemsWithStartPosition`.

1. What should I do if there is no search result?
2. Google assistant doesn't call `onSearch` and `onGetSearchResult`, is this normal? It directly calls `onSetMediaItems`. Can you make `MediaItemsWithStartPosition` in `onSetMediaItems` nullable to interrupt the action (including the following play action)?

**Comment by Kyant0** [comment]
I shouldn't determine the number of songs in `Player`'s `handleSetMediaItems`, because it should also happens when playlist gets cleared. Even if I early return in this case, then the `play` will be called, and I can't control it.

**Comment by tonihei** [comment]
> Google assistant doesn't call onSearch and onGetSearchResult, is this normal? It directly calls onSetMediaItems.

This part is working as expected. `onSearch`/`onGetSearchResult` is used to **browse** the library without any immediate intent to play. Note that these values also don't have a `MediaItem` input. `onAddMediaItems` is used for new items that are supposed to be **added to the player** and it has a `MediaItem` input to define what should be played. (`MediaItem.RequestMetadata.searchQuery` will contain the search query, and you can also identify which controller is requesting this playback by checking the `ControllerInfo` parameter).

> Can you make MediaItemsWithStartPosition in onSetMediaItems nullable to interrupt the action (including the following play action)?

You can return a failed or cancelled future from `onSetMediaItems` to interrupt the action and prevent any further call to `play`. This should also address your follow-up comment. If you do everything inline, you could for example use `Futures.immediateFailedFuture(new UnsupportedOperationException())`, which is also what happens by default if you don't even implement the method.

> the search result is empty 

This may be clear to you already, but Assistant will send an empty search request if the user says something like "Hey Google, play music in [your app]". The expectation is that you either play something suitable (for example, resume previous playback) or let the request fail.

**Comment by Kyant0** [comment]
Ok, thanks for the detailed explanation.
