### ISSUE TITLE
Black screen flickering when promoting video quality track

### ISSUE THREAD

**Issue by changxiangzhong** [androidx/media#1174]
### Version

Media3 1.3.0

### Devices that reproduce the issue

Philips OLED TV 706. Device name and firmware version specified as following
```
[ro.boot.device_name]: [65OLED706/12]
[ro.build.product]: [PH1M_EA_9970A]
[ro.vendor.build.fingerprint]: [Philips/PH1M_EA_9970A/PH1M_EA_9970A:11/RTT2.211108.001/2717:user/release-keys]
```

### Devices that do not reproduce the issue

Broadcom 72180 boxes

### Reproducible in the demo app?

Yes

### Reproduction steps

Steps
- Kill the previous exoplayer demo
- Apply the following patch/channel
- Start the channel
- Pay attention to **VIDEO BITRATE PROMOTING**, and you'll see the black screen flickering. A sample video has been uploaded to [here](https://drive.google.com/file/d/10j_nmVOnG2K6GH4n27cQyVXlupN2owwB/view). 

Use the following patch on **media.exolist.json**
```
  {
    "name": "Telia",
    "samples": [
      {
        "name": "NRK1 HD - Telia Solna",
        "uri": "https://director.streaming.telia.com/tvm-packager-prod/group11/6530d589890ef35940120dc3/manifest.mpd?adap=default",
        "drm_scheme": "widevine",
        "drm_license_uri": "https://lic.drmtoday.com/license-proxy-widevine/cenc/?specConform=true",
        "drm_key_request_properties": {
          "x-dt-custom-data": "TO-BE-SENT-THROUGH-SECRET-CHANNEL"
        }
      },
```

### Expected result

Smooth video bit-rate transition to high

### Actual result

A black screen flickering during video bit-rate promoting

### Media

```
  {
    "name": "Telia",
    "samples": [
      {
        "name": "NRK1 HD - Telia Solna",
        "uri": "https://director.streaming.telia.com/tvm-packager-prod/group11/6530d589890ef35940120dc3/manifest.mpd?adap=default",
        "drm_scheme": "widevine",
        "drm_license_uri": "https://lic.drmtoday.com/license-proxy-widevine/cenc/?specConform=true",
        "drm_key_request_properties": {
          "x-dt-custom-data": "TO-BE-SENT-THROUGH-SECRET-CHANNEL"
        }
      },
```

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by changxiangzhong** [comment]
@tonihei, the issue is reproducible in release 1.1.0 and exoplayer 2.18.5. so not the same one as #1158

**Comment by tonihei** [comment]
Thanks for checking, so it's indeed not the same issue. Given your media is DRM protected, it might be you are running in the same problem that was originally reported in https://github.com/google/ExoPlayer/issues/8196. This was a platform limitation on some devices up to API 30/31 that caused a black frame to be shown on some DRM-protected transitions. If this is the case, then there is unfortunately not much we can do from within our library. If you think it's something else or was introduced by some version of ExoPlayer, please let us know. I also checked your bugreport, but couldn't see anything suspicious either.

**Comment by tonihei** [comment]
Thanks for confirming! I'll mark it as duplicate then. 

> This this issue has been reproduced on the following SoCs? Any other known affected platforms?

I'm afraid we don't have any data on this as there is also no known workaround we could apply to avoid the issue on the affected devices.
