### ISSUE TITLE
Downloading video issues

### ISSUE THREAD

**Issue by Kunal0bhatt** [androidx/media#1175]
### Version

Media3 main branch

### More version details

we are using hls so while loading the stream we get the error StringIndexOutOfBoundsException in  HlsChunkSource.java file.
the video wokrs fine online, but when i download multiple videos, we get this exception in some of the downloaded video , and if we re download that same video, it works properly

### Devices that reproduce the issue

almost on all device

### Reproducible in the demo app?

Yes

### Reproduction steps

[output-metadata.json](https://github.com/androidx/media/files/14558547/output-metadata.json)
id -> kunal0bhatt@gmail.com
pass -> kunal@123

download multiple video
now in the bottom tab there is my page icon, 
click on it 
now there is a card view that contain downloaded video
click on it and check weather the video is working or not

### Expected result

the video play succes fully

### Actual result

some video does not play

### Media

[output-metadata.json](https://github.com/androidx/media/files/14558542/output-metadata.json)
id -> kunal0bhatt@gmail.com
pass -> kunal@123

download multiple video
now in the bottom tab there is my page icon, 
click on it 
now there is a card view that contain downloaded video
click on it and check weather the video is working or not

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by tonihei** [comment]
I do not really understand the reproduction steps with the output-metadata.json file. Could you explain in more detail what we need to do to reproduce the issue? Downloading multiple videos in the demo apps seems to work fine, but there is probably more involved to get to a reproducible example.

> StringIndexOutOfBoundsException in HlsChunkSource.java

Could you also share more details about this error in particular?
