### ISSUE TITLE
MediaMetadata extras do not get populated when only setExtras used in Builder

### ISSUE THREAD

**Issue by akshdeep-singh** [androidx/media#1176]
### Version

Media3 1.3.0

### Devices that reproduce the issue

Pixel 5 API 34 Emulator

### Reproducible in the demo app?

Not tested

### Reproduction steps

This works:
```kotlin
val extras = Bundle().apply { putString("uri", uri) }
val mediaMetadata = MediaMetadata.Builder()
    .setDisplayTitle(title)
    .setExtras(extras)
    .build()
val mediaItem = MediaItem.Builder()
    .setUri(uri)
    .setMediaMetadata(mediaMetadata)
    .build()
```
```kotlin
override fun onMediaItemTransition(mediaItem: MediaItem?, reason: Int) {
   println(mediaItem?.mediaMetadata?.extras?.getString("uri"))
   // NOT null
}
```
This doesn't work (when only `setExtras` are used):
```kotlin
val extras = Bundle().apply { putString("uri", uri) }
val mediaMetadata = MediaMetadata.Builder()
    .setExtras(extras)
    .build()
val mediaItem = MediaItem.Builder()
    .setUri(uri)
    .setMediaMetadata(mediaMetadata)
    .build()
```
```kotlin
override fun onMediaItemTransition(mediaItem: MediaItem?, reason: Int) {
   println(mediaItem?.mediaMetadata?.extras?.getString("uri"))
   // null
}
```
Same issue with `playlistMetadata`.

### Expected result

MediaMetadata extras should not be null.

### Actual result

MediaMetadata extras are null.

### Media

I am observing this issue for all mp3 files (not tested for other types).

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by tonihei** [comment]
Thanks for reporting! We'll provide a fix for this in the next bugfix release (1.3.1).
