### ISSUE TITLE
Playing ads (via IMA SDK) when ExoPlayer is inside MediaSessionService

### ISSUE THREAD

**Issue by ziem** [androidx/media#118]
Hello!
I’m experimenting with Media3 library, and I encountered one issue. It’s related to how `AdsLoader` is constructed and the fact that the recommended solution for background playback is to keep `ExoPlayer` instance inside `MediaSessionService`.

Some background:
I’m creating an app which allows users to watch videos and listen to music. I would like to be able to make both play in the background. I decided to use approach from https://developer.android.com/guide/topics/media/media3/getting-started/playing-in-background#using-mediasessionservice, and I put `ExoPlayer` instance inside `MediaSessionService`. Let’s say I have `PlayerActivity` which binds to the `PlaybackService` via:
```
...

controllerFuture = MediaController.Builder(
    this,
    SessionToken(this, ComponentName(this, PlaybackService::class.java))
)
.buildAsync()

...
```

Inside `PlaybackService` `ExoPlayer` instance is created inside `onCreate` method.

---

Everything works great until I need to load ads through IMA SDK. To configure IMA SDK, when constructing `AdsLoader`, we need to pass `AdViewProvider`. It’s not possible to do inside a `Service`, and since we keep `ExoPlayer` instance in it, we cannot provide it on the `PlayerActivity` level. `AdViewProvider` cannot be changed after `AdsLoader` is built. I mean, we can pass null, and it makes ads audio-only but then in the `PlayerActivity` we wouldn’t have video ads played.

My problem/question is how can I configure IMA SDK/`AdViewProvider` to be able to play video ads when running `PlayerActivity` and still be able to background the playback using `MediaSessionService` and the whole session approach?

I can’t find any obvious solution for this problem. Maybe I’m missing something as Media3 library is still in beta, and its documentation covers only simpler cases.

**Comment by marcbaechinger** [comment]
A controller talks to the session through a `Binder`. Generally this requires any arguments that are sent over the `Binder` to be `Parcelable`. If I understand correctly the problem you are facing as you can not send the `ViewGroup` or the `AdOverlayInfo` to the service. 

I don't think there is an easy solution for this that would generally work across processes. This is the requirement on the library level for the communication between controller and session. 

If you as an app can make sure that your service is running in the same process you probably can workaround this yourself by adding something to your service that allows to pass these argument to the service in a conventional Java way , that the library can not do.

**Comment by ziem** [comment]
Thank you for your answer and suggested solution 👍

**Comment by ofcbujin** [comment]
Hi @ziem did you find a workaround ? I'm having the same problem. I try to override the onbind method and treat the MediaLibraryService as a normal service but I couldn't find a way to build the MediaController with the SessionToken and bind the service in the same instance.
