### ISSUE TITLE
Scaling Bug in media3 with Android 14

### ISSUE THREAD

**Issue by sunnat629** [androidx/media#1184]
### Version

Media3 main branch

### More version details

When using the `media3-exoplayer` library to play videos in a Jetpack Compose application with `PlayerView` inside an `AndroidView`, the video content does not scale correctly on devices running Android 14. The issue is observable on a Pixel 7 Pro where using `RESIZE_MODE_FIT` leads to the video not filling the `PlayerView` as expected. This issue does not occur with `RESIZE_MODE_FILL`, but it is present in all other resize modes, including `RESIZE_MODE_FIXED_HEIGHT`, `RESIZE_MODE_FIXED_WIDTH`, and `RESIZE_MODE_ZOOM`.

### Reproducible in the demo app?
The issue is not reproducible in the standard demo app but can be observed in a custom Jetpack Compose setup. in Linked demo app, if you use `MainActivity2` I use xml and there is no issue there.

Using: RESIZE_MODE_FILL
![RESIZE_MODE_FILL](https://github.com/androidx/media/assets/5854791/6252a9da-bf1b-4818-b3ad-974e339ea0f0)

Using: RESIZE_MODE_FIT
![RESIZE_MODE_FIT](https://github.com/androidx/media/assets/5854791/e9eba055-2c4d-4deb-a475-a2ad676f4383)

### Devices that reproduce the issue

- Pixel 7 Pro running Android 14 (90% time)
- Galaxy S22, Android 14 (70-80% time)

### Devices that do not reproduce the issue

- Samsung S10 running Android 12 (around 30% time)
- - Motorola G7 Power running Android 10 (0%)

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Create a `PlayerView` with `resizeMode` set to `RESIZE_MODE_FIT`.
2. Play a video.
3. Observe that the video content does not fill the `PlayerView`.

### Expected result

The video content should scale to fit within the `PlayerView` without any cropping or letterboxing, maintaining the video's aspect ratio.

### Actual result

The video content does not scale properly, and parts of the video are cropped or do not fill the `PlayerView`.

### Link to test content
Github: https://github.com/sunnat629/Media3ExoplayerScale

### Version of the library
Media3 version: 1.3.0
```
implementation("androidx.media3:media3-exoplayer:1.3.0")
implementation("androidx.media3:media3-exoplayer-hls:1.3.0")
implementation("androidx.media3:media3-ui:1.3.0")
```

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by oceanjules** [comment]
I think the library is doing what should be expected from documentation. Let me paste the relevant code snippet:

https://github.com/androidx/media/blob/d13a0f4ec62ca092b79746a5725b62a3244cc5b4/libraries/ui/src/main/java/androidx/media3/ui/AspectRatioFrameLayout.java#L174-L209

1) The reason `RESIZE_MODE_FILL` as you say "works" is that it's actually not doing any resizing at all ("Ignore target aspect ratio" branch)
2) `RESIZE_MODE_FIT` is documented to DECREASE one of the dimensions: 
https://github.com/androidx/media/blob/d13a0f4ec62ca092b79746a5725b62a3244cc5b4/libraries/ui/src/main/java/androidx/media3/ui/AspectRatioFrameLayout.java#L69-L70
3) `RESIZE_MODE_ZOOM` is documented to INCREASE one of the dimensions:
https://github.com/androidx/media/blob/d13a0f4ec62ca092b79746a5725b62a3244cc5b4/libraries/ui/src/main/java/androidx/media3/ui/AspectRatioFrameLayout.java#L85-L86

Now back to your particular video sample:
* 1100k video is 1680x750, i.e. `videoAspectRatio = 2.24`
* 2200k video is 3360x1500, i.e. `videoAspectRatio = 2.24`
* Pixel 7 positions the video in a view with `width=2984` and `height=1272`
* `viewAspectRatio = 2.34`
* `aspectDeformation = videoAspectRatio / viewAspectRatio - 1` is NEGATIVE
* For "FILL" that means: height stays the same, width shrinks (as per your screenshot)


Attaching my own reproduction screenshot below. Feel free to debug yourself - AspectRatioFrameLayout is the place

![Screenshot 2024-03-14 at 17 30 58](https://github.com/androidx/media/assets/19333204/0a4ed2d3-02ab-44d4-a5c4-bfa999cf3035)


Note, however, there is currently a problem with using SurfaceView and AspectRatioFrameLayout where FIT will work, but ZOOM will leak the contents of the video to outside of the FrameLayout (https://github.com/androidx/media/issues/1123, https://github.com/androidx/media/issues/1120, https://github.com/androidx/media/issues/1107)

**Comment by Junaid17** [comment]
@oceanjules Iam using  RESIZE_MODE_FIT and still able to see the above on Pixel 14 devices. Is there any possible work around for this to work with compose?

**Comment by anushagif** [comment]
I have same issue but when switching the orientation to landscape will solve the problem.

**Comment by oceanjules** [comment]
@Junaid17 
The OP was also struggling with RESIZE_MODE_FIT and I documented above as to why the scaling is dependent on the video aspect ratio AND the phone size. 

RESIZE_MODE_FIT looks at `aspectDeformation = videoAspectRatio / viewAspectRatio - 1` to decide whether to shrink width or height. With the same media (i.e. videoAspectRatio), you might be seeing different scaling behaviour depending on the phone size (i.e. viewAspectRatio)
