### ISSUE TITLE
 player.setVideoEffects() doesnot work with GLSurfaceView

### ISSUE THREAD

**Issue by omkarsurya** [androidx/media#1186]
### Version

Media3 main branch

### More version details

exoplayer:1.3.0
media3-transformer:1.3.0

### Devices that reproduce the issue

Samsung Galaxy Tab A7 lite

### Reproducible in the demo app?

Yes

### Reproduction steps

1. use the GLsurfaceview Demo  
2. add the [MatrixTransformationFactory](https://github.com/androidx/media/blob/release/demos/transformer/src/main/java/androidx/media3/demo/transformer/MatrixTransformationFactory.java) from the Transformer demo code
3. add the effects using `ImmutableList.Builder<Effect> effects = new ImmutableList.Builder<>(); effects.add(MatrixTransformationFactory.createSpin3dEffect());  player.setVideoEffects(effects.build()); ` after player.prepare
4. if we comment the `player.setVideoEffects(effects.build());`  the video plays other wise it wont play

### Expected result

video should play with the applied effect and the bitmap overlay provided by the demo app 

### Actual result

video does not play it is stuck at 0

### Media

not applicable 

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by andrewlewis** [comment]
Please could you add more info about why you need `GLSurfaceView` support, instead of just using `SurfaceView`? We can look into why it's not working, but it should also be possible to avoid the overhead of having two GL contexts set up. The extra functionality that `GLSurfaceView` adds on top of `SurfaceView` is generally unnecessary when using `setVideoEffects`.

**Comment by omkarsurya** [comment]
I  want to add some custom implementation of GLsurfaceview, to show so video effects, while I know that `GlEffects` can be applied to exoplayer, there are various limitations of `ExoPlayer.setVideoEffects()` also the preview of the effects, is not available, I have raised a separate issue for that [here](https://github.com/androidx/media/issues/1185) In my example say I want to implement an effect with GLsurfaceview  and a`MatrixTransformationFactory.createSpin3dEffect()` the video just doesnot play. 

The Limitation of explayer to display various `effects` while live editing over a timeline which is a basic feature of any video editing app is my primary requirement So I  decided to use both `GLsurfaceview` and `MatrixTransformationFactory.createSpin3dEffect()` but came across this  bug

**Comment by droid-girl** [comment]
We recommend waiting for CompositionPlayer APIs that will support this use case.
