### ISSUE TITLE
System UI crashes when switch songs very fast

### ISSUE THREAD

**Issue by Kyant0** [androidx/media#1195]
Double tap the forward button or the next button fast will crash System UI, leading to a temporary black screen or infinite black screen flickering, the user had to reboot.

Device: MIUI, Android 11

I can notice the image of system notification will get a short blank if fast switch, but bitmap exists in BitmapLoader.
When I throw an Exception in the method, System UI must crash at evey time song plays. But I don't think it produced an exception in the version before I throw the exception manually. So what causes the System UI crash?

**Comment by Kyant0** [comment]
https://github.com/androidx/media/assets/76829190/7b8a71ef-4d0a-4b2a-8296-eed3efbaf5c7

**Comment by oceanjules** [comment]
If you are reporting a `bug`, rather than asking a `question`, it would be helpful to fill out our bug-template. Then we can see reproduction steps, which media you are playing (if not in the demo app) and dump logs.
