### ISSUE TITLE
Video not rendered when using AspectRatioFrameLayout.RESIZE_MODE_FIXED_HEIGHT on Pixel phones

### ISSUE THREAD

**Issue by pavelbayburtyan** [androidx/media#1196]
### Version

Media3 1.3.0

### More version details

Was able to reproduce it also on `1.2.0` and `1.0.2` 

### Devices that reproduce the issue

* Pixel 6, Pixel 8 Android 14, Android Security Update March 5, 2024, Google Play System Update February 1, 2024. Started appearing after some of the latest Pixel software updates. 

### Devices that do not reproduce the issue

* Samsung S22 Ultra, Android 14
* Pretty much any other phone. Was able to reproduce it only on Pixel phones.

### Reproducible in the demo app?

No

### Reproduction steps

1. Use `AndroidView` in compose and as `factory` provide a `PlayerView`
2. Set `resizeMode` to `AspectRatioFrameLayout.RESIZE_MODE_FIXED_HEIGHT`
3. Load an mp4 video using uri.

### Expected result

The video is properly rendered.

### Actual result

The video is not rendered but instead a black frame. After sending the app to the background and resuming it the video starts to be rendered more properly but still some artifacts (like a black horizontal line) can be observed

I was able to reproduce the issue only when using  `RESIZE_MODE_FIXED_HEIGHT`

### Media

https://github.com/androidx/media/assets/116361059/bc4e262c-f9ff-4967-aeb9-25f0a58d7549

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by oceanjules** [comment]
Thank you for your report. Would it be possible for you to attach the media as a raw mp4 file? It seems like the content is only read-access at the moment, so I cannot download it to reproduce locally.

Also, could you provide your MainActivity code with AndroidView as a minimal example, since we currently do not have a demo app that uses Compose. It might be that you are missing something else in the player setup.

**Comment by pavelbayburtyan** [comment]
@oceanjules hey, thanks for your response. I did not exactly get what you mean with read-only access. I'm able to download the video via 3-dots menu at the bottom right corner.
 I've also attached how it looks like on Pixel 6 Android 14 and Moto G51 Android 12. 
As you can see on Pixel 6 first the video is not rendered at all, after resuming app it's rendered but also not positioned correctly

https://github.com/androidx/media/assets/116361059/15b8df6c-14dc-4a58-9fe8-fcea5f322c1a

https://github.com/androidx/media/assets/116361059/12c4e7f4-fd00-453b-ba9b-1c9c9bfde665

Here some sample code. 

```kotlin
 override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    
    setContent {

        val context = LocalContext.current
        val videoUri = remember { RawResourceDataSource.buildRawResourceUri(R.raw.phn_video) }
        val mediaItem = remember { MediaItem.fromUri(videoUri) }
    
        val exoPlayer = remember(context) {
            ExoPlayer.Builder(context).build().apply {
                setMediaItem(mediaItem)
                prepare()
                playWhenReady = true
                repeatMode = REPEAT_MODE_ALL
            }
        }
        MaterialTheme {
            Scaffold {
                Column(modifier = Modifier.padding(it), verticalArrangement = Arrangement.Center) {
                    Row(
                        Modifier
                            .background(color = Color.White)
                            .height(40.dp),
                    ) {
                        Text(text = "Just some offset")
                    }
                    Row(Modifier.weight(1f)) {
                        Video(exoPlayer)
                    }
                }
            }
        }
    }
}

@Composable
private fun Video(exoPlayer: ExoPlayer) {
    var isVideoPrepared by remember { mutableStateOf(false) }
    val alpha by animateFloatAsState(targetValue = if (isVideoPrepared) 1f else 0f, label = "video fade in")

    val shutterColor = MaterialTheme.colorScheme.background.toArgb()
    exoPlayer.addListener(
        object : Player.Listener {
            override fun onPlaybackStateChanged(playbackState: Int) {
                super.onPlaybackStateChanged(playbackState)
                isVideoPrepared = isVideoPrepared(playbackState)
            }
        },
    )
    AndroidView(
        factory = { ctx ->
            PlayerView(ctx).apply {
                useController = false
                resizeMode = AspectRatioFrameLayout.RESIZE_MODE_FIXED_HEIGHT
                player = exoPlayer
                setShutterBackgroundColor(shutterColor)
            }
        },
        modifier = Modifier.alpha(alpha),
    ) {
        isVideoPrepared = isVideoPrepared(it.player?.playbackState)
    }
}
```

Let me know if you need anything else! Thanks in advance for your help!

**Comment by oceanjules** [comment]
Sorry for a delay - here are my recent findings:


<details>
<summary>With the code slightly modified to remove animation (uncollapse to see)</summary>

```
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.annotation.OptIn
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.toArgb
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.compose.ui.viewinterop.AndroidView
import androidx.media3.common.MediaItem
import androidx.media3.common.Player.REPEAT_MODE_ALL
import androidx.media3.common.util.UnstableApi
import androidx.media3.datasource.RawResourceDataSource
import androidx.media3.exoplayer.ExoPlayer
import androidx.media3.ui.AspectRatioFrameLayout
import androidx.media3.ui.PlayerView

class MainActivity : ComponentActivity() {

  @OptIn(UnstableApi::class)
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    setContent {
      val context = LocalContext.current

      val exoPlayer =
        remember(context) {
          ExoPlayer.Builder(context).build().apply {
            setMediaItem(MediaItem.fromUri(RawResourceDataSource.buildRawResourceUri(R.raw.phn_video)))
            prepare()
            playWhenReady = true
            repeatMode = REPEAT_MODE_ALL
          }
        }
      MaterialTheme {
        Scaffold {
          Column(modifier = Modifier.padding(it), verticalArrangement = Arrangement.Center) {
            Row(Modifier.background(color = Color.White).height(40.dp)) {
              Text(text = "Just some offset")
            }
            Row(Modifier.weight(1f)) { Video(exoPlayer) }
          }
        }
      }
    }
  }

  @OptIn(UnstableApi::class)
  @Composable
  private fun Video(exoPlayer: ExoPlayer) {

    val shutterColor = MaterialTheme.colorScheme.background.toArgb()

    AndroidView(
      factory = { ctx ->
        PlayerView(ctx).apply {
          useController = false
          resizeMode = AspectRatioFrameLayout.RESIZE_MODE_FIXED_HEIGHT
          player = exoPlayer
          setShutterBackgroundColor(shutterColor)
        }
      }
    )
  }
}
```
</details>
I can see that it works on:

Pixel 6 (API 33/Android 13)

https://github.com/androidx/media/assets/19333204/160855ce-1836-4636-81bd-0f23822a3cde


Pixel 7 (API 34/Android 14)

https://github.com/androidx/media/assets/19333204/b7685f7c-41ab-4a6b-9dca-641777b665e9


Pixel 8 (API 34/Android 14)

https://github.com/androidx/media/assets/19333204/48f8226f-eebc-4a69-a0db-19b00b155c53




I assume it's something to do with the `alpha`? You didn't paste your implementation of isVideoPrepared(int state), so maybe you are stuck in the 0f value and the screen looks black/unrendered?

**Comment by pavelbayburtyan** [comment]
Hey @oceanjules. Thanks for your response! In my case it's the same behavior I've described: video is not rendered. I tried to remove alpha completely from our prod code, also I tried your exact code you've pasted: in both cases it's a black frame :(

**Comment by pavelbayburtyan** [comment]
Anyway our issue is already solved by replacing `ExoPlayer` with `MediaView`. But I guess still interesting to know what causes this issue.
