### ISSUE TITLE
Clarification about DASH-Thumbnails support in exoplayer

### ISSUE THREAD

**Issue by He12345678901** [androidx/media#1199]
Hi
I'd like to clarify and make sure please whether the ExoPlayer in version 2.13.2 support Thumbnails in DASH playout

here's an example of the additional Adaptation Set containing the Thumbnail in the DASH Manifest MPD:
1.This type of Adaptation Set is being supported for the exoplayer 2.13.2 to display the Thumbnails when moving fast forward/rewind on the played program?
2. any modifications need to be made in the player parameters to support the Thumbnails ?

thanks.

**Comment by He12345678901** [comment]
Hi
I'd like to clarify and make sure please whether the ExoPlayer in version 2.13.2 support Thumbnails in DASH playout

here's an example of the additional Adaptation Set containing the Thumbnail in the DASH Manifest MPD:
1.This type of Adaptation Set is being supported for the exoplayer 2.13.2 to display the Thumbnails when moving fast forward/rewind on the played program?
2. any modifications need to be made in the player parameters to support the Thumbnails ?

thanks.

**Comment by He12345678901** [comment]
[DASH_Thumbnail_Adaptation_Set_Example.txt](https://github.com/androidx/media/files/14649519/DASH_Thumbnail_Adaptation_Set_Example.txt)

**Comment by He12345678901** [comment]
Hi,
Support for DASH thumbnails playback in Media3 1.3.0, means it's aligned with the DASH-IF interoperability points ? so that for Thumbnails' signaling provided within the DASH Manifest there'll be an additional Adaptation Set with ContentType of 'image' and mimeType of 'image/jpeg' (as per the .txt file I have previously attached) - will Media3 1.3.0 support this structure and display the thumbnails when moving forward/backward on the video ?
thanks.

**Comment by tonihei** [comment]
As I said above, you need manually enable this track if you want to use it and then ExoPlayer outputs the images at the right time to the image output (which you can use to update a corresponding UI element).

**Comment by He12345678901** [comment]
Hi
can you please describe with the exact details of this track and its properties we need to enable on the Media 3 code in order to see the image/thumbnails ?
thanks.
