### ISSUE TITLE
How to detect when the playback position is behind the live window?

### ISSUE THREAD

**Issue by cdongieux** [androidx/media#1204]
Hi,

I have a live DASH stream having a buffer duration of 4 hours. I need this use case to be possible:

1. seek to any position in the buffer
2. pause playback
3. wait for few seconds/minutes/hours
4. resume playback at the right position, the right position being one of these:
    - the same position the playback paused if the playback position is still within the live window
    - the trailing edge of the stream (position 0) if the paused playback position is behind the live window

I want to be able to seek to the trailing edge of the stream (player.seekTo(0)), then pause the playback for few seconds/minutes, then when I resume the playback I need the player to resume 

The basic approach is to resume playback at step 4, catch the `BehindLiveWindowException`, then seek to 0. But the drawback is when resuming playback the player will play few seconds of what is still buffered instead of directly playing content from 0.

Do you have any idea how I can achieve this?

**Comment by cdongieux** [comment]
Hi again,

Sorry for my silly question, it was quite simple in deed: when resuming playback, just check the player position: if it's negative then do a `seekTo(0)`.

**Comment by tonihei** [comment]
To add to that, you may not want to use `seekTo(0)` as this seeks right to the end of the live window and factoring in some delay to get playback started again, you likely end up with being behind the live window almost immediately again. It's likely better to seek closer to the live edge, something like `seekTo(player.getDuration() - 2000)` to seek 2 seconds away from the currently available start of the live window.
