### ISSUE TITLE
In Media3 how to update the title in notification dynamically during playback

### ISSUE THREAD

**Issue by saravr** [androidx/media#1205]
I need to update the title shown in the media notification based on the current playback position. Unfortunately, I cannot split the mediaitem into separate ones which could have made this easy.

Is there a way to do this in the player listener `onPositionDiscontinuity` callback?

```
override fun onPositionDiscontinuity(
    oldPosition: Player.PositionInfo,
    newPosition: Player.PositionInfo,
    reason: Int,
) {
    super.onPositionDiscontinuity(oldPosition, newPosition, reason)
    val updatedMetadata = currentMediaItem?.mediaMetadata?.buildUpon()?.setTitle("New title")?.build()!!
    val updatedMediaItem = currentMediaItem?.buildUpon()?.setMediaMetadata(updatedMetadata)?.build()!!
    // IS THERE A WAY TO UPDATE NOTIFICATION HERE??
}
```

**Comment by marcbaechinger** [comment]
I think `Player.replaceMediaItem(int, MediaItem)` could work. This can be called either on `ExoPlayer` or on a `MediaController`:

```
controller.replaceMediaItem(mediaItemPosition, updatedMediaItem)
```

Please check the [ JavaDoc of the `Player` interface](https://github.com/androidx/media/blob/release/libraries/common/src/main/java/androidx/media3/common/Player.java#L2343-L2357) for more details.
