### ISSUE TITLE
update    api ' com.google.android.gms:play-services-cast-framework:21.3.0' to gms:play-services-cast-framework:21.4.0 returns error for build

### ISSUE THREAD

**Issue by pooya-mohammadhossein** [androidx/media#1209]
### Version

Media3 1.3.0

### More version details

dependencies {
    api 'com.google.android.gms:play-services-cast-framework:21.3.0'

...

### Devices that reproduce the issue

I have used the most recent branch (Media3 1.3.0) how ever in Library folder , if I would update    api ' com.google.android.gms:play-services-cast-framework:21.3.0' to gms:play-services-cast-framework:21.4.0
 returns error for build. Please fix this issue with the next commit.

### Reproducible in the demo app?

Yes

### Reproduction steps

open build.gradle (:lib-cast)
update  from
```
dependencies {
    api 'com.google.android.gms:play-services-cast-framework:21.3.0'
...
}
to
dependencies {
    api 'com.google.android.gms:play-services-cast-framework:21.4.0'
...
}
```

### Expected result

Expected result is build become successful but it's not after this library update

### Actual result

Expected result is build become successful but it's not after this library update

### Media

[build.gradle.zip](https://github.com/androidx/media/files/14701577/build.gradle.zip)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment]
Please provide more information about the build error you see.
