### ISSUE TITLE
App launched from tapping notification but extras from PendingIntent are not set

### ISSUE THREAD

**Issue by saravr** [androidx/media#1218]
I would like to take the user directly to the player UI when the user taps on media notification. I see that app is launched (or brought to foreground) but intent extras are null and I cannot take the user to the player screen.

In MediaSessionService onCreate() I have
```
      val intent = packageManager.getLaunchIntentForPackage(packageName)
      intent?.putExtra("DESTINATION", "player")
      val pendingIntent = PendingIntent.getActivity(this, 0, intent, FLAG_IMMUTABLE or FLAG_UPDATE_CURRENT)

      mediaSession = MediaSession.Builder(this, player)
          .setSessionActivity(pendingIntent)
          .build()
```

And in the MainActivity onResume/onStart/onNewIntent I see that the intent extras are not set.

```
    override fun onStart() {
        super.onStart()
        Timber.e("onStart: intents: ${intent.extras?.size()}") // <--- this is 0
    }
```

This is what I have in manifest.

```
      <activity
          android:name=".MainActivity"
          android:exported="true">
          <intent-filter>
              <action android:name="android.intent.action.MAIN" />
              <category android:name="android.intent.category.LAUNCHER" />
          </intent-filter>
      </activity>
```

I am testing this in API level 34.

What am I missing? Also, I have MainActivity and MediaSessionService in different gradle modules but I suppose manifests are merged anyway.

**Comment by marcbaechinger** [comment]
Thanks for your report!

When I change the code of the `PlaybackService` of the demo app like this

```
override fun getSingleTopActivity(): PendingIntent? {
    val intent = Intent(this, PlayerActivity::class.java)
    intent.putExtra("test", "testValue")
    return getActivity(
      this,
      0,
      intent,
      immutableFlag or FLAG_UPDATE_CURRENT
    )
  }
```

then I can see the extra with `intent.getStringExtra("test")` when the `PlayerActivity` is launched.

From this I would say this is generally working. I'm not sure how this is intended to work with `packageManager.getLaunchIntentForPackage(packageName)`. It's probably that method that does something special?

Can you check if this works when creating an explicit `Intent` as in the snippet above?

**Comment by saravr** [comment]
I am still stuck on this issue, any help possible?

**Comment by marcbaechinger** [comment]
Yeah, I don't think we can do much from the library side I'm afraid.

**Comment by saravr** [comment]
I'm good, this ticket can be closed.
