### ISSUE TITLE
Not able to play HLS streams.

### ISSUE THREAD

**Issue by Shabinder** [androidx/media#1220]
### Version

Media3 1.3.0

### More version details

I am unable to play audio only hls streams using exoplayer,
but vlc does play that.

Exoplayer only can play simple .mp3, .m4a content but not hls.

### Devices that reproduce the issue

Emulators and physical devices alike, ex: Nothing Phone 1

### Reproduction steps

Play below link with exoplayer:

 https://libraryitems.insighttimer-api.net/e5x7j9t6x6w6b4v4p6f5f1u9t5m9j1q1y7v5x4p0/hls/v1/index.m3u8

```
val mediaItem = MediaItem.Builder().run {
        val uri = Uri.parse("https://libraryitems.insighttimer-api.net/e5x7j9t6x6w6b4v4p6f5f1u9t5m9j1q1y7v5x4p0/hls/v1/index.m3u8")
        setMediaId(uri.toString())
        setUri(uri)
        if (uri.path?.endsWith("m3u8") == true) {
            setMimeType(MimeTypes.APPLICATION_M3U8)
        }

        setRequestMetadata(
            MediaItem.RequestMetadata.Builder()
                .setMediaUri(uri)
                .build()
        )

       /*more metadata props*/
}

player.setMediaItem(mediaItem)
 player.playWhenReady = true
player.prepare()
```

### Expected result

Should have started playback, as vlc does.

### Actual result

It throws below error
```

androidx.media3.exoplayer.ExoPlaybackException: Source error
        at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:713)
        at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:683)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)

Caused by: androidx.media3.common.ParserException: Loading finished before preparation is complete.{contentIsMalformed=true, dataType=1}
        at androidx.media3.exoplayer.hls.HlsSampleStreamWrapper.maybeThrowPrepareError(HlsSampleStreamWrapper.java:290)
        at androidx.media3.exoplayer.hls.HlsMediaPeriod.maybeThrowPrepareError(HlsMediaPeriod.java:188)
        at androidx.media3.exoplayer.source.MaskingMediaPeriod.maybeThrowPrepareError(MaskingMediaPeriod.java:157)
        at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1119)
        at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:541)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```

### Media

https://libraryitems.insighttimer-api.net/e5x7j9t6x6w6b4v4p6f5f1u9t5m9j1q1y7v5x4p0/hls/v1/index.m3u8

**Comment by Shabinder** [comment]
Additional Info: 

Starting Playback directly on `ExoPlayer` like below works, but the app needs to control and start playback using setMediaItems on `Player` interface

```
      val testLink = "https://libraryitems.insighttimer-api.net/e5x7j9t6x6w6b4v4p6f5f1u9t5m9j1q1y7v5x4p0/hls/v1/index.m3u8"
      val track = HlsMediaSource.Factory(SoundboundCache.cacheFactory).createMediaSource(MediaItem.fromUri(testLink))

      innerPlayer.setMediaSource(track)
      innerPlayer.prepare()
      innerPlayer.playWhenReady
```

**Comment by icbaker** [comment]
> Starting Playback directly on `ExoPlayer` like below works

It's quite surprising that playback works when you directly interact with ExoPlayer but fails with the described error when interacting via MediaController.

What happens if you use `exoplayer.setMediaItem` directly instead of `setMediaSource`?

How are you building/configuring the ExoPlayer instance that you pass to your MediaSession? (code snippet of this would be useful).

Please can you add some debug logging to check what URL is being passed down to ExoPlayer? The easiest way is probably to override [`MediaSession.Callback.onAddMediaItems`](https://developer.android.com/reference/androidx/media3/session/MediaSession.Callback#onAddMediaItems(androidx.media3.session.MediaSession,androidx.media3.session.MediaSession.ControllerInfo,java.util.List%3Candroidx.media3.common.MediaItem%3E)) with your logging and a call to the super-implementation (assuming you haven't already added custom logic here):

```java
@Override
public ListenableFuture<List<MediaItem>> onAddMediaItems(
    MediaSession mediaSession, 
    MediaSession.ControllerInfo controller,
    List<MediaItem> mediaItems) {
  for (MediaItem item : mediaItems) {
    Log.w("1220", "uri=" + (item.localConfiguration != null ? item.localConfiguration.uri : "null"));
  }
  return super.onAddMediaItems(mediaSession, controller, mediaItems);
}
```

**Comment by Shabinder** [comment]
> What happens if you use exoplayer.setMediaItem directly instead of setMediaSource?

It **worked** with MediaItem directly on Exoplyer, while it fails on instance of MediaBrowser, the exact same code.


> How are you building/configuring the ExoPlayer instance that you pass to your MediaSession? (code snippet of this would be useful).

```
val innerPlayer = ExoPlayer.Builder(this)
            .setAudioAttributes(
                AudioAttributes.Builder()
                    .setUsage(C.USAGE_MEDIA)
                    .setContentType(C.AUDIO_CONTENT_TYPE_MUSIC)
                    .build(), true
            )
            .setSeekBackIncrementMs(5000)
            .setSeekForwardIncrementMs(5000)
            .setHandleAudioBecomingNoisy(true)
            .setWakeMode(C.WAKE_MODE_NETWORK)
            .setMediaSourceFactory(
                DefaultMediaSourceFactory(
                    this,
                    DefaultExtractorsFactory()
                ).setDataSourceFactory(
                 CacheDataSource.Factory()
                            .setCache(simpleCache)
                            .setCacheReadDataSourceFactory(FileDataSource.Factory())
                            .setUpstreamDataSourceFactory(
                                DefaultDataSource.Factory(context)
                            )
                 )
            )
            .build()

```


> Please can you add some debug logging to check what URL is being passed down to ExoPlayer? The easiest way is probably to override [MediaSession.Callback.onAddMediaItems]


```
       mediaItems.forEach { mediaItem ->
            DefaultLogger.i { "Added MediaItem uri: ${mediaItem.localConfiguration?.uri}" }
        }

using above got below: 

Added media uri: https://libraryitems.insighttimer-api.net/e5x7j9t6x6w6b4v4p6f5f1u9t5m9j1q1y7v5x4p0/hls/v1/index.m3u8

```


**Additional Info:**
upon using super.implementation in addMediaItem rather than recreating mediaItem, error changed to below:
 ```
androidx.media3.exoplayer.ExoPlaybackException: Source error
      at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:713)
      at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:683)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:223)
      at android.os.HandlerThread.run(HandlerThread.java:67)
  Caused by: androidx.media3.common.ParserException: Input does not start with the #EXTM3U header.{contentIsMalformed=true, dataType=4}
      at androidx.media3.exoplayer.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:262)
      at androidx.media3.exoplayer.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:69)
      at androidx.media3.exoplayer.upstream.ParsingLoadable.load(ParsingLoadable.java:184)
      at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
```

Earlier for some reason I was doing this, likely did this in early stages of impl, while testing things, but both ways got the same uri, just different crash trace... surprising.
```
    override fun onAddMediaItems(
        mediaSession: MediaSession,
        controller: MediaSession.ControllerInfo,
        mediaItems: List<MediaItem>
    ): ListenableFuture<List<MediaItem>> = Futures.immediateFuture(
        mediaItems.map { mediaItem ->
            mediaItem.buildUpon()
                .setUri(mediaItem.requestMetadata.mediaUri)
                .build()
        }
    )
```

**Comment by Shabinder** [comment]
Related to above new trace, maybe relevant:

Sharing a Image of the data-source its reading as from above uri only, in ParsingLoadbale.load, passing to `HlsPlaylistParser.parse`

see image below:
<img width="1498" alt="image" src="https://github.com/androidx/media/assets/44765050/dc3bda88-688c-4416-8286-5f67f65d9b95">

**Comment by icbaker** [comment]
The symptoms certainly suggest something is going wrong when the stream is being read/loaded. To rule out more things, can you please try removing all the caching from your ExoPlayer set-up? i.e. configure it with a `DataSource.Factory` that directly makes HTTP requests with no intermediate caches. From the code snippets provided above it seems your `DataSource.Factory` set-up is different between your "directly interact with ExoPlayer" case and your "use MediaController" case - and both seem to mention caching - so I'd suggest simplifying both of these to be completely identical (with no caching) to see if the issue continues to reproduce.

----

>```
> Caused by: androidx.media3.common.ParserException: Input does not start with the #EXTM3U header.{contentIsMalformed=true, dataType=4}
>```

What does the stream start with in this case? You can see by adding logging to `HlsPlaylistParser.checkPlaylistHeader`.

**Comment by Shabinder** [comment]
> What does the stream start with in this case? You can see by adding logging to HlsPlaylistParser.checkPlaylistHeader.

Check screenshot in this comment to see what stream was read like...
https://github.com/androidx/media/issues/1220#issuecomment-2018675132

**Comment by icbaker** [comment]
I see, thanks - that seems to confirm that something is going wrong loading, because I would expect an HLS playlist to be all/mostly ASCII characters, and that seems to have a lot of unrenderable bytes. To confirm that, what do you see if you add the same logging when successfully playing the stream?

Please also try removing caching as suggested above.

**Comment by Shabinder** [comment]
> To confirm that, what do you see if you add the same logging when successfully playing the stream?

Correct readable data from m3u8 is visible when started directly with Exoplayer, see below image:
<img width="1990" alt="image" src="https://github.com/androidx/media/assets/44765050/ca9c9d9f-3a5d-4445-87a7-561741b3ca3f">


as per your suggestion I tried disabling **my extra config of cache source**, and surprisingly it worked.

upon further digging, I can confirm, there was a issue in CacheKeyFactory, since I was returning same uri for parent m3u8 and all .ts files, fixing that, **fixed the issue**, but dont know **why behaviour was different when starting on Exoplayer, and when starting on MediaBrowser ?**

**Comment by icbaker** [comment]
Thanks for confirming you've resolved the issue.

> dont know **why behaviour was different when starting on Exoplayer, and when starting on MediaBrowser ?**

Hard to say I'm afraid, maybe something was actually different in the `MediaItem` instances that ended up being passed to the underlying player?
