### ISSUE TITLE
H264 video cannot be decoded - No error details available (libVLC plays it without issues)

### ISSUE THREAD

**Issue by cyberdreamandroid** [androidx/media#1228]
### Version

Media3 1.3.0

### More version details

Happens also on earlier versions of ExoPlayer

### Devices that reproduce the issue

Nvidia Shield 2019 with Android 11, Fire TV, more...

### Reproducible in the demo app?

Yes

### Reproduction steps

Try to stream attached file

### Expected result

Video plays

### Actual result

Does not start, no error details, only SourceError

### Media

https://4cf.de/video/h264.mp4

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment]
`ffprobe` throws a lot of errors for the provided video, mostly like:
```
[h264 @ 0x5618143a8c80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x5618143a8c80] decode_slice_header error
[h264 @ 0x5618143a8c80] no frame!
```

Chrome refuses to play it.

Given this, it seems likely that this video is not correctly formed.

ExoPlayer does not aim to report detailed error messages for every possible way video files can be malformed - so the behaviour you're observing is expected for broken media.
