### ISSUE TITLE
Demo apps for Audio Streams (ie Radios) show a picture instead of black screen

### ISSUE THREAD

**Issue by pooya-mohammadhossein** [androidx/media#1234]
Hi there,

First of all, keep up the great work on [Media3]!

This is a minor suggestion, and it's easy to implement in the demo apps. I propose adding an image (like a banner) when using Media3's audio stream instead of displaying a black screen. This visual cue would help ordinary users understand that the audio is playing even though they see a black screen, making the Media3 demo apps more visually appealing.

To reproduce the issue, simply try using any audio stream with a demo app, such as this one:

https://sarcheshmeh2-ssl.icdndhcp.com/stream

With the latest Media3 1.3.0 demo apps, you'll see a black screen while the audio plays in the background.

Thanks in advance for considering this suggestion!
Pooya

**Comment by rohitjoins** [comment]
Hi @pooya-mohammadhossein,

Banners are typically used to provide additional information or context about media content. If the media doesn't inherently include this information, adding a banner could confuse users or misrepresent the content.

The primary goal for demo apps in Media3 is to provide common use cases, which serves as starting point for developers to integrate the library into their own app. Please feel free to add your customizations as you see fit.
