### ISSUE TITLE
HLS: Video size changes when selecting a different quality track

### ISSUE THREAD

**Issue by alexarassat** [androidx/media#1236]
I was testing my app on many `Android 13/14` emulators (Pixel c 13 for example) and noticed the same behavior for each of those. When a different track is selected, the video size changes in a weird way. Then, I tested the demo app and noticed the same again.

[Screen_recoding.webm](https://github.com/androidx/media/assets/31002454/f0aea5b3-4572-4aa4-b158-48b3d262df20)

The issue can be reproduced only on `Android >= 13` emulators with `media3 >= 1.1.0` . Unfortunately, I do not own an Android 13 or 14 device to test with, and so i was wondering: Could this be an emulator only issue ?

**Comment by rohitjoins** [comment]
Hi @alexarassat,

Thank you for reporting the issue. I can confirm that this is an emulator only issue as the same is not reproducible on physical devices with Android version >=13.

Uploading screen-20240403-183402.mp4…
