### ISSUE TITLE
Transformer hangs if you pass a ClippingConfiguration of 0,0

### ISSUE THREAD

**Issue by jordond** [androidx/media#1242]
### Version

Media3 1.3.0

### Devices that reproduce the issue

- S22
- Z Fold 4
- Z Flip 5
- S24 Ultra
- Pixel 7 Pro

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Open the transformer demo
2. Use the default preset file
3. Enable "trim" and set it to start=0, end=0 
4. Hit export

### Expected result

I would expect Transformer would throw an error, or ignore the Clipping configuration.

### Actual result

Transformer hangs and never completes. As far as I can tell nothing is signalled to the `onComplete` or `onError`.

If you call `transformer.getProgress()`, eventually you will get a `Transformer.PROGRESS_STATE_UNAVAILABLE`. But Transformer continues to hang.

### Media

Not applicable

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by calren** [comment]
I would if we should just enforce the end position to be > 0 ? (https://github.com/androidx/media/blob/main/libraries/common/src/main/java/androidx/media3/common/MediaItem.java#L1972)

I'll let @droid-girl chime in

**Comment by kim-vde** [comment]
Thanks for reporting this. I'll make a change to throw when the clipping end time is equal to the clipping start time.

**Comment by jordond** [comment]
Awesome, thanks for the quick fix 💪

**Comment by kim-vde** [comment]
I will roll back my change (sorry) because we have discussed in team and there might be better ways to fix this. I will keep you updated!
