### ISSUE TITLE
Allow total override of onSetMediaItems/onAddMediaItems

### ISSUE THREAD

**Issue by OxygenCobalt** [androidx/media#1257]
### [REQUIRED] Use case description
Since the internal playback logic of `Player` is not advanced enough for my app's usecase, I want to forward all MediaItem playback events to my internal logic before they are sent back to the player. However, the overrides available like `onSetMediaItems` only allow me to *transform* `MediaItems` before they are sent to the player anyway, which prevents me from doing such. My complex logic cannot just be done on MediaItems, it requires transforming the MediaItems to the rest of my app's data model, performing some queue generation operations, performing a series of careful steps to initialize the player, and also delivering events using those internal data types to the rest of the app. 

 I want to be able to disable this transform behavior and just be able to control the player myself in these cases.

### Proposed solution

`onSetMediaItems`, `onAddMediaItems`, etc. should have another return option (such as null) that indicates "no, I set the player myself, no need to do anything".

I can make a PR for this since it seems pretty straightforward.

### Alternatives considered
It is possible to do all this logic in the transformation methods, but it would result in extremely fragile and bug-prone internal logic compared to being able to route it directly. I can also just vendor my own patches and keep them to myself.

**Comment by marcbaechinger** [comment]
I think there are multiple APIs available that may be helpful for your case below the `Callback` API of the session.

In cases when the media structure of an app differs considerably to the media structure of what a standard `ExoPlayer` it can be useful to implement `SimpleBasePlayer` that is backed by an `ExoPlayer` instance. You would kind of wrap an `ExoPlayer` instance inside the `SimpleBasePlayer` instance. This way you get in between the session and the player and you can for instance handle the `setMediaItems(List<MediaItem>)` after it went through the `onAddMediaItems/onSetMediaItems` callback. In this case you would just not override these and received the params in `SimpleBasePlayer`. `ForwardingPlayer` is a similar approach, but for your complex case `SimpleBasePlayer` is  probably a better choice. With both approaches ytou get in between the session and the actual player instance.

If you want to create your `MediaSource` in a complex way before it is added to the player as a consequence of for instance `setMediaItems(List<MediaItem>)` being called, you can inject your own `MediaSource.Factory` into the player when you build it with [`ExoPlayer.Builder`.](https://developer.android.com/reference/kotlin/androidx/media3/exoplayer/ExoPlayer.Builder#setMediaSourceFactory(androidx.media3.exoplayer.source.MediaSource.Factory)).

**Comment by OxygenCobalt** [comment]
I guess you are right about this. I'm already overriding `ForwardingPlayer`, so I'll just add more overrides that handle these cases. Will come back if I have more issues.

**Comment by OxygenCobalt** [comment]
Okay, this worked for me. Thanks.
