### ISSUE TITLE
MediaSession callback when a controller connects

### ISSUE THREAD

**Issue by Ethan1983** [androidx/media#1258]
Is there a way for a Media3's MediaSession to detect when a controller connects to it? This would be something similar to MediaSessionCompat's RegistrationCallback. This is for a custom protocol where session would send a message when a controller connects to it.

![Screenshot 2024-04-09 at 8 23 24 PM](https://github.com/androidx/media/assets/1020585/ee428859-4c2c-4196-b35a-d4801de966ed)

**Comment by marcbaechinger** [comment]
When you build the session, you can set a `Callback` that has a [`onConnect`](https://developer.android.com/reference/androidx/media3/session/MediaSession.Callback#onConnect(androidx.media3.session.MediaSession,androidx.media3.session.MediaSession.ControllerInfo)) method that is called when a controller connects.

The session demo implements this [here](https://github.com/androidx/media/blob/release/demos/session_service/src/main/java/androidx/media3/demo/session/DemoMediaLibrarySessionCallback.kt#L71-L89).

**Comment by Ethan1983** [comment]
Thanks, that works great.
