### ISSUE TITLE
HttpEngine should use RequiresExtension

### ISSUE THREAD

**Issue by yschimke** [androidx/media#1262]
HttpEngine is marked as @RequiresApi(34)

https://github.com/androidx/media/blob/d13a0f4ec62ca092b79746a5725b62a3244cc5b4/libraries/datasource/src/main/java/androidx/media3/datasource/HttpEngineDataSource.java#L69

But HttpEngine is based on extension versions

@RequiresExtension(extension = Build.VERSION_CODES.S, version = 7)

In practice trying to configure HttpEngine and pass it to HttpEngineDataSource, Android Studio wanted me to add both.

Should HttpEngineDataSource be changed to use RequiresExtension, so that it works on API 31 devices that have received the latest mainline versions?

**Comment by marcbaechinger** [comment]
Thanks for raising this!

I think we should do what makes the least hassle for our users. So if AS complains, we probably should do this.

For my education: with `@RequiresApi` I know how I as a developer can code and take different API levels into account. Like

```
if (Util.SDK_INT >= 21) {
  // here
}
```

How would that work with such a `@RequiresExtension` annotation? Do you know?

**Comment by yschimke** [comment]
```
SdkExtensions.getExtensionVersion(Build.VERSION_CODES.S) >= 7
```

**Comment by icbaker** [comment]
This was done in https://github.com/androidx/media/commit/91633e6ae3ca0a41652154f99477dc757981fd88, which was then reverted and then re-done in https://github.com/androidx/media/commit/00d1e70a346f542d849253b72b52cf0b638845fd.
