### ISSUE TITLE
onSearch - Notifying change when media being searched changes?

### ISSUE THREAD

**Issue by OxygenCobalt** [androidx/media#1273]
In my app, the media being accessed external browser may change at any moment if the internal library changes. Updating browsers is easy with typical `onSubscribe`/`onUnsubscribe` calls to specific `MediaItems`, however I'm not sure if/how I'm supposed to do the same with `onSearch` calls. 

`notifySearchResultChanged` is *worded* as if you should call it when the search results change, but it's only used to notify when the search has finished in all of the documentation and demos. Additionally, there's no easy way to track active search subscriptions since there's no corresponding `onUnsubscribe` method as there is for `MediaItems`.

Is it possible to get any more clarification over whether I should call `notifySearchResultChanged` when the media itself changes v.s. just calling it when the search finishes and leaving the returned media stale?

**Comment by marcbaechinger** [comment]
Yeah, I think you are right that the wording and the analogy of the wording to `notifyChildrenChanged` creates the impression that it's working the same.

As you discovered, the implementation doesn't intend this. Unlike the case of subscriptions for `parentId`, controllers issuing a search are not tracked in the same way.

I haven't tested, but from reading the code, this works in the sense that if you track the controller yourself and then call  `notifySearchResultChanged` for the controller, the message with the new, updated search result is sent to the controller. 

So the library doesn't restrict you to do so I'd think. If the controller is still connected, you can send such an update if this makes sense in the context of your app.

Can you confirm such updates work for your app?

**Comment by OxygenCobalt** [comment]
Okay, I can write my own tracking, but how can I know if a controller disconnects or otherwise unsubscribes from a search result @marcbaechinger?
