### ISSUE TITLE
Use ExoPlayer to access special metadata in DASH manifest

### ISSUE THREAD

**Issue by JonWatson** [androidx/media#1295]
Our video provider is encoding a `wallClockTime` value in the DASH manifests and we need to access this via `ExoPlayer`.

Does anyone know how to reference this values via the Window or other means?

DASH manifest example:

`<ProducerReferenceTime id="0" type="encoder" wallClockTime="2024-04-18T15:59:55.297Z" presentationTime="210000"`

**Comment by tonihei** [comment]
We do not parse the `ProducerReferenceTime` tags at the moment. If you want, feel free to open a pull request to add the parsing to `DashManifestParser` to write the information into the `Representation` class. 

For these additional tags that are not directly relevant for playback, the usual way to obtain them later is via `(DashManifest) exoPlayer.getCurrentTimeline().getWindow(currentIndex, new Window()).manifest`.

**Comment by JonWatson** [comment]
Using a custom DashManifest parser to decode the values in the manifest and then placing them in the Representation worked perfectly for us, allowing us to access from different layers.  Thank you!
