### ISSUE TITLE
Will there be a composition preview support  in the new 1.4.0 release

### ISSUE THREAD

**Issue by pawaom** [androidx/media#1296]
Will composition preview be supported in the new 1.4.0 release

I was going through the recent changes in code and came across this 

[Composition preview tests with surfaces](https://github.com/androidx/media/commit/1355f4734d7c4830c81009e642531fc7c6b0dc87)

Is Composition preview  available in 1.4.0 , is there any example how to use it

The file only provides only a SurfaceView  and TextureView  , how do we use it for Composition preview

**Comment by droid-girl** [comment]
Hi @pawaom, composition preview will not be available in the 1.4.0 release. 
Please keep an eye on release notes in the upcoming releases, we will make sure to mention composition preview and the APIs to use.
