### ISSUE TITLE
AdsMediaSource is causing Exoplayer IMA SDK library extension to not play ads every playback session

### ISSUE THREAD

**Issue by klapeyre-ensemble** [androidx/media#1298]
Related to Issue #1290 

Previously had asked about a way to setup CSAI with the Exoplayer IMA SDK extension library with HLS streams that require chunkless preparation to be set to false. I was provided an answer and initially tried it out and it seemed to work.

However, what I am seeing now is that ads are played maybe 25% of the time, when they should be played 100% of the time, a pre-roll on each VOD session. 

My current setup:

```
val dataSourceFactory = DefaultHttpDataSource.Factory()
    .setUserAgent(userAgent)
    .setDefaultRequestProperties(headers ?: emptyMap())

val mediaSourceFactory = HlsMediaSource.Factory(dataSourceFactory).setAllowChunklessPreparation(false)
val contentMediaSource = mediaSourceFactory
    .createMediaSource(MediaItem.fromUri(uri))

val mediaSource = AdsMediaSource(
    contentMediaSource,
    DataSpec(adsUri),
    streamId,
    mediaSourceFactory,
    adsLoader,
    playerView
)

val newPlayer = ExoPlayer.Builder(context)
    .setTrackSelector(DefaultTrackSelector(context))
    .setLoadControl(DefaultLoadControl())
    .build().also {
        this.player = it
    }

playerView.player = newPlayer
adsLoader.setPlayer(newPlayer)

newPlayer.setMediaSource(mediaSource)

if (!shouldRestart) {
    newPlayer.seekTo(position)
}
newPlayer.prepare()
newPlayer.setAudioAttributes(AudioAttributes.DEFAULT, true)
```

Original setup where we followed the IMA SDK extension library documentation, which gives us an ad 100% of the time:

```
val dataSourceFactory = DefaultDataSource.Factory(context)
val mediaSourceFactory = DefaultMediaSourceFactory(dataSourceFactory)
    .setLocalAdInsertionComponents({ adsLoader }, playerView)
val newPlayer = ExoPlayer.Builder(context).setMediaSourceFactory(mediaSourceFactory).build().also {
    player = it
}
playerView.player = newPlayer
adsLoader.setPlayer(newPlayer)

val mediaItem = MediaItem.Builder()
    .setUri(uri)
    .setAdsConfiguration(MediaItem.AdsConfiguration.Builder(adsUri).build())
    .build()

newPlayer.setMediaItem(mediaItem)

if (!shouldRestart) {
    newPlayer.seekTo(position)
}
newPlayer.prepare()
newPlayer.setAudioAttributes(AudioAttributes.DEFAULT, true)

initialized = true
```

Am I missing something here? This is running both on an API 31 emulator, and a FireTV OS6 device (API 25). Exoplayer and IMA SDK library version is 2.18.1

In these cases:
- shouldRestart is always false, can ignore
- streamId is a string related to the stream, so the adsId is the same for an individual stream URL
- adsLoader is created new each playback session

**Comment by marcbaechinger** [comment]
Can you please provide us with a test stream, an ad tag or let us know how to repro this with the main demo app.

If you're unable to share bug reports or test content publicly, please send them to android-media-github@google.com using a subject in the format "Issue #1298". Please also update this issue to indicate you’ve done this.

**Comment by klapeyre-ensemble** [comment]
Thanks @marcbaechinger - I sent in a test stream with ad tag to the provided email. Please let me know if you need anything else

**Comment by klapeyre-ensemble** [comment]
Hi @marcbaechinger - just wanted to check in and see if anything notable was found with the test stream? Many thanks

**Comment by klapeyre-ensemble** [comment]
Hi @marcbaechinger - checking in again, I tried following up with the android-media-github email too, but I did not hear back. I imagine the teams are busy, so I understand it may take some time. Many thanks

**Comment by klapeyre-ensemble** [comment]
Hi @marcbaechinger - checking in to see if anything had been discovered with this. Thanks!

**Comment by klapeyre-ensemble** [comment]
@marcbaechinger going to close this issue. We will take another crack at it sometime soon, and if we are unable to resolve or are still seeing issues, I will open a new issue.

**Comment by klapeyre-ensemble** [comment]
@marcbaechinger leaving a note here, I did manage to solve our issue. The media source factory provided to AdsMediaSource for the ad content was also being given the HLS media source factory (same one used for the content). However most ads come in mp4 or mpeg. I noticed in the debug logs that it was failing to load the ad with the following error: Linear assets were found in the VAST ad response, but none of them matched the video player's capabilities.

I instead passed in a progressive media source for the ad and that solved the problems. Ads are now coming through 100% of the time. 

In case anyone runs into this issue in the future:

```
                val dataSourceFactory = DefaultHttpDataSource.Factory()
                    .setUserAgent(userAgent)
                    .setDefaultRequestProperties(headers ?: emptyMap())
                val mediaSourceFactory = HlsMediaSource.Factory(dataSourceFactory)
                val contentMediaSource = mediaSourceFactory
                    .setAllowChunklessPreparation(false) // Increases startup time a bit to allow discovery of additional tracks, captions etc
                    .createMediaSource(MediaItem.fromUri(uri))

                AdsMediaSource(
                    contentMediaSource,
                    DataSpec(adsUri),
                    UUID.randomUUID().toString(),
                    ProgressiveMediaSource.Factory(dataSourceFactory), // Ads generally are mp4
                    adsLoader,
                    playerView
                )
```
