### ISSUE TITLE
Notification: Available buttons not updated on playlist change

### ISSUE THREAD

**Issue by tzugen** [androidx/media#130]
### Media3 Version

1.0.0-beta02

### Devices that reproduce the issue

All

### Devices that do not reproduce the issue

--

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. Add Media to the playlist
2. Play the media until the last item.
3. The notification won't display a "Skip to next" button (correct.)
4. Add a new mediaItem while the last song is playing.
5. The notification won't display a "Skip to next" button (incorrect.)

### Expected result

The notification won't display a "Skip to next" button (correct.)

### Actual result

 The notification won't display a "Skip to next" button (incorrect.)

### Media

N/A

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
I can reproduce this using the session demo app - thanks for reporting.
