### ISSUE TITLE
Incorrect mapping of Metadata to tag fields

### ISSUE THREAD

**Issue by bryanparadis** [androidx/media#1302]
### Version

Media3 main branch

### More version details

[These mappings](
https://github.com/androidx/media/blob/d833d59124d795afc146322fe488b2c0d4b9af6a/libraries/extractor/src/main/java/androidx/media3/extractor/mp4/MetadataUtil.java#L389C7-L394C55 ) are mixed up and are causing music to be sorted wrongly in Auxio Music Player. Artist Vitalism was showing up in among artists starting with D and it ended up due to having a sort album field in the mp4 tag with an album starting with D.

All 3 below seem to be mixed up.

```
      } else if (type == TYPE_SORT_ALBUM) {
        return parseTextAttribute(type, "TSO2", ilst);

```

TYPE_SORT_ALBUM should be TSOA

```
      } else if (type == TYPE_SORT_ARTIST) {
        return parseTextAttribute(type, "TSOA", ilst);
```

TYPE_SORT_ARTIST should be TSOP

```
      } else if (type == TYPE_SORT_ALBUM_ARTIST) {
        return parseTextAttribute(type, "TSOP", ilst);
```

TYPE_SORT_ALBUM_ARTIST should be TSO2

### Devices that reproduce the issue

Fairphone 4 running Android 13

### Devices that do not reproduce the issue

n/a

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. Grab a M4A file with sort album field in tag or add the field
2. Get the Metadata and check TYPE_SORT_ARTIST contains the sort album value

### Expected result

TYPE_SORT_ARTIST contains the value of the sort artist tag field

### Actual result

TYPE_SORT_ARTIST contains the value of sort album tag field

### Media

Not Applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by bryanparadis** [comment]
> > The ‘Album sort order’ frame defines a string which should be used instead of the album name (TALB) for sorting purposes. E.g. an album named “A Soundtrack” might preferably be sorted as “Soundtrack”.
> 
> > TYPE_SORT_ARTIST should be TSOP
> 
> This isn't obvious to me. We map `SHORT_TYPE_ARTIST` to `TPE1` which ID3 describes as:
> 
> > The ‘Lead artist/Lead performer/Soloist/Performing group’ is used for the main artist
> 
> Whereas the ID3 spec describes `TSOP` as (emphasis mine):
> 
> > The ‘Performer sort order’ frame defines a string which should be used instead of the performer (**TPE2**) for sorting purposes.
> 
> And TPE2 is defined as (and we map this to `TYPE_ALBUM_ARTIST`):
> 
> > The ‘Band/Orchestra/Accompaniment’ frame is used for additional information about the performers in the recording.
> 
> So is it just a typo in the ID3 spec and it should just say "[...] instead of the performer (**TPE1**) [...]"?
> 

Did you mean to write SHORT_TYPE_ARTIST as I was referring to TYPE_SORT_ARTIST? 

All of these are different artist/performers
[TPE1](https://mutagen-specs.readthedocs.io/en/latest/id3/id3v2.4.0-frames.html?highlight=tsop#tpe1) Lead performer(s)/Soloist(s)
[TPE2](https://mutagen-specs.readthedocs.io/en/latest/id3/id3v2.4.0-frames.html?highlight=tsop#tpe2) Band/orchestra/accompaniment
[TPE3](https://mutagen-specs.readthedocs.io/en/latest/id3/id3v2.4.0-frames.html?highlight=tsop#tpe3) Conductor/performer refinement
[TPE4](https://mutagen-specs.readthedocs.io/en/latest/id3/id3v2.4.0-frames.html?highlight=tsop#tpe4) Interpreted, remixed, or otherwise modified by

This would be I believe what most people should be using for Artist value in applications?
[TPE1](https://mutagen-specs.readthedocs.io/en/latest/id3/id3v2.4.0-frames.html?highlight=tsop#tpe1) Lead performer(s)/Soloist(s)

and then this would be your alternative sort value
[TSOP](https://mutagen-specs.readthedocs.io/en/latest/id3/id3v2.4.0-frames.html?highlight=tsop#tsop) Performer sort order

Let me know if I have misunderstood what you have wrote.

> > TYPE_SORT_ALBUM_ARTIST should be TSO2
> 
> I couldn't see TSO2 in the page I linked above, but I do see it here: https://wiki.hydrogenaud.io/index.php?title=Foobar2000:ID3_Tag_Mapping (and there TSOP is more clearly linked to TPE1, and TPE2 is more clearly considered 'album artist').
> 
> I'll send a change based on the hydrogenaud.io link.

It is listed on mutagen-specs in the Off-Spec Frames section:

https://mutagen-specs.readthedocs.io/en/latest/id3/id3v2-other-frames.html?highlight=tso2

I am not sure how supported it is in ID3 or not as it's not my area of expertise. It looks to be referenced a fair number of places.

**Comment by bryanparadis** [comment]
Everything that I can find while searching online shows TPE1 as the main artist and TPE2 as additional/album artist.

https://mutagen-specs.readthedocs.io/en/latest/id3/id3v2.4.0-frames.html?highlight=tsop#tpe1

> TPE1
>   The ‘Lead artist/Lead performer/Soloist/Performing group’ is used for the main artist.

> TPE2
>   The ‘Band/Orchestra/Accompaniment’ frame is used for additional information about the performers in the recording. 

here as well https://docs.mp3tag.de/mapping/#albumartist

**Comment by icbaker** [comment]
> Edit: TPE2 must be a typo. Why would they not use the main field for artist/performer? I think that TSO2 is what is used as an alternative sort for TPE2. Artist = TPE1 and Album Artist = TPE2

Yeah, this makes sense to me - sorry my comment was a bit confusing.

> It is listed on mutagen-specs in the Off-Spec Frames section:

Ah great, thanks for that link, I hadn't seen that.

**Comment by icbaker** [comment]
This should be fixed by the commit above.

**Comment by bryanparadis** [comment]
> > Edit: TPE2 must be a typo. Why would they not use the main field for artist/performer? I think that TSO2 is what is used as an alternative sort for TPE2. Artist = TPE1 and Album Artist = TPE2
> 
> Yeah, this makes sense to me - sorry my comment was a bit confusing.

No worries!

> > It is listed on mutagen-specs in the Off-Spec Frames section:
> 
> Ah great, thanks for that link, I hadn't seen that.

Glad I could help.

Thanks for fixing this!
