### ISSUE TITLE
MediaMetadata doesn't include some ID3 tags

### ISSUE THREAD

**Issue by akshdeep-singh** [androidx/media#1305]
### Version

Media3 1.3.1

### Devices that reproduce the issue

Pixel 3a Emulator API 34 

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. Play any mp3 file which contains id3 tags with ids `TCON`, `COMM`, etc.
2. Check values in `onMediaMetadataChanged` and `onTracksChanged`

```kotlin
override fun onTracksChanged(tracks: Tracks) {
    tracks.groups.forEach { group ->
        for (i in 0 until group.length) {
            group.mediaTrackGroup.getFormat(i).metadata?.let { metadata ->
                for (j in 0 until metadata.length()) {
                    metadata.get(j).let {
                        if (it is TextInformationFrame) {
                            println("${it.id} ${it.values}") // TCON [<value>]
                        }

                        if (it is CommentFrame) {
                            println("${it.id} ${it.text}") // COMM <value>
                        }
                    }
                }
            }
        }
    }
}

override fun onMediaMetadataChanged(mediaMetadata: MediaMetadata) {
    println("genre: ${mediaMetadata.genre}") // null
    println("description: ${mediaMetadata.description}") // null
}
```

### Expected result

Value of `MediaMetadata.genre` is filled with `TCON` frame content
Value of `MediaMetadata.description` is filled with `COMM` frame content

### Actual result

MediaMetadata values described above are null

### Media

Sample MP3 [link](https://www.sikhsangeet.com/audio/Shabad%20Kirtan/Harjinder%20Singh%20(Sri%20Nagar%20Wale)/Teri%20Bhagat%20Na%20Chhodon/01%20-%20Harjinder%20Singh%20-%20Nindo%20Nindo%20Mauko%20-%20SikhSangeet.Com.mp3)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment]
Please can you try listening to [`Player.Listener.onMetadata`](https://developer.android.com/reference/androidx/media3/common/Player.Listener#onMetadata(androidx.media3.common.Metadata))? That's where I would expect this to be emitted, as described here: https://developer.android.com/media/media3/exoplayer/retrieving-metadata#during-playback

**Comment by icbaker** [comment]
I played the provided link in the [demo app](https://developer.android.com/media/media3/exoplayer/demo-application) and I see `COMM` and `TCOM` logged as part of the metadata in `onTracksChanged` (this logging is [part of `EventLogger`](https://github.com/androidx/media/blob/d833d59124d795afc146322fe488b2c0d4b9af6a/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/util/EventLogger.java#L305-L320), see https://developer.android.com/media/media3/exoplayer/debug-logging):

```
tracks [eventTime=1.27, mediaPos=0.00, window=0, period=0
  group [
    [X] Track:0, id=null, mimeType=audio/mpeg, bitrate=128000, channels=2, sample_rate=44100, supported=YES
  ]
  Metadata [
    COMM: language=xxx, description=
    TCOM: description=null: values=[SikhSangeet.com]
    TCON: description=null: values=[Shabad Kirtan]
    TCOP: description=null: values=[SikhSangeet.com]
    TENC: description=null: values=[SikhSangeet.com]
    WXXX: url=http://SikhSangeet.com
    TALB: description=null: values=[Teri Bhagat Na Chhodon]
    TIT2: description=null: values=[Nindo Nindo Mauko]
    TOPE: description=null: values=[Harjinder Singh (Sri Nagar Wale)]
    TPE1: description=null: values=[Harjinder Singh (Sri Nagar Wale)]
    TRCK: description=null: values=[01]
  ]
]
```

**Comment by akshdeep-singh** [comment]
yes, `onTracksChanged` gets called but `onMetadata` doesn't, but my actual point of reporting this issue was that information such as "genre" is very basic which should be filled in `MediaMetadata`, right?

**Comment by icbaker** [comment]
Ah gotcha, I misunderstood your original comment.

> Value of `MediaMetadata.genre` is filled with `TCON` frame content

This makes sense, based on my reading of the [definition of the `TCON` frame here](https://mutagen-specs.readthedocs.io/en/latest/id3/id3v2.4.0-frames.html#tcon), though we probably don't want to naively popoulate the string directly and instead optionally do the numeric resolution described there, and somewhat already implemented here (although there may be an off-by-one bug there, I'm going to dig a bit further):
https://github.com/androidx/media/blob/d833d59124d795afc146322fe488b2c0d4b9af6a/libraries/extractor/src/main/java/androidx/media3/extractor/mp4/MetadataUtil.java#L514-L527

----

> Value of `MediaMetadata.description` is filled with `COMM` frame content

I'm not sure sure about this. [`COMM` is described in a very free-form way](https://mutagen-specs.readthedocs.io/en/latest/id3/id3v2.4.0-frames.html#comm), in particular there might be more than one, so I don't think it maps very clearly to `MediaMetadata.description`. I'm not sure that any of [these ID3 frame types](https://mutagen-specs.readthedocs.io/en/latest/id3/id3v2.4.0-frames.html) really contain a 'description'.

---

I'll prepare a change to map `TCON` to `MediaMetadata.genre`.

**Comment by icbaker** [comment]
This is now implemented by the commits referenced above.
