### ISSUE TITLE
Forcing the MediaSession to reload metadata/bitmap?

### ISSUE THREAD

**Issue by OxygenCobalt** [androidx/media#1306]
The images that my app will show in the MediaSession may change if certain settings are changed, so ideally I also want this change to be reflected in the MediaSession's active metadata (Not the MediaItems, their images are not settings-dependent). Is there any way to force the MediaSession to reload it's metadata & notification in this case? I'm vendoring Media3, so if there's an internal method that allows me to do that, then that would also work.

**Comment by tianyif** [comment]
Hi @OxygenCobalt,

Could you please give me an example of the "settings" that you mentioned? Do you mean that you want the library to deal with the change of the settings and trigger a reload of the metadata / bitmap?

**Comment by OxygenCobalt** [comment]
@tianyif Basically, my users can change the way my app loads cover art, such as:

1. Switching out the data source (Higher-Quality but slow Media3 extraction vs. Fast MediaStore cover art)
2. Cropping the image to 1:1, or leaving it uncropped.

These settings are stored w/`SharedPreferences` and are very app-specific, so I don't think Media3 should directly support responding to the updates, I should just be able to force a metadata update myself in my code when the settings change.

**Comment by OxygenCobalt** [comment]
Two questions @tianyif:

1. I forgot to mention that I'm actually using a custom `BitmapLoader` based on Coil, so two identical metadatas could feasibly produce different bitmaps at different times due to some internal technical reasons. I think I can just hack around this by adding a randomly generated field to `extras` to fiddle force an inequality.
2. Would replacing the MediaItem not cause playback to stutter at all? I remember encountering that a long time ago when working with ExoPlayer.

**Comment by tianyif** [comment]
@OxygenCobalt,

1. I'm not sure how Coil is going to work, but please be aware that the [equality check](https://github.com/androidx/media/blob/release/libraries/common/src/main/java/androidx/media3/common/MediaMetadata.java#L1153) of `MediaMetadata` doesn't consider the content in `extras`. It just compares the nullness of it.
2. ExoPlayer checks the new media items with [`canUpdateMediaSourcesWithMediaItems`](https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/ExoPlayerImpl.java#L755) if the `MediaSource`s in the player can be directly updated with those items. The [decision logic](https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/source/MediaSource.java#L437) varies for different source implementation logic, but in general, if you're just changing the metadata, it shouldn't cause playback to stutter. However, if you're changing something fundamental (eg. the media url), then it will definitely cause the interruption as the player has to prepare the new media.

**Comment by OxygenCobalt** [comment]
> I'm not sure how Coil is going to work, but please be aware that the [equality check](https://github.com/androidx/media/blob/release/libraries/common/src/main/java/androidx/media3/common/MediaMetadata.java#L1153) of MediaMetadata doesn't consider the content in extras. It just compares the nullness of it.

This actually causes a lot of issues beyond the scope of this issue since for architectural reasons I need to marshal around data in the extras field, which could easily lead to issues if the extras are not being differentiated. Is it safe for me to just patch in an extras equality check somehow? Or is it not present because it has weird effects?

**Comment by OxygenCobalt** [comment]
> I'm not sure how Coil is going to work, but please be aware that the [equality check](https://github.com/androidx/media/blob/release/libraries/common/src/main/java/androidx/media3/common/MediaMetadata.java#L1153) of MediaMetadata doesn't consider the content in extras. It just compares the nullness of it.

This actually causes a lot of issues beyond the scope of this issue @tianyif. For architectural reasons I need to marshal around data in the extras field, and if MediaMetadata is not being differentiated on them that could easily cause some extreme issues, including making this specific use-case non-viable. I'll try my best to just avoid using extras, but if that's not possible, is it safe for me to just patch in an extras equality check somehow? Or is that not present because it has weird effects?

**Comment by tianyif** [comment]
@OxygenCobalt,

From the [current context](https://github.com/androidx/media/blob/release/libraries/common/src/main/java/androidx/media3/common/MediaMetadata.java#L1086-L1092), it looks like we didn't add the `extras` equality check for its complexity. This is discussable though. But I also need to make sure that the equality check can definitely solve your problem. One question comes into me is - how would you update the notification with the new bitmap?

**Comment by OxygenCobalt** [comment]
> One question comes into me is - how would you update the notification with the new bitmap?

Basically @tianyif, I overloaded `BitmapLoader` to disable `decodeBitmap` and `loadBitmap` and directly overloaded `loadBitmapFromMetadata` to do the following:

1. Read the identifier I added to MediaMetadata.extras (I can also do the same with MediaMetadata.mediaId)
2. Retrieve the music data from my internal systems that actually contains the cover information I need.
3. Check the coil image cache immediately to see if we've loaded it prior. If so, immediately return it.
4. Otherwise get coil to load the image and return the a future that will resolve when it's done.

There are other ways I can go about this (Notably I can get rid of steps 1 and 2 and just marshal the cover data itself), but the issue remains that *any data type I attempt to marshal to `BitmapLoader` will stay the same between settings changes*. This is why I need to force an inequality through an `extras` field that has maybe the current image setting configuration. But `extras` isn't compared, so either I add an inequality check for `extras` or I cram a force inequality into some other `MediaMetadata` field which could easily go wrong.

**Comment by OxygenCobalt** [comment]
> So you're going to replace the media item with a metadata different in extras right? Then the media session will be triggered to reload the bitmap, then followed by what you just described, and then update the media notification. Sorry for the confusion, I misunderstood that you were going to replace the media item. Cool, I shall discuss internally with the team on the equality check of the extras.

Yeah, basically. Thanks. For now I'll just patch in a very primitive equality check using my `extras` fields since you said it was complicated to compare `Bundle`.

**Comment by OxygenCobalt** [comment]
> For your case, how do you think of taking advantage of the artworkUri and possibly add the query parameters to it when the settings are changed? This will trigger the reload of bitmap after you replace the MediaItem with the new artworkUri, and your custom BitmapLoader can have some logic to triage the query parameters before (or when) you send the request to your data source. Please let me know if that can work

I *believe* that will work. Not fully sure. Will confirm.

**Comment by OxygenCobalt** [comment]
Hey @tianyif, I actually don't believe this will work. There's actually a third quirk with the way I use MediaItems. While the cover of the *playing* `MediaItem` is going to be extracted with the custom `BitmapLoader`, the cover of queue/browser `MediaItem`s are provided by `artworkUri`. Since the currently playing `MediaItem` is also a queue `MediaItem`, I am unable to modify `coverUri` to use my custom format. `artworkData` might work, but only if it's used in the equality **and** `artworkUri` is prioritized over it. I really don't want to risk it though. Is there anything else I can do? If no, I'm just patching in a thin `extras` equality that will compare `cover` myself in my vendored fork.

**Comment by OxygenCobalt** [comment]
Okay, so I just patched in my own equality checks, which works for me. My use case is too niche and weird for media3 to be justified in handling it.
