### ISSUE TITLE
Full screen button don't change on auto rotate of device in exo player with jetpack compsoe.

### ISSUE THREAD

**Issue by sid1605** [androidx/media#1309]
### Version

Media3 1.3.1

### More version details

media3_version: 1.3.1

### Devices that reproduce the issue

all android devices

### Reproducible in the demo app?

Yes

### Reproduction steps

1- add setFullScreenButtonClickListener in `PlayerView` inside `AndroidView`, it will show a fullscreen button that toggles into exit full screen button on click. and i do  -  

```
     if (!isFullscreen) {
                                (context as? Activity)?.requestedOrientation =
                                    ActivityInfo.SCREEN_ORIENTATION_USER_LANDSCAPE
                                isFullscreen = true
                            } else {
                                (context as? Activity)?.requestedOrientation =
                                    ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED
                                isFullscreen = false
                            }
```

this works when i click on button then its orientation changes. 

Problem: how to change button (from full screen to exit full screen and vice versa) when screen auto rotate .
![Screenshot_2024-04-24-10-52-50-63_6acdc9aa7b878f572c44a02942cb6f60 1](https://github.com/androidx/media/assets/137288149/51365c4b-96fc-4483-a86d-c524ed7730a0)
![Screenshot_2024-04-24-11-08-04-50_6acdc9aa7b878f572c44a02942cb6f60 1](https://github.com/androidx/media/assets/137288149/872c84cb-11bc-48b6-b640-e47033161997)

  

### Expected result

![Screenshot_2024-04-24-11-11-30-04_6acdc9aa7b878f572c44a02942cb6f60 1](https://github.com/androidx/media/assets/137288149/adffd257-701c-40b9-83c4-cb3665bf7f91)

### Actual result

![Screenshot_2024-04-24-11-08-04-50_6acdc9aa7b878f572c44a02942cb6f60 1](https://github.com/androidx/media/assets/137288149/f935a3d4-86c9-4bd7-8e1b-9ccff6d498a0)

### Media

the video is drmn protected hence background is black

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by sid1605** [comment]
this happen when auto rotate, but when rotate onclick means of full screen button then it is okay

**Comment by oceanjules** [comment]
This looks similar to https://github.com/androidx/media/issues/184 and https://github.com/google/ExoPlayer/issues/10391#issuecomment-1336676267, however I am struggling to understand your reproduction steps. 

* Do you start off in Portrait mode and rotate your phone, causing the video to change to Landscape automatically?
* Do you press the fullscreen button before or after rotation?

The fullscreen button might be losing its state (i.e. it is "forgetting" that it already moved from smallScreen->fullScreen) and defaulting back to its original value. It is hard to analyse this further without seeing more of your code.
