### ISSUE TITLE
10bit H265 HVEC video link mkv not working

### ISSUE THREAD

**Issue by 676blue** [androidx/media#1311]
### Version

Media3 1.3.1

### More version details

implementation(libs.androidx.media3.exoplayer)
    implementation(libs.androidx.media3.ui)
    implementation(libs.androidx.media3.cast)
    implementation(libs.androidx.media3.exoplayer.dash)
    implementation(libs.androidx.media3.exoplayer.hls)
    implementation(libs.androidx.media3.datasource.cronet)
    implementation(libs.androidx.media3.datasource.okhttp)
implementation(files("libs/media3-decoder-ffmpeg-1.3.1.aar"))

### Devices that reproduce the issue

Android Emulator 34

### Reproducible in the demo app?

Yes

### Reproduction steps

val renderersFactory = DefaultRenderersFactory(this)
        renderersFactory.setExtensionRendererMode(DefaultRenderersFactory.EXTENSION_RENDERER_MODE_PREFER)
        exoPlayer = ExoPlayer.Builder(this, renderersFactory).build()

        binding.player.player = exoPlayer

        val mediaItem = MediaItem.Builder()
            .setUri("https://next.rentrakhq.com/index.php/s/9srNqAWrTm54SAD/download/test.mkv")
            .build()

        exoPlayer.setMediaItem(mediaItem)
        exoPlayer.prepare()
        exoPlayer.play()

### Expected result

10bit H265 HVEC video link mkv worked successfully 

### Actual result

Video codec error
  android.media.MediaCodec$CodecException: Error 0xe
NoSupport [codec.profileLevel, hvc1.2.4.L120, video/hevc] [c2.android.hevc.decoder, video/hevc] [emu64a, sdk_gphone64_arm64, Google, 34]
Playback error
  androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=1, format=Format(1, null, null, video/hevc, hvc1.2.4.L120, -1, und, [1920, 1080, -1.0, null], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES

### Media

https://next.rentrakhq.com/index.php/s/9srNqAWrTm54SAD/download/test.mkv
[logs.txt](https://github.com/androidx/media/files/15091709/logs.txt)
[Media3MKVIssueSourceCode.zip](https://github.com/androidx/media/files/15091711/Media3MKVIssue.zip)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by tianyif** [comment]
Hi @676blue,

I can reproduce this with Galaxy Nexus API 34 emulator, but not with the Pixel 6 pro real device. I saw [`format_supported=NO_EXCEEDS_CAPABILITIES`](https://github.com/androidx/media/blob/release/libraries/common/src/main/java/androidx/media3/common/C.java#L1482) in the exception that both of us got. This suggests that the formats with the same MIME type are supported, but the properties (eg. resolution) of this format exceed the declared capabilities, then a playback failure is expected.
