### ISSUE TITLE
Does exoplayer support AFR(Auto frame rate） function

### ISSUE THREAD

**Issue by DorisGM** [androidx/media#1318]
Our app use  Exoplayer as player。 I want to know  does exoplayer support AFR(Auto frame rate） function?   c
if not, how can i  support it ?

**Comment by microkatz** [comment]
Hello @DorisGM,

I believe that you are referring to the display adjusting its refresh rate depending on the frame rate of the content? ExoPlayer does support seamless frame rate switching by default. You can read about it in this [blog post](https://medium.com/androiddevelopers/prep-your-tv-app-for-android-12-9a859d9bb967#:~:text=Android%2012%20developer,app%20for%20compatibility). It also provides some pointers for if you want to customize the functionality. 

By default, after each frame is processed to be skipped, dropped or rendered, the `VideoFrameReleaseControl.getFrameReleaseAction` method calls `updateSurfaceMediaFrameRate` to "update the media frame rate that's used to calculate the playback frame rate of the current surface. If the frame rate is updated then `updateSurfacePlaybackFrameRate` is called to update the surface.

Hope that answer your question!

**Comment by DorisGM** [comment]
Thanks。I‘ll check it.
