### ISSUE TITLE
Does Exoplayer support Tag/Label for subtitles names inside of DASH .mpd manifest?

### ISSUE THREAD

**Issue by Crazyvod00** [androidx/media#1319]
Hi guys,
as the title suggests, I would like to know if exoplayer supports tag/label for subtitle names.

Using an exoplayer based app I can set both forced and normal subtitles in the DASH manifest. Unfortunately, however, I cannot find a way to split subtitles by name in case they have the same language. Here an example of my subtitles part inside the mpd.

        <AdaptationSet mimeType="text/vtt" lang="it" accessibility="main" forced="true" default="true">
            <Representation id="forced" bandwidth="8000">
                <BaseURL>URL.vtt</BaseURL>
            </Representation>
        </AdaptationSet>
        <AdaptationSet mimeType="text/vtt" lang="it" accessibility="main" forced="false" default="false">
            <Representation id="regular" bandwidth="8000">
                <BaseURL>URL.vtt</BaseURL>
            </Representation>
        </AdaptationSet>
        
In case it is not yet available, is it possible to support a tag/label to index different subs by name in the future?

Now for example I have as output for subtitles:

None
Italiano (automatically detected because they are forced)
Italiano

The target would be instead:
None
Italiano - Forced
Italiano - Regular

Perhaps the solution already exists but I am ignorant and do not know how to find it.

**Comment by icbaker** [comment]
You can also inspect [`Format.roleFlags`](https://developer.android.com/reference/androidx/media3/common/Format#roleFlags()) for some of those parameters you've listed.

I think my answer above resolves your question - possibly combined with being able to [customize track names in the UI](https://developer.android.com/reference/androidx/media3/ui/TrackNameProvider)?

If you still have questions, please can you add some more detail.
