### ISSUE TITLE
Notification is not showing with MediaStyle when trying to play videos in background

### ISSUE THREAD

**Issue by Shvet** [androidx/media#1320]
I am trying to play videos from external storage in background, as it works fine and plays but in notification it shows App is running title and i can not find any other buttons related to media. 
I am using [https://github.com/RcuDev/SimpleMediaPlayer](SimpleMediaPlayer) for testing.
 ```
 val mediaItem: MediaItem =
                MediaItem.Builder()
                    .setMediaId(audioModel.id.toString())
                    .setUri(audioModel.filePath)
                    .setTag(audioModel)
                    .setMediaMetadata(
                        MediaMetadata.Builder()
                            .setIsBrowsable(true)
                            .setMediaType(MediaMetadata.MEDIA_TYPE_FOLDER_ALBUMS)
                            .setArtworkUri(Uri.parse("https://plus.unsplash.com/premium_photo-1664361480105-33afc4559c40?q=80&w=2123&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"))
                            .setIsPlayable(true)
                            .setTitle(audioModel.fileName)
                            .setAlbumArtist(audioModel.directory)
                            .setAlbumTitle(audioModel.fileName)
                            .setDisplayTitle(audioModel.directory)
                            .build()
                    ).build()
```
MediaService Code:

```
@AndroidEntryPoint
class SimpleMediaService : MediaSessionService() {
    @Inject
    lateinit var mediaSession: MediaSession

    @Inject
    lateinit var notificationManager: SimpleMediaNotificationManager
    override fun onGetSession(controllerInfo: MediaSession.ControllerInfo): MediaSession {
        return mediaSession
    }

    @OptIn(UnstableApi::class)
    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        notificationManager.startNotificationService(
            mediaSessionService = this,
            mediaSession = mediaSession
        )

        return super.onStartCommand(intent, flags, startId)
    }

    override fun onDestroy() {
        super.onDestroy()
        mediaSession.run {
            release()
            if (player.playbackState != Player.STATE_IDLE) {
                player.seekTo(0)
                player.playWhenReady = false
                player.stop()
            }
        }
    }
}

```
I have tried to put static data for testing, if it could show media style notification. But it is not showing. Screenshot is attached below.

![Screenshot_20240427_181006](https://github.com/androidx/media/assets/7760064/26b749d8-3eee-41f8-9b31-72714192b208)

**Comment by tonihei** [comment]
`MediaSessionService` is handling the media notification automatically without any action required from you. Could you try removing your custom notification handling code shown above?  See https://developer.android.com/media/media3/session/background-playback#notification

**Comment by Shvet** [comment]
I did removed it, but it wont show notification and when i will try to stop service it will give me error on not being foreground service.

**Comment by tonihei** [comment]
I'm afraid I can't really provide any useful hints or information without knowing more details. If there is an issue with stopping the service correctly, please also refer to our lifecycle guide here: https://developer.android.com/media/media3/session/background-playback#service-lifecycle

Otherwise, if you think there is something wrong with the default notification or you unexpected exception, please provide detailed reproduction steps or projects that allow us to see the issue as well.  Thanks!
