### ISSUE TITLE
"No periods found. Downloading entire stream" for mp4 media

### ISSUE THREAD

**Issue by patildnyaneshwar** [androidx/media#1321]
Hi, 

I'm using the same code base as the demo app. Here with HLS media I'm able to download the video for offline however if change it to mp4 media (ProgressiveMediaSource), I get the "No periods found. Downloading entire stream." means all the time for mp4 media I get DownloadHelper.periodCount zero(0). 

code for ProgressiveMediaSource which is not working. 
```
 val defaultHttpDataSourceFactory = DemoUtil.getDataSourceFactory(this)
            val defaultMediaSourceFactory =  ProgressiveMediaSource.Factory(defaultHttpDataSourceFactory!!)

            // Set the MediaSource.Factory on the Player.
            player =
                ExoPlayer.Builder(this).setMediaSourceFactory(defaultMediaSourceFactory).build()
```
code for HlsMediaSource work as expected. 
```
 val defaultHttpDataSourceFactory = DemoUtil.getDataSourceFactory(this)
            val defaultMediaSourceFactory =  HlsMediaSource.Factory(defaultHttpDataSourceFactory!!)

            // Set the MediaSource.Factory on the Player.
            player =
                ExoPlayer.Builder(this).setMediaSourceFactory(defaultMediaSourceFactory).build()
```
code for download
```
  btnDownload.setOnClickListener {
            val renderersFactory = DemoUtil.buildRenderersFactory(this)
            downloadTracker?.toggleDownload(supportFragmentManager, mediaItem, renderersFactory)
        }
```

**Comment by tonihei** [comment]
"No periods found. Downloading entire stream." is expected for progressive files (like MP4). These are just simple files with no additional structure as provided by DASH or HLS manifests. 

The demo app works by just calling `downloadHelper.getDownloadRequest` in this case without showing a track selection dialog. 

Could you clarify if this matches your observations and if not, highlight exactly which steps we have to follow, what you expect to see and what currently happens? Thanks!
