### ISSUE TITLE
Play pause problem

### ISSUE THREAD

**Issue by ps8303383** [androidx/media#1324]
<LinearLayout
        android:id="@+id/controlRack"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        android:gravity="center"
        android:orientation="horizontal">

        <ImageButton
            android:id="@id/exo_rew"
            style="@style/PlayerControlButtonBaseStyle.RewButton" />

        <ImageButton
            android:id="@id/exo_play"
            style="@style/PlayerControlButtonBaseStyle.PlayButton"
            android:layout_width="100dp"
            android:layout_marginLeft="@dimen/player_control_play_pause_margin"
            android:layout_marginRight="@dimen/player_control_play_pause_margin" />

        <ImageButton
            android:id="@id/exo_pause"
            style="@style/PlayerControlButtonBaseStyle.PauseButton"
            android:layout_width="100dp"
            android:layout_marginLeft="@dimen/player_control_play_pause_margin"
            android:layout_marginRight="@dimen/player_control_play_pause_margin" />

        <ImageButton
            android:id="@id/exo_ffwd"
            style="@style/PlayerControlButtonBaseStyle.FfwdButton" />
</LinearLayout>

style="@style/PlayerControlButtonBaseStyle.PlayButton
style="@style/PlayerControlButtonBaseStyle.PauseButton
above code is working on exoplayer2 what new code on play pause exoplayer media3

**Comment by oceanjules** [comment]
The renaming was as follows:

| exo2 | media3 |
|---|---|
| PlayerControlView | LegacyPlayerControlView |
| StyledPlayerControlView | PlayerControlView |
| StyledPlayerView | PlayerView |

Which means `PlayerControlView` are not equivalent between exoplayer2 and media3. Can you confirm which class you are using?
