### ISSUE TITLE
Sometime I am getting error from exoplayer "Invalidate date format"

### ISSUE THREAD

**Issue by gautamlook** [androidx/media#1326]
### Version

Media3 1.3.1

### More version details

Media3 1.3.1

### Devices that reproduce the issue

AndroidTV
FireTV

### Reproducible in the demo app?

Yes

### Reproduction steps

play shared media.

### Expected result

The media should be play

### Actual result

Invalidate date format

### Media

URL : https://30a-tv.com/feeds/zeasn/30atv.m3u8

sometime , I am getting below error from exoplayer but shared url is working other platform like ROKU , WEB and VLC 
Playback error androidx.media3.exoplayer.ExoPlaybackException: Source error at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:713) at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:683) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:211) at android.os.HandlerThread.run(HandlerThread.java:65) Caused by: androidx.media3.common.ParserException: Invalid date/time format: 2024-03-28T07:35:37R{contentIsMalformed=true, dataType=1} at androidx.media3.common.util.Util.parseXsDateTime(Util.java:1700) at androidx.media3.exoplayer.hls.playlist.HlsPlaylistParser.parseMediaPlaylist(HlsPlaylistParser.java:851) at androidx.media3.exoplayer.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:281) at androidx.media3.exoplayer.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:69) at androidx.media3.exoplayer.upstream.ParsingLoadable.load(ParsingLoadable.java:184) at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:764)

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by tonihei** [comment]
Based on the error the String `2024-03-28T07:35:37R` was listed as the `#EXT-X-PROGRAM-DATE-TIME`. The `R` at the end caused the parsing to fail. As far as I can tell, this extra letter isn't allowed for a valid ISO/IEC 8601:2004 date/time tag. Is this letter expected, and if so, what does it represent?
