### ISSUE TITLE
"Usage not a subset." error log spammed 20 times per second. Only happens on certain device.

### ISSUE THREAD

**Issue by distinctdan** [androidx/media#1328]
### Version

Media3 1.2.0

### Devices that reproduce the issue

Microtouch M1-215IC-AA2 running Android 13

### Devices that do not reproduce the issue

Microtouch IC-215P-AA2 running Android 10

### Reproducible in the demo app?

Unknown

### Reproduction steps

I'm playing an RTSP stream on this microtouch tablet, and I'm seeing the following error log spammed maybe 25 times per second. Our app streams multiple live RTSP streams, in this case, I have 5 players running onscreen. We haven't seen this error on other devices, so it appears to be specific to either Android 13 or this microtouch. However, there's no stack trace to indicate where it's coming from, and I haven't been able to find this error in the Media3 code base either. The streams all play correctly, but the error log is concerning. Any ideas where this is coming from?

```
2024-04-29 14:05:39.682  4034-4553  my.package         com.company.my.package              E  Usage not a subset. Buffer usage = 0x100, Descriptor usage = 0x900
```

### Expected result

No error logs, or at least a stack trace or indication of where it's coming from.

### Actual result

Lots of error logs

### Media

Any RTSP stream, don't know of a free one, sorry.

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by distinctdan** [comment]
Update: I've determined that this only happens after a player is released and a new player is created. We do this for several reasons, such as when a user enters edit mode. Here's the sequence of events:
 - Initial page load, players are created and started, no errors.
 - User enters edit mode, we stop and release existing players. No errors are thrown.
 - User leaves edit mode, we create new players for the same streams. Tons of error logs appear.

Here's our code for releasing a player:
```kotlin
    internal fun destroy() {
        Timber.d("$TAG: Wrap.destroy: Releasing player. card.id='${cardId}', config.name='${curConfig?.name}', config.url='${curConfig?.urlHostAndPath}'")

        // Remove our listener and stop our retry logic so we don't try to restart while releasing.
        restartJob?.cancel()
        stoppedCheckJob?.cancel()
        player.removeListener(eventsListener)

        try {
            player.stop()
        } catch (e: Exception) {
            Timber.w(e, "$TAG: Wrap.destroy: Error stopping player, maybe it wasn't playing. cardId='${cardId}'")
        }
        try {
            player.release()
        } catch (e: Exception) {
            Timber.e(e, "$TAG: Wrap.destroy: Error releasing player. cardId='${cardId}'")
        }
    }
```

**Comment by tonihei** [comment]
From what I can tell this is probably just harmless log spam and might be a bug on these devices. The line itself is coming from within the Android platform code, so there is nothing we can do in ExoPlayer to prevent that. Feel free to report it to the device manufacturer as they might be able to do something about it. Closing it otherwise as there is nothing we can do.

**Comment by distinctdan** [comment]
Ok, thanks for the information here.
