### ISSUE TITLE
How to run an ExoPlayer custom PlayerView on a background thread?

### ISSUE THREAD

**Issue by distinctdan** [androidx/media#1336]
### Version

Media3 1.2.0

### Devices that reproduce the issue

Any, Emulator

### Reproducible in the demo app?

Not tested

### Reproduction steps

So I'm trying run an ExoPlayer on a background thread because it sometimes blocks for up to several seconds at a time when releasing (I'm using an RTSP media source. If it's not connected when I release, it can block for seconds). Our app displays up to 8 players streaming live video, and this problem can cause the whole UI to lock up when leaving the page.

My idea was to instantiate `ExoPlayer` on a background thread, then create a stripped down copy of `PlayerView` that switches context to that thread when calling `setPlayer`. The docs say that you can pass a Looper to ExoPlayer, and that does work. However, I'm getting a crash because SurfaceView callbacks are always called on the main thread. Is there something I'm missing here that would allow a player on a background thread to be used with SurfaceView?

Also, it would be really nice if you guys could prioritize integrating ExoPlayer with Compose and coroutines, I've run into a ton of memory leaks and issues trying to get the current way to work.

Here's my code to integrate the player with a single threaded coroutine:
```kotlin
// From: https://stackoverflow.com/questions/65183494/coroutinedispatcher-on-a-looper-thread
private val handlerThread = HandlerThread(TAG).apply { start() }
private val handler = Handler(handlerThread.looper)
val playerCoroutineContext = handler.asCoroutineDispatcher(TAG)

fun createPlayers() {
    withContext(dispatcher) {
        ExoPlayer.Builder()
    }
}

// ----- In MyPlayerView ----
fun setPlayer(player: Player?) {
    runBlocking(playerCoroutineContext) {
        // Copied code from Playerview
    }
}

// ----- In MyCameraCard Composable ----
AndroidView(
    factory = { ctx ->
        MyPlayerView(ctx, card.playerCoroutineContext).apply {
            setResizeMode(AspectRatioFrameLayout.RESIZE_MODE_FIT)
            layoutParams = FrameLayout.LayoutParams(MATCH_PARENT, MATCH_PARENT)
        }
    },
    update = { view ->
        view.setPlayer(card.player)
    },
    // Allows view reuse by LazyList.
    onReset = { view ->
        // IMPORTANT - The player must be set to null here and in onRelease
        // when we're done with it to prevent a significant memory leak.
        view.setPlayer(null)
    },
    onRelease = { view ->
        view.setPlayer(null)
    }
)
```

This produces the following exception when SurfaceView runs its callbacks on the main thread:
```
Exception configuring surface
java.lang.IllegalStateException
	at androidx.media3.common.util.Assertions.checkState(Assertions.java:85)
	at androidx.media3.common.util.ListenerSet.verifyCurrentThread(ListenerSet.java:309)
	at androidx.media3.common.util.ListenerSet.queueEvent(ListenerSet.java:218)
	at androidx.media3.common.util.ListenerSet.sendEvent(ListenerSet.java:259)
	at androidx.media3.exoplayer.ExoPlayerImpl.maybeNotifySurfaceSizeChanged(ExoPlayerImpl.java:2728)
	at androidx.media3.exoplayer.ExoPlayerImpl.access$1900(ExoPlayerImpl.java:128)
	at androidx.media3.exoplayer.ExoPlayerImpl$ComponentListener.surfaceChanged(ExoPlayerImpl.java:3174)
	at android.view.SurfaceView.updateSurface(SurfaceView.java:1018)
	at android.view.SurfaceView.lambda$new$0$android-view-SurfaceView(SurfaceView.java:160)
	at android.view.SurfaceView$$ExternalSyntheticLambda5.onPreDraw(Unknown Source:2)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1182)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3567)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2328)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9087)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Expected result

I would be able to use ExoPlayer on a different thread.

### Actual result

It crashes because SurfaceView uses the Main thread.

### Media

N/a

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by distinctdan** [comment]
Alternatively, how much work would it be to make `ExoPlayerImpl` threadsafe? It looks like many things already use a queue architecture. Would it be enough to wrap the public methods in `synchronized(lock) {` blocks?

**Comment by tonihei** [comment]
> Is there something I'm missing here that would allow a player on a background thread to be used with SurfaceView?

I think the critical element here is that SurfaceView has lifecycle methods that require all usages to stop within the scope of the method. See [this callback](https://developer.android.com/reference/android/view/SurfaceHolder.Callback#surfaceDestroyed(android.view.SurfaceHolder)) that explains that all rendering has to stop before returning from this function. This is the main reason ExoPlayer blocks on calls to clear a Surface until the operation has been fully handled on the internal playback thread. 

If you use ExoPlayer on a custom Looper, then it becomes your responsibility to handle the Surface lifecycle and if I'm not mistaken you'll have the same problem too unless you manage to reliably clear the surface from the Player before it is destroyed by the Android system.  

> prioritize integrating ExoPlayer with Compose

We are already working on a proper Compose integration, which is tracked by https://github.com/google/ExoPlayer/issues/9654. This won't remove the need to clear the SurfaceView when it's destroyed though. 

> Our app displays up to 8 players streaming live video, and this problem can cause the whole UI to lock up when leaving the page.

It sounds as if the issue is that all the blocking operations happen sequentially. I wonder if you can speed this up by manually triggering to clear the surface on all players (without waiting) and then some of the blocking operations get faster because they are likely already completed. You can manually trigger the internal surface removal with:
```
for (int i = 0; i < player.getRendererCount(); i++) {
  if (player.getRendererType(i) == C.TRACK_TYPE_VIDEO) {
    player.createMessage(player.getRenderer(i))
        .setType(Renderer.MSG_SET_VIDEO_OUTPUT)
        .setPayload(/* videoOutput */ null) // This is the default, just added for completeness
        .send();
  }
}
```

**Comment by distinctdan** [comment]
Thanks tonihei, really appreciate the information here. Reading through the docs, it says that SurfaceView is called on the thread running the window, which is the main thread, so it looks like to support true multithreading, SurfaceView itself would need to be able to be run on a background thread, or would need to gracefully handle being accessed after destroy is called. So if ExoPlayer continues to use SurfaceView, then it does sound like the only option would be to continue using the main thread, unless you guys would be able to make adjustments to SurfaceView itself or use something else.

So the main reason I'm focusing on this is we've encountered other bugs that cause the full blocking timeouts to run. For example, in my latest bug report, I've found that a disconnected RTSP player will block the main thread for the full 2 seconds when the user leaves the page because of the surface detach timeout: https://github.com/androidx/media/issues/1340. So normally I think running on the main thread would be fine as long as the underlying stuff is fast to stop, it's just that we're seeing it block for the full timeout length in a few cases.

That's a really interesting idea to detach the surfaces in parallel. I'm somewhat hesitant though because technically we would be detaching the surface before Compose has had a chance to call the AndroidView callbacks. And if a composition is in progress when we detach, I'm not sure what would happen. Do you know offhand if it's safe to detach a surface from an ExoPlayer that's still onscreen?

**Comment by tonihei** [comment]
> Do you know offhand if it's safe to detach a surface from an ExoPlayer that's still onscreen?

The only effect is that the codec is no longer producing new frames for the Surface, so this should be safe.

**Comment by distinctdan** [comment]
Great! We'll have to give this a try, I'll see if I can record some performance to measure the impact. Again, really appreciate the advice.

**Comment by distinctdan** [comment]
Wanted to followup on this. So I was able to dispatch the messages before leaving the page, but unfortunately it still looks like the specific timeout we're seeing is happening on the main thread, so this didn't seem to affect it. I'm guessing that message handling is still being done on the main thread, so even if we dispatch beforehand, the messages are still being processed sequentially. We're currently working around this by reducing the surfaceDetachTimeout from 2000ms to 250ms which I think should still be safe.
