### ISSUE TITLE
How to set setOngoing for the built in notification when using MediaSessionService

### ISSUE THREAD

**Issue by saravr** [androidx/media#1341]
I am using MediaSessionService, building a MediaSession, and returning that in the `onGetSession` callback. All works fine and notification shows up on the locked screen. However, I want to pin the notification in quick settings, which I believe, requires calling 
```
NotificationBuilder.setOngoing(true)
```
However, I am using built-in notification as that is sufficient for me. How do I set ongoing here?

Or should I implement a custom medianotification provider and call setMediaNotificationProvider() on the session service?

I am using Media3 version 1.3.1

**Comment by tonihei** [comment]
Thanks for the question! I wonder why this is not set automatically similar to how the old `PlayerNotificationManager` in the UI module [sets this flag based on the player state](https://github.com/androidx/media/blob/d833d59124d795afc146322fe488b2c0d4b9af6a/libraries/ui/src/main/java/androidx/media3/ui/PlayerNotificationManager.java#L1430). Will investigate and then decide if this should be done by default.

In the meantime, I think the only way to customize this is to write a custom media notification provider as you already suggested. You can potentially wrap the default implementation and then only change this flag on the created notification.

**Comment by saravr** [comment]
@tonihei thanks for your response. For some reason, even when I wrote a custom provider and added the following, still the notification was removed from the locked screen where there was a playback (source) exception. I wonder what I am missing. I have a related question on `unable-to-restart-after-exception` https://github.com/androidx/media/issues/1342.

```
        val notification: Notification =
            builder
                ...
                .setOnlyAlertOnce(true)
                .setSmallIcon(smallIconResourceId)
                .setStyle(mediaStyle)
                .setVisibility(NotificationCompat.VISIBILITY_PUBLIC)
                .setOngoing(true) // <<---
                .setPriority(PRIORITY_MAX) // <<--
                .setGroup(DefaultMediaNotificationProvider.GROUP_KEY)
                .build()
```
