### ISSUE TITLE
Android TV Content Streaming issue on Hisense TV

### ISSUE THREAD

**Issue by ChetanPatelPlayBoxTV** [androidx/media#1349]
### Version

Media3 main branch

### More version details

App opens and crashes while streaming content. I checked the internet connectivity is fine. I wanted to know the fixes to resolve this issue efficiently.

Error :

=> "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, "

=> " Caused by: androidx.media3.exoplayer.video.MediaCodecVideoDecoderException: Decoder failed: OMX.MS.AVC.Decoder"

complete log 
`Playback error
05-06 19:45:52.571 15305 15559 E ExoPlayerImplInternal:   androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D401E, 690800, null, [640, 360, -1.0, ColorInfo(BT601, Limited range, Unset color transfer, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES
05-06 19:45:52.571 15305 15559 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:623)
05-06 19:45:52.571 15305 15559 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
05-06 19:45:52.571 15305 15559 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:223)
05-06 19:45:52.571 15305 15559 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
05-06 19:45:52.571 15305 15559 E ExoPlayerImplInternal:   Caused by: androidx.media3.exoplayer.video.MediaCodecVideoDecoderException: Decoder failed: OMX.MS.AVC.Decoder
05-06 19:45:52.571 15305 15559 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1915)
05-06 19:45:52.571 15305 15559 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:848)
05-06 19:45:52.571 15305 15559 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:940)
05-06 19:45:52.571 15305 15559 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1112)
05-06 19:45:52.571 15305 15559 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:544)
05-06 19:45:52.571 15305 15559 E ExoPlayerImplInternal:       ... 3 more
05-06 19:45:52.571 15305 15559 E ExoPlayerImplInternal:   Caused by: java.lang.IllegalStateException
05-06 19:45:52.571 15305 15559 E ExoPlayerImplInternal:       at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
05-06 19:45:52.571 15305 15559 E ExoPlayerImplInternal:       at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
05-06 19:45:52.571 15305 15559 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:108)
05-06 19:45:52.571 15305 15559 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1934)
05-06 19:45:52.571 15305 15559 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:827)
05-06 19:45:52.571 15305 15559 E ExoPlayerImplInternal:       ... 6 more
05-06 19:45:52.573 15305 15559 E ExoPlayerImplInternal: Disable failed.
05-06 19:45:52.573 15305 15559 E ExoPlayerImplInternal:   java.lang.IllegalStateException
05-06 19:45:52.573 15305 15559 E ExoPlayerImplInternal:       at android.media.MediaCodec.native_flush(Native Method)
05-06 19:45:52.573 15305 15559 E ExoPlayerImplInternal:       at android.media.MediaCodec.flush(MediaCodec.java:2298)
05-06 19:45:52.573 15305 15559 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:168)
05-06 19:45:52.573 15305 15559 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:912)
05-06 19:45:52.573 15305 15559 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:905)
05-06 19:45:52.573 15305 15559 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:744)
05-06 19:45:52.573 15305 15559 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:711)
05-06 19:45:52.573 15305 15559 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.BaseRenderer.disable(BaseRenderer.java:220)
05-06 19:45:52.573 15305 15559 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1803)
05-06 19:45:52.573 15305 15559 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1525)
05-06 19:45:52.573 15305 15559 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1482)
05-06 19:45:52.573 15305 15559 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:667)
05-06 19:45:52.573 15305 15559 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
05-06 19:45:52.573 15305 15559 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:223)
05-06 19:45:52.573 15305 15559 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)`

### Devices that reproduce the issue

SmartTV 4K, Hisense
Philips 4K A1
Smart TV, TCL

### Devices that do not reproduce the issue

LG

### Reproducible in the demo app?

Yes

### Reproduction steps

This issue is not 100% reproducible, but It should be reproduceable with the demo app.
I will try to reproduce it in the demo app.

### Expected result

No PlaybackException with decoder init failed when playing WideoVide video content

### Actual result

every times there is an PlaybackException with decoder init failed when playing WideoVide video content.

 Caused by: androidx.media3.exoplayer.video.MediaCodecVideoDecoderException: Decoder failed: OMX.MS.AVC.Decoder

### Media

 {
        "name": "HD (cenc)",
        "uri": "https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears.mpd",
        "drm_scheme": "widevine",
        "drm_license_uri": "https://proxy.uat.widevine.com/proxy?video_id=2015_tears&provider=widevine_test"
      }

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment]
Please 

> ### Bug Report
> * [ ]  You will email the zip file produced by `adb bugreport` to [android-media-github@google.com](mailto:android-media-github@google.com) after filing this issue.

Please do this part - it will include more logging than you have quoted above and may help to understand exactly what is going wrong.

**Comment by ChetanPatelPlayBoxTV** [comment]
@icbaker after update tv framework issue resolved. thanks for supporting.
