### ISSUE TITLE
Allow setting preferred devices to AudioTrack 

### ISSUE THREAD

**Issue by yschimke** [androidx/media#135]
### Use case description

AudioTrack is useful to apps for multiple reasons

- exposes detailed state of the audio subsystem, such as offload.
- allows changing the preferred devices

### Proposed solution

Make AudioTrack accessible in DefaultAudioSink.

### Alternatives considered

Fully expose all *interesting* bits of AudioSink via accessors in DefaultAudioSink or Player.Listener events.

**Comment by tonihei** [comment]
Besides `isAudioOffloadEnabled`, which bits of information would you like to expose exactly? It's not quite clear to me what these *interesting* bits of `AudioSink` are. We are unlikely to expose the `AudioTrack` directly as it breaks the encapsulation and may cause unexpected side effects if someone changes `AudioTrack` in any way outside of `DefaultAudioSink`.

**Comment by yschimke** [comment]
I think just the preferred devices.  

But more generally once you get to a point that you care about the state of the AudioTrack, it's awkward to do anything without copying and pasting DefaultAudioSink for even the most minor of changes.

Feel free to close.

**Comment by tonihei** [comment]
Thanks, I'll change it to an enhancement tracking how users can specify preferred devices for audio playback.

**Comment by christosts** [comment]
@tonihei this is completed, right?

**Comment by yschimke** [comment]
I think yes via other APIs.
