### ISSUE TITLE
Disable Jetifier

### ISSUE THREAD

**Issue by MGaetan89** [androidx/media#1362]
### Use case description

Currently, this repository has Jetifier enabled:
https://github.com/androidx/media/blob/fff68f19328cb01e3b959508b57253973b071618/gradle.properties#L3

According to Android Studio, this is no longer necessary, and Jetifier can be disabled:
<img width="782" alt="Screenshot 2024-05-10 at 10 14 56" src="https://github.com/androidx/media/assets/1009664/929b2305-198e-4b46-93e7-b138d2b07b52">

### Proposed solution

Remove the `android.enableJetifier` property, since [Jetifier is disabled by default](https://developer.android.com/jetpack/androidx#using_androidx_libraries_in_your_project):
> The flag is `false` by default if it is not specified.

Additionnaly, the `android.jetifier.ignorelist` property in `gradle.properties` can also be removed.

**Comment by icbaker** [comment]
Thanks for the report - is that a screenshot from Android Studio? I don't see the same message show up in my AS - so I was wondering if you needed to manually enable/run the check or similar.

**Comment by MGaetan89** [comment]
Yes, you have to manually run the checks. Here's how I do it:
- Trigger a builder. Once completed, you should see a notification from the Build Analyzer
- Click on "Review to improve build performance" from that notification
- Select "Jetifier" in the left pane
- Press the "Run Jetifier check" in the right pane

**Comment by icbaker** [comment]
Ah thanks, for some reason this wasn't showing up on our internal version of the project but I see it when directly opening the project from the external git project. I'll send a change to remove these lines.

**Comment by icbaker** [comment]
The change linked above removes the jetifier config.
