### ISSUE TITLE
Unable to resume playback in onPlayWhenReadyChanged (Player.Listener)

### ISSUE THREAD

**Issue by y20k** [androidx/media#139]
### Media3 Version

1.0.0-beta02

### Devices that reproduce the issue

* Emulator Pixel 5 API 33

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. in a `MediaSessionService` create a Player with the attribute `setPauseAtEndOfMediaItems(true)`
2. start playback of `MediaItem` **A**
3. unbind the service from its activty (kill the activity for example)
4. listen in `onPlayWhenReadyChanged` (Player.Listener) for the reason (int) `Player.PLAY_WHEN_READY_CHANGE_REASON_END_OF_MEDIA_ITEM`
5. load a new `MediaItem` B when `Player.PLAY_WHEN_READY_CHANGE_REASON_END_OF_MEDIA_ITEM`
4. start playback of new *MediaItem` **B**

### Expected result

Player resumes playback with the MediaItem **B**.

### Actual result

The app crashes and throws `ForegroundServiceStartNotAllowedException` (*android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service org.y20k.escapepod/.PlayerService*).

Problem / my explanation: `setPauseAtEndOfMediaItems(true)` pauses the player. If the service is not bound to an activity and playback is paused, media3 makes the service call `stopForeground(true)` - probably [here](https://github.com/androidx/media/blob/1.0.0-beta02/libraries/session/src/main/java/androidx/media3/session/MediaNotificationManager.java#L211). 

I think, once paused a MediaSessionService cannot start playback again by itself. A solution might be #45.

### Media

Not applicable

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by y20k** [comment]
I just wanted to let you know that I found a solution to my specific problem. The problem

> once paused a MediaSessionService cannot start playback again by itself

might still be an issue for other uses cases than mine.

**Comment by marcbaechinger** [comment]
Thanks for the detailed report. 

You are mentioning issue #45 that has some comments explaining the design decision of taking the service off the foreground when the player is paused by default. The justification for this is mainly system health. 

`By default` means that an app can override `MediaSessionService.updateNotification(MediaSession)` and manage foreground handling itself.

**Comment by y20k** [comment]
Hi @marcbaechinger 

Thanks for explaining the default behavior and the customization options to circumvent the problem I observed. 

This is not a bug.
