### ISSUE TITLE
 DaiStreamRequest class not found

### ISSUE THREAD

**Issue by zeusalmighty717** [androidx/media#14]
Steps to reproduce:
1. Clone the repo
2. Build the project / Run demo app

File Name : `ImaServerSideDaiMediaSourceFactory`
Line 737: Not able to import class `  DaiStreamRequest` 

There are several other errors that prevent running the demo app.

**Comment by icbaker** [comment]
The `ImaServerSideDaiMediaSourceFactory.java` file was included in this repository by mistake (it's not quite ready to be published). You can safely delete the file and hopefully everything else should work. We will also push a commit shortly that deletes this file.

**Comment by zeusalmighty717** [comment]
Thanks for the quick reply @icbaker . Keeping this open until the new commit is pushed.

**Comment by tonihei** [comment]
The class was deleted as part of https://github.com/androidx/media/commit/dc887070c8cede760a74b2a719aa9ed44b5682f2
