### ISSUE TITLE
Unable to style  default `SubtitleView` of the Media3 ExoPlayer

### ISSUE THREAD

**Issue by ForceGT** [androidx/media#1403]
I am trying to style captions that come into my DASH segment as .vtt files. Scouted the internet for how to do that, and found a suggestion from the docs [here](https://github.com/google/ExoPlayer/issues/8056)

Moving further with the suggestion of styling Cue objects, I couldn't get it to work.

Here's a sample code for reference

The params `zoomInFactor`, `subtitleTopSpacing` , `subtitleFontSize` are all part of business logic, and can vary.Also the flag i`sVideoZoomed`, is also business logic, and the spacing can vary

Here, I am concerned about the fact, that these styled Cues are not being applied to the subtitleView using subtitleView?.setCues(cues)

What can be going wrong?

I have also opened a StackOverflow Question [here](https://stackoverflow.com/questions/78424403/unable-to-style-cue-in-default-subtitleview-media3-exoplayer)

```kotlin
fun setCues(
        cues: ImmutableList<Cue>,
        zoomInFactor: Float,
        subtitleTopSpacing: Float,
        subtitleFontSize: Float,
){

 if (cues.isEmpty()) return
        // First clear the existing cues
        subtitleView?.setCues(null)
        try {
            // Modify the existing cues as per the available parameters
            val modifiedCues = cues.map { cue ->
                val cueBuilder = cue.buildUpon()
                if (isVideoZoomed) {
                    cueBuilder.setLine(
                        (subtitleTopSpacing + ((zoomInFactor - 1) * 0.5F)) / zoomInFactor,
                        Cue.LINE_TYPE_FRACTION,
                    )
                    cueBuilder.setTextSize(
                        subtitleFontSize / zoomInFactor,
                        Cue.TEXT_SIZE_TYPE_FRACTIONAL,
                    )
                } else {
                    cueBuilder.setLine(subtitleTopSpacing, Cue.LINE_TYPE_FRACTION)
                    cueBuilder.setTextSize(
                        subtitleFontSize, Cue.TEXT_SIZE_TYPE_FRACTIONAL,
                    )
                }
                cueBuilder.lineAnchor = Cue.ANCHOR_TYPE_END
                cueBuilder.build()
            }
            subtitleView?.setCues(modifiedCues)
        } catch (ex: Exception) {
            ex.printStackTrace()
        }
}
```

**Comment by icbaker** [comment]
The provided code looks like it should roughly work (though I don't think you want to immediately return if the list is empty, because doesn't that mean you never clear subtitles from the screen?).

> I couldn't get it to work.

What do you observe happening that constitutes "not working"?

How are you wiring this `setCues` method into the rest of your app's UI components? Where do you get an instance of `SubtitleView` from? Is `SubtitleView.setCues` **also** being called with the unstyled cues from elsewhere, or have you prevented that from happening?

**Comment by ForceGT** [comment]
> though I don't think you want to immediately return if the list is empty, because doesn't that mean you never clear subtitles from the screen?
I can remove the empty check. I did it before hand to just prevent the nullability and empty check

When I say, I couldn't get it to work, I meant that, the styling doesn't reflect, as I want it to

As a workaround, what I did is, get access to the `SubtitleView` and style the main `FrameLayout` that it has, and not the cues inside. I know this is a hack, but this works, and styling the cues doesn't

>  Is SubtitleView.setCues also being called with the unstyled cues from elsewhere

I tried to print the `Cue` object and it contains the new styles
Interesting, I will try to take a look, if it's called from somewhere else and being reset for some reason

**Comment by ForceGT** [comment]
@icbaker I checked my code, the `setCues` function is called from the `onCues` function in the `ExoPlayerListener` interface

**Comment by icbaker** [comment]
Closing because these questions were not clearly answered, so it's not possible to offer further assistance:

> How are you wiring this `setCues` method into the rest of your app's UI components? Where do you get an instance of `SubtitleView` from?
