### ISSUE TITLE
HLS playback crash on Android 6 and below.

### ISSUE THREAD

**Issue by goranch** [androidx/media#1406]
### Version

Media3 main branch

### More version details

Version 1.3.1

The crash is caused by Introducing a Java 8 java.util.Stream api here: https://github.com/androidx/media/pull/1054/files#diff-3895326de0c5e6ffdc885f40d9160501824ffaa155f4fb6593db8d648a83e1b0R982

You can reproduce it by playing the HLS streams on the demo app on an Android 6 device.

### Devices that reproduce the issue

Any Android OS 6 or below.

### Devices that do not reproduce the issue

Android 7 and up.

### Reproducible in the demo app?

Yes

### Reproduction steps

You can reproduce it by playing the HLS streams on the demo app with ExoPlayer 1.3.1 on an Android 6 device.

### Expected result

No crash

### Actual result

Crash

`2024-05-29 09:57:16.877 22666-22786 AndroidRuntime          androidx.media3.demo.main            E  FATAL EXCEPTION: ExoPlayer:Playback
                                                                                                    Process: androidx.media3.demo.main, PID: 22666
                                                                                                    java.lang.NoSuchMethodError: No interface method stream()Ljava/util/stream/Stream; in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
                                                                                                    	at androidx.media3.common.Format.<init>(Format.java:982)
                                                                                                    	at androidx.media3.common.Format.<init>(Format.java:128)`

### Media

Reproducible on the HLS streams in the demo app (Apple 16x9 basic stream TS)

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by rohitjoins** [comment]
Hi @goranch,

We have [reverted]((https://github.com/androidx/media/commit/6ac60c6dffb464851140d2a4bb21b38b26c11f8a#diff-3895326de0c5e6ffdc885f40d9160501824ffaa155f4fb6593db8d648a83e1b0R992) ) the mentioned usage of Java 8 above. This change will be included in our next release.
