### ISSUE TITLE
Support for setting the start and end times of playback in TextOverlay.

### ISSUE THREAD

**Issue by tomo-TW** [androidx/media#1414]
Hi,

I would like the feature to specify the playback start and end times of the text in a TextOverlay.
Currently, I am using Media3 Transformer to embed text into videos, but I cannot set the playback time of the text.
Would I need to create a custom Overlay class to achieve this?

The following is the code I wrote.
```
fun createDynamicTextOverlay(
    overlayText: SpannableString,
    overlaySettings: OverlaySettings,
    startTime: Long,
    endTime: Long,
): TextOverlay {
    return object : TextOverlay() {
        override fun getText(presentationTimeUs: Long): SpannableString {
            if (presentationTimeUs in startTime .. endTime) {
                return overlayText
            } else {
                return SpannableString("")
            }
        }

        override fun getOverlaySettings(presentationTimeUs: Long): OverlaySettings {
            return overlaySettings
        }
    }
}
```

**Comment by droid-girl** [comment]
Hi @tomo-TW, there is currently no API available to support this use case out of the box, but there are several ways to achieve this effect:

1. Use [Timestampwrapper](https://github.com/androidx/media/blob/release/libraries/effect/src/main/java/androidx/media3/effect/TimestampWrapper.java) together with TextOverlay effect. You can find some information on the usage [here](https://github.com/androidx/media/issues/737#issuecomment-1770567499). 
2. Create a custom TextOverlay as you mentioned.

I hope it helps

**Comment by tomo-TW** [comment]
Thanks will give it a try

**Comment by tomo-TW** [comment]
I was able to do it successfully by doing the following.
thank you so much.

```
        val overlayEffect = OverlayEffect(overlaysBuilder.build())
        val timeWrappedEffect = TimestampWrapper(overlayEffect, 5000L * 1000, 10000L * 1000)
```

**Comment by droid-girl** [comment]
Closing this issue.
