### ISSUE TITLE
DASH manifest default_KID parameter

### ISSUE THREAD

**Issue by xxanisxx** [androidx/media#1421]
Your DASH manifest is missing the required default_KID parameter in the <ContentProtection>
i know that the dash manifest required to have it but the question is 

is it possbile for me to add it without make change to the dash manifest stream?
or if i have the key/kid pair is it possible to make it work without it  like it does when i test it in jwplayer or shakaplayer?

the same dash manifest will work in when it have the default_KID but it wont when it dosent thats when i use exoplayer
but if i use webplayer tester like jwplayer will work if it have it or not so whats the different ? 

this is the dash manifest i use 
https://linear314-it-dash1-prd-ll.cdn13.skycdp.com/016a/31478/FHD/skysportf1/master.mpd
kid: 00366649eb2eb82ee172e1bd310e4136
key: 27e85c17d97722288ffa5970389d8baf

**Comment by tonihei** [comment]
> is it possbile for me to add it without make change to the dash manifest stream

You can customize the `DashManifestParser` with `DashMediaSource.Factory.setManifestParser` and providing a subclass of `DashManifestParser` that overrides the `parseContentProtection` method. 

>  if i use webplayer tester like jwplayer will work if it have it or not so whats the different

The manifest also contains data for PlayReady and Widevine, maybe the other player had access to these DRM schemes? To use Widevine for example, you need to provide the license service URL in `HttpMediaDrmCallback` passed to `DefaultDrmSessionManager.Builder` (see demo app).

**Comment by xxanisxx** [comment]
am sorry am new to this things and still learning 
i did this example before #1208 
every things ok and working but i want to make some change to it to make it work without default_KID 
so how i start what i cant change

**Comment by tonihei** [comment]
> i want to make some change to it to make it work without default_KID

As the DASH spec doesn't allow streams without a default_KID, we don't really want to add support for this in the library.

But as I said above, you can work around it yourself by providing a custom `DashManifestParser` that adds the missing in information in `parseContentProtection`.
