### ISSUE TITLE
Can the anchor position of a video be changed by effects in a composition?

### ISSUE THREAD

**Issue by kleiren** [androidx/media#1428]
I would like to crop a specific video (or image) inside a composition and change its position in the frame (for example for zooming in a specific part of a video that is not the center point).
I know there are effects for rotating and cropping a media item. Also, TextureOverlays can be set in a specified position by defining OverlaySettings anchor points.

**Is there an equivalent for setting an anchor for an editableMediaItem?** I have looked into VideoCompositorSettings, where "getOverlaySettings" can maybe be overridden,  but it seems that it is applied to the full composition instead of a single editableMediaItem.

Thanks!

**Comment by tof-tof** [comment]
We have an video effect called [Crop](https://github.com/androidx/media/blob/d833d59124d795afc146322fe488b2c0d4b9af6a/libraries/effect/src/main/java/androidx/media3/effect/Crop.java#L55) that allows you to specify the vertices of a rectangle (using NDCs -explain in the method javadoc). This should allow you to crop to any position in the video frame
