### ISSUE TITLE
Crypto key not available: ERROR_DRM_NO_LICENSE 

### ISSUE THREAD

**Issue by taransinghlayal** [androidx/media#1431]
Hi,

I have integrated the player version 1.1.1 in the app. We are playing DASH contents with .mpd URLs. 
Ever since we have migrated to the Media3Exoplayer from the older Exo Player we have started seeing this error "Crypto Key not available" on our analytics tool.

Unfortunately we are not able to reproduce this error on our side so I am unable you to provide the detailed logs however we do track the playbackException obj and respective failed chunk URL on analytic tool which has below mentioned information

The PlaybackException obj gives message as - **Unexpected runtime error**
unexpectedException - **Crypto key not available: ERROR_DRM_NO_LICENSE cdm err: 0, oem err: 0, ctx: 0 ============================== Beginning of DRM Plugin Log ============================== 06-05 23:53:24.829 I found instance=clearkey version=android.ha**

We have all content that supports L3 security level and the UUID used for DRMSessionManger is also WIDEVINE_UUID

We have also checked our chunk URLs and the key was present in the same but still player was not able to get the keys.

Can you please let us know what can be the possible reason for this.

I understand that this information is not sufficient but this would really help us if you can point us to some direction where this issue can be. Also please suggest if there is more information in case of error which we can track on our analytic tool in order to get the more insights about this issue.

**Comment by rrfrias** [comment]
Is it possible to share a bugreport? If the exception is only retrieved from telemetry data, can you get Widevine metrics data after a failure occurs. Use [MediaDrm.getPropertyByteArray](https://developer.android.com/reference/android/media/MediaDrm#getPropertyByteArray(java.lang.String))("metrics") . This returns a byte[] so you might need to convert it to a Base64 encoded string before you share with us (Base64.getEncoder().encodeToString(bytes)) .

Email [android-media-github@google.com](mailto:android-media-github@google.com) after filing this issue.

**Comment by taransinghlayal** [comment]
HI @rrfrias 

We were able to reproduce this issue once at our side but we could not get any bytes in MediaDrm.getPropertyByteArray("metrics") as the bytes were 0 when this error occurred. We have tried this with the same FrameworkMediaDRM obj that was used for the playback and also one separate obj that was created before initialising the player of MediaDRM class. But both of this object did not gave any bytes in the metrics.

However we were able to capture the stacktrace of the error for this issue which I have sent to the above email address for your reference. Can you please check the logs and let us know if you are able to fetch the reason of this failure.

We have also observed one thing that this issue was reproduced when the app was sent to background without releasing the player. Do you think this can be a probable cause as we do not release the player and only pause the player as soon as the app goes in to background.

**Comment by taransinghlayal** [comment]
Hi @rrfrias Did you get a chance to check this?

**Comment by rrfrias** [comment]
Thanks for the bugreport. I can see invocation of MediaCodec but not MediaDrm, indicating clear playback? Maybe encrypted playback was not captured in the log? I took a look at the metrics in the bugreport and there does not seem to have been any DRM activity. Can you try again and share another logcat/bugreport?

**Comment by rrfrias** [comment]
> Do you think this can be a probable cause as we do not release the player and only pause the player as soon as the app goes in to background.

@icbaker , can you give us some guidance on this implementation behavior and then assign back to me to wait on information from @taransinghlayal ?

**Comment by taransinghlayal** [comment]
Hi @rrfrias 

Can you also look at the detailed error logs that I have sent when this issue occurred under the same email with subject **Issue #1431**

**Comment by icbaker** [comment]
> Do you think this can be a probable cause as we do not release the player and only pause the player as soon as the app goes in to background.

Hard to say if this is related really (and also unclear if you are using a foreground service, or just running within an activity). Do you release the player if the app is completely dismissed (i.e. in [`onDestroy()`](https://developer.android.com/guide/components/activities/activity-lifecycle#ondestroy))? And if not, when the app is restarted I guess you will have to re-create the player and all the DRM machinery - so does this end up leaving unreleased resources from the previous run?

**Comment by taransinghlayal** [comment]
Hi @icbaker 

We are releasing the player in onDestroy callback. And we are not using any foreground service to play the content and the player is attched with Fragment only.

However we are not releasing the player in activity on Stop method. but this is getting released in the onDestroy callback.

So if any user put the app in the background for a long time and the app is not killed then do you think not releasing the player could lead to this problem.

**Comment by icbaker** [comment]
> So if any user put the app in the background for a long time and the app is not killed then do you think not releasing the player could lead to this problem.

I don't know of a reason this set up would lead to the problem you're seeing.

**Comment by rrfrias** [comment]
> Can you also look at the detailed error logs that I have sent when this issue occurred under the same email with subject Issue https://github.com/androidx/media/issues/1431

Looking at the stack trace, it appears license requests were sent and received every minute for about 32 minutes. We then see license requests but no response and eventually the license expires. I have a few questions
1. Do you need to re-request the license every minute? It seems excessive (though not harmful)
2. License requests are made from the same session. Are these license renewals?

**Comment by taransinghlayal** [comment]
Yes the license request in every minute.
Yes the playback was in progress and the app was in background for a long time. After taking app to foreground this error was thrown. As the player is not released this should be same session

**Comment by taransinghlayal** [comment]
Hi @icbaker 

Did you get a chance to check this?

**Comment by rrfrias** [comment]
Looking at the stack trace again, it appears that the license expired. There should be events from MediaDrm indicating that the keys are no longer available and that the license expired if event Listeners are setup [MediaDrm.OnKeyStatusChangeListener](https://developer.android.com/reference/android/media/MediaDrm.OnKeyStatusChangeListener) and [MediaDrm.OnExpirationUpdateListener](https://developer.android.com/reference/android/media/MediaDrm.OnExpirationUpdateListener)

**Comment by taransinghlayal** [comment]
Hi @rrfrias 

We could not get any bytes in MediaDrm.getPropertyByteArray("metrics") as the bytes were 0 when this error occurred.
Can you confirm if the response is handled internally by the player or not whenever license renewal request were made or is there any additional handling required for this?

**Comment by rrfrias** [comment]
> Can you confirm if the response is handled internally by the player or not whenever license renewal request were made or is there any additional handling required for this?

@icbaker does Exoplayer handle renewal network round-trips? Renewal requests are being generated but no responses are received leading to license expiration.

**Comment by icbaker** [comment]
For license renewals, ExoPlayer registers a `MediaDrm.OnEventListener` on the underlying `MediaDrm` object here in `DefaultDrmSessionManager`:
https://github.com/androidx/media/blob/b01c6ffcb3fca3d038476dab5d3bc9c9f2010781/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/drm/DefaultDrmSessionManager.java#L404

Which forwards the event via a `Handler`:
https://github.com/androidx/media/blob/b01c6ffcb3fca3d038476dab5d3bc9c9f2010781/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/drm/DefaultDrmSessionManager.java#L921

To the appropriate `DefaultDrmSession` instance (determined by `sessionId`):
https://github.com/androidx/media/blob/b01c6ffcb3fca3d038476dab5d3bc9c9f2010781/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/drm/DefaultDrmSessionManager.java#L807-L811

And this handles `EVENT_KEY_REQUIRED`:
https://github.com/androidx/media/blob/b01c6ffcb3fca3d038476dab5d3bc9c9f2010781/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/drm/DefaultDrmSession.java#L220-L228

Which results in requesting a new license:
https://github.com/androidx/media/blob/b01c6ffcb3fca3d038476dab5d3bc9c9f2010781/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/drm/DefaultDrmSession.java#L441

By first getting the key request from the framework `MediaDrm`:
https://github.com/androidx/media/blob/b01c6ffcb3fca3d038476dab5d3bc9c9f2010781/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/drm/DefaultDrmSession.java#L497

And then the response is passed back to the framework here:
https://github.com/androidx/media/blob/b01c6ffcb3fca3d038476dab5d3bc9c9f2010781/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/drm/DefaultDrmSession.java#L523

From the logs quoted in https://github.com/androidx/media/issues/1431#issuecomment-2246382769 it seems that the `MediaDrm.getKeyRequest` call is being made, but no corresponding `MediaDrm.provideKeyResponse` call is seen. This could happen if the key request is considered stale by the time the response arrives (though this seems unlikely from the timestamps in the logs which are 15s apart):
https://github.com/androidx/media/blob/b01c6ffcb3fca3d038476dab5d3bc9c9f2010781/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/drm/DefaultDrmSession.java#L506-L509

Or it could be due the license request being dropped by a customised [`MediaDrmCallback`](https://developer.android.com/reference/androidx/media3/exoplayer/drm/MediaDrmCallback) implementation.
----

ExoPlayer does not register an implementation of `MediaDrm.OnKeyStatusChangeListener` or `MediaDrm.OnExpirationUpdateListener`.

**Comment by taransinghlayal** [comment]
Thanks for such deep illustration.

In my case I am not using any custom mediaDRMCallback. The FrameworkMediaDrm newInstance(UUID uuid) is getting used in my case. But I am still not able to understand how I can fix this issue if the timestamp was very low. Do you think re initialising the player when comes to foreground will help fix this issue.

**Comment by rrfrias** [comment]
Might it be possible to add some logging to confirm that the license request is sent and understand why `MediaDrm.provideKeyResponse` is not being called? Hoping you can get this added to telemetry data as you mentioned you are unable to reproduce locally.

**Comment by rrfrias** [comment]
Another option is to increase the time period of your licenses. If you increase the renewal delay window, it will reduce the likelihood of an excessive network roundtrip from interrupting playback.

**Comment by JosephSanjaya** [comment]
We've encountered a similar issue in our application. In our case, the error specifically occurs on some Android 14 devices. 
![image](https://github.com/user-attachments/assets/eafa84d2-c56a-49b3-8c6d-f7bc598afe51)

Our implementation uses a single instance player that persists throughout the app's lifecycle, without being released. This approach differs from the one described in the original post, where the player is released in the onDestroy callback.

Some additional details about our scenario:

1. The error is consistently reproducible on some of Android 14 (ex. from crashlytics  Galaxy A24, Galaxy A15, Galaxy A13)
2. We're using a single instance of ExoPlayer that's maintained throughout the app's lifecycle.
3. The player is not released when the app goes to the background or when activities are destroyed.

We're curious if other developers have experienced this issue specifically on Android 14, and if the single-instance approach to player management could be a contributing factor.

Any insights or suggestions for troubleshooting this issue?

**Comment by rrfrias** [comment]
@JosephSanjaya a few questions

* are these failures consistently reproducible. If not can you mention the reproducibility rates for given models?
* might the failure be tied to particular titles
* can you check that the license was correctly loaded
* key is present in the license
* do these problems occur on a particular title on android 14 devices but not earlier android versions?

Can you try to capture 
* a logcat/bugreport
* if that is not possible call MediaDrm.getPropertyByteArray("metrics")  after the error

and share it with android-media-github@google.com, mention "Issue #1431" in Subject

**Comment by JosephSanjaya** [comment]
> @JosephSanjaya a few questions
> 
>     * are these failures consistently reproducible. If not can you mention the reproducibility rates for given models?
> 
>     * might the failure be tied to particular titles
> 
>     * can you check that the license was correctly loaded
> 
>     * key is present in the license
> 
>     * do these problems occur for a particular title on android 14 devices but not earlier android versions?
> 
> 
> Can you try to capture
> 
>     * a logcat/bugreport
> 
>     * if that is not possible call MediaDrm.getPropertyByteArray("metrics")  after the error
> 
> 
> and share it with [android-media-github@google.com](mailto:android-media-github@google.com), mention "Issue #1431" in Subject

1. Yes this issue is constantly occured on devices, for example in our last log it showing samsung SM-A725F, always get this exception when playing drm Content
2. We check on the log that license is already downloaded and loaded
3. the key is appear on log also so the key is there.
4. if we check on crashlytics these issue is just appeared on devices api 14 like i shown above.

I cant provide any logcat/bugreport for now because it occured in client devices. 

i will try to ask for it and get back to you

Thanks!

**Comment by taransinghlayal** [comment]
How can we check if key is present in the license?

**Comment by JosephSanjaya** [comment]
@taransinghlayal, we currently used pallycon as our drm provider, so we can check through CDATA if the key is contained on returned license or not.

**Comment by taransinghlayal** [comment]
How to check that the license was correctly loaded?

**Comment by rrfrias** [comment]
There is a [MediaDrm.OnKeyStatusChangeListener](https://developer.android.com/reference/android/media/MediaDrm.OnKeyStatusChangeListener) that you can register for to be informed about Key Ids that are available. At the bottom of https://github.com/androidx/media/issues/1431#issuecomment-2273598980 

> ExoPlayer does not register an implementation of MediaDrm.OnKeyStatusChangeListener or MediaDrm.OnExpirationUpdateListener.

So you will have to add your own custom code.

**Comment by rrfrias** [comment]
@JosephSanjaya 

> Yes this issue is constantly occured on devices, for example in our last log it showing samsung SM-A725F, always get this exception when playing drm Content

If you cannot reproduce this locally, can you call MediaDrm.getPropertyByteArray("metrics") after the error, report if to  crashAnalytics and share it with [android-media-github@google.com](mailto:android-media-github@google.com), mention "Issue https://github.com/androidx/media/issues/1431" in Subject

**Comment by rrfrias** [comment]
Is this a case of key rotation similar to https://github.com/androidx/media/issues/1684#issuecomment-2345367629 but for streaming
