### ISSUE TITLE
Is there a version of KOTLIN?

### ISSUE THREAD

**Issue by sswudiss** [androidx/media#145]
I am a novice. After opening the project, I found that it is all java code.
Need IDE and then convert to KOTLIN
For newbies, hope the code has some annotations.
Is there a version of KOTLIN?

thank you very much!

**Comment by christosts** [comment]
I'm not sure what you mean by

> Need IDE and then convert to KOTLIN

you don't need to convert it to Java. The [demo-session](https://github.com/androidx/media/tree/1.0.0-beta02/demos/session) app is written in Kotlin, if you want to see examples in Kotlin how to use the code on your app.
