### ISSUE TITLE
How to support iso Blu-ray original disc playback

### ISSUE THREAD

**Issue by aslnfl** [androidx/media#1459]
How to support iso Blu-ray original disc playback.

**Comment by microkatz** [comment]
@aslnfl,

Apologies but we currently don't intend to support this in the player. 

If you wanted to support it yourself then you would need to write a custom [Extractor](https://github.com/androidx/media/blob/release/libraries/extractor/src/main/java/androidx/media3/extractor/Extractor.java) to recognize the file, provide a media format so the player can configure a decoder, and parse and provide media samples from it.
