### ISSUE TITLE
Unable to import exoplayer UI string resource 

### ISSUE THREAD

**Issue by pawaom** [androidx/media#1467]
Unable to import exoplayer UI string resource 

I was working with the exoplayer main demo in media 3

[here](https://github.com/androidx/media/tree/release/demos/main)

The [TrackSelectionDialog](https://github.com/androidx/media/blob/release/demos/main/src/main/java/androidx/media3/demo/main/TrackSelectionDialog.java) contains few string resource which should be included after we include the UI library however they are still not included the following two images explain it better 

![Screenshot 2024-06-18 145038](https://github.com/androidx/media/assets/28686824/f3680cb1-26fc-4b93-b409-813727f6be86)
![Screenshot 2024-06-18 145106](https://github.com/androidx/media/assets/28686824/78bdb19b-7b02-4b85-8dff-8be9a346f92c)

I think they refer to this file 

 [here](https://github.com/androidx/media/blob/d833d59124d795afc146322fe488b2c0d4b9af6a/libraries/ui/src/main/res/values/strings.xml#L92)  and others

even after including `implementation 'androidx.media3:media3-ui:1.X.X'` we are unable to get this resources 

how can we include them

**Comment by tonihei** [comment]
These strings moved to the demo app as of https://github.com/androidx/media/commit/ebe74daaecc53a61a374676428405260e1a46584. I guess your project is using a local checkout of the demo app, but depends on a release version of the UI module? To fix this issue you either need to check out the demo app at the release tag you are depending on, or build the UI module from the main branch as well.

**Comment by pawaom** [comment]
I have used `val media3_version = "1.3.1"` even then it causes the issue
