### ISSUE TITLE
EVENT_PLAYBACK_SUPPRESSION_REASON_CHANGED and PLAYBACK_SUPPRESSION_REASON_TRANSIENT_AUDIO_FOCUS_LOSS are not being sent when audio focus is lost

### ISSUE THREAD

**Issue by aljohnston112** [androidx/media#1470]
### Version

Media3 main branch

### More version details

    implementation "androidx.media3:media3-common:1.2.0"
    implementation "androidx.media3:media3-exoplayer:1.2.0"
    implementation "androidx.media3:media3-session:1.2.0"

### Devices that reproduce the issue

Pixel 8 Android 14

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. Create a Player with setAudioAttributes' handleAudioFocus parameter to true.
2. Set up a MediaSession and start playback.
3. Have another app take audio focus.

### Expected result

As described here: https://github.com/google/ExoPlayer/issues/10293

When playback is stopped due to loss of audio focus, Player.Listener.onPlaybackSuppressionReasonChanged will be called with reason Player.PLAYBACK_SUPPRESSION_REASON_TRANSIENT_AUDIO_FOCUS_LOSS.

The event included in Player.Listener.onEvents() with key EVENT_PLAYBACK_SUPPRESSION_REASON_CHANGED.

### Actual result

Neither of the two expected results happen.

### Media

Not applicable

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by aljohnston112** [comment]
I did find that ```onPlayWhenReadyChanged``` is triggered with reason ```PLAY_WHEN_READY_CHANGE_REASON_AUDIO_FOCUS_LOSS``` when audio focus is lost. If that is what the intended behavior is, feel free to close this ticket.

**Comment by tonihei** [comment]
Yes, this is the intended behavior. Note that there is a difference between `onPlaybackSuppressionReasonChanged(PLAYBACK_SUPPRESSION_REASON_TRANSIENT_AUDIO_FOCUS_LOSS)` (= **transient**, short-lived suppression with automatic resumption) and `onPlayWhenReadyChanged(PLAY_WHEN_READY_CHANGE_REASON_AUDIO_FOCUS_LOSS)` (=a permanent focus loss, no automatic resumption).
