### ISSUE TITLE
Implement Custom Browse Actions with Media3 MediaLibraryService

### ISSUE THREAD

**Issue by icutvaric** [androidx/media#1474]
How can we implement same Custom Browse Actions described in here https://developer.android.com/training/cars/media#how_to_implement_custom_browse_actions
with Media3 MediaLibraryService?

**Comment by tonihei** [comment]
We are in the process of adding this feature and we can use this issue to track this effort publicly. Unfortunately, we missed that Android Auto published guidelines for this already without waiting for the Media3 implementation, so apologies for the feature gap.

**Comment by icutvaric** [comment]
@tonihei thanks for the clarification. Do you know approx. when can we expect this feature?

**Comment by tonihei** [comment]
Yes, I meant Automotive (fixed my post too). And we can't provide concrete timelines, but unfortunately it won't be part of the upcoming 1.4.0 release. We'll try to get it in as soon as possible afterwards.

**Comment by marcbaechinger** [comment]
The [Media3 API for this is documented now on DAC](https://developer.android.com/media/media3/session/serve-content#command-buttons-for-media-items) as part of the 1.5 release.

Custom browse actions declared by a legacy `MediaBrowserServiceCompat` are converted to command buttons for media items in Media3 and vice versa. 

With the legacy library, this feature is only available to a `MediaBrowserCompat`. In Media3 this is a feature of the basic `MediaSession` and hence is available to `MediaController` and `MediaBrowser` in the same way and doesn't require a `MediaLibraryService`.

I'm closing this issue. Please file a new issue regarding the implementation if required.
