### ISSUE TITLE
Migrated to Media 3 Debug benchflixdebug logs?

### ISSUE THREAD

**Issue by techker** [androidx/media#1478]
We currently migrated our app to Media 3 and when in debug mode there is a really invasive log benchflixdebug? Is there a way to shut that off? 

024-06-20 11:40:17.030 13641-16195 benchflixdebug          com.myapp              D  offset: 0 size: 6144 presentationTimeUs: 600539375 flags: 0......

**Comment by tonihei** [comment]
These logs are not coming from our library, so I'm afraid we can't help you there. Interestingly, you also seem to be the [first person to ever mention this on the Internet](https://www.google.com/search?q=%22benchflixdebug%22) :), so maybe it's coming from your own app or some special device set up you are using?

**Comment by techker** [comment]
no special setup.odd, i have also another app i added and it shows.Need to
do some more digging.

**Comment by techker** [comment]
i asked chat gpt to see lol
The `benchflixdebug` log in your Media3 layer Android app likely originates
from the benchmarking tools or debug logs embedded within the app or the
libraries it uses. Media3 is a suite of libraries for media playback and
UI, and often developers include detailed logs to help diagnose performance
issues or ensure proper functionality during development.

Here are a few steps to identify and potentially resolve the source of this
log:

1. **Check Log Tags and Sources**: Look at the tags associated with the log
messages. These often indicate the source module or library. Search your
codebase for `benchflixdebug` to pinpoint where it's being logged.

2. **Review Media3 Documentation**: Review the Media3 documentation or any
other libraries you are using to see if they mention benchmarking or debug
logging features.

3. **Debug Configuration**: Sometimes, debug logs can be controlled through
configuration files or build variants. Ensure your app is not running in a
debug or verbose logging mode if unnecessary.

4. **Remove or Adjust Logging**: If you identify the source and determine
it's not needed, you can either adjust the logging level or remove it
entirely from your development or production builds.

If you provide more context or specific log examples, I can offer more
precise guidance.

**Comment by tonihei** [comment]
We found some internal bugs referencing a tool called Benchflix actually. It seems to be a third-party benchmarking tool that can be used to debug/benchmark devices. Maybe someone left this enabled/installed on your test device? I'll close the issue in any case because there still nothing we can do about that in our library.
