### ISSUE TITLE
The url can't play

### ISSUE THREAD

**Issue by FongMi** [androidx/media#1485]
### Version

Media3 1.3.1

### More version details

Unable to play url via OkHttpDataSource
But the downloaded video can be played

### Devices that reproduce the issue

Xiaomi 13

### Reproducible in the demo app?

Yes

### Reproduction steps

Play url by progressive type

### Expected result

It should be able to play like MXplayer

### Actual result

![image](https://github.com/androidx/media/assets/3471963/bac0922c-2dfe-4cce-9852-c8abc23502fa)

### Media

https://download6.mcloud.139.com/storageWeb/servlet/downloadServlet?code=TUEwMDExV1Y0WFYwVHU3MTExN3dCdEN2ckti&un=1217540CFF7482339CFAD1429AE34CEA886FF97A5A8AB3B58C86EF110E93F993&dom=D933&rate=0&txType=0

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by FongMi** [comment]
I found that the requested Range is different from MX Player
But they all start playing from 0

MX Player
![image](https://github.com/androidx/media/assets/3471963/b91e8028-6812-4e63-8713-42939c6703a0)

ExoPlayer
![image](https://github.com/androidx/media/assets/3471963/f9f70a38-066d-4638-b115-10405f3cffdd)

**Comment by icbaker** [comment]
> ### Media
> https://download.mcloud.139.com/storageWeb/servlet/downloadServlet?code=S0IwaTExWXc3Tk0weXkwODkxN3dCcVBEQk9H&un=B8C3F2014B53E467A8BC00DCEFBAD3B0B818EA2BF742F71CA414E126D6C09851&dom=D961&rate=0&txType=0

This link gives a 404 for me. Please can you provide the media in a way we can access?

**Comment by FongMi** [comment]
> > ### Media
> > https://download.mcloud.139.com/storageWeb/servlet/downloadServlet?code=S0IwaTExWXc3Tk0weXkwODkxN3dCcVBEQk9H&un=B8C3F2014B53E467A8BC00DCEFBAD3B0B818EA2BF742F71CA414E126D6C09851&dom=D961&rate=0&txType=0
> 
> This link gives a 404 for me. Please can you provide the media in a way we can access?

https://download.mcloud.139.com/storageWeb/servlet/downloadServlet?code=S0EwaTExWXc3Tk0weXkwODYxN3dCdEN0dUww&un=943ED44DE0309328129758D6BDA5C7B5DC14CFDD686BA601463212AC72640C0B&dom=D961&rate=0&txType=0

**Comment by FongMi** [comment]
Here is new one
https://download6.mcloud.139.com/storageWeb/servlet/downloadServlet?code=TUEwMDExV1Y0WFYwVHU3MTExN3dCdEN2ckti&un=1217540CFF7482339CFAD1429AE34CEA886FF97A5A8AB3B58C86EF110E93F993&dom=D933&rate=0&txType=0

**Comment by icbaker** [comment]
> Here is new one
> https://download6.mcloud.139.com/storageWeb/servlet/downloadServlet?code=TUEwMDExV1Y0WFYwVHU3MTExN3dCdEN2ckti&un=1217540CFF7482339CFAD1429AE34CEA886FF97A5A8AB3B58C86EF110E93F993&dom=D933&rate=0&txType=0

I can download this one from the browser, but when i try and play it with the demo app I get an HTTP 500 error (both with cronet and okhttp).

If the byte range requested by Exoplayer is within the length of the file (which it almost certainly is if local playback works) then this is likely a question for the server provider, since they shouldn't be rejecting the request. I'm not going to spend more time trying to repro this, I suggest you contact the server provider since there's no evidence of an ExoPlayer bug here.

**Comment by icbaker** [comment]
Closing because we were unable to repro due to HTTP 500 errors, and the details of the issue provided sound like an issue with the media or the content server, not the playback library.
