### ISSUE TITLE
Hiding duration textviews

### ISSUE THREAD

**Issue by Soft-Buddy** [androidx/media#1486]
![image](https://github.com/androidx/media/assets/149814863/f4141697-0c31-435f-9df8-7f3b29298904)

I'm playing an hls stream from m3u8 url. I wish to hide the duration textviews... If possible

**Comment by oceanjules** [comment]
I'm assuming you mean, you want to hide the following:

https://github.com/androidx/media/blob/d833d59124d795afc146322fe488b2c0d4b9af6a/libraries/ui/src/main/java/androidx/media3/ui/PlayerControlView.java#L447-L448

There is currently no programmatic way to do it. However, I wonder if you can override `exo_player_control_view.xml` with your own layout? And omit the following:
https://github.com/androidx/media/blob/d833d59124d795afc146322fe488b2c0d4b9af6a/libraries/ui/src/main/res/layout/exo_player_control_view.xml#L46-L54

**Comment by Soft-Buddy** [comment]
![image](https://github.com/androidx/media/assets/149814863/f7811b7f-4293-4c50-9036-3c5807bd893a)
Thank you for giving me the directions.
