### ISSUE TITLE
KEYCODE_HEADSETHOOK and double click behaviour

### ISSUE THREAD

**Issue by DavidEdwardsBL** [androidx/media#1493]
### Version

Media3 main branch

### Devices that reproduce the issue

Devices that have a headset attached to them and send `KEYCODE_HEADSETHOOK` when clicking on the headsets primary button. 

Concrete error device: `OPPO CPH1951`.

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. Play media
2. Double click on headset primary button (usually on single button headsets it is play / pause)

On all devices, the issue can be reproduced by sending the keycode for `KEYCODE_HEADSETHOOK` twice (replicating a double tap) over ADB.

We took a look at the code, and can see why there is an issue. At [this stage, we are testing for PLAY_PAUSE and HEADSETHOOK](https://github.com/androidx/media/commit/f2cf43ccd562e2cf23f85ee7a43fc5824e5de2e9#diff-28d9a8014284d097c12c0fb28894d9e5c9578b3fdd698ea71774916cc2787f31R1117). It then [sets a handler to fire to detect a double tap](https://github.com/androidx/media/commit/f2cf43ccd562e2cf23f85ee7a43fc5824e5de2e9#diff-28d9a8014284d097c12c0fb28894d9e5c9578b3fdd698ea71774916cc2787f31R1129). Once the [next tap comes through, the double tap flag is set](https://github.com/androidx/media/commit/f2cf43ccd562e2cf23f85ee7a43fc5824e5de2e9#diff-28d9a8014284d097c12c0fb28894d9e5c9578b3fdd698ea71774916cc2787f31R1126). 

After the flag is set, it will be checked either [here](https://github.com/androidx/media/commit/f2cf43ccd562e2cf23f85ee7a43fc5824e5de2e9#diff-28d9a8014284d097c12c0fb28894d9e5c9578b3fdd698ea71774916cc2787f31R1141) or [here](https://github.com/androidx/media/commit/f2cf43ccd562e2cf23f85ee7a43fc5824e5de2e9#diff-28d9a8014284d097c12c0fb28894d9e5c9578b3fdd698ea71774916cc2787f31R1161). Unfortunately, neither cases take KEYCODE_HEADSETHOOK into account. This leads to next media not being set.

### Expected result

The system converts to a seek to next.

### Actual result

The system makes a play / pause.

### Media

Any

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment]
Thanks for reporting - it looks like `HEADSETHOOK` is handled for double tap by media1: https://cs.android.com/android/platform/superproject/+/androidx-main:frameworks/support/media/media/src/main/java/android/support/v4/media/session/MediaSessionCompat.java;l=1147-1150;drc=1991cf1992f8ec2331848b8f0b6c26a433da5f54

I also noticed our code seems to consider `KEYCODE_MEDIA_PLAY` for the **second** of a double tap (in one of the branches), but not the first:
https://github.com/androidx/media/blob/be2d68c2b373384529cc6b359d658d022942ec71/libraries/session/src/main/java/androidx/media3/session/MediaSessionImpl.java#L1252-L1253

I've sent a change to make all 3 places handle all 3 of:
* `HEADSETHOOK`
* `PLAY_PAUSE`
* `PLAY`

**Comment by icbaker** [comment]
After a bit of back and forth in review, I dropped the handling of `PLAY` for consistency with what we [already document](https://developer.android.com/reference/androidx/media3/session/MediaSession#media-key-events-mapping). The change is linked above.
