### ISSUE TITLE
Unstable Api Annotations

### ISSUE THREAD

**Issue by Faiyyaz** [androidx/media#1495]
Hi,

Thank you for such a great library.

I have a question if you see the sample ```main``` most of the classes like DemoUtil, DownloadTracker, TrackSelectionDialog etc are using @UnstableApi annotations.

Can you let me know why it is like that?

Also if it is unstable, can you provide a stable example for the same since in our app we need to give quality control, download features etc which used to work fine in exoplayer2 without such annotations.

**Comment by oceanjules** [comment]
You can see what is meant by "stability" here in the [README](https://github.com/androidx/media?tab=readme-ov-file#api-stability) and [UnstableAPI java doc](https://github.com/androidx/media/blob/main/libraries/common/src/main/java/androidx/media3/common/util/UnstableApi.java).

In short: it doesn't have to do with _quality_ or _performance_. You can assume the functions and classes behave as documented. However, the library is not ready to freeze these APIs and commit to long-term backwards compatibility. So use with caution to avoid breaking changes when upgrading the library version.

**Comment by Faiyyaz** [comment]
Okay so if you are saying those can be removed then can we have stable version of the same example if possible?

**Comment by oceanjules** [comment]
Stabilising the API is a lengthy process and the full ExoPlayer/media3 API (everything accessible by an application developer like you) is too large to guarantee this kind of stability. We want to be sure that everything we add to the stable API is worth the long-term investment of the team supporting it. There is a trade-off between freezing the APIs too early and allowing the flexible experimental setup like this to evolve over time to something better.

When ExoPlayer moved to the `androidx.media3` package, it went through a stabilising stage. We became a part of AndroidX libraries and hence we now adhere to backward-compatibility guarantees between minor versions. 

When we do promote APIs to stable, it is announced in the [release notes](https://developer.android.com/jetpack/androidx/releases/media3).

If you think your particular use-case cannot be achieved using the stable API only, you could file an issue about stabilising those components. However, looking at the list of classes you pasted: `DemoUtil` is utility methods for the main demo,  `DownloadTracker` and `TrackSelectionDialog` are also just examples of how to achieve certain functionality. You are free to copy it over to your project and customize according to your needs. The library as a whole does not rely on these classes.

**Comment by Faiyyaz** [comment]
Okay the list of features I am trying to achieve are download track, quality control, speed control etc. I copied it over since the same code was used in exoplayer2 to do the same and it used to work fine since many years and even the sample app has the same code as of now
