### ISSUE TITLE
Is it necessary to specify `C.CLEARKEY_UUID` to play DASH ClearKey streams?

### ISSUE THREAD

**Issue by hakonschia** [androidx/media#1500]
I'm trying to play a DASH ClearKey stream. We currently create our media item as such `player.setMediaItem(MediaItem.fromUri("..."))`. This results in no video being shown, but the stream is playing (in the sense that the scrubber moves and no playback error occurs, and also subtitles are shown at the correct timestamps)

If I add a DrmConfiguration specifying `C.CLEARKEY_UUID` it plays as expected:

```
player.setMediaItem(
    MediaItem.Builder()
        .setUri("...")
        .setDrmConfiguration(
            DrmConfiguration.Builder(C.CLEARKEY_UUID)
                .build()
        )
        .build()
)
```

It looks like [DashManifestParser](https://github.com/androidx/media/blob/d833d59124d795afc146322fe488b2c0d4b9af6a/libraries/exoplayer_dash/src/main/java/androidx/media3/exoplayer/dash/manifest/DashManifestParser.java#L649) already parses out the ClearKey UUID. It also parses out the license server URL correctly so I don't have to call `setLicenseUri()` on the DrmConfiguration builder

So my question is: Is it necessary to specify the DRM type when building the media item, or is there something I'm missing here?

We're on version 1.3.1. Here's a stream URL (it should be available globally, please let me know if it isn't)

https://static.nrk.no/dev/streamtests/scalcast/clearkey/dash.mpd

**Comment by icbaker** [comment]
Yes, this is needed so that the `MediaSource` is configured for the right type of DRM playback. This is mentioned at https://developer.android.com/media/media3/exoplayer/drm

**Comment by hakonschia** [comment]
Thanks for the quick reply.

The docs you linked also say

> and the license server URI should be specified [when building a media item](https://developer.android.com/guide/topics/media/exoplayer/media-items#protected-content).

Is this a general rule that doesn't apply to DASH ClearKey? As I mentioned it seems to play without having to specify this and it uses the one found in the manifest. I'm just wondering if there is some sort of condition that will make it not use the URI in the manifest which results in video being displayed if I don't specify the URI manually in the DrmConfiguration

**Comment by icbaker** [comment]
Ah fair point, that wording is a bit confusing, the javadoc on [`MediaItem.DrmConfiguration.Builder#setLicenseUri`](https://developer.android.com/reference/androidx/media3/common/MediaItem.DrmConfiguration.Builder#setLicenseUri(java.lang.String)) is maybe a bit more clear that it's a 'default' (i.e. only used if the media doesn't specify a license URI [1]) and 'optional'.

I've sent a change to tighten up the wording on the docs page I linked, and also to make it clear that the code snippet in https://developer.android.com/media/media3/exoplayer/media-items#protected-content is just an example showing some fields that can be set, but not all of them need to be in all cases.

[1] WIth the caveat of this can be over-ridden with [`MediaItem.DrmConfiguration.Builder#setForceDefaultLicenseUri`](https://developer.android.com/reference/androidx/media3/common/MediaItem.DrmConfiguration.Builder#setForceDefaultLicenseUri(boolean))

**Comment by hakonschia** [comment]
Got it, thanks!
