### ISSUE TITLE
Colours discrepancy when applying overlay

### ISSUE THREAD

**Issue by mikekudzin** [androidx/media#1509]
### Version

Media3 pre-release (alpha, beta or RC not in this list)

### More version details

1.4.0-beta01

### Devices that reproduce the issue

Pixel 4a Android 13

### Reproducible in the demo app?

Not tested

### Reproduction steps

Overlaying video with a bitmap.

![28 Jun 2024 11_18_34 GMT_overlays](https://github.com/androidx/media/assets/7223881/5c199ab6-b101-434b-be45-9dd4189eafbe)

no. 1: Create transparent media items with a BitmapOverlay
Code:        
        
        val bitmapOverlayWithText = BitmapOverlay.createStaticBitmapOverlay(overlayBitmap)
        val overlayFrameEMI = EditedMediaItem.Builder(MediaItem.fromUri(frameFile.toUri()))
            .setFrameRate(D_F_RATE)
            .setDurationUs(D_DURATION)
            .setRemoveAudio(true)
            .setEffects(
                Effects(
                    listOf(),
                    listOf(
                        OverlayEffect(ImmutableList.of(bitmapOverlayWithText)),
                    )
                )
            )
            .build()

        val backgroundMI = MediaItem.fromUri(backgroundBitmapFile.toUri())
        val backgroundEMI = EditedMediaItem.Builder(backgroundMI)
            .setFrameRate(D_F_RATE)
            .setDurationUs(D_DURATION)
            .setRemoveAudio(true)
            .build()

        val videoMI = MediaItem.Builder().setUri(baseMediaUri)
            .setClippingConfiguration(
                MediaItem.ClippingConfiguration.Builder()
                    .setStartPositionUs(0)
                    .setEndPositionUs(D_DURATION)
                    .build()
            )
            .build()

        val videoEMI = EditedMediaItem.Builder(videoMI)
            .setEffects(
                Effects(
                    listOf(),
                    listOf(ScaleAndRotateTransformation.Builder().setRotationDegrees(45f).build())
                )
            )
            .build()

        val composition = Composition.Builder(
            EditedMediaItemSequence(overlayFrameEMI),
            EditedMediaItemSequence(videoEMI),
            EditedMediaItemSequence(backgroundEMI),            
        )
            .build()

        val transformer: Transformer =
            Transformer.Builder(context)
                .setVideoMimeType(MimeTypes.VIDEO_H264)
                .setAudioMimeType(MimeTypes.AUDIO_AAC)
                .build()
        transformer.start(composition, outputFilePath)

Result:

![image](https://github.com/androidx/media/assets/7223881/b353f400-78d4-446a-b32e-593d4986dbab)

no. 2: create MediaItem directly from the file
Code diff
        val overlayFrameEMI = EditedMediaItem.Builder(MediaItem.fromUri(overlayFile.toUri()))
            .setFrameRate(D_F_RATE)
            .setDurationUs(D_DURATION)
            .build()

![image](https://github.com/androidx/media/assets/7223881/5efbe4fd-96e2-47d6-8a64-ac83ecdc9879)

Although, the the last one looks close to origin, there is a significant colours discrepancy between the origin no. 1 and no. 2
I didn't observe no. 1 issue on 1.3.1 

### Expected result

Colours in the output are the same as in the origin.

### Actual result

There is a difference between colours in the origin and BitmapOverlay

### Media

-

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by tof-tof** [comment]
Hi @mikekudzin, thanks for writing in.

just to make sure I understand the setup, are you saying in (1) you used overlays and in (2) you didn't use overlays at all?

Since you didn't see it in 1.3.1 I figure it could have some involvment to with the way we process color changing. Using the code in https://github.com/androidx/media/issues/1050#issuecomment-2132541344 may help your case

In addition I see there are some artefacts  around the borders of your image. @ychaparov does any of the recent work you've done around improving sampling help with this?

**Comment by ychaparov** [comment]
Not really, we haven't made improvements to resampling of 45-degree rotated videos yet.

The original image [bitmap overlay](https://private-user-images.githubusercontent.com/7223881/344146813-5c199ab6-b101-434b-be45-9dd4189eafbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDIzOTYsIm5iZiI6MTcyMDAwMjA5NiwicGF0aCI6Ii83MjIzODgxLzM0NDE0NjgxMy01YzE5OWFiNi1iMTAxLTQzNGItYmU0NS05ZGQ0MTg5ZWFmYmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDNUMTAyMTM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDI3OGE2ZDhiNWI3MjY1ODdiOWIyZmQwNzliOTlhNmUzMDYyMjBlZTcyYWU5Yjg1OTgwYzQ2MWQ2MGM2MTcyNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aD7b_W3f23_r73SqsDJxLgSVzP-y9I9HYUZsOAohzxc) is not aligned with the [no. 1 output](https://private-user-images.githubusercontent.com/7223881/344147729-b353f400-78d4-446a-b32e-593d4986dbab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDIzOTYsIm5iZiI6MTcyMDAwMjA5NiwicGF0aCI6Ii83MjIzODgxLzM0NDE0NzcyOS1iMzUzZjQwMC03OGQ0LTQ0NmEtYjMyZS01OTNkNDk4NmRiYWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDNUMTAyMTM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTRmMmZjNDZhZWJhNTFmYWMzMzExOThmNDkzMDdmMjlmNWY3NTJlMzk3N2U5ZGVjYWUxNjE1NWM2YTI4YWUyOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GkIyYmXoXPMTa_qHO1s-kpU-OIqtS-OPPxtswREQ2I0) -- the text is a bit scaled and rotated even though both images have resolution 1080x1920.
I don't think `BitmapOverlay` causes this image modification.

@mikekudzin can you share your bitmap-reading code?
How did you create `overlayBitmap` used in
```
    val bitmapOverlayWithText = BitmapOverlay.createStaticBitmapOverlay(overlayBitmap)
```

**Comment by yuriikonovalov** [comment]
@tof-tof @ychaparov I have the same problem. The version is [1.4.0-beta01](https://developer.android.com/jetpack/androidx/releases/media3#1.4.0-beta01). I've tried the suggestion in the [#1050 ](https://github.com/androidx/media/issues/1050#issuecomment-2132541344) comment but it does not help.

Here is the input and output resources:
* This image is added as a `MediaItem`
<img height="100" src="https://github.com/androidx/media/assets/84384099/c8a8cfb9-cc01-4755-bc11-5728e6349112"/>

* This image is added as a `BitmapOverlay`
<img height="100"  src="https://github.com/androidx/media/assets/84384099/1b2a3d7d-da63-499e-992b-b4d7e6d93011"/>

* This is a frame in an output video
<img height="500" src="https://github.com/androidx/media/assets/84384099/534bd8bc-b6ef-461b-a18b-cf8c52ab2f4f"/>

&nbsp;
Here is the way the overlay bitmap is created:
```kotlin
   val stream = context.contentResolver.openInputStream(uri)
   val bitmap = BitmapFactory.decodeStream(stream)
```

**Comment by ychaparov** [comment]
Depending on the image you're loading, you should probably set some bitmap factory options like this:

```
    if (Util.SDK_INT >= 26) {
      options = new BitmapFactory.Options();
      options.inPreferredColorSpace = ColorSpace.get(ColorSpace.Named.SRGB);
    }
```

Here's how the MediaItem image BitmapFactory options will be set https://github.com/androidx/media/blob/d833d59124d795afc146322fe488b2c0d4b9af6a/libraries/transformer/src/main/java/androidx/media3/transformer/DefaultAssetLoaderFactory.java#L83

**Comment by yuriikonovalov** [comment]
@ychaparov just tried that and it stays the same as I mentioned above.

**Comment by mikekudzin** [comment]
> just to make sure I understand the setup, are you saying in (1) you used overlays and in (2) you didn't use overlays at all?

@tof-tof Correct.

@ychaparov here is bitmap initialisation code. 
```
    private fun createCanvasBitmap(width: Int = D_WIDTH, height: Int = D_HEIGHT): Bitmap {
        val bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
        return bitmap
    }

    protected fun initCanvas(width: Int = D_WIDTH, height: Int = D_HEIGHT): Pair<Canvas, Bitmap> {
        val bitmap = createCanvasBitmap(width, height)
        val canvas = Canvas(bitmap)
        return canvas to bitmap
    }
```

**Comment by droid-girl** [comment]
@yuriikonovalov and @mikekudzin how many `EditedMediaItemSequence`s do you have in your composition?

**Comment by yuriikonovalov** [comment]
@droid-girl In my case, it's 2 `EditedMediaItemSequences`. One is for a video. Another one is a transparent image with those bitmap overlays.

**Comment by mikekudzin** [comment]
@droid-girl I use 3 `EditedMediaItemSequences`

**Comment by droid-girl** [comment]
@ychaparov figured out the problem, we will have a fix soon in main. The issue was with `Composition` that contains more than 1 sequence containing video/image assets.

**Comment by ychaparov** [comment]
Could you please try verify if https://github.com/androidx/media/commit/7103f21da9498ec4208d5ed8fe49be27cd104986 fixes the issue for your use cases?
