### ISSUE TITLE
Customize buttons in Android Auto via MediaLibraryService

### ISSUE THREAD

**Issue by vanniktech** [androidx/media#151]
I already have managed to get my app running on Android Auto using a MediaLibraryService. However, I'd like to customize the buttons. Currently, only seek to previous and play pause are shown:

<img width="800" alt="Screen Shot 2022-08-15 at 20 15 04" src="https://user-images.githubusercontent.com/5759366/184692082-37b6f12d-33fd-4929-a341-7870c665f3c3.png">

How can I issue more buttons? I've already tried the following in `onCreate`:

```kotlin
mediaSession?.setCustomLayout(
  listOf(
    CommandButton.Builder()
      .setPlayerCommand(Player.COMMAND_SEEK_FORWARD)
      .setIconResId(androidx.media3.session.R.drawable.media3_notification_seek_to_next)
      .setDisplayName("Forward")
      .build()
  )
)
```

No luck. Still the same layout. I also read about:

```kotlin
override fun onConnect(session: MediaSession, controller: MediaSession.ControllerInfo): MediaSession.ConnectionResult {
  val connectionResult = super.onConnect(session, controller)
  val sessionCommands =
    connectionResult.availableSessionCommands
      .buildUpon()
      // Add custom commands
      .add(SessionCommand("REWIND_30", Bundle()))
      .add(SessionCommand("FAST_FWD_30", Bundle()))
      .build()
  return MediaSession.ConnectionResult.accept(
    sessionCommands, connectionResult.availablePlayerCommands
  )
}
```

Does nothing either. How can I get a layout similar to Spotify using media3?

<img width="800" alt="Screen Shot 2022-08-15 at 10 37 50" src="https://user-images.githubusercontent.com/5759366/184603713-2155e28e-82ac-48ef-8290-75076a6d90d6.png">

**Comment by rohitjoins** [comment]
@vanniktech You can add custom commands to `MediaLibraryService` as shown below:
```
mediaLibrarySession.setCustomLayout(
  listOf(
        CommandButton.Builder()
          .setDisplayName("Rewind")
          .setSessionCommand(SessionCommand("REWIND_30", Bundle()))
          .setIconResId(androidx.media3.session.R.drawable. media3_notification_seek_to_next)
          .build()
      )
)
```

Note that I'm using `setSessionCommand` here. You would also need to override the function `onCustomCommand` to make the buttons actionable. You can find an example implementation [here](https://github.com/androidx/media/blob/release/demos/session/src/main/java/androidx/media3/demo/session/PlaybackService.kt).

**Comment by vanniktech** [comment]
That does work! Thanks @rohitjoins. One other thing. In my `onGetLibraryRoot`, I have the following code:

```
override fun onGetLibraryRoot(
  session: MediaLibrarySession,
  browser: MediaSession.ControllerInfo,
  params: LibraryParams?,
): ListenableFuture<LibraryResult<MediaItem>> {
  val rootExtras = Bundle().apply {
    putBoolean(
      MediaConstants.BROWSER_SERVICE_EXTRAS_KEY_SEARCH_SUPPORTED,
      true,
    )
    putBoolean("android.media.browse.CONTENT_STYLE_SUPPORTED", true)
    putInt(
      MediaConstants.DESCRIPTION_EXTRAS_KEY_CONTENT_STYLE_BROWSABLE,
      MediaConstants.DESCRIPTION_EXTRAS_VALUE_CONTENT_STYLE_GRID_ITEM,
    )
    putInt(
      MediaConstants.DESCRIPTION_EXTRAS_KEY_CONTENT_STYLE_PLAYABLE,
      MediaConstants.DESCRIPTION_EXTRAS_VALUE_CONTENT_STYLE_LIST_ITEM,
    )
  }
  val libraryParams = LibraryParams.Builder().setExtras(rootExtras).build()
  return Futures.immediateFuture(LibraryResult.ofItem(rootMediaItem, libraryParams))
}
```

in `onGetChildren`, I load all of my items and they are being displayed just fine:

<img width="800" alt="Screen Shot 2022-08-17 at 23 27 20" src="https://user-images.githubusercontent.com/5759366/185246388-62b8ca89-8bcc-441b-bac5-269935a90d50.png">
 
However when selecting one, I'd expect to use the List of `MediaItem` so that I can automatically skip ahead. But instead my queue contains only the selected item:

<img width="800" alt="Screen Shot 2022-08-17 at 23 28 20" src="https://user-images.githubusercontent.com/5759366/185246576-90ca5839-0b99-44a0-b81f-ca740540f520.png">


How can I let my queue be all my items?

**Comment by rohitjoins** [comment]
We generally try to keep issues focused on one topic. Please
[open a new issue](https://github.com/google/ExoPlayer/issues/new/choose). This way we can assign
someone that can provide support specifically for your question. I will mark your comment as
off-topic. Thanks!

**Comment by vanniktech** [comment]
Amazing how easy it is to set custom buttons once you know how to make 'em work. Nice work @rohitjoins & the rest of your team!
