### ISSUE TITLE
Request support for kotlin multiplatform

### ISSUE THREAD

**Issue by tmxdyf** [androidx/media#1512]
Hi, this is a feature request. Thank you very much for the media3 team for developing such an excellent work. It would be perfect if it can support kotlin multiplatform, so that developers can use media3 on ios and desktop. Thanks!

**Comment by icbaker** [comment]
Both Media3 ExoPlayer and MediaSession tightly integrate with Android-specific framework APIs (`MediaCodec`, `AudioTrack`, `MediaSession`, etc). We don't have any plans to write additional player implementations on top of the lower level APIs available on other devices, so it's therefore not really feasible to suport Kotlin Multiplatform.
