### ISSUE TITLE
Using CustomDashManifestParser class (extends DashManifestParser) with DownloadHelper class

### ISSUE THREAD

**Issue by flashworldnet** [androidx/media#1514]
I am currently using a CustomDashManifestParser to play ClearKey protected contents on my Android application. The reason for using a CustomDashManifestParser is because the KID is not included in the Dash manifest of the contents. Currently, I am having no issues playing these contents online. Because there I can parse my CustomDashManifestParser when creating the DashMediaSource.

My question is, how to use this CustomDashManifestParser with the DownloadHelper class. Then I can play these contents offline as well.

What I am currently doing
```
DashMediaSource.Factory(DownloadUtil.getHttpDataSourceFactory(requireContext()))
        .setManifestParser(CustomDashManifestParser(keys))
        .setDrmSessionManagerProvider { drmSessionManager }
        .createMediaSource(dashMediaItem)
```

**Comment by tonihei** [comment]
I assume you are currently trying to use `DownloadHelper.forMediaItem`? This method uses a `DefaultMediaSourceFactory` internally for convenience, so it can't use your custom setup. You can instead use the constructor of `DownloadHelper` that allows you to pass in any custom `MediaSource` directly:
```
DownloadHelper(
  dashMediaItem,
  DashMediaSource.Factory(...)...createMediaSource(dashMediaItem),
  DownloadHelper.getDefaultTrackSelectionParameters(context),
  DefaultRendererCapabilitiesList.Factory(renderersFactory).createRendererCapabilitiesList())
```

**Comment by flashworldnet** [comment]
Thanks for the suggestion.

I used the DownloadHelper.createMediaSource() method to create the media source which will then be parsed to the player. It worked well without any issue except for the above scenario.

I am going to try your suggestion but it will not return a media source right?

**Comment by tonihei** [comment]
My suggestion was about using the `DownloadHelper` to create the `DownloadRequest`. If you already have a `DownloadRequest` you can simply call `downloadRequest.toMediaItem()` and use it directly with your custom `MediaSource.Factory`.

**Comment by flashworldnet** [comment]
Yeah I already have the download request. I will try and give an update.

**Comment by flashworldnet** [comment]
It worked. Thanks.

Closing the issue
