### ISSUE TITLE
Update the End of a Live Clip During Playback

### ISSUE THREAD

**Issue by Xlcghs** [androidx/media#1517]
I need to update my DashMediaSource during playback, given that this media source is a live ClippingMediaSource with a start position. I want to update the end of this clip based on an event detected in the manifest and insert a new item into the player at the end of this clip without impacting the user interface. In other words, I want the modification of the mediaSource's endTime and the transition to the next item to be seamless. Is this possible with the APIs provided by Media3, such as updateMediaItem? Do you have any idea how to achieve this?

Thank you

**Comment by tonihei** [comment]
Updating the clipping mid-playback is unfortunately not yet supported. The feature is tracked by https://github.com/google/ExoPlayer/issues/3163.
