### ISSUE TITLE
media3 create MediaController no result

### ISSUE THREAD

**Issue by aacai** [androidx/media#1524]
https://developer.android.google.cn/media/media3/session/connect-to-media-app?hl=zh-cn#create-controller 
I created the MediaController exactly as per the tutorial on the official website, but it just doesn't call back the code block in my listener。
![image](https://github.com/androidx/media/assets/62132503/744f1ca5-ee44-4b64-8739-7f70c3ca8656)
![image](https://github.com/androidx/media/assets/62132503/a6924b66-718f-4d9d-84bf-e43c4126a02b)
It was available at first, but now it does not enter the callback anyway

media3 version is 1.3.1, android 14

**Comment by aacai** [comment]
if needed ,this is sample,click 全部电台 -> click any Station ,The bug will reappear

**Comment by aacai** [comment]
[PlayVideo.zip](https://github.com/user-attachments/files/16081230/PlayVideo.zip)
this is my sample

**Comment by debz-eight** [comment]
Try this:

Create two variables and initialize as I did below:

````
private var controller: MediaController? = null
private var mediaControllerFuture: ListenableFuture<MediaController>? = null

@UnstableApi
  private fun initializeMediaController() {
        val sessionToken =
            SessionToken(this, ComponentName(this, SongPlayerService::class.java))
        mediaControllerFuture = MediaController.Builder(this, sessionToken).buildAsync()
        mediaControllerFuture?.apply {
            addListener(Runnable {
                controller = get()
            }, MoreExecutors.directExecutor())
        }
    }
````

As for `initializeMediaController()`, call it inside onCreate of Acitivty or onViewCreated of fragment.

**Comment by aacai** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by marcbaechinger** [comment]
See comment from @debz-eight as an exaample.

As per [JavaDoc of `MediaControlle.Builder.buildAsync()`](https://developer.android.com/reference/androidx/media3/session/MediaController.Builder#buildAsync()), you should keep a reference of the `Future` until the listener is executed and you can call `get()` on the future. The future may be garbage collected if you don't do so.
