### ISSUE TITLE
[Feature Request] Add the capability to suppress being automatically started by Bluetooth or other external players when the app isn't running

### ISSUE THREAD

**Issue by Digipom** [androidx/media#1529]
### [REQUIRED] Use case description
The primary complaint I get from users is about the app automatically starting when it receives a play command from a car stereo or other Bluetooth source.

### Proposed solution
Allow setting an option on the session or player to disallow these sorts of background starts.

### Alternatives considered
We can override onMediaButtonEvent and suppress the event, however there are two issues that have to be contended with:
a) Properly detecting that the event is external and was initiated when the app is in the background: https://github.com/androidx/media/issues/1527
b) Handling ForegroundServiceDidNotStartInTimeException: https://github.com/androidx/media/issues/1528

**Comment by marcbaechinger** [comment]
I'm marking this as a dulicate of #1528 . Please let me know if you think that's not the right thing to do.
