### ISSUE TITLE
IcyInfo should be used in MediaMetadata

### ISSUE THREAD

**Issue by y20k** [androidx/media#153]
Some radio streams publish Icecast metadata. ExoPlayer extracts Icecast metadata in the form of 

- `IcyHeaders` and 
- `IcyInfo`. 

`IcyHeaders` are used to [populate](https://github.com/androidx/media/blob/1.0.0-beta02/libraries/extractor/src/main/java/androidx/media3/extractor/metadata/icy/IcyHeaders.java#L176) the `station` and `genre` fields in `MediaMetadata`. You can check that for example in `onMediaMetadataChanged`(Player.Listener): `station` and `genre` are being updated.

`IcyInfo` usually contains information like the currently playing song. It is being extracted properly. You can check that for example in `onMetadata`(Player.Listener). There is also a function that can [populate](https://github.com/androidx/media/blob/1.0.0-beta02/libraries/extractor/src/main/java/androidx/media3/extractor/metadata/icy/IcyInfo.java#L59) `MediaMetadata`. I would correctly update the `title` field. **Problem:** It seems like this function is never used, because the `title` field is not updated in `onMediaMetadataChanged`(Player.Listener).

I tested this behavior in the Media Session Demo app. If you want to reproduce the behavior you would need run the [forked app](https://github.com/y20k/media3) and start the radio station that I added to [catalog.json](https://github.com/y20k/media3/blob/2632b0d5a3e03d7f3f8d679d8dd304951282a80c/demos/session/src/main/assets/catalog.json) and filter LogCat for "ICY issue" ([1](https://github.com/y20k/media3/blob/2632b0d5a3e03d7f3f8d679d8dd304951282a80c/demos/session/src/main/java/androidx/media3/demo/session/PlaybackService.kt#L239)) ([2](https://github.com/y20k/media3/blob/2632b0d5a3e03d7f3f8d679d8dd304951282a80c/demos/session/src/main/java/androidx/media3/demo/session/PlaybackService.kt#L251)) ([3](https://github.com/y20k/media3/blob/2632b0d5a3e03d7f3f8d679d8dd304951282a80c/demos/session/src/main/java/androidx/media3/demo/session/PlaybackService.kt#L265)).

_I think `IcyInfo` should be used in `MediaMetadata` because it contains really interesting information about the currently playing media._

**Comment by icbaker** [comment]
I think the `IcyInfo` title is already incorporated into `MediaMetadata`. In order to see this in the main (not session) demo app I needed to first comment out the `setMediaMetadata` call here, because ExoPlayer assumes that developer-provided metadata should override stream-provided metadata (so the title from the `IcyInfo` is never set into `MediaMetadata`, and so it never changes and the callback is never called):

https://github.com/androidx/media/blob/50475814f700d08519c88585c9583f2aba5d702e/demos/main/src/main/java/androidx/media3/demo/main/IntentUtil.java#L129

I think the same issue (developer-provided metadata overriding media-provided) probably affects your session demo example too.

Can you take a look and see if you can also get this working in the main demo app as I've described?

**Comment by y20k** [comment]
Hi @icbaker 

When I use MediaItems that do not have a title set in their metadata, the player uses stream-provided metadata. It works flawless in my own app. The notification automatically displays IcyInfo from the stream.

Thank you for the clarification and for helping me out!

**Comment by icbaker** [comment]
Glad it's working!

**Comment by y20k** [comment]
Hi @icbaker 

as I wrote in October my app's notification displays IcyInfo metadata, once I do not set the title. :heart: 

There is an unintended consequence of [not setting the title](https://github.com/y20k/media3/blob/2e722acef9dbf7c7bc5f079c1605b779e2d42dae/demos/session/src/main/java/androidx/media3/demo/session/MediaItemTree.kt#L77) though: 

The Always-On Display now reads: **No Title**

<a href="https://user-images.githubusercontent.com/9103935/213874563-f4cc0fe6-2f12-4676-939f-b140a4190d1d.jpg"><img src="https://user-images.githubusercontent.com/9103935/213874563-f4cc0fe6-2f12-4676-939f-b140a4190d1d.jpg" height=320 /></a> <a href="https://user-images.githubusercontent.com/9103935/213874564-6c4cef14-4ae4-4bac-b30d-cbead7a75c12.jpg"><img src="https://user-images.githubusercontent.com/9103935/213874564-6c4cef14-4ae4-4bac-b30d-cbead7a75c12.jpg" height=320 /></a>

The photos above are from a fork of the demo-session app (see https://github.com/y20k/media3/commit/2e722acef9dbf7c7bc5f079c1605b779e2d42dae).

I now wonder ...
... is this something that I can fix?
... is this something that you (media3) can fix?
... or is this something that needs to be handled differently by the Android platform?

**Comment by icbaker** [comment]
Thanks for the update - please can you file a new issue? You can link back to this issue for context, but it's helpful to keep the discussions separate.

**Comment by y20k** [comment]
Okay. I created a new issue.
