### ISSUE TITLE
Should Media3 use media duration to calculate frame rate rather than track duration?

### ISSUE THREAD

**Issue by ybai001** [androidx/media#1531]
**Background**

When I contribute this code: https://github.com/androidx/media/pull/1235, I find there is a potential issue in Mp4Extractor.java.

**Technical Details**

(1) Using AndroidX Media to parse mp4 file. For example, one Media3 test media: https://github.com/androidx/media/blob/release/libraries/test_data/src/test/assets/media/mp4/dolbyVision-hdr.MOV

(2) This test media includes one video track with 5 samples and frame rate is 30fps (You can check it by MediaInfo or other tools.). The key point here is this mp4 file has 'elst' box with segment duration = 64 (timescale = 600, so it is ~0.107s.) If you check the "**TRACK DURATION**" (moov->trak->tkhd→duration), it is same. But the "**MEDIA DURATION**" (moov->trak->mdia->mdhd->duration) is 100 (timescale  = 600, so it is ~0.167s.) All of above follow ISO spec and there is NO problem.

(3) In AndroidX Media, Mp4Extractor::processMoovAtom(), https://github.com/androidx/media/blob/release/libraries/extractor/src/main/java/androidx/media3/extractor/mp4/Mp4Extractor.java#L553, it calculates framerate by "**TRACK DURATION**" rather than "**MEDIA DURATION**", https://github.com/androidx/media/blob/release/libraries/extractor/src/main/java/androidx/media3/extractor/mp4/Mp4Extractor.java#L622
So the result is framerate = 5 / (106667/1000000) = 46.875fps, which is very different from the file's actual framerate (30fps). 

(4) If the "**MEDIA DURATION**" is used, framerate = 5 / (166667/1000000) = 30fps, which is same as the file's actual framerate.

**Thought**

I think, as long as there is 'elst' box in MP4 file, the calculated frame rate will be wrong here.
 
Do you think we should change the behavior here (replace track duration with media duration) in Media3?

**Comment by ybai001** [comment]
Hi, could you have a look whether this is an issue? :)

**Comment by rohitjoins** [comment]
> Do you think we should change the behavior here (replace track duration with media duration) in Media3?

Yes, you're correct. It is more accurate to derive the frame rate using the media duration stored in the mdhd box of each track. We have added a [fix](https://github.com/androidx/media/commit/ecb0024a0b683f7bec8665f6d339f93c3ecca924) for this. Thank you for raising this issue!
