### ISSUE TITLE
How do I detect if media item transition has been triggered from next or previous seek?

### ISSUE THREAD

**Issue by debz-eight** [androidx/media#1537]
I have implemented media3 with MediaSessionService or my song player service and I am using MediaController for my UI side. In my service I also have implemented MediaSession.Callback().

```
val mediaItems = streamerVm.getSongList().map { song ->
                    MediaItem.Builder().setMediaId(song.audio).setMediaMetadata(
                        MediaMetadata.Builder().setFolderType(MediaMetadata.FOLDER_TYPE_ALBUMS)
                            .setArtworkUri(Uri.parse(song.bannerSquare?.md))
                            .setArtist(streamerVm.getSeriesName()).setTitle(song.name)
                            .setExtras(putMediaItemsData()).build()
                    ).build()
                }
                controller.setMediaItems(
                    mediaItems,
                    getCurrentSongPosition(),
                    streamerVm.getCurrentPlayingSongProgressDataInMs()
                )
```

I am setting MediaItems using controller and these media items are being received correctly inside `onAddMediaItems()`.

Now I am two buttons in my UI that calls `contoller.seekToNext()` and `controller.seekToPrevious()` respectively. When any of these two are clicked `onMediaItemTransition(mediaItem: MediaItem?, reason: Int)` is triggered.

Inside `onMediaItemTransition()`, I am getting the reason as `Player.MEDIA_ITEM_TRANSITION_REASON_SEEK` , which only tells me that the media item transition is due to seek.

Is it possible to know whether the media item transition seek is from next or previous seek?

**Comment by marcbaechinger** [comment]
You can use `onPositionDiscontinuity(PositionInfo oldPosition, PositionInfo newPosition, @DiscontinuityReason int reason)` instaed, that gives you the same reason but also `PositionInfo` which allows you to figure out whether the seek was inside or across media items.

**Comment by debz-eight** [comment]
Thanks @marcbaechinger, this worked flawlessly. I was able to solve my requirement.

If anyone is wondering, you can access the index directly by `oldPosition.mediaItemIndex` and `newPosition.mediaItemIndex`. With this you can check if the seek performed was a next seek or a previous seek.
