### ISSUE TITLE
player.addMediaItems or player.setMediaItems  takes too much time

### ISSUE THREAD

**Issue by litianjun05090** [androidx/media#1545]
my code 
```
List<MediaItem> mediaItems=new ArrayList<>();
            for (int i = 0; i < mVideoFiles.size(); i++) {
                    String pathTemp = mVideoFiles.get(i).getPath();
                    Uri uriTemp = Uri.parse(mVideoFiles.get(i).getPath());
                    mediaItems.add(MediaItem.fromUri(uriTemp));
            }
            player.addMediaItems(mediaItems);    //too costly，3000 videos take more than 1000ms
```

I want to put it in  background thread , but the player must be in main thread. Any solutions ?

**Comment by debz-eight** [comment]
I faced this issue too. I told my backend developers and had them made the api such that it returns me 50 elements at a time. I implemented pagination along with this. From inside the player if anyone reaches the 50th episode and clicks next, I am calling the API again to get the next 50 songs and updating my song list along with adding them as media items.

**Comment by marcbaechinger** [comment]
Pagination as explained above helps. Thanks @debz-eight for your suggestion and how you solved that problem. 

> I want to put it in background thread , but the player must be in main thread. 

The player doesn't need to be on the main thread. You need to call the player on the same `Looper` on which you created it or you need to set the `Looper` manually when building the player. You can use [`ExoPlayer.Builder.setLooper(Looper)`](https://developer.android.com/reference/androidx/media3/exoplayer/ExoPlayer.Builder#setLooper(android.os.Looper)) to set the `Looper`. 

> Any solutions ?

There are two now. I'm closing this issue. Please re-open if you think this is required.

**Comment by tonihei** [comment]
To add to the possible solutions: if you have many items, please use the bulk operations `addMediaItems` instead of adding single items.

This version takes about 7-9 seconds on my phone:

```
for (int i = 0; i < 3000; i++) {
  player.addMediaItem(mediaItem);
}
```

whereas this takes less than 200 milliseconds:

```
ImmutableList.Builder<MediaItem> items = ImmutableList.builderWithExpectedSize(3000);
for (int i = 0; i < 3000; i++) {
  items.add(mediaItem);
}
player.addMediaItems(items.build());
```
