### ISSUE TITLE
"onSurfaceTextureSizeChanged" will not called with new size when use Video Effects.

### ISSUE THREAD

**Issue by kolyneh** [androidx/media#1546]
### Version

Media3 main branch

### Devices that reproduce the issue

Any device.

### Reproducible in the demo app?

Yes

### Reproduction steps

Just set effects.

### Expected result

"onSurfaceTextureSizeChanged" will be called with new surface.

### Actual result

"onSurfaceTextureSizeChanged" will only called once with the initial size.

### Media

https://storage.googleapis.com/exoplayer-test-media-1/60fps/bbb-clear-1080/manifest.mpd

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by claincly** [comment]
This is intentional - see https://github.com/androidx/media/blob/b01c6ffcb3fca3d038476dab5d3bc9c9f2010781/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/video/MediaCodecVideoRenderer.java#L670

Do you need the specific surface view size?
