### ISSUE TITLE
Creating a perpetually loading MediaItem

### ISSUE THREAD

**Issue by OxygenCobalt** [androidx/media#1555]
I'm trying to work on getting my player's state to reflect a long-running loading task from #1246. One of the options @tonihei recommended was setting the player to an infinitely loading MediaItem, and since overriding the player state itself didn't seem viable due to my inability to update listeners to my new arbitrary state, I decided to go for that.

The issue is that while I can create the `MediaItem` and identify it within my own `MediaSource.Factory`, implementing the `MediaSource` is extremely confusing. It's a low-level API using media buffering/decoding terminology I'm not very familiar with.

I tried to build this:

```kt
class InfiniteMediaSource(private val mediaItem: MediaItem) : MediaSource {
    override fun getMediaItem() = mediaItem

    override fun createPeriod(
        id: MediaSource.MediaPeriodId,
        allocator: Allocator,
        startPositionUs: Long
    ) = IndexingMediaPeriod()

    override fun prepareSource(
        caller: MediaSource.MediaSourceCaller,
        mediaTransferListener: TransferListener?,
        playerId: PlayerId
    ) {}

    override fun maybeThrowSourceInfoRefreshError() {}

    override fun enable(caller: MediaSource.MediaSourceCaller) {}

    override fun disable(caller: MediaSource.MediaSourceCaller) {}

    override fun addDrmEventListener(handler: Handler, eventListener: DrmSessionEventListener) {}

    override fun removeDrmEventListener(eventListener: DrmSessionEventListener) {}

    override fun addEventListener(handler: Handler, eventListener: MediaSourceEventListener) {}

    override fun removeEventListener(eventListener: MediaSourceEventListener) {}

    override fun releaseSource(caller: MediaSource.MediaSourceCaller) {}

    override fun releasePeriod(mediaPeriod: MediaPeriod) {}
}

class IndexingMediaPeriod : MediaPeriod {
    override fun prepare(callback: MediaPeriod.Callback, positionUs: Long) {}

    override fun selectTracks(
        selections: Array<out ExoTrackSelection?>,
        mayRetainStreamFlags: BooleanArray,
        streams: Array<out SampleStream?>,
        streamResetFlags: BooleanArray,
        positionUs: Long
    ) = 0L

    override fun getBufferedPositionUs() = 0L

    override fun getNextLoadPositionUs() = 0L

    override fun getTrackGroups(): TrackGroupArray = TrackGroupArray()

    override fun seekToUs(positionUs: Long) = 0L

    override fun getAdjustedSeekPositionUs(positionUs: Long, seekParameters: SeekParameters) = 0L

    override fun isLoading() = true

    override fun continueLoading(loadingInfo: LoadingInfo) = false

    override fun readDiscontinuity() = 0L

    override fun reevaluateBuffer(positionUs: Long) {}

    override fun discardBuffer(positionUs: Long, toKeyframe: Boolean) {}

    override fun maybeThrowPrepareError() {}
}
```

But I can't tell if this is right. It seems to just cause the player to hang in a weird way.

Can I get any help with this, or at least the closest library `MediaSource` to what I need that I could modify easily? Thanks.

**Comment by marcbaechinger** [comment]
I understand you are referring to the suggestion to create a player with a media source that never completes preparation in #1246.

I think the idea above can be implemented by a media source that never calls `MediaSourceCaller.onSourceInfoRefreshed(MediaSource source, Timeline timeline)`. The player then waits until this happens while consulting `MediaSource.maybeThrowSourceInfoRefreshError()` whether the wait is cause by an exception. If `maybeThrowSourceInfoRefreshError` never throws this results in the constant `BUFFERING` state until either preparation completes or the playing period changed through a seek or setting another media item.

Looking at `WrappingMediaSource` I think this would do that when [`WrappingMediaaSource.prepareChildSource`](https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/source/WrappingMediaSource.java#L239-L241) (or 'prepareSourceInternal') would just do nothing. This looks like a good starting ground to me which is based on a subclass that is easy to understand but solid in the sense that it is known to work.

**Comment by OxygenCobalt** [comment]
To be honest, I'm still having a hard time understanding even `WrappingMediaSource` @marcbaechinger.

I really don't know what kind of placeholder values/behaviors I can specify in methods like createPeriod/releasePeriod/getInitialTimeline that will placate ExoPlayer. Any help?

**Comment by icbaker** [comment]
I wonder if you could avoid needing to answer fiddly questions about `MediaPeriod` implementation by wrapping a [`SilenceMediaSource`](https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/source/SilenceMediaSource.java) inside the `WrappingMediaSource`, and then overriding `WrappingMediaSource.prepareSourceInternal` as suggested above, to just do nothing (instead of the default behaviour, which would forward the call to the `SilenceMediaSource`) - this should introduce a sufficient "break" in control flow to ensure that preparation never completes, but avoids needing to implement lots of `MediaSource` and `MediaPeriod` methods directly.

**Comment by OxygenCobalt** [comment]
Looks like @icbaker's suggestion worked well enough for my purposes.

I still need to handle other reloading tasks that occur during playback (and would be heavily interrupted by the way android likes to automatically boot my app from foreground), but still.
