### ISSUE TITLE
HttpMediaDrmCallback setKeyRequestProperty PSSH name for header request

### ISSUE THREAD

**Issue by RobertConstantinDinescu02** [androidx/media#1556]
Hi everyone! I was looking for information on this topic but I cant find any response. 
My question is under which name I should include the PSSH key in the header when I am calling setKeyRequestProperty from HttpMediaDrmCallback?
Thanks in advance and congrats for your work :)

**Comment by icbaker** [comment]
`setKeyRequestProperty` is used to append additional information to the headers that are sent to the DRM license server alongside a license request. The body of the license request comes from [`MediaDrm.getKeyRequest()`](https://developer.android.com/reference/android/media/MediaDrm#getKeyRequest(byte[],%20byte[],%20java.lang.String,%20int,%20java.util.HashMap%3Cjava.lang.String,java.lang.String%3E)).

The additional headers are generally consumed by the DRM license server implementation, so this is a question you should ask of your DRM license server operator, not of this library.
