### ISSUE TITLE
When playing a MediaItem on Android Auto the queue only contains the currently selected MediaItem

### ISSUE THREAD

**Issue by vanniktech** [androidx/media#156]
### Media3 Version

1.0.0-beta02

### Devices that reproduce the issue

Android Auto with Pixel 6 Pro

### Devices that do not reproduce the issue

-

### Reproducible in the demo app?

Not tested

### Reproduction steps

In my `onGetLibraryRoot`, I have the following code:

```kotlin
internal val rootMediaItem: MediaItem by lazy {
  MediaItem.Builder()
    .setMediaId(PARENT_ID)
    .setMediaMetadata(
      MediaMetadata.Builder()
        .setFolderType(MediaMetadata.FOLDER_TYPE_MIXED)
        .setIsPlayable(false)
        .build()
    )
    .build()
}
  
  
override fun onGetLibraryRoot(
  session: MediaLibrarySession,
  browser: MediaSession.ControllerInfo,
  params: LibraryParams?,
): ListenableFuture<LibraryResult<MediaItem>> {
  val rootExtras = Bundle().apply {
    putBoolean(
      MediaConstants.BROWSER_SERVICE_EXTRAS_KEY_SEARCH_SUPPORTED,
      true,
    )
    putBoolean("android.media.browse.CONTENT_STYLE_SUPPORTED", true)
    putInt(
      MediaConstants.DESCRIPTION_EXTRAS_KEY_CONTENT_STYLE_BROWSABLE,
      MediaConstants.DESCRIPTION_EXTRAS_VALUE_CONTENT_STYLE_GRID_ITEM,
    )
    putInt(
      MediaConstants.DESCRIPTION_EXTRAS_KEY_CONTENT_STYLE_PLAYABLE,
      MediaConstants.DESCRIPTION_EXTRAS_VALUE_CONTENT_STYLE_LIST_ITEM,
    )
  }
  val libraryParams = LibraryParams.Builder().setExtras(rootExtras).build()
  return Futures.immediateFuture(LibraryResult.ofItem(rootMediaItem, libraryParams))
}
```

in `onGetChildren`, I load all of my items and they are being displayed just fine:

<img width="800" alt="Screen Shot 2022-08-17 at 23 27 20" src="https://user-images.githubusercontent.com/5759366/185246388-62b8ca89-8bcc-441b-bac5-269935a90d50.png">

### Expected result

When selecting one, I'd expect to use the List of `MediaItem` so that I can automatically skip ahead

### Actual result

My queue contains only the selected item:

<img width="800" alt="Screen Shot 2022-08-17 at 23 28 20" src="https://user-images.githubusercontent.com/5759366/185246576-90ca5839-0b99-44a0-b81f-ca740540f520.png">

### Media

-

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by vanniktech** [comment]
Thanks for answering Marc! Indeed, this does work. I've used your workaround to shuffle the list. Not perfect but far better than having no queue at all.

**Comment by vanniktech** [comment]
@marcbaechinger I also find that in the `onAddMediaItems` method, `mediaItems.first().mediaMetadata.extras` is always null. Even though I am setting extras in `onGetChildren`. Is this related or should I file a separate issue?

**Comment by marcbaechinger** [comment]
I don't think there is something the Media3 library can do to avoid that as long as Android Auto is using Media1. When AA is browsing your catalogue they are receiving a [`MediaBrowserCompat.MediaItem`](https://developer.android.com/reference/kotlin/android/support/v4/media/MediaBrowserCompat.MediaItem) from which they take the `mediaId` to call [`Callback.prepareByMediaId(String  mediaId)`](https://developer.android.com/reference/android/support/v4/media/session/MediaSessionCompat.Callback?authuser=1#onPlayFromMediaId(java.lang.String,%20android.os.Bundle)). 

Media3 then receives this call and creates a `androidx.media3.MediaItem` with it that only contains the `mediaId`. This is all the information available. You need to resolve the `mediaId` to a full `androidx.media3.MediaItem` in `onAddMediaItems`.

**Comment by PaulWoitaschek** [comment]
Now with `MediaItemsWithStartPosition` which you can return in `MediaLibraryService.MediaLibrarySession.Callback#onSetMediaItems` this is kind of solved, correct?

I wonder what's the best way to prepare additional things with media3. For example I also need to set the playback speed which I persisted, depending on the media items.
And for which I need to query the database which is an async operation.

The only workaround I can imagine right now is to create a delegating player and overwrite all 6 setMediaItem permutations:

<img width="739" alt="image" src="https://github.com/androidx/media/assets/743462/559f78ea-d7eb-4a83-8a0f-e9a661e744d3">

Then somehow fetch from the MediaItems where they belong to and then do an runBlocking here to also set the playback speed. But that feels very hacky.

**Comment by marcbaechinger** [comment]
I think you can just defer completing the `Future` that you return from `onSetMediaItems`. It's fine to set the speed before the items are set into the player.

For instance:

1. Create a `SettableFuture<MediaItemsWithStartPosition>`  (and return it)
2. Load the data for `MediaItemsWithStartPosition`.
3. Load the data for speed, shuffleMode and set it to the player.
4. Set the loaded `MediaItemsWithPosition` to the settable future. This will prepare the player and then start with the speed you set.

I haven't tried but I think that should work.

**Comment by marcbaechinger** [comment]
Closing as the initial issue is fixed.
