### ISSUE TITLE
DRM Video Playback: Black Screen with Audio Playing

### ISSUE THREAD

**Issue by PruthiviRaj27** [androidx/media#1561]
### Version

Media3 main branch

### Devices that reproduce the issue

- TECNO Camon 20 Running Android 14

### Devices that do not reproduce the issue

- Samsung M40 Running Android 11
- Samsung Tab A7 Lite Running Android 14
- Motorola Edge 40 Neo Running Android 14

### Reproducible in the demo app?

Yes

### Reproduction steps

When attempting to play DRM-protected videos using ExoPlayer, the video screen remains black while the audio plays correctly. This issue occurs consistently across multiple DRM-protected video streams.

1. Play the attached media in the demo app

### Expected result

Both video and audio should play seamlessly without any black screen.

### Actual result

- The audio plays without any issues.
- The video screen remains black throughout the playback.

### Media

I have already sent the media details and bug report to android-media-github@google.com.

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by Soft-Buddy** [comment]
What is the licenseType of your stream?
* Clearkey
* Widevine
* Playready

**Comment by PruthiviRaj27** [comment]
We are using Widevine

**Comment by microkatz** [comment]
Hello @PruthiviRaj27,

I checked out the log report you sent to [android-media-github@google.com](mailto:android-media-github@google.com). It does not appear to have any logcat trace logs in the file. Would you be able to collect another trace for us? If you could please reproduce the issue using the ExoPlayer demo app and record another [bug report](https://developer.android.com/studio/debug/bug-report) then that would be great. Thanks!

**Comment by icbaker** [comment]
If you add an `EventLogger`, do you see any information about the video tracks in logcat? e.g. they may be shown as `supported=NO_UNSUPPORTED_DRM`
