### ISSUE TITLE
How can I play 360 stereoscopic vr video in ExoPlayer 

### ISSUE THREAD

**Issue by Sojourner64564** [androidx/media#1564]
I need to make app that will use ExoPlayer and play stereoscopic 360 video like here[here](https://i.sstatic.net/MBX2amPp.jpg) .
I already did android [app](https://github.com/Sojourner64564/android_java_360_player.git) with sphericalGLSurfaceView.setDefaultStereoMode(C.STEREO_MODE_LEFT_RIGHT); like it says in [this](https://stackoverflow.com/questions/73132412/playing-360-degree-split-screen-videos-with-exoplayer?noredirect=1&lq=1) StackOverflow answer but it didn't work. 
So how do I can do this?

**Comment by microkatz** [comment]
Hi @Sojourner64564 

Here is a blog post depicting how to setup the ExoPlayer demo app to play with spherical videos. https://medium.com/google-exoplayer/playing-360-degree-videos-with-exoplayer-f3b48f8ea390 Hope that provides additional support! Let us know if you have any more questions.

**Comment by Sojourner64564** [comment]
Hi, @microkatz
Thanks for answer. But [this](https://gist.githubusercontent.com/erdemguven/0b51847c21deafd525ce5e7b7c3242a2/raw/87349188e9996f1ceade5dcb06ef81115b7c7b77/setDefaultStereoMode.java) doesn't work because that class (SphericalSurfaceView) doesn't exist. Maybe article outdated, I used class SphericalGLSurfaceView in my [project](https://github.com/Sojourner64564/android_java_360_player.git) and it works just fine with same result like a in your article.  
But I need stereoscopic view this is my main goal. So can I add double views for left and right eyes?

**Comment by microkatz** [comment]
Ah, apologies @Sojourner64564. The blog is outdated as ExoPlayer removed the sample code for 360 videos in this commit, https://github.com/google/ExoPlayer/commit/73df8e4a260934d9be55e64b0298f21613c7661f. 

It seems like though you got the 360 spherical playback working alright?

When I play a 360 video without any changes in the demo app then its plays in the normal surface view looking like two videos on "on top of each other"? I'm not entirely clear on your goal. If you can elaborate further or provide sample code, content, or graphics. If you are trying to split the stream into two views, you can use an Effect, https://medium.com/google-exoplayer/trim-transcode-concatenate-your-guide-to-media3-editing-libraries-668b4e4c2f97, to crop the stream to just one view. Use two Players with two Views to stream the content. You can synchronize the two players by setting one clock to be the other player's clock.

Hopefully that helps!

**Comment by microkatz** [comment]
As there has been no response I am assuming that the provided advice helped! I am going to close this issue. If you have additional questions then feel free to open or create a new issue. Thank you!
