### ISSUE TITLE
Content containing DTS UHD descriptor ID stuck buffering since 1.3.0

### ISSUE THREAD

**Issue by okycelt** [androidx/media#1583]
### Version

Media3 main branch

### More version details

- Able to reproduce since 27c021fd7bb827491568dca04b11a9a396d8aee9 (e.g. on  1.3.0, 1.4.0, b01c6ffcb3fca3d038476dab5d3bc9c9f2010781)
- Working on 1.2.0, 1.3.0-alpha01, until e41b23d2f4b576a64ce9c7e750858c46511d78af

### Devices that reproduce the issue

- Changhong GIU3A00 (Android 10)
- Changhong GIU6770 (Android 9)
- SEI Robotics Box R Lite 4K (Android 11)
- Google Pixel 3a (Android 12)

### Reproducible in the demo app?

Yes

### Reproduction steps

Play the file sent via email in Media3 demo app (either from local storage or via UDP)

What fixed the issue for us was returning `null` instead of `new PesReader(new DtsReader(esInfo.language, DtsReader.EXTSS_HEADER_SIZE_MAX))` for `TsExtractor.TS_STREAM_TYPE_DTS_UHD` in `DefaultTsPayloadReaderFactory.createPayloadReader`. However, this isn't feasible unless we depend on the modules locally. 

### Expected result

The media plays successfuly

### Actual result

The playback is stuck in a buffering state and ends with the following exception
```
androidx.media3.exoplayer.ExoPlaybackException: Unexpected runtime error
    at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:720)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:193)
    at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: java.lang.IllegalStateException: Playback stuck buffering and not loading
    at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1221)
    at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:561)
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:193) 
    at android.os.HandlerThread.run(HandlerThread.java:65) 
```

### Media

Sent via email

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by rohitjoins** [comment]
@okycelt,

The error mentioned occurs because, during stream parsing, we are unable to locate a sync frame, which prevents us from reading the sample data properly.

It appears that the file you sent via email is corrupted and cannot be parsed correctly. You can use ffprobe to examine the file. When I ran ffprobe, I received the following output:

```
[mpeg2video @ 0x56243979c6c0] Invalid frame dimensions 0x0.
    Last message repeated 30 times
[mpeg2video @ 0x5624397fcb80] ac-tex damaged at 42 2
[mpeg2video @ 0x5624397fcb80] Warning MVs not available
```

However, I encountered no such errors when testing other sample files we have for DTS UHD.
