### ISSUE TITLE
MediaItem with OverlayEffect (GIF) stops when including Crop and ScaleAndRotateTransformation effect

### ISSUE THREAD

**Issue by Kilyc2** [androidx/media#1585]
I'm having a little problem making a composition with MediaItems that have a common OverlayEffect that plays a GIF continuously over the images as they change during playback. It works correctly.

The problem is that some of the MediaItems in that composition also have the Crop and ScaleAndRotateTransformation effects and when, once the composition is generated, it reaches that MediaItem, the GIF stops.

I'm doing this by adding effects on each MediaItem with the order ScaleAndRotateTransformation, Crop, Presentation and OverlayEffect, so that each one has the effect it needs (all with Presentation and OverlayEffect and some with Crop and ScaleAndRotate). Am I doing something wrong by adding these effects that make the OverlayEffect (the GIF) stop?

Thank you very much!

**Comment by droid-girl** [comment]
Hi @Kilyc2,
How to add a GIF to an overlay? The APIs does not support GIF out of the box, did you make an extension to be able to process GIFs?
Does it work on only one MediaItem and no effects?

**Comment by Kilyc2** [comment]
Sorry, let me explain better, to show a GIF I create a BitmapOverlay and in the getBitmap method I get the next frame to show from the GIF by calculating the presentation time. I include that BitmapOverlay as an OverlayEffect.

This OverlayEffect is added to all the MediaItems that make up the composition, and there is no problem, a video is created with several "clips" that show the GIF (frame by frame) on top.

The problem is that when I include the other effects in any of the MediaItems, that common BitmapOverlay executes the release event and I can no longer continue showing new frames of that GIF and it stops. If I don't add the Crop or Translate effects, the BitmapOverlay continues painting bitmaps until the end without any problem.

The question is, what makes the BitmapOverlay execute a release in relation to adding those effects?

**Comment by droid-girl** [comment]
We will need to test this use case to see where the problem is. Do you see any GL errors in your logs? If yes, could you please share.

**Comment by Kilyc2** [comment]
No, the whole generation is going well, without showing any errors in the logs

**Comment by droid-girl** [comment]
I have tested a similar setup where I use BitmapOverlay and all other effects you have applied. It works as expected for me. 
To support your use case, did you create your own custom effect by extending BaseGlShaderProgram? 
How many `MediaItem`s do you have in a composition? 
For info, you can apply Presentation effect onto Composition by using `setEffects`. This is the only effect that is supported to apply to `Composition`
