### ISSUE TITLE
Inconsistency between DefaultMediaDescriptionAdapter and DefaultMediaNotificationProvider

### ISSUE THREAD

**Issue by yschimke** [androidx/media#160]
### Use case description

DefaultMediaDescriptionAdapter uses displayTitle then title.

https://github.com/androidx/media/blob/850bd69dddca45915199f221d48573fca3fc790b/libraries/ui/src/main/java/androidx/media3/ui/DefaultMediaDescriptionAdapter.java#L50

DefaultMediaNotificationProvider uses title only.

https://github.com/androidx/media/blob/3de3f4175746aedd6b2ea869e90025683cca5d9a/libraries/session/src/main/java/androidx/media3/session/DefaultMediaNotificationProvider.java#L159

It isn't clear if one is right and one is wrong.

### Proposed solution

1) A Data Dictionary for MediaMetadata.
2) Make these points customisable.

### Alternatives considered
A clear and concise description of any alternative solutions you considered,
if applicable.

**Comment by marcbaechinger** [comment]
This has been made customizable in `DefaultMediaNotificationProvider`. Will be available in the public repo as soon as we sync the code to GitHub.

> It isn't clear if one is right and one is wrong.

Yes, this is totally arbitrary.
