### ISSUE TITLE
Casting packaged AAC HLS

### ISSUE THREAD

**Issue by declan-bauer** [androidx/media#1601]
I'm trying to add cast functionality to my app however it does not seem to like the HLS I am giving it.

I can play the HLS examples from the demo-cast but cannot play HLS examples like this https://streams.radiomast.io/ref-128k-aaclc-stereo/hls.m3u8 from https://www.radiomast.io/reference-streams.

I have been able to cast the same stream from VLC, so I'm guessing my device(Home Mini Gen 1) supports it unless they are doing something really custom.

I really just want to know if I'm missing something obvious here.

---

Adding the below to demo-cast's `DemoUtil` will enable it to play locally but when trying to cast it seems to get stuck in a buffering state.
``` java
samples.add(
    new MediaItem.Builder()
        .setUri("https://streams.radiomast.io/ref-128k-aaclc-stereo/hls.m3u8")
        .setMediaMetadata(new MediaMetadata.Builder()
            .setTitle("AACLC HLS audio stream")
            .build())
        .setMimeType(MIME_TYPE_HLS)
        .build()
);
```
Adding an `onEvents` override to `PlayerManager` I can see player updates but never makes it passed `STATE_BUFFERING` on the above `MediaItem`

```java
@Override
public void onEvents(Player player, Player.Events events) {
  Log.i("PlayerManager", player.toString());
  Log.i("PlayerManager", "State: " + player.getPlaybackState());

  if(events.size() > 0) {
    Log.i("PlayerManager", "Events:");
    for (int i = 0; i < events.size(); i++) {
      Log.i("PlayerManager", String.valueOf(events.get(i)));
    }
  }
  Player.Listener.super.onEvents(player, events);
}
```
ExoPlayer has an `addAnalyticsListener`, is there anything similar for CastPlayer?

**Comment by declan-bauer** [comment]
Update for anyone else who might run into this. Turns out for my needs it has to be a different content type when casting.

`MIME_TYPE_HLS` works when running locally, `MIME_TYPE_DASH` does not work locally, however it does work when casting.

Setting a `MediaItemConverter` when creating the `CastPlayer` and overriding the `contentType` in `toMediaQueueItem` seems to work, though I do need to look into some playback issues.

``` kotlin
val contentType = if(mediaItem.localConfiguration?.mimeType == MimeTypes.APPLICATION_M3U8 ) {
    MimeTypes.APPLICATION_MPD
} else {
    mediaItem.localConfiguration?.mimeType
}
val mediaInfo = MediaInfo.Builder(mediaItem.mediaId)
    .setStreamType(MediaInfo.STREAM_TYPE_LIVE)
    .setContentType(contentType)
    .setContentUrl(mediaItem.localConfiguration?.uri.toString())
    .setMetadata(metadata)
    .build()
return MediaQueueItem.Builder(mediaInfo).build()
```

**Comment by marcbaechinger** [comment]
I think this is an issue with these devices and the default receiver app this kind of stream is not supported.

I have changed `DefaultMediaItemConverter` to set the stream type to live

```
new MediaInfo.Builder(contentId)
   .setStreamType(MediaInfo.STREAM_TYPE_LIVE)
```

and tried on Google TV, Nest Audio and Nest Hub but none of them are able to play this stream with the default receiver app that `CastPlayer` is using.

> I have been able to cast the same stream from VLC, so I'm guessing my
> device(Home Mini Gen 1) supports it unless they are doing something really custom.

My guess is that VLC is having a different receiver app that is running on your device. 

I'm closing this issue as I don't see how we could provide some help here. I'd try using a different receiver app that is using another player on the Cast device.
