### ISSUE TITLE
Media3 Notification question

### ISSUE THREAD

**Issue by yi1234** [androidx/media#1605]
How does the media3 Notification bar display the music playing time you set? For example, 5 minutes or 10 minutes?
The progress corresponds to the progress of setting the total playback duration.

**Comment by tianyif** [comment]
Hi @yi1234,

Are you asking the progress bar on the media notification? Also could you please provide the `appTargetSdkVersion` of your app? Thanks!

**Comment by yi1234** [comment]
targetSdkVersion 34

**Comment by yi1234** [comment]
targetSdk版本 34

**Comment by tianyif** [comment]
Hi @yi1234,

Thanks for getting back with the information! We can custom the action button on the notification, however, the progress bar is pretty standardized by the system UI and we're not able to add a numerical display unfortunately.
