### ISSUE TITLE
 Identify MediaItem in TrackSelector's selectTracks Method

### ISSUE THREAD

**Issue by Amud** [androidx/media#1608]
When using a single ExoPlayer instance to play a playlist of media items, custom track selection can be performed by overriding the selectTracks method in the TrackSelector. However, there is a challenge in identifying which MediaItem the selectTracks method is being called for, especially since selectTracks can be invoked before onMediaItemTransition, where the currently playing MediaItem can be identified.

Currently, the selectTracks method provides a MediaPeriodId, but this does not directly expose the MediaItem or its associated mediaId, making it difficult to perform custom track selection based on the specific MediaItem.

Is there any direct way to achieve this identification within the selectTracks method?

**Comment by microkatz** [comment]
Hello @Amud,

You can retrieve the media item from the `Timeline` given the `MediaPeriodId`. See the following code snippet.

```
int windowIndex =
    timeline.getPeriodByUid(mediaPeriodId.periodUid, new Timeline.Period()).windowIndex;
timeline.getWindow(windowIndex, new Timeline.Window()).mediaItem;
```

Hope that helps!

**Comment by microkatz** [comment]
As there has been no response I will take it that the suggestion on how to retrieve the media item from the timeline was helpful. I will close this issue. Please re-open or file a new one if you have any additional questions!

**Comment by Amud** [comment]
It took me some time to test, but the suggested solution worked fine :).
The only minor downside was that I had to copy the DefaultTrackSelector class and make the selectTracks function (with mediaPeriodId: MediaSource.MediaPeriodId and timeline: Timeline as arguments) non-final.

Thanks for the support :)
