### ISSUE TITLE
Clarification about the dependency injection from datasource factories

### ISSUE THREAD

**Issue by jpgpuyo** [androidx/media#1610]
Hello,

I would like to request a clarification about the dependency injection from datasource factories.

For instance, to create a DashMediaSource, we need this:

```
DataSource.Factory dataSourceFactory = new DefaultDataSource.Factory(this);
MediaSource mediaSource = new DashMediaSource.Factory(dataSourceFactory)
.setDrmSessionManagerProvider(unusedMediaItem -> drmSessionManager)
.createMediaSource(MediaItem.fromUri(uri));
```

I have found some samples where DefaultDataSource.Factory(this) is injected with Dagger as a Singleton annotation or with Reusable annotiation, but at the same time, looking at the source code, this class  DefaultDataSource.Factory contains methods to open and close the connections.
In my opinion, using this as a Singleton can cause memory leaks or unexpected behaviour, but maybe I'm missing something.

In a production app, which is the recommended way to use this kind of factories?
Is it safe use DefaultDataSource.Factory(this) as a Singleton and reuse the same instance every time that a new player instance is created?
Or should we create one DefaultDataSource.Factory every time that a player instance is created?

Thanks

**Comment by icbaker** [comment]
> looking at the source code, this class DefaultDataSource.Factory contains methods to open and close the connections.

I don't think this is correct.

The [`DataSource`](https://developer.android.com/reference/androidx/media3/datasource/DataSource) interface has `open()` and `close()` methods. The [`DataSource.Factory`](https://developer.android.com/reference/androidx/media3/datasource/DataSource.Factory) interface only has `createDataSource()`. A singleton `DataSource.Factory` shared across players seems safe providing all the players use the same [application looper](https://developer.android.com/reference/kotlin/androidx/media3/common/Player#getApplicationLooper()), and assuming a new `DataSource` instance will be created each time `createDataSource()` is called (which is the case for all `DataSource.Factory` provided by the media3 library).

**Comment by jpgpuyo** [comment]
Thanks for the clarification!
