### ISSUE TITLE
How to control audio playback with widgets?

### ISSUE THREAD

**Issue by leejooheon** [androidx/media#1611]
How to control audio playback with a widget when the app is not running?
Playback resumes in onStartCommand, but ForegroundServiceDidNotStartInTimeException occurs.
If you have an example project, please let me know.

**Comment by icbaker** [comment]
I assume by 'widget' you're referring to home screen widgets as described in https://developer.android.com/develop/ui/views/appwidgets/overview.

**Comment by leejooheon** [comment]
I asked because there is no official guide for sending a playback command from a [widget](https://developer.android.com/develop/ui/views/appwidgets/overview?hl=ko).

In the traditional way, when [some_widget](https://gist.github.com/leejooheon/1029b265c4107008c2d2e5b98dbe86e4#file-barwidgetprovider-kt) receives a user action, the action is received and processed in onStartCommand of [service](https://gist.github.com/leejooheon/1029b265c4107008c2d2e5b98dbe86e4#file-playbackservice-kt).

In media3, is it correct to create [some_controller](https://gist.github.com/leejooheon/1029b265c4107008c2d2e5b98dbe86e4#file-widgetplayercontroller-kt) and send the appropriate command when an action is received from [some_widget](https://gist.github.com/leejooheon/1029b265c4107008c2d2e5b98dbe86e4#file-barwidgetprovider-kt)?
(In fact, I don't like using applicationContext instead of the context given in onReceive.)

I would really appreciate it if you could check whether the above code snippets are implemented according to the ExoPlayer developer's intention.

I would also appreciate it if you could update the code related to playback control in [widget](https://developer.android.com/develop/ui/views/appwidgets/overview?hl=ko) in the demo app so that many people can check it.

**Comment by marcbaechinger** [comment]
Yes, the way is to build a controller, then call something like

```
controller.setMediaItems(mediaItems);
controller.prepare();
controller.play();
```

Please let us know if this doesn't work. I added the `documentation candidated` label to mark this issue accordingly. I don't think we get around looking into building a widget ourself soon I'm afraid though.

**Comment by leejooheon** [comment]
@marcbaechinger 
it works fine.
Thanks for checking.
Have a nice day!

**Comment by marcbaechinger** [comment]
Great! I'm glad it's working. I'm closing this issue then!
