### ISSUE TITLE
How do I detect we're in a loading state while streaming HLS files?

### ISSUE THREAD

**Issue by alexsullivan-substack** [androidx/media#1622]
First off - I've been super impressed with how easy it's been to get HLS streaming up and running. Kudos to the team!

I'm trying to add a loading indicator before an HLS stream starts. I initially reached for the `onIsLoadingChanged` callback, but that seems to be called with a `true` value and then never change to `false`. Conceptually I guess that makes sense - you're _always_ loading. But that leaves me confused about how to accomplish my goal of showing a loading indicator. Should I just wait for the first frame callback and use that a as a signal that we're "done" doing the initial load?

**Comment by icbaker** [comment]
> Conceptually I guess that makes sense - you're _always_ loading

Yes, until your loading position either reaches the end of the stream or far enough ahead of your playback position that your `LoadControl` indicates to stop, at which point you stop loading.

> But that leaves me confused about how to accomplish my goal of showing a loading indicator

Our UI components have an optional buffering indicator, and you can see the implementation checks `player.state == BUFFERING`:
https://github.com/androidx/media/blob/b01c6ffcb3fca3d038476dab5d3bc9c9f2010781/libraries/ui/src/main/java/androidx/media3/ui/PlayerView.java#L1700-L1709

I think this matches what you want. Unlike "first frame", It will go 'true' again if the network is unable to load content fast enough during playback, resulting in playback pausing while more content is loaded.

**Comment by alexsullivan-substack** [comment]
Thanks for the response @icbaker! 

I initially reached for checking the buffering state but found that we were not buffering when the stream initially started. I actually never saw the BUFFERING state show up, but I've been testing on solid network. Would you expect us to reach a buffering state before the first frame is shown?

**Comment by icbaker** [comment]
Are you saying you see the state transition directly from `IDLE` to `READY`? That is a bit surprising. Is this confirmed if you [attach an `EventLogger`](https://developer.android.com/media/media3/exoplayer/debug-logging) and look for lines in logcat like this:

```
state [eventTime=0.01, mediaPos=0.00, window=0, BUFFERING]  
```

**Comment by alexsullivan-substack** [comment]
Hmm I do see a buffering event, I'm sorry I must've goofed up my debugging earlier. I'll give that a shot, thank you!
