### ISSUE TITLE
transformer support soft decoding/encoding

### ISSUE THREAD

**Issue by fanmingyi** [androidx/media#1633]
Based on the description, it seems that transformer doesn't support soft decoding. However, we have a business requirement for this. Are there any ready-made solutions available?

**Comment by fanmingyi** [comment]
![img_v3_02du_55d8b37a-6aea-436b-9d49-2df916fbcfhu](https://github.com/user-attachments/assets/f1b07bd5-9eed-4f96-9331-684bd7effdec)

**Comment by droid-girl** [comment]
`MediaCodec` supports both hardware and software encoders/decoders, thus Transformer also supports both options.
If you need to only use software encoders, you need to implement [`EncoderSelector`](https://github.com/androidx/media/blob/release/libraries/transformer/src/main/java/androidx/media3/transformer/EncoderSelector.java) and pass it to the `DefaultEncoderFactoryBuilder`.
For decoders, you need to implement [`MediaCodecSelector`](https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/mediacodec/MediaCodecSelector.java) and pass it to the `DefaultDecoderFactory.Builder`

**Comment by fanmingyi** [comment]
![image](https://github.com/user-attachments/assets/ca68f3d7-9666-4393-8c8e-81f0d0901cc7)
I use transformer for video format conversion, but on some mobile phones, the error shown in the image appears. If possible, could you please guide me on how to handle this compatibility issue? My initial thought was that switching to a software decoder/encoder should solve similar problems. @droid-girl

**Comment by droid-girl** [comment]
For decoder, you can try to use [`setEnableDecoderFallback()`](https://github.com/androidx/media/blob/b01c6ffcb3fca3d038476dab5d3bc9c9f2010781/libraries/transformer/src/main/java/androidx/media3/transformer/DefaultDecoderFactory.java#L106) method.
For encoder, a similar method [here](https://github.com/androidx/media/blob/b01c6ffcb3fca3d038476dab5d3bc9c9f2010781/libraries/transformer/src/main/java/androidx/media3/transformer/DefaultEncoderFactory.java#L125)
