### ISSUE TITLE
Support seamless replacement of `MediaItem`s with different URIs

### ISSUE THREAD

**Issue by realmazharhussain** [androidx/media#1634]
### Use case
In a service we are using, to prevent unwanted access to their content, they expire URLs of media after some amount of time, and provide us with a new URL. We need to seamlessly change the URL of a `MediaItem`, without interrupting playback.

### Proposed solution
Rather than URL of the media item, use `MediaItem.mediaId` (when available) to decide whether to do a seamless replacement or not. When `MediaItem.mediaId` is not provided, fallback to media item URI for the decision.

### Alternative solutions
Add a new optional parameter to `MediaController.replaceMediaItem()`

```kotlin
enum class ReplacementBehavior {
    Auto,  // does a seamless replacement if URIs match, otherwise an abrupt replacement.
    Seamless,
    Abrupt,
}

fun replaceMediaItem(item: MediaItem, replacementBehavior: ReplacementBehavior = ReplacementBehavior.Auto)
```

**Comment by tonihei** [comment]
Is your proposal about a specific behavior of the `MediaController` or playback with `ExoPlayer` in the app hosting the `MediaSession`? 

If it's about `MediaController` only, could you clarify in more detail what you are currently seeing and what you'd like to see exactly?

If it's about playback with `ExoPlayer`, the decision to handle new `MediaItem` instances seamlessly lies solely with the underlying `MediaSource` instance. You could for example write a `WrappingMediaSource` around your real `MediaSource` that overrides `canUpdateMediaItem`, `updateMediaItem` and `onChildSourceInfoRefreshed` to handle `MediaItem` updates seamlessly without touching the behavior of the actual playback.

**Comment by realmazharhussain** [comment]
> Is your proposal about a specific behavior of the MediaController or playback with ExoPlayer in the app hosting the MediaSession?

I am not very familiar with media3/ExopPlayer internals. I just want to be able to update media item URI without interruption, and without having to write so much glue code.

**Comment by tonihei** [comment]
> I am not very familiar with media3/ExopPlayer internals

No need to be familiar with internals. In order to help you effectively and provide some useful guidance I still need to know what you'd like to do exactly. In particular:
 - Do you call `replaceMediaItem` on an `ExoPlayer` instance or a `MediaController` instance? 
 - What is the expected and observed behavior? Is it how `MediaController` shows the change immediately after calling `replaceMediaItem`, or is it about how `ExoPlayer` treats the update?

**Comment by realmazharhussain** [comment]
> Do you call `replaceMediaItem` on an `ExoPlayer` instance or a `MediaController` instance?

I call `replaceMediaItem` on a `MediaController` instance, not `ExoPlayer`.

> What is the expected and observed behavior? Is it how MediaController shows the change immediately after calling replaceMediaItem, or is it about how ExoPlayer treats the update?

I guess, it is about how `ExoPlayer` treats the update. I want there to be no buffering caused by the change of the URI.

**Comment by tonihei** [comment]
> I guess, it is about how ExoPlayer treats the update. I want there to be no buffering caused by the change of the URI.

You should be able to do something like that, by wrapping the MediaSource created by ExoPlayer with one that accepts arbitrary `MediaItem` updates as long as the id is the same for example (this logic can be adjusted to your needs of course):

```
public static final class UrlChangingMediaSource extends WrappingMediaSource {

    private MediaItem mediaItem;

    public UrlChangingMediaSource(MediaSource mediaSource) {
      super(mediaSource);
      this.mediaItem = mediaSource.getMediaItem();
    }

    @Override
    public synchronized MediaItem getMediaItem() {
      return mediaItem;
    }

    @Override
    public synchronized boolean canUpdateMediaItem(MediaItem mediaItem) {
      return Objects.equals(this.mediaItem.mediaId, mediaItem.mediaId);
    }

    @Override
    public synchronized void updateMediaItem(MediaItem mediaItem) {
      this.mediaItem = mediaItem;
    }
  }
```

If you don't create `MediaSource` instances directly because everything is done via `MediaItem`, you should be able to set `ExoPlayer.Builder.setMediaSourceFactory` creating such instances like so:

```
MediaSource.Factory wrappedFactory =
          new MediaSource.Factory() {

            DefaultMediaSourceFactory defaultFactory = new DefaultMediaSourceFactory(context);
        
             // Override other methods with default / returning this. 

            @Override
            public MediaSource createMediaSource(MediaItem mediaItem) {
              return new UrlChangingMediaSource(defaultFactory.createMediaSource(mediaItem));
            }
          };

ExoPlayer player =
     new ExoPlayer.Builder(context) .setMediaSourceFactory(wrappedFactory).build();
```

**Comment by tonihei** [comment]
I assume this answers the question, please let me know if there is anything missing in the library that would help your use case.
