### ISSUE TITLE
Caption positioning for 608/708 standard

### ISSUE THREAD

**Issue by nishantkp** [androidx/media#1637]
Hello,

How can I adjust the caption position from the player view for a broadcast stream (embedded 608/708)?

So captions are fixated on line 10 or 11. I wasn't able to find anything for adjusting vertical positioning.

Is `bottomPaddingFraction` a good way to do it?

**Streaming protocol**: HLS

**Comment by icbaker** [comment]
Closing because I think the question has been answered.
