### ISSUE TITLE
Cannot apply a customLayout per controller

### ISSUE THREAD

**Issue by mickael-qobuz** [androidx/media#165]
### Media3 Version

1.0.0-beta02

### Devices that reproduce the issue

All

### Devices that do not reproduce the issue

None

### Reproducible in the demo app?

Yes

### Context:
I would like to display different custom actions depending on the controller (notification, Android Auto...).
For basic example notification would have shuffle action, Android Auto would have repeat action.

`session.setCustomLayout(controller, customLayout)` 
- is working as expected on the media notification: set the shuffle button
- has no effect when the controller is Android Auto controller (packageName=com.google.android.projection.gearhead): no repeat action set

So in order to apply changes to Android Auto custom actions, I need to call `session.setCustomLayout(customLayout)` without passing the controller, which cause the update of all the controllers (media notification is updated with repeat button but since repeat action is not allowed for the related controller, none of shuffle or repeat icon is displayed).

Also calling `session.setCustomLayout(controller, customLayout)` into `onPostConnect()` has no effect when controller is related to Android Auto.

### Expected result

I am able to provide contextual custom actions depending on the controller (notification, Android Auto, ...).

### Actual result

Unable to have contextual custom actions depending on the controller (notification, Android Auto, ...).

### Media

He is the updated session demo project to be able to reproduce the bug:
[media3.zip](https://github.com/androidx/media/files/9565062/media3.zip)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment]
Controllers that are using the legacy `MediaControllerCompat` are reading the custom actions from the platform media session. You can see the state of the platform session `adb shell dumpsys media_session` which shows the actions in the platform session that all legacy controllers see. For instance, System UI and Android Auto are both using the legacy controller API, so you can only provide the same set of custom commands for these.

You can declare different custom commands for Media3 controllers. These have a `controller.controllerVersion` that is `> 0`. All controllers that have a `controller.controllerVersion=0` are legacy controllers that read from the platform session.

**Comment by mickael-qobuz** [comment]
Alright, thank you Marc for your explanations.
