### ISSUE TITLE
In ExoPlayer, my input stream is pixelated, causing the player to display those pixelations. Instead of showing pixelated frames, I want the player to either freeze on the last frame or display a black screen when pixelation occurs

### ISSUE THREAD

**Issue by amit12kumardish** [androidx/media#1661]
In ExoPlayer, my input stream is pixelated, causing the player to display those pixelations. Instead of showing pixelated frames, I want the player to either freeze on the last frame or display a black screen when pixelation occurs

**Comment by tonihei** [comment]
This is a duplicate of #1660
