### ISSUE TITLE
MergingMediaSource Causes Prolonged Buffering (30+ Seconds)

### ISSUE THREAD

**Issue by joh9911** [androidx/media#1670]
This is my code.

```
override fun onAddMediaItems(
        mediaSession: MediaSession,
        controller: MediaSession.ControllerInfo,
        mediaItems: MutableList<MediaItem>
    ): ListenableFuture<MutableList<MediaItem>> {
        val dataSourceFactory = DefaultHttpDataSource.Factory()
            .setConnectTimeoutMs(DEFAULT_CONNECT_TIMEOUT_MILLIS)
            .setReadTimeoutMs(DEFAULT_READ_TIMEOUT_MILLIS)
            .setAllowCrossProtocolRedirects(true)

        val mediaSources = mediaItems.map {
            val videoUri = it.mediaMetadata.extras?.getString("videoUrl")
            val audioUri = it.mediaMetadata.extras?.getString("audioUrl")
            if (videoUri != null && audioUri != null) {
                val videoSource = createOptimizedSource(videoUri, dataSourceFactory)
                val audioSource = createOptimizedSource(audioUri, dataSourceFactory)
                MergingMediaSource(true, videoSource, audioSource)
            } else {
                ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(it)
            }
        }

        (mediaSession.player as? ExoPlayer)?.setMediaSources(mediaSources)
        return super.onAddMediaItems(mediaSession, controller, mediaItems)
    }

    private fun createOptimizedSource(uri: String, dataSourceFactory: DataSource.Factory): MediaSource {
        return when {
            uri.contains(".mpd") -> DashMediaSource.Factory(dataSourceFactory)
                .createMediaSource(MediaItem.fromUri(uri))
            uri.contains(".m3u8") -> HlsMediaSource.Factory(dataSourceFactory)
                .createMediaSource(MediaItem.fromUri(uri))
            else -> ProgressiveMediaSource.Factory(dataSourceFactory)
                .createMediaSource(MediaItem.fromUri(uri))
        }
    }
```
    
Both URLs work well individually.

However, when I combine them using MergingMediaSource and apply it to ExoPlayer, it plays fine for the first 7 seconds, but then it buffers for about 30 seconds.

Is there any solution for this? I’m sorry for not knowing much about this.

```
@OptIn(UnstableApi::class)
    @Provides
    @Singleton
    fun provideExoPlayer(
        @ApplicationContext context: Context,
        audioAttributes: AudioAttributes,
        customMediaSourceFactory: CustomMediaSourceFactory
    ): ExoPlayer = ExoPlayer.Builder(context)
        .setAudioAttributes(audioAttributes, true)
        .setHandleAudioBecomingNoisy(true)
        .setLoadControl(DefaultLoadControl.Builder()
            .setBufferDurationsMs(
                DefaultLoadControl.DEFAULT_MIN_BUFFER_MS,
                DefaultLoadControl.DEFAULT_MAX_BUFFER_MS,
                DefaultLoadControl.DEFAULT_BUFFER_FOR_PLAYBACK_MS,
                DefaultLoadControl.DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS
            )
            .setTargetBufferBytes(C.LENGTH_UNSET)
            .setPrioritizeTimeOverSizeThresholds(true)
            .build())
        .setTrackSelector(DefaultTrackSelector(context))
        .build()
```

These are two urls.

VideoOnlyUrl: https://rr5---sn-3u-bh2z7.googlevideo.com/videoplayback?expire=1724896547&ei=w4DPZo7yM-Oh88EPltS72AI&ip=220.87.44.4&id=o-AIoz2KWMcjybokbzqAWQVWs2r86HY7MrVenrf_8vNvNY&itag=298&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=wU&mm=31%2C26&mn=sn-3u-bh2z7%2Csn-oguelnsy&ms=au%2Conr&mv=m&mvi=5&pl=24&initcwndbps=7701250&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=973590922&dur=2559.316&lmt=1717727874192885&mt=1724874551&fvip=1&keepalive=yes&c=IOS&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhANLuoDZsjOyHfpodXYxRRRiHdTFZlvewtfWaMLLhYsAyAiEAnO7l1-AN6Xw9BXUSIqu9nZHAkYt3imZSjqdLGYP0Tok%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRQIgIHG8CSFWMvs_mUQyVd3mcCcirnU8tKy8jqDM_wwNaA0CIQCPN6qzvR_hGndWbBsTFViOiwxjU_5_5tH-fDvaE008ww%3D%3D&cpn=GhROpA2hCxu-1KQE

AudioOnlyUrl: https://rr5---sn-3u-bh2z7.googlevideo.com/videoplayback?expire=1724896547&ei=w4DPZo7yM-Oh88EPltS72AI&ip=220.87.44.4&id=o-AIoz2KWMcjybokbzqAWQVWs2r86HY7MrVenrf_8vNvNY&itag=139&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=wU&mm=31%2C26&mn=sn-3u-bh2z7%2Csn-oguelnsy&ms=au%2Conr&mv=m&mvi=5&pl=24&initcwndbps=7701250&vprv=1&svpuc=1&mime=audio%2Fmp4&rqh=1&gir=yes&clen=15608199&dur=2559.442&lmt=1717713869892498&mt=1724874551&fvip=1&keepalive=yes&c=IOS&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgU-14x8zSX6gRz5Uv5SAH0cMHrZPT4B4nIX02zzn9TokCIE9IxhfJsF7OPklRJo_7AyPNxZDtPOqeKK_L2Mxrcdm4&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRQIgIHG8CSFWMvs_mUQyVd3mcCcirnU8tKy8jqDM_wwNaA0CIQCPN6qzvR_hGndWbBsTFViOiwxjU_5_5tH-fDvaE008ww%3D%3D&cpn=GhROpA2hCxu-1KQE

**Comment by tonihei** [comment]
I'm afraid I can't access these URLs for testing. Please share test media we can access, or alternatively send a link to android-media-github@google.com with "Issue #1670" in the subject and then report back here.
