### ISSUE TITLE
Add 16 kb page support to `decoder_flac` to support Android 15

### ISSUE THREAD

**Issue by maxoertel** [androidx/media#1685]
### Version

Media3 main branch

### More version details

Android 15 adds support for devices with [16 kb page size memory](https://developer.android.com/guide/practices/page-sizes#ndk-build_1). Any native parts of the app need to be rebuild, otherwise apps will crash at these new devices. Currently, the Flac extension of Exoplayer does not support this. Hence, validating the APK shows **UNALIGNED**:

<img width="420" alt="Screenshot 2024-09-02 at 11 37 50" src="https://github.com/user-attachments/assets/b282791b-fb3a-4505-b7cf-9842758f4469">

## TODO:
- [ ] Follow steps [here](https://developer.android.com/guide/practices/page-sizes#ndk-build_1) to add 16 kb page size support

### Devices that reproduce the issue

Any

### Devices that do not reproduce the issue

-

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Build and run the debug app.
2. Locate the debug APK and unzip it
3. Use the `alignment.sh` script provided in the official migration guide linked above and run this command:
 `sh alignment.sh my_apk_out | grep "arm64-v8a"`

(where `my_apk_out` is the unzipped apk)

### Expected result

`libflacJNI.so` (the Flac lib) should say `ALIGNED`

### Actual result

It says `UNALIGNED`

### Media

-

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by rohitjoins** [comment]
Hi @maxoertel,

Thank you for raising this issue. We will add support for 16KB page to all the extension modules and keep you updated.

**Comment by rohitjoins** [comment]
Hi @maxoertel,

Support for 16 KB page size has been [added](https://github.com/androidx/media/commit/2640ebd58ff2c35dc2ad384c9db6fbe68ab05587). Thank you once again for raising this issue.

**Comment by maxoertel** [comment]
Thx @rohitjoins for adding 16 KB page size support 💪🏼

**Comment by Tolriq** [comment]
@rohitjoins AFAIK 16k pages requires NDK 27 and all the docs still references NDK 21 as tested solution. Might worth a doc update?

**Comment by maxoertel** [comment]
@Tolriq I'm very confident that NDK 27 is **not** required for 16kb pare support. We updated our own libs already and still use NDK 21 and it works fine.

Google even has a dedicated section for below NDK 27: https://developer.android.com/guide/practices/page-sizes#compile-r26-lower

**Comment by Tolriq** [comment]
Yes but from that part:

```
In order to test on those lower versions of the NDK on 16 KB devices, canary releases of LTS NDK versions [r21](https://ci.android.com/builds/branches/aosp-ndk-release-r21/grid) (for Windows and Linux only), [r23](https://ci.android.com/builds/branches/aosp-ndk-release-r23/grid), and [r25](https://ci.android.com/builds/branches/aosp-ndk-r25-release/grid) are available on Android CI with 16 KB aligned libc++_shared.so libraries. Regardless, it is recommended to move to Android NDK r27 or higher to update to the 16 KB ELF aligned version of the C++ standard library. Otherwise, your app will fail to install on 16 KB devices today.
```

Says it requires canary versions of those NDK

**Comment by rohitjoins** [comment]
Hi @Tolriq,

We recently streamlined the build process for most decoder extensions by switching from `ndk-build` to `CMake`. Users no longer need to manually check out the `NDK` or rely on it directly. Once we upgrade to AGP versions that support NDK version 27, we might need to update the flags for 16 KB page sizes.

Eg: [Simplified Flac extension build process](https://github.com/androidx/media/commit/c78abaac3f2c4ff024cd69e93658881029189c0c)

**Comment by maxoertel** [comment]
@rohitjoins We tested the `1.5.0-beta01` release which mentions it includes the 16 kb page size support:

```
Decoder Extensions (FFmpeg, VP9, AV1, etc.):
Add 16 KB page support for decoder extensions on Android 15 ([https://github.com/androidx/media/issues/1685](https://github.com/a...
```

When running the `alignment.sh` script I'm still getting the `UNALIGNED` output. Could you please check on your side, if you can reproduce it (specifically for the Flac extension)?

![Screenshot 2024-11-08 at 09 53 49](https://github.com/user-attachments/assets/5082bc41-453d-451a-9f89-775896d35fb2)

**Comment by rohitjoins** [comment]
Hi @maxoertel,

Did you test it on a device with [16KB page size enabled](https://developer.android.com/guide/practices/page-sizes#developer-option)?

I have tested this on both an emulator and a device with 16KB page enabled and the script does show aligned to me.

<img width="486" alt="Screenshot 2024-11-08 at 11 42 37" src="https://github.com/user-attachments/assets/8bce5476-0def-43d8-b9f2-8929dd871890">

**Comment by maxoertel** [comment]
Hey @rohitjoins,

I didn't test it on a 16KB emulator yet, since the script showed `UNALIGNED` so I stopped there. Here are the exact steps I did and also tried again today:

1. Bump the following dependencies to `1.5.0-beta01`

```
androidx.media3:media3-exoplayer:1.5.0-beta01
androidx.media3:media3-exoplayer-hls:1.5.0-beta01
androidx.media3:media3-datasource-okhttp:1.5.0-beta01
```

2. Target Android 15 / SDK 35 (since the new version required that).
3. Build and run our app.
4. Take the generated debug APK file, unzip it
5. Use the unzipped folder of the APK as input for the `alignment.sh` script

The same steps worked for other SDKs, they showed after updating their versions in the last step `ALIGNED`. Only the `libflachJNI.so` shows still `UNALIGNED` for us:

![Screenshot 2024-11-11 at 09 08 54](https://github.com/user-attachments/assets/93a51f7c-ef94-415e-8553-c1fd4d4cd619)

Am I doing something wrong?

**Comment by rohitjoins** [comment]
Hey @maxoertel,

Thanks for the details! Testing specifically on a 16KB emulator isn’t necessary. What I meant was that testing should be done on either a physical or virtual device running Android 15 with 16KB page alignment enabled.

Could you check if 16KB page alignment was enabled on the device? This setting is essential for verifying alignment. 

We use the same alignment parameters in our [CMakeLists file](https://github.com/androidx/media/blob/release-1.5.0-beta01/libraries/decoder_flac/src/main/jni/CMakeLists.txt#L49-L51) for flacJNI as we do for other extensions:

```
# Enable 16 KB ELF alignment.
target_link_options(flacJNI
                    PRIVATE "-Wl,-z,max-page-size=16384")
```

**Comment by rohitjoins** [comment]
Nice to hear that. 

> just the script provided by Google doesn't print ALIGNED. Any idea why?

Not really, it shows aligned to me when I use the script as attached in https://github.com/androidx/media/issues/1685#issuecomment-2464520746.

Closing the issue as the extension works!
