### ISSUE TITLE
Exoplayer: Video Effects Not Applied When Using MediaItem with Image URI

### ISSUE THREAD

**Issue by avinash--reddy** [androidx/media#1687]
### Version

Media3 main branch

### More version details

Library Version: androidx.media3:media3-transformer:1.4.1
Android Version: Android 13 and other emulators.
Device Model: Tested in Moto Edge 40 and pixel emulators

### Devices that reproduce the issue

Device Model: Tested in Moto Edge 40 and pixel emulators .

### Devices that do not reproduce the issue

NA

### Reproducible in the demo app?

Yes

### Reproduction steps

I've been exploring the Media3 APIs for applying video effects, and I've encountered an issue when trying to preview effects on image-based MediaItem. The effects are successfully applied and previewed when the MediaItem is a video, but the same effects are not applied when the MediaItem is an image (e.g., a JPEG file).

**Working Case (Video):**
Create a MediaItem with a video URI.
Apply video effects such as zoom or rotate.
The effects are successfully applied and previewed using ExoPlayer.

```
val mediaItem1 = MediaItem.Builder().setUri(videoUri).build()

val player = ExoPlayer.Builder(context).build()
player.playWhenReady = true
player.setMediaItem(mediaItem1)
player.setVideoEffects(
    ImmutableList.of(
        createRotateEffect(3000),
        createZoomEffect(3000, 0.5f, 1f),
        createZoomEffect(3000, 1f, 0.5f)
    )
)
player.prepare()
playerView.player = player

```
**Not Working Case (Image):**
Create a MediaItem with an image URI and set a duration using setImageDurationMs.
Apply the same video effects.
The effects are not applied when previewing using ExoPlayer.

```
val mediaItem1 = MediaItem.Builder()
    .setUri(getUri(context, "image1.jpg"))
    .setImageDurationMs(3000)
    .build()

val player = ExoPlayer.Builder(context).build()
player.playWhenReady = true
player.setMediaItem(mediaItem1)
player.setVideoEffects(
    ImmutableList.of(
        createZoomEffect(3000, 0.5f, 1f)
    )
)
player.prepare()
playerView.player = player
```

### Expected result

The video effects should be applied and previewed correctly, even when the MediaItem is an image.

### Actual result

The effects are not applied when the MediaItem is an image.

### Media

[Screen_recording_20240902_200249.webm](https://github.com/user-attachments/assets/15a585ab-7530-42a1-854a-40f37ec50215)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by avinash--reddy** [comment]
Please note that the same is working for export using Media transformer api.Same has been discussed in https://github.com/androidx/media/issues/1658 and working as expected now.

**Comment by avinash--reddy** [comment]
Hi @droid-girl  Could you please help with this query.

**Comment by avinash--reddy** [comment]
@claincly  I see this restrict option for compositionPlayer. Will this be a restriction for other apps to use this ? 

![image](https://github.com/user-attachments/assets/9bbb138c-e204-43c9-b11c-dc886d0b1e08)

**Comment by claincly** [comment]
It's added because it's currently under construction and may be less tested, but you can try it out no problem.

**Comment by avinash--reddy** [comment]
Thank you @claincly !! 
I’ve tested CompositionPlayer, and it seems to be working well . Given that it is currently marked with the @RestrictTo(LIBRARY_GROUP) annotation and noted as being under construction, is it recommended to use it in a production app at this stage ? Are there any potential issues or limitations that we should be aware of before proceeding?. Thanks.

**Comment by claincly** [comment]
I guess that depends on what you want to achieve with it and what features do you need, like what is your typical set up, what you want to play with it?

**Comment by claincly** [comment]
These features should all be well-supported, one note on the TextOverlay, we don't support `Composition` level effects yet so you have to add it to every `EditedMediaItem`

**Comment by avinash--reddy** [comment]
Ok. Thank you very much for all the details.
