### ISSUE TITLE
Issue with Replacing Existing Subtitle in ExoPlayer

### ISSUE THREAD

**Issue by Usman-Click** [androidx/media#1696]
Hi,
I'm encountering an issue when trying to replace an existing subtitle in an ExoPlayer-based Android project. When attempting to replace an existing subtitle, the player continues to use the old subtitle or does not reflect the updated configuration. However, adding a subtitle to a video that does not already have a subtitle works fine.

### **Steps to Reproduce:**

1. **Attempt to Replace the Subtitle:**
   - Clear the media items, create a new `SubtitleConfiguration`, and set it as the new subtitle for the media item.
   - Example:
     ```java
     MediaItem.SubtitleConfiguration newSubtitle = new MediaItem.SubtitleConfiguration.Builder(newSubtitleUri)
            .setMimeType(MimeTypes.APPLICATION_SUBRIP)
            .setSelectionFlags(C.SELECTION_FLAG_DEFAULT)
            .build();

     MediaItem newMediaItem = new MediaItem.Builder()
            .setUri(videoUri)
            .setSubtitleConfigurations(ImmutableList.of(newSubtitle))
            .build();

     player.clearMediaItems(); // Clear any existing media items
     player.setMediaItem(newMediaItem); // Set the new media item with the updated subtitle
     player.prepare();
     ```

2. **Play the Video:**
   - Resume playback with the expectation that the new subtitle will be displayed.

### **Expected Behavior:**
- The player should display the new subtitle, effectively replacing the existing subtitle.

### **Actual Behavior:**
- When replacing an existing subtitle, the player continues to display the initial subtitle or does not reflect the new subtitle configuration as expected.
- Adding a subtitle to a video that does not already have a subtitle works fine.

### **Additional Context:**
- The issue occurs consistently when trying to replace an existing subtitle with a new one.
- The problem does not occur when adding subtitles to a video that does not already have subtitles.
- Clearing the media items and setting a new media item does not appear to update the subtitle as intended.

Thank you for your response

**Comment by oceanjules** [comment]
What do you mean by "resume playback"? Are you clearing the media items during playback? Are you keeping the same videoUrl, hoping for a seamless continuation?

**Comment by Usman-Click** [comment]
I meant: when I select another subtitle file from storage and try to add it to the video it doesn't reflect it's the old one that's reflecting ,

As you can see below I created a new MediaItem with the new subtitle file but still it's the subtitle that comes with the video shows 

MediaItem.SubtitleConfiguration newSubtitle = new MediaItem.SubtitleConfiguration.Builder(newSubtitleUri)
       .setMimeType(MimeTypes.APPLICATION_SUBRIP)
       .setSelectionFlags(C.SELECTION_FLAG_DEFAULT)
       .build();

MediaItem newMediaItem = new MediaItem.Builder()
       .setUri(videoUri)
       .setSubtitleConfigurations(ImmutableList.of(newSubtitle))
       .build();

player.clearMediaItems(); // Clear any existing media items
player.setMediaItem(newMediaItem); // Set the new media item with the updated subtitle
player.prepare();

**Comment by icbaker** [comment]
I'm not able to reproduce this at the tip of the `main` branch. What version of the library are you using? I modified the demo app to add the following code to `PlayerActivity.initializePlayer` [just after the call to `player.prepare()`]():

```java
MediaItem mediaItemWithDifferentSubtitles =
    mediaItems
        .get(0)
        .buildUpon()
        .setSubtitleConfigurations(
            ImmutableList.of(
                new MediaItem.SubtitleConfiguration.Builder(
                        Uri.parse(
                            "https://storage.googleapis.com/exoplayer-test-media-1/ttml/japanese-ttml.xml"))
                    .setMimeType(MimeTypes.APPLICATION_TTML)
                    .setSelectionFlags(C.SELECTION_FLAG_DEFAULT)
                    .build()))
        .build();
player
    .createMessage(
        (messageType, message) -> player.setMediaItem(mediaItemWithDifferentSubtitles))
    .setLooper(player.getApplicationLooper())
    .setPosition(5000)
    .send();
```

I then played the `Subtitles > TTML Positioning` sample and 5s in (as expected) playback restarted and showed Japanese subtitles instead.

I tried modifying my code to include the additional `clearMediaItems()` and `prepare()` calls from your example, but I still was unable to reproduce your problem:

```java
player
    .createMessage(
        (messageType, message) -> {
          player.clearMediaItems();
          player.setMediaItem(mediaItemWithDifferentSubtitles);
          player.prepare();
        })
    .setLooper(player.getApplicationLooper())
    .setPosition(5000)
    .send();
```

I also tried with legacy subtitle decoding (`defaultMediaSourceFactory.experimentalParseSubtitlesDuringExtraction(false)`), but was still unable to repro.

One thing that's not clear in your repro steps: Is your **original** media item configured with sideloaded subtitles via `MediaItem.Builder.setSubtitleConfigurations` or are the subtitles part of the stream (e.g. muxed into an MP4 file, or configured as part of a DASH/HLS playlist)? 

If it's the former case (which is what my repro steps recreate), please can you try my repro steps in the demo app and see if you still see an issue?

If it's the latter case, please can you send the media file to android-media-github@google.com with subject `Issue #1696` so we can take a look, and update this issue when you've done so.
