### ISSUE TITLE
exoplayer video rotate is error

### ISSUE THREAD

**Issue by captain81** [androidx/media#1704]
### Version

Media3 main branch

### More version details

1.Record the video with rotate 180 by iphone 
2.Play the video by iphone, the video is play with rotate 0 on iphone
3.Play the video by ffmpeg or vlc, the video is play with rotate 180 on these players
4.Play the video by exoplayer, the video is play with rotate 0 on exoplayer
5.get the video information by ffmpeg, the displaymatrix is 
[SIDE_DATA]
side_data_type=Display Matrix
displaymatrix=
00000000:       **-65536**           0           0
00000001:            0       **65536**           0
00000002:    125829120           0  1073741824
rotation=**-180**
6. Exoplayer's  parseTkhd() 
  if (a00 == -fixedOne && a01 == 0 && a10 == 0 && a11 == -fixedOne) {
      rotationDegrees = 180;
    }
if a00 == -65536 and a11 == -65536  rotationDegrees is 180,  but this video a00 == -65536 and a11 == 65536, rotationDegrees consider as 0 degrees by exoplayer, so the display degree is error 

### Devices that reproduce the issue

oppo mobilephone

### Reproducible in the demo app?

Yes

### Reproduction steps

Play the video by exoplayer

### Expected result

the video is play with rotate 180 on exoplayer

### Actual result

the video is play with rotate 0 on exoplayer

### Media

NA

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by marcbaechinger** [comment]
Thanks for your report. 

Can you please provide us with a sample media that allows us to reproduce the issue?
