### ISSUE TITLE
How to override small icon in media3 notification

### ISSUE THREAD

**Issue by marcelpallares** [androidx/media#172]
I have been trying to change the small icon from the default media3 notification following the next approach from the following links for ExoPlayer:

https://github.com/google/ExoPlayer/issues/5372
https://stackoverflow.com/a/58302954/4945933

So I have added these in one of my values xml files to test it:

```
<drawable name="exo_notification_small_icon">@drawable/ic_notification_icon</drawable>
<drawable name="exo_notification_pause">@drawable/ic_pause</drawable>
<drawable name="exo_notification_play">@drawable/ic_play</drawable>
```

These are not working and I'm wondering if this approach actually works with `media3`? 
Should it work straight away? Don't I need to somehow reference these drawables from my theme? 
Am I missing anything? :) 

Thanks!

**Comment by marcbaechinger** [comment]
In Media3 the notification is created by the `DefaultMediaNotificationProvider`. 

You can either override the  drawable in your resource files:

```
<drawable name="media3_notification_small_icon">@drawable/my_drawable_small_icon</drawable>
```

of use the API on the `DefaultMediaNotificationProvider` that has a setter `setSmallIcon(@DrawableRes int smallIconResourceId)`.

Please re-open if this does not work. Thanks!
