### ISSUE TITLE
How to get real playlist when player is in shuffled mode

### ISSUE THREAD

**Issue by dongpingwang** [androidx/media#1724]
i want to snap left and right to switch prev/next song，i can't get real playlist in shuffled mode , so it  don't know how to handle it

when snapping i need display prev/next song's name, but i only have playlist in repeated mode, cause display song's name is not  right when snapping, after snapping finish  i use skipToNextMediaItem/skipToPreviousMediaItem to switch song.

**Comment by marcbaechinger** [comment]
Thanks for your question. 

You can iterate over the timeline and say whether to use shuffling mode or not. This works in the very same way except the boolean that indicates whether to apply shuffling or not:

```

    val window = Timeline.Window()
    var windowIndex = timeline.getFirstWindowIndex(true)

    // iterate with shuffle mode off
    while (windowIndex != C.INDEX_UNSET) {
      // do something with the media item
      timeline.getWindow(windowIndex, window).mediaItem
      // next window index without shuffling
      windowIndex =
        timeline.getNextWindowIndex(
          windowIndex,
          Player.REPEAT_MODE_OFF,
          /* shuffleModeEnabled= */ false,
        )
    }

   // iterate with shuffle mode on
    while (windowIndex != C.INDEX_UNSET) {
      // do something with the media item
      timeline.getWindow(windowIndex, window).mediaItem
      // go to next window in shuffle mode
      windowIndex =
        timeline.getNextWindowIndex(
          windowIndex,
          Player.REPEAT_MODE_OFF,
          /* shuffleModeEnabled= */ true,
        )
    }
```

**Comment by dongpingwang** [comment]
thx，i test it's good!，thx
