### ISSUE TITLE
Two switchable PlayerViews on one screen

### ISSUE THREAD

**Issue by ziem** [androidx/media#174]
Hello,
Is there any documentation describing how to handle multiple switchable `PlayerView`s on one screen? 

In my case, I have two `Fragment`s on one screen: 
1. `PlayerFragment` with a normal `PlayerView`;
2. `MiniPlayerFragment` with another, smaller `PlayerView`. 

As a user, you can switch between them so there is always only one `PlayerView` playing a video. When you switch to `MiniPlayerFragment` it appears and follows you through the apps. When you switch back, `MiniPlayerFragment` disappears, and the playback resumes in the `PlayerFragment`. It's very similar to the mini player YouTube app has. The only difference is that it's done by using two `PlayerView`s. 

I'm using `MediaSessionService` where I keep `ExoPlayer` instance, and each `Fragment` has its own `MediaController`, and I switch between them like this (simplified):
```
if (showInMiniPlayer) {
    playerFragment.playerView.player = null
    miniPlayer.playerView.player = miniPlayerMediaController // created in `onStart` method
} else {
    miniPlayer.playerView.player = null
    playerFragment.playerView.player = playerMediaController // created in `onStart` method
}
```

It works, I mean sometimes. In general, controls work, but often `PlayerView` becomes black (the one that should play a video). I can hear the audio, and the time bar is moving.

What’s the recommended approach for such cases?

**Comment by tonihei** [comment]
I think you need to swap the order of your assignments to ensure the player can seamlessly transition between the views. 
We also have a helper method: `PlayerView.switchTargetView` that handles this for you and takes care about the ordering.

**Comment by ziem** [comment]
Thanks @tonihei
