### ISSUE TITLE
java.net.SocketTimeoutException & HttpDataSrouce$InvaildResponseCodeException : 503

### ISSUE THREAD

**Issue by WoKee** [androidx/media#1743]
### Version

Media3 main branch

### More version details

1.4.1

### Devices that reproduce the issue

all device

### Reproducible in the demo app?

No

### Reproduction steps

1、Media url : ftp://a.gbl.114s.com:20320/8895/雪迷宫02.mp4

2、Using P2P libraries,  convert to : http://127.0.0.1:8089/%D1%A9%C3%D4%B9%AC02.mp4 

`     
 p2p.P2Pdoxstart(path.getBytes("GBK"));

       clock.setCallback(this);

       clock.stop().start();

       return "http://127.0.0.1:" + p2p.port + "/" + URLEncoder.encode(Uri.parse(path).getLastPathSegment(), "GBK");

`

3、Using IjkPlayer SDK  / VLC SDK / Mpv SDK , can play successfully , but only using exoplayer play error.

4、The ExoPlayer HttpDataSource.Factory  I am using.  

`
 private HttpDataSource.Factory getHttpDataSourceFactory() {

        if (httpDataSourceFactory == null)

            httpDataSourceFactory =  new OkHttpDataSource.Factory(new OkHttpClient.Builder().build());

        return httpDataSourceFactory;

    }

`

Using OkHttpDataSource throw java.net.SocketTimeoutException :timeout.
![Dingtalk_20240919173401](https://github.com/user-attachments/assets/e1462995-cc14-4d15-960c-633fe82e35db)

` 
private HttpDataSource.Factory getHttpDataSourceFactory() {

        if (httpDataSourceFactory == null)

            httpDataSourceFactory =  new DefaultHttpDataSource.Factory();

        return httpDataSourceFactory;

    }
`
 
Using DefaultHttpDataSource throw HttpDataSrouce$InvaildResponseCodeException : 503

![Dingtalk_20240919175142](https://github.com/user-attachments/assets/b99766ea-3125-4f7a-b40a-2556cdfe9c5f)

### Expected result

play successfully 

### Actual result

error

### Media

ftp://a.gbl.114s.com:20320/8895/雪迷宫02.mp4

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment]
Converting an `ftp://` URL to a `localhost` `http://` URL sounds unusual - I suspect whatever is facilitating this 'conversion' (presumably by proxying HTTP calls and forwarding them over FTP) is responsible for the issues you're seeing.

> Using DefaultHttpDataSource throw HttpDataSrouce$InvaildResponseCodeException : 503

This error is coming from the HTTP server - if you want to know why it's occuring, you need to inspect the server logs, we can't really help from the client side. In this case it seems likely the "HTTP server" is the tool you're using to "convert" from FTP to HTTP.

**Comment by WoKee** [comment]
If it's an HTTP service issue, ijk or vlc will also fail to play. 
 
`http://127.0.0.1:8089/%D1%A9%C3%D4%B9%AC02.mp4`

There is no problem with converting this address, and the IDM downloader can also download the file normally.

This is a P2P address, and I believe it is due to exo's `DefaultMediaSourceFactory ` not correctly converting to the corresponding MediaSource ` (convert to ProgressiveMediaSource)` , which caused the program to use the wrong BaseDataSource, `OkHttpDataSource.open (DataSpec dataSpec)`

This is just a speculation. If needed, I can provide a GitHub demo that integrates ijk and exo

**Comment by WoKee** [comment]
log:

IJK : success

[ijk.txt](https://github.com/user-attachments/files/17112330/ijk.txt)

EXO :  fail

[exo.txt](https://github.com/user-attachments/files/17112328/exo.txt)

**Comment by icbaker** [comment]
I'm going to close this issue, because I don't think there's much more help we can offer here (I don't have anything further to add beyond my previous comment).

**Comment by WoKee** [comment]
> I'm going to close this issue, because I don't think there's much more help we can offer here (I don't have anything further to add beyond my previous comment).

OK ，I will use VLC to replace EXO to solve this problem

**Comment by FongMi** [comment]
Add http header "Range" : "0" to play

**Comment by shan0404** [comment]
你可以复制一份OkHttpDataSource.java自定义一下
将
 `@Nullable String rangeHeader = buildRangeRequestHeader(position, length);`
替换成
`@Nullable String rangeHeader = dataSpec.uri.getPort()==8089?buildRangeRequestHeaderJP(position, length):buildRangeRequestHeader(position, length);
`
然后添加方法
`
  public static String buildRangeRequestHeaderJP(long position, long length) {
    StringBuilder rangeValue = new StringBuilder();
    rangeValue.append("bytes=");
    rangeValue.append(position);
    rangeValue.append("-");
    if (length != C.LENGTH_UNSET) {
      rangeValue.append(position + length - 1);
    }
    return rangeValue.toString();
  }
`

**Comment by shan0404** [comment]
> > 你可以复制一份OkHttpDataSource.java自定义一下 将
> > ```
> > @Nullable String rangeHeader = buildRangeRequestHeader(position, length);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 替换成
> > ```
> > @Nullable String rangeHeader = dataSpec.uri.getPort()==8089?buildRangeRequestHeaderJP(position, length):buildRangeRequestHeader(position, length);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后添加方法
> > ```
> > public static String buildRangeRequestHeaderJP(long position, long length) {
> >     StringBuilder rangeValue = new StringBuilder();
> >     rangeValue.append("bytes=");
> >     rangeValue.append(position);
> >     rangeValue.append("-");
> >     if (length != C.LENGTH_UNSET) {
> >       rangeValue.append(position + length - 1);
> >     }
> >     return rangeValue.toString();
> >   }
> > ```
> 
> 这个方法可以。 是因为EXO的 DefaultHttpDataSource.java 没有正确处理header range导致的？ 这个问题的解决思路是什么？

你这里用的是OkHttpDataSource不是DefaultHttpDataSource.java，直接把这里的改成本地自定义的OkHttpDataSource.java
```
    if (httpDataSourceFactory == null)

        httpDataSourceFactory =  new OkHttpDataSource.Factory(new OkHttpClient.Builder().build());

    return httpDataSourceFactory;

}
```
当rangeHeader等于null的时候，OkHttpDataSource.java open 方法里的this.response = executeCall(call);会一直收不到服务器的响应，应该是服务器在rangeHeader为null时不会正确响应，至于ijk和mpv为什么可以，或许也是它们自行构造了不为null的rangeHeader，你可以自己分析一下，当然这只是我的理解不知道对不对。
