### ISSUE TITLE
Support Live Photo 

### ISSUE THREAD

**Issue by 309152665** [androidx/media#1748]
Support play Live Photo

**Comment by tonihei** [comment]
If your questions is about motion photos, then they are already supported: https://developer.android.com/media/media3/exoplayer/images#motion-photos

If you are referring to something else, please clarify.

**Comment by 309152665** [comment]
> If your questions is about motion photos, then they are already supported: https://developer.android.com/media/media3/exoplayer/images#motion-photos
> 
> If you are referring to something else, please clarify.


iPhone -> Camera -> 
![QQ_1727227159914](https://github.com/user-attachments/assets/9419a03c-e92e-4801-874f-a3fb84caa2ad)

take photo , the image is Live Photo.
