### ISSUE TITLE
How to receive a search query from a voice command with Media3 session callback?

### ISSUE THREAD

**Issue by tzugen** [androidx/media#177]
G-Play review suddenly demands voice commands to be implemented if the app has Android Auto enabled.
I guess it looks at on whether [onPlayFromSearch()](https://developer.android.com/reference/android/support/v4/media/session/MediaSessionCompat.Callback#onPlayFromSearch(java.lang.String,%20android.os.Bundle)) is implemented.

But media3.MediaLibrarySession does not have a `onPlayFromSearch`. 
Do you have any idea what to do instead?

**Comment by marcbaechinger** [comment]
This is an legacy API that does not exist in Media3. 

The request coming from the legacy controller is converted to the Media3 API by creating a `RequestMetadata` object which is part of the `MediaItem`. You need to override `MediaSession.Callback.onAddMediaItems(...)` where you can acccess the search query with `mediaItem.requestMetadata.searchQuery`.

Please [see the demo app](https://github.com/androidx/media/blob/release/demos/session/src/main/java/androidx/media3/demo/session/PlaybackService.kt#L191) also that uses the `searchQuery` as explained.

**Comment by marcbaechinger** [comment]
Closing as the question looks sufficiently answered.
