### ISSUE TITLE
Video Output Fails After Minimizing App in OpenGL ExoPlayer Demo

### ISSUE THREAD

**Issue by Shadkirill** [androidx/media#1780]
### Version

Media3 main branch

### More version details

I am encountering an issue with the OpenGL `ExoPlayer demo` that renders the player output into a `GLSurfaceView`. After minimizing the app and reopening it, the video stops displaying and only a black screen appears. The issue can sometimes be reproduced more easily by minimizing the app, starting a YouTube video, and then returning to the OpenGL demo app.

Steps to Reproduce:
Run the OpenGL ExoPlayer demo that renders into a `GLSurfaceView`.
Minimize the app.
Reopen the app – at this point, the video fails to display, showing only a black screen.
Additional Information:

The issue does not occur in the older ExoPlayer repository, so it might be a recent problem introduced in media3.
The bug is intermittent but seems to happen more frequently after switching between the demo app and another video-playing app like YouTube.

Could you please investigate this issue and provide any guidance on how to resolve or work around it?

### Devices that reproduce the issue

Pixel 8 PRO
Samsung Fold 4
Pixel 7 PRO

### Reproducible in the demo app?

Yes

### Reproduction steps

Run the OpenGL ExoPlayer demo that renders into a `GLSurfaceView`.
Minimize the app.
Reopen the app – at this point, the video fails to display, showing only a black screen.
Additional Information:

### Expected result

The media plays

### Actual result

Black screen

### Media

---

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by Shadkirill** [comment]
any updates?

**Comment by ychaparov** [comment]
I was unable to reproduce this issue with [demos/gl/src/main/java/androidx/media3/demo/gl/MainActivity.java](https://github.com/androidx/media/blob/c35a9d62baec57118ea898e271ac66819399649b/demos/gl/src/main/java/androidx/media3/demo/gl/MainActivity.java#L54)

Can you please reproduce the issue again, record an `adb bugreport` zip and email it to [android-media-github@google.com](mailto:android-media-github@google.com) ?

See instructions in the github issue template
