### ISSUE TITLE
Exoplayer takes more time to render the first frame of UDP Live stream compared to VLC

### ISSUE THREAD

**Issue by AustinRenitezC** [androidx/media#1787]
We are using target version as Android 11 and Exoplayer media 3 version 1.1.1 in Android STB (Set top box). When we play an UDP stream on an average Exoplayer is taking 3 sec to render the first frame. But when we used standalone Android VLC player in the same STB it is taking only 1.5 seconds to render the first frame. Below is the code used to play the UDP stream in Exoplayer, any way to improve the first frame render time 
NetworUploadSpeed = 97.5MBPS
NetworDownloadSpeed  = 97MBPS

fun initializeUDP(context: Context, videoUrl: String) {
        trackSelector = DefaultTrackSelector(context).apply {
            setParameters(buildUponParameters().setAllowVideoMixedDecoderSupportAdaptiveness(true))
        }

        // Create MediaSource
        val uri = Uri.parse(videoUrl)
        val mediaSource: MediaSource = ProgressiveMediaSource.Factory(UdpDataSource())
            .createMediaSource(MediaItem.fromUri(uri))

        val renderersFactory = DefaultRenderersFactory(context)
            .forceEnableMediaCodecAsynchronousQueueing()
            .experimentalSetSynchronizeCodecInteractionsWithQueueingEnabled(true)
        player = ExoPlayer.Builder(context, renderersFactory)
            .setTrackSelector(trackSelector!!)
            .build()
        player!!.playWhenReady = true
        if (playerView != null) {
            playerView!!.player = player
        }
        player!!.setMediaSource(mediaSource)
        player!!.addListener(this)
        player?.addAnalyticsListener(this)
        player!!.prepare()
    }

**Comment by microkatz** [comment]
@AustinRenitezC 

Thank you for posting your code snippet. I don't see any customizations on the LoadControl settings for your player. You can, for instance, set the duration values for the player's LoadControl instance to adjust how much content should be buffered before playback will resume. Check out the [setBufferDurationsMs](https://developer.android.com/reference/androidx/media3/exoplayer/DefaultLoadControl.Builder#setBufferDurationsMs(int,int,int,int)) API. You can see the default values for these [here](https://developer.android.com/reference/androidx/media3/exoplayer/DefaultLoadControl#constants_1).

It may help your case to set a `DefaultLoadControl` instance with a customized `bufferForPlaybackMs` to reduce the duration that must be buffered before playback starts. The ExoPlayer.Builder interface has a [setLoadControl](https://developer.android.com/reference/kotlin/androidx/media3/exoplayer/ExoPlayer.Builder#setLoadControl(androidx.media3.exoplayer.LoadControl)) API.

Hope that helps!

**Comment by microkatz** [comment]
As I have not received a response I will assume the suggestion resolved your issue! If it had not, then feel free to re-open or create a new issue thread. Thanks!
