### ISSUE TITLE
Groovy dependency documentation shows kotlin "val"

### ISSUE THREAD

**Issue by dburckh** [androidx/media#179]
### Media3 Version

1.0.0-beta02

### Devices that reproduce the issue

All

### Devices that do not reproduce the issue

Note

### Reproducible in the demo app?

Not tested

### Reproduction steps

Click this link

https://developer.android.com/jetpack/androidx/releases/media3#groovy

Groovy doc uses kotlin keyword "val", should be "def"

### Expected result

dependencies {
    def media3_version = "1.0.0-beta02"

### Actual result

dependencies {
    val media3_version = "1.0.0-beta02"

### Media

https://developer.android.com/jetpack/androidx/releases/media3#groovy

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
Good spot, thanks for reporting - I've sent a change to fix this internally, it should be published shortly after it's merged.

**Comment by dburckh** [comment]
Thanks for the lightning fast response!

**Comment by icbaker** [comment]
The fix is now live
