### ISSUE TITLE
EXOPlayer + H265  report  PLA-352 PLAYER_DECODER_ERROR

### ISSUE THREAD

**Issue by tongwu460** [androidx/media#1803]
Issue picture:
![image](https://github.com/user-attachments/assets/c4d712c0-a877-47c5-804e-d862f75e2493)

Android device version:
[LG]webOS TV UR78006LL    8.3.1-3607
![Samsung Device version](https://github.com/user-attachments/assets/3d06c0f7-a341-4700-9c3b-bb7446c43817)

MPD files:
[3221227439.mpd.txt](https://github.com/user-attachments/files/17355405/3221227439.mpd.txt)

Android device ERROR Logs:
[Error-logs.txt](https://github.com/user-attachments/files/17355409/Error-logs.txt)

10-13 10:50:47.444  8279  8538 E ExoPlayerImplInternal: Playback error
10-13 10:50:47.444  8279  8538 E ExoPlayerImplInternal:   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/hevc, hvc1.1.6.L90.B0, 1537148, null, [854, 480, 25.0], [-1, -1]), format_supported=YES
10-13 10:50:47.558  8279  8352 I ReactNativeJS: ["10:50:47 [app:api:analytics:firebase] → [LOG] EVENT => eventName=playback_error, param: {\"title\":\"ART Al Hekayat\",\"channelId\":\"5788\",\"channelName\":\"ART Al Hekayat\",\"channelNumber\":152,\"errorCode\":\"PLA-352\",\"code\":\"PLAYER_DECODER_ERROR\",\"numCode\":\"352\",\"description\":\"React Native Video Error: Decoder Error\",\"playerAutoRetry\":true,\"context\":\"PLA\",\"extraLog\":\"\",\"backend\":\"\",\"backendErrorCode\":\"MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/hevc, hvc1.1.6.L90.B0, 1537148, null, [854, 480, 25.0], [-1, -1]), format_supported=YES\"}","color: lightblue"]

**Comment by tongwu460** [comment]
@OmarBasem  can you pls support have a look at this error?

**Comment by rrfrias** [comment]
Is this a LG web OS TV or an android TV? I am not sure how you are getting android logs from a web OS TV (based on the TV information jpeg). Can you share a bugreport with [android-media-github@google.com](mailto:android-media-github@google.com) and mention `Issue 1803` in the subject.
