### ISSUE TITLE
Android 15 loudness normalization and existing volume normalization

### ISSUE THREAD

**Issue by OxygenCobalt** [androidx/media#1806]
Android 15 introduces support for [AAC loudness control](https://developer.android.com/about/versions/15/features#loudness-control). Moreover, it's said that Media3 will add support for this. 

If I'm understanding this correctly, will this allow me to offload my own app's volume normalization data to the OS, rather than using an `AudioProcessor` like in [this issue](https://github.com/google/ExoPlayer/issues/9796)?

For example, in some `MediaItem` I could do like:

`mediaItemBuilder.setLoudnessControl(dbGain = -3.9)`

And Media3 would pipe that loudness metadata into `MediaCodec`, and the system would automatically adjust the volume down -3.9 dB.

Or will it only work in particular situations, such as only in AAC containers?

Thanks!

**Comment by microkatz** [comment]
@OxygenCobalt 

Apologies for the delay. Yes, the `LoudnessCodecController` is supported as of ExoPlayer 1.5.0 as noted in the [release notes](https://github.com/androidx/media/releases/tag/1.5.0#:~:text=Automatically%20configure%20CTA%2D2075%20loudness%20metadata%20on%20the%20codec%20if%20present%20in%20the%20media.). 

ExoPlayer automatically connects the media codec and audio track platform pieces using a default [LoudnessCodecController](https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/mediacodec/LoudnessCodecController.java#L66). You can see that ExoPlayer follows the suggested practice in attached documentation [link](https://developer.android.com/about/versions/15/features#loudness-control) of creating a LoudnessCodecController and attaching `MediaCodec`s and `AudioSessionId` to it. This will automatically make the media codec take in the characteristics of the output devices with the content loudness metadata when decoding. The effects are in line with the CTA-2075 spec. Section 8 describes the effects of the environment and output devices with different compressed audio formats on the loudness.

As the mediacodec decoders take in metadata specifically within the stream, there is not a setter within `MediaItem.Builder` to adjust loudness data.

If you want to provide additional edits on loudness. You can still implement your own audio processor. Or you can take advantage of the new `LoudnessCodecController` class with a custom `LoudnessParameterUpdateListener`. The `onLoudnessParameterUpdate` callback is invoked whenever the platform will update mediacodec with new parameters to adjust the loudness. By altering these values you would be modifying how the decoder will make adjustments.

Hope that helps!

**Comment by OxygenCobalt** [comment]
> @OxygenCobalt 
> 
> Apologies for the delay. Yes, the `LoudnessCodecController` is supported as of ExoPlayer 1.5.0 as noted in the [release notes](https://github.com/androidx/media/releases/tag/1.5.0#:~:text=Automatically%20configure%20CTA%2D2075%20loudness%20metadata%20on%20the%20codec%20if%20present%20in%20the%20media.). 
> 
> ExoPlayer automatically connects the media codec and audio track platform pieces using a default [LoudnessCodecController](https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/mediacodec/LoudnessCodecController.java#L66). You can see that ExoPlayer follows the suggested practice in attached documentation [link](https://developer.android.com/about/versions/15/features#loudness-control) of creating a LoudnessCodecController and attaching `MediaCodec`s and `AudioSessionId` to it. This will automatically make the media codec take in the characteristics of the output devices with the content loudness metadata when decoding. The effects are in line with the CTA-2075 spec. Section 8 describes the effects of the environment and output devices with different compressed audio formats on the loudness.
> 
> As the mediacodec decoders take in metadata specifically within the stream, there is not a setter within `MediaItem.Builder` to adjust loudness data.
> 
> If you want to provide additional edits on loudness. You can still implement your own audio processor. Or you can take advantage of the new `LoudnessCodecController` class with a custom `LoudnessParameterUpdateListener`. The `onLoudnessParameterUpdate` callback is invoked whenever the platform will update mediacodec with new parameters to adjust the loudness. By altering these values you would be modifying how the decoder will make adjustments.
> 
> Hope that helps!
> 

This is helpful! Will test on my own end and see what I can do and follow up later

**Comment by microkatz** [comment]
Glad I could provide useful context! In that case I'm going to close this thread. If you have additional questions then feel free to create a new issue.
