### ISSUE TITLE
ExoPlayer ignores embedded 608 captions in Dolby Vision streams

### ISSUE THREAD

**Issue by Halmo** [androidx/media#1820]
### Version

Media3 main branch

### More version details

627b7a3e56e3c8242a1f702509c7484373f9cdce

### Devices that reproduce the issue

All

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Play a Dolby Vision DASH stream with embedded 608 captions in the Demo app.
2. Enable captions.

### Expected result

Captions are enabled and are rendered.

### Actual result

Captions are enabled but are not rendered.

This occurs because the Dolby Vision metadata in the video track causes the mime type to be `video/dolby-vision` instead of `video/hevc` or `video/avc`.

In this line: https://github.com/androidx/media/blob/49337d966705d854091dfc26a3f2006d29231c97/libraries/extractor/src/main/java/androidx/media3/extractor/mp4/FragmentedMp4Extractor.java#L1609

`NalUnitUtil.isNalUnitSei` always returns false because the function only checks for H264 or H25 mime types: https://github.com/androidx/media/blob/release/libraries/container/src/main/java/androidx/media3/container/NalUnitUtil.java#L342

If the mime type is Dolby Vision the Sei NAL units get ignored.

Secondly for H265 Dolby Vision this check also fails: https://github.com/androidx/media/blob/49337d966705d854091dfc26a3f2006d29231c97/libraries/extractor/src/main/java/androidx/media3/extractor/mp4/FragmentedMp4Extractor.java#L1632

If Dolby Vision is or'd with the H265 format for the above 2 cases the issue is resolved. However, the fix obviously isn't that simple because H264 or H265 can in theory be Dolby Vision. 

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by akhilesh-dubey** [comment]
@icbaker 
@Halmo will provide more details on this. The main issue is that the check for Dolby Vision MIME type is not included, which leads to a failure in displaying CEA-608 captions when playing Dolby Vision (HEVC-HDR) tracks. It works fine with MIME type AVC (AVC-SDR) tracks. Although adding a following check for Dolby Vision in both places resolves the issue, Not sure if this is the correct approach for Dolby Vision support. Unfortunately, there's no quick workaround available to implement a fix right away.

```
  public static boolean isNalUnitSei(@Nullable String mimeType, byte nalUnitHeaderFirstByte) {
    return (MimeTypes.VIDEO_H264.equals(mimeType)
            && (nalUnitHeaderFirstByte & 0x1F) == H264_NAL_UNIT_TYPE_SEI)
        || (MimeTypes.VIDEO_H265.equals(mimeType)
            && ((nalUnitHeaderFirstByte & 0x7E) >> 1) == H265_NAL_UNIT_TYPE_PREFIX_SEI)
        || (MimeTypes.VIDEO_DOLBY_VISION.equals(mimeType)
            && ((nalUnitHeaderFirstByte & 0x7E) >> 1) == H265_NAL_UNIT_TYPE_PREFIX_SEI);
  }
```
and
```
            nalBuffer.setPosition(MimeTypes.VIDEO_H265.equals(track.format.sampleMimeType)
                || MimeTypes.VIDEO_DOLBY_VISION.equals(track.format.sampleMimeType) ? 1 : 0);
```

**Comment by akhilesh-dubey** [comment]
Thanks @icbaker 
@Halmo can provide more details on this and probably share the sample assets if required. 
The main issue is that the check for Dolby Vision MIME type is not included, which leads to a failure in displaying CEA-608 captions when playing Dolby Vision (HEVC-HDR) tracks. It works fine with MIME type AVC (AVC-SDR) tracks. Although adding a following check for Dolby Vision in both places resolves the issue, Not sure if this is the correct approach for Dolby Vision support. Unfortunately, there's no quick workaround available to implement a fix right away.

```
  public static boolean isNalUnitSei(@Nullable String mimeType, byte nalUnitHeaderFirstByte) {
    return (MimeTypes.VIDEO_H264.equals(mimeType)
            && (nalUnitHeaderFirstByte & 0x1F) == H264_NAL_UNIT_TYPE_SEI)
        || (MimeTypes.VIDEO_H265.equals(mimeType)
            && ((nalUnitHeaderFirstByte & 0x7E) >> 1) == H265_NAL_UNIT_TYPE_PREFIX_SEI)
        || (MimeTypes.VIDEO_DOLBY_VISION.equals(mimeType)
            && ((nalUnitHeaderFirstByte & 0x7E) >> 1) == H265_NAL_UNIT_TYPE_PREFIX_SEI);
  }
```
and
```
            nalBuffer.setPosition(MimeTypes.VIDEO_H265.equals(track.format.sampleMimeType)
                || MimeTypes.VIDEO_DOLBY_VISION.equals(track.format.sampleMimeType) ? 1 : 0);
```

@icbaker, to answer your question, yes if we can identify the SEI NAL unit for Dolby Vision stream, and based on that can decide to skip the header bytes, it will resolve the issue. Thanks a lot.

**Comment by icbaker** [comment]
@akhilesh-dubey 

> The main issue is that the check for Dolby Vision MIME type is not included, which leads to a failure in displaying CEA-608 captions when playing Dolby Vision (HEVC-HDR) tracks. **It works fine with MIME type AVC (AVC-SDR) tracks.**

Does the bit I've bolded mean that when you play H.264-in-dolby-vision with CEA-608 subtitles, they work? If so, how does that work, because surely the same MIME type checks you've flagged here should fail with `video/dolby-vision` MIME type.

**Comment by akhilesh-dubey** [comment]
We haven't tried playing H.264 with Dolby Vision yet, but my guess is that it likely won’t work. However, we did test H.264 without Dolby Vision and CEA-608 subtitles, and that played fine. I’m not certain if we have an H.265 stream with Dolby Vision and CEA-608 subtitles available, but if I can find one, I’ll definitely test it.

**Comment by akhilesh-dubey** [comment]
We haven't tried playing H.264(with CEA-608 subtitles) with Dolby Vision yet, but my guess is that it likely won’t work. 
However, we did test H.264(with CEA-608 subtitles) without Dolby Vision, and that worked fine. 
I’m not certain if we have an H.264(with CEA-608 subtitles) stream with Dolby Vision, but if I can find one, I’ll definitely test it.

**Comment by Halmo** [comment]
@icbaker the problem with

```
public static boolean isNalUnitSei(@Nullable String mimeType, byte nalUnitHeaderFirstByte) {
  return ((MimeTypes.VIDEO_H264.equals(mimeType) 
              || MimeTypes.VIDEO_DOLBY_VISION.equals(mimeType))
          && (nalUnitHeaderFirstByte & 0x1F) == H264_NAL_UNIT_TYPE_SEI)
      || ((MimeTypes.VIDEO_H265.equals(mimeType) 
              || MimeTypes.VIDEO_DOLBY_VISION.equals(mimeType))
          && ((nalUnitHeaderFirstByte & 0x7E) >> 1) == H265_NAL_UNIT_TYPE_PREFIX_SEI);
}
```

Is that it would allow H265 Dolby Vision content to check `(nalUnitHeaderFirstByte & 0x1F) == H264_NAL_UNIT_TYPE_SEI)` and presumably that's not valid for H265. I'm not familiar enough with low level H265 spec details to know if that could give a false positive.

Similarly you could also have the inverse where you are playing H264 Dolby Vision and it fails the first check but then checks  `((nalUnitHeaderFirstByte & 0x7E) >> 1) == H265_NAL_UNIT_TYPE_PREFIX_SEI)` not sure if there could be false positives there.

To be honest I think ExoPlayer really needs to append Dolby Vision to the H264/H265 mime types vs having it as its own mime type since to my knowledge there's no dolby vision only codec it's always built on top of another existing codec. But this of course is a large change that touches a lot of pieces in ExoPlayer. We have other workarounds in our code due to the mime type being reported as Dolby Vision and the original codec being dropped from the mime type.

As for content I'll reach out to our internal teams to see if we can help in adding the 608 embedded to your existing test asset.

**Comment by Halmo** [comment]
@icbaker I've sent a sample asset to [android-media-github@google.com](mailto:android-media-github@google.com). It doesn't seem to want to play in ExoPlayer for some reason (didn't investigate too much) but it does execute the code path in FragmentedMp4Extractor.

**Comment by icbaker** [comment]
Thanks for the sample, and for flagging the concerns with false-positives if we just inspect the NAL byte.

I've gone for a different approach using the existing [`MimeTypes.containsCodecsCorrespondingToMimeType()`](https://developer.android.com/reference/androidx/media3/common/MimeTypes#containsCodecsCorrespondingToMimeType(java.lang.String,java.lang.String)) method, which I think should resolve this - the commit with this change is linked above.

**Comment by Halmo** [comment]
> Support CEA-608 subtitles in Dolby Vision

Thanks @icbaker, appreciate the quick action on this. Would you be able to provide an idea on when this will be in a version of Media3 that we can consume?
