### ISSUE TITLE
Android TV - Using D-pad right one press it resets my player to 0:00 time

### ISSUE THREAD

**Issue by simranthakkar1996** [androidx/media#1830]
I am having issue with D-pad right click buttons
When I use D-pad right just once (not long press) then it resets my player to 0:00 time 

This is my code to +10/-10 on my player 
```
       defaultTimeBar = findViewById(R.id.exo_progress);
        if (defaultTimeBar != null) {
            defaultTimeBar.setKeyTimeIncrement(10_000);
        }

```
it should do +10 only instead it just takes me back to beginning of the video
This happens after playing content for 2-3 minutes 

Any suggestion or help would be really helpful 
Thank You.

**Comment by marcbaechinger** [comment]
Please narrow down your question to something not working with the library. We can't debug you app code and it's unclear what the context of the code snippet above is.
