### ISSUE TITLE
How to handle voice commands in Media 3

### ISSUE THREAD

**Issue by jqi26** [androidx/media#1832]
Our Play Store submission with Android Auto support was rejected due to it not supporting voice commands. 

I found this [old issue](https://github.com/androidx/media/issues/177) asking the same question. The answer claims `onAddMediaItems` should be invoked upon a voice query but `onAddMediaItems` in our implementation of `MediaLibrarySession.Callback` is not being called. 

The answer also says to refer to the media session demo, but placing a breakpoint on every overridden function (`onAddMediaItems`, `onGetChildren`, etc.) in `DemoMediaLibrarySessionCallback` shows none of them are being called. In fact, it doesn't seem like voice commands work on the demo app at all.

Steps:
1. Ask Google Assistant "Play Wake Up In Media 3 session demo".
2. Google Assistant responds with "Got it, asking Media 3 Session Demo to play Wake Up in Media 3 session demo".
3. Google Assistant then says "Sorry, something went wrong. When it's safe, please try opening the app to continue".

Expected: Play Wake Up automatically, like in other apps like Spotify.

Can you please re-confirm how we're expected to handle voice commands in Media 3?

**Comment by jqi26** [comment]
Just found this: https://github.com/androidx/media/issues/762. It mentions that voice commands don't work unless the app is installed from the Play Store or as an internal tester. This does make development tricky since we'd need need to upload the build to Google Play to test any change as an internal tester instead of just running it locally. Want to double check I'm not misunderstanding.

**Comment by Tolriq** [comment]
Apps that are not providers officially recognized does not really work when using the name even when on Play Store for years.

You can test by ensuring that you have no media provider configured in Google assistant.
Then use your app with a working media session to be the last active app.

Then just say play some music or play X by Y and the commands will reach your app.

**Comment by lovegaoshi** [comment]
I thought it works if you specify the app name in the command (play X on Y) **and** set Google Assistant's whatever provider to be non default? we have previously tested with podverse's android auto integration.

but anyways what used to be playFromSaerch for media3 is [onSetMediaItems/onAddMediaItems, where mediaItems[0].requestMetadata.searchQuery is your query](https://github.com/lovegaoshi/react-native-track-player/blob/7089bbae462f4173f87823d7bfe5e70325e1b792/android/src/main/java/com/doublesymmetry/trackplayer/service/MusicService.kt#L1083)

**Comment by jqi26** [comment]
> Yeah, we can not really help you with that I'm afraid.
> 
> Media3 provides a media controller to Assistant that is using the controller to send the query to the session it picks. If that happens, the query will arrive as you described and you can handle it. We are not aware how Assistant decides to pick which session.
> 
> So yes, I can confirm that the `mediaItem.requestMetadata.query` is populated when a legacy controller sends a search query via [`MediaControllerCompat.TransportControls.playFromSearch(query)`](https://developer.android.com/reference/kotlin/android/support/v4/media/session/MediaControllerCompat.TransportControls#playFromSearch(java.lang.String,android.os.Bundle)). If that happens you will receive the query.
> 
> You can test this by using the media [controller test app](https://github.com/androidx/media/tree/release/testapps/controller). Install the test app and start playback in your app to make sure there is a session. Then start the test app, choose your app from the list and press the `control` button for your app. Then on the first screen you see a text field: `search` fill in a search query and press 'play'. Then a media item is passed to `onAddMediaItems` with `mediaItem.requestMetadata.query` set according to what you typed in that field.

Thanks @marcbaechinger. Confirmed that my app is getting the search query from the Controller test app in both `onSetMediaItems` and `onAddMediaItems`.

Is the recommendation to assume Google Assistant will work correctly if the input via the controller app is handled correctly?

**Comment by jqi26** [comment]
> Apps that are not providers officially recognized does not really work when using the name even when on Play Store for years.
> 
> You can test by ensuring that you have no media provider configured in Google assistant. Then use your app with a working media session to be the last active app.
> 
> Then just say play some music or play X by Y and the commands will reach your app.

@Tolriq or @lovegaoshi can you clarify what you mean by removing the media provider from Google Assistant? Can you walk me through/point me to how I can do this on a device?

**Comment by marcbaechinger** [comment]
> Is the recommendation to assume Google Assistant will work correctly if the input via the controller app is handled correctly?

Sorry I can't get you a recommendation here due to lack of familiarity with this integration.

**Comment by lovegaoshi** [comment]
https://9to5google.com/2020/10/16/google-assistant-settings-podcast/

**Comment by jqi26** [comment]
Checked and found the providers were already set to default.

Found the issue: we were missing `<action android:name="android.media.action.MEDIA_PLAY_FROM_SEARCH" />` from our app manifest. After adding that, voice commands are reaching the callback as expected.
