### ISSUE TITLE
How to play m3u8 playlist with random video file extensions?

### ISSUE THREAD

**Issue by every-time** [androidx/media#1835]
I have an m3u8 playlist which has random extensions on its video files. They include `js`, `css`, `txt`, etc. The extensions are random but the files are all standard MP4 videos.

Exoplayer actually plays mostly everything correct, but sometimes gets hung up on certain extensions (e.g. `srt` and `php`). For those, looking at Network Inspector in Android Studio, it seems as though the request is never even initiated. I get a Source error, Caused by: androidx.media3.datasource.HttpDataSource$InvalidResponseCodeException: Response code: -1

How can I make this work?

Edit: It works with an `OkHttpDataSource.Factory`, but not with a `DefaultHttpDataSource.Factory`.

**Comment by ozguroktem** [comment]
Did you try setting a mime type? [Here is a reference](https://developer.android.com/media/media3/exoplayer/media-items#handling-non-standard).

**Comment by every-time** [comment]
> Did you try setting a mime type? [Here is a reference](https://developer.android.com/media/media3/exoplayer/media-items#handling-non-standard).

I've set a mime type for the m3u8 playlist that I'm passing to ExoPlayer, but not sure how I can set a mime type for each individual file in the playlist. The files have random extensions and content-type headers, but are just regular mp4 files.

Anyway, OkHttp works while the default HTTP factory does not, and I'm unable to provide files/examples at this time, so I'll be closing this issue.
