### ISSUE TITLE
Video resolution size reduced during transformation

### ISSUE THREAD

**Issue by mikkeloptikos** [androidx/media#1838]
### Version

Media3 main branch

### More version details

// 1.4.1
    implementation(libs.androidx.media3.transformer)
    implementation(libs.androidx.media3.effect)
    implementation(libs.androidx.media3.common)

### Devices that reproduce the issue

Google Pixel 6 Pro

### Devices that do not reproduce the issue

Samsung Galaxy S21 5G

### Reproducible in the demo app?

You do not record in the demo apps

### Reproduction steps

Use MediaRecorder to record video with these configurations
```
private fun createRecorder(surface: Surface): MediaRecorder {
        MediaRecorder(context).apply {
            setVideoSource(MediaRecorder.VideoSource.SURFACE)
            setOutputFormat(MediaRecorder.OutputFormat.MPEG_4)
            setOutputFile(outputFile)
            setVideoEncodingBitRate(10_000_000)
            setVideoFrameRate(30)
            setVideoSize(4000, 3000)
            setVideoEncoder(MediaRecorder.VideoEncoder.H264)
            setInputSurface(surface)
        }
    }

private val inputSurface: Surface by lazy {
        val surface = MediaCodec.createPersistentInputSurface()
        val recorder = createRecorder(surface)
        recorder.prepare()
        recorder.release()
        surface
    }
```

And using the Camera2 API to record the surface

```
suspend fun CameraDevice.newCaptureSession(
    previewSurface: Surface,
    inputSurface: Surface,
) {
       val surfaces = listOf(previewSurface, inputSurface)
        val configs = surfaces.map { OutputConfiguration(it) }

        val executor = Executors.newCachedThreadPool()
        val sessionConfig = SessionConfiguration(
            SessionConfiguration.SESSION_REGULAR,
            configs,
            executor,
            object : CameraCaptureSession.StateCallback() {
                override fun onConfigured(session: CameraCaptureSession) {
                session.setRepeatingRequest(captureRequest, null, handler)
                        val captureRequest = cameraDevice.createCaptureRequest(CameraDevice.TEMPLATE_RECORD).apply {
                             surfaces.forEach { addTarget(it) }
                             set(CaptureRequest.CONTROL_AE_TARGET_FPS_RANGE, Range(30, 30))
                         }.build()
                        mediaRecorder.prepare()
                        mediaRecorder.start()
                       session.setRepeatingRequest(captureRequest, null, handler)
                       // wait 5 seconds
                      session.stopRepeating()
                      mediaRecorder.stop()
                      // output file ready here
                   }

                override fun onConfigureFailed(session: CameraCaptureSession) =
                    cont.resumeWithException(Exception("Configuration failed"))
            },
        )
        createCaptureSession(sessionConfig)
    }
}

```

and use Media3 to transform the video. In my case, I needed to trim the length to 2 seconds:
```
val clippingConfiguration = MediaItem.ClippingConfiguration.Builder()
                .setStartPositionMs(0)
                .setEndPositionMs(2000)
                .build()
            val mediaItem = MediaItem.Builder()
                .setUri(videoUri)
                .setClippingConfiguration(clippingConfiguration)
                .build()
            val transformer = Transformer.Builder(context)
                .setVideoMimeType(MimeTypes.VIDEO_H264)
                .addListener(listener)
                .build()
            transformer.start(mediaItem, outputFile.path)
```

### Expected result

Output video resolution is identical to input video resolution
4000x3000 -> 4000x3000

### Actual result

Output video resolution is NOT identical to input video resolution
4000x3000 -> 2800x2100 (70% reduction)

### Media

Theres nothing particularly interesting about the videos. They look identical, but resolutions are different.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by claincly** [comment]
We do have logic to downsize video streams into an encodable format. You could turn it off by setting `enableFallback` to `false` on `DefaultEncoderFactory`, something like

```
Transformer transformer =
    new Transformer.Builder(/* context= */ this)
        .setEncoderFactory(new DefaultEncoderFactory.Builder(/* context= */ this)
            .setEnableFallback(false)
            .build())
        .build();
```

But note, `4000x3000` encoding is probably not supported widely on phones, so encoder is likely to fail if you turn off encoder fallback.

If possible, please use standard resolutions, like 4k (3840x2160), which are much better supported.

**Comment by mikkeloptikos** [comment]
Oh that's interesting. Why does h264 not support a 4:3 aspect ratio? Any resources on this?

**Comment by claincly** [comment]
H.264 certainly supports 4:3 aspect ratio (as you can see it encodes `2800x2100`), it's the resolution you used is over the range of normally supported resolutions on a phone, which I think is usually 4k.

Also it's worth noting that many encoders require both width and height to be multiples of 16.
