### ISSUE TITLE
exo_play attribute seems not working propery

### ISSUE THREAD

**Issue by masah517** [androidx/media#186]
### Media3 Version

1.0.0-beta02

### Devices that reproduce the issue

Pixexl6 running on Android 12

### Reproducible in the demo app?

Not tested

### Reproduction steps

when overrides the default control panel by using 
"app:controller_layout_id=~"
the play button and pause button seems not working properly by overriding following ids 
"@id/exo_play"
"@id/exo_pause"

### Expected result

The media can play and pause by overriding following layout ids 

"@id/exo_play"
"@id/exo_pause"

### Actual result

The media does not play and pause by overriding following layout ids 

"@id/exo_play"
"@id/exo_pause"

### Media

https://storage.googleapis.com/exoplayer-test-media-0/BigBuckBunny_320x180.mp4

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by masah517** [comment]
@icbaker 
Hi! Thank you for your prompt response.

Let me clarify my question as follows. 


### **My question**

- I am trying to implement a custom player control view layout for my own, by overriding the layout file as advised below
[https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/PlayerControlView.html#:~:text=Overriding%20the%20layout%20file](url)

- Here is the sample project I've set up for demo
https://github.com/masah517/Media3CustomPlayerController

### **Problems**

- The custom play button displayed on the player view is not functioning, and media doesn't get rendered when the play button is pressed 
<img src="https://user-images.githubusercontent.com/79954308/196314532-3e3b2bf3-54c2-4941-a97d-badb51e25576.png" alt="drawing" width="200"/>

- The app layout attribute "show_timeout" is set as below in my sample project, but it seems the timeout duration only affects the views which get overridden, such as Progress bar. The custom view of full screen button does not hide according to the duration of show_timeout.
> app:show_timeout="3000"

- The play button and pause button are overlapped when using the custom player control panel


### **Media3 Version**
1.0.0-beta02


Please let me know if there is any insufficient information. Thank you!

**Comment by icbaker** [comment]
> * I am trying to implement a custom player control view layout for my own, by overriding the layout file as advised below
>   [https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/PlayerControlView.html#:~:text=Overriding%20the%20layout%20file](url)

Ah, I think this might be the issue. I'm afraid it's a bit confusing - when migrating from the `exoplayer2` package to `media3` we kept most of the class names the same, but we did rename a few. Specifically the `PlayerView` and `PlayerControlView` classes were renamed as follows:

`exoplayer2` | `media3`
-------- | --------
`PlayerView` (deprecated) | N/A (doesn't exist)
`PlayerControlView` | `LegacyPlayerControlView`
`StyledPlayerView`   | `PlayerView`
`StyledPlayerControlView`   | `PlayerControlView`

So you're reading the javadoc for `com.google.android.exoplayer2.ui.PlayerControlView` which in media3 is called `androidx.media3.ui.LegacyPlayerControlView`.

I'm afraid we haven't got the media3 javadoc hosted yet, so you'll need to browse it in the source (either in your IDE or here on GitHub) - but you'll see that `androidx.media3.ui.PlayerView` and `androidx.media3.ui.PlayerControlView` don't recommend overriding the layout file, this type of customisation is not supported with these components.

**Comment by icbaker** [comment]
Customising the controller of `androidx.media3.ui.PlayerView` is not supported. `androidx.media3.ui.LegacyPlayerControlView` is not intended to be used with `PlayerView`, it's intended to be used on its own without a `PlayerView`.

The XML customisation of these components that is supported is documented in their javadoc. Anything else may or may not work today, but it's not supported and it may stop working in future versions of the library.

**Comment by masah517** [comment]
Understood. 
Will close this issue, and thanks for your time and response!
