### ISSUE TITLE
Unable to play two DRM-protected medias at the same time

### ISSUE THREAD

**Issue by MGaetan89** [androidx/media#1877]
### Version

Media3 1.4.1

### More version details

I've also tried with ExoPlayer 2.19.1, and Media3 [main branch](https://github.com/androidx/media/tree/4acd1b970c7fdcf47577053f8f371702ca1a9b68).

### Devices that reproduce the issue

- Huawei P40 Lite (JNY-LX1), Android 10, EMUI 12.0.0

### Devices that do not reproduce the issue

- Google Pixel 7 Pro, Android 15 QPR1 Beta

### Reproducible in the demo app?

Yes

### Reproduction steps

See PR #1878

### Expected result

Two DRM-protected media can be played at the same time.

### Actual result

Only the audio of each media is being played. A black screen is displayed instead of each video.

### Media

See PR #1878

### Bug Report

- [x] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment]
I suspect this device doesn't support multiple secure decoders - in which case there's not much ExoPlayer can do to play multiple encrypted streams with hardware-secure decryption.

Depending on the license constraints, you may be able to use L3 software decryption instead - you could try forcing your playbacks to use L3 as shown in this comment: https://github.com/google/ExoPlayer/issues/7790#issuecomment-678473131

See also https://developer.android.com/media/media3/exoplayer/drm#using-a-custom-drmsessionmanager

> * You will email the zip file produced by `adb bugreport` to [android-media-github@google.com](mailto:android-media-github@google.com) after filing this issue.

I can't see the either the `AndroidXMedia3` or `ExoPlayerLib` log lines that are logged when a player instance is prepared. I didn't spot any useful logs in this BR.

Your demo also doesn't attach an `EventLogger` - which would tell you lots about the playback, including whether ExoPlayer thinks both encrypted video tracks are supported or not.

**Comment by MGaetan89** [comment]
Hi @icbaker,

Switching to L3 seems to be working. We'll investigate if this is a viable option for us, or if we will disable that feature in our app on unsupported devices.

FYI: I've added the `EventLogger` to my branch just in case
