### ISSUE TITLE
How to customize the UI of the demo session_automotive app?

### ISSUE THREAD

**Issue by feroxtransmissons** [androidx/media#1883]
It seems that the automotive demo session app does not contain an activity or any layout files to define the UI of the app, instead possibly using some default layout? The layout .xml files in lib-ui do not reflect what the app looks like so it is unclear how this layout is defined. Can somehow tell me how I would go about customizing the UI for this demo automotive app?

Thanks very much. 

https://github.com/androidx/media/tree/release/demos/session_automotive

**Comment by marcbaechinger** [comment]
A media app only provides a service that the Autom,otive app connects with a `MediaBrowser` against. The UI of an Automotive app is provided by the client. You can't customize this.

The documentation around building media apps gives you an idea how the architecture works: https://developer.android.com/training/cars/media/automotive-os

You can start the emulator in Android Studio with an Automotive emulator image to test the Automotive demo app or your own version: https://developer.android.com/training/cars/testing/emulator

**Comment by feroxtransmissons** [comment]
Thanks. We build our own Trout image we test on. 
I am curious then how does Amazon Music, Tidal and Apple Music downloaded from the automotive play store have custom UI's that differ?

**Comment by feroxtransmissons** [comment]
Got it. 
Do you know if I could at least add the Seekbar to this app? I am able to follow the logic in DemoMediaLibrarySessionCallback.kt for adding custom command buttons like Shuffle and Fast Forward, or even custom buttons, but is the Seekbar possible at all? Thank you.

**Comment by feroxtransmissons** [comment]
How can I launch the session_automotive app with 'am start' ?
