### ISSUE TITLE
Need configuration to keep Cookies in Chunkloading

### ISSUE THREAD

**Issue by JaroslavHerber** [androidx/media#1903]
Hello devs,

I have this case:
1. I'm loading a channel-URL from cloudfront CDN.
2. It has a redirect. In the redirection response there is a "Set-Cookie" header.
3. The manifest is loaded correctly. ExoPlayer tries to load the (mp4) chunks next.
4. For chunk loading, the cloudfront CDN needs the Cookie in the Request-Header (from Response - see no. 2)
5. Because ExoPlayer ignored the Cookie, cloudfront returns status code "403 - Permission Denied" in the Chunkloading request

Is there a possibility to read the "Set-Cookie" header from `DefaultHttpDataSource.makeConnection()` and set it as "Cookie" header for example in `DefaultDashChunkSource.newInitializationChunk()` ?

Do you guys have a tipp how to accomplish this?

**Comment by JaroslavHerber** [comment]
This case is not new: https://github.com/google/ExoPlayer/issues/4870

**Comment by marcbaechinger** [comment]
Does this work with another network stack? Like CroNet or OkHttp?

https://developer.android.com/media/media3/exoplayer/network-stacks#supported-network

**Comment by JaroslavHerber** [comment]
Tried also with CroNet, but it does not work either.
Added also `setHandleSetCookieRequests(true)`

Got this error:
```
internalError [eventTime=16.46, mediaPos=7167.16, window=0, period=8, loadError
androidx.media3.datasource.HttpDataSource$InvalidResponseCodeException: Response code: 403
  at androidx.media3.datasource.cronet.CronetDataSource.open(CronetDataSource.java:647)
  at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
  at androidx.media3.exoplayer.source.chunk.InitializationChunk.load(InitializationChunk.java:103)
  at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:450)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
  at java.lang.Thread.run(Thread.java:1012)
```

But I managed to hack it with a TransferListener in DefaultHttpDataSource:

```
TransferListener oTransferListener = new TransferListener() {
    @Override
    public void onTransferStart(DataSource source, DataSpec dataSpec, boolean isNetwork) {
        if( !dataSpec.httpRequestHeaders.isEmpty() ) {
            // CUSTOM hack: Cookie was added in DefaultHttpDataSource.open()
            String sCookie = dataSpec.httpRequestHeaders.get("Cookie");
            if( sCookie != null ) {
                Map<String, String> aHeadersMap = new HashMap<>();
                aHeadersMap.put("Cookie", sCookie);
                oHttpDataSourceFactory.setDefaultRequestProperties(aHeadersMap);
            }
        }
    }
    ...
};

HttpDataSource.Factory oHttpDataSourceFactory = new DefaultHttpDataSource.Factory()
    .setKeepPostFor302Redirects(true)
    .setAllowCrossProtocolRedirects(true)
    .setTransferListener(oTransferListener);
```

And hack in DefaultHttpDataSource.java
```
  public String sM3uIptvCookieHeader = "";
  
  public long open(DataSpec dataSpec) throws HttpDataSourceException {
    this.dataSpec = dataSpec;
    bytesRead = 0;
    bytesToRead = 0;
    transferInitializing(dataSpec);

    // CUSTOM hack: set Cookie header from previous redirect and catch it in TransferListener.onTransferStart()
    if( !this.sM3uIptvCookieHeader.isEmpty() ) {
      Map<String, String> aHeadersMap = new HashMap<>();
      aHeadersMap.put("Cookie", this.sM3uIptvCookieHeader);
      dataSpec = dataSpec.withAdditionalHeaders(aHeadersMap);
    }
    
    String responseMessage;
    HttpURLConnection connection;
    try {
      this.connection = makeConnection(dataSpec);
      connection = this.connection;
      responseCode = connection.getResponseCode();
      responseMessage = connection.getResponseMessage();
    } catch (IOException e) {
      closeConnectionQuietly();
      throw HttpDataSourceException.createForIOException(
          e, dataSpec, HttpDataSourceException.TYPE_OPEN);
    }

    // CUSTOM hack - save Cookie header to be used after redirect
    if( connection.getHeaderField("Set-Cookie") != null ) {
      this.sM3uIptvCookieHeader = connection.getHeaderField("Set-Cookie");
    }
    ...
}
```

**Comment by marcbaechinger** [comment]
Thanks for your patience. 

I understand the `Set-Cookie` interaction you describe above is a normal cookie interaction based on the cookies spec. Please correct me if I'm wrong with that and this is about a specific customization required for your cloudfront integration. I think that would mean that the redirect goes to a host or domain that is eligible for recieving the cookie according to that spec..

If this is about Cookies only (as the `Set-Cookies`, `Cookie` approach above makes me think it is), then you need to configure the network stack you are using accordingly. ExoPlayer doesn't do cookies.

The `DefaultHttpDataSource` is implicitly using the configuration of the system as it uses an URl connection. So this can be configured with setting the system cookie manager. The demo app does this [here](https://github.com/androidx/media/blob/release/demos/main/src/main/java/androidx/media3/demo/main/DemoUtil.java#L113-L117) in case cronet and okhttp is not available.

CroNet and OkHttp support this with their default config I assume. Else, there is this SOF post that seems helpful for OkHtttp at least: https://stackoverflow.com/questions/34881775/automatic-cookie-handling-with-okhttp-3.

If this is a specific customization used for cloudfront that is out of a normal spec, then I think I'd look into [`ResolvingDataSource`](https://developer.android.com/reference/androidx/media3/datasource/ResolvingDataSource) which allows to receive the original `DataSpec` that should be used and to map that to another `DataSpec` that in that case has addition request HTTP headers set. I'd be suprise if this is needed though as it looks like a burden to integrate with cloudfront. But I'm not well informed about such things.
