### ISSUE TITLE
Transport stream H264 video track not playable due to keyframes not being detected

### ISSUE THREAD

**Issue by spiricn** [androidx/media#1907]
### Version

Media3 main branch

### More version details

Video track does not seem to be playable. Upon further investigation, it seems to be related to key frames. 

Specifically the `H264Reader` never seems to detect a keyframe, and for that reason no frames are actually submitted to the decoder for decoding.

Looking at the `H264Reader#setSampleIsKeyframe` function call I can see that plenty of `NAL_UNIT_TYPE_NON_IDR` frames seem to be read; however both `allowNonIdrKeyframes` and `randomAccessIndicator` flags seem to always be `false` resulting in none of the frames being marked as key frame.

I've experimented a bit, and removed the logic which waits for a keyframe and the video plays just fine with seemingly no artifacts.

### Devices that reproduce the issue

Samsung S23

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Play attached media

### Expected result

Media plays with video and audio

### Actual result

Only audio plays, even though video track is detected

### Media

https://hospitality-dev.codemeup.net/images/spiric-test/224.0.181.12_1510.ts

### Bug Report

- [x] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment]
> however both `allowNonIdrKeyframes` and `randomAccessIndicator` flags seem to always be `false` resulting in none of the frames being marked as key frame.

You can set `FLAG_ALLOW_NON_IDR_KEYFRAMES` yourself: https://developer.android.com/media/media3/exoplayer/troubleshooting#why-do-some-mpeg-ts-files-fail-to-play
