### ISSUE TITLE
Transport stream H264 video track not playable due to missing AUD NAL units

### ISSUE THREAD

**Issue by spiricn** [androidx/media#1908]
### Version

Media3 main branch

### More version details

Video track produces no frames for decoding.

Upon deeper investigation of `H264Reader#endNalUnit` it seems that `outputSample` branch is never executed.

The stream does not contain any AUD NAL units, and neither is `detectAccessUnits` set to true.

The NAL units in the stream are as follows:

SPS -> PPS -> SEI -> IDR -> NON_IDR -> NON_IDR  etc.

### Devices that reproduce the issue

Galaxy Samsung S23

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Play attached media

### Expected result

Both audio and video plays correctly

### Actual result

Only audio plays, without video ; even though video track is detected

### Media

https://hospitality-dev.codemeup.net/images/spiric-test/224.0.121.4_1510.ts

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment]
> The stream does not contain any AUD NAL units, and neither is `detectAccessUnits` set to true.

You can set `FLAG_DETECT_ACCESS_UNITS` for this: https://developer.android.com/media/media3/exoplayer/troubleshooting#why-do-some-mpeg-ts-files-fail-to-play
