### ISSUE TITLE
Documentation for MediaLibraryService(), MediaSessionService, MediaLibrarySession.Callback, MediaSession.Callback

### ISSUE THREAD

**Issue by pawaom** [androidx/media#191]
Where can we find proper Documentation for MediaLibraryService(), MediaSessionService, MediaLibrarySession.Callback, MediaSession.Callback

When I checked the media3 documentation on developer.android.com I could not find any documentation

all I found was the old documentation about MediaBrowserService 

https://developer.android.com/guide/topics/media/media-controls

https://developer.android.com/guide/topics/media/media-controls#mediabrowserservice_implementation

and this
https://developer.android.com/guide/topics/media/media3/getting-started/mediasession

after going through the sample app and UAMP media3 example we can see we need to implement  MediaLibrarySession.Callback and need to override various methods like onConnect , onPostConnect ,  onCustomCommand ,  onGetLibraryRoot, onGetItem, onSubscribe, onGetChildren, onAddMediaItems, getMediaItemFromSearchQuery

We need proper documentation for these methods, we have to dig deep into android code to find any info, we only find info about  onConnect , onCustomCommand  however proper documentation will be helpful like how to use onGetLibraryRoot, onGetItem etc

**also we need documentation about how to use media3 with various google products like google assistant, google auto, Automative OS, wear OS and how we can test these features.**

**Comment by pawaom** [comment]
I am new to using media session and I am learning by comparing old UAMP code and new UAMP-- media3/compose code

earlier we need to override onGetRoot() and onLoadChildren() which was required to be Called to get information about the children of a media item , in MediaBrowserServiceCompat() , 

now there is no need to do this?

what are the corresponding methods we need to override?

Suppose if we dont override these methods still can, ---> other apps mediabrowser/mediacontroller can communicate with our service like say wear OS, google assitant etc ? --> or do we need to override other methods

**Comment by marcbaechinger** [comment]
If you are familiar with the old API then you can look into the [migration guide](https://developer.android.com/guide/topics/media/media3/getting-started/migration-guide).

There is a section answering your question about [overrdiing domain methods of the service](https://developer.android.com/guide/topics/media/media3/getting-started/migration-guide#MediaBrowserService).

**Comment by pawaom** [comment]
I came across this for  mediabrowserservicecompat 

https://medium.com/androiddevelopers/mediabrowserservicecompat-and-the-modern-media-playback-app-7959a5196d90

can we have similar blog post for  MediaLibraryService
