### ISSUE TITLE
ExoPlayer DRM Native code and DRM decryption code

### ISSUE THREAD

**Issue by rdutta2020** [androidx/media#1913]
I have two questions :

1. I would like to browse source code related to DRM decryption (e.g. Widevine) in exoplayer. In which file those code will be present ?
2. Where can I find source code for native code (cpp, c files) ?

**Comment by icbaker** [comment]
ExoPlayer doesn't have any code directly related to the decryption logic for conventional DRM playback. This is handled by the framework implementation of `MediaDrm` and the logic underneath that. You can see the [clearkey decryption code in AOSP](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/av/drm/mediadrm/plugins/clearkey/common/include/clearkeydrm/). I don't believe the Widevine source code is published.
