### ISSUE TITLE
Rtmp datasource support 16kb page size

### ISSUE THREAD

**Issue by youtengli** [androidx/media#1918]
Hello:

### [REQUIRED] Use case description
I am using exoplayer to play rtmp url and checking 16kb page size support on my app.
`implementation "androidx.media3:media3-datasource-rtmp:1.5.0"`
According to [google developer page]( https://developer.android.com/guide/practices/page-sizes):
`librtmp-jni.so` is LOAD align `2**12`

**Comment by rohitjoins** [comment]
Hi @youtengli,

Thank you for reporting this issue!

The `media3-datasource-rtmp` module doesn’t directly include native code. Instead, it relies on [LibRtmp-Client-for-Android](https://github.com/ant-media/LibRtmp-Client-for-Android). You would want to report this issue directly to that repository, as they maintain the native library (librtmp-jni.so).

Let us know if you have any other questions or need further assistance!

**Comment by rohitjoins** [comment]
Please let us know when the client is updated to support 16KB page size and we can update the client version in Media3 `datasource_rtmp` module.
