### ISSUE TITLE
Notification play/pause button doesn't match player state

### ISSUE THREAD

**Issue by JaCobbMedia** [androidx/media#192]
### Media3 Version

1.0.0-beta02

### Devices that reproduce the issue

- Pixel 5 (Android 13)
- Samsung Galaxy S21 Ultra (Android 12)

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Start demo-session app
2. Play any item (was easiest to reproduce on  "Mango Open Movie project")
3. Click on play/pause button
4. It doesn't happen often so you might need to click it multiple times

I could reproduce this issue even with my custom `MediaNotificationProvider` which chooses play/pause button icon by `playWhenReady` flag.

### Expected result

Play/pause notification button should match current player state

### Actual result

Play/pause notification button doesn't match player state (player is paused but notification shows pause button, should show play button)

### Media

Album folder -> Mango Open Movie project -> Future Scenario

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tianyif** [comment]
Fixed in e1d12fc395d9f9edb28755a5b1026e26b378e005.
