### ISSUE TITLE
Composition of Images and Videos for final video

### ISSUE THREAD

**Issue by muhammad-najam-cmp** [androidx/media#1921]
I'm getting an issue to compose images and videos for final output.

        val transformer = remember {
            Transformer.Builder(context).setVideoMimeType(MimeTypes.VIDEO_H264)
                .setAudioMimeType(MimeTypes.AUDIO_AAC)
                .build()
        }
        
            val filteredSelectionModels = selectedFiles.filter { it.uriString.isNotEmpty() }

            val videos = filteredSelectionModels.mapIndexed { _, selectedFile ->
                val videoEffects = arrayListOf<Effect>()
                videoEffects.add(
                    Presentation.createForWidthAndHeight(outputWidth, outputHeight, presentationType)
                )
                if (selectedFile.fileType == "Video") {
                    val startTime = (selectedFile.uriStartTime * 1000).toLong()
                    val endTime = (selectedFile.uriStartTime * 1000 +5000 ?: 5000).toLong()
                    val fpsValue = uiStateViewModel?.fpsValue?.value?.toFloat()
                    log(fpsValue.toString())
                    videoEffects.add(
                        FrameDropEffect.createDefaultFrameDropEffect(
                            fpsValue ?: 30f
                        )
                    )
                    EditedMediaItem.Builder(
                        MediaItem.Builder().apply {
                            setUri(selectedFile.uriString).setClippingConfiguration(
                                MediaItem.ClippingConfiguration.Builder().setStartPositionMs(startTime)
                                    .setEndPositionMs(endTime).build()
                            )
                        }.build()
                    ).setRemoveAudio(selectedFile.enableOriginalAudio).setEffects(Effects(listOf(), videoEffects)).build()
                } else {
                    val imageDurationUs = (selectedFile.uriDuration * 1000 * 1000).toLong()
                    log(selectedFile.uriDuration.toString() +" "+ selectedFile.uriString)
                    EditedMediaItem.Builder(
                        MediaItem.Builder().apply {
                            setUri(selectedFile.uriString)
                        }.build()
                    ).setDurationUs(imageDurationUs).build()
           
                }
            }
            
            currently I've following implementation. Its working fine with when only input files are videos but failed for images asking to add ImageAssetLoader. I'm not getting proper implementation for adding ImageAssetLoader to the transformer or .
            
            I required proper implementation for composing both images and videos.

**Comment by droid-girl** [comment]
@muhammad-najam-cmp I looked at your code and you need to set frameRate when you create `EditedMediaItem` for images

` editedMediaItemBuilder.setFrameRate(IMAGE_FRAME_RATE_FPS);`

Could you try it?

There is also one limitation in the APIs currently that you should be aware of, if the first item is image, you need to force audio track when building `Composition`:
`compositionBuilder.experimentalSetForceAudioTrack(true)`

**Comment by muhammad-najam-cmp** [comment]
Thanks these changes help me out,
but strange documentation sand my initial searches talks about 'ImageAssetLoader', that should be handled at library side.
