### ISSUE TITLE
multiple instances of playerview and MediaController in different activities for same service, like the mediasessions demo

### ISSUE THREAD

**Issue by pawaom** [androidx/media#193]
multiple instances of playerview in different activities

We are planning to have a Player Activity and  a common player fragment 

While the player activity, will be a separate activity with its own , playerview ,as provided in the mediasessions demo 

we also want to have a common palyerfragment which can act as a mini player which is the common pattern accross music apps, which we can include in various activities. 

the question is can we have different instances of player view and MediaController in this player activity and player fragment.

Also I am confused regarding the pattern we need to follow, while the mediasessions demo directly calls the playerview and MediaController  in player activity and calls the MediaBrowser in the PlayableFolderActivity , where as the UAMP has a MusicServiceConnection -->   that manages a connection to a [MediaLibraryService] instance, in the musicservice class, 

So do we need to have a MusicServiceConnection class or as is mentioned in this video 

https://www.youtube.com/watch?v=sTIBDcyCmCg&t=480s 

which mentions  mediacontroller is a player implementation, we can direclty pass it to the playerview

**Comment by marcbaechinger** [comment]
In general I would only create a single controller at a time which can be passed to multiple UI elements at the same time if this is required. The state of the controller always reflects the state of the session, so the state of multple controllers area always the same. There is no point in having more then one instances from that point of view. 

There are no design constraints in how you design you app that is using a media `MediaLibraryService`. The demo app and UAMP that you mention have chosen a different design. There is no need for you to follow on or the other as you can pick whatever suits your app and use cases best.
