### ISSUE TITLE
when to use Mediasessionservice and medialibraryservice and which librarycallbacks should we use

### ISSUE THREAD

**Issue by pawaom** [androidx/media#194]
when to use Mediasessionservice and medialibraryservice

According to this video 

https://youtu.be/sTIBDcyCmCg?t=749

We can use mediasessionservice for exposing mediasession

and medialibraryservice for exposing medialibrary

so when using mediasessionservice allows other apps to control playback-(does this automatically support android auto, do we need to develop a seprate ui for wearos and auto.)

while medialibraryservice needs a content library (the video says medialibraryservice supports android auto which provides its own driver safe UI ) --> should we follow the MediaItemTree --> structure provided in the demo app or we can have our own structure like just providing an array obtained by Cursor for the getContentResolver().

and the most important thing is which callbacks should we implement--> for browsing the library and for the new feature of playback resumption.

**Comment by marcbaechinger** [comment]
For Android Auto you need a `MediaLibraryService` and implement the `MediaLibrarySession.Callback`.
It's totally up to you how you implement the domain methods of the callback. The `MediaItemTree` is how the demo app is doing it, you will likely use another approach that reads from a database. 

The UI of Android AUto is provided by Automotive OS/Android Auto. You only need to provide the `MediaLibraryService` that is exposed to other apps.

Please also look into the migration guide for [`MediaBrowserServiceCompat`](https://developer.android.com/guide/topics/media/media3/getting-started/migration-guide#MediaBrowserService).
