### ISSUE TITLE
Build failed on version 1.5.0

### ISSUE THREAD

**Issue by ponthamaya** [androidx/media#1942]
> Task :lib-transformer:mergeReleaseShaders 
> Task :lib-transformer:compileReleaseShaders NO-SOURCE 
> Task :lib-transformer:generateReleaseAssets UP-TO-DATE 
> Task :lib-transformer:packageReleaseAssets 
> Task :lib-transformer:generateReleaseRFile 
> Task :lib-transformer:prepareLintJarForPublish 
> Task :lib-transformer:extractReleaseAnnotations 
warning: unknown enum constant When.MAYBE 
  reason: class file for javax.annotation.meta.When not found 
warning: unknown enum constant Level.FULL 
  reason: class file for com.google.j2objc.annotations.ReflectionSupport$Level not found 
> Task :lib-transformer:compileReleaseJavaWithJavac FAILED 
/home/runner/work/media/media/media/**libraries/transformer/src/main/java/androidx/media3/transformer/SequenceRenderersFactory.java:286: error: incompatible types: VideoSink cannot be converted to boolean 
          videoSink); 
          ^**
Note: Some input files use or override a deprecated API. 
Note: Recompile with -Xlint:deprecation for details. 
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output 
1 error 
2 warnings 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':lib-transformer:compileReleaseJavaWithJavac'. 
644 actionable tasks: 644 executed

**Comment by rohitjoins** [comment]
Hi @ponthamaya,

I checked out the release branch, which is currently at version `1.5.0` (latest release), and I didn't encounter any build failures. Could you let me know which git commit you're currently checked out at? That might help in understanding the issue better.

Thanks!

**Comment by kim-vde** [comment]
Are you using the same version for lib-transformer and lib-exoplayer?
