### ISSUE TITLE
[CMCD] DefautDataSource doesn't add headers on master playlist requests

### ISSUE THREAD

**Issue by AlexStankevic** [androidx/media#1951]
### Version

Media3 1.4.1

### More version details

DefautDataSource doesn't add headers on master playlist requests

### Devices that reproduce the issue

reproduced on Google Pixel 6 Pro

### Devices that do not reproduce the issue

no device

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. Add cmcd headers into CMCDConfiguration factory, add it into Datasource 

```
val cmcdConfigurationFactory = CmcdConfiguration.Factory { mediaItem ->
        val cmcdRequestConfig = CmcdConfiguration(
            /* sessionId=*/  UUID.randomUUID().toString() 
            /* contentId= */ UUID.randomUUID().toString() ,
            object : CmcdConfiguration.RequestConfig {})
```
`mediaSourceFactory.setCmcdConfigurationFactory(cmcdConfigurationFactory)`

2. Run any HLS stream 

3. Headers is presents during ts requests, but not presents during m3u8 requests   

### Expected result

cmcd headers presents in m3u8 requests

### Actual result

No cmcd headers in m3u8 requests

### Media

https://devstreaming-cdn.apple.com/videos/streaming/examples/adv_dv_atmos/main.m3u8
But can be uses any hls stream

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by rohitjoins** [comment]
Hi @AlexStankevic,

Thank you for bringing this to our attention. We’ve implemented a [fix]( https://github.com/androidx/media/commit/8d2f531470d7437d8ddf01b8fca196d1106a8cdb)  to enable CMCD data on playlist requests.
