### ISSUE TITLE
Video size is broken after migrating from 1.4.1 to 1.5.0

### ISSUE THREAD

**Issue by Raenar4k** [androidx/media#1955]
### Version

Media3 main branch

### Devices that reproduce the issue

Pixel 9 pro 14 android

### Reproducible in the demo app?

Not tested

### Reproduction steps

Video link: https://static.brighty.app/onboarding/exchange.mp4

We use Exoplayer in Compose screen through AndroidView:
```Kotlin
    AndroidView(
        factory = { context ->
            PlayerView(context).apply {
                this.useController = false
                this.player = player
                this.resizeMode = AspectRatioFrameLayout.RESIZE_MODE_FIT
            }
        },
        modifier = Modifier.fillMaxSize()
            .background(color = Theme.colors.positive)
    )
```

Version 1.5.0:
https://github.com/user-attachments/assets/631fe91c-3270-49f6-af81-853634244304

Version 1.4.1
https://github.com/user-attachments/assets/1ed92af4-f9b4-4b17-9991-23dde79c9068

### Expected result

Size of resulting video should not change

### Actual result

Size of video has changed

### Media

https://static.brighty.app/onboarding/exchange.mp4

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment]
Have you enabled to [Compose-specific workaround](https://developer.android.com/reference/androidx/media3/ui/PlayerView#setEnableComposeSurfaceSyncWorkaround(boolean)) for `PlayerView` as described in the [1.5.0 release notes](https://github.com/androidx/media/blob/release/RELEASENOTES.md#150-2024-11-27)?

See also https://github.com/androidx/media/issues/1594

**Comment by anton-begeima-okcupid** [comment]
I am seeing the same issue with the compose workaround enabled
```
AndroidView(
            modifier = Modifier.fillMaxSize(),
            factory = {
                PlayerView(context).apply {
                    player = exoPlayer
                    resizeMode = AspectRatioFrameLayout.RESIZE_MODE_ZOOM
                    useController = false
                    setEnableComposeSurfaceSyncWorkaround(true)
                    FrameLayout.LayoutParams(
                        ViewGroup.LayoutParams.MATCH_PARENT,
                        ViewGroup.LayoutParams.MATCH_PARENT
                    )
                }
            }
        )
```

**Comment by icbaker** [comment]
@anton-begeima-okcupid Interesting - what do you observe on 1.4.1 (where the workaround should be enabled by default, and that method doesn't exist)? That will help us understand whether the workaround in general isn't working for you, or whether there's something wrong with the way we're toggling it in 1.5.0.

**Comment by anton-begeima-okcupid** [comment]
On 1.4.1 the video displayed correctly but on 1.5.0 is stretched width-wise. here is the video from Pixel 7 Android 15.

https://github.com/user-attachments/assets/af1fb20c-bac7-4d30-97e1-3853fcbc1a0b


https://github.com/user-attachments/assets/1ce27778-ea00-4391-8783-9c0da2f5efdf

**Comment by icbaker** [comment]
The repro case we were provided with in https://github.com/androidx/media/issues/1237 works with the workaround on Android 14 and media3 1.5.0, and doesn't work without the workaround (I just checked).

@anton-begeima-okcupid Please can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally? Without this I don't think we can investigate further.

This could be an Android Studio project zipped up and sent to android-media-github@google.com  with the subject "Issue #1234". If emailing please also update this issue to indicate you’ve done this.

**Comment by anton-begeima-okcupid** [comment]
I sent the email with the minimal reproducible example attached. I reproduced the issue on the emulator Pixel 8a API 35. The file was a little too big for the email so I added the Google Drive link and granted permissions to the android-media-github@google.com. Let me know if it works, if not maybe I can just create a public repo.

**Comment by dsparano** [comment]
This seems an issue with the Pixel phones, rather than an issue with the 1.5.0 code. 

On a Pixel 4a I can see that the device provides a `mediaFormat` in `MediaCodecVideoRenderer::onOutputFormatChanged()` with `sar-width` and `sar-height` wrongly set to 1 (a surviving default assignment?) while they should be 360:427 as signalled in exchange.mp4 both in SPS VUI and in pasp. I've checked other devices and they simply do not carry the sar in `mediaFormat`.

One way to resolve it could be a Pixel workaround gating the block at https://github.com/androidx/media/blob/cc8439db93f256d2c5820b38ce9ffac9154a1203/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/video/MediaCodecVideoRenderer.java#L1366, changed in [#PR1371](https://github.com/androidx/media/pull/1371). While a real case of sar!=1 from stream and sar=1 after post-processing would still fail on a Pixel phone it seems to us still an improvement on both 1.4.1 and 1.5.0.

We, as contributors of [#PR1371](https://github.com/androidx/media/pull/1371), are willing to provide such a PR, please @icbaker let us know.

**Comment by icbaker** [comment]
There's also more info/analysis of this same issue in internal b/378713448.

**Comment by dsparano** [comment]
Hi Ian,

Thanks for the heads up, but how can I access your internal bug tracker?

Best,
Daniele


This email and any attachments are sent in strictest confidence for the sole use of the addressee and may contain legally privileged, confidential, proprietary and personal data. If you are not the intended recipient, please advise the sender by replying promptly to this email and then delete and destroy this email and any attachments without any further use, copying or forwarding.

For more information on how we use and protect your information, please review our Privacy Policy here<https://www.v-nova.com/privacy-policy/>

Please consider your environmental responsibility before printing this e-mail

**Comment by icbaker** [comment]
@dsparano You cannot. This note is for us in the future to more easily follow the breadcrumbs from GitHub back to our internal issue tracker.
