### ISSUE TITLE
MediaService is keeping app process alive

### ISSUE THREAD

**Issue by WSteverink** [androidx/media#1956]
### Summary
During some testing, I encountered the following situation and am uncertain if this is expected behavior or a potential bug.

**Scenario 1**

If I remove my app from the recent apps list without playing anything, the app and its process seem to be properly destroyed. I can confirm this because Logcat shows that the process has ended:

`PROCESS ENDED (30547) for package androidx.media3.demo.session`

And I can see that all memory gets cleared instantly in the Android Studio profiler.
        
![Screenshot 2024-12-06 at 10 36 47](https://github.com/user-attachments/assets/56eb1351-daf9-4b05-af84-169a91a89128)

**Scenario 2**     

If I am playing something and remove the app from the recent apps list, I have noticed something different.
When playing something and then removing the app from recents, I encountered the following:

- The onTaskRemoved and onDestroy methods from the service are called, and playback stops as expected.
- However, the app process is not terminated.

I can verify this by checking the Android Studio profiler, LogCat, and the fact that the "Force Stop" option remains available for the app in Android settings.
        
![Screenshot 2024-12-06 at 10 33 16](https://github.com/user-attachments/assets/21dd050a-bfc6-4c0d-a802-76630e0ad7f6)

### Reproduce

To reproduce scenario 2 in the Media3 app (latest main branch, running the demo-session), I made the following changes:

**Code**
```kotlin
@OptIn(UnstableApi::class)
override fun onTaskRemoved(rootIntent: Intent?) {
  Log.d("[DEBUG]", "onTaskRemoved: ") // <---------------

  super.onTaskRemoved(rootIntent)
  pauseAllPlayersAndStopSelf() // <---------------
}

// MediaSession.setSessionActivity
// MediaSessionService.clearListener
@OptIn(UnstableApi::class)
override fun onDestroy() {
  Log.d("[DEBUG]", "onDestroy: ") // <---------------

  getBackStackedActivity()?.let { mediaLibrarySession.setSessionActivity(it) }
  mediaLibrarySession.release()
  mediaLibrarySession.player.release()
  clearListener()
  super.onDestroy()
}
```
       

### Question

I am wondering if this behavior is by design—perhaps an inherent Android OS behavior—or if it could be a bug.

In our case, we want to ensure that some resources are removed or cleaned up immediately after the app is swiped away.

It’s a bit of a long shot, but I look forward to your response so we can take the appropriate action. Thanks in advance!

**Comment by marcbaechinger** [comment]
> I am wondering if this behavior is by design—perhaps an inherent Android OS behavior—or if it could be a bug.

The system doesn't kill the process immediately if there is not reason for that. If you create memory pressure, it would kill the process and the memory be reclaimed.

Similarly, I see sometimes that the service that is in the background waiting for being killed by the system isn't killed but then as soon as I start another app like Gmail on that phone the service is terminated (which doesn't mean the process is terminated also).

In the case that you describe, if you start the app again, the process is reused to launch the activity or service that is started.

**Comment by WSteverink** [comment]
> > I am wondering if this behavior is by design—perhaps an inherent Android OS behavior—or if it could be a bug.
> 
> The system doesn't kill the process immediately if there is not reason for that. If you create memory pressure, it would kill the process and the memory be reclaimed.
> 
> Similarly, I see sometimes that the service that is in the background waiting for being killed by the system isn't killed but then as soon as I start another app like Gmail on that phone the service is terminated (which doesn't mean the process is terminated also).
> 
> In the case that you describe, if you start the app again, the process is reused to launch the activity or service that is started.

Check, so this is by design and basically not something we control. We need to figure out another approach for our bug. Thanks for the quick response!

**Comment by marcbaechinger** [comment]
> In our case, we want to ensure that some resources are removed or cleaned up immediately after the app is swiped away.

Sorry, I haven't read that. I think you can't do more then releasing and cleaning up everything in `onDestroy()` of the service.

**Comment by marcbaechinger** [comment]
Closing this as it seems answered so far. Thanks for your question!
