### ISSUE TITLE
Adjusting output bitrate using the Media Transformer API

### ISSUE THREAD

**Issue by bluesky2319** [androidx/media#1957]
I didn't see any option for adjusting the bitrate in the Transformer demo. I'd like to know if there is any way to set the output bitrate while transcoding video. If so, could you please guide me on how we can achieve it?

Also, how can I retrieve the bitrate from the input video while using Media Transformer? Thank you.

**Comment by droid-girl** [comment]
Hi @bluesky2319 ,
To be able to adjust bitrate you can use VideoEncoderSetting , please check [this comment](https://github.com/androidx/media/issues/1304#issuecomment-2124324237) and #1154 for more details

```
new DefaultEncoderFactory.Builder(context)
                    .setRequestedVideoEncoderSettings(
                        new VideoEncoderSettings.Builder()
                            .setBitrate(bitrate)
                            .build()) 
```

**Comment by bluesky2319** [comment]
Thank you for your reply. Regarding retrieving the bitrate from the input video, is there any way to achieve this?
