### ISSUE TITLE
retrieve the bitrate from the input video while using Media Transformer

### ISSUE THREAD

**Issue by bluesky2319** [androidx/media#1959]
Is there any way to retrieve the bitrate from the input video while using Media Transformer? If so, could you please provide a hint? Thank you.

**Comment by bluesky2319** [comment]
@SheenaChhabra Hello, could you please give me a hint on how to resolve my problem? Thank you.

**Comment by SheenaChhabra** [comment]
@bluesky2319 You can try using [MetadataRetriever](https://github.com/androidx/media/blob/df887a942222914836081f868067960eb0149547/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/MetadataRetriever.java#L74) to retrieve the `Format` object for audio/video stream. The `Format` object will have the `bitrate` field set if the information was available in the input file.

**Comment by droid-girl** [comment]
Closing this issue, please reopen if you have any follow up questions

**Comment by bluesky2319** [comment]
@SheenaChhabra Thank you for your help.
