### ISSUE TITLE
Video is stuck in buffering when the video file is broken in one case

### ISSUE THREAD

**Issue by kevinguitar** [androidx/media#196]
### Media3 Version

1.0.0-beta02

### Devices that reproduce the issue

Reproducible on various devices.

### Devices that do not reproduce the issue

none

### Reproducible in the demo app?

Not tested

### Reproduction steps

Simply play the video file that I attached

Here are a few observations on this broken video file, hope it will be useful

The file has few out-of-accepted rules (these are the list of dimensions and frame rates that are supported with most of the codecs):
- it is frame rate is ~0.2, which gives frame_rate = 1 or 0 depending on the concrete media extractor implementation, it can be an issue that slows buffering and playback, but is not a fatal one
- the fatal thing the recorder program did, is its final frame has timestamp - 0, encoding/multiplexing libraries usually make checks on such broken sequences and don't allow putting a frame with a higher timestamp than the previous one had. This problem can make the buggering process eternal.

### Expected result

The player is stuck in buffering state forever

### Actual result

I expect a proper exception, at least to be clear that the player cannot process this video file.

### Media

Video file:
https://bandlabvideo.azureedge.net/public/491a77f9-fd5c-40fa-a9a7-a201bbac6a26/original.mp4

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
ExoPlayer is a playback library, not a media validation library - in general it's written on the assumption that the provided media is valid. Where possible we aim to have clear failures and error messages, but I'm afraid it's not always a good use of our time (or bytes of code) to add explicit error handling for every possible way that media could be invalid.

If you play invalid media (which it sounds like this is) with this library then the result is [undefined behaviour](https://en.wikipedia.org/wiki/Undefined_behavior) - which can include buffering forever.

**Comment by kevinguitar** [comment]
@icbaker  Thanks for your reply. I wanted to add one more thing, although this file is problematic, we checked it on Quick time/ Chrome and iOS player, and they all played it fine, I'm wondering if it's worth looking into the case?

**Comment by icbaker** [comment]
I'm afraid the fact that other players work around invalid media isn't evidence that the media is valid or should be playable by all other players.

I'm going to close this because we don't plan to change anything about ExoPlayer's behaviour here.
