### ISSUE TITLE
Please support Ongoing Activity API on wear.

### ISSUE THREAD

**Issue by Digipom** [androidx/media#1975]
### [REQUIRED] Use case description
We want to be able to customize the default ongoing activity.

### Proposed solution
It should be possible to provide a hook to the NotificationCompat.Builder() so we can call OngoingActivity APIs. See: https://developer.android.com/training/wearables/notifications/ongoing-activity

### Alternatives considered
It's only currently possible if all default notification handling is completely replaced, which is not ideal. `OngoingActivity.recoverOngoingActivity(context)` doesn't work with the system-provided ongoing activity.

**Comment by marcbaechinger** [comment]
Thanks for reporting!

> It should be possible to provide a hook to the NotificationCompat.Builder() so we can call OngoingActivity APIs.

From the docs you only need to call 

```
.setSmallIcon(..)
 .setOngoing(true)
```

on APIs that Media3 hides internally. Is this correct? The other APIs are Wear specific and we are not obscuring these or something if I understand correctly.

You can already call `DefaultMediaNotificationProvider.setSmallIcon(resId)`.

So all you need is a setter to set the `ongoing` flage to true or false to your liking.

Can you please confirm whether this is correct, or then let us know what else you would need.

**Comment by Digipom** [comment]
@marcbaechinger It seems that the ongoing activity builder needs the NotificationCompat.Builder and I also have to create the ongoing activity *before* NotificationCompat.Builder.build(). I can do this if I replace all of media3's notification stuff with my own, but I'd rather just leverage media3.

**Comment by marcbaechinger** [comment]
Ah, yeah, I see how the builder is passed into the activity.

I think we should sync with the Wear OS team how to provide a good solution for their users. Will do that. Thanks for reporting!

**Comment by marcbaechinger** [comment]
Reading the documentation this says:

> Figure 5. Media: Plays music throughout a session. Ends immediately after the user pauses the session.
> Wear creates ongoing activities automatically for media apps.

So my understanding is that there is already such an ongoing activity and for media apps with a session, Wear OS already 
creates such an ongoing activity.

> so we can call OngoingActivity APIs
> OngoingActivity.recoverOngoingActivity(context) doesn't work with the system-provided ongoing activity.

Can you elaborate a bit on what you want to customize? Sorry for asking naive questions.

**Comment by marcbaechinger** [comment]
As of now I think it's expected that apps can't customize the ongoing activity. This is done by OEMs to have a consistent UI across all apps. I filed b/384445054 internally to ask for advise and whether Wear OS want to change this.

**Comment by Digipom** [comment]
Hi @marcbaechinger, it's definitely possible to customize the ongoing activity -- we've done it in test code. It just requires us to bypass media3's notification because we need access to the NotificationCompat.Builder.

> Can you elaborate a bit on what you want to customize? 

AFAICT, all that would be needed is some sort of override that gets access to the NotificationCompat.Builder before build() is called.

**Comment by Digipom** [comment]
If it helps I can prepare a test project for demoing this.

**Comment by marcbaechinger** [comment]
What I hear back from Wear OS eng  is that the platform-posted media OA is overriding the customized OA of an app as this has priority. From this I don't think Media3 should change it API as we can not actually expect this is going to work.

Thanks for your suggestion and for raising awareness for the ongoing activity!
