### ISSUE TITLE
Release new beta soonish?

### ISSUE THREAD

**Issue by tzugen** [androidx/media#198]
Hi!

#167 is affecting us a lot on Play Store, and from the bug it sounds like its been fixed in trunk.
It would be super cool if you could release a new beta soonish, so that we can get rid of these crashes!

:bow:

**Comment by rohitjoins** [comment]
Yes, we are going to release a new beta soon.

**Comment by johnpaulmckean** [comment]
![oops](https://i.imgflip.com/3l3brt.jpg)
