### ISSUE TITLE
Access denied finding property "vendor.display-size"

### ISSUE THREAD

**Issue by JJSarrasin** [androidx/media#1986]
Hello guys,

On our launcher app, we're seeing a lot of warning logs about the message in the title.

After digging a bit, here are our observation:

  | Previous box (ATV 11) | New box (ATV12)
-- | -- | --
vendor.display-size | OK 4K | Erreur
vendor.nx.display-size | OK 4K | OK 4K
Display.getMode().getPhysicalWidth/Height | wrong 1080p | OK 4K

Our OEM tells us that vendor.display-size won't be used anymore since ATV 12 and we should refer on Display.getMode().physicalWidth/Height instead.

I don't know if it is something widely used nowadays on Android 12, if it is, you could priorize this instead of vendor.display-size.

**Comment by icbaker** [comment]
I think you can safely ignore these warnings? It looks like we fall-back from `vendor.display-size` to `Display.getMode().getPhysicalWidth()` in the logic in `Util.getCurrentDisplayModeSize`, via `getDisplaySizeV23()` (and you can see an explanation for why we use this process for TVs in the comment there too):

https://github.com/androidx/media/blob/df887a942222914836081f868067960eb0149547/libraries/common/src/main/java/androidx/media3/common/util/Util.java#L3146-L3198

**Comment by JJSarrasin** [comment]
Yes we can ignore them. 
I give the feedback, I don't know if it's really the new way to go for Android 12 and further. It could improve the process, but it seems to be a sensitive detection path and complicate to change :)
