### ISSUE TITLE
How to show a stop button in the notification with Media3

### ISSUE THREAD

**Issue by pawaom** [androidx/media#200]
How to show PlayerNotificationManager useStopAction  in media3 ,

Earlier we used to impalement the PlayerNotification and use useStopAction   to show the stop button, how can we do the same in media3

**Comment by marcbaechinger** [comment]
I think you can to do a custom command for the stop action. The custom command is reflected on all API levels either by adding an action to the notification or by replicating the custom Media3 commands to a media1 custom action in the legacy session.

This [comment](https://github.com/androidx/media/issues/38#issuecomment-1138578035) of issue #38 explains with code samples how you can do custom commands.

**Comment by Symon265** [comment]
Can you help me with a sample code just for a simple player media 3 , am
really struggling for the past 3 months its not working at all

**Comment by pawaom** [comment]
I can understand if we need custom actions like add to favorite or other such functionality supported by custom actions, but 
PlayerNotificationManager useStopAction was an inbuild functionality in exoplayer like this

<img width="296" alt="fUv3J" src="https://user-images.githubusercontent.com/28686824/199643789-7bc086b5-ab01-4a31-9b61-17b8230fb19f.png">

**Why should we use custom action for an inbuild functionality**

**Comment by marcbaechinger** [comment]
On Android 13, the mini player that is created by System UI is based on the media session. This [mini player does not support a stop button](https://developer.android.com/about/versions/13/behavior-changes-13#playback-controls). If you want the mini player to show a stop button, then you need to do a custom command.

**Comment by marcbaechinger** [comment]
I'm closing this issue because it is answered as to use a custom layout with a custom stop `SessionCommand`. The Media3 library makes sure it lands either on the Notification or the mini player depending on the OS of the device and the `targetSdkVersion` of the app.

Please re-open as needed.
