### ISSUE TITLE
How to keep video synced in different views

### ISSUE THREAD

**Issue by lyellss** [androidx/media#2001]
Greetings

At present, Exoplayer using Media3 meets a demand, which needs to display the same video synchronously on two views. For example, two views are added in ViewGroup, and the progress of these two views is consistent when playing the same local file. I found some of our documents. It seems that MediaClock needs to be used, but I don't know how to do it in media3. Do you have any suggestions and directions to think about to solve this problem?

Thanks again. Have a good life

**Comment by tianyif** [comment]
@lyellss,

I hope this comment (https://github.com/google/ExoPlayer/issues/8644#issuecomment-788788733) can guide you about the `MediaClock` solution. Briefly speaking, the secondary player needs to run a video renderer that implements `MediaClock` and whose `getCurrentPositionUs` returns the position of the renderer from the first player.

**Comment by lyellss** [comment]
@tianyif 

thank you for your replay.

I will closed this issue soon.
