### ISSUE TITLE
Documentation for Media3 implementation in Android Auto/AutomotiveOS

### ISSUE THREAD

**Issue by pawaom** [androidx/media#204]
Documentation for Media3 implementation in Android Auto/AutomotiveOS

While trying to learn about the Media3 implementation in Android Auto/AutomotiveOS 

we came across only these

https://www.youtube.com/watch?v=AHHERLwjUGo

and 

https://developer.android.com/training/cars/media

Which are based on the old mediasession and MediaBrowserServiceCompat API. 

And moreover the code that is used to explain in probably deprecated(AsyncTask in the search functionality implementation)

It would be very helpful to have a video explanation and a code with explanation example like the one provided for the old mediasession and MediaBrowserServiceCompat API.

Also a Codelab If possible will be very helpful in learning and faster adoption and migration to media3 and Auto/AutomotiveOS

**Comment by marcbaechinger** [comment]
There is a [migration guide](https://developer.android.com/guide/topics/media/media3/getting-started/migration-guide) that explains how to migrate from media1 to Media3.

The Media3 team does not provide product documentation for Android Auto/Automotive OS I'm afraid. You need to request this elsewhere.

**Comment by pawaom** [comment]
thanks for the reply , can you guide where I can request the guide.

**Comment by marcbaechinger** [comment]
**Demo apps**

We've added support for Android Auto to the session demo app and added a separated demo app for Automotive OS as guidance. It's not much different to another session app.

* [Session demo app](https://github.com/androidx/media/tree/release/demos/session) supporting mobile and Android Auto
* [ Automotive OS session demo app](https://github.com/androidx/media/tree/release/demos/session_automotive) supporting Automotive OS (separate APK running on AAOS)

Further documentation thta may be useful for Android Auto/Automotive OS:

**developer.android.com**

* [Advance controller configuration and backwards compatibility](https://developer.android.com/guide/topics/media/session/mediasessionservice#advanced)
* [Authorize Android Auto to send custom commands](https://developer.android.com/guide/topics/media/session/mediasessionservice#auto-authorization)

**JavaDoc**

* [MediaSession.isAutoCompanionController](https://developer.android.com/reference/androidx/media3/session/MediaSession#isAutoCompanionController(androidx.media3.session.MediaSession.ControllerInfo))
* [MediaSession.isAutomotiveController](https://developer.android.com/reference/androidx/media3/session/MediaSession#isAutomotiveController(androidx.media3.session.MediaSession.ControllerInfo))
