### ISSUE TITLE
[demo-session app] ForegroundServiceDidNotStartInTimeException is thrown when trying to play from notification

### ISSUE THREAD

**Issue by JaCobbMedia** [androidx/media#205]
### Media3 Version

1.0.0-beta02

### Devices that reproduce the issue

- Pixel 5 (Android 13)

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Build demo-session app (main branch)
2. Play any media item
3. Pause playback (either from player screen or notification)
4. Kill the app (remove from recent screens)
5. Notification is still visible
6. Press play in notification
7. Wait for 30s - `android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException` is thrown and visible in logcat

### Expected result

App should start playback or at least not crash if playback is not possible

### Actual result

`android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException` is thrown and notification stays stale

### Media

any media in demo app

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment]
Thanks for reporting. 

That's a bug in the demo app that does not properly stop the service when the app is killed (step 4 in your repro steps). This crashes the service without properly calling `onDestroy()` and leaves a stale notification. The system then restarts the service that was started with `START_STICKY`. You press that stale notification in your step 6.

Can you confirm that in the logs, you should find a log line from `ActivivtyManager` similar like below?

```
Scheduling restart of crashed service androidx.media3.demo.session/.PlaybackService in 1000ms for start-requested
```

The solution to this is the demo app properly killing the service when the app is killed. This way the service properly cleans up and the notification is removed.

Internal bug-ref: [b/249959896]

**Comment by JaCobbMedia** [comment]
Thanks for a quick answer @marcbaechinger . I can see the line you mentioned in logcat. What is the proper way to stop the service besides releasing all controllers/browsers?

**Comment by marcbaechinger** [comment]
I think you can override onTaskRemoved in your service like so. I need to test that in more detail first but this seem to remove the restart and it makes `onDestroy` being called.

```
override fun onTaskRemoved(rootIntent: Intent?) {
 if (!player.playWhenReady) {
   stopSelf()
 }
}
```
