### ISSUE TITLE
Apple Lossless Mp4 silent on Xiaomi device.

### ISSUE THREAD

**Issue by tzugen** [androidx/media#208]
### Media3 Version

1.0.0-beta02

### Devices that reproduce the issue

Xiaomi 10s

### Devices that do not reproduce the issue

Pixel 3

### Reproducible in the demo app?

Not tested

### Reproduction steps

Play test file

### Expected result

Audible sound

### Actual result

No sound

### Media

Test file: https://gitlab.com/ultrasonic/ultrasonic/uploads/0cec528339691a713351898ea51e3731/Black_Star.m4a

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tzugen** [comment]
The user was playing the same files with our app fine when it was using traditional Android Media. Now they are silent.

**Comment by christosts** [comment]
I don't see this format as guaranteed to be supported in Android devices
https://developer.android.com/guide/topics/media/media-formats

Whether it plays on a device or not goes down to whether a device has a decoder for this format. You can play this file with ExoPlayer on all devices if you use the [FFmpeg decoder module](https://exoplayer.dev/supported-formats.html#ffmpeg-extension). The instructions how to build and use ffmpeg decoder module [here](https://github.com/androidx/media/tree/1.0.0-beta02/libraries/decoder_ffmpeg). Note that when building ffmpeg, you need to specify the `ALAC` format, i.e. when you set the `ENABLED_DECODERS` variable, you must include at least `alac` (and any other format you may wish to play with the module).

When you say 

> The user was playing the same files with our app fine when it was using traditional Android Media

what exactly do you mean by _"traditional Android Media"_?

**Comment by tzugen** [comment]
> what exactly do you mean by _"traditional Android Media"_?
I meant that we were using a plain [MediaPlayer](https://developer.android.com/reference/android/media/MediaPlayer) before and according to the user there it worked fine.

**Comment by christosts** [comment]
You report that you are able to play this on a Pixel 3. Is that with mediaplayer too? I can't play this file with MediaPlayer, I tried a Pixel 3 and a Pixel 4.

**Comment by tzugen** [comment]
Ok, that was what i was trying. But now i realized the server might have transcoded it, need to check that.

**Comment by christosts** [comment]
I see. I'll repeat my initial comment that this audio format is not guaranteed to supported by the platform. It could be that some devices have a decoder for it, but it's down to the OEM. If you use the ffmpeg decoder module, you will be able to play the file with ExoPlayer across devices.

I'll close this issue, feel free to re-open
