### ISSUE TITLE
Private  constructor in DefaultMediaNotificationProvider makes overriding impossible

### ISSUE THREAD

**Issue by tzugen** [androidx/media#213]
### Media3 Version

1.0.0-beta03

### Reproduction steps

In getMediaButtons the comment reads:
> Override this method to customize the buttons on the notification. Commands of the buttons returned by this method must be contained in MediaController.getAvailableCommands().

Unfortunately it seems to be impossible to extend DefaultMediaNotificationProvider in beta-3, because Java will require a call to the constructor() of the inherited function, but it is private in DefaultMediaNotificationProvider.

Maybe there is some advanced trick to get it working, but it shouldn't not be that complicated, or at least documented how one can do it.

Full code:

```
@UnstableApi public class CustomProvider extends DefaultMediaNotificationProvider {
    public CustomProvider(Context ctx) {
        super(new Builder(ctx));
    }
    
    @Override
    protected List<CommandButton> getMediaButtons(Player.Commands playerCommands, List<CommandButton> customLayout, boolean showPauseButton) {
        return super.getMediaButtons(playerCommands, customLayout, showPauseButton);
    }
}
```

**Comment by rohitjoins** [comment]
Thank you for reporting this. It is a miss on our end and we will soon push a fix in the `main` branch.

**Comment by rohitjoins** [comment]
A [fix](https://github.com/androidx/media/commit/f3e450e7833bbc62237c1f24f9a1f6c4eed21460) for this has been released to the `main` branch.
