### ISSUE TITLE
Unresponsive notification after app has been dismissed

### ISSUE THREAD

**Issue by y20k** [androidx/media#224]
### Media3 Version

1.0.0-beta03

### Devices that reproduce the issue

* Emulator Pixel 4a API 33

### Reproducible in the demo app?

Yes

### Reproduction steps

1. open demo-session app
2. start playback
3. pause playback
4. dismiss the app via the task switcher

### Expected result

* the notification of the demo-session app is cancelled since the PlaybackService has been destroyed

### Actual result

* the notification of the demo-session app is still shown, its buttons are not responding though.

### Media

(You can reproduce the issue using the unmodified demo-session app.)

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment]
Thanks for reporting. That's fixed in the main branch by this commit:
https://github.com/androidx/media/commit/6a5ac19140253e7e78ea65745914b0746e527058

**Comment by y20k** [comment]
Thank you!
