### ISSUE TITLE
TimeLine of when Media 3 will be production ready

### ISSUE THREAD

**Issue by pawaom** [androidx/media#237]
TimeLine of when Media 3 will be production ready

Media 3 has been a great development for creating new apps with media support, specially reducing the need to write extra code as compared to exoplayer. 

When we check the RELEASENOTES , the latest beta version was released in November 2022, When we go through the issues pages, there are a few bugs and enhancements which are still pending , We have been developing app based on media 3 and would like to know how soon can we expect the media 3 Libraries will be production ready.  Most other developers also want the library to be available soon. Kindly consider the request to release the production ready version as soon as possible.

**Comment by pawaom** [comment]
if we get a proper timeline we will able to plan and release new apps accordingly, if we have initial information about future releases like its done with android versions like the planned  four monthly beta releases and final platform stability it helps us to work with a proper plan.

**Comment by marcbaechinger** [comment]
I can't give you a proper timeline about when we are going to release the stable version I'm afraid. We are trying to bring this out as soon as possible. As you mentioned, there are some pending bugs that we want to close before shipping the stable version. We are currently working on these.  

We definitively want to release as soon as possible just like you. This may mean that we are not shipping some of the `enhancements` but focus on `bugs` to speed this up.

**Comment by pawaom** [comment]
thanks for the reply , if we get a list of high priority bugs that will be focused on and the work around we can use for the current version, in the mean time will be helpful for us.

**Comment by marcbaechinger** [comment]
There is nothing that you can't find here in the public issue tracker.  We don't know about release blocking bugs of the library itself. We are working on improving the user experience when handling #111 on Android 12. Besides this there are few rather polishing things that we think are required for releasing a first stable 1.0.0 version.

I'm closing this issue.
