### ISSUE TITLE
Jetpack compose  , Hilt and coroutines example for the demo apps 

### ISSUE THREAD

**Issue by pawaom** [androidx/media#238]
Jetpack compose example for the demo apps 

Since the recommended way for future android is Kotlin with Jetpack compose, dagger hilt and coroutines, can you provide examples for media 3 using these .

**Comment by marcbaechinger** [comment]
This is a duplicate of [#google/ExoPlayer/9654](https://github.com/google/ExoPlayer/issues/9654). Some users provided some resources on how to integrate with compose.  I'm closing this issue. Please comment in the other issue.
