### ISSUE TITLE
Setting playback parameters with MediaControllerCompat

### ISSUE THREAD

**Issue by reygi1** [androidx/media#250]
I'm following this demo here: https://github.com/googlesamples/android-media-controller

The app works really well but I want to add this function here:
https://developer.android.com/reference/androidx/media3/session/MediaController#setPlaybackParameters(androidx.media3.common.PlaybackParameters)

This is available only in the new media3 MediaController.

I'm trying to implement the new MediaController and maybe use that one only for the setplayback instead of changing the whole code,  I saw that we have a function to convert the old token to the new one and tried this but the app crashes on start.

```
public void setupMediaController() {
        try {
            MediaSessionCompat.Token token = mMediaAppDetails.sessionToken;
            if (token == null) {
                token = mBrowser.getSessionToken();
            }
            mController = new MediaControllerCompat(this, token);
            mControllerN = (MediaController) new MediaController.Builder(this, SessionToken.createSessionToken(this,token).get()).buildAsync();

            mController.registerCallback(mCallback);
            mRatingUiHelper = ratingUiHelperFor(mController.getRatingType());

            // Force update on connect.
            mCallback.onPlaybackStateChanged(mController.getPlaybackState());
            mCallback.onMetadataChanged(mController.getMetadata());

            // Ensure views are visible.
            binding.viewPager.setVisibility(View.VISIBLE);
        } catch (ExecutionException e) {
            throw new RuntimeException(e);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
    }
```

The **mcontrollerN** is the new media3 controller.

Is there an easier way? I just need to use the _setPlaybackParameters_ function, and that is not available in the MediaControllerCompat.

Thanks

**Comment by marcbaechinger** [comment]
I think personally I would avoid having `media1` and `Media3` dependencies in my app at the same time. I'd prefer to be able to migrate to `Media3` and then remove the `media1` dependency entirely. This way the compiler would easily tell me whether I'm done. That may be a matter of taste though, but I'd prefer that for my own development to avoid my code being dependent to another external dependency. Like in the sense that, given we think it's hard to remove the `media1` dependency, we shouldn't add another before cleaning up. :)

For your specific case, I think I would create a custom action and send the `PlaybackParameters` object or a float for the `speed` from the controller to the session with such a custom action.   I'm not sure about your use case but only for setting the speed I'd shy back of using two controllers of different versions.

In case you are using `MediaSessionConnector` the playback speed is already set to the `PlaybackStateCompat` and [a controller can read it from there with the getter](https://developer.android.com/reference/android/support/v4/media/session/PlaybackStateCompat#getPlaybackSpeed()). To set a new speed you can then send the new value from the controller to the session with a custom actions.

**Comment by reygi1** [comment]
Thanks for the answer Marc.

I actually only need to change the pitch, I saw only MediaController and Exoplayer had that function.  

The SonicAudioProcessor has a [function that changes the pitch]( https://developer.android.com/reference/androidx/media3/exoplayer/audio/SonicAudioProcessor#setPitch(float)), but I don't know if it will work in real time like the example I need

The media controller example it's really good and it's well integrated with apps like Spotify and Youtube, but it's just missing this feature to change the pitch that I want to implement.

Would it be possible to convert [this function ](https://github.com/androidx/media/blob/50475814f700d08519c88585c9583f2aba5d702e/libraries/session/src/main/java/androidx/media3/session/MediaController.java#L782) and apply it on the MediaControllerCompat? I can't seem to find the source code that applies the pitch change.

**Comment by marcbaechinger** [comment]
> Would it be possible to convert [this function ](https://github.com/androidx/media/blob/50475814f700d08519c88585c9583f2aba5d702e/libraries/session/src/main/java/androidx/media3/session/MediaController.java#L782)and apply it on the MediaControllerCompat?

In general, I don't think we will add new functionality to the `media1` library. The custom action approach should be sufficient for such cases

I probably misunderstand some things you were saying. Please bear with me if so, but I want to give some more context to avoid any misunderstanding. Please ignore if already known: 

If the intention is to change the pitch on an session that you don't own (eg. Spotify) yourself and from which you only have a legacy controller, then I don't think that porting back to `media1` can help.  
In `media1` an app needs to map the state of the player to the session and back (as opposed to Media3 where the library is doing this). So even if we would add that method, then `Spotify` and `YouTube` would need to implement this on their end (update to the new library and implement the callback). 

However, I'm not sure whether the existing mental model from how connecting with a Media3 controller against a legacy session works is accurate. If the understanding is that using a `Media3` controller against an app that is only having a legacy session, will lend that app `Media3` capabilities, then I think this leads to disappointment I'm afraid. `Media3` can't magically add functionality on the client side. So even if you have the `Media3` API with a new controller, if the app is using the legacy session library then that session is restricted to the functionality of `media1` until the app decides to migrate to `Media3`.

I think in case you don't own the session side you can't add the pitch feature I'm afraid. Please let me know if your use case is different from connecting against 3rd-party apps. I don't think there is a good solution without talking with the owners of the session (Spotify/YouTube).

**Comment by reygi1** [comment]
Yes I would just need to change the pitch and integrate with Spotify/Youtube in real time.

I've found this function https://developer.android.com/reference/android/media/SoundPool.html#setRate(int,%20float) 

On the SoundPool library, which is part of media1. I'm just struggling to find a way to implement it with the MediaController, do you think it's possible?

**Comment by marcbaechinger** [comment]
I don't think we will backport this to `media1` I'm afraid. We're glad if ti works with `Media3`.
