### ISSUE TITLE
Suspend function when creating custom DataSource Factory

### ISSUE THREAD

**Issue by chientrm** [androidx/media#257]
How do I create a custom `DataSource.Factory` where it can run suspend code?
Firebase `idToken` only lives for 1 hour and can't be retrieved synchronously.

```kt
val defaultDataSourceFactory = DefaultHttpDataSource.Factory()
val dataSourceFactory = DataSource.Factory {
    val dataSource = defaultDataSourceFactory.createDataSource()
    val idToken = FirebaseAuth.getInstance().currentUser!!.getIdToken(false) // <- Here return a Task not a String
    dataSource.setRequestProperty("Authorization", "Bearer <supposed id token>")
    dataSource
}
val player = ExoPlayer
    .Builder(this)
    .setMediaSourceFactory(DefaultMediaSourceFactory(dataSourceFactory))
    .build()
```

**Comment by christosts** [comment]
Try wrapping the datasources with a [ResolvingDataSource](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/ResolvingDataSource.html) whose resolver gets the Id and sets it as a request property directly on the `DataSpec` (a `DataSpec` is the player's struct to describe an IO request and you can set request properties on it too, besides a `DataSource`).

Note, `ResolvingDataSource` is used from the player's loading threads, which are different from the app main thread. That means that you can perform some blocking operations on those threads without risking delays in app code, but you might need to be careful of synchronizing you data (if for example you share the same resolving state).

**Comment by chientrm** [comment]
> Try wrapping the datasources with a [ResolvingDataSource](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/ResolvingDataSource.html) whose resolver gets the Id and sets it as a request property directly on the `DataSpec` (a `DataSpec` is the player's struct to describe an IO request and you can set request properties on it too, besides a `DataSource`).
> 
> Note, `ResolvingDataSource` is used from the player's loading threads, which are different from the app main thread. That means that you can perform some blocking operations on those threads without risking delays in app code, but you might need to be careful of synchronizing you data (if for example you share the same resolving state).

I managed to use `runBlocking` to get Firebase `idToken`.
For now thing works well but I'm not sure if there'll be any glitch in the future.
