### ISSUE TITLE
Player does not switch to different quality streams (HLS)

### ISSUE THREAD

**Issue by montrimas** [androidx/media#276]
### Media3 Version

Media3 1.0.0-rc01

### Devices that reproduce the issue

Pixel 7 running Android 13

### Reproducible in the demo app?

Not tested

### Reproduction steps

Hello,
We are currently implementing adaptive HLS streaming in our app. Unfortunately we're struggling to find the reason why some of the audio tracks are not selected.
I'm creating DefaultTrackSelector with AdaptiveTrackSelection
but from the logs I can see that only a single track is being selected and player does not switch to other track despite the network conditions. Also it is clear that first group contains all of the tracks with adaptiveSupported=true, but none of those are selected and there are 3 more separate groups each containing a specific quality stream.

``` tracks [eventTime=25.54, mediaPos=1299.00, window=0, period=0
   group [
     [ ] Track:0, id=0, mimeType=audio/mp4a-latm, bitrate=68704, codecs=mp4a.40.2, supported=YES, adaptiveSupported=true
     [ ] Track:1, id=1, mimeType=audio/mp4a-latm, bitrate=202366, codecs=mp4a.40.2, supported=YES, adaptiveSupported=true
     [ ] Track:2, id=2, mimeType=audio/mp4a-latm, bitrate=339447, codecs=mp4a.40.2, supported=YES, adaptiveSupported=true
   ]
   group [
     [X] Track:0, id=default-audio-group:stream_1, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, label=stream_1, selectionFlags=[auto], supported=YES, adaptiveSupported=false
   ]
   group [
     [ ] Track:0, id=default-audio-group:stream_2, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, label=stream_2, selectionFlags=[auto], supported=YES, adaptiveSupported=false
   ]
   group [
     [ ] Track:0, id=default-audio-group:stream_0, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, label=stream_0, selectionFlags=[auto], supported=YES, adaptiveSupported=false
   ]
   group [
     [X] Track:0, id=ID3, mimeType=application/id3, supported=YES, adaptiveSupported=false
   ]
   Metadata [
     HlsTrackMetadataEntry [default-audio-group, stream_1]
   ]
 ]
 ```

*Example of HLS playlist:*
```#EXTM3U
## Generated with https://github.com/google/shaka-packager version v2.6.1-634af65-release

#EXT-X-INDEPENDENT-SEGMENTS

#EXT-X-MEDIA:TYPE=AUDIO,URI="stream_1.m3u8",GROUP-ID="default-audio-group",NAME="stream_1",AUTOSELECT=YES,CHANNELS="2"
#EXT-X-MEDIA:TYPE=AUDIO,URI="stream_2.m3u8",GROUP-ID="default-audio-group",NAME="stream_2",AUTOSELECT=YES,CHANNELS="2"
#EXT-X-MEDIA:TYPE=AUDIO,URI="stream_0.m3u8",GROUP-ID="default-audio-group",NAME="stream_0",AUTOSELECT=YES,CHANNELS="2"

#EXT-X-STREAM-INF:BANDWIDTH=68704,AVERAGE-BANDWIDTH=66244,CODECS="mp4a.40.2",AUDIO="default-audio-group",CLOSED-CAPTIONS=NONE
stream_1.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=202366,AVERAGE-BANDWIDTH=195010,CODECS="mp4a.40.2",AUDIO="default-audio-group",CLOSED-CAPTIONS=NONE
stream_2.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=339447,AVERAGE-BANDWIDTH=319471,CODECS="mp4a.40.2",AUDIO="default-audio-group",CLOSED-CAPTIONS=NONE
stream_0.m3u8
```

Thanks for your time.

### Expected result

Player switching between audio tracks based on the network conditions.

### Actual result

Player has only one track selected and does not switch to the other despite network conditions.

### Media

Not applicable (HLS playlists we use are available internally)

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by montrimas** [comment]
any updates on this one? we are not sure if thats a bug or is there something wrong with our HLS setup. any input on this would be really helpful.

**Comment by microkatz** [comment]
Hi @montrimas.

The track groups are being ordered via the `AudioTrackInfo.compareTo` method in the DefaultTrackSelector class.  You can check out the method in the code to see what attributes are being considered and how it orders tracks in its comparisons.

It would be easier to debug with content, but from your log snippet, it seems that the second group is being selected because it has a channel count and none of the tracks in the first group have that attribute?

There are ways to address this. If you have control over the HLS content, you can add attributes that provide the comparator more information. You can add a `TrackOverride` to your `TrackSelectionParameters` of your `DefaultTrackSelector`. Here is an [webpage](https://exoplayer.dev/track-selection.html) about track selection with ExoPlayer.

Hope this helps and let me know if you have any questions!

**Comment by microkatz** [comment]
I hope the suggestions above helped solve your problem. I'm going to close the issue. Please re-open or create a new issue if it did not.
