### ISSUE TITLE
Exoplayer handles in-progressive recording. 

### ISSUE THREAD

**Issue by zgzong** [androidx/media#284]
### Media3 Version

Media3 1.0.0

### Devices that reproduce the issue

Pixel 7 os 13

### Reproducible in the demo app?

Yes

### Reproduction steps

Similar issue has been discussed some years ago, https://github.com/google/ExoPlayer/issues/4603

Here are some difference compare with before, the circumstances:
- In-progress recordings are type="dynamic" manifests with mediaPresentationDuration and minimumUpdatePeriod
- mediaPresentationDuration has a fix value, and doesn't change when manifest update
- Once the recording is complete, the stream is converted to type="static"
- The manifest can pass all check on DASH IF conformance tool on https://conformance.dashif.org/

The exoplayer will 
- treat this as a live stream, and start the playback from live point
- finish download and play all segments then stop when manifest type changed from dynamic to static

The shaka player will 
- treat the stream as 'Detected as IPR stream, but does not match our model of IPR!'.
- start the playback from begin, not the live edge.

But frequently, the playback stop shortly since begin, player doesn't download any video/audio segments but only downloading the manifest. 

### Expected result

Expect exoplayer could continuously play the stream until all segments played when its type change to static. 

### Actual result

Stopped shortly since playback starts. 

### Media

We couldn't provide the stream, but i attached a copy of the manifest file. 
[ipr_manifest.txt](https://github.com/androidx/media/files/11083609/ipr_manifest.txt)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by zgzong** [comment]
With our investigation, we found the stream manifest may not update when refreshing, and it may only update after 3-4 times refresh, and add 3-4 new segments in SegmentTimeline. 

And we found inside the DefaultDashChunkSource.java public void getNextChunk() method contains following codes, 
`
    boolean periodEnded = periodDurationUs != C.TIME_UNSET;
`
In non-IPR stream, the above statement is correct, as when a period duration is not unset, this period can ended. And when segmentNum > lastAvailableSegmentNum || (missingLastSegment && segmentNum >= lastAvailableSegmentNum) condition meet, then player could safely consider the period is ended and segment loader reach the end of stream. 

But in IPR stream, the periodDuration is a known value and not equal TIME_UNSET, because the stream manifest may not update manifest when refreshing, even when condition meets, that doesn't mean the stream reach end of stream. 
'(segmentNum > lastAvailableSegmentNum || (missingLastSegment && segmentNum >= lastAvailableSegmentNum)) '

should we consider periodEnded as false when manifest is dynamic and it is the last period? 

And if we patch this way, the exoplayer could handle IPR stream as expected.

**Comment by zgzong** [comment]
Thanks for the agile response. 

> _because_ the stream manifest may not update manifest when refreshing_

That's what we observed the stream server behaviour. The manifest segmentTimeline may no change during 3-4 times mpd refreshing, and when it changes, it will bring 3-4 new segments. This condition cause the DefaultDashChunkSource assume it has found the end of the stream and refuses to load any further segments. 

Thanks for point out other use cases, regarding detecting the end of live stream. 
We will test with your suggest and feedback on this ticket.

**Comment by zgzong** [comment]
In DefaultDashChunkSource, add following, that helps to update the periodEnded correctly for this IPR stream. 
`  long firstAvailableSegmentStartTimeUs = representationHolder.getSegmentStartTimeUs(firstAvailableSegmentNum);
    long lastAvailableSegmentEndTimeUs = representationHolder.getSegmentEndTimeUs(lastAvailableSegmentNum);
    long availablePeriodDurationUs = lastAvailableSegmentEndTimeUs - firstAvailableSegmentStartTimeUs;
    periodEnded &= (availablePeriodDurationUs >= periodDurationUs);
`

**Comment by tonihei** [comment]
Sorry for the delay in getting back to you. Is it really needed to subtract `firstAvailableSegmentStartTimeUs`? I assume `lastAvailableSegmentEndTimeUs` and `periodDurationUs` are already in the same time reference and can be compared directly. Otherwise this idea looks good to me. Do you want to send a PR or should we change this internally?

**Comment by zgzong** [comment]
During our testing, we found that some Vod stream announced MPD@mediaPresentationDuration bigger than one of these AdaptationSets' duration calculated from SegmentTemplate. 

Most common reason is that video or audio last segment doesn't exist, and the delta between mediaPresentationDuration and AdaptationSets_duration is very small. 

In the end, we only apply the above check only manifest.dynamic is true. 

I didn't check firstAvailableSegmentStartTimeUs value, do you mean, that value always 0?

**Comment by tonihei** [comment]
> I didn't check firstAvailableSegmentStartTimeUs value, do you mean, that value always 0?

No, but which segment is first available one shouldn't influence the overall duration of the period. Does your change work if you just do `periodEnded &= (lastAvailableSegmentEndTimeUs >= periodDurationUs);`?

**Comment by zgzong** [comment]
Yes, that's works. 
firstAvailableSegmentStartTimeUs is always 0.

**Comment by tonihei** [comment]
Thanks for confirming! Do you want to send a PR for this or shall we just make the change internally?

**Comment by zgzong** [comment]
@tonihei 

After apply the patch, the original IPR stream can be played, but we met different issue when play similar stream with following variation, the player will fire ENDED after it loads init segments for video and audio. 

- period@start value is non-zero
- mpd@availabilityStartTime is 1970-01-01T00:00:00Z
I attached mpd for you to review.
[ipr_hevc.txt](https://github.com/androidx/media/files/12467798/ipr_hevc.txt)

It seems that non-zero value period@start doesn't take consideration by player engine,  E.G. DashManifest.java getPeriodDurationMs(int index);
After modify this method as below, the player will fire ended after it downloads the very first video&audio segment from the segment timeline, and do nothing.  
`  public final long getPeriodDurationMs(int index) {
    return index == periods.size() - 1
        ? (durationMs == C.TIME_UNSET ? C.TIME_UNSET : (durationMs - (periods.get(index).startMs - periods.get(0).startMs )))
        : (periods.get(index + 1).startMs - periods.get(index).startMs);
  }`
I attached the exoplayer log here
[ipr_hevc.log](https://github.com/androidx/media/files/12467951/ipr_hevc.log)

Can you shed some light on how to address this, please?

**Comment by tonihei** [comment]
I think the value of `mediaPresentationDuration` in the manifest of the last comment is invalid. The ISO 23009:1 spec for DASH generally assumes that `MPD@mediaPresentationDuration` is equivalent to the sum of
`Period@start` + `Period@duration` of the last Period (and either one or the other can be specified to deduce the actual duration). 

In your example manifest, `Period@start = "PT1693094874.718S"` and `MPD@mediaPresentationDuration="PT5400S"`, which doesn't really work because the assumption above implies that `MPD@mediaPresentationDuration >=  Period@start`.

**Comment by tonihei** [comment]
I'll mark the bug as fixed because the original problem was addressed with #528.
