### ISSUE TITLE
How to flip a video left or right in ExoPlayer without using TextureView.

### ISSUE THREAD

**Issue by hyoromo** [androidx/media#285]
> If you can't use TextureView, it's also possible to set a rotation when configuring the MediaCodec, which you could do by subclassing MediaCodecVideoRenderer and passing your subclass via a custom RenderersFactory when building the player.

[#8099](https://github.com/google/ExoPlayer/issues/8099#issuecomment-715262463) the above exchange, is it possible to inherit from MediaCodecVideoRenderer and implement left-right reversal of video?

If possible, it would be helpful if you could be more specific in your implementation.

**Comment by christosts** [comment]
I'm not aware of another transformation MediaCodec can apply besides rotation. That said, we recently developed the ability to apply effects on video frames at real-time. The feature is pushed on the main branch but included in a stable release yet. The high-level API is on the `ExoPlayer` interface

https://github.com/androidx/media/blob/dbeb9f51c4d618f7b129fb7837881ef0a230c5fe/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/ExoPlayer.java#L1551

You can also take a look at the transformer demo app (note: from the `main`) which demonstrates how this works.

@claincly do we have an effect that performs left-right reversal (I guess that's mirroring? - sorry, I don't know the exact terminology here)

**Comment by andrewlewis** [comment]
Here is an example for flipping left/right using `MatrixTransformation`:

```
player.setVideoEffects(ImmutableList.of((MatrixTransformation) presentationTimeUs -> {
      android.graphics.Matrix transformationMatrix = new android.graphics.Matrix();
      transformationMatrix.postScale(/* sx= */ -1, /* sy= */ 1);
      return transformationMatrix;
    }));
```

**Comment by andrewlewis** [comment]
I will close this as answered but please reply if there are any follow-up questions and we can reopen.

**Comment by hyoromo** [comment]
Excellent!
Thank you for your support.
