### ISSUE TITLE
Exoplayer HLS throws ParserException even when HTTP response body is valid

### ISSUE THREAD

**Issue by devingryu** [androidx/media#286]
My goal is to intercept HTTP stream open operation and change url + insert cookies.
In order to achieve it, I've created custom HttpDataSource which overrides `open()`.
``` kotlin
override fun open(dataSpec: DataSpec): Long {
        try {
            if (knownUrl != null && knownHeaders != null) {
                return super.open(
                    dataSpec.buildUpon().setHttpRequestHeaders(knownHeaders!!).setUri(knownUrl!!)
                        .build()
                )
            } else {
                val data =
                    ServiceClient.createService(FooInterface::class.java).getVodUrlCookies(vodId)
                        .execute()
                if (data.isSuccessful) {
                    with(data.body()!!) {
                        // Create cookieString from response body...
                        val newHeaders = dataSpec.httpRequestHeaders.toMutableMap().apply {
                            set("Cookie", cookieString)
                        }
                        knownUrl = vodUrl; knownHeaders = newHeaders.toMap()

                        return super.open(
                            dataSpec.buildUpon().setHttpRequestHeaders(newHeaders).setUri(vodUrl!!)
                                .build()
                        )
                    }
                } else throw CookieInvalidResponseCodeException(
                    data.code(),
                    null,
                    data.message(),
                    dataSpec,
                    data.errorBody()
                )
            }
        } catch (e: Exception) {
            throw CookieRequestException(e.message, e)
        }
    }
```

and this is how I create MediaSource.
``` Kotlin
val httpDataSourceFactory = SignedCookieRequiredHttpDataSource.Factory(vodId)
                .setUserAgent("Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0")
                .setAllowCrossProtocolRedirects(true)
                .apply {
                    setDefaultRequestProperties(mapOf("vod_id" to vodId.toString()))
                }
            val hdsf = DefaultHlsDataSourceFactory(httpDataSourceFactory)
            val mediaItem = MediaItem.fromUri(Uri.parse(""))
            HlsMediaSource.Factory(hdsf).createMediaSource(mediaItem)
```

I think this works pretty well, since Network Inspector shows content of .m3u8 file properly.  
However, HLS parser is the problem. It generates the following exception.
```
E  Playback error
com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:614)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.ParserException: Loaded playlist has unexpected type.
        at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker$MediaPlaylistBundle.onLoadCompleted(DefaultHlsPlaylistTracker.java:588)
        at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker$MediaPlaylistBundle.onLoadCompleted(DefaultHlsPlaylistTracker.java:512)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:478)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```
I thought that the actual URI of MediaItem could be the problem(since it is blank), so I replaced it with random .m3u8 link for placeholder. Unfortunately, this wasn't the case.  
What could be the problem? Thanks in advance.

**Comment by devingryu** [comment]
Thanks for helping!

I'm pretty sure that data which retrieved url is pointing is HLS Media Playlist. I've already checked that the media is played properly when I directly give the link to Exoplayer.

But come to think of it, I've never considered about loading the actual media file in HLS Media Playlist(*.ts files). Will Exoplayer use given HttpDataSource to load those files too? It doesn't explain the exception I get though.

**Comment by devingryu** [comment]
> If you don't want this you should provide your own implementation of HlsDataSourceFactory and branch on the value of dataType in createDataSource.

Before working on customization of HlsDataSourceFactory, I think I might be able to produce simillar behavior by checking uri of dataSpec in my custom `HttpDataSource`. If I provide certain string to `MediaSource` and check if dataSpec's uri is equivalent with it, I could find out whether the url needs to be replaced or not.

I'll give it a try and make an update here in a few hours.

**Comment by icbaker** [comment]
Also, if you only want to intercept the calls to `DataSource.open()` and modify the `DataSpec` before passing it into another `DataSource` instance you can probably use `ResolvingDataSource` rather than subclassing `DefaultHttpDataSource`: https://exoplayer.dev/customization.html#customizing-server-interactions

**Comment by devingryu** [comment]
Thanks, checking if url is null or empty worked. Think I should've checked documentation more carefully...

> Also, if you only want to intercept the calls to DataSource.open() and modify the DataSpec before passing it into another DataSource instance you can probably use ResolvingDataSource rather than subclassing DefaultHttpDataSource:

And this is actually pretty helpful! This seems to perfectly match my needs. Gonna check it out soon.

Again, thanks for helping!
