### ISSUE TITLE
Playback does not start when audio is too much early than video

### ISSUE THREAD

**Issue by goffioul** [androidx/media#291]
[I'm posting this as a question instead of a bug, as you might not consider it a bug per-se]

I'm using ExoPlayer 2.18.1 and I've encountered a problem with a test stream (I will post link via email), whereby ExoPlayer never starts playback on multiple platforms. ExoPlayer actually never enters ready state, but if the playback position is moved manually (e.g. using progress bar in demo app), then video plays normally.

This particular stream, a capture from a real-life scenario, has a rather bumpy start, with initial AC3 audio data with a timestamp that is significantly early compared to first video frames. This difference is larger than the threshold in https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/audio/MediaCodecAudioRenderer.java#L664, so the audio clock is updated (backwards). But then the first video frames produced by the codec are not rendered, as they have a later timestamp, and MediaCodecVideoRenderer never enters ready state.

I've seen failure to start playback on multiple platforms:
- rockchip with Android 11
- amlogic with Android 7
- android-x86 with Android 11 (ffmpeg-omx) and Android 13 (ffmpeg-codec2)
- using the platform AC3 codec (if present) or using the ffmpeg audio extension of ExoPlayer (with ac3 enabled)

If I increase the threshold mentioned above to 750000, then playback starts normally. Whether this is a proper fix, I don't know. There's a comment there that states it's a hack, and refers to an internal bug report.

The question is really whether ExoPlayer could handle this more gracefully than not starting playback?

**Comment by tonihei** [comment]
Thanks for reporting! This is in fact a known bug in the logic of `MediaCodecVideoRenderer` of when to render the first frame. The line you linked in `MediaCodecAudioRenderer` accidentally avoids the problem if the offset is small, but this isn't the solution. The logic for the real fix is quite complicated to get right as it needs to work for many different scenarios and that's why we haven't yet fixed it. [internal bug ref: b/160461756#comment11]
