### ISSUE TITLE
Opt in/out of Low Latency for DASH

### ISSUE THREAD

**Issue by sobbe81** [androidx/media#292]
Hi,

We are trying to setup low latency streams and LL works fine most of the times if the network condition is good. However, when the network condition is bad we feel that the experience with LL is poorer compared to non-LL. 

We are looking for a way to disable LL even though the streams would contain `ServiceDescription` tag in the DASH manifest. Comparing to Shaka player they have a `lowLatencyMode` boolean that can be used to opt in/out of LL. Are there any ways to achieve the same result on Exoplayer?

Regards,
Martin

**Comment by tonihei** [comment]
> when the network condition is bad we feel that the experience with LL is poorer compared to non-LL.

Could you provide more details about what you observed there? ExoPlayer automatically stays further away from the live edge if the buffer level is not sustainable. I wonder if there is something missing for your case that could make it work out of the box? 

> We are looking for a way to disable LL even though the streams would contain ServiceDescription tag in the DASH manifest.

You can override the `LiveConfiguration` in the `MediaItem.Builder` and set any `targetOffsetMs` you desire.

**Comment by tonihei** [comment]
Closing, because it looks like the question was answered.
