### ISSUE TITLE
Call MediaControllerCompat.Callback#onSessionEvent from MediaLibraryService

### ISSUE THREAD

**Issue by Yangwoqizuo** [androidx/media#293]
A function calling onSessionEvent is needed(maybe broadcastCustomCommand?)
PS: 
MediaControllerImplLegacy#onSessionEvent will call onCustomCommand(means MediaBrowserService can call Media3's onCustomCommand)
, so is there any way to let MediaLibraryService call MediaControllerCompat.Callback#onSessionEvent?
(Media3's MediaLibraryService call legacy MediaController's onSessionEvent)

**Comment by tonihei** [comment]
Thanks for the request! This looks like an oversight that should be added to the library as you described. I'll mark it as an enhancement.
