### ISSUE TITLE
how to make exoplayer2 use H264 codec instead of H265 in Kotlin Android?

### ISSUE THREAD

**Issue by Lz-01** [androidx/media#295]
I am trying o create a rtsp stream with the exoplayer2 (release 2.18.5). And i am trying to force the player to use H264. It does not work with the MimeType, because the player overwrites it somehow and uses H265 instead. I think i have to request the codec format before or i have to edit the response body in order to get the codec H264.

resonse.body of the RTSP Stream:

```
...
m=video 0 RTP/AVP 35
a=rtpmap:35 H264/90000
a=rtpmap:102 H265/90000
...
```
this is the code for the exoplayer setup:
```
val url = cameraInfo.cameraURLScheme
val player = ExoPlayer.Builder(context).build()

        // Build the media items.
        val mediaItem = MediaItem.Builder().setMimeType(MimeTypes.VIDEO_H264)
            .setUri(url)
            .build()
    
        val mediaSource = RtspMediaSource.Factory().createMediaSource(mediaItem)
    
        // Add the media items to be played.
        player.addMediaSource(mediaSource)
        // Prepare the player.
        player.prepare()
        // Start the playback.
        player.play()
```
Sidenote: I cannot use the H265 because it does not have the sprop-vps parameter

I have already tried to set the Mimetype and i debugged it and the mediaEncoder was still H265. i get the followig exception

`Caused by: java.io.IOException: java.lang.IllegalArgumentException: missing sprop-vps parameter`

because it uses H265 Format.

**Comment by tonihei** [comment]
I believe the RTSP module supports multiple different stream with different codecs. 

Can you try setting the preferred MIME type with
```
player.setTrackSelectionParameters(
    player.getTrackSelectionParameters().buildUpon()
        .setPreferredVideoMimeType(MimeTypes.VIDEO_H264)
        .build());
```
? Setting the mime type in the `MediaItem` has no effect because it only influences the type of source created for your `MediaItem` (which will always be RTSP).

If that doesn't work, please provide an example stream and ideally also a bugreport for further analysis. You can sent these to dev.exoplayer@gmail.com with subject "Issue #295" if needed.

**Comment by Lz-01** [comment]
i have added a parameter to the URL to automatic choose the H264 format. But now my i get the following exception:
`C2SoftAacDec            media.swcodec                        D  Invalid AAC stream
 C2SoftAacDec            media.swcodec                        W  aacDecoder_DecodeFrame decoderErr = 0x0005
 C2SoftAacDec            media.swcodec                        W  AAC decoder returned error 0x0005, substituting silence`
 
 i have the following ending of my rtsp url:
rtsp://.../rtsp_tunnel?inst=2&enableaudio=0&fmtp=1&h26x=4

if i disable the audio, the stream works fine. But i need the sound on the stream.

my sdp file looks like this:

`v=0
o=- 0 0 IN IP4 192.168.111.113
s=LIVE VIEW
c=IN IP4 0.0.0.0
t=0 0
a=control:rtsp://.../rtsp_tunnel?inst=2&enableaudio=1&fmtp=2
m=video 0 RTP/AVP 35
a=rtpmap:35 H264/90000
a=rtpmap:102 H265/90000
a=control:rtsp://.../rtsp_tunnel?inst=2&enableaudio=1&fmtp=2&stream=video
a=recvonly
a=fmtp:35 packetization-mode=1;profile-level-id=4d4028;sprop-parameter-sets=Z01AKI2NQDwBE/LgLcBAQFAAAD6AAA6mDoYAJ6wAAX14LvLjQwAT1gAAvrwXeXCg,aO44gA==
m=audio 0 RTP/AVP 96
a=rtpmap:96 mpeg4-generic/16000/1
a=fmtp:96 streamtype=5; profile-level-id=5; mode=AAC-hbr; config=1408; SizeLength=13; IndexLength=3; IndexDeltaLength=3
a=control:rtsp://.../rtsp_tunnel?inst=2&enableaudio=1&fmtp=2&stream=audio
a=recvonly`
