### ISSUE TITLE
Switching between subtitles doesn't work (English -> None -> English)

### ISSUE THREAD

**Issue by ziem** [androidx/media#296]
### Media3 Version

Media3 1.0.0

### Devices that reproduce the issue

- Pixel 5 (Android 13)
- OnePlus 10 Pro 5G

### Reproducible in the demo app?

Yes

### Reproduction steps

In the demo-session project inside `MediaItemTree` class comment out `.setSubtitleConfigurations(subtitleConfigurations)` (line 88).

1. Play https://d3rlna7iyyu8wu.cloudfront.net/skip_armstrong/skip_armstrong_stereo_subs.m3u8 in the demo app (demo-session)
2. Click subtitles button (cc)
3. Select None
4. Click subtitles button again
5. Select English

### Expected result

English subtitles should appear and be selected

### Actual result

English subtitles doesn't appear

### Media

https://d3rlna7iyyu8wu.cloudfront.net/skip_armstrong/skip_armstrong_stereo_subs.m3u8 (found on the internet)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment]
Thanks for reporting! This is caused by stripping some metadata from the subtitle format and as a result the player can't find the track you selected.

**Comment by ziem** [comment]
Is there any workaround I could use to fix this issue?

**Comment by ziem** [comment]
v1.0.1 fixes the issue, thanks 👍
