### ISSUE TITLE
Cannot hide controller_layout view when using MotionLayout in player_layout

### ISSUE THREAD

**Issue by yt8492** [androidx/media#298]
### Media3 Version

ExoPlayer 2.18.5

### Devices that reproduce the issue

Pixel 6 running Android 13

### Reproducible in the demo app?

Not tested

### Reproduction steps

This is my reproducible demo app repository.
https://github.com/yt8492/ExoPlayerBugReport

When using MotionLayout as a parent in player_layout, this problem is occurred.
If player_layout parent replace with ConstraintLayout, this problem is not occurred.

Reproduction steps:

1. Play the media in demo app
2. Tap screen to hide controller
3. The bug occurs

### Expected result

The controller in player is hidden

### Actual result

The controller is still showing

### Media

https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8

### Bug Report

- [x] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
Customising `PlayerView` beyond what's described in its javadoc is not really supported: https://developer.android.com/guide/topics/media/exoplayer/ui-components#further_customization

**Comment by icbaker** [comment]
Ah right, thanks for clarifying. I'll leave this open but since ExoPlayer's `PlayerView` is deprecated, I'm afraid we're unlikely to spend much time investigating.

**Comment by yt8492** [comment]
Thank you.
I researched current behavior using breakpoint.
I confirmed that the `hide()` method in `PlayerControlView` is finally called via `performClick()` method in `PlayerView` and called `setVisibility(GONE)`, but the controller UI is still showing.
