### ISSUE TITLE
How to download + transform

### ISSUE THREAD

**Issue by yschimke** [androidx/media#3]
I'm using Media3 on Wear, and want to make sure I'm always sending AAC over Bluetooth.  This seems very easy to convert using the 

https://github.com/androidx/media/blob/e6242690ffbd661fcf1fdc5e063d11dda3dfbd61/libraries/transformer/src/main/java/androidx/media3/transformer/TranscodingTransformer.java

But as it outputs to a new path, I wasn't sure how best to transcode items that I have just downloaded for offline, or even whether I can transcode as I'm downloading so I only have the preferred codec file, and don't have to replace the media item with a different local URL to replace the external HTTPS URL.

**Comment by andrewlewis** [comment]
Re-encoding locally could only make sense when using hardware audio offload, and as far as I know this isn't widely supported on Wear devices yet. If you are not using audio offload, the player will decode to PCM (raw audio) and I think the system will take care of re-encoding if needed for the Bluetooth output path automatically.

Even if you do you have a way to use audio offload on a Wear device, re-encoding locally in the app seems very wasteful of battery/CPU. It would be better to prepare the content in a suitable format for the watch on the host/server.

Anyway, to answer the question, currently Transformer uses `MediaMuxer` to write the output file. It should be possible to output to a new path and then overwrite/delete the input file if needed, and then pass the new path to the player.

**Comment by yschimke** [comment]
I understood I should prefer using AAC, but I believe feedback from some partners is that it's typical to have libraries encoded in other formats for mobile. I'd definitely like to use Audio Offload on recent Wear devices, fallback to other formats if not, but even then I thought AAC would be more efficient than MP3.

As I might need to deal with playlists coming from externally curated sources, is their guidance on which formats to prefer/avoid? 

The download could be optimised/pinned to happen when watch is charging, so this should negate the download/transform cpu/battery cost and make any savings for playback time the most relevant.

**Comment by andrewlewis** [comment]
> As I might need to deal with playlists coming from externally curated sources, is their guidance on which formats to prefer/avoid?

I don't think we have documented guidance on this but so far I've only seen devices supporting AAC and MP3 for audio offload.

**Comment by yschimke** [comment]
Thanks.  That matches my expectations, also limits on bitrates, possibly < 48kHz?

This guidance https://exoplayer.dev/battery-consumption.html#audio-playback also suggests that I should care about using audio offload for background media playback on Wear.
