### ISSUE TITLE
Why does SubtitleView no longer implement Player.Listener? 

### ISSUE THREAD

**Issue by Koster35** [androidx/media#301]
Hello,
Our app's video player implementation requires that `SubtitleView` implements `Player.Listener` so that closed captions can be rendered during playback. I'm curious why this was removed in this recent change: https://github.com/google/ExoPlayer/commit/06d73e93e6e47856a87b747120117385ac8ee622

We have a workaround in place to achieve the same result, but I figured I would ask why this change was made. Thanks!
```
exoPlayer.addListener(object : Player.Listener {
            override fun onCues(cueGroup: CueGroup) {
                subtitleView.setCues(cueGroup.cues)
            }
        })
```

**Comment by tonihei** [comment]
As noted in the commit message, the `SubtitleView` was not directly added as a listener in any of our default classes. It also keeps the `SubtitleView` more independent and cleaner as it doesn't need any reference to a `Player` or similar. 

Forwarding the event the subtitle view is relatively straight-forward (see your "workaround") and thus we concluded that the listener interface isn't needed. Do you think it would significantly simplify your app code if it's implementing `Player.Listener`?

**Comment by Koster35** [comment]
This solution works just fine. Thank you for the clarification!
