### ISSUE TITLE
HDR to SDR fails when using media3/transformer demo app for release 1.0.0

### ISSUE THREAD

**Issue by harini113** [androidx/media#304]
### Media3 Version

Media3 1.0.0

### Devices that reproduce the issue

Internal device

### Reproducible in the demo app?

Yes

### Reproduction steps

convert HDR10 clip to SDR with all other options set to false in the demo apk except Request SDR tone mapping

### Expected result

transformer demo app output clip should be generated

### Actual result

clip generated is 0 bytes and the logs have the following error

04-04 21:27:26.118  7504  7504 E TransformerActivity: Transformation error
04-04 21:27:26.118  7504  7504 E TransformerActivity:   androidx.media3.transformer.TransformationException: VideoDecoder, mediaFormat={color-transfer=3, allow-frame-drop=0, mime=video/hevc, profile=2, width=1920, color-range=2, rotation-degrees=0, max-input-size=234138, color-standard=1, height=1080, csd-0=java.nio.HeapByteBuffer[pos=0 lim=84 cap=84]}, mediaCodecName=c2.qti.hevc.decoder
04-04 21:27:26.118  7504  7504 E TransformerActivity:       at androidx.media3.transformer.DefaultCodec.createTransformationException(DefaultCodec.java:372)
04-04 21:27:26.118  7504  7504 E TransformerActivity:       at androidx.media3.transformer.DefaultCodec.maybeDequeueOutputBuffer(DefaultCodec.java:321)
04-04 21:27:26.118  7504  7504 E TransformerActivity:       at androidx.media3.transformer.DefaultCodec.getOutputBufferInfo(DefaultCodec.java:249)
04-04 21:27:26.118  7504  7504 E TransformerActivity:       at androidx.media3.transformer.VideoTranscodingSamplePipeline.maybeProcessDecoderOutput(VideoTranscodingSamplePipeline.java:330)
04-04 21:27:26.118  7504  7504 E TransformerActivity:       at androidx.media3.transformer.VideoTranscodingSamplePipeline.processDataUpToMuxer(VideoTranscodingSamplePipeline.java:235)
04-04 21:27:26.118  7504  7504 E TransformerActivity:       at androidx.media3.transformer.BaseSamplePipeline.processData(BaseSamplePipeline.java:77)
04-04 21:27:26.118  7504  7504 E TransformerActivity:       at androidx.media3.transformer.TransformerBaseRenderer.render(TransformerBaseRenderer.java:97)
04-04 21:27:26.118  7504  7504 E TransformerActivity:       at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1015)
04-04 21:27:26.118  7504  7504 E TransformerActivity:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:510)

### Media

Any HDR10 clip can be used 

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by dway123** [comment]
Does the device's codec support HDR to SDR tone-mapping for HDR10? I suspect it doesn't, but it may also only support tone-mapping in HLG10, or not support HDR to SDR tone-mapping at all.

If the device's codec doesn't support HDR to SDR tone-mapping for HDR10, then this version of Transformer wouldn't be able to decode and tone-map this content.

However, the main (not yet release) branch of Transformer will be able to convert this, as long as you're on an API 29+ device, using [`HDR_MODE_TONE_MAP_HDR_TO_SDR_USING_OPEN_GL`](https://github.com/androidx/media/blob/main/libraries/transformer/src/main/java/androidx/media3/transformer/TransformationRequest.java#L89), or [this option](https://github.com/androidx/media/blob/main/demos/transformer/src/main/java/androidx/media3/demo/transformer/ConfigurationActivity.java#L186) in the Transformer demo.

**Comment by harini113** [comment]
with Beta02 release on the same device we were able to execute the test with our version of the app using the libs. It was noticed first on rc01. I will try this above mentioned api call and update the thread.
