### ISSUE TITLE
Add ability to customize Player Notification or replace it with custom PlayerNotification

### ISSUE THREAD

**Issue by CodeBoy722** [androidx/media#306]
the default player notification made by Media session service is good but i will like to customize mine to fit my apps design and so far in the docs i have seen nothing about this,

**Comment by CodeBoy722** [comment]
after some digging, I found out the default Player notification could be overwritten in the onUpdateNotification method of the MediaLibraryService, the Javadoc on the method says this 

Called when a notification needs to be updated. Override this method to show or cancel your own notifications.
This method is called whenever the service has detected a change that requires to show, update or cancel a notification. The method will be called on the application thread of the app that the service belongs to.
Override this method to create your own notification and customize the foreground handling of your service.
At most one of onUpdateNotification(MediaSession, boolean) and this method should be overridden. If neither of the two methods is overridden, the default implementation will present a default notification or the notification provided by the MediaNotification.Provider that is set by the app. Further, the service is started in the foreground  when playback is ongoing and put back into background otherwise.
Apps targeting SDK_INT >= 28 must request the permission, android.Manifest.permission.FOREGROUND_SERVICE.
Params:
session – A session that needs notification update.

**Comment by marcbaechinger** [comment]
I think the best way to customize the notification is by using a 'MediaNotificationProvider` as described in the class level [JavaDoc of the `MediaSessionService`](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/MediaSessionService.java#L107). 

There is nothing wrong with overriding `onUpdateNotification` which works, but it probably needs a bit more work if it is really only about customizing the look of the notification.
