### ISSUE TITLE
MediaBrowserServiceCompat can't be terminated

### ISSUE THREAD

**Issue by MrBzik** [androidx/media#307]
Hi. In my MediaBrowserServiceCompat i am runnin this code, in task removed: 

```
override fun onTaskRemoved(rootIntent: Intent?) {
     super.onTaskRemoved(rootIntent)

            exoPlayer.stop()

            exoPlayer.clearMediaItems()
    }
```

Same as in uamp it triggers notification, which calls stopself().

onDestroy code : 
```
 override fun onDestroy() {

        exoPlayer.removeListener(radioPlayerEventListener)
        exoPlayer.release()

        mediaSession.run {
            isActive = false
            release()
        }

        serviceJob.cancel()

    }
```

If exoPlayer is not playing when app is closed, everythin is fine. But if it is playing, then it prevents service to end. I wonder why.

**Comment by marcbaechinger** [comment]
To properly stop the service in `onTaskRemove` a few conditions must be met. 

- The service should not run in the foreground, so you should call `player.pause` before stopping the service.
- The service should not have controllers being bound to it when stopping the service, so you should call `session.release()` to disconnect all controllers.

> Same as in uamp it triggers notification, which calls stopself().

Please note there is a `media3` branch in UAMP. It seems to me that [UAMP does the following](https://github.com/android/uamp/blob/media3/common/src/main/java/com/example/android/uamp/media/MusicService.kt) to make sure these conditions are met.


```
 override fun onTaskRemoved(rootIntent: Intent) {
        saveRecentSongToStorage()
        super.onTaskRemoved(rootIntent)
        // The choice what to do here is app specific. Some apps stop playback, while others allow
        // playback to continue and allow users to stop it with the notification.
        releaseMediaSession()
        stopSelf()
    }
```

**Comment by MrBzik** [comment]
Hi. Thanks for the answer.
It seems to me, that the code both implementations running is the same. Aparat that in media3 branch it does not handle notification. Or is it that I should release session before calling stopSelf()?
I tried it but still if exoplayer is playing, service does not stop. 

It does terminate only if I pause player via RadioServiceConnection .transportControls before closing app. Maybe so because of the delay, I don't know.

**Comment by marcbaechinger** [comment]
Yes, exactly. From above:

> The service should not run in the foreground, so you should call player.pause before stopping the service.

**Comment by MrBzik** [comment]
But then how to stop service if audio is still playing? Calling exoplayer.pause() in onTaskRemoved() does not make difference.

**Comment by marcbaechinger** [comment]
Sorry, I was confused. I was thinking you are using a Media3 service which isn't the case. If you are using `MediaBrowserServiceCompat` then your app does put the service into the foreground itself I think. The `MediaBrowserService` doesn't do that. If you look at the code of your app/service. You probably somewhere call `service.startForeground(int, notification)`. If you are in this state when you are in `onTaskRemoved` the you need to remove the service from the foreground.

UAMP with `MediaBrowserServiceCompat` does this [here](https://github.com/android/uamp/blob/main/common/src/main/java/com/example/android/uamp/media/MusicService.kt#L614).

**Comment by MrBzik** [comment]
Oh, okay. I think I am removing it already here though:
 
```
    override fun onNotificationCancelled(notificationId: Int, dismissedByUser: Boolean) {
        super.onNotificationCancelled(notificationId, dismissedByUser)

        radioService.apply {
            stopForeground(STOP_FOREGROUND_REMOVE)
            isForegroundService = false

            stopSelf()
        }
    }
```

**Comment by MrBzik** [comment]
Any new  thoughts on this matter? 
I spotted another scenario with exoplayer when service will not be terminated. 
It is if setting mediasource with stream which will trigger onPlayerError, or just putting phone in airplane mode for same result. If I pause exoplayer, and close an app, the service will still go on.
