### ISSUE TITLE
ExoPlayer stuck on BUFFERING while using HLS Live

### ISSUE THREAD

**Issue by be6ana** [androidx/media#315]
Hi,
ExoPlayer is 2.18.5

If we using HLS for playing Live stream, after some time playback stuck on BUFFERING. We see on the server side that player is requesting just an HLS manifest file but not individual chunk segment.

We trying to increase the buffers. Nothing is changed.
We trying to add flags :

`val defaultHlsExtractorFactory = DefaultHlsExtractorFactory(DefaultTsPayloadReaderFactory.FLAG_DETECT_ACCESS_UNITS or DefaultTsPayloadReaderFactory.FLAG_ALLOW_NON_IDR_KEYFRAMES, true)`

```
val hlsMediaSourceNew: MediaSource = HlsMediaSource
            .Factory(dataSourceFactory)
            .setExtractorFactory(defaultHlsExtractorFactory)
            .setAllowChunklessPreparation(true)
            .setLoadErrorHandlingPolicy(getMyErrorHandlingPolicy())
            .createMediaSource(mediaItem)

```
```
player!!.apply {
            setMediaSource(hlsMediaSourceNew)
            playWhenReady = false
            seekTo(0, 0L)
            prepare()
        }.also {
          videoView!!.player = it
        }

```
 Also stuck on BUFFERING.

HLS Playlist is simple manifest with 10s chunks

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:11
#EXT-X-MEDIA-SEQUENCE:168122060
#EXTINF:10.336,
http://x.x.x.x:2080/hls/74/168122060.ts
#EXTINF:10.432,
http://x.x.x.x:2080/hls/74/168122061.ts
#EXTINF:10.312,
http://x.x.x.x:2080/hls/74/168122062.ts
#EXTINF:10.456,
http://x.x.x.x:2080/hls/74/168122063.ts
#EXTINF:10.336,
http://x.x.x.x:2080/hls/74/168122064.ts
#EXTINF:10.352,
http://x.x.x.x:2080/hls/74/168122065.ts
```

P.S. If we decrease the buffers , stuck on buffering appears much earlier.

Does anyone know a solution how to fix this ?

Thanks

**Comment by christosts** [comment]
Can you please try playing the content on the ExoPlayer [demo app](https://developer.android.com/guide/topics/media/exoplayer/demo-application) to verify the issue happens there too? Also, can you share a link to the HLS playlist so that we can try playing the content as well? if you cannot share the link publicly, please send an email to dev.exoplayer@gmail.com with subject "Media3 issue #315" and update this issue that you done so.

Thanks.

**Comment by be6ana** [comment]
Thank you for your answer, unfortunately with the demo app issue still exist. This is a last messages from the log : 

```
12:15:44.740 EventLogger                     D  state [eventTime=1591.52, mediaPos=-29.39, window=0, period=0, BUFFERING]
12:15:44.747 EventLogger                     D  isPlaying [eventTime=1591.53, mediaPos=-29.39, window=0, period=0, false]
12:15:51.278 EventLogger                     D  timeline [eventTime=1598.06, mediaPos=-39.77, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
12:15:51.278 EventLogger                     D    period [?]
12:15:51.278 EventLogger                     D    window [61.75, seekable=true, dynamic=true]
12:15:51.278 EventLogger                     D  ]
12:16:02.474 EventLogger                     D  timeline [eventTime=1609.26, mediaPos=-50.04, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
12:16:02.475 EventLogger                     D    period [?]
12:16:02.475 EventLogger                     D    window [61.75, seekable=true, dynamic=true]
12:16:02.475 EventLogger                     D  ]
12:16:13.654 EventLogger                     D  timeline [eventTime=1620.43, mediaPos=-60.28, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
12:16:13.654 EventLogger                     D    period [?]
12:16:13.658 EventLogger                     D    window [61.87, seekable=true, dynamic=true]
12:16:13.658 EventLogger                     D  ]
12:16:24.829 EventLogger                     D  timeline [eventTime=1631.61, mediaPos=-70.66, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
12:16:24.829 EventLogger                     D    period [?]
12:16:24.830 EventLogger                     D    window [61.69, seekable=true, dynamic=true]
```

And of course its stuck on BUFFERING...

I send you a link to the testing stream to dev.exoplayer@gmail.com

Thanks

**Comment by christosts** [comment]
This is from the demo app running on a Pixel device

```
D/EventLogger: tracks [eventTime=1.71, mediaPos=10.29, window=0, period=0
D/EventLogger:   group [
D/EventLogger:     [ ] Track:0, id=0, mimeType=video/mpeg2, res=720x576, supported=NO_UNSUPPORTED_TYPE
D/EventLogger:   ]
D/EventLogger:   group [
D/EventLogger:     [ ] Track:0, id=3120/3, mimeType=audio/mpeg-L2, channels=2, sample_rate=48000, language=bg, supported=NO_UNSUPPORTED_TYPE
D/EventLogger:   ]
D/EventLogger:   group [
D/EventLogger:     [ ] Track:0, id=3120/8194, mimeType=application/cea-608, supported=YES
D/EventLogger:   ]
D/EventLogger:   group [
D/EventLogger:     [X] Track:0, id=null, mimeType=application/id3, supported=YES
D/EventLogger:   ]
D/EventLogger: ]
```

The content is encoded using codecs that are not supported out-of-the-box on the device, `video/mpeg2` for video and `audio/mpeg-L2` for the audio. This looks like the reason you're not seeing content playing, unless you're using the ffmpeg extension already (more below). To verify, you can run the demo app and inspect the EventLogger logs. If you see `supported=NO_UNSUPPORTED_TYPE` for video and audio tracks, then you hit this issue. Feel free to copy/paste the EventLogger logs here if you want us to verify this, or obtain a [bug-report](https://developer.android.com/studio/debug/bug-report) from the device and attach it here.

That said, at least for the audio track, you may able to play it with the [ffmpeg decoder extension](https://github.com/androidx/media/tree/release/libraries/decoder_ffmpeg), if you're not using it already, but we don't have a way to play the video if it's not supported by the device (there are decoder extensions for other video codecs, but not fir this specific).

**Comment by be6ana** [comment]
Hi, I did not saying that I have unsopported video or audio track. Of course out of the box there is no decoders for mpeg-2. I’m saying that the HLS stream after some time playback stuck on Buffering and nothing is happened. Just requesting the HLS manifest and not downloading the individual segments.

**Comment by christosts** [comment]
How exactly did you test in on the demo app? With only audio? What do I need to do to play the stream on phone?

**Comment by be6ana** [comment]
Sony Android TV and Android TV box.

**Comment by christosts** [comment]
Hi, is the stream still alive? I got access to a Sony TV

**Comment by be6ana** [comment]
Hi, the stream is still alive, just change the last 3 digits from the token parameter.

**Comment by christosts** [comment]
I've played the stream with the demo app on 2.18.5 twice for about 5 minutes each time and playback worked fine. Is the issue still happening on your side? Is there a way for me to trigger the issue?

**Comment by be6ana** [comment]
Hi, 
We found what exactly generate the problem. The mismatch of the segment duration and his declaration in the hls manifest.  That its not  exactly mismatch because declared duration was from video track stream duration. After changing the duration from video track to audio track (there is difference about 0.5 ms) , and declaring him into hls manifest, player does not stop to buffer 2 days in tests. I think this is not a solution to got audio stream duration for his declaration into manifest
