### ISSUE TITLE
SsaDecoder does not support utf-16 encoded ass files

### ISSUE THREAD

**Issue by viqbgrg** [androidx/media#319]
### Media3 Version

Media3 1.0.0

### Devices that reproduce the issue

redmi k30pro running android 12

### Reproducible in the demo app?

Yes

### Reproduction steps

SsaDecoder uses utf8 by default, if you play subtitles in utf16 encoding format, there will be problems

### Expected result

ass subtitles display normally

### Actual result

SsaDecoder's parseHeader method equalsIgnoreCase cannot judge equality normally

### Media

[ass](https://drive.google.com/file/d/1_B0q6Rf0Bzm2GKZBpPwLoz-PCL3aBV6-/view?usp=share_link)

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by microkatz** [comment]
Hello @viqbgrg.

Thank you for logging your issue! We added support for utf-16 to the SsaDecoder. Here is a link, [a9c8f2](github.com/google/ExoPlayer/commit/a9c8f2f383d86cf0f9765b0a499d503215d7fd61), to the commit to the main branch that added the feature. Hope this works! Please reopen if this does not fix your issue.
