### ISSUE TITLE
setAuxEffectInfo does not apply 

### ISSUE THREAD

**Issue by MrBzik** [androidx/media#322]
Hi. I can not find any example how to apply AudioEffects to exoplayer. I tried to add it before and after media source is set. For example reverb: 

```
 val reverb = PresetReverb(1, exoPlayer.audioSessionId)

        reverb.preset = PresetReverb.PRESET_LARGEHALL

        reverb.enabled = true

        exoPlayer.setAuxEffectInfo(AuxEffectInfo(reverb.id, 1f))
```
It does not work.

**Comment by icbaker** [comment]
Are you checking that `ExoPlayer.getAudioSessionId` isn't returning `C.AUDIO_SESSION_ID_UNSET` (per [the docs](https://developer.android.com/reference/androidx/media3/exoplayer/ExoPlayer#getAudioSessionId())) - see the docs on [`setAudioSessionId`](https://developer.android.com/reference/androidx/media3/exoplayer/ExoPlayer#setAudioSessionId(int)) for how you can generate one if needed.

**Comment by MrBzik** [comment]
Oh, right. I was looking at a wrong info. Other effects seems to work with exoplayer. 
I tried to launch reverb on session 0 (and still it did not work, but that 's not related to exoplayer), but I did not see it is mandatory. 
Thank you.
