### ISSUE TITLE
How to control remote device volume with hardware buttons on remote playback?

### ISSUE THREAD

**Issue by ashutoshgngwr** [androidx/media#328]
Hi there,

I set up the media router menu item to support Google Cast in my app as follows.

```kotlin
menu.add(titleResId).also {
  it.setShowAsAction(MenuItem.SHOW_AS_ACTION_IF_ROOM)
  MenuItemCompat.setActionProvider(it, MediaRouteActionProvider(context))
  CastButtonFactory.setUpMediaRouteButton(context, menu, it.itemId)
}
```

Previously, with Media Session Compat APIs, I used [`MediaSessionCompat#setPlaybackToRemote()`](https://developer.android.com/reference/kotlin/android/support/v4/media/session/MediaSessionCompat#setPlaybackToRemote(androidx.media.VolumeProviderCompat)) to control the remote device volume with hardware buttons. But with the latest Media 3 APIs, I couldn't find a suitable alternative. How do I achieve this?

**Comment by ashutoshgngwr** [comment]
Resolved by https://github.com/google/ExoPlayer/issues/10471#issuecomment-1510869336!

**Comment by tzugen** [comment]
@ashutoshgngwr 

I wonder, did you get the native volume bar to show up? I have added COMMAND_GET_DEVICE_VOLUME, COMMAND_SET_DEVICE_VOLUME and COMMAND_ADJUST_DEVICE_VOLUME commands, and when I use the hardware buttons the correct methods are called, but I don't get the native volume UI yet..

**Comment by ashutoshgngwr** [comment]
@tzugen Yes, the hardware buttons work correctly, but there were a lot of boundary conditions, e.g., the player must be in the playing state, and the player must propagate volume changes to the remote device and vice versa.

My full implementation is wrapped in [this class](https://github.com/trynoice/android-app/blob/8edb20faaad848041d3dc10a51736279bd116656/app/src/main/java/com/github/ashutoshgngwr/noice/engine/SoundPlaybackMediaSession.kt#L110-L345), and [this commit](https://github.com/trynoice/android-app/commit/7f9e91e3a1ed592b74208bb581444589016432e5) introduced changes necessary for remote device volume management. Please feel free to use these as references!

**Comment by tzugen** [comment]
@ashutoshgngwr 
Thanks! Though I am not sure if you read my question how i meant...

The logic I have implemented but I would like to get the native UI, like this:
![volume-buttons-android-p-actually-control-media-by-default-now w1456](https://github.com/androidx/media/assets/67737443/2d5b095b-049b-48da-adbc-ece77248a83c)

Do ave this working?

**Comment by ashutoshgngwr** [comment]
Ah, I thought you were referring to the slider that appears with the cast icon on pressing the volume rocker. If I understand you correctly now, in your case, your player doesn't need to handle `COMMAND_GET_DEVICE_VOLUME`, `COMMAND_SET_DEVICE_VOLUME` and `COMMAND_ADJUST_DEVICE_VOLUME`. If you add these commands to its state builder, Media 3 will expect the player instance to adjust the device volume and the player state based on these callbacks. However, if you do not _intercept_ these commands, Media 3 will fall back to the default behaviour, and you should see the slider on pressing the volume rocker.

**Comment by tzugen** [comment]
OK thanks a lot :)
Could you show a screenshot of how this slider with the castIcon looks?

**Comment by tzugen** [comment]
Ah, it was some other place in my code which was blocking it. Got it working now, thanks!
