### ISSUE TITLE
Can't replay video after player in ExoPlayer.STATE_ENDED

### ISSUE THREAD

**Issue by lukedawe** [androidx/media#330]
### Media3 Version

ExoPlayer 2.18.5

### Devices that reproduce the issue

Any

### Devices that do not reproduce the issue

None

### Reproducible in the demo app?

No

### Reproduction steps

Code for ExoPlayer:

```kotlin
val context = LocalContext.current

val exoPlayer = ExoPlayer.Builder(LocalContext.current)
        .build()
        .also { exoPlayer ->
            val mediaItem = MediaItem.Builder()
                    .setUri(Uri.parse("android.resource://" + packageName + "/" + R.raw.xxxxxx))
                    .build()
            exoPlayer.setMediaItem(mediaItem)
            exoPlayer.playWhenReady = true
            exoPlayer.videoScalingMode = C.VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING
            exoPlayer.addListener(playerEventListener)
            exoPlayer.prepare()
        }

DisposableEffect(
        AndroidView(factory = {
            StyledPlayerView(context).apply {
                hideController()
                useController = false
                player = exoPlayer
            }
        })
                ) {
    onDispose { exoPlayer.release() }
}
```

Then I create a button to be able to restart the video:
```kotlin
Button(onClick = {                             
                                exoPlayer.seekTo(0)
                                exoPlayer.play() 
                                             }, 
                                  ) {
                                Text(
                                        text = "replay",
                                        fontSize = 18.sp,
                                        modifier = Modifier
                                                .padding(5.dp),
                                        textAlign = TextAlign.Center
                                    )
                            }
```

### Expected result

The button will replay the video no matter what state it's in.

### Actual result

The button works **while the video is playing**, however when the video ends the button no longer works.

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by christosts** [comment]
I'm no UI expert, especially with Compose, but could it be your DisposableEffect's onDispose() is releasing the player?

**Comment by christosts** [comment]
I double checked with the player demo app and calling seekTo(0) & play() once the player is reached the end of the media item restarts playback. I suppose there is something going on on your app. 

We could provide a bit more help if you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by lukedawe** [comment]
I've sent an email with a link to the project zip, unfortunately I couldn't attach it so hopefully you can use the drive link that I sent in the email - otherwise I'll upload it on GitHub.

If it's any help, I noticed that the line that caused the issue for me was when I accessed the viewModel from within `playerEventListener` on the `ExoPlayer.STATE_ENDED` event.

**Comment by christosts** [comment]
I checked your project, thanks for sending it. As I said, I'm no UI expert but what I see in the code is that the app is creating multiple player instances so the "restart" button is probably accessing the wrong player reference. Please make sure your app is using one player instance, or at least the button is referencing the right instance. This is not a problem specific to ExoPlayer and more of a generic Android programming question, so I'll close this issue and suggest that you seek help to a more suitable forum, like StackOverflow.

Thanks.

**Comment by lukedawe** [comment]
Hi @christosts, I'm afraid I have to disagree with what you're saying on this one. I create the player in the `onCreate()` method which only runs once when the activity is created, so I don't see how multiple players would be created. 
Upon reflection what I think is happening is that the variable that I change in the viewModel in the `showNextButton()` method causes a recomposition of the screen, and somehow this breaks ExoPlayer. I think this issue should be looked into further because it seems that adding any code that triggers a recomposition from the Player.Listener callbacks causes exoPlayer to break.

**Comment by christosts** [comment]
I tried replacing the short mp4 asset wity playing `"https://html5demos.com/assets/dizzy.mp4"` which is a bit longer. 

Yes,`onCreate()` is called once, but the code that instantiates the player inside `MVPExoPlayerReplayTheme` is called again after the video reaches the end. Then, the restart button seeks and calls play on the new player instance (I can hear the audio playing) but the player view is still using the previous player instance. As I said, I'm far from UI expert, but this is not a problem specific to the library.

**Comment by lukedawe** [comment]
Ah I found the issue with the code, for anyone with the same issue and to put @christosts mind at ease that they will stop getting bugged by me:

```kotlin
val exoPlayer = remember {
                        ExoPlayer.Builder(context)
                                .build()
                                .also { exoPlayer ->
                                    val mediaItem = MediaItem.Builder()
...
```

instead of

```kotlin
val exoPlayer = ExoPlayer.Builder(context)
                                .build()
                                .also { exoPlayer ->
                                    val mediaItem = MediaItem.Builder()
...
```

The `remember` call means that compose remembers the state of the player and will not recreate it on the next recomposition.

Cheers @christosts for the diagnosis on the code.
