### ISSUE TITLE
MediaBrowserServiceCompat - Result.onErrorSent

### ISSUE THREAD

**Issue by tobyworks** [androidx/media#334]
We're seeing a few occurences of the following error which is only happening on Android 8. It looks to me like it is happening because at the point of `loadChildren` the controller is not yet set. What might be reason for this to happen, it started happening since we introduced media3 we're also using Android Auto. 

```
Fatal Exception: java.lang.UnsupportedOperationException
It is not supported to send an error for /
androidx.media.MediaBrowserServiceCompat$Result.onErrorSent (MediaBrowserServiceCompat.java:945)
androidx.media.MediaBrowserServiceCompat$Result.sendError (MediaBrowserServiceCompat.java:890)
androidx.media3.session.MediaLibraryServiceLegacyStub.onLoadChildren (MediaLibraryServiceLegacyStub.java:197)
androidx.media3.session.MediaLibraryServiceLegacyStub.onLoadChildren (MediaLibraryServiceLegacyStub.java:187)
androidx.media.MediaBrowserServiceCompat$MediaBrowserServiceImplApi21.onLoadChildren (MediaBrowserServiceCompat.java:427)
androidx.media.MediaBrowserServiceCompat$MediaBrowserServiceImplApi21$MediaBrowserServiceApi21.onLoadChildren (MediaBrowserServiceCompat.java:518)
android.service.media.MediaBrowserService.performLoadChildren (MediaBrowserService.java:675)
android.service.media.MediaBrowserService.addSubscription (MediaBrowserService.java:612)
android.service.media.MediaBrowserService.-wrap3
android.service.media.MediaBrowserService$ServiceBinder$3.run (MediaBrowserService.java:288)
android.os.Handler.handleCallback (Handler.java:790)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:164)
android.app.ActivityThread.main (ActivityThread.java:6558)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:469)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:826)
```

**Comment by victor-munoz** [comment]
Is there any update regarding this crash? I have the same problem but also for Android 6 and 7

**Comment by marcbaechinger** [comment]
Do you have some repro steps how this happens? Like what method is called trying to achieve what in in what context this happens (right after connecting, every time, randomly, ...)? Who is calling this method? Your app, Android Auto?

From the stack trace above it looks like a legacy `BrowserCompat` is calling `subcribe` to receive children from the `MediaLibraryService`. There is a test case for this [here](https://github.com/androidx/media/blob/release/libraries/test_session_current/src/androidTest/java/androidx/media3/session/MediaBrowserCompatWithMediaLibraryServiceTest.java#L214). I think we need to understand a bit better in what context this happens.

If you can give us some more info to make this actionable, this would be helpful. If you have a bug report when you repro, this would of cource be helpful as well.

**Comment by victor-munoz** [comment]
This is all the information that I have:

Operation system: 
- 6.0.1
- 7.1.1
- 7.0

Devices:
- Galaxy J7 Prime
- Galaxy S7
- Galaxy Tab A
- Galaxy Tab S2
- Galaxy Tab S2
- Galaxy Tab A

The Stack trace is the same as posted early. But I am afraid I cannot reproduce it using an emulator, and I don't have Android devices with those OS. Something curious is that there are a few users who are reporting many crashes; maybe it is a device-specific issue; at least only Samsung devices are reporting this crash.

**Comment by marcbaechinger** [comment]
> Who is calling this method?

To give some context. The stack trace above shows that an app with `MediaControllCompat` is accessing your app that is running Media3. 

Do you have code in you app, that uses the legacy API? What app is connecting against your service? I'm asking because we need a repro to fix this. With the information currently available it's difficult for us to investigate.

**Comment by victor-munoz** [comment]
I reproduced the issue using the media app demo-session on an emulator API 24.

https://github.com/androidx/media/assets/9167014/a333ff60-619f-4445-a193-061adadc488d

This is the log of the crash:


`
FATAL EXCEPTION: main
 Process: androidx.media3.demo.session, PID: 18513
java.lang.UnsupportedOperationException: It is not supported to send an error for [rootID]
at androidx.media.MediaBrowserServiceCompat$Result.onErrorSent(MediaBrowserServiceCompat.java:945)
at androidx.media.MediaBrowserServiceCompat$Result.sendError(MediaBrowserServiceCompat.java:890)
at androidx.media3.session.MediaLibraryServiceLegacyStub.onLoadChildren(MediaLibraryServiceLegacyStub.java:200)
at androidx.media3.session.MediaLibraryServiceLegacyStub.onLoadChildren(MediaLibraryServiceLegacyStub.java:190)
at androidx.media.MediaBrowserServiceCompat$MediaBrowserServiceImplApi21.onLoadChildren(MediaBrowserServiceCompat.java:427)
at androidx.media.MediaBrowserServiceCompat$MediaBrowserServiceImplApi21$MediaBrowserServiceApi21.onLoadChildren(MediaBrowserServiceCompat.java:518)
at android.service.media.MediaBrowserService.performLoadChildren(MediaBrowserService.java:662)
at android.service.media.MediaBrowserService.addSubscription(MediaBrowserService.java:600)
at android.service.media.MediaBrowserService.-wrap3(MediaBrowserService.java)
at android.service.media.MediaBrowserService$ServiceBinder$3.run(MediaBrowserService.java:272)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6077)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
`

**Comment by victor-munoz** [comment]
Hello @marcbaechinger.

We publish an update using the last media3 version 1.1.0. We can confirm that this crash is still happening but there is something that is repeated on every crash: the last call shown in the logs is:
 `service::onGetLibraryRoot | packageName:com.android.bluetooth | return:ROOT_ID`
 
 
P.S. There is another open issue created last year in May that can be related or duplicated: [https://github.com/androidx/media/issues/78](https://github.com/androidx/media/issues/78)

**Comment by marcbaechinger** [comment]
I can not repro the crash when using an emulator running Android 7/API 24.

There is a bug in the media controller app that does not allow to browse the categories. Once this bug is fixed, I can connect to the session demo and navigate through the library. I can also start and pause playback of the current item and add a new item for playback when using the browser.

I have file a pull request against the media controller app to fix this: https://github.com/googlesamples/android-media-controller/pull/50

I try to get my hands on an Samsung device with API 24.
