### ISSUE TITLE
PHP progressive download streams each minute disconnect problem

### ISSUE THREAD

**Issue by m0hamedessam** [androidx/media#344]
### Media3 Version

ExoPlayer 2.18.6

### Devices that reproduce the issue

any android device

### Devices that do not reproduce the issue

none

### Reproducible in the demo app?

Yes

### Reproduction steps

1- play live stream for 1 or 2 mins will be disconnected however on other libs like vlc or ijk player works fine maybe because its not native progressive download streams (its php progressive download streams)

### Expected result

play live stream without disconnected

### Actual result

live stream will be disconnected and restarted each 1 min however on other libs like vlc or ijk player works fine maybe because its not native progressive download streams (its php progressive download streams)

### Media

i will email live test url 

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by m0hamedessam** [comment]
any updates ?

**Comment by christosts** [comment]
Have you changed your server's behavior? I'm streaming for more than 3 minutes?

**Comment by m0hamedessam** [comment]
> Have you changed your server's behavior? I'm streaming for more than 3 minutes.

no we didnt just wait more time you will see its restarting.

**Comment by christosts** [comment]
I test with the demo app. Playback works fine, more than 3 minutes, I stopped playback at 5 minutes. I am seeing timeouts from the http client and I tried with two clients, the `CronetHttpDataSource` and the `DefaultHttpDataSource` (I've ran 4 tests in total). Despite the occasional timeouts, the player recovers from them, it retries to load and carried on. I did not see the player restarting.

I can't tell if you hit the same issue with the timeouts or this came up only my testing, or whether your server is stalling data transmission that's causing an issue. I was not able to repro the issue, and I'm inclined to close the issue as not reproducible.

**Comment by m0hamedessam** [comment]
Im talking about this timeout restart its not from server its from exoplayer if you test on ijk player or vlc you will see its working fine

**Comment by christosts** [comment]
There is a default read timeout of 8 seconds, [here](https://github.com/androidx/media/blob/3c01488f8d478caaa54038431ee6339444ea6e04/libraries/datasource_cronet/src/main/java/androidx/media3/datasource/cronet/CronetDataSource.java#L419) for the `CronetHttpDataSource` and [here](https://github.com/androidx/media/blob/3c01488f8d478caaa54038431ee6339444ea6e04/libraries/datasource/src/main/java/androidx/media3/datasource/DefaultHttpDataSource.java#L224) for the DefaultHttpDataSource. Can I assume your server is not responding with any bytes for that long?

I do not know what vlc is doing for network transfers. You can try to change the timeout your app, you'll need to customize the player to use a custom instance of an http client, there is documenation of this in
https://developer.android.com/guide/topics/media/exoplayer/network-stacks#configuring_exoplayer_to_use_a_specific_network_stack
