### ISSUE TITLE
Get Audio Data after preparing the content

### ISSUE THREAD

**Issue by StAincrad** [androidx/media#354]
Hello, I've been working with a plugin for Unity based on ExoPlayer for displaying video in my game. Everything is working fine, but I'm wondering if there is a way to extract the audio data from ExoPlayer after the video has been prepared. 
My idea is to extract the audio bytes or data and then send that information to Unity, so in Unity I will be able to control the audio for being a 3D audio or putting filters such as an under-water effect or different things. 

This is my idea: 
Load video content in Unity -> ExoPlayer prepare the video and audio content -> Extract audio (video is already done) -> Send to Unity -> Do my stuff in Unity side

I've been checking the functions provide by the player as well (exoPlayer.getAudioFormat(),exoPlayer. getAudioAttributes() and exoPlayer.getAudioDecoderCounters()) but it doesn't look I can get anything useful for my case with those. 

I also took a look at [AudioSink](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/audio/AudioSink.html) and [AudioProcessor](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/audio/AudioProcessor.html) but I still don't know how to use that in my case. 

Thanks!

**Comment by rohitjoins** [comment]
Is this possible @christosts?

**Comment by christosts** [comment]
I do not know how the unity plugin is implemented and what level of control you have on the player. To grab the decoded PCM audio out, you can use the [TeeAudioProcessor](https://developer.android.com/reference/androidx/media3/exoplayer/audio/TeeAudioProcessor). The processor must be set on the `DefaultAudioSink` at construction time. By default, the `DefaultAudioSink` is constructed by the `DefaultRendererFactory.buildAudioSink()` which you can override. It should be something like 

```java
ExoPlayer exoPlayer = new ExoPlayer.Builder(context, new DefaultRenderersFactory(context){
  @Nullable
  @Override
  protected AudioSink buildAudioSink(Context context, boolean enableFloatOutput,
      boolean enableAudioTrackPlaybackParams, boolean enableOffload) {
    new DefaultAudioSink.Builder(context)
        .setAudioProcessors(/* the TEE audio processor */)
        .build()
  }
}).build();
```
