### ISSUE TITLE
Preview bar with images

### ISSUE THREAD

**Issue by VolodymyrYeletskyi** [androidx/media#365]
Does Media3 has an option to get video frames and show them while user rewinds video like in Youtube?

**Comment by rohitjoins** [comment]
@VolodymyrYeletskyi,

The question has multiple layers to consider:
- Use of trick play tracks that contain only sparse i-frames to support fast back and forward seeking
- UI support that displays these trick play tracks as thumbnails above the scrubber.

There was a recent [question](https://github.com/androidx/media/issues/360) to support being able to extract thumbnails from a video on-device which can be an alternative to the i-frame trick play for a media that doesn't have it(obviously this won't work for live streams as the whole piece of media should be loaded locally). Currently, there are no plans to provide this feature. 

Regarding trick play support, https://github.com/google/ExoPlayer/issues/5254 is tracking support for DASH. We would like to extend this support for other formats in the future.

As for UI support, I think it is a niche use case, and at the moment, there are no plans to prioritise its implementation. However, high-quality pull requests for this feature are welcome. I'm going to keep this issue open, marked as a low priority enhancement.

**Comment by prashantchothani** [comment]
This feature is very useful and is now default in all players and apps. MPEG-DASH trick play adaptation set if available, then the Player UI should have this functionality.

**Comment by tonihei** [comment]
https://github.com/google/ExoPlayer/issues/3752 is a catch-all feature tracker for trick-play related logic. If you look at the list in https://github.com/google/ExoPlayer/issues/3752#issuecomment-1147346684, it also includes the UI elements for it. I think we can duplicate this issue against the other one given they are all part of the larger effort to support trick play in the player.

**Comment by prashantchothani** [comment]
@tonihei in exoplayer2 the feature tracker was finished and there was a PR merged for work done by fraunhoferfokus as below:

https://github.com/google/ExoPlayer/pull/10793

Is this available in Media3 as well, since Media3 continues after Exoplayer versions ?

**Comment by icbaker** [comment]
@prashantchothani The media3 and exoplayer2 code bases have a single source-of-truth, so changes in exoplayer2 are mirrored in media3. In this specific case, https://github.com/google/ExoPlayer/pull/10793 is merged in media3 in https://github.com/androidx/media/commit/c6569a36fbce6fc3ece55c9a904508bd4a4c45da and that was then cherrypicked into the 1.0.0-rc01 release in https://github.com/androidx/media/commit/d49bd456b695c5d289b2e05dfcf6d03cb5fe20fe.

**Comment by prashantchothani** [comment]
@icbaker Thanks a lot for letting me know this. Does that mean that if the manifest has the Image Adaptation Sets Track, the Thumbails would appear onScrubbing when we use media3 ? Thanks once again in advance.

**Comment by tonihei** [comment]
So far we also parse the image track information from the manifest and nothing more. The remaining improvements are tracked by https://github.com/google/ExoPlayer/issues/3752#issuecomment-1147346684 as pointed out above.
