### ISSUE TITLE
Play Fails with NO_EXCEEDS_CAPABILITIES

### ISSUE THREAD

**Issue by sridhard** [androidx/media#372]
### Media3 Version

ExoPlayer 2.17.1

### Devices that reproduce the issue

Samsung galaxy F22

### Devices that do not reproduce the issue

It reproduces in few devices. Other devices it works fine

### Reproducible in the demo app?

Yes

### Reproduction steps

we are using DASH. We have 2 DASH videos.

**DASH Stream-1**
   ```
   <Representation id="1" bandwidth="1545324" codecs="avc1.42c01e" mimeType="video/mp4" sar="1:1" width="1002" height="540">
        <BaseURL>vAQStream.mp4</BaseURL>
        <SegmentBase indexRange="1595-23130" timescale="12800">
          <Initialization range="0-1594"/>
        </SegmentBase>
      </Representation>
      <Representation id="2" bandwidth="2341434" codecs="avc1.42c01e" mimeType="video/mp4" sar="1:1" width="1336" height="720">
        <BaseURL>vMQStream.mp4</BaseURL>
        <SegmentBase indexRange="1591-23126" timescale="12800">
          <Initialization range="0-1590"/>
        </SegmentBase>
      </Representation>
      <Representation id="3" bandwidth="4402202" codecs="avc1.42c01e" mimeType="video/mp4" sar="1:1" width="2004" height="1080">
        <BaseURL>vHQStream.mp4</BaseURL>
        <SegmentBase indexRange="1595-23130" timescale="12800">
          <Initialization range="0-1594"/>
        </SegmentBase>
      </Representation>
```

**Dash Stream 2**
  ```
    <Representation id="1" bandwidth="1520198" codecs="avc1.42c01e" mimeType="video/mp4" sar="1:1" width="852" height="480">
        <BaseURL>vAQStream.mp4</BaseURL>
        <SegmentBase indexRange="1593-17368" timescale="12800">
          <Initialization range="0-1592"/>
        </SegmentBase>
      </Representation>
      <Representation id="2" bandwidth="1848876" codecs="avc1.42c01e" mimeType="video/mp4" sar="1:1" width="960" height="540">
        <BaseURL>vMQStream.mp4</BaseURL>
        <SegmentBase indexRange="1593-17368" timescale="12800">
          <Initialization range="0-1592"/>
        </SegmentBase>
      </Representation>
      <Representation id="3" bandwidth="2742682" codecs="avc1.42c01e" mimeType="video/mp4" sar="1:1" width="1280" height="720">
        <BaseURL>vHQStream.mp4</BaseURL>
        <SegmentBase indexRange="1589-17364" timescale="12800">
          <Initialization range="0-1588"/>
        </SegmentBase>
      </Representation>
```

Dash Stream 2 has max resolution of 720p and it plays properly
Dash stream 1 has  max resolution of 1080p and it gives NO_EXCEEDS_CAPABILITIES

### Expected result

As per the error, device does not have the capability to play 1080p video. But the dash stream has 720p and 540p videos which should be played.

### Actual result

Play fails with exception:
```
 exception e = {"error":{"errorStackTrace":"com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(3, null, null, video/avc, avc1.42C01E, 1266088, null, [2242, 1080, 25.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:575)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loopOnce(Looper.java:226)\n\tat android.os.Looper.loop(Looper.java:313)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\nCaused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: c2.mtk.avc.decoder.secure\n\tat com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1512)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:813)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)\n\t... 4 more\nCaused by: android.media.MediaCodec$CodecException: Error 0x80000000\n","errorCode":"24003","errorException":"MediaCodecVideoRenderer error, index=0, format=Format(3, null, null, video/avc, avc1.42C01E, 1266088, null, [2242, 1080, 25.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES","errorString":"ExoPlaybackException: ERROR_CODE_DECODING_FAILED"}}
1683022356509 : Info in 'onError()' of 'lplayer: StreamingPlayer' : STREAMING_PLAYER_EXCEPTION:12 : code = -1
                subErrCode = -1
                errString = ExoPlaybackException: ERROR_CODE_DECODING_FAILED
                funcName = react-native-video
                exceptionTrace = MediaCodecVideoRenderer error, index=0, format=Format(3, null, null, video/avc, avc1.42C01E, 1266088, null, [2242, 1080, 25.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES

```

### Media

This issue happens for any 1080p media is some devices

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment]
Do you have a stream for us so we can look into this when seeing the media playing? 

If you're unable to share test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #372" Please also update this issue to indicate you’ve done this.

**Comment by sridhard** [comment]
@marcbaechinger the stream is encrypted with widevine drm. Can I share the drm stream? or how you want to share the details?

**Comment by marcbaechinger** [comment]
Of courese! You can share the json snippet that you used when you tested with the demo app. We can then just copy and paste for testing.

**Comment by sridhard** [comment]
@marcbaechinger we have done more testing. We have tested encrypted(widevine) and unencrypted version of same DASH stream. Below are the streams

Unencrypted Stream: 
https://learnyst-content-mumbai.s3.ap-south-1.amazonaws.com/issue/unencrypted/unbbdb5ae3b4e20d/ndrm/audio_video/stream.mpd

Encrypted Stream:
https://learnyst-content-mumbai.s3.ap-south-1.amazonaws.com/issue/unencrypted/en38af1df7b64a49/sdrm/cbcs/audio_video/stream.mpd

1. Unencrypted DASH stream plays with no issue
2. Encrypted stream fails with error NO_EXCEEDS_CAPABILITIES

Widevine DRM we are using is L3 DRM.

Thanks
Sridhar

**Comment by marcbaechinger** [comment]
Thanks! Do we need a license URI to play the encrypted stream?

In the [demo app we are using such json snippets:](https://github.com/androidx/media/blob/release/demos/main/src/main/assets/media.exolist.json#L33) 

```
{
        "name": "HD (cenc)",
        "uri": "https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears.mpd",
        "drm_scheme": "widevine",
        "drm_license_uri": "https://proxy.uat.widevine.com/proxy?video_id=2015_tears&provider=widevine_test"
      },
```

So I think we'd need a `drm_license_uri` to be able to test the encrypted stream where the problem exhibits.

If you're unable to share test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #372". Please also update this issue to indicate you’ve done this.

**Comment by sridhard** [comment]
@marcbaechinger below are the details of encrypted stream:
{
"name": "Issue Debug Stream",
"uri": "https://learnyst-content-mumbai.s3.ap-south-1.amazonaws.com/issue/exoissuedebug/stream.mpd",
"drm_license_uri": "https://drm-u-beta.learnyst.com/lic",
"drm_scheme" :"widevine"
}

Please note that the same stream unencrypted version will play properly. Only widevine encrypted stream is giving issue.
Also the issue is reproducible only on few mobiles like samsung galaxy F22.

Thanks

**Comment by sridhard** [comment]
@marcbaechinger we have tested the encrypted stream in chrome browser in shaka player. The encrypted stream is playing in chrome browser shaka player.

Please let me know if you need any more details

**Comment by marcbaechinger** [comment]
Thanks! Yes, I can play this media with DRM on a Pixel 6. So it seems indeed to be device specific.

If you have such a device at hand, can you please do a bugreport so we have all the information available.

@rrfrias What is the procedure for a device-specifc problem with Samsung devices? Can you have a quick look and advise, please?

**Comment by sridhard** [comment]
@rrfrias can you please help us

**Comment by microkatz** [comment]
@sridhard.

Would you be able to provide a [bug report](https://developer.android.com/studio/debug/bug-report) with your issue to provide us with logs? If you're unable to share it publicly then please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #372". Please also update this issue to indicate you've done this.

**Comment by rrfrias** [comment]
Side note: Opened internal tracker [281917583](http://b/281917583) to reproduce and follow up with Samsung. It will take a while for devices to be updated with any potential fix, so this should not distract from a workaround/request for a bugreport.

**Comment by sridhard** [comment]
@rrfrias @microkatz @marcbaechinger please find the attached bug report. Since we dont have the device it took time to get the bug report.

https://learnyst-content-mumbai.s3.ap-south-1.amazonaws.com/exoissue/bugreport-f22ins-TP1A.220624.014-2023-05-18-18-04-40.zip

Please let mw know if you need more details

**Comment by sridhard** [comment]
> 281917583

@rrfrias till now we have seen thus issue in samsung galaxy F22 only. Also the issue exist for widevine encrypted content only. Exoplayer is able to play the unencrypted content. Also in chrome browser, shaka player is able to play both encrypted and unencrypted content.

Same video works in other devices like redmi, oppo etc.

**Comment by sridhard** [comment]
@rrfrias @microkatz @marcbaechinger have you got any clue from the bugreport?

**Comment by microkatz** [comment]
@sridhard.

I was able to look at the bug report. Were you using the demo app when taking the logs? I don't see any of our EventLogger trace lines. If you are using your own app then you enable the debug logging by adding this 
```
player.addAnalyticsListener(new EventLogger());
```
This is described in [Debug Logging](https://exoplayer.dev/debug-logging.html)

As far as your question below from earlier:
>Is there any way the application can remove the unsupported resolutions? Or any way where application can remove the resolutions which are greater than 720p always?

You can play with TrackSelectionOverrides in order to mandate a maximum resolution for your problem device. This is described [here](https://exoplayer.dev/track-selection.html#modifying-track-selection-parameters). You can set the track selection parameters specifically for when your application is playing on that Samsung device. 

Comment back if you have any questions!

**Comment by microkatz** [comment]
@sridhard.

Our partners looking into the bug have had issues with testing. The media you provided seems to no longer be accessible. The key you provided may no longer be valid. Could you supply another sample of content that reproduces the issue?

**Comment by sridhard** [comment]
@microkatz 

This happens with any 1080p stream (width>"2004" height="1080") . We have removed 1080p stream since the video was not playing. I will prepare new streams.

Also I have one query. We are encoding 1080p with H264 baseline level 3 profile. But I think as per H264 standard it should be level 4.2. Does the android player has strict restrictions on the profile level? We are encoding in baseline profile because some android devices still doesnot support high profile

Thanks

**Comment by sridhard** [comment]
@microkatz can you pls help

**Comment by microkatz** [comment]
@sridhard

We do run checks on profile and resolution. As far as I can tell in our code, for when running below Android 21, the format support check will fail for your 1080p stream for H264. For above 21, we run through some Android framework APIs to check profile and resolution support. Though I would expect the new behavior would be the same. Does ExoPlayer play the H264 stream successfully? In the trace logs, does it say whether format is handled or not?

**Comment by sridhard** [comment]
@microkatz Suppose we encode a 1080p video in baseline3.0 resolution, then most of the devices are playing the content. Only few devices like Samsung galaxy F22 are giving error.

Can you tell me what kind of profile and resolution check will be done by exoplayer and android? If these checks are there then the video play should fail in all devices correct? Or as per the specification H264 baseline profile level 3 support 1080p video?

**Comment by microkatz** [comment]
@sridhard

Below are the code snippets in ExoPlayer that run the resolution checks
[MediaCodecInfo.java](https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/mediacodec/)
Method: *isFormatSupported*
*isFormatSupported*, if the framework version is above 29, it will check the [MediaCodecInfo.VideoCapabilities.PerformancePoint](https://developer.android.com/reference/android/media/MediaCodecInfo.VideoCapabilities.PerformancePoint). If the decoder says it supports the format then it should support it.

If the check fails but there is not any other stream or resolution to play, then ExoPlayer may try to play that format anyway. That may be why you see some devices succeed in playing that content. I would be able to tell more about the decoder support check if you send trace logs. 

If play fails with NO_EXCEEDS_CAPABILITIES then that's by design. The device said it cannot play that format and then also fails to play that format. That is not a bug.

**Comment by sridhard** [comment]
@microkatz @rrfrias this issue is happening in xiaomi redmi note 12 also. Play fails with NO_EXCEEDS_CAPABILITIES.

Device is the latest device and has 1080p support. Can you tell how to debug this issue?

**Comment by sridhard** [comment]
@microkatz @rrfrias any update on this issue?

**Comment by rrfrias** [comment]
@sridhard can you send a bugreport for the Xioami Redmi Note 12. Instructions [here](https://github.com/androidx/media/issues/372#issuecomment-1539966664)

**Comment by HMT2002** [comment]
I encounter this problems today. It seems like because the different between video codec, 'cause I have 2 urls and one of them worked fine.
Working url: http://34.87.76.48/videos/Rm4gz1GDash/init.mpd
NO_EXCEEDS_CAPABILITIES url: http://34.87.76.48/videos/N0PIosNDash/init.mpd
Both is H264 and AAC. The different is the pixel format, the working url is yuv420p, while NO_EXCEEDS_CAPABILITIES using yuv420p10. My device is Samsung btw.

**Comment by rrfrias** [comment]
Hi @HMT2002 , This is very interesting. Can you attach a bgreport that includes the failure and follow [these instructions](https://github.com/androidx/media/issues/372#issuecomment-1539966664)
