### ISSUE TITLE
How to set start position?

### ISSUE THREAD

**Issue by chientrm** [androidx/media#373]
I'm playing audio from `URL`.

I see that we can use `seekTo` but the player is required to be playing first.

How do I start playing audio stream with the start position set at the beginning without additional seeking? 🤔

**Comment by marcbaechinger** [comment]
The shortest way the API offers is:

```
MediaItem mediaItemWithAudioStream = MediaItem.fromUri(audioUri);
player.setMediaItems(mediaItemWithAudioStream, /* startPositionMs= */ 10_000);
player.prepare();
player.play();
```

> I see that we can use seekTo but the player is required to be playing first.

The player isn't required to be playing first. You can easily do:

```
MediaItem mediaItemWithAudioStream = MediaItem.fromUri(audioUri);
player.setMediaItem(mediaItemWithAudioStream);
player.prepare();
player.seekTo(10_000); // seek to 10 sec

[...]

player.play(); // can be called later also and starts at 10_000
```

**Comment by chientrm** [comment]
> The shortest way the API offers is:
> 
> ```
> MediaItem mediaItemWithAudioStream = MediaItem.fromUri(audioUri);
> player.setMediaItem(mediaItemWithAudioStream, /* startPositionMs= */ 10_000);
> player.prepare();
> player.play();
> ```
> 
> > I see that we can use seekTo but the player is required to be playing first.
> 
> The player isn't required to be playing first. You can easily do:
> 
> ```
> MediaItem mediaItemWithAudioStream = MediaItem.fromUri(audioUri);
> player.setMediaItem(mediaItemWithAudioStream);
> player.seekTo(10_000); // seek to 10 sec
> player.prepare();
> 
> [...]
> 
> player.play(); // can be called later also and starts at 10_000
> ```

I wonder if these strategies require at least 2 http requests to the streaming server?

The first request is for bitrate determination so that the player can calculate the `Range` header for the second request? 🤔

**Comment by chientrm** [comment]
> The shortest way the API offers is:
> 
> ```
> MediaItem mediaItemWithAudioStream = MediaItem.fromUri(audioUri);
> player.setMediaItem(mediaItemWithAudioStream, /* startPositionMs= */ 10_000);
> player.prepare();
> player.play();
> ```
> 
>  > I see that we can use seekTo but the player is required to be playing first.
> 
> The player isn't required to be playing first. You can easily do:
> 
> ```
> MediaItem mediaItemWithAudioStream = MediaItem.fromUri(audioUri);
> player.setMediaItem(mediaItemWithAudioStream);
> player.seekTo(10_000); // seek to 10 sec
> player.prepare();
> 
> [...]
> 
> player.play(); // can be called later also and starts at 10_000
> ```

You can see here it costs me 1 extra request (the first line with result code `200`) to start playing the streaming audio. After that, any `seekTo` will just cost 1 request which results as `206` response. 🤔 

<img width="349" alt="Screen Shot 2023-05-03 at 11 45 47 AM" src="https://user-images.githubusercontent.com/70304839/235834384-16ee301d-a21d-454b-89ab-ead4bad18f5f.png">

Is there anyway to start playing the audio directly with only 1 request at the beginning?
