### ISSUE TITLE
DashMediaSource make crash

### ISSUE THREAD

**Issue by FongMi** [androidx/media#380]
### Media3 Version

Media3 1.0.1

### Devices that reproduce the issue

![image](https://user-images.githubusercontent.com/3471963/236423462-691b57b6-c037-4a33-a7d7-08dcf6a383b0.png)

### Reproducible in the demo app?

Yes

### Reproduction steps

1. play mpd file

### Expected result

Don' crash

### Actual result

Crash

### Media

local file

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by FongMi** [comment]
Here is gradle version
![image](https://user-images.githubusercontent.com/3471963/236423819-9ef55755-8406-4b53-9b44-ce797c990127.png)
![image](https://user-images.githubusercontent.com/3471963/236423859-a094916b-2fcb-4b80-b02d-dfe7a0b06d15.png)

**Comment by FongMi** [comment]
I have add this line to my proguard, and works
`-keep class org.xmlpull.v1.** { *; }`

**Comment by marcbaechinger** [comment]
I can not repro this. Probably also because you didn't declare repro steps.

It looks like it works now. Can we close this issue?
