### ISSUE TITLE
Is it possible to use Media3 Transformer in a WorkManager Worker?

### ISSUE THREAD

**Issue by gdingenen** [androidx/media#381]
### Media3 Version
Media3 1.0.1

I'm trying to use Transformer in a WorkManager Worker. But the Transformer is accessed on the wrong thread.

Is it possible to run androidx.media3.transformer.Transformer.startTransformation() from a WorkManager CoroutineWorker?

**Comment by kim-vde** [comment]
`Transformer.startTransformation()` must be call from a looper thread.

By default, this thread is the thread used to build the Transformer instance. If this thread doesn't have a looper, it is the application's main thread.

If you want to call `Transformer.startTransformation()` from another thread, you need to pass the associated looper to [`Transformer.Builder.setLooper()`](https://github.com/androidx/media/blob/1.1.0-alpha01/libraries/transformer/src/main/java/androidx/media3/transformer/Transformer.java#L326).

Hope this helps.
