### ISSUE TITLE
Stutter Playback on Livestream DRM

### ISSUE THREAD

**Issue by FadillahMozhaiq** [androidx/media#385]
### Media3 Version

Media3 1.0.1

### Devices that reproduce the issue

- Samsung A31 running on Android 12
- Xiaomi Poco M4 Pro running on Android 11
- Asus Zenfone Max Pro M1 running on Android 9

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Watch Livestream DRM Video

### Expected result

The media play smooth

### Actual result

Stutter occurs

### Media

Will be sent to email dev.exoplayer@gmail.com

### Bug Report

- [x] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by FadillahMozhaiq** [comment]
Hi, is there anything I can help to investigate this issue?
hope this may help the investigation, there are several `audioTrackUnderrun` on the log

```
05-04 10:18:46.486 10351 10506 10506 E EventLogger: audioTrackUnderrun [eventTime=16.54, mediaPos=23.04, window=0, period=0, 120832, 684, 33]
05-04 10:18:46.507  1000   783  1170 E PQ      : [PQ][PQSessionManager] PQSessionManager::getPQSession m_PQSupport == 0
05-04 10:18:46.538  1041   825  1409 I SoundAlive_SRC384 arch64: SoundAlive_SRC384: Instance 1194 Init(outFs 8, InFs 7, chnum 2, outBW 3, inBW 3)
05-04 10:18:46.538  1041   825  1409 I Samsung_SoundAlive_SRC arch64: SRC384 version Samsung SoundAlive SRC ver320 arch64  2021.08.04 (Cppref for ARM64, ver.300.c 32bit 07_10_2016 based)
05-04 10:18:46.540  1000   783  1170 E PQ      : [PQ][PQSessionManager] PQSessionManager::getPQSession m_PQSupport == 0
05-04 10:18:46.554 10351 10506 10506 E EventLogger: audioTrackUnderrun [eventTime=16.61, mediaPos=23.11, window=0, period=0, 120832, 684, 30]
05-04 10:18:46.566 10045  1835  1930 D NetworkController: SignalStrength from intent slotId=0
05-04 10:18:46.566 10045  1835  1930 D NetworkController.MobileSignalController(0/2147483647): new mSignalStrength=SignalStrength:{mCdma=Invalid,mGsm=CellSignalStrengthGsm: rssi=-69 ber=2147483647 mTa=0 mLevel=4,mWcdma=Invalid,mTdscdma=Invalid,mLte=Invalid,mNr=Invalid,SignalBarInfo{ gsmLevel=4 },rat=16,primary=CellSignalStrengthGsm}
05-04 10:18:46.566 10045  1835  1930 D NetworkController.MobileSignalController(0/2147483647): Display signal bar by emergency only[true][true]
05-04 10:18:46.574  1000   783  1170 E PQ      : [PQ][PQSessionManager] PQSessionManager::getPQSession m_PQSupport == 0
05-04 10:18:46.576  1000  1433  1718 D SemNscXgbMsL1: Probability - Cloud gaming: [0.007305817]
05-04 10:18:46.576  1000  1433  1718 D SemNscXgbMsL1: Probability - Real time: [0.22444561]
05-04 10:18:46.576  1000  1433  1718 D SemNscXgbMsL1: Probability - Non real time: [0.9578367]
05-04 10:18:46.576  1000  1433  1718 D SemNscXgbMsL1: 1 sample inference time: 0.616615 msecs
05-04 10:18:46.577  1000  1433  1718 D SemNscXgbL2Rt: L2 RT 1 sample inference time: 0.673846 msecs
05-04 10:18:46.578  1000  1433  1718 D SemNscXgbL2Nrt: L2 NRT 1 sample inference time: 1.192615 msecs
05-04 10:18:46.602  1041   825  1409 I SoundAlive_SRC384 arch64: SoundAlive_SRC384: Instance 1194 Init(outFs 8, InFs 7, chnum 2, outBW 3, inBW 3)
05-04 10:18:46.602  1041   825  1409 I Samsung_SoundAlive_SRC arch64: SRC384 version Samsung SoundAlive SRC ver320 arch64  2021.08.04 (Cppref for ARM64, ver.300.c 32bit 07_10_2016 based)
05-04 10:18:46.608  1000   783  1170 E PQ      : [PQ][PQSessionManager] PQSessionManager::getPQSession m_PQSupport == 0
05-04 10:18:46.615 10351 10506 10506 E EventLogger: audioTrackUnderrun [eventTime=16.67, mediaPos=23.17, window=0, period=0, 120832, 684, 32]
05-04 10:18:46.641  1000   783  1170 E PQ      : [PQ][PQSessionManager] PQSessionManager::getPQSession m_PQSupport == 0
05-04 10:18:46.667  1041   825  1409 I SoundAlive_SRC384 arch64: SoundAlive_SRC384: Instance 1194 Init(outFs 8, InFs 7, chnum 2, outBW 3, inBW 3)
05-04 10:18:46.667  1041   825  1409 I Samsung_SoundAlive_SRC arch64: SRC384 version Samsung SoundAlive SRC ver320 arch64  2021.08.04 (Cppref for ARM64, ver.300.c 32bit 07_10_2016 based)
05-04 10:18:46.675  1000   783  1170 E PQ      : [PQ][PQSessionManager] PQSessionManager::getPQSession m_PQSupport == 0
05-04 10:18:46.679 10351 10506 10506 E EventLogger: audioTrackUnderrun [eventTime=16.73, mediaPos=23.24, window=0, period=0, 120832, 684, 31]
05-04 10:18:46.708  1000   783  1170 E PQ      : [PQ][PQSessionManager] PQSessionManager::getPQSession m_PQSupport == 0
05-04 10:18:46.730  1041   825  1409 I SoundAlive_SRC384 arch64: SoundAlive_SRC384: Instance 1194 Init(outFs 8, InFs 7, chnum 2, outBW 3, inBW 3)
05-04 10:18:46.731  1041   825  1409 I Samsung_SoundAlive_SRC arch64: SRC384 version Samsung SoundAlive SRC ver320 arch64  2021.08.04 (Cppref for ARM64, ver.300.c 32bit 07_10_2016 based)
05-04 10:18:46.736 10351 10506 10506 E EventLogger: audioTrackUnderrun [eventTime=16.79, mediaPos=23.30, window=0, period=0, 120832, 684, 30]
05-04 10:18:46.741  1000   783  1170 E PQ      : [PQ][PQSessionManager] PQSessionManager::getPQSession m_PQSupport == 0
05-04 10:18:46.775  1000   783  1170 E PQ      : [PQ][PQSessionManager] PQSessionManager::getPQSession m_PQSupport == 0
05-04 10:18:46.809  1000   783  1170 E PQ      : [PQ][PQSessionManager] PQSessionManager::getPQSession m_PQSupport == 0
05-04 10:18:46.842  1000   783  1170 E PQ      : [PQ][PQSessionManager] PQSessionManager::getPQSession m_PQSupport == 0
05-04 10:18:46.846  1041   825  1409 I SoundAlive_SRC384 arch64: SoundAlive_SRC384: Instance 1194 Init(outFs 8, InFs 7, chnum 2, outBW 3, inBW 3)
05-04 10:18:46.846  1041   825  1409 I Samsung_SoundAlive_SRC arch64: SRC384 version Samsung SoundAlive SRC ver320 arch64  2021.08.04 (Cppref for ARM64, ver.300.c 32bit 07_10_2016 based)
05-04 10:18:46.859  1000   783  1170 E PQ      : [PQ][PQSessionManager] PQSessionManager::getPQSession m_PQSupport == 0
05-04 10:18:46.870 10351 10506 10506 E EventLogger: audioTrackUnderrun [eventTime=16.92, mediaPos=23.41, window=0, period=0, 120832, 684, 53]
05-04 10:18:46.893  1000   783  1170 E PQ      : [PQ][PQSessionManager] PQSessionManager::getPQSession m_PQSupport == 0
05-04 10:18:46.959  1000   783   783 I hwcomposer: [HWCDisplay] [Display_0 (type:1)] fps:36.262115,dur:1020.35,max:34.27,min:13.30  
05-04 10:18:46.960  1000   783  1170 E PQ      : [PQ][PQSessionManager] PQSessionManager::getPQSession m_PQSupport == 0
05-04 10:18:46.972  1041   825  1409 I SoundAlive_SRC384 arch64: SoundAlive_SRC384: Instance 1194 Init(outFs 8, InFs 7, chnum 2, outBW 3, inBW 3)
05-04 10:18:46.972  1041   825  1409 I Samsung_SoundAlive_SRC arch64: SRC384 version Samsung SoundAlive SRC ver320 arch64  2021.08.04 (Cppref for ARM64, ver.300.c 32bit 07_10_2016 based)
05-04 10:18:46.996 10351 10506 10506 E EventLogger: audioTrackUnderrun [eventTime=17.05, mediaPos=23.50, window=0, period=0, 120832, 684, 52]
```

More detail log in bug report also already sent to dev.exoplayer@gmail.com,
Looking forward for your response, thanks in advance.

**Comment by tonihei** [comment]
I'm not sure if it's the same issue, but on some devices decryption slows down the decoding process and we added an asynchronous mode to ExoPlayer's renderer that should help with this general symptom. It's automatically enabled on devices with API >= 31 and you can manually enable it on lower API versions by calling DefaultRenderersFactory.forceEnableMediaCodecAsynchronousQueueing() (and pass this DefaultRenderersFactory to ExoPlayer.Builder.setRenderersFactory). See https://github.com/google/ExoPlayer/issues/6348 where this was originally reported.

**Comment by FadillahMozhaiq** [comment]
Thanks for replying @tonihei
Actually, I'm aware of the forceEnableMediaCodecAsynchronousQueueing() API, after attempting to implement those API, unfortunately, the playback is still experiencing stutter.

Also, we already tried several things as well. One thing that comes to mind is that it might be caused by performance stuff, so we attempt to set up several modes to adjust performance issues. We're following the guide from [here](https://websites.fraunhofer.de/video-dev/solving-exoplayer-rendering-performance-issues/)

We also attempt to expand the buffer by customizing the LoadControl. Please see the code below:
```
val loadControl = DefaultLoadControl.Builder()
            .setBufferDurationsMs(
                10_000,
                DefaultLoadControl.DEFAULT_MAX_BUFFER_MS,
                DefaultLoadControl.DEFAULT_BUFFER_FOR_PLAYBACK_MS,
                DefaultLoadControl.DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS
            )
            .setPrioritizeTimeOverSizeThresholds(true)
            .build()
```

And last, we thought it might be due to hardware decoder issues, so we forced the playback to Widevine L3, yet still stuttered.

**Comment by tonihei** [comment]
Do you have similar streams or other DRM-protected streams (e.g. from the ExoPlayer demo app) you can try? There is a chance that there is something wrong with the media itself. Also, are there any devices where it works well? (If not, then it's very likely a media issue).

**Comment by FadillahMozhaiq** [comment]
I have sent a new link to the bug report via email. Please check your inbox for the updated access to the Google Drive.

We don't have any special configuration in `DefaultLoadControl`. The DefaultLoadControl that we previously shared was an attempt to fix the issue, but it didn't resolve it. If there is a possibility that the issue is related to the LiveStream content, we will try to generate the Stream URL and send it via email for further testing.

**Comment by tonihei** [comment]
Thanks for the bugreport. I can see the same logs you already shared above, but no other particularly interesting log lines. It still looks like playback is trying to continue too early before we have enough buffer available. If you have a stream URL for testing, that would be ideal to debug this further.

**Comment by FadillahMozhaiq** [comment]
Here is the Link: [Stream](https://www.vidio.com/live/6299-bein-1) and [MPD](https://etslive-2-vidio-com.akamaized.net/drm/dash/6299_stream.mpd)
Unfortunately, DRM Secret has 10 minutes expiry duration and we cannot extend its expiration duration.

So, the issue only occurs with DRM-protected content. We have consulted with our DRM partner but have yet to find any solution. 
No issue was found in the license issuance process from the DRM partner.

**Comment by tonihei** [comment]
I can't access the MPD unfortunately (also tried with VPN to Indonesia). You can also send files and links to [android-media-github@google.com](mailto:android-media-github@google.com) with "Issue #385" in the subject if needed.

**Comment by FadillahMozhaiq** [comment]
Okay, just sent the mpd files through the email android-media-github@google.com

**Comment by tonihei** [comment]
I'm afraid I'm still getting Access Denied messages when opening the URL.

**Comment by FadillahMozhaiq** [comment]
Hi @tonihei ,
Can you open the attachment File? Or do you need to access the URL directly?

**Comment by tonihei** [comment]
Sorry, I didn't see the attachment, only the link in the email! I checked the manifest now and it looks fairly normal with nothing unusual or suspicious. 

I'm afraid that means I can help you further if I have proper access to the live stream (and use one of the mentioned devices) to reproduce myself. The problem is likely in the DRM management, in the media or how the AudioTrack is configured. 

Two things you could try to debug this further are:
 1. Debug `DefaultLoadControl.shouldStartPlayback` to see at which `bufferedDurationUs` it returns false. The value shouldn't be too close to zero. 
 2. Override `DefaultRenderersFactory.buildAudioSink`, create the default one (using `super.buildAudioSink`) and then use `setAudioTrackBufferSizeProvider` on the `DefaultAudioSink` that sets a large buffer size. You can provide a `DefaultAudioTrackBufferSizeProvider` and set `setMinPcmBufferDurationUs` to something like two seconds (2_000_000) for example.

**Comment by FadillahMozhaiq** [comment]
Yes, unfortunately, DRM secret has only a 600s expiry time and also we cannot extend the duration due to global configuration for the entire content expiry time.

But, let's see if we could create one stream and we'll share it with you through email.

Thanks for the debug tips, I will get back to you with the debug result.

**Comment by FadillahMozhaiq** [comment]
Hi @tonihei,
We've tried to reproduce with the point 2 solution as you mentioned, but the stutter still exists

Also, we have put an information log on DefaultLoadControl as mentioned, here is the log on reproducing from the APK without `setMinPcmBufferDurationUs()`

```
2023-07-05 08:19:18.451 21110   275 I PLAYBACK: LoadControl: [shouldStartPlayback: true, bufferedDurationUs: 11166667, playbackSpeed: 1.0, rebuffering: false, targetLiveOffsetUs: -9223372036854775807
```

On using `setMinPcmBufferDurationUs()`, we found below log

```
2023-07-05 08:11:10.153 12236   251 I PLAYBACK: LoadControl: [shouldStartPlayback: false, bufferedDurationUs: 1933233, playbackSpeed: 1.0, rebuffering: false, targetLiveOffsetUs: -9223372036854775807
2023-07-05 08:11:10.158 12236   251 I PLAYBACK: LoadControl: [shouldStartPlayback: false, bufferedDurationUs: 1933233, playbackSpeed: 1.0, rebuffering: false, targetLiveOffsetUs: -9223372036854775807
2023-07-05 08:11:10.166 12236   251 I PLAYBACK: LoadControl: [shouldStartPlayback: true, bufferedDurationUs: 5904611, playbackSpeed: 1.0, rebuffering: false, targetLiveOffsetUs: -9223372036854775807
```

**Comment by tonihei** [comment]
Thanks for checking. Looks like we can discard problems with the `LoadControl` at least. 

I'll leave this issue open for now, but I think we can only make further progress if we can find a way for us to reproduce ourselves.

**Comment by FadillahMozhaiq** [comment]
Hi @tonihei,
I have sent an email with the stream URL to dev.exoplayer@gmail.com, please help to check,
Thank you

**Comment by tonihei** [comment]
Thanks for sharing the stream. I'm afraid I still only get 404 replies when trying to access this stream (also tested with VPN to Indonesia). Is there anything else needed besides the DRM config details you sent via email? The potentially short expiry also makes it quite hard to debug in general, because I won't be able to look into this immediately until I can get hold of one of the mentioned devices.

**Comment by FadillahMozhaiq** [comment]
Hi @tonihei ,

Thanks for checking the stream, 
Unfortunately, it should've already been terminated by our operation team.

We'll recreate the stream and reshare it for you. Anyway, do you mind sharing your availability time for checking the stream? 

The stream secret itself only can remain for 4 hours. So, it is best that we could set the stream to match your availability time.

**Comment by tonihei** [comment]
> We have conducted experiments on several LiveStreaming DRM contents in the ExoPlayer demo app and encountered the same issue

I re-discovered this comment. Are you saying that other DRM live streams show the same problem in the ExoPlayer demo app? Is there another stream you used for testing that is more easily shareable?

> The stream secret itself only can remain for 4 hours

This is really too restrictive for debugging. Even if we manage to reproduce the issue, there is hardly any time to investigate, fix and verify anything within this timeframe.

**Comment by tonihei** [comment]
I think the main hypothesis is still that the devices are just too slow to manage decoding and decryption at the same time. The observation that this happens only for live streams and not encrypted VOD content leaves the possibility that something else is going on too. One thing I haven't asked you about is which resolution and frame rate your test content is in. And whether the test content for the working VOD stream is any different in its resolutions and frame rate. Could you check these values to see if this may just be the difference? See also https://github.com/androidx/media/issues/544#issuecomment-1651540908 where a similar question has been addressed with links to the official limits that should be supported.

**Comment by FadillahMozhaiq** [comment]
We have now sent the content URL instead of the manifest URL. This content URL can also be used to obtain the manifest URL and DRM Token as explained in the email.

> One thing I haven't asked you about is which resolution and frame rate your test content is in. And whether the test content for the working VOD stream is any different in its resolutions and frame rate.

As for the resolution we already tested for resolution as low as 144p, and the Stutter still occurs.

**Comment by tonihei** [comment]
> Unfortunately our contents for DRM Livestream currently have single audio track for all of them.

The bug report shared with us had multiple audio tracks, hence my question. But it seems this is unrelated to the problem.

> We tried to do some additional testing with forcing L3 and disabling audio track and got following result for stutter status:

This is very helpful. If the problem can be solved with forcing L3, it may be some DRM issue, but it could also mean that not using the secure path does not trigger other problems because the device is using less CPU for example. I'll assign to @rrfrias for now to see if there is anything DRM-related that could be wrong here.

Rahul - the issue reporter shared a bugreport with our email alias (10th May) and a reliable way to play the stream (1 Aug) in separate emails.

**Comment by tonihei** [comment]
One other note: we already force L3 for Asus Zenfone 2 as a result of https://github.com/google/ExoPlayer/issues/4413. This is interesting because another Asus Zenfone is part of the mentioned devices.

**Comment by rrfrias** [comment]
Waiting on access to the bugreport.

**Comment by GilangJS** [comment]
Hi @rrfrias we've sent the bug report under subject `Issue #385` on May 10 and the link with updated permission in its reply on June 23.
Kindly provide your email address so I can forward it to you.

**Comment by GilangJS** [comment]
Hi @rrfrias is there any update regarding this?
We've turned off the test stream since there's no update from exoplayer team.
Kindly tell us in case you need the test stream.
Thanks

**Comment by rrfrias** [comment]
I took a look at the bugreport. There are no obvious issues. It seems surprising that the stutter issues might improve with L3 at high resolutions. 

Might it be possible to share a demo app to reproduce the problem. Will you be willing to give approval if we share the app with Samsung to investigate furthur?
