### ISSUE TITLE
Long opus buffers very slowly

### ISSUE THREAD

**Issue by PaulWoitaschek** [androidx/media#391]
### Media3 Version

Media3 1.0.1

### Devices that reproduce the issue

* Pixel 7 running Android 13
* Emulators

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Play the attached file in the demo app
2. Seek to hour 35

### Expected result

The playback start immediately

### Actual result

The playback doesn't start at all or starts after several minutes.

If in the range of < 20h the playback starts immediately on seeking. After the 25h mark it's getting very very slow.

### Media

Sent by mail

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by PaulWoitaschek** [comment]
Also see https://github.com/PaulWoitaschek/Voice/issues/1653 for the original bug report and some theories by @zsln

**Comment by christosts** [comment]
I can reproduce it with v1.0.1. There is a wrong calculation when calculating the seek point, a `long` is overflowing. I'll  prepare a fix.
