### ISSUE TITLE
has a Native Crash for ExoPlayer:Playb

### ISSUE THREAD

**Issue by Kasq-Lee** [androidx/media#395]
### Media3 Version

ExoPlayer 2.14.2

### Devices that reproduce the issue

I encountered a low-level error while using it, and I did not use the UI component. The main code is as follows:

```
DefaultRenderersFactory defaultRenderersFactory = new DefaultRenderersFactory(context);
        defaultRenderersFactory.setExtensionRendererMode(DefaultRenderersFactory.EXTENSION_RENDERER_MODE_PREFER);
        SimpleExoPlayer.Builder builder = new SimpleExoPlayer.Builder(context, defaultRenderersFactory);
        builder.setMediaSourceFactory(new DefaultMediaSourceFactory(new DefaultHttpDataSource.Factory().setConnectTimeoutMs(10000)));
        mPlayer = builder.build();

    private void initListener() {
        mPlayer.addListener(new Player.Listener() {
            @Override
            public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
              
            }

            @Override
            public void onPlayerError(@NonNull ExoPlaybackException error) {
              
            }
        });
    }
```

ABI: 'arm'
Timestamp: 2023-05-10 12:44:04-0400
pid: 751, tid: 4552, name: ExoPlayer:Playb
uid: 10065
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7ff91500
r0 80515da0 r1 7ff91500 r2 00000320 r3 00000020
r4 849e9978 r5 00000340 r6 00000340 r7 7ff91500
r8 b3ba4edc r9 b4d78200 r10 00000000 r11 00000000
ip 00000000 sp 849e9958 lr b3bc6e3b pc b0c68924

backtrace:
#00 pc 00060924 /apex/com.android.runtime/lib/bionic/libc.so (__memcpy_base_a55+124) (BuildId: 29bc0f9d4101e570b3fe12148d8fe2fc)
https://github.com/google/ExoPlayer/issues/1 pc 00046e37 /system/lib/libaudioclient.so (android::AudioTrack::write(void const*, unsigned int, bool)+266) (BuildId: 0e6541c880803e2edea73b4a5d4cc008)
https://github.com/google/ExoPlayer/issues/2 pc 000d8da5 /system/lib/libandroid_runtime.so (int writeToTrack(android::spandroid::AudioTrack const&, int, signed char const*, int, int, bool)+104) (BuildId: 6c99b8fea85d3283f1f3743253b051f0)
https://github.com/google/ExoPlayer/issues/3 pc 000d631b /system/lib/libandroid_runtime.so (android_media_AudioTrack_write_native_bytes(_JNIEnv*, _jobject*, _jobject*, int, int, int, unsigned char)+126) (BuildId: 6c99b8fea85d3283f1f3743253b051f0)
https://github.com/google/ExoPlayer/issues/4 pc 00db710b /system/framework/arm/boot-framework.oat (art_jni_trampoline+122) (BuildId: 8ebceaef13c8403faa1c5b383dd86cf1fc566ed2)
https://github.com/google/ExoPlayer/issues/5 pc 010848f7 /system/framework/arm/boot-framework.oat (android.media.AudioTrack.write+398) (BuildId: 8ebceaef13c8403faa1c5b383dd86cf1fc566ed2)
https://github.com/google/ExoPlayer/issues/6 pc 02028267 /memfd:jit-cache (deleted) (offset 0x2000000) (c.b.a.a.x1.z.Q+710)
https://github.com/google/ExoPlayer/issues/7 pc 0202af4f /memfd:jit-cache (deleted) (offset 0x2000000) (c.b.a.a.x1.z.J+190)
https://github.com/google/ExoPlayer/issues/8 pc 02023347 /memfd:jit-cache (deleted) (offset 0x2000000) (c.b.a.a.x1.z.g+4446)
https://github.com/google/ExoPlayer/pull/9 pc 0202b36f /memfd:jit-cache (deleted) (offset 0x2000000) (c.b.a.a.x1.c0.q0+254)
https://github.com/google/ExoPlayer/issues/10 pc 02029405 /memfd:jit-cache (deleted) (offset 0x2000000) (c.b.a.a.c2.u.T+1644)
https://github.com/google/ExoPlayer/issues/11 pc 020083db /memfd:jit-cache (deleted) (offset 0x2000000) (c.b.a.a.c2.u.v+298)
https://github.com/google/ExoPlayer/issues/12 pc 020210ab /memfd:jit-cache (deleted) (offset 0x2000000) (c.b.a.a.r0.d+4370)
https://github.com/google/ExoPlayer/pull/13 pc 02026c17 /memfd:jit-cache (deleted) (offset 0x2000000) (c.b.a.a.r0.handleMessage+2590)
https://github.com/google/ExoPlayer/issues/14 pc 02059227 /system/framework/arm/boot-framework.oat (android.os.Handler.dispatchMessage+110) (BuildId: 8ebceaef13c8403faa1c5b383dd86cf1fc566ed2)
https://github.com/google/ExoPlayer/pull/15 pc 0205baf1 /system/framework/arm/boot-framework.oat (android.os.Looper.loop+1376) (BuildId: 8ebceaef13c8403faa1c5b383dd86cf1fc566ed2)
https://github.com/google/ExoPlayer/pull/16 pc 0205ab73 /system/framework/arm/boot-framework.oat (android.os.HandlerThread.run+250) (BuildId: 8ebceaef13c8403faa1c5b383dd86cf1fc566ed2)
https://github.com/google/ExoPlayer/pull/17 pc 000d39d5 /apex/com.android.art/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: f3dcf6d85f63090693a2a803bf4230f2)
https://github.com/google/ExoPlayer/issues/18 pc 004eaf13 /apex/com.android.art/lib/libart.so (art_quick_invoke_stub+282) (BuildId: f3dcf6d85f63090693a2a803bf4230f2)
https://github.com/google/ExoPlayer/issues/19 pc 0012bd2d /apex/com.android.art/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+148) (BuildId: f3dcf6d85f63090693a2a803bf4230f2)
https://github.com/google/ExoPlayer/issues/20 pc 003f8777 /apex/com.android.art/lib/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValuesart::ArtMethod*(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+374) (BuildId: f3dcf6d85f63090693a2a803bf4230f2)
https://github.com/google/ExoPlayer/issues/21 pc 003f8887 /apex/com.android.art/lib/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+42) (BuildId: f3dcf6d85f63090693a2a803bf4230f2)
https://github.com/google/ExoPlayer/issues/22 pc 00439995 /apex/com.android.art/lib/libart.so (art::Thread::CreateCallback(void*)+1056) (BuildId: f3dcf6d85f63090693a2a803bf4230f2)
https://github.com/google/ExoPlayer/issues/23 pc 000aabb3 /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+40) (BuildId: 29bc0f9d4101e570b3fe12148d8fe2fc)
https://github.com/google/ExoPlayer/pull/24 pc 00064023 /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30) (BuildId: 29bc0f9d4101e570b3fe12148d8fe2fc)

### Reproducible in the demo app?

Yes

### Reproduction steps

I don't know how to reproduce it. It was randomly tested by monkeys

### Expected result

not has native crash

### Actual result

 has native crash

### Media

We cannot provide it, but you can find a network URL resource, which has no specific

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tianyif** [comment]
Hi @Kasq-Lee,

Could you please provide the information on what extension renderers you have configured and also a bug report? Could you please confirm if you sent the bug report to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) since I didn't find it.

**Comment by Kasq-Lee** [comment]
I send email for [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) and The theme is this title

**Comment by marcbaechinger** [comment]
Sorry I couldn't find an email with issue number 395 or the title of this issue. 

I think without further information and we/you being able to repro for instance with the demo app on different devices it will be difficult to  find the issue.

I'm closing for now. If you can repro again, please file a new issue. Below the standard blurb regarding filing a bug just for reference. Thanks.

Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.
