### ISSUE TITLE
Fast forward and rewind stuttering

### ISSUE THREAD

**Issue by BraveHL** [androidx/media#402]
I customized the layout, and then implemented the function of fast forward and rewind, I used some writing, but every time I jumped, it would freeze for more than 1 second, how to optimize, is it my problem, I put the command in Ctrip to execute, still stuttering

 player.seekTo(player.currentPosition + 10000)

            lifecycleScope.launch {
                player.seekTo(player.currentPosition - 10000)
            }

**Comment by tianyif** [comment]
Hi @BraveHL,

We'd like to help, but could you please describe your problem in more details? You can follow our [question template]( https://github.com/androidx/media/blob/release/.github/ISSUE_TEMPLATE/question.md) to start with. And if you think it is a bug with seeking, please create a bug with full details suggested by the [bug template](https://github.com/androidx/media/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug.yml).

I'm closing this one, please feel free to create a new issue with the completed information. Thanks!

**Comment by AndroidJohnsonWang** [comment]
I have the same problem
