### ISSUE TITLE
How to set a fixed resolution, such as smooth, SD, HD, etc

### ISSUE THREAD

**Issue by BraveHL** [androidx/media#403]
How to set a fixed resolution, such as smooth, SD, HD, etc., I am a novice exoplayer, I checked the information early, probably know to set through TrackSelector, I did not find a way to set the specific value in it, only the minimum and maximum value setting, please how to set

**Comment by tianyif** [comment]
Hi @BraveHL,

I don't think we have a setter that sets the specific value for a fixed resolution in `TrackSelectorParameter`. Would set minimum and maximum to the same value help?

**Comment by BraveHL** [comment]
> How to set a fixed resolution

So can I use other methods, manually set the resolution of the video, just like in youtube, in addition to automatic adjustment of the resolution, you can also set manually, my need is to set manually, if TrackSelectorParameter can not do it, this player has another way to achieve。

In addition, if I use TrackSelectorParameter and set its maximum and minimum values to the same, can the video being played dynamically switch the value of this parameter, and if so, how to write the code

**Comment by tianyif** [comment]
@BraveHL I'm not sure if I understood your question correctly. You can set the max and min video size via the [setters](https://developer.android.com/reference/androidx/media3/common/TrackSelectionParameters.Builder#setMaxVideoSize(int,int)) in `TrackSelectionParameters.Builder`. 

If at some point you just want to change some specific parameters, you can 

```
// Build on the current parameters.
TrackSelectionParameters currentParameters = player.getTrackSelectionParameters()
// Build the resulting parameters.
TrackSelectionParameters newParameters = currentParameters
    .buildUpon()
    .setMaxVideoSize(newVideoWidth, newVideoHeight)
    .setMinVideoSize(newVideoWidth, newVideoHeight)
    .build();
// Set the new parameters to the player.
player.setTrackSelectionParameters(newParameters);
```
Then `DefaultTrackSelector` will trigger the track re-selection based on the new parameters.

**Comment by BraveHL** [comment]
> 

For example, I want to add a button to switch the video bitrate in the player, you can switch to 360p, 720p, for example, when I select the 360p button, how should I let the player play a 360p video, and then switch to 720p, how to switch, please give me a simple example, in addition, when switching, the video cannot be paused or replayed from the beginning of the video

**Comment by icbaker** [comment]
> For example, I want to add a button to switch the video bitrate in the player, you can switch to 360p, 720p, for example, when I select the 360p button, how should I let the player play a 360p video, and then switch to 720p, how to switch, please give me a simple example, in addition, when switching, the video cannot be paused or replayed from the beginning of the video

The demo app does this, so you can read the code to understand how it's done: https://github.com/androidx/media/blob/release/demos/main/src/main/java/androidx/media3/demo/main/TrackSelectionDialog.java

There's more info on track selection here: https://developer.android.com/guide/topics/media/exoplayer/track-selection

As @tianyif has mentioned on your other issues, I'm afraid we don't have capacity to offer 1:1 support to individual developers. I think enough information has been provided in this issue to answer the question, so I'm going to close it.
