### ISSUE TITLE
How should I achieve preloading?

### ISSUE THREAD

**Issue by BraveHL** [androidx/media#404]
I am a novice exoplayer，How should I achieve preloading? I have rewritten a view to use exoplay. The custom features of androidx.media3.ui.PlayerView are too few to meet my needs. Then, when I play the same video, androidx.media3.ui.PlayerView can preload, but what I write cannot, which causes me to get very stuck during fast forward. Please help me

![}7SMT)9M769T@M29)PJQSGT](https://github.com/androidx/media/assets/22335503/631d66dc-f03d-4142-92cb-ac4b5f985e4b)
![1I B)V%0 _QX}FDN9AW@~IP](https://github.com/androidx/media/assets/22335503/3bf90f94-7d83-45f6-8577-4ae0c5b3bade)

**Comment by tianyif** [comment]
Unfortunately we can't give 1:1 support for solving app integration issues. If you think this is a problem with ExoPlayer, please narrow down your issue to describe the ExoPlayer behaviour that doesn't match your expectations and create a new issue with us.
