### ISSUE TITLE
What may be the reason for the blurred screen during video playback? it will not be spent on the second playback.

### ISSUE THREAD

**Issue by BraveHL** [androidx/media#405]
What may be the reason for the blurred screen during video playback? it will not be spent on the second playback.

**Comment by tianyif** [comment]
Hi @BraveHL,

If you think there is a bug with the video playback, could you please create a new issue with the detailed information? The issue template can be found [here](https://github.com/androidx/media/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug.yml). Thanks!
