### ISSUE TITLE
Datasource.Cache assumes Java.File access is available (doesn't work with SAF)

### ISSUE THREAD

**Issue by tzugen** [androidx/media#412]
### Media3 Version

Media3 1.1.0-alpha01

### Devices that reproduce the issue

All

### Reproduction steps

We would like to use the Media3 native CacheDatasource and Download Service.
This means that we need to implement a Cache. SimpleCache does not fit our purpose as we have already an elaborate cache system.

The problem is that the Cache interface, specifically `commitFile` and `startFile` assume that the app can use the Java.File interface. If the cache is outside of the internal app data directory this is not possible anymore in modern Android versions.

Our app offers the possibility to store the downloaded music in a user-choosen directory. This means we need to use the Storage Access Framework, so we never have a pointer to a Java.File.

If the API of the Cache  interface was designed so to accept simply generic InputStreams or OutputStreams, it would be usable indepent of which storage backend is being used.

### Expected result

----

### Actual result

---

### Media

----

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tzugen** [comment]
To add, CacheDataSink is already using FileOutputStreams to handle writing to the cache:
```
    file =
        cache.startFile(
            castNonNull(dataSpec.key), dataSpec.position + dataSpecBytesWritten, length);
    FileOutputStream underlyingFileOutputStream = new FileOutputStream(file);
```
If simply the act of turning a File (or Document or whatever) into a Stream was the task of the Cache itself and not of the DataSink, it would be easily adaptable.

**Comment by tonihei** [comment]
> If the cache is outside of the internal app data directory this is not possible anymore in modern Android versions

These classes were developed with app data directories in mind because the written files are not useful outside of the `CacheDataSource` and can't be opened directly by other apps for example. So I'm curious why your existing cache system lives outside of the app data space? This question doesn't solve your problem, but it's relevant to understand if you are using the right approach for what you'd like to achieve.

Independent of this question, your proposal sounds sensible to me. The only problem I see is that it removes some flexibility on the user side (e.g. in `CacheDataSink`) because it can no longer interact directly with the underlying `File` if needed.

**Comment by tonihei** [comment]
> When we cache data in Ultrasonic, we create human readable directories (Artist/Album/Track). For the users it's nice because they can playback the tracks they downloaded with any other player as well.

Thanks for clarifying this part. ExoPlayer's cache structure is not meant to be useful outside the app (=it doesn't just download the file as it is, but chooses to download chunks that are needed to be as efficient as possible). So it may not be easily possible to combine `CacheMediaSource` with an external file that is playable in another player too. How would you handle partial downloads, for example if the source only request bytes 1000-3000? 

Overall, it sounds to me as if your requirement could be better solved by a standard background task that simply downloads files to disk. And your app can then choose at the time playback starts whether to provide the local file URI or a remote URI to the player. The only thing that doesn't work with this approach is starting off with an online stream and then reusing the already loaded data for the downloaded file.
