### ISSUE TITLE
SimpleCache is not well extendable

### ISSUE THREAD

**Issue by tzugen** [androidx/media#413]
### Media3 Version

Media3 1.0.2

### Devices that reproduce the issue

I can extend SimpleCache, but it's contructor is using package-only classes such as `CachedContentIndex`  `CacheFileMetadataIndex`, and `SimpleCacheSpan`, so I cannot actually extend the class without copying a bunch of subclasses as well.

Suggestion: Remove /*package*/ annotation from these classes.

### Devices that do not reproduce the issue

All

### Reproducible in the demo app?

Yes

**Comment by tonihei** [comment]
Can you explain in a bit more detail what you are trying to achieve? `SimpleCache` is a `final` class, so I assume you want to wrap it and not extend it? If so, what prevents you from using the existing public constructors that only use publicly available types?
