### ISSUE TITLE
Build failures when using the media3 modules from an another gradle project

### ISSUE THREAD

**Issue by h6ah4i** [androidx/media#416]
### Media3 Version

Media3 1.0.2

### Devices that reproduce the issue

n/a

### Devices that do not reproduce the issue

n/a

### Reproducible in the demo app?

Not tested

### Reproduction steps

Recent changes by the following commit causes a build error when using the `core_settings.gradle` file from non-media3 project.

Commit: https://github.com/androidx/media/commit/0888dfbd05e1f22436137d93a67e56d06b8928

---

1. Create a new Android project
2. Clone the media3 repo locally
3. Modify `settings.gradle`  of the newly created project to use media3
    - :point_right: https://github.com/androidx/media#locally
4. `./gradlew`
5. Build error :boom: 

### Expected result

The media3 library modules can be used from other projects as written in README.

https://github.com/androidx/media#locally

> Next, add the following to your project's settings.gradle file, replacing path/to/media with the path to your local copy:
> 
> ```gradle
> gradle.ext.androidxMediaModulePrefix = 'media-'
> apply from: file("path/to/media/core_settings.gradle")
> ```

---

Also, setting `rootProject.name` in `core_settings.gradle` should be avoided because the file may be included from the non-media3 project's `settings.gradle` file. 

### Actual result

The following error occurs when running the gradle command. Also, in spite of it having already been configured by the user's `settings.gradle` file, the `rootProject.name` tried to be overwritten.

---

Gradle version: 7.4.2

```bash
$ ./gradlew
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

FAILURE: Build failed with an exception.

* Where:
Script '***/androidx-media/core_settings.gradle' line: 24

* What went wrong:
A problem occurred evaluating script.
> Cannot get property 'androidxMediaProjectName' on extra properties extension as it does not exist

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
```

### Media

n/a

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
Thanks for the report, and apologies for the trouble - I can repro the problem. I will send a fix internally to move `rootProject.name` assignment back from `core_settings.gradle` to `settings.gradle` so it won't get pulled in when you depend on this project locally - when it's published it will be linked here.
