### ISSUE TITLE
How to prevent re-requesting master playlist for HLS content?

### ISSUE THREAD

**Issue by NikSatyr** [androidx/media#429]
Our app serves video content over HLS, where the entry point is setting an HLS master playlist URL (.m3u8) to a `MediaItem`. Due to security concerns, the returned URL to the master playlist is expiring, and any request to this master playlist URL after a certain period of time will return 403 Forbidden. Our system architecture implies that the request to the master playlist should only be made once and then cached.

This results in a problem in a following scenario:
1. We start the video playback, the master playlist is consumed by the ExoPlayer, the content is playing fine
2. We wait for the master playlist URL to expire – after that we still can play the video fine
3. The player encounters a network error & the playback is stopped
4. After the connection is restored, the player tries to recover, which includes an under-the-hood request to the master playlist, which at this point returns 403 & cannot be recovered from

I've been digging into the `DefaultHlsPlaylistTracker` and I think the problem is coming from the [start method](https://github.com/androidx/media/blob/2fc189d6a40f116bd54da69ab9a065219f6973e7/libraries/exoplayer_hls/src/main/java/androidx/media3/exoplayer/hls/playlist/DefaultHlsPlaylistTracker.java#LL136C11-L136C11). The thing is recovering from a network error involves calling this once again apart from the initialization process, meaning this can occur after the URL has expired.

I doubt that this is a bug in the library but rather our app-specific requirements, but it would be nice if we could somehow customize caching of the master playlist. Or maybe I'm missing something and you could give me some other guidance? 

For now I'm trying to somehow use `CacheDataSource` in the described method (can be provided via constructor using a custom `HlsDataSourceFactory`) to avoid a network call once the playlist has been cached, but so far no luck. Seems like I might be lacking an understanding on how to apply the `DataSource` component.

**Comment by icbaker** [comment]
> For now I'm trying to somehow use `CacheDataSource` in the described method (can be provided via constructor using a custom `HlsDataSourceFactory`) to avoid a network call once the playlist has been cached, but so far no luck. Seems like I might be lacking an understanding on how to apply the `DataSource` component.

This is the approach I was going to suggest while reading the first part of your question.

Can you give a bit more detail about how you wired up this bit, in case there's something obvious we can help you with.

**Comment by NikSatyr** [comment]
Seems like there's a problem in a combination of our multiple `DataSource`s (we have a chain of `ResolvingDataSource` -> `CacheDataSource` -> `HttpDataSource` all sugared up with wrappers and delegates, so maybe some of these components do not get along well with what I'm trying to achieve), as I finally managed to make this work with a following setup:


```
    @Provides
    @ServiceScoped
    fun provideHlsMediaSourceFactory(
        @ApplicationContext context: Context,
        databaseProvider: DatabaseProvider
    ): MediaSourceFactory {
        val cacheFolder = File(context.cacheDir, "temp_med")
        val cacheEvictor = LeastRecentlyUsedCacheEvictor(10 * 1024 * 1024)

        val cache = SimpleCache(cacheFolder, cacheEvictor, databaseProvider)

        val cacheDataSourceFactory = CacheDataSource.Factory()
            .setCache(cache)
            .setUpstreamDataSourceFactory(DefaultHttpDataSource.Factory())
            .setCacheKeyFactory { dataSpec ->
                if (dataSpec.uri.toString().contains("master-playlist")) {
                    return@setCacheKeyFactory "temp-master-key"
                }

                return@setCacheKeyFactory CacheKeyFactory.DEFAULT.buildCacheKey(dataSpec)
            }

        return HlsMediaSource.Factory(cacheDataSourceFactory)
    }
```

This also required some tweaks to the `LeastRecentlyUsedCacheEvictor` to avoid evicting the master playlist as the cache gets full. Maybe it's worth using a `NoOpCacheEvictor` here, will give it a try to avoid writing separate logic for custom keys and their handling. 

In case you think I'm on a right track and do not have any additional thoughts or considerations, I'll continue investigating why this does not work for our full setup and get back to you next week. Thanks!

**Comment by icbaker** [comment]
```
return HlsMediaSource.Factory(cacheDataSourceFactory)
```

Just a quick note (not sure if it's deliberate): This will use your cache for **all** requests from the HLS media source (i.e. manifests, DRM keys **and** media segments). If you want to only cache the manifest then you should pass an `HlsDataSourceFactory` here instead, which delegates to either your `CacheDataSource.Factory` if `dataType == C.DATA_TYPE_MANIFEST` or to `DefaultDataSource.Factory` (or whatever your 'normal' `DataSource.Factory` is) otherwise.

**Comment by NikSatyr** [comment]
ok, with a couple more tweaks to the setup config the problem is solved – the master playlist is now being cached, which avoids the need to call the server which would return 403.

the final setup looks like this:

```
internal class ManifestCachingHlsDataSourceFactory(
    private val upstreamFactory: DataSource.Factory,
    private val manifestCachingDataSourceFactory: CacheDataSource.Factory,
) : HlsDataSourceFactory {

    override fun createDataSource(@DataType dataType: Int): DataSource {
        if (dataType == C.DATA_TYPE_MANIFEST) {
            return manifestCachingDataSourceFactory.createDataSource()
        }

        return upstreamFactory.createDataSource()
    }

}
```

```
@Provides
@ServiceScoped
fun provideHlsDataSourceFactory(
    upstreamFactory: ResolvingDataSource.Factory,
    @Named(MANIFEST_CACHE) manifestDataSourceFactory: CacheDataSource.Factory
): HlsDataSourceFactory {
    return ManifestCachingHlsDataSourceFactory(upstreamFactory, manifestDataSourceFactory)
}

@Provides
@ServiceScoped
@Named(MANIFEST_CACHE)
fun provideCacheDataSourceFactory(
    @Named(MANIFEST_CACHE) manifestCache: Cache,
    upstreamDataSourceFactory: ResolvingDataSource.Factory
): CacheDataSource.Factory {
    return CacheDataSource.Factory()
        .setCache(manifestCache)
        .setCacheKeyFactory(CacheKeyFactory.DEFAULT)
        .setUpstreamDataSourceFactory(upstreamDataSourceFactory)
        .setFlags(CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR)
}

@Provides
@ServiceScoped
@Named(MANIFEST_CACHE)
fun provideCache(
    @ApplicationContext context: Context,
    databaseProvider: DatabaseProvider
): Cache {
    val cacheFolder = File(context.cacheDir, CACHE_FOLDER_NAME)
    val cacheEvictor = LeastRecentlyUsedCacheEvictor(CACHE_SIZE_BYTES)
    return SimpleCache(cacheFolder, cacheEvictor, databaseProvider)
}
```

I'll close the issue, thanks for your guidance!
