### ISSUE TITLE
Why is the localConfiguration of a MediaItem removed when set on a mediaController?

### ISSUE THREAD

**Issue by huaweikai** [androidx/media#43]
Now I am using the media3 do a music software. I have a function to save the last playlist, so the next time I launch the app, I load the last playlist and index directly. But I found that in Media3 mediaLibrarySession must set the MediaItemFiller, leaving it blank will also cause the check to be empty.

The official demo reads like this:
```
    inner class CustomMediaItemFiller : MediaSession.MediaItemFiller {
        override fun fillInLocalConfiguration(
            session: MediaSession,
            controller: MediaSession.ControllerInfo,
            mediaItem: MediaItem
        ): MediaItem {
            return itemTree.getItem(mediaItem.mediaId) ?: mediaItem
        }
    }
```
So when I start up my app, I go to the database and retrieve the list and I go to setMediaItems, and it jumps to the MediaItemFiller, which looks from the ItemTree first, but some of my songs are going to be in the album, and they're not going to scan for them when they first load. But the mediaItem that was returned is the mediaItem that was passed in, and I see that its Uri is already empty, which will cause the localConfiguration to still be empty when I check.
```
    inner class CustomMediaItemFiller : MediaSession.MediaItemFiller {
        override fun fillInLocalConfiguration(
            session: MediaSession,
            controller: MediaSession.ControllerInfo,
            mediaItem: MediaItem
        ): MediaItem {
            return MediaItem.Builder()
                .setMediaMetadata(mediaItem.mediaMetadata)
                // I need to reset the Uri，but why?
                .setUri(mediaItem.mediaMetadata.mediaUri)
                .setMediaId(mediaItem.mediaId)
                .build()
        }
    }
```

**Comment by marcbaechinger** [comment]
When you are calling `mediaController.setMediaItems(items)` in a UI component like an `Activity` or a `Fragment`,  the argument that you pass to the method is sent to the service and under the hood marshalled in a Parcel and then unparceled back to a `MediaItem` when arriving at the service. In this process the `localConfiguration` is removed for security/privacy reasons. It may contain information like uri and DRM keys an app doesn't wants to share. This restriction applies in both directions of communications between client and service. 

The `MediaItemFiller` then adds the data that is validated and often read from a database by using the `mediaId` as the key.

What you are doing is a different, but equally reasonable approach to provide that data. If you are sure only your application is using the service this is perfectly fine. I think you probably do so to not be required to read from the database from the service also which is probably a reasonable decision.

**Comment by marcbaechinger** [comment]
We have similar question in #8 . I'm closing this issue. Please re-open if you think there needs to be something added.
