### ISSUE TITLE
ClippingConfiguration produces unexpected output when fallback is required

### ISSUE THREAD

**Issue by audkar** [androidx/media#437]
### Media3 Version

Media3 1.0.2

### Devices that reproduce the issue

* GoogleApi 33 emulator

(but probably all devices)

### Reproducible in the demo app?

Yes

### Reproduction steps

(not `main` but `transformer` demo app)

* Choose preset file `360p VP8 video  and Vorbis audio`
* Select `trim` values `15` - `20`
* Click `Transform`

### Expected result

Output is ~5s long

### Actual result

The output length is the same. But content is cut (in Vorbis case)

<img src="https://github.com/androidx/media/assets/1947112/00c8011d-3fa4-45f4-ba92-b3eec4a27967" width=30%/>

--- 

When doing the same flow with mp3 input, the transformation crashes.

### Media

Preset `360p VP8 video  and Vorbis audio`

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by audkar** [comment]
Oh wow. Just rechecked 

❌ `release` branch fail (reproducible) 
:heavy_check_mark: `main` pass. `mp3` trim is also works properly and doesn't crash.

Seems that we need to wait for the next version after 1.0.2 :smile:

**Comment by icbaker** [comment]
You could try with `1.1.0-beta01`: https://github.com/androidx/media/releases/tag/1.1.0-beta01

**Comment by audkar** [comment]
We are not adding anything to our prod code that is < `RC`.

But good to know that fix is already in the coming versions.
