### ISSUE TITLE
Adding fallback handling for MediaUtils.convertToRepeatMode() in MediaControllerImplLegacy

### ISSUE THREAD

**Issue by h6ah4i** [androidx/media#448]
### What's the matter?

I am using a forked version of the media3 library for my app to work around a specific issue. The problem is that some apps maybe use their own extended definition of repeat mode.

At least, the app I can find that causes the problem is [Stellio](https://play.google.com/store/apps/details?id=io.stellio.music). This app has two special repeat modes that cannot be handled by [`MediaUtils.convertToRepeatMode()`](https://github.com/androidx/media/blob/2fc189d6a40f116bd54da69ab9a065219f6973e7/libraries/session/src/main/java/androidx/media3/session/MediaUtils.java#L955)

* Jump to a next list - **Stop on last track**
  * :point_right: representation code in decimal: `100`
* Jump to a next list - **Stop from first list**
  * :point_right: representation code in decimal: `101`

<img src="https://github.com/androidx/media/assets/2552365/b436c215-7a49-4c05-a7e7-4f1fdf79977f" width="200" />

### Proposed solution

Wrap the `MediaUtils.convertToRepeatMode()` call with a try-catch block and fallback to an alternative repeat mode like this.

https://github.com/androidx/media/blob/2fc189d6a40f116bd54da69ab9a065219f6973e7/libraries/session/src/main/java/androidx/media3/session/MediaControllerImplLegacy.java#L1869

```diff
-    repeatMode = MediaUtils.convertToRepeatMode(newLegacyPlayerInfo.repeatMode);
+    try {
+      repeatMode = MediaUtils.convertToRepeatMode(newLegacyPlayerInfo.repeatMode);
+    } catch (IllegalArgumentException e) {
+      repeatMode = Player.REPEAT_MODE_OFF;
+    }
```

I think calling `MediaUtils.convertToShuffleModeEnabled()` is somewhat dangerous too due to the same reason, but I don't find the app that causes the error in the real world for now.

**Comment by oceanjules** [comment]
It is a design decision not to handle the repeat modes we know nothing about. Although, I can see a way for us to introduce a different function like:

`MediaUtils.convertToRepeatMode(@PlaybackStateCompat.ShuffleMode int repeatMode, @Player.RepeatMode int defaultMode);`

However, to avoid that, can I ask you whether you can handle the repeat mode yourself before letting it propagate as an invalid integer? If you manage to convert it to `PlaybackStateCompat.REPEAT_MODE_INVALID`, then it will be handled exactly how you want - with a `Player.REPEAT_MODE_OFF`

**Comment by h6ah4i** [comment]
> However, to avoid that, can I ask you whether you can handle the repeat mode yourself before letting it propagate as an invalid integer? If you manage to convert it to `PlaybackStateCompat.REPEAT_MODE_INVALID`, then it will be handled exactly how you want - with a `Player.REPEAT_MODE_OFF`

That sounds more flexible and clean solution to me :+1:

**Comment by h6ah4i** [comment]
@oceanjules 

Sorry, I am not sure where I can inject the repeat mode transformation logic without creating a fork of the media3 library... Will you add the mechanism in a future release of media3?

The app I mentioned [Stellio](https://play.google.com/store/apps/details?id=io.stellio.music) is not what I maintain. I just need to control this app from a different app through `androidx.media3.session.MediaController` created with a MediaSession.

In the implementation of the media3 library, I can see there are two places where I need to insert a transformation logic.

1. In a `android.support.v4.media.session.MediaControllerCompat.Callback#onRepeatModeChanged()` callback
    - https://github.com/androidx/media/blob/2fc189d6a40f116bd54da69ab9a065219f6973e7/libraries/session/src/main/java/androidx/media3/session/MediaControllerImplLegacy.java#L1751
2. Where calling the `android.support.v4.media.session.MediaControllerCompat.getRepeatMode()` method
    - https://github.com/androidx/media/blob/2fc189d6a40f116bd54da69ab9a065219f6973e7/libraries/session/src/main/java/androidx/media3/session/MediaControllerImplLegacy.java#L1231
    - https://github.com/androidx/media/blob/2fc189d6a40f116bd54da69ab9a065219f6973e7/libraries/session/src/main/java/androidx/media3/session/MediaControllerImplLegacy.java#L1667

---

Should I report this issue to the [issue tracker of Android](https://issuetracker.google.com/issues/new?component=461042&template=1238510) instead of here, because `MediaControllerCompat` is part of `androidx.media:media` package?

**Comment by oceanjules** [comment]
After an internal discussion, it was noted that:
-  the behaviour of handling of unsupported types is currently _undefined_. It can be an IllegalArgumentException or it can be a common-case default value or anything else.
- ideally, you would be able to talk to the app developers who are violating the interface and let them know that they are causing the crash. We are aware of the difficulties that brings and we want to provide the best experience for whoever is on the MediaController/MediaSession Media3/Legacy boundary (with the focus of media3 adoption of course)
- in this particular case, we will change the current behaviour to:
  - unsupported `PlaybackStateCompat` repeat mode ->` Player.REPEAT_MODE_OFF`
  - log-warning that this is the translation that occurred
- in the future, we might end up with injectable behaviour for various Legacy <-> Media3 modes where you could override the defaults

**Comment by h6ah4i** [comment]
Thanks for the detailed information :bow:  I'll try to contact the author of the app that violates the spec of the media/media3 boundary.
