### ISSUE TITLE
Exoplayer not playing video in Android 11

### ISSUE THREAD

**Issue by abhiroop-medtronic** [androidx/media#455]
Hi,

I am using custom IMX8MPlus board with Android 11.2.6 NXP release. 
I am trying to play few short videos via exoplyaer.

The video info are attached.
![video_codec_info](https://github.com/google/ExoPlayer/assets/136320514/edb9e086-062b-4024-a98d-2ddc1ebeb2ad)

But the video is not playing nd I am getting these logs:
D MediaCodecInfo: NoSupport [codec.profileLevel, avc1.7A0032, video/avc] [c2.imx.avc.decoder, video/avc]

Please let me know how can I resolve this issue.
Do I need to change the video or need to add ay extra code?

Thanks and regards,
Abhiroop Nandi Ray

**Comment by FongMi** [comment]
Please provide video file or link to test.

**Comment by andrewlewis** [comment]
The codecs string is `avc1.7A0032`. I think 7A indicates High profile 4:2:2 chroma subsampling, which is not guaranteed to be supported on Android devices: https://source.android.com/docs/compatibility/13/android-13-cdd#534_h264

**Comment by abhiroop-medtronic** [comment]
Hi,

I have tested with a sample video. 1280 x 720 px with 60 fps and it worked. It was probably the other videos codec and resolution was not as per with the Android supported formats.
