### ISSUE TITLE
Getting ExoPlaybackException: Source error While playing M3U8 URL in Exo Player

### ISSUE THREAD

**Issue by patelakshay13890** [androidx/media#463]
androidx.media3.exoplayer.ExoPlaybackException: Source error
 
 Caused by: androidx.media3.common.ParserException: Input does not start with the #EXTM3U header.
 
 URL : "https://******.live/***/index.m3u8?user=#####&token=####&ip=$$$$"
 

![image](https://github.com/androidx/media/assets/6092323/cfe8a62a-bdb0-480b-8ea6-e5c207f0d132)

**Comment by tianyif** [comment]
Hi @patelakshay13890,

Could you please make sure that your playlist start with `#EXTM3U` header? Per the instruction in [HLS spec](https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis-13#section-4.4.1.1):

```
It MUST be the first line of every Media Playlist and every Multivariant Playlist.
```

Thanks!

**Comment by patelakshay13890** [comment]
But my Link is M3U8, so what other lib should i use other than this lib ?

**Comment by tianyif** [comment]
M3u8 is simply a UTF-8 version of the M3U format. We have sample HLS M3u8 playlist in the [demo app](https://github.com/androidx/media/blob/release/demos/main/src/main/assets/media.exolist.json#L229), and they are playable.
