### ISSUE TITLE
How to use MediaSessionService with m3u8 format?

### ISSUE THREAD

**Issue by BoikoIlya** [androidx/media#464]
i try to play m3u8 format and it not playing and no errors in logcat. Song url https://cs25-2v4.vkuseraudio.net/s/v1/ac/6eEbeJLYA40oJpXiZweJ4kxFQbVUFlthr122mnRtEQkQrgQhb2zT3PUJTKYt7RBEJMuqylePyew0eoF-fmsI6Ag3QpmudRgotTQJEzadtSOXFSkcykXiLVXHZQdxOINZO-u4ujacHRlZWz3rV0FJnXjZTezQtHtZZSCBOz8hku4jm_k/index.m3u8

HOW TO FIX THAT? (mp3 is working fine)

This is how i create media item 

( data.id is song url )

 ```
override  fun map(data: TrackCache): MediaItem {
        return MediaItem.Builder()
            .setMediaId(data.id)
            .setUri(data.id)
            .setMimeType(MimeTypes.APPLICATION_M3U8)
            .setMediaMetadata(
                MediaMetadata.Builder()
                    .setTitle(data.name)
                    .setArtist(data.artistName)
                    .setAlbumTitle(data.albumName)
                    .setArtworkUri(Uri.parse(data.imgUrl))
                    .build()
            )
            .build()
    }
```

**Comment by marcbaechinger** [comment]
When I try to load the media I get a HTTP/302. Can you please make sure this is not the reason for the playback problem?

**Comment by BoikoIlya** [comment]
The url is correct, i opened it in chrome and yandex browsers on pc and it was succsesffully downloaded. when i opened it in chrome on my mobile it loaded browser player and started playing the song.
![image](https://github.com/androidx/media/assets/100340546/cf38c9be-f738-491b-8e18-63e185c1e54c)
![photo1687174256](https://github.com/androidx/media/assets/100340546/a73b3829-97ff-4328-89b3-a2b2f40daded)

**Comment by BoikoIlya** [comment]
And android MediaPlayer is able to play that format. But ExoPlayer not.

**Comment by marcbaechinger** [comment]
Thanks! I didn't say the URI is not correct. I see a HTTP/301 though

```
< HTTP/2 301 
< server: kittenx
< date: Mon, 19 Jun 2023 11:45:02 GMT
```

If you want to make this issue actionable for us, please do.

**Comment by BoikoIlya** [comment]
But i dont see 301 in logcat when start the song. how can i help? Or we have misunderstanding

**Comment by marcbaechinger** [comment]
Yeah, you are right. Sorry my fault. Works for me as well.

**Comment by BoikoIlya** [comment]
So, how to make exoplayer play m3u8 format?

**Comment by BoikoIlya** [comment]
The problem is solved. To play m3u8 format i need 2 more dependencies:

` implementation "androidx.media3:media3-exoplayer:1.1.0-beta01"
 implementation "androidx.media3:media3-exoplayer-hls:1.1.0-beta01"`

And these way of ExoPlayer creation : 
` ExoPlayer.Builder(context)
            .setMediaSourceFactory(
                HlsMediaSource.Factory(
                    DefaultHlsDataSourceFactory(DefaultHttpDataSource.Factory())))
            .build()`
