### ISSUE TITLE
Allow only forced subtitle tracks with `TrackSelector`

### ISSUE THREAD

**Issue by moneytoo** [androidx/media#466]
Hi,

Say I'm opening various user controlled Matroska video files in `ExoPlayer`. My goal is to configure the player so it doesn't show subtitles unless it's a forced track. Is it possible to achieve that with `TrackSelector`? I'm trying to use `setIgnoredTextSelectionFlags()` and `C.SELECTION_FLAG_*`, but I can only disable subtitles in both cases (samples "Default" and "Default & Forced"), while I would like to disable it in the first case ("Default") but keep it on in the second one ("Default & Forced").

[Default](https://raw.githubusercontent.com/ietf-wg-cellar/matroska-test-files/master/test_files/test5.mkv)

```
Text #1
ID                                       : 3
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Language                                 : English
Default                                  : Yes
Forced                                   : No
```

[Default & Forced](https://brouken.com/Forced%20Sub%20Sample%20(PGS).mkv)

```
Text
ID                                       : 3
Format                                   : PGS
Muxing mode                              : zlib
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 23 s 523 ms
Bit rate                                 : 9 276 b/s
Count of elements                        : 8
Stream size                              : 26.6 KiB (0%)
Title                                    : Forced English Subtitles
Language                                 : English
Default                                  : Yes
Forced                                   : Yes
```

Or are there any other options? Any suggestion is much appreciated. Thanks

**Comment by icbaker** [comment]
I think `setIgnoredTextTrackSelectionFlags(C.SELECTION_FLAG_DEFAULT)` should do exactly this - but when I try that in the demo app I can see it doesn't select the `[default,forced]` track like you report, so this looks like a bug, thanks for reporting - I'll dig a bit deeper and see what's going on.

**Comment by moneytoo** [comment]
Thanks a million, it surely works! I'm able to play that audio track with the FFmpeg extension, but somehow I was always testing the track selection with this sample and in demo without the extension.
