### ISSUE TITLE
Bug in MediaMetadata.equals() and MediaMetadata.hashCode()

### ISSUE THREAD

**Issue by cdongieux** [androidx/media#470]
### Media3 Version

ExoPlayer 2.18.7

### Devices that reproduce the issue

Not device-related.

### Reproducible in the demo app?

Not tested

### Reproduction steps

```
val player: ExoPlayer = ...
player.playlistMetadata = MediaMetadata.Builder()
    .setExtras(
        bundleOf("foo" to "bar")
    )
    .build()
assertEquals("bar", player.playlistMetadata?.extras?.getString("foo"))
```

### Expected result

`assertEquals("bar", player.playlistMetadata?.extras?.getString("foo"))` should be true.

### Actual result

`assertEquals("bar", player.playlistMetadata?.extras?.getString("foo"))` is false because `ExoPlayerImpl.setPlaylistMetadata(MediaMetadata mediaMetadata)` checks equality between the new playlist metadata and the current playlist metadata:

```
    if (playlistMetadata.equals(this.playlistMetadata)) {
      return;
    }
```

The problem is `MediaMetadata.equals()` and `MediaMetadata.hashCode()` don't take care of the `extras` property, thus `playlistMetadata.equals(this.playlistMetadata)` returns true, thus the new playlist metadata is not set.

### Media

Not media-related.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
This is expected, and [documented](https://developer.android.com/reference/androidx/media3/common/MediaMetadata#extras()) on `MediaMetadata.extras`:

> Given the complexities of checking the equality of two [`Bundles`](https://developer.android.com/reference/android/os/Bundle.html), this is not considered in the [`equals`](https://developer.android.com/reference/androidx/media3/common/MediaMetadata#equals(java.lang.Object)) or [`hashCode`](https://developer.android.com/reference/androidx/media3/common/MediaMetadata#hashCode()).
