### ISSUE TITLE
BitArray.skipBits() should have been called when BitArray.skipBytes() is

### ISSUE THREAD

**Issue by unext-wendong** [androidx/media#474]
### Media3 Version

Media3 1.0.2

### Description

By reading the code change in commit 5ebbdc52cb32b54ca48a0a791521681d898d21fa, it seems clear it's a mistake in this line:
https://github.com/androidx/media/blob/release/libraries/extractor/src/main/java/androidx/media3/extractor/Ac3Util.java#L217
 to call `dataBitArray.skipBytes(6)` when it should call `dataBitArray.skipBits(6)`.

### Reproducible in the demo app?

Yes

### Reproduction steps

n/a

### Expected result

n/a

### Actual result

n/a

### Media

n/a

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by rohitjoins** [comment]
@unext-wendong 

Thank you for raising this issue. I'll correct this and update the code soon.

**Comment by rohitjoins** [comment]
The [fix](https://github.com/androidx/media/commit/07d4e5986b06ef6e362fe00fb97187469f42bc25) was uploaded to the `main` branch.
