### ISSUE TITLE
exoplayer2 in media3

### ISSUE THREAD

**Issue by giladna** [androidx/media#476]
hi team

I was thinking you might be interested in updating this line:

```
private static String buildCustomDiagnosticInfo(int errorCode) {
      String sign = errorCode < 0 ? "neg_" : "";
      return "com.google.android.exoplayer2.mediacodec.MediaCodecRenderer_"
          + sign
          + Math.abs(errorCode);
    }
  }
```

https://github.com/androidx/media/blob/2fc189d6a40f116bd54da69ab9a065219f6973e7/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/mediacodec/MediaCodecRenderer.java#L189

**Comment by tianyif** [comment]
Thanks a lot for the reporting! We will make a change on this.
