### ISSUE TITLE
How to pass customData to DataSpec when using CacheDataSource

### ISSUE THREAD

**Issue by Shabinder** [androidx/media#477]
I am using a CacheDataSource with a custom CacheReadDataSourceFactory.

in the DataSource when opening a DataSpec, I want to have custom Object or Key/Value props.
I can see there is a customData object with Any type.

but how would I pass a data when loading a MediaItem into player instance, since the internal methods like : ProgressiveMediaPeriod.ExtractingLoadable.buildDataSpec doesnt pass in said property when building a DataSpec.

Any help would be appreciated.

**Comment by tianyif** [comment]
Hi @Shabinder, what data do you want to pass into when loading the `MediaItem`?

**Comment by dagerler001** [comment]
@Shabinder Hi,
You can use `ResolvingDataSource` for wrap data source and modify `dataSpec`

for example i use it for set in custom data, unique value for generation cacheKey
```
  /**
     * Added to DataSpec contentId, which help create unique KeyCache
     */
    private fun wrapResolveDataSourceFactory(contentId: String, dataSourceFactory: DataSource.Factory): DataSource.Factory {
        return ResolvingDataSource.Factory(dataSourceFactory) { dataSpec ->
            // Add to DataSpec contentId for find relative cache
            if (dataSpec.uri.toString().endsWith(".ts") || dataSpec.uri.toString().endsWith(".m3u8")) {
                return@Factory dataSpec.buildUpon().setCustomData(contentId).build()
            } else {
                return@Factory dataSpec
            }
        }
    }
```

**Comment by Shabinder** [comment]
> Hi @Shabinder, what data do you want to pass into when loading the `MediaItem`?

A custom model, which I wanted to retrieve at my custom CacheReadDataSource.
