### ISSUE TITLE
Need some help with building the FFMPEG extension

### ISSUE THREAD

**Issue by GormlessGeorge** [androidx/media#479]
Hello,

I'm trying to build the FFMPEG extension using Ubuntu VM. I was closely following the [README](https://github.com/androidx/media/tree/release/libraries/decoder_ffmpeg) steps, and after some "clang" related errors the `build_ffmpeg.sh` COMPLETES its run. However, the only thing I’m getting is a new “android libs” directory that goes  into the ffmpeg 4.2.9 folder (don't know if that's intended). The contents are as follows:

```
ffmpeg/android-libs/arm64-v8a/libavcodec.a, libavutil.a, libswresample.a
ffmpeg/android-libs/armeabi-v7a/libavcodec.a, libavutil.a, libswresample.a
ffmpeg/android-libs/x86/libavcodec.a, libavutil.a, libswresample.a
ffmpeg/android-libs/x86_64/libavcodec.a, libavutil.a, libswresample.a
```

So even though `build_ffmpeg.sh` completes the script successfully(?), I don't understand what my next steps should be, because according to the [troubleshooting  guide](https://developer.android.com/guide/topics/media/exoplayer/troubleshooting#how-can-i-get-a-decoding-library-to-load-and-be-used-for-playback)  it should generate ".so" files in the libs subdirectory of the extension’s path:

> "You should see .so files appear in the libs subdirectory of the extension’s path for each supported architecture after following the steps in the README."

Another issue, is that sometimes there's this yellow warning:  
`"WARNING: /home/gg/ff-extension/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi16-pkg-config not found, library detection may fail."`

 I was getting this on Windows, and after it being displayed, my Power Shell would close instantly. However, on Ubuntu it doesn't prevent the script completion.
 
Don't know what the problem is, because I have no idea what the end result should be. 

Versions
---
NDK: **android-ndk-r21e** *
FFMPEG: **4.2.9**
media: **1.0.2**

*I also tried switching the NDK versions(a lot of them, actually). The lower/newer ones give me "C compiler errors" related to `androideabi16-clang` which doesn't seem to exist at all.

Result
---
[Directory screenshots](https://imgur.com/a/wFNYxge) (Imgur)

[Terminal inputs](https://pastebin.com/iKqCcqFY) (Pastebin)

[Script results](https://pastebin.com/bD0RRUQ0) (Pastebin)

Can you please point me in the right direction and describe me my next steps (or point out any mistakes)? This thing is driving me insane :/

**Comment by christosts** [comment]
> So even though build_ffmpeg.sh completes the script successfully(?), I don't understand what my next steps should be, because according to the [troubleshooting guide](https://developer.android.com/guide/topics/media/exoplayer/troubleshooting#how-can-i-get-a-decoding-library-to-load-and-be-used-for-playback) it should generate ".so" files in the libs subdirectory of the extension’s path

Things look OK on your setup and you should be able to continue to the next steps, which is including the extension as a dependency in your app's module gradle file. 

For the .so file, this is built from the ffmpeg extension's gradle file [here](https://github.com/androidx/media/blob/2fc189d6a40f116bd54da69ab9a065219f6973e7/libraries/decoder_ffmpeg/build.gradle#L19). The file is called `libffmpegJNI.so` and should be present in the `buildout` directory of the extension, and then copied to the app's buildout by gradle.

Let me know if you need any more assistance.

**Comment by GormlessGeorge** [comment]
Hey, @christosts, thank you for your reply!

Still a bit confused. However, I did manage to build something. At least it was loaded (logcat: Loaded FfmpegAudioRenderer.) and the audio plays just fine.

Here's what I did:
`./gradlew lib-decoder-ffmpeg:assembleRelease ` from the media root

It generated some files including the `.aar` file inside `media\libraries\decoder_ffmpeg\buildout` directory
And then added the `.arr` to my project.

Not sure if I did everything correct. For some reason, I think it pulled the default ffmpeg setup that you guys provide (if that makes sense)

If that's the case, can you please go in detail on how can I include the extension as a dependency?

Thank you for your time.

**Comment by christosts** [comment]
Glad to hear you got it to work.

> how can I include the extension as a dependency?

First, there are some instructions how to depend on the project locally from sources at https://github.com/androidx/media#locally, maybe you are already following them. Then the dependency to the ffmpeg decoder should be with `implementation project(':media-lib-decoder-ffmpeg')`
