### ISSUE TITLE
Exoplayer not able to play DRM video

### ISSUE THREAD

**Issue by sridhard** [androidx/media#481]
### Media3 Version

ExoPlayer 2.18.7

### Devices that reproduce the issue

Redmi android 10

### Devices that do not reproduce the issue

Samsung

### Reproducible in the demo app?

Not tested

### Reproduction steps

Just play the video. We get the below error

exception e = {"error":{"errorStackTrace":"com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(0, null, null, video/avc, avc1.42C01E, 37506, null, [1016, 540, 25.0], [-1, -1]), format_supported=YES\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:575)\n\tat android.os.Handler.dispatchMessage(Handler.java:103)\n\tat android.os.Looper.loop(Looper.java:224)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\nCaused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.MTK.VIDEO.DECODER.AVC.secure\n\tat com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1512)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:813)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)\n\t... 3 more\nCaused by: java.lang.IllegalStateException\n\tat android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)\n\tat android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2789)\n\tat com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:106)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1806)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:792)\n\t... 5 more\n","errorCode":"24003","errorException":"MediaCodecVideoRenderer error, index=0, format=Format(0, null, null, video/avc, avc1.42C01E, 37506, null, [1016, 540, 25.0], [-1, -1]), format_supported=YES","errorString":"ExoPlaybackException: ERROR_CODE_DECODING_FAILED"}}

### Expected result

Video should play

### Actual result

Play fails

### Media

Any DASH video with widevine L3 has issue

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
Please email the zip file produced by `adb bugreport` immediately after reproducing the problem to dev.exoplayer@gmail.com with subject `Issue #481`, and update this issue when you've done this.
