### ISSUE TITLE
Duration from media item

### ISSUE THREAD

**Issue by pranjaljhawar26** [androidx/media#484]
I am trying to get the duration from the media item itself instead of player.getduration() as player.getduration() gives C.TIME_UNSET until player gets ready

**Comment by marcbaechinger** [comment]
The duration is available as soon as the player know the duration.

If you know the duration ahead of time, then you can add it to the `MediaMetadata.extras` with a custom key that can define for your app.

**Comment by pranjaljhawar26** [comment]
@marcbaechinger 
Does media metadata have duration?
How to get that from extras ?
Can you please mention some sample code lines

**Comment by pranjaljhawar26** [comment]
> @marcbaechinger Does media metadata have duration? How to get that from extras ? Can you please mention some sample code lines

Can parser be used for it?

**Comment by pranjaljhawar26** [comment]
> The duration is available as soon as the player knows the duration.
> 
> If you know the duration ahead of time, then you can add it to the `MediaMetadata.extras` with a custom key that can be defined by your app.

Does media metadata have duration?
How to get that from extras ?
Can you please mention some sample code lines
Can parser be used for it?

**Comment by marcbaechinger** [comment]
`Player.getDuration()` shows the duration of the media as known to the player at the earliest moment possible. If `Player.getDuration()` returns `C.TIME_UNSET`, then the duration is not known to the player yet. There is not other API that then knows the duration.

If you as the developer know the duration, as for instance you have the duration of your media stored in a database, then you can populate the `MediaMetadata` with that duration from the database before you pass the `MediaItem` to the player. Please [consult our developer guide on how you can build a media item](https://developer.android.com/guide/topics/media/exoplayer/media-items).
