### ISSUE TITLE
Is it possible to shift the playback position between video and audio?

### ISSUE THREAD

**Issue by ho3y** [androidx/media#495]
Hi,
Is there a new API for media3 that will only speed up or slow down the playback position of audio?

If not, how should the audio delay be handled?
Should I prepare two player and separate them for video playback and audio playback?

I would be happy to be advised.

**Comment by microkatz** [comment]
Hi @ho3y,

Thank you for reporting your question. Can you elaborate on your intent/expected playback scenario? 

If you are looking to change playback speed then you can use `setPlaybackSpeed`.

If you are looking to alter audio playback separate from video playback then that is a bit more difficult.

**Comment by ho3y** [comment]
Hi,
Sorry for writing in a way that is difficult to convey.

I would like to solve the problem of the video image and sound being out of sync.
It is misaligned when recording the app on the device or using Bluetooth earphones.

Is it possible to make the sound play one second faster than the video, for example?

**Comment by ho3y** [comment]
@microkatz
Thanks for the reply.

ExoPlayer is not the cause of the delay when listening via Bluetooth. It is wireless, so there will be some delay due to specification issues.

I would like to adjust the discrepancy between the video and music from 0.1 second increments.
Set delay time for video or music. Or, I would like to know if it is possible to separate the video and music into different Players and shift the playback position.

**Comment by microkatz** [comment]
I think what you want to do then is just to override your player's MediaCodecAudioRenderer to return the playback position with whatever delta you want(+0.1 second). That would cause the video to be played ahead at that delta. 

You need to create two custom classes. A CustomMediaCodecAudioRenderer that wraps MediaCodecAudioRenderer and a CustomRenderersFactory that wraps DefaultRenderersFactory. You then set the CustomRenderersFactory through ExoPlayer#Builder.setRenderersFactory. Your CustomRenderersFactory overrides the protected method buildAudioRenderers in DefaultRenderersFactory to return your CustomMediaCodecAudioRenderer.

I hope that helps.

**Comment by ho3y** [comment]
Thank you very much.
The method you taught me solved the problem!
