### ISSUE TITLE
Extracted in memory crash

### ISSUE THREAD

**Issue by BoikoIlya** [androidx/media#496]
### Media3 Version

Media3 1.0.0-beta01

### Devices that reproduce the issue

Samsung a70 android 11

### Reproducible in the demo app?

Not tested

### Reproduction steps

just random times

### Expected result

media playing

### Actual result

 pid: 18355, tid: 18355, name: xample.musicapp  >>> com.example.musicapp <<<
12:54:30.964  A        #24 pc 000000000040d2d0  [anon:dalvik-classes.dex extracted in memory from /data/app/~~dgr_Xut3TL9gMoORBSm6HA==/com.example.musicapp-92ZqeDltiBFib0OZ-aNyhw==/base.apk] (androidx.media3.session.DefaultMediaNotificationProvider.getMediaButtons+96)
12:54:30.964  A        #27 pc 000000000040d060  [anon:dalvik-classes.dex extracted in memory from /data/app/~~dgr_Xut3TL9gMoORBSm6HA==/com.example.musicapp-92ZqeDltiBFib0OZ-aNyhw==/base.apk] (androidx.media3.session.DefaultMediaNotificationProvider.createNotification+116)
12:54:30.964  A        #30 pc 0000000000427898  [anon:dalvik-classes.dex extracted in memory from /data/app/~~dgr_Xut3TL9gMoORBSm6HA==/com.example.musicapp-92ZqeDltiBFib0OZ-aNyhw==/base.apk] (androidx.media3.session.MediaNotificationManager.lambda$updateNotification$7$androidx-media3-session-MediaNotificationManager+8)
12:54:30.964  A        #33 pc 00000000004271a0  [anon:dalvik-classes.dex extracted in memory from /data/app/~~dgr_Xut3TL9gMoORBSm6HA==/com.example.musicapp-92ZqeDltiBFib0OZ-aNyhw==/base.apk] (androidx.media3.session.MediaNotificationManager$$ExternalSyntheticLambda3.run+20)
12:54:30.964  A        #36 pc 000000000033767c  [anon:dalvik-classes.dex extracted in memory from /data/app/~~dgr_Xut3TL9gMoORBSm6HA==/com.example.musicapp-92ZqeDltiBFib0OZ-aNyhw==/base.apk] (androidx.media3.common.util.Util.postOrRun+52)
12:54:30.965  A        #39 pc 0000000000427bc2  [anon:dalvik-classes.dex extracted in memory from /data/app/~~dgr_Xut3TL9gMoORBSm6HA==/com.example.musicapp-92ZqeDltiBFib0OZ-aNyhw==/base.apk] (androidx.media3.session.MediaNotificationManager.updateNotification+126)
12:54:30.965  A        #42 pc 000000000042f5d2  [anon:dalvik-classes.dex extracted in memory from /data/app/~~dgr_Xut3TL9gMoORBSm6HA==/com.example.musicapp-92ZqeDltiBFib0OZ-aNyhw==/base.apk] (androidx.media3.session.MediaSessionService.onUpdateNotification+22)
12:54:30.965  A        #45 pc 000000000042f1e2  [anon:dalvik-classes.dex extracted in memory from /data/app/~~dgr_Xut3TL9gMoORBSm6HA==/com.example.musicapp-92ZqeDltiBFib0OZ-aNyhw==/base.apk] (androidx.media3.session.MediaSessionService.onUpdateNotificationInternal+18)
12:54:30.965  A        #48 pc 000000000042750e  [anon:dalvik-classes.dex extracted in memory from /data/app/~~dgr_Xut3TL9gMoORBSm6HA==/com.example.musicapp-92ZqeDltiBFib0OZ-aNyhw==/base.apk] (androidx.media3.session.MediaNotificationManager$MediaControllerListener.onEvents+34)
12:54:30.965  A        #51 pc 0000000000419bb6  [anon:dalvik-classes.dex extracted in memory from /data/app/~~dgr_Xut3TL9gMoORBSm6HA==/com.example.musicapp-92ZqeDltiBFib0OZ-aNyhw==/base.apk] (androidx.media3.session.MediaControllerImplBase.lambda$new$0$androidx-media3-session-MediaControllerImplBase+18)
12:54:30.965  A        #54 pc 00000000004170c8  [anon:dalvik-classes.dex extracted in memory from /data/app/~~dgr_Xut3TL9gMoORBSm6HA==/com.example.musicapp-92ZqeDltiBFib0OZ-aNyhw==/base.apk] (androidx.media3.session.MediaControllerImplBase$$ExternalSyntheticLambda96.invoke+8)
12:54:30.965  A        #57 pc 000000000033216c  [anon:dalvik-classes.dex extracted in memory from /data/app/~~dgr_Xut3TL9gMoORBSm6HA==/com.example.musicapp-92ZqeDltiBFib0OZ-aNyhw==/base.apk] (androidx.media3.common.util.ListenerSet$ListenerHolder.iterationFinished+52)
12:54:30.965  A        #60 pc 0000000000332244  [anon:dalvik-classes.dex extracted in memory from /data/app/~~dgr_Xut3TL9gMoORBSm6HA==/com.example.musicapp-92ZqeDltiBFib0OZ-aNyhw==/base.apk] (androidx.media3.common.util.ListenerSet.handleMessage+40)
12:54:30.966  A        #63 pc 0000000000332200  [anon:dalvik-classes.dex extracted in memory from /data/app/~~dgr_Xut3TL9gMoORBSm6HA==/com.example.musicapp-92ZqeDltiBFib0OZ-aNyhw==/base.apk] (androidx.media3.common.util.ListenerSet.$r8$lambda$bio3pd12v5B_9b5UeFaPn9XBQ90)
12:54:30.966  A        #66 pc 0000000000331fe0  [anon:dalvik-classes.dex extracted in memory from /data/app/~~dgr_Xut3TL9gMoORBSm6HA==/com.example.musicapp-92ZqeDltiBFib0OZ-aNyhw==/base.apk] (androidx.media3.common.util.ListenerSet$$ExternalSyntheticLambda0.handleMessage+4)

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment]
Thanks for your report.

This report is not actionable for us I'm afraid. Can you add some more context like reproduction steps or similar? I'm going to paste the standard blurb below about requesting more info. Many thanks.

Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #496". Please also update this issue to indicate you’ve done this.
