### ISSUE TITLE
Cancels notificationManager provided by the service

### ISSUE THREAD

**Issue by huaweikai** [androidx/media#50]
There is an updateNotification callback in both alpha01 and Media2, and I just need to return null to use my own defined notificationManager and NotificationListener. Now alpha02 this method have no, followed by a setMediaNotificationProvider, but I will not use.

Now there will also be a UI refresh problem for the notification provided, click the problem. For example, after clicking pause, the pause button will return to the pause button after playing, and clicking on it will not work. The progress bar often fails to refresh.How do I stop using this Notification and use my custom Notification Manager.
https://github.com/huaweikai/testDemo/blob/d2599896e3346e1d309f2a9e5ae0f4d2f539a019/DA4D55E705C3EC32BE0C49410B0803D6.mp4

**Comment by christosts** [comment]
Thank you for the feedback. This was a miss  and we will bring back a method to make the library not handle notifications and let the app do so.

**Comment by huaweikai** [comment]
ok ,i will wait for you

**Comment by marcbaechinger** [comment]
Closing as this is fixed and will be included in `1.0.0-beta01` which is on its way to be released.
