### ISSUE TITLE
MediaPipe sample is failing because of a falsely referenced class

### ISSUE THREAD

**Issue by kihaki** [androidx/media#500]
### Version

Media3 1.1.0

### Devices that reproduce the issue

All, tested on Pixel 6 pro

### Devices that do not reproduce the issue

None

### Reproducible in the demo app?

Yes

### Reproduction steps

Setup MediaPipe sample according to the README, try the sample, the MediaPipe sample will fail with an error

### Expected result

The MediaPipe sample should transform the video by doing edge detection

### Actual result

The MediaPipe transform example fails

### Media

Use included sample video to reproduce, but any video will do

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by kihaki** [comment]
In `TransformerActivity.java:435` replace 

`Class<?> clazz = Class.forName("androidx.media3.demo.transformer.MediaPipeProcessor");`

with 

`Class<?> clazz = Class.forName("androidx.media3.demo.transformer.MediaPipeShaderProgram");`

The class seems to have been renamed and the new name is not referenced correctly.

This fixes the sample.

**Comment by andrewlewis** [comment]
Thanks for reporting this, I can merge a quick fix.

> I would love to create a PR for this, but it seems like I cannot get permissions to do so. Maybe I didn't set up my git correctly?

Not sure what the problem might be here, do you have any further information? Are you creating the PR against the `main` branch?

**Comment by kihaki** [comment]
I guess if I invested more than the casual 2 minutes, I could probably find out what went wrong with the PR. If there really is an issue and if the issue persists, I will answer again here.

Thanks for the quick response, feel free to merge a quickfix, I am not in need for the glory of having fixed it so to speak ;)

**Comment by andrewlewis** [comment]
Ok, understood :)

I've merged a fix internally, which should appear here next time we push the main branch. Thanks again!
