### ISSUE TITLE
Framerate matching removed from legacy version (not lite)

### ISSUE THREAD

**Issue by MasterDudess** [androidx/media#502]
### Version

Media3 1.1.0

### More version details

Hi Moneytoo,

It seems with 1.48 that you removed framerate matching in the menu from the legacy version. I presume this is a mistake and only for the lite version. Can you please return this option?

### Devices that reproduce the issue

Hi Moneytoo,

It seems with 1.48 that you removed framerate matching in the menu from the legacy version. I presume this is a mistake and only for the lite version. Can you please return this option?

### Devices that do not reproduce the issue

Hi Moneytoo,

It seems with 1.48 that you removed framerate matching in the menu from the legacy version. I presume this is a mistake and only for the lite version. Can you please return this option?

### Reproducible in the demo app?

Not tested

### Reproduction steps

1

### Expected result

1

### Actual result

1

### Media

Hi Moneytoo,

It seems with 1.48 that you removed framerate matching in the menu from the legacy version. I presume this is a mistake and only for the lite version. Can you please return this option?

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by microkatz** [comment]
Hi! It seems that you are trying to log a bug with a different project? Please take up your issue with their project.  I'm going to close this issue.

**Comment by marcbaechinger** [comment]
@moneytoo Can you take this over for us? :)

@MasterDudess Pleas check this project here: https://github.com/moneytoo/Player  I think you want to file your bug there.
