### ISSUE TITLE
App crashes when trying to invoke removeCallbacks inside processManifest

### ISSUE THREAD

**Issue by DenisVacaru** [androidx/media#518]
### Version

ExoPlayer 2.18.1

### Devices that reproduce the issue

Samsung Galaxy S10
Xiaomi Mi A3
Samsung Galaxy A22
and many more ...

### Reproducible in the demo app?

Not tested

### Reproduction steps

We were not able to reproduce it so far, only seeing quite a big number of crashes inside Firebase.

### Expected result

App should not crash

### Actual result

App crashes with the following stacktrace: 

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void android.os.Handler.removeCallbacks(java.lang.Runnable)' on a null object reference
com.google.android.exoplayer2.source.dash.DashMediaSource.processManifest (DashMediaSource.java:851)
com.google.android.exoplayer2.source.dash.DashMediaSource.onUtcTimestampResolutionError (DashMediaSource.java:780)
com.google.android.exoplayer2.source.dash.DashMediaSource.onUtcTimestampLoadError (DashMediaSource.java:697)
com.google.android.exoplayer2.source.dash.DashMediaSource$UtcTimestampCallback.onLoadError (DashMediaSource.java:1349)
com.google.android.exoplayer2.source.dash.DashMediaSource$UtcTimestampCallback.onLoadError (DashMediaSource.java:1325)
com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage (Loader.java:489)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loopOnce (Looper.java:226)
android.os.Looper.loop (Looper.java:313)
android.app.ActivityThread.main (ActivityThread.java:8757)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:604)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1067)
```

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment]
That looks like it shouldn't happen in theory. The `Handler` instance that is null in your stacktrace is only null before the source is first prepared and after the source is released. But there shouldn't be any UTC timestamp loading before the source is prepared and at the point of releasing the source, any ongoing load will also be stopped (which prevents further callbacks). 

Can you explain a bit more how you are integrating with `DashMediaSource`? Do you use it at all in your code, and if so, how?

**Comment by DenisVacaru** [comment]
@tonihei thanks for replying.

Unfortunately, I can't share code from our repository, this is not allowed. I'll try to create a vanilla project and get back to you. It's difficult for us to understand where the error originates since we were not able to reproduce it. 

To answer your question, yes, we're using `DashMediaSource` inside our project.

**Comment by DenisVacaru** [comment]
@tonihei I'm back with more info and some code

` dashMediaSource = DashMediaSource.Factory(dataSourceFactory)
                .createMediaSource(MediaItem.fromUri(Uri.parse(adsStream.manifestUrl)))

            mediaSourceCaller = MediaSource.MediaSourceCaller { _, timeline ->
                try {
                    val window = Timeline.Window()
                    timeline.getWindow(timeline.getFirstWindowIndex(false), window)
                    it.onSuccess(
                        Optional.of(
                            OriginManifestData(
                                windowStartTimeMs = window.windowStartTimeMs,
                                timeShiftBufferDepthMs = extractTimeShiftBuffer(window)
                            )
                        )
                    )
                } catch (exception: Exception) {
                  //////// code
                }
            }.also {
                dashMediaSource?.prepareSource(it, null)
            }`
            
    And finally we're calling inside the `doOnTerminate` block
    
    `  mediaSourceCaller?.let {
                    dashMediaSource?.releaseSource(it)
                    dashMediaSource = null
                    mediaSourceCaller = null
                }`
                
I've noticed that whenever we're releasing the source there's a handled exception inside exoplayer, similar to the one that our users are experiencing, but, unfortunately that's not handled. 
  
![4](https://github.com/androidx/media/assets/110381250/ae8101ff-bef8-4c8d-a680-ba328aec16e1)

**Comment by tonihei** [comment]
Aha, that explains it I believe :)  I assume you also use the same source in a player at some point? 

You shouldn't need to prepare and release the source yourself, see the JavaDoc of these methods that specifically call out "Should not be called directly from application code."

By preparing and releasing the source yourself, you probably confuse the implementation which thread it should use for its callbacks and the safe shutdown in release I was describing above no longer works as expected (leading to the problematic stack trace). Instead, just give the source to the player and will automatically do the right thing.
