### ISSUE TITLE
Too many keys requested by ExoPlayer

### ISSUE THREAD

**Issue by Doolali** [androidx/media#523]
### Version

Media3 1.1.0

### More version details

main

### Devices that reproduce the issue

Sony Xperia 10 V running latest Android

### Reproducible in the demo app?

Yes

### Reproduction steps

Generate a multi-key Widevine Protected piece of content with more than 60 tracks.

### Expected result

The media plays.

### Actual result

The device generates an invalid Widevine Payload that Googles Widevine servers can't parse.

### Media

TBD

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by Doolali** [comment]
We introduced a temporary fix where we request the keys prior to playing back in batches of 15 keys.
Was thinking this kind of logic would be better implemented and handled by Media3 in a way better suited for its architecture.

**Comment by tonihei** [comment]
> Generate a multi-key Widevine Protected piece of content with more than 60 tracks.

Is it possible to share this content with us? You can send a link to android-media-github@google.com with subject "Issue #523" if needed.

> Generate a multi-key Widevine Protected piece of content with more than 60 tracks.

Are all these keys needed in parallel or sequentially? I agree that the player should ideally handle the sequential case no matter what the underlying hardware limit for keys is. But if there is an inherent limit for parallel keys that can be acquired and the keys needed at one time exceed this limit, then it's probably not possible to solve this issue.
