### ISSUE TITLE
How to get PCM data of audio without play it?

### ISSUE THREAD

**Issue by Ding-Chuan** [androidx/media#527]
I want to use ExoPlayer to decode audio and obtain PCM data, and then write it to a file. I noticed TeeAudioProcessor, but it seems to operate during playback. What I need is to decode all frames quickly without playing them. How can I achieve this? 
Thanks.

**Comment by andrewlewis** [comment]
What format do you want to write the audio data in? If AAC in MP4 is okay then [Transformer](https://developer.android.com/guide/topics/media/transformer) should support what you need, as it will load and decode audio, let you process it with a custom `AudioProcessor`, then encode and mux the result.

The reason I mention AAC in MP4 is that the output audio format needs to be supported by `MediaMuxer`. So for example, if you wanted to output PCM/WAVE audio then I think you'd need to implement a custom [`Muxer`](https://github.com/androidx/media/blob/release/libraries/transformer/src/main/java/androidx/media3/transformer/Muxer.java) as `MediaMuxer` doesn't support that output format.

**Comment by andrewlewis** [comment]
With Transformer the media doesn't play, but processed + encoded media does get output to the muxer. In your original message you mentioned writing it to a file -- could you elaborate on what you need?

**Comment by Ding-Chuan** [comment]
I have received helpful information from your answer. I mentioned writing to a file earlier to provide a more specific description of the use case. Thank you again.

**Comment by andrewlewis** [comment]
If you want to process media and not mux an output file you could try writing a muxer implementation that just throws away data, though this is a bit of work to do. We are aware that having a 'batch mode' for transformer would be useful but we probably won't get round to implementing it for a while.

Glad to hear this was helpful. I will close this now but please let us know if you need something else.

**Comment by Ding-Chuan** [comment]
Sorry to bother you again, but I need some help with Transformer. 
Specifically, I'm using audio as the input source for create video, and the default Transformer output is an mp4 video file that only contains one audio track. How can I add an additional video track that includes only some images or video frames generated from PCM continuously?
