### ISSUE TITLE
Query on Tunneled playback

### ISSUE THREAD

**Issue by onlytanmoy** [androidx/media#530]
Hi, I am using ExoPlayer in my Shield TV Pro 2019 device. Can I enable Tunneled playback? I am not sure if Shield supports it or not so thought of clarifying. Thanks!

**Comment by icbaker** [comment]
You can enable tunneling as described here: https://developer.android.com/guide/topics/media/exoplayer/track-selection#tunneling

Whether it's supported by a particular device is out of scope for this issue tracker (we just maintain the library, we don't have expertise on the specific capabilities of different hardware).
