### ISSUE TITLE
How to  change Overlay coordinates 

### ISSUE THREAD

**Issue by zoomGitS** [androidx/media#531]
How to set coordinates of overlay(TextureOverlay) , it is always positioned in the middle of video.

**Comment by tof-tof** [comment]
An overlay can be positioned using the [OverlaySettings](https://github.com/androidx/media/blob/release/libraries/effect/src/main/java/androidx/media3/effect/OverlaySettings.java).

In this class, there is an ability to `setMatrix(float[] matrix)`, providing an [openGL matrix](https://developer.android.com/reference/android/opengl/Matrix). Matrix transformations can be used to translate the overlay to the desired point and scale it accordingly.  You can see multiple examples of how this is done in our [tests](https://github.com/androidx/media/blob/release/libraries/effect/src/androidTest/java/androidx/media3/effect/OverlayShaderProgramPixelTest.java).


FYI: in the 1.2.0 release, where simplifying this api, taking setMatrix() out and adding explicit methods `scale()` and `setAnchor()` methods to customize the overlay for ease of use.
