### ISSUE TITLE
Support providing OPUS base gain in `Metadata`

### ISSUE THREAD

**Issue by OxygenCobalt** [androidx/media#540]
### Use case description
Users of my app use volume adjustments in their audio files. In the case of Opus, this includes a base volume adjustment in it's header. Currently, this is seemingly not applied via ExoPlayer or by MediaCodec.

### Proposed solution
Since volume adjustment is likely out-of-scope for ExoPlayer or MediaCodec, I'd either want a new field in `Metadata` or a hard-coded `VorbisComment` that provides the base volume adjustment from the OPUS header. 

### Alternatives considered
Applying a hard-coded adjustment assuming that the base header value will be most likely be 5 dB, which is inflexible and will lead to more edge-cases later.

**Comment by microkatz** [comment]
@OxygenCobalt

You said that your users provide the "base volume adjustment in the header". Are you referencing the Output Gain in the ID Header referenced by [RFC 7845](https://datatracker.ietf.org/doc/html/rfc7845#section-5.1)? The default Ogg and Matroska extracters copy the header payload bytes into the Format's initializationData field. You might be able to grab the Format from `getAudioFormat()` and parse the initializationData bytes for the Output Gain and adjust the output volume from there.

**Comment by OxygenCobalt** [comment]
Yes, that's what I'm talking about @microkatz. I've always referred it as base gain to differentiate it from other types of volume adjustments. I'll try the solution you proposed.

**Comment by microkatz** [comment]
Great! Hopefully that works for you. I'm going to close this issue, please re-open or recreate if you have additional questions.
