### ISSUE TITLE
How to construct shuffled indices for media items in Media3?

### ISSUE THREAD

**Issue by iZakirSheikh** [androidx/media#541]
Hello,

I'm using latest version of Media3 to play a playlist of media items with shuffle mode enabled. I want to know how to construct the shuffled indices for the media items, so that I can access them by their shuffled position.

According to bing chat, In ExoPlayer, there was a method called getShuffledIndex() in the Timeline class, which returned the shuffled index of a media item from its original queue index. However, this method was removed in Media3 1.1.0-alpha01.

Is there a better way to construct the shuffled indices for the media items in Media3? If not, could you please consider adding a method or a utility class for this purpose?

Thank you for your help and your great work on Media3.

**Comment by oceanjules** [comment]
A quick search among our issues landed me with:

1. https://github.com/androidx/media/issues/325
2. https://github.com/androidx/media/issues/343
3. https://github.com/google/ExoPlayer/issues/5426
4. https://github.com/google/ExoPlayer/issues/6431
5. https://github.com/google/ExoPlayer/issues/9611

If any of these help you (if not to resolve your issue, then at least to confirm you want the exact same enhancement that others have already reported), let me know!
