### ISSUE TITLE
Jerkiness on 50 fps DASH stream with Widevine DRM - Arcadyan TV box Android 7

### ISSUE THREAD

**Issue by hugohlln** [androidx/media#544]
### Version

ExoPlayer 2.18.4

### Devices that reproduce the issue

Arcadyan TV box running on Android 7. API Level Version 24

Chipset marvell berlin 
https://android.googlesource.com/kernel/msm/+/android-7.1.0_r0.2/Documentation/devicetree/bindings/arm/marvell,berlin.txt?autodive=0%2F%2F%2F

### Devices that do not reproduce the issue

Other generic android TV devices
Arcadyan TV boxes running on Android 8 or greater

### Reproducible in the demo app?

Yes

### Reproduction steps

Play the given media
Wait until video jerkiness appears
It usually appears in the first five minutes

### Expected result

Video jerkiness should not appear on the screen

### Actual result

When playing the stream some jerkiness appears on the screen.

Here is what we did to find the reason :
- Jerkiness does not appear when we play the same stream but without DRM.
- We are sure that the jerkiness doesn't come from the source because we tried the stream on other android devices and nothing happened. Only this device is concerned by the issue.
- We tried to play the same stream but from another CDN, but it doesn't change anything.
- It's impossible to give any jerkiness apparition frequency, sometimes it happens twice a minute while sometimes we don't see any video jerkiness during 10 minutes
- We also ensured that the problem doesn't come from our bandwidth, but after some verifications, we saw that the player returns an estimated bandiwdth > 100 mbits/s
- On the same stream, when switching to another profile in 25 fps, we can't see any video jerkiness
- We saw similar issues on the ExoPlayer github but it's on older versions and all potential fixes don't work
- We tried to enable tunneling we it didn't change anything

What would you recommend us to do ?

Thank You

### Media

Not applicable since we can reproduce the issue with other DASH Widevine DRM protected in 50fps

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
It's likely that this device just isn't performant enough to both decrypt and decode the content at 50fps. You don't mention what resolution of content you observe this with, but I suspect this is more likely with high resolution/bitrate content.

You can see the minimum requirements for Android 7 video decoding support here (e.g. up to 60fps for 1080p H.265): https://source.android.com/docs/compatibility/7.0/android-7.0-cdd#5_3_video_decoding

Although there's no explicit wording in that CDD that these thresholds must **also** be supported for secure DRM playback (more recent CDDs do have explicit requirements about secure video decoding performance).

You are likely best off restricting the track selection to not select these 50fps tracks on this device - there's not really anything we as a library can do.

> We saw similar issues on the ExoPlayer github but it's on older versions and all potential fixes don't work

I assume you have already tried enabling async interactions with `MediaCodec`: https://developer.android.com/guide/topics/media/exoplayer/customization#enabling-asynchronous-buffer-queueing

**Comment by hugohlln** [comment]
This is a 1920x1080 video at 7.2 mbits/s

> I assume you have already tried enabling async interactions with MediaCodec: https://developer.android.com/guide/topics/media/exoplayer/customization#enabling-asynchronous-buffer-queueing
Yes we already tried that, but still not working

**Comment by tonihei** [comment]
Just checking - is this a live stream or VOD? And in case it's a live stream, do you also observe the same problem with DRM-protected VOD streams with similar resolution/frame rate properties? I'm asking because of a similar sounding issue in https://github.com/androidx/media/issues/385 where the behavior only seems to occur for live streams.

**Comment by hugohlln** [comment]
> Is the 2160p@50fps non-DRM content? Is the 1080p 50fps widevine content also H.265?
1080p@50 FPS Widevine DRM content protected H.264
2160p@50 FPS Widevine DRM content protected H.265

**Comment by icbaker** [comment]
That suggests the H.265 decoder is simply more performant, so ensures more time is available for the device to spend on decryption of each frame. It still seems like a device performance issue to me?

For **unprotected** content on Android TV devices (I'm assuming this is an Android TV device), the CDD requires 1080p @ 60fps H.264 (i.e. this device doesn't meet this bar when playing encrypted content). But as I said above, I don't see anything in the Android 7 CDD setting minimum performance requirements for secure playback.

**Comment by hugohlln** [comment]
Ok, thanks for your reply.

The device on which we are experiencing these problems is not ours. It's an operator's TV box on which we offer our application to our customers. So we have no control over it. The device is an Android AOSP.

Would it be possible to help us and tell us which metrics in the player or anything else would be interesting to monitor to make it clear to the TV box manufacturer that it's the device that's responsible for the jerks we're seeing on our stream?
