### ISSUE TITLE
No voice can be heard with OPUS offload playback 

### ISSUE THREAD

**Issue by zling123** [androidx/media#545]
# [Description]
I created an APK using ExoPlayer, the lib version is latest 2.19.0.
When I enable Offload mode, AAC can be played normally (voice can be heard and the log shows it is using compress-offload-playback).
But OPUS did not play as expected (the clip finish playing but voice cannot be heard, and the log shows it is using compress-offload-playback).

# [Question]
Are there any special setup/APIs for OPUS offload playback compared to AAC?

**Comment by zling123** [comment]
I confirmed that OPUS offload playback is supported on my phone.

**Comment by zling123** [comment]
Solved!
It might be a bug on lib2.19.0.
I added this code https://github.com/google/ExoPlayer/commit/4c894aa6a961fb53e92bf01361f8459d65055af3 to branch release-v2, and then audio can be heard.
Is there any plan to commit this change to branch release-v2?

**Comment by microkatz** [comment]
Hello @zling123,

Glad that fixed the issue! Yes, https://github.com/google/ExoPlayer/commit/4c894aa6a961fb53e92bf01361f8459d65055af3 will be added to the next release which should be 1.2.0. 

Since the issue has been addressed I'm going to close this. Thank you!!
