### ISSUE TITLE
Download from rtsp is still non-supported ?

### ISSUE THREAD

**Issue by xiejane** [androidx/media#546]
I want to record the video form IPCAM by rtsp, has it updatde in exoplayer3 to support downloading from RTSP?

**Comment by claincly** [comment]
I don't think we'll support downloading RTSP streams as they are live and we don't currently have a method for a user to stop the stream. 

There is a way to hack it to work though - by using Transformer, but the caveat is you can't use ExoPlayer's PlayerView to look at the video as it's being downloaded. You can however preview the video using DebugPreviewProvider.

Let me know if this something you want and I can provide more info on how to hack it. Note this will not be officially supported.

**Comment by xiejane** [comment]
> I don't think we'll support downloading RTSP streams as they are live and we don't currently have a method for a user to stop the stream.
> 
> There is a way to hack it to work though - by using Transformer, but the caveat is you can't use ExoPlayer's PlayerView to look at the video as it's being downloaded. You can however preview the video using DebugPreviewProvider.
> 
> Let me know if this something you want and I can provide more info on how to hack it. Note this will not be officially supported.

Thanks, please show me.  I just need to download, playing is not important. 

And  I want to get the byte array of the each frame to support analysis, can you provide me more info ? 

Thanks a lot.

**Comment by claincly** [comment]
Sorry for the delayed reply - yes you could download the video with Transformer, but this only works with VOD streams, meaning the stream has to be of limited duration, and the server has to stop send data after the video stream ends. In other words, this won't work with live streams, like the stream from a webcam.

If that is OK with you, you could do the download as simple as 

```
Transformer transformer = new Transformer.Builder(context).addListener(...).build();
transformer.start(MediaItem.fromUri(/* RTSP URI */);
// wait until done in Transformer.Listener.onCompleted()
```

(you also need to add dependency of  `lib-transformer` and `lib-exoplayer-rtsp` to your project)

As for analyzing each frame - this is not very easily doable at the moment (although doable), could you let us know what sort of analysis you are looking for?
