### ISSUE TITLE
Text in forward button inside player controls not readable when using Material 3 theme

### ISSUE THREAD

**Issue by cemrich** [androidx/media#547]
### Version

Media3 1.1.0

### Devices that reproduce the issue

Should affect all devices, but tested with:
- Fold-Out Emulator Android 11
- Pixel 7 Android 13

Some more users reported this on Zapp: https://github.com/mediathekview/zapp/issues/366

### Reproducible in the demo app?

Yes

### Reproduction steps

- Replace the parent of `PlayerTheme` in the demo app with `Theme.Material3.Dark` or some other material 3 theme
- Play back any video
- Tap to show the control view buttons

### Expected result

The prev button should display the default **15 seconds forward increment** in a readable way.

### Actual result

The prev button seemingly displays a **5 seconds forward increment**: 
![grafik](https://github.com/androidx/media/assets/403202/a3234ae8-0dde-4a9f-8e51-7c10f23188b3)

However, according to the layout inspector the text is set correctly. It does break in an unfortunate way, so only the 5 figure is visible to the user.

### Media

Clear DASH > HD

But this issue occurs with every video file.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by rohitjoins** [comment]
Hi @cemrich,

Thanks for reporting the issue. I can confirm that this issue is reproducible on the demo app. I'll assign this to someone who knows more about UI.

**Comment by cemrich** [comment]
I openend a PR that should fix this issue - it might take a bit for it to be merged and released.
