### ISSUE TITLE
What could cause renderers to get stuck?

### ISSUE THREAD

**Issue by ggabdol** [androidx/media#550]
We are seeing quite a few HLS live streams that get stuck on [ExoPlayer renderer](libraries/exoplayer/src/main/java/androidx/media3/exoplayer/Renderer.java) when we enable **tunneling** mode using ExoPlayer 2.18.7.
The following log snippet were captured when the problem occurred, printing playback positions every second.

```
07-26 14:31:09.023 1513-1513/com.att.tv.openvideo D/PlayerLogs: Playback is in Progress... progressMilliseconds 3702561 durationMilliseconds 3738001 windowStartTime 1690403316563
07-26 14:31:10.037 1513-1513/com.att.tv.openvideo D/PlayerLogs: Playback is in Progress... progressMilliseconds 3703558 durationMilliseconds 3738001 windowStartTime 1690403316563
07-26 14:31:11.023 1513-1513/com.att.tv.openvideo D/PlayerLogs: Playback is in Progress... progressMilliseconds 3704561 durationMilliseconds 3744007 windowStartTime 1690403316563
07-26 14:31:12.022 1513-1513/com.att.tv.openvideo D/PlayerLogs: Playback is in Progress... progressMilliseconds 3705565 durationMilliseconds 3744007 windowStartTime 1690403316563
07-26 14:31:13.023 1513-1513/com.att.tv.openvideo D/PlayerLogs: Playback is in Progress... progressMilliseconds 3706563 durationMilliseconds 3744007 windowStartTime 1690403316563
07-26 14:31:14.023 1513-1513/com.att.tv.openvideo D/PlayerLogs: Playback is in Progress... progressMilliseconds 3707562 durationMilliseconds 3744007 windowStartTime 1690403316563
07-26 14:31:15.024 1513-1513/com.att.tv.openvideo D/PlayerLogs: Playback is in Progress... progressMilliseconds 3708565 durationMilliseconds 3744007 windowStartTime 1690403316563
07-26 14:31:16.023 1513-1513/com.att.tv.openvideo D/PlayerLogs: Playback is in Progress... progressMilliseconds 3709563 durationMilliseconds 3744007 windowStartTime 1690403316563
07-26 14:31:17.022 1513-1513/com.att.tv.openvideo D/PlayerLogs: Playback is in Progress... progressMilliseconds 3710565 durationMilliseconds 3744007 windowStartTime 1690403316563
07-26 14:31:18.022 1513-1513/com.att.tv.openvideo D/PlayerLogs: Playback is in Progress... progressMilliseconds 3711560 durationMilliseconds 3750013 windowStartTime 1690403316563
07-26 14:31:19.024 1513-1513/com.att.tv.openvideo D/PlayerLogs: Playback is in Progress... progressMilliseconds 3711977 durationMilliseconds 3750013 windowStartTime 1690403316563
07-26 14:31:20.023 1513-1513/com.att.tv.openvideo D/PlayerLogs: Playback is in Progress... progressMilliseconds 3712813 durationMilliseconds 3750013 windowStartTime 1690403316563
07-26 14:31:21.022 1513-1513/com.att.tv.openvideo D/PlayerLogs: Playback is in Progress... progressMilliseconds 3713442 durationMilliseconds 3750013 windowStartTime 1690403316563
07-26 14:31:22.024 1513-1513/com.att.tv.openvideo D/PlayerLogs: Playback is in Progress... progressMilliseconds 3713442 durationMilliseconds 3750013 windowStartTime 1690403316563
07-26 14:31:23.023 1513-1513/com.att.tv.openvideo D/PlayerLogs: Playback is in Progress... progressMilliseconds 3713442 durationMilliseconds 3750013 windowStartTime 1690403316563
```
`progressMilliseconds` is the value returned from 
https://github.com/androidx/media/blob/5328d6464acb077a7e8cba61b8cac1973c4943d7/libraries/common/src/main/java/androidx/media3/common/Player.java#L2885

As you might notice, the playback position was not advancing at some point. I verified that all of the renderers were in `STATE_STARTED` state, Player was in `STATE_READY`, and there were enough loaded media data in the player buffer.

The followings are the time differences of log timestamps and current playback position.
| Timestamp    | Timestapm Diff | progressMilliseconds | progressMilliseconds Diff (second) |
| ------------ | -------------- | -------------------- | ---------------------------------- |
| 14:31:09.023 |                | 3702561              |                                    |
| 14:31:10.037 | 01.014         | 3703558              | 1.00                               |
| 14:31:11.023 | 00.986         | 3704561              | 1.00                               |
| 14:31:12.022 | 00.999         | 3705565              | 1.00                               |
| 14:31:13.023 | 01.001         | 3706563              | 1.00                               |
| 14:31:14.023 | 01.000         | 3707562              | 1.00                               |
| 14:31:15.024 | 01.001         | 3708565              | 1.00                               |
| 14:31:16.023 | 00.999         | 3709563              | 1.00                               |
| 14:31:17.022 | 00.999         | 3710565              | 1.00                               |
| 14:31:18.022 | 01.000         | 3711560              | 1.00                               |
| 14:31:19.024 | 01.002         | 3711977              | 0.42                               |
| 14:31:20.023 | 00.999         | 3712813              | 0.84                               |
| 14:31:21.022 | 00.999         | 3713442              | 0.63                               |
| 14:31:22.024 | 01.002         | 3713442              | 0.00                               |
| 14:31:23.023 | 00.999         | 3713442              | 0.00                               |

If you look at the last 5 lines, the playback position was not advancing in a constant rate and eventually get stuck.
I am investigating what can cause situation like that, and I'd really appreciate for any input on the possible cause.

**Comment by rohitjoins** [comment]
Hi @ggabdol,

Can you please provide us with a test media which can be used to reproduce this problem on our end? If you're unable to provide test content publicly, please send them to android-media-github@google.com with the subject
`Issue #550`. Please also update this issue to indicate you've done this.
