### ISSUE TITLE
playback preview mode support

### ISSUE THREAD

**Issue by AndyYoung1004** [androidx/media#551]
### [REQUIRED] Use case description
can we support preview function when playback?
we can only preview when transcoding process and we need prview
function when we playback avsync

### Proposed solution
we import avsync playback function and add filters or text

**Comment by andrewlewis** [comment]
[`ExoPlayer.setVideoEffects`](https://github.com/androidx/media/blob/5328d6464acb077a7e8cba61b8cac1973c4943d7/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/ExoPlayer.java#L1546) lets you pass effects to apply when playing video with ExoPlayer (including color filtering or adding text overlays).
