### ISSUE TITLE
Get stream ID using Exoplayer + IMA SDK DAI Extension

### ISSUE THREAD

**Issue by mathDias** [androidx/media#555]
Hi everyone, 
I'm looking for a way to get the session ID to debug the ad requests without a Charles Session.

Into the IMA SDK documentation, there is a way to retrieve this value using the method: https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side/api/reference/com/google/ads/interactivemedia/v3/api/StreamManager.html#getStreamId()

But I wasn't able to use that with the Exoplayer IMA Extension, is it possible?

Another option to debug that I've found was passing a UUID on setStreamMonitorID during the ssaiLiveUri builder. Example:

```
Uri ssaiLiveUri =
            new ImaServerSideAdInsertionUriBuilder()
                    .setStreamActivityMonitorId("5d19a744-b5a8-4ae3-81c3-4c30ecb6244f")
                    .setAssetKey(SAMPLE_ASSET_KEY)
                    .setFormat(CONTENT_TYPE_HLS) // Use CONTENT_TYPE_DASH for dash streams.
                    .build();
```
But I think that it isn't the best way.
I'm using the code from https://github.com/googleads/googleads-ima-android-dai/tree/main/ExoPlayerExample example to test.

Thanks!

**Comment by tonihei** [comment]
This value isn't published at the moment. Do you know if it's changing per ad/content or is it a single value per DAI stream? I can't quite tell from the documentation. Depending on how often it changes, we can either add it to the ad metadata or add a getter/callback elsewhere in the IMA extension classes.

**Comment by rajneeshrawal** [comment]
Hi,

I am having a similar requirement where I need to use StreamID for event tracking purposes in my application. 
[(https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side/api/reference/com/google/ads/interactivemedia/v3/api/StreamManager.html#getStreamId())]
IMA SDK extension doesn't provide any callback or method to get this ID.
I am adding the extension in the build.gradle 
implementation "com.google.android.exoplayer:extension-ima:2.18.1"

Is there any workaround to get streamID from the  IMA SDK extension?
Thanks.

**Comment by marcbaechinger** [comment]
> Do you know if it's changing per ad/content or is it a single value per DAI stream?

The latter I think. The stream manager is provided by the SDK when resolving an assetKey/videoId to a content URI while the `ImaSSAIMediaSource` is prepared. I don't know of a way to reuse a stream manager for another stream. AFAICT, the stream ID doesn't change for the same `StreamManager` instance, at least for how we use the SDK.

> Is it possible to get the StreamManager callback from the IMA SDK extension?

It's possible to register your own listener, but I don't think you can get the Stream ID from these events. Does someone know whether this is possible? That would be nice and solve the prob. 

When you build the ads loader to configure `ImaServerSideAdInsertionMediaSource` , you can use `ImaServerSideAdInsertionMediaSource.AdsLoader.Builder.setAdEventListener(AdEvent.AdEventListener)` and `ImaServerSideAdInsertionMediaSource.AdsLoader.Builder.setAdErrorListener(AdErrorEvent.AdErrorListener)` to pass your own listeners. 

These will be [set to the stream manager](https://github.com/androidx/media/blob/release/libraries/exoplayer_ima/src/main/java/androidx/media3/exoplayer/ima/ImaServerSideAdInsertionMediaSource.java#L643) as soon as it becomes available after the content URI has been resolved. The JavaDoc of the builder is wrong in saying how the listener is used. I'll fix this.

> I'm looking for a way to get the session ID [...]
> Is there any workaround to get streamID from the IMA SDK extension?

Like Toni said that is currently not published and I guess this is a valid request.

My first idea is making our own listener that extends from `AdEvent.AdEventListener`. We can then just keep it as we have it in the `AdsLoader.Builder` and add some more callbacks that we can call in the life-cycle of a IMA SSAI source, like when the stream ID becomes available. 

Essentially: We discuss/resolve details internally, but we'll provide a way to get that stream ID.

**Comment by marcbaechinger** [comment]
With the commit above an app can now set a `StreamEventListener` when building the ads loader. It is called each time the stream ID changes. This is basically, when the `StreamManager` becomes after the stream request is completed by the IMA SDK.

```java
serverSideAdsLoader = 
    new ImaServerSideAdInsertionMediaSource.AdsLoader.Builder(/* context= */ this, playerView)
      .setStreamEventListener(new ImaServerSideAdInsertionMediaSource.StreamEventListener() {
        @Override
        public void onStreamIdChanged(MediaItem item, String streamId) {
          Log.d("dai", "onStreamIdChanged: " + item.localConfiguration.uri + " resolved to " + streamId);
        }
      })
      .build();
```

```java
/** A listener to be notified of stream events. */
public interface StreamEventListener {

  /**
   * Called when the {@linkplain StreamManager#getStreamId() stream ID} provided by the IMA SDK
   * changed.
   *
   * <p>This method is called on the main thread.
   *
   * @param mediaItem The media item that the source resolved to the given stream ID.
   * @param streamId The stream ID.
   */
  void onStreamIdChanged(MediaItem mediaItem, String streamId);
}
```
