### ISSUE TITLE
Where do i process downloaded chunks for decryption purposes?

### ISSUE THREAD

**Issue by markg85** [androidx/media#562]
Hi,

I'm using the [NextPlayer](https://github.com/anilbeesetti/nextplayer) which in turn uses [ExoPlayer](https://github.com/google/ExoPlayer. I've been told that the URL handling (so downloading the content and presenting it on display) is done by ExoPlayer hence asking my question here.

I want to hook into the downloaded data to do processing before it's send on to the player.
Specifically i want to do AES decryption.

The idea here is that the whole video file is encrypted thus i need to provide a way to decrypt that data.
I did search around in the ExoPlayer source but couldn't quite find the point in code that was downloading a blob of data and forwarding it to the media library, a pointer to that part would be much appreciated!

I explicitly **do not** want to use HLS or DASH for this. These formats specify their own encoding scheme which is something i don't want. I want to use whole-file encryption/decryption which is codec/format/container agnostic.

Thanx,
Mark

### Update 5-8-2023
I'll leave the above for reference.

After a **lot** debugging i figured i kinda figured it out though i can't get it working. Yet.

The player has a lot of source layers (CacheDataSource.java, asset..., some more and in the deepest layer you have **CronetDataSource.java**).

I tried modifying CronetDataSource.java (in the read(...) function) to hack in AES decryption.
An issue i'm facing in that function is that CronetDataSource.java is just getting data from HTTP (with some more layers). That's fine for playback, but not for decryption. AES decryption (CBC in this case) works on blocks. If a block is too small the decryption fails. In my case i need to have 16-byte blocks. That data that the `read` function receives is nearly never aligned to a multiple of 16-bytes. So i tried to be smart (and failed) to get the current buffer and cut it off at the highest multiple of 16-bytes. This means that in many read calls i have "bytes left" that can't be parsed. So i "remember" those remaining blocks and prepend them to a new read so that all data does get decrypted.

That approach doesn't work.

Alternatively, ExoPlayer also has a load of so called "extractors" (MatroskaExtractor, FragmentedMp4Extractor, and a load more). I did think about creating a, say, "AesExtractor" that would just constantly require a 16-byte aligned buffer (which it can build as those extractors have a read function too) and from there pass it on the the current extractors. But that seems super complex so i rather don't go that route.

That leaves me with a couple questions:
- Which place in the ExoPlayer codebase is the proper point to "glue in" AES decryption?
- How can that place get 16-byte aligned data?
- If still going for hacking CronetDataSource.java to support AES (don't care about the place, that place would be fine for my case as all content comes in over http anyhow) then how do i force the read function in that class to always have 16-byte aligned data?

**Comment by markg85** [comment]
.. bump ..

**Comment by marcbaechinger** [comment]
> Which place in the ExoPlayer codebase is the proper point to "glue in" AES decryption?

I think I'd look into a `DataSource` implementation that reads the encrypted file from an upstream data source and decrypts what it reads from upstream. `androidx.media3.datasource.AesCipherDataSource` is such an example. The extractor of the container you are using then reads clear bytes from that data source as when reading a clear file directly.

I'm not an expert and not exactly sure I understand your specific requirements. If `AesCipherDataSource` isn't the right thing, then it gives an idea of how to integrate this

> How can that place get 16-byte aligned data?

I don't understand the encryption details to support you here I'm afraid. Naively I'd say you can `read` a byte array from the upstream `DataSource` as you like. See `DataSource.read(byte[] buffer, int offset, int length)`.

@icbaker probably has some thoughts.

**Comment by markg85** [comment]
> I'm not an expert and not exactly sure I understand your specific requirements. If AesCipherDataSource isn't the right thing, then it gives an idea of how to integrate this

The concept is really easy so i'll try to explain it in a way that conveys both the beauty but also the requirement of it.

This all has to do with sharing data between parties. Let's call them X and Y.
In a normal web environment you'd share data (let's say videos for this example) through private means. Like for example a dropbox link, a weshare link or through one of the many cloud storage providers. A share between X and Y is just a normal playable video.

In a web3 context we're talking about decentralized environments and public networks. Sharing data between X and Y goes over a public network which makes it fairly easy for a nefarious actor to eavesdrop on the network. With plain data that entity (let's call it Z) can now see whatever X and Y are sharing.

A solution here is encryption (i'm leaving the key sharing mechanism aside for simplicity). To use a public network for private data you need to encrypt data. So for X and Y to share a video, X now makes that video available in an encrypted format (has 0 todo with HLS, just file encryption) and Y needs to be able to decrypt that data. Eavesdropping actors like Z can't do a thing with this data as they lack the key. And here you have the recipe for using a public network for private data. For this to be as hassle free as possible, the player should understand how to decrypt this data and that's where my initial request comes from. To support this form of data decryption regardless of video container format used. The share between X and Y might be an AVI file, might be an MKV file. It shouldn't matter. The player should decrypt the data and perform it's format detection with the decrypted data to play it.

> I think I'd look into a DataSource implementation that reads the encrypted file from an upstream data source and decrypts what it reads from upstream. androidx.media3.datasource.AesCipherDataSource is such an example.

That might very well be the class i need! Thank you for the pointer!

**Comment by icbaker** [comment]
`AesCipherDataSource` sounds like the right tool for this, and if it's not flexible enough then, as Marc says, you can use it as inspiration to write your own custom `DataSource`. If you write a custom one, I would strongly recommend writing a contract test around it: https://medium.com/google-exoplayer/standardising-datasource-implementations-through-testing-b7a8ab04f8d1

I'm going to close this as it sounds like the question has been answered.

**Comment by markg85** [comment]
Will go that route.
Thanx for the input, that's much appreciated!

**Comment by dhavaln** [comment]
@markg85 I have a similar problem, where we need to provide support for Ac3 decryption at the Device-end. In our case, the source is a LIVE stream and not a file. At the moment we are using VLC lib, but we are unable to find the right mechanism to do that. I am trying to switch away from VLC and we are checking if ExoPlayer can be used as a replacement or not. Based on the readings of this thread, were you able to develop any solution, or if you can help me point in the right direction? Much appreciated.

**Comment by markg85** [comment]
@dhavaln My route turned out to be playing a "file" over http, so i suppose streaming rules apply there too.

Long story short, I have's gotten it to work.

I did create a different datasource that is decrypting the file and seems to be working fine for the first 32KB or so, after that it breaks down. This means it already breaks down in determining the codec of the decrypted data. I haven't figured out why yet (padding biting me?), but then again haven't quite worked on it much more then say 1 or 2 days since my last post. I can probably get it working when i get back at it again.

This stuff is super hard to debug because it goes through a lot of format detection code where it's read a byte at a time.

That all being said, are you sure we're talking about the same thing here?
AC3, as far as i'm aware, is an audio codec. It has nothing the do with encryption and/or decryption. It would be one of the audio streams within a video (container) format like mkv for example.

**Comment by dhavaln** [comment]
Sorry yes, that's my bad, the AC3 part is nonrelevant here. Thanks for pointing that out. 

I was hoping that Exoplayer would allow to do the pre-processing of the frames/blocks before the rendering.
