### ISSUE TITLE
Exoplayer play video or audio where ssl has expired.

### ISSUE THREAD

**Issue by chitgoks** [androidx/media#566]
Before filing a feature request:
-----------------------
- Search existing open issues, specifically with the label ‘enhancement’:
  https://github.com/androidx/media/labels/enhancement
- For ExoPlayer-related feature requests, please also check for existing feature
  requests on the ExoPlayer tracker:
  https://github.com/google/ExoPlayer/labels/enhancement
- Search existing pull requests:
    - On this tracker: https://github.com/androidx/media/pulls,
    - On the ExoPlayer tracker: https://github.com/google/ExoPlayer/pulls

When filing a feature request:
-----------------------
Replace the content in the sections below.

### [REQUIRED] Use case description
A video/audio file where the source site's ssl has expired should still be able to play.

I read this Fixing “SSLHandshakeException”, “CertPathValidatorException” and “ERR_CERT_AUTHORITY_INVALID” errors
SSLHandshakeException, CertPathValidatorException and ERR_CERT_AUTHORITY_INVALID all indicate a problem with the server’s SSL certificate. These errors are not ExoPlayer specific. Please see [Android’s SSL documentation](https://developer.android.com/training/articles/security-ssl#CommonProblems) for more details.

But is there currently a way to pass this to the exo player?

### Proposed solution
There are already code out there to bypass certificate issues e.g. invalid, expired etc. but this requires having a reference to the http client. can exo player provide a way for users to do so? I figure connecting is internal so there is no way for users to override it (please correct me if im wrong).

### Alternatives considered
None

**Comment by icbaker** [comment]
> There are already code out there to bypass certificate issues e.g. invalid, expired etc. but this requires having a reference to the http client.

The link you posted above (https://developer.android.com/training/articles/security-ssl#CommonProblems) doesn't seem to suggest making changes to an 'http client', it suggests putting the changes in a `network_security_config.xml` file. I don't think any changes are needed in this library in order to follow those instructions.

**Comment by chitgoks** [comment]
ok ill close this issue.

i actually tried that before creating an issue ticket here but it did not work. will see if i probably missed something else.
