### ISSUE TITLE
Changing the buffer values dynamically without creating new player instance

### ISSUE THREAD

**Issue by karthik3389** [androidx/media#568]
We need to create a new Exoplayer instance if we want to change buffer values via (Default)LoadControl. Is there a way to change the buffer values dynamically without creating a new instance of the player?

**Comment by tonihei** [comment]
This is not supported by the default class. But you can provide your own `LoadControl` implementation that forwards calls to a `DefaultLoadControl` class and then allow your custom `LoadControl` to recreate its wrapped instance with new parameters if needed. Note that methods on `LoadControl` are called on an internal playback thread and your reconfiguration is likely triggered by your app's main thread, so you need to be careful about threading here.

**Comment by tonihei** [comment]
Forgot to reply here, sorry for that! 

> Now DefaultLoadControl.Builder() is marked @UnstableApi is there a Stable API to do this ?

`@UnstableApi` does not mean you can't use it, just that we don't provide the same guarantees about not changing the APIs  in the future. See https://developer.android.com/reference/androidx/media3/common/util/UnstableApi for more details
