### ISSUE TITLE
Time fallback obtained by getCurrentPosition during playback

### ISSUE THREAD

**Issue by Jasper-5572** [androidx/media#569]
I have a requirement that when playing a video, the preview frame should be displayed in real-time, which is displayed in a timeline manner. My current processing method is to use a timer to obtain the timestamp of the current broadcast of ExoPlayer in real time, and then dynamically slide the timeline. However, some videos have issues with getCurrentPosition on certain phones. The following is a screenshot of the log：

![image](https://github.com/androidx/media/assets/59760719/1389baf9-a8f4-466e-8b2a-cf5579c6e59f)

**Comment by tianyif** [comment]
@Jasper-5572,

Could you please provide a sample video and phone information that you were seeing the time flipping up and down?
