### ISSUE TITLE
On seeking more than half over a downloaded m4a file, makes the AudioPlayer go silent, but still showing as playing.

### ISSUE THREAD

**Issue by Shabinder** [androidx/media#575]
### Version

Media3 1.1.0

### Devices that reproduce the issue

 - Nothing Phone 1.
 - AVDs as well.

### Reproducible in the demo app?

Not tested

### Reproduction steps

Just have Exoplayer instantiated with DefaultMediaSourceFactory, and load the shared file into it, 

 - if you skip only to a small portion to left / right, all works as expected.
 - If you skip a substantial amount, like go after half duration when media is playing from start, the player continues playing but no sound comes from speaker.
 - If I retry and reach to same part of media by seeking repeatedly in smaller gaps, all works as expected.

This happens with all media files in my devices where I have tested.

### Expected result

Media Sound should always come from speaker.

### Actual result

 - If you skip a substantial amount, like go after half duration when media is playing from start, the player continues playing but no sound comes from speaker.
 - If I retry and reach to same part of media by seeking repeatedly in smaller gaps, all works as expected.

### Media

[Kala Chashma_Amar Arshi.m4a.zip](https://github.com/androidx/media/files/12317309/Kala.Chashma_Amar.Arshi.m4a.zip)

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by Shabinder** [comment]
Mail with bug report has been sent, let me know If I can share any more info to help nail this issue.

**Comment by tianyif** [comment]
Hi @Shabinder,

The specified issue was not reproducible on the demo app running on my Pixel device, with your provided media. I would recommend you to try to reproduce on:

* [demo app](https://github.com/androidx/media/tree/release/demos/main) running the phone that has this issue, and
* your app running the other phones

to see if this is an app integration / device specific problem.
