### ISSUE TITLE
Is it possible to set the output bitrate or constant rate factor (crf) using Transformer?

### ISSUE THREAD

**Issue by maf1ab0y** [androidx/media#578]
I want to perform video compression using Transformer. I can reduce resolution and frame rate, but I'm unsure how to reduce bitrate or CRF. Is that possible?

**Comment by droid-girl** [comment]
Yes, it is possible by using `VideoEncoderSettings`:
1) Use `VideoEncoderSettings` to set `bitrate` when creating an `EncoderFactory`:
```
EncoderFactory encoderFactory =
        new DefaultEncoderFactory.Builder(context)
            .setRequestedVideoEncoderSettings(
                new VideoEncoderSettings.Builder()
                    .setBitrate(bitrate)
                    .build())
            .build();
``` 
2) Set `encoderFactory` when building transformer:
```
 Transformer transformer =
        new Transformer.Builder(context)
            .setEncoderFactory(encoderFactory)
            .build();
```
