### ISSUE TITLE
The height and width are reversed when using Presentation and Transformer

### ISSUE THREAD

**Issue by maf1ab0y** [androidx/media#581]
### Version

Media3 1.1.0

### Devices that reproduce the issue

* Pixel 7 running Android 13
* Pixel 3 XL running Android 9

### Reproducible in the demo app?

Not tested

### Reproduction steps

I'm attempting to compress a video using the following code (The input video resolution is 720x1600):

```
val editedMediaItem = EditedMediaItem.Builder(MediaItem.fromUri(uri))
            .setEffects(Effects(listOf(), listOf(Presentation.createForHeight(800))))
            .build()

val transformationRequest = TransformationRequest.Builder()
            .setVideoMimeType(MimeTypes.VIDEO_H264)
            .setAudioMimeType(MimeTypes.AUDIO_AAC)
            .build()

val transformer = Transformer.Builder(context)
            .setTransformationRequest(transformationRequest)
            .build()

transformer.start(editedMediaItem, outputPath)
```

Then I use the following code to obtain the output video resolution:

```
val cursor = context.contentResolver.query(uri, arrayOf(MediaStore.Video.VideoColumns.RESOLUTION), null, null, null)
cursor?.apply {
        moveToFirst()
        val resolution = getInt(getColumnIndexOrThrow(MediaStore.Video.VideoColumns.RESOLUTION))
        Timber.d(resolution)
}
```

### Expected result

The output video resolution should be 360x800

### Actual result

The output video resolution ends up being 800x360

### Media

https://github.com/androidx/media/assets/5085836/815c4ab8-8c3b-4e44-aade-639324735bc8

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by dway123** [comment]
Encoders are more compatible with videos where the width is greater than or equal to the height. Therefore, to produce videos that can be played on more devices, we do automatically rotate videos to always have a width greater than or equal to the height, after applying all other effects. 

This is described in our [comments](https://github.com/androidx/media/blob/5328d6464acb077a7e8cba61b8cac1973c4943d7/libraries/transformer/src/main/java/androidx/media3/transformer/VideoSamplePipeline.java#L431-L434) too. This is done in VideoSamplePipeline, which unfortunately isn't currently a customizable component.

**Comment by maf1ab0y** [comment]
Then what should I do to store the correct resolution in MediaStore? We need the accurate resolution for other tasks as well.

**Comment by andrewlewis** [comment]
Is the rotation reflected in [`MediaStore.MediaColumns.ORIENTATION`](https://developer.android.com/reference/android/provider/MediaStore.MediaColumns#ORIENTATION)?

**Comment by maf1ab0y** [comment]
Ah, I see. The rotation for that output video is 90 degrees
