### ISSUE TITLE
Create ExoPlayer In MediaSessionService

### ISSUE THREAD

**Issue by Easoncheng0405** [androidx/media#584]
I'm making a video player application which supports playing local videos, online mp4 and m3u8 videos
I use **CacheDataSource** to play videos that user has already cached, and if cache misses, fail back to **DefaultHttpDataSource**

Which DataSource to use or play local video depends on the URL of the video being played.
But in **MediaSessionService**, I must create the Exoplayer in **MediaSessionService.onCreate** callback
I have no way to determine the datasource parameters of the player

Can someone help me, thanks.

**Comment by marcbaechinger** [comment]
I think you can just use [`DefaultDataSource`](https://github.com/androidx/media/blob/release/libraries/datasource/src/main/java/androidx/media3/datasource/DefaultDataSource.java#L34-L57) that figures out what data source to use by inspecting the URI of the media.

See JavaDoc of `DefaultDataSource` for details.
