### ISSUE TITLE
(ExoPlayer 2.19.1) RTSP does not correctly fall back to TCP

### ISSUE THREAD

**Issue by machenmusik** [androidx/media#586]
### Version

ExoPlayer 2.19.1

### Devices that reproduce the issue

Android devices

### Reproducible in the demo app?

Not tested

### Reproduction steps

Set up an instance of https://github.com/bluenviron/mediamtx with RTSP protocols set to [tcp] (i.e. only supporting TCP).

Configure any test source, and attempt to connect to its RTSP path using ExoPlayer.

Exoplayer sends RTSP SETUP with no lower transport (i.e. UDP)
`Transport: RTP/AVP;unicast;...`

### Expected result

Upon receiving a 461 Unsupported Transport error, it does not retry with TCP.
So playback fails.

### Actual result

Upon receiving a 461 Unsupported Transport error, it should retry with TCP.

Exoplayer should retry, sending RTSP SETUP with TCP lower transport
`Transport: RTP/AVP/TCP;unicast;...`

Playback will then succeed.

### Media

Any test source for https://github.com/bluenviron/mediamtx 

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by microkatz** [comment]
Hello @machenmusik,

Thank you for reporting your issue! This is a bit surprising as fallback to TCP due to a 461 Unsupported Transport error in the RTSP SETUP Response was added to ExoPlayer 2.19.0 in this commit, https://github.com/google/ExoPlayer/commit/bbd45c8e4c838005846659dfa87c959804a042ed. Are you able to reproduce this in the demo app? If you were to add the RTSP url to media.exolist.json and try playing it?

Also in reproducing the issue, if you could share a [bug reports](https://developer.android.com/studio/debug/bug-report) then that would be helpful! If you are not able to send it publicly, please send them to android-media-github@google.com with the subject `Issue #586`. Please also update this issue to indicate you've done this.

**Comment by machenmusik** [comment]
Agreed it was surprising, as I had upgraded to 2.19.1 to try this specifically.  Maybe other changes obsoleted that commit?

I can't share a bugreport (sorry).

Is there a pre-built demo APK for 2.19.1 that I can try?  That would help rule out any build issues here.

**Comment by microkatz** [comment]
Hi @machenmusik,

Sorry there is not a pre-built demo APK and for non-technical reasons that is not something that we do. 

It would also require you to provide me the exact rtsp URI and have me build the APK for you with that.

If this helps, here is some documentation about how to use and deploy the demo app https://developer.android.com/guide/topics/media/exoplayer/demo-application

**Comment by machenmusik** [comment]
Thanks.  Will see if I can find time to get to this, but may not be able to... current workaround is to use the force RTP TCP option.

**Comment by Docteh** [comment]
Hi, what would the disk-space requirements for this? hopefully I can build and run the test in an emulator for less than 100GB

As a possibly off topic note, VRChat's Quest 2 build claims to be ExoPlayerLib/2.19.0 in user agent and also exhibits this bug.

**Comment by Arcitec** [comment]
> current workaround is to use the force RTP TCP option.

So you are saying that I can provide a "rtsp://" URL and ExoPlayer will immediately try TCP mode?

How to do that? Where is that setting?

**Comment by Arcitec** [comment]
@microkatz By the way, I have a possible theory why the automatic TCP fallback didn't work for the original reporter.

I assume that you (Katz) have already tested with a MediaMTX server where UDP is disabled (see original reporter's first post), and verified that the UDP to TCP fallback works?

If so, the reported issue may be outside of ExoPlayer:

The reporter used the VRChat video player.

I have seen discussions on Reddit saying that ExoPlayer takes a very long time to fall back to TCP when UDP fails (8+ seconds) and that this often hits the 10 second timeout of the VRChat video player and it then automatically aborts playback.

So it is possible that the ExoPlayer automatic TCP fallback was working but taking too long.

Here is an example discussion about it:

https://www.reddit.com/r/VRchat/comments/1gfhgdv/comment/lui2w6e/

And here is a whole thread where VRChat users are trying to solve all these streaming issues:

https://feedback.vrchat.com/feature-requests/p/support-rtspt-protocol-streams-on-quest

Do you think that might be the issue? If you have already verified that MediaMTX with UDP disabled is working with ExoPlayer in your own tests, then my only conclusion is that this external issue is the reason.

**Comment by microkatz** [comment]
@Arcitec 

Foremost, we are not responding to issues on the old ExoPlayer project in general. If you would like to submit a question or issue to the androidx/media project, https://github.com/androidx/media, then we would be happy to help!

However just to note an answer to the question about forcing TCP. The API is in `RtspMediaSource.Factory' and is setForceUseRtpTcp. Here is a link to the code, https://github.com/androidx/media/blob/release/libraries/exoplayer_rtsp/src/main/java/androidx/media3/exoplayer/rtsp/RtspMediaSource.java#L95. Hope that helps!

**Comment by Arcitec** [comment]
@microkatz 

> Foremost, we are not responding to issues on the old ExoPlayer project in general. If you would like to submit a question or issue to the androidx/media project, https://github.com/androidx/media, then we would be happy to help!

Oh, sorry, I didn't realize that this repo is abandoned. But I am really confused, the URL you just gave me is to the repo I just commented on.

> However just to note an answer to the question about forcing TCP. The API is in `RtspMediaSource.Factory' and is setForceUseRtpTcp.

Thank you so much, that helped me find it! :heart:
