### ISSUE TITLE
seekTo doesn't do anything while video is playing

### ISSUE THREAD

**Issue by silverAndroid** [androidx/media#593]
### Version

Media3 1.1.1

### Devices that reproduce the issue

Samsung Z Fold 4 running Android 13
Pixel 6 Pro running Android 13

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Modify the main demo app to call `player.seekTo(5000)` either before or after `playerView.setPlayer(player)` is called.
2. Play one of the selected videos

### Expected result

Player seeks to the media successfully

### Actual result

Player doesn't seek at all

### Media

https://drive.google.com/file/d/1DpRu5HL7rbl5Irme7D4IHsxbwI63j4b6/view?usp=sharing

Video generated using FFmpegKit through (multiple attempts)
* `ffmpeg -i https://ta-044.a4cdn.pro/1ab5d45273a9183bebb58eb74d5722d8ea6384f350caf008f08cf018f1f0566d0cb82a2a799830d1af97cd3f4b6a9a81ef3aed2fb783292b1abcf1b8560a1d1aa308008b88420298522a9f761e5aa1024fbe74e5aa853cfc933cd1219327d1232e91847a185021b184c027f97ae732b3708ee6beb80ba5db6628ced43f1196fe/31014405f62933f3613ce2ec15abf3c4/ep.5.1691084753.m3u8 -c copy -f mkv -y /storage/emulated/0/Android/data/ca.digixp.aniplay/files/videos/145064_5.mkv`
* `ffmpeg -i https://ta-044.a4cdn.pro/1ab5d45273a9183bebb58eb74d5722d8ea6384f350caf008f08cf018f1f0566d0cb82a2a799830d1af97cd3f4b6a9a81ef3aed2fb783292b1abcf1b8560a1d1aa308008b88420298522a9f761e5aa1024fbe74e5aa853cfc933cd1219327d1232e91847a185021b184c027f97ae732b3708ee6beb80ba5db6628ced43f1196fe/31014405f62933f3613ce2ec15abf3c4/ep.5.1691084753.m3u8 -c copy -f mp4 -y /storage/emulated/0/Android/data/ca.digixp.aniplay/files/videos/145064_5.mp4`
* `ffmpeg -live_start_index 0 -ss 15 -i https://ta-044.a4cdn.pro/1ab5d45273a9183bebb58eb74d5722d8ea6384f350caf008f08cf018f1f0566d0cb82a2a799830d1af97cd3f4b6a9a81ef3aed2fb783292b1abcf1b8560a1d1aa308008b88420298522a9f761e5aa1024fbe74e5aa853cfc933cd1219327d1232e91847a185021b184c027f97ae732b3708ee6beb80ba5db6628ced43f1196fe/31014405f62933f3613ce2ec15abf3c4/ep.5.1691084753.m3u8 -c copy -f mp4 -y /storage/emulated/0/Android/data/ca.digixp.aniplay/files/videos/145064_5.mp4` <- Video above was generated using this command

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by marcbaechinger** [comment]
When I play the file that I downloaded from your link I can seek within that media as expected. 

The seekbar works as expected. I can for instance seek right before the end and then let playback continue until `STATE_ENDED` is reached.

Can you please, play the media in the demo app and then try moving the seekbar of the UI? If this doesn't work, then please take a bug report and upload it here. I can then look into the bug report to see whether the logs tells something about why this isn't working for you.

**Comment by silverAndroid** [comment]
Sorry if I wasn't clear, seeking through the seek bar works, but when I call seekTo in the application code (see demo app repro steps), it doesn't reflect the seek in the UI.

**Comment by marcbaechinger** [comment]
Yeah, I can't repro this either. WHich is a bit expected because the seekbar doesn't do something else then calling `player.seekTo()` .

I modified the main demo app so that a button calls `player.seekTo(5000)`.

1. I add your media to the main demo app
2. User starts playback.
3. User presses seekTo(5000)-button
4. The player seeks to 5 Seconds and the UI reflects this: 0:05
5. User uses the seekbar to seek to for instance  11:00
6. User presses seekTo(5000)-button
7. The player seeks to 5 Seconds and the UI reflects this: 0:05

This seems to work for me.

**Comment by silverAndroid** [comment]
I figured out that the reason was because it had something to do with trying to use Exoplayer with Jetpack Compose. Is there any guidance on using Exoplayer with Compose?

(In the meantime, I'm using a View-based Activity just for Exoplayer)

**Comment by marcbaechinger** [comment]
Ok, cool. Thanks for letting me know.

We don't have general guidance for using Compose I'm afraid. Please see [9654](https://github.com/google/ExoPlayer/issues/9654) also.

I'm closing as this issue seems resolved. Please file a new issue if you have further questions.
