### ISSUE TITLE
Can we join / concat two audio files

### ISSUE THREAD

**Issue by pawaom** [androidx/media#597]
Is it possible to to join two audio files, I have one audio file which is 10 seconds long and another one in 15 seconds long, I want to join them into one file of 25 seconds long can we do it with transformers, 

I have checked the Demo example TransformerActivity.java

and with this code 

```
 Transformer transformer = createTransformer(bundle, inputUri, filePath);
      Composition composition = createComposition(mediaItem, bundle);
```

It looks like we can use only one file, however is there an option to join mutiple files

**Comment by droid-girl** [comment]
It is currently not possible using `1.1.1` version however you can check out the `release-1.2.0-alpha01` or later upcoming releases and it should be possible to join/concat two audio files using this code: 
```
val audio1 = EditedMediaItem.Builder(MediaItem.fromUri(path1))
                    .build()
val audio2 = EditedMediaItem.Builder(MediaItem.fromUri(path2))
                    .build()
val audioSequence = EditedMediaItemSequence(ImmutableList.of(audio1, audio2))
val composition = Composition.Builder(ImmutableList.of(audioSequence)).build()
```
