### ISSUE TITLE
Will consider to support mts/m2ts format videos?

### ISSUE THREAD

**Issue by NanyangTaiji** [androidx/media#608]
Before filing a feature request:
-----------------------
- Search existing open issues, specifically with the label ‘enhancement’:
  https://github.com/androidx/media/labels/enhancement
- For ExoPlayer-related feature requests, please also check for existing feature
  requests on the ExoPlayer tracker:
  https://github.com/google/ExoPlayer/labels/enhancement
- Search existing pull requests:
    - On this tracker: https://github.com/androidx/media/pulls,
    - On the ExoPlayer tracker: https://github.com/google/ExoPlayer/pulls

When filing a feature request:
-----------------------
Replace the content in the sections below.

### [REQUIRED] Use case description
Describe the use case or problem you are trying to solve in detail. If there are
any standards or specifications involved, please provide the relevant details.

### Proposed solution
A clear and concise description of your proposed solution, if you have one.

### Alternatives considered
A clear and concise description of any alternative solutions you considered,
if applicable.

**Comment by tonihei** [comment]
I'm afraid this isn't supported. See https://github.com/google/ExoPlayer/issues/1488 that tracks this improvement (and where you also commented on recently). We are generally able to accept high-quality pull requests if your are willing to provide this enhancement. Note that in this case, it should make sure to reuse as much as possible from the existing TS extractor code and provide test content for extractor tests. To keep the history of the previous conversation, I'm going to close this one in favor of the existing issue on the ExoPlayer tracker.
