### ISSUE TITLE
How to access Muxer from Transformer

### ISSUE THREAD

**Issue by pawaom** [androidx/media#614]
How to access Muxer from Transformer

We are trying to use some audio processing for our video, for which we need to access the muxer of Transformer 
 
The audio processing code is different from the one used by Transformer,java class , we just want to use the muxer in order to process the video using the Transformer and the audio which is processed from our code and create a new video using both the features,

All we want is to access the muxer used by Transformer class, how can we do that

**Comment by SheenaChhabra** [comment]
@pawaom Can you please explain your requirements a bit more in details?

This is what I have understood so far
1. Process audio in your code.
2. Process video via Transformer.
3. Mux both audio and video using muxer.

The muxer used by Transformer can not be accessed directly but you can pass your custom muxer
https://developer.android.com/reference/androidx/media3/transformer/Transformer.Builder#setMuxerFactory(androidx.media3.transformer.Muxer.Factory)

If your requirement is to pass a custom implementation for processing audio then please let us know we can suggest accordingly.

**Comment by pawaom** [comment]
What we want to achieve is overlay audio over existing video which contains audio as well. 

For this in one of our previous issue raised here we were told it is currently not supported by transformer 

so for this we are using this library 

https://github.com/ZeroOneZeroR/android_audio_mixer#merging-audio-with-video-and-using-external-mediamuxer

however  we also came across this in a different issue raised here

https://github.com/androidx/media/issues/557#issuecomment-1661772844

we implemented it using the main branch using this code and the files that were provided by the user who had asked the question here, 

code
https://github.com/androidx/media/issues/557#issuecomment-1671081176

files
https://github.com/androidx/media/issues/557#issuecomment-1670276144

however it created blank video with duration of audio with only audio from the music file playing in the background

the question that we want to know is

1) can we overlay audio over video which already contains audio using transformer(is it supported,) not remove the audio of the video and replace it 

2) other modifications, like adding audio at specific duration like video is 45 seconds long and overlay audio over the video from 15th second to 40 th second , looping audio  etc is supported

**Comment by droid-girl** [comment]
@pawaom: here are some answers regarding your questions in the previous comment:

1. can we overlay audio over video which already contains audio using transformer(is it supported,) not remove the audio of the video and replace it: 
Yes you can. You can create 2 sequences: the first one with video (containing an audio track) and the second one with background audio, add those sequences into a composition.
2. other modifications: It is currently not supported to add audio at a particular time as mentioned in issue [598](https://github.com/androidx/media/issues/598). It is only supported to add audio at the beginning of a composition. It is also possible to add a 10 second audio and set  [isLooping](https://github.com/androidx/media/blob/5328d6464acb077a7e8cba61b8cac1973c4943d7/libraries/transformer/src/main/java/androidx/media3/transformer/EditedMediaItemSequence.java#L65) to true. In this case, the background audio track will start at the beginning of the video and keep looping over 10 second interval for a duration of a video.

Please share your sample code if possible and output file, if you still experience issues.
Please keep in mind that this codebase is rapidly developing and some of the previous answers might not be applicable anymore.

**Comment by pawaom** [comment]
> 2. other modifications: It is currently not supported to add audio at a particular time as mentioned in issue [598]

will this be considered as an enhancement so we can track the development of this feature

Also since this is not supported is there a way to create silent audio using transformer like this Library based on media codec and media muxer

https://github.com/natario1/Transcoder

https://github.com/natario1/Transcoder/issues/51

**Comment by droid-girl** [comment]
The issue number [598](https://github.com/androidx/media/issues/598) has now an `enhancement` label, so you should be able to track the progress there. 
It is not supported to have a silent audio so you can use it as a gap item.
