### ISSUE TITLE
Equivalent to the MediaSessionConnector.setMediaMetadataProvider

### ISSUE THREAD

**Issue by ChernyshovYuriy** [androidx/media#615]
ExoPlayer has [MediaSessionConnector](https://github.com/google/ExoPlayer/blob/release-v2/extensions/mediasession/src/main/java/com/google/android/exoplayer2/ext/mediasession/MediaSessionConnector.java) class with a method `void setMediaMetadataProvider(@Nullable MediaMetadataProvider mediaMetadataProvider)`.
This is a good way to update metadata runtime in case of  live streaming, such as Radio Station streaming.
Moving to Media3, it is very hard to find it alternative.
The [guidelines](https://developer.android.com/guide/topics/media/media3/getting-started/migration-guide) mention `Remove the MediaSessionConnector and use the androidx.media3.session.MediaSession instead`, but particular class has no API to update metadata runtime.
Can you please help to find alternatives on `media3`?
Appreciate in advance.

**Comment by panzhiev** [comment]
Following up on the above question the same story with `setEnabledPlaybackActions()` method of `MediaSessionConnector`. Could someone help with this ?

**Comment by tonihei** [comment]
> void setMediaMetadataProvider(@Nullable MediaMetadataProvider mediaMetadataProvider)

With Media3, you can call `player.replaceMediaItem(..mediaItemWithUpdatedMetadata...)` (or `controller.replaceMediaItem`) to do this. This only works well with the upcoming 1.2.0 release though as a result of the improvements for #33.  You should be able to upgrade to 1.2.0-alpha01 to test this out. 

> setEnabledPlaybackActions

This can be done with configuring the available commands for the controllers. See https://developer.android.com/guide/topics/media/session/mediasession#commands

**Comment by WSteverink** [comment]
> > void setMediaMetadataProvider(@nullable MediaMetadataProvider mediaMetadataProvider)
> 
> With Media3, you can call `player.replaceMediaItem(..mediaItemWithUpdatedMetadata...)` (or `controller.replaceMediaItem`) to do this. This only works well with the upcoming 1.2.0 release though as a result of the improvements for #33. You should be able to upgrade to 1.2.0-alpha01 to test this out.
> 

I have just been testing this behaviour and it seems that the DefaultNotification only gets updated when using the ExoPlayer directly to replace the MediaItem. I want to make use of a Controller to update the MetaData. Any suggestions?
