### ISSUE TITLE
Widevine decode error

### ISSUE THREAD

**Issue by sridhard** [androidx/media#618]
### Version

ExoPlayer 2.19.1

### Devices that reproduce the issue

Realme, Android 13

### Devices that do not reproduce the issue

Samsung and others.
It is happening in few devices only

### Reproducible in the demo app?

Yes

### Reproduction steps

Just play the video encrypted with widevine

### Expected result

Video should play

### Actual result

Play fails with below exception

{"error":{"errorStackTrace":"com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(2, null, null, video/avc, avc1.42C01E, 489314, null, [640, 360, 24.0], [-1, -1]), format_supported=YES\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:575)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loopOnce(Looper.java:240)\n\tat android.os.Looper.loop(Looper.java:351)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\nCaused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: c2.mtk.avc.decoder.secure\n\tat com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1512)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:813)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)\n\t... 4 more\nCaused by: android.media.MediaCodec$CodecException: Error 0x80000000\n","errorCode":"24003","errorException":"MediaCodecVideoRenderer error, index=0, format=Format(2, null, null, video/avc, avc1.42C01E, 489314, null, [640, 360, 24.0], [-1, -1]), format_supported=YES","errorString":"ExoPlaybackException: ERROR_CODE_DECODING_FAILED"}}

### Media

Happens with any Widevine encrypted video

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by tonihei** [comment]
Could you share a full bugreport for this issue? And then send it to [android-media-github@google.com](mailto:android-media-github@google.com) with "Issue #618" in the subject and report back here. 

Assigning to @rrfrias for now given this looks like a device-specific DRM issue.

**Comment by rrfrias** [comment]
Is it possible to share a bugreport? If the exception is only retrieved from telemetry data, can you get WIdevine metrics data after a failure occurs. Use [MediaDrm.getPropertyByteArray](https://developer.android.com/reference/android/media/MediaDrm#getPropertyByteArray(java.lang.String))("metrics") . This returns a byte[] so you might need to convert it to a Base64 encoded string before you share with us (`Base64.getEncoder().encodeToString(bytes)`) .

**Comment by sridhard** [comment]
These kind of exceptions are happening in our customer mobiles. They are not willing to share bugreport. They are not developers and they dont know how to take bug reports. Even if we provide detailed steps they dont do it.

If we can capture anything programatically then it will be good. We can capture all data and report when the user report a ticket.

Can you tell me how can we capture the required data programatically?

**Comment by sridhard** [comment]
We got one bug report. Can ypu pls check @rrfrias 
[bugreport-RMX3741-SP1A.210812.016-2023-09-14-16-44-05-dumpstate_log-4847.txt](https://github.com/androidx/media/files/12611677/bugreport-RMX3741-SP1A.210812.016-2023-09-14-16-44-05-dumpstate_log-4847.txt)

**Comment by rrfrias** [comment]
@sridhard this is a dumpstate file but does not capture any logging or the failure. There is no information in the file that would aid an investigation.

**Comment by rrfrias** [comment]
@sridhard is it possible to make changes to the app to capture metrics data after a failure occurs? The API you need to call is mentioned [here](https://github.com/androidx/media/issues/618#issuecomment-1707753660). If you can share Base64 encoded data with us, we can analyze furthur.
