### ISSUE TITLE
STATE_ENDED not sent for very short files

### ISSUE THREAD

**Issue by TheMelody** [androidx/media#622]
I tried the latest **1.1.1** and **1.2.0-alpha01**, but still have this problem：
[https://github.com/androidx/media/issues/538](https://github.com/androidx/media/issues/538)

**Comment by icbaker** [comment]
I'm unable to reproduce this with media3 1.1.1 and the media provided in https://github.com/androidx/media/issues/538, so this doesn't look like exactly the same issue.

Please provide media we can use to reproduce the issue in the demo app. Please either upload it here or send to android-media-github@google.com using the subject `Issue #622`. Please also update this issue to indicate you’ve done this.
