### ISSUE TITLE
Widevine Video fail to play

### ISSUE THREAD

**Issue by sridhard** [androidx/media#623]
### Version

ExoPlayer 2.19.1

### Devices that reproduce the issue

Samsung SM-A037F

### Devices that do not reproduce the issue

Xiaomi, oppo, oneplus, samsung (Other modes) etc

### Reproducible in the demo app?

Yes

### Reproduction steps

Play widevine encrypted video

### Expected result

Video should play

### Actual result

Video does not play and gives the below exception:

error":{"errorStackTrace":"com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(3, null, null, video/avc, avc1.42C01E, 389754, null, [1004, 540, 25.0], [-1, -1]), format_supported=YES\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:575)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loopOnce(Looper.java:226)\n\tat android.os.Looper.loop(Looper.java:313)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\nCaused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: c2.mtk.avc.decoder.secure, Format(3, null, null, video/avc, avc1.42C01E, 389754, null, [1004, 540, 25.0], [-1, -1])\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1017)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:546)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1437)\n\tat com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:799)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:950)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)\n\t... 4 more\nCaused by: android.media.MediaCodec$CodecException: start failed\n\tat android.media.MediaCodec.native_start(Native Method)\n\tat android.media.MediaCodec.start(MediaCodec.java:2322)\n\tat com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.initialize(AsynchronousMediaCodecAdapter.java:171)\n\tat com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.access$100(AsynchronousMediaCodecAdapter.java:50)\n\tat com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:111)\n\tat com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:128)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1095)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1006)\n\t... 11 more\n","errorCode":"24001","errorException":"MediaCodecVideoRenderer error, index=0, format=Format(3, null, null, video/avc, avc1.42C01E, 389754, null, [1004, 540, 25.0], [-1, -1]), format_supported=YES","errorString":"ExoPlaybackException: ERROR_CODE_DECODER_INIT_FAILED"}}

### Media

Happens for any widevine encrypted video

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by tonihei** [comment]
Could you share a full bugreport for this issue? And then send it to [android-media-github@google.com](mailto:android-media-github@google.com) with "Issue #623" in the subject and report back here. 

Assigning to @rrfrias for now given this looks like a device-specific DRM issue.

**Comment by rrfrias** [comment]
Is it possible to share a bugreport? If the exception is only retrieved from telemetry data, can you get WIdevine metrics data after a failure occurs. Use [MediaDrm.getPropertyByteArray](https://developer.android.com/reference/android/media/MediaDrm#getPropertyByteArray(java.lang.String))("metrics") . This returns a byte[] so you might need to convert it to a Base64 encoded string before you share with us (`Base64.getEncoder().encodeToString(bytes)`) .

**Comment by sridhard** [comment]
[bugreport-RMX3741-SP1A.210812.016-2023-09-14-16-44-05-dumpstate_log-4847.txt](https://github.com/androidx/media/files/12608199/bugreport-RMX3741-SP1A.210812.016-2023-09-14-16-44-05-dumpstate_log-4847.txt)

**Comment by sridhard** [comment]
@rrfrias we got one bug report. This issue happening for multiple users
