### ISSUE TITLE
Transformer - How to add fade in or fade out to audio and video?

### ISSUE THREAD

**Issue by pawaom** [androidx/media#624]
How can we add Fade in Fade out audio to video

Changing volume of audio is supported by this library , but how can we add Fade in Fade out audio effect,

**Comment by pawaom** [comment]
export the video using transformer, 

I have referred to this 

https://github.com/androidx/media/issues/388

and 

https://github.com/androidx/media/issues/411

**Comment by Samrobbo** [comment]
To support fade in and fade out:

On the audio side, you will need a custom [`AudioProcessor`](https://github.com/androidx/media/blob/release/libraries/common/src/main/java/androidx/media3/common/audio/AudioProcessor.java) implementation. Within the processor you will need to keep track of the amount of data that has been queued to know when to start the fade.

For supporting on the video side, @dway123 may be able to advise.  [`RgbMatrix`](https://github.com/androidx/media/blob/release/libraries/effect/src/main/java/androidx/media3/effect/RgbMatrix.java) `GlEffect` may be a place to start.

**Comment by dway123** [comment]
To fade a video in or out, we don't currently support this. You can implement a custom `GlEffect`, that implements something like [`AlphaScale`](https://source.corp.google.com/piper///depot/google3/third_party/java_src/android_libs/media/libraries/effect/src/main/java/androidx/media3/effect/AlphaScale.java) (and [`AlphaScaleShaderProgram`](https://source.corp.google.com/piper///depot/google3/third_party/java_src/android_libs/media/libraries/effect/src/main/java/androidx/media3/effect/AlphaScaleShaderProgram.java), but with a different alpha value for different timestamps.

We hope to support some sort of crossfade in the future though, but I'm not sure when this will be completed.
