### ISSUE TITLE
An alternative to the setMediaSources API in the Exoplayer in the new media3 API

### ISSUE THREAD

**Issue by abdurahmanadilovic** [androidx/media#634]
I used to set manually different sources for different items in the Exoplayer by calling `setMediaSources` on the Exoplayer instance, to support offline playing since some episodes are downloaded and some are not. I had two different data source factories, one for online playing that is a simple CachedDataSource and an offline data source that is also CachedDataSource but it never expired, something like this: 

```
 val dataSourceFactory =
            CacheDataSource
                .Factory()
                .setCache(get(named("downloads-cache")))
                .setUpstreamDataSourceFactory(get<DefaultHttpDataSource.Factory>())
                .setCacheWriteDataSinkFactory(null)
        dataSourceFactory
```

What is the equivalent of this in the media3 API? Also, episodes can be downloaded while they are in the queue, so potentially it would be ideal to switch data sources just before the episode begins to play

**Comment by marcbaechinger** [comment]
Why do you need to handle these differently? When the cache finds the data cached on the device it will deliver it from there. If the episode isn't downloaded then it delegates to the upstream data source.  Can't this be solved with the very same `DataSource`?

If you really need to handle this differently, then you can inject your own `MediaSourceFactory`. See #606 for a code sample.

> episodes can be downloaded while they are in the queue, so potentially it would be ideal to
> switch data sources just before the episode begins to play

I don't think there is a way to swap out the data source dynamically. Like I said above. I think you can just handle them the same and if it's not downloaded the `CacheDataSource` will delegate to upstream. CAn you elaborate a bit on why this isn't possible for your use case?

**Comment by abdurahmanadilovic** [comment]
perfect, I'll try that
