### ISSUE TITLE
Apple Music app crashes when requesting the SESSION_COMMAND_REQUEST_SESSION3_TOKEN command

### ISSUE THREAD

**Issue by h6ah4i** [androidx/media#636]
### Version
Media3 1.1.1

### More version details
n/a

### Devices that reproduce the issue

* Emulator running Android 13
* Pixel 7a running Android 13

* **Apple Music app version: 4.2.0 (1286)**

### Devices that do not reproduce the issue
n/a

### Reproducible in the demo app?
No

### Reproduction steps

1. Install [Apple Music](https://play.google.com/store/apps/details?id=com.apple.android.music) app.  (This app needs sign-in and subscription to use, but they are not required to reproduce this issue)
2. Launch Apple Music app.
3. Create a SessionController with a media session that is associated with the Apple Music app (*)
4. Apple Music crashes and an error message appears on logcat.

(*) Sorry, I have not created a minimal sample project to reproduce it yet.

### Expected result

Apple Music app should not crash and can be controlled through SessionController.

### Actual result

Apple Music crashes with the following error message log.

```
FATAL EXCEPTION: MediaPlaybackService:Handler
Process: com.apple.android.music, PID: 6218
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Bundle.setClassLoader(java.lang.ClassLoader)' on a null object reference
	at a9.q0.d(MusicApp:1)
	at android.support.v4.media.session.MediaSessionCompat$a$b.onCommand(MusicApp:39)
	at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1590)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

### Media
n/a

### Bug Report
* [ ]  You will email the zip file produced by `adb bugreport` to [android-media-github@google.com](mailto:android-media-github@google.com) after filing this issue.

-----

## Additional info

I believe this is not a media3 side bug, but Apple Music side bug. However, this can be avoided with a small code change on media3 side as far as I know...

The current implementation of Apple Music app seems [the extras (`Bundle` instance) parameter of custom command handler](https://developer.android.com/reference/android/support/v4/media/session/MediaSessionCompat.Callback#onCustomAction(java.lang.String,android.os.Bundle)) is always not-null.

However, media3 [sends its custom action `SESSION_COMMAND_REQUEST_SESSION3_TOKEN` without the extras Bundle argument](https://github.com/androidx/media/blob/3f366109b7e5cbf7b7e5b46e8b923e167e9ae893/libraries/session/src/main/java/androidx/media3/session/SessionToken.java#L344). I have made a small code change that media3 not to send null, and it seems work and Apple Music stopped crashing.

```diff
    controller.sendCommand(
        MediaConstants.SESSION_COMMAND_REQUEST_SESSION3_TOKEN,
-        /* params= */ null,
+        /* params= */ Bundle.EMPTY,
        new ResultReceiver(handler) {
          @Override
          protected void onReceiveResult(int resultCode, Bundle resultData) {
            // Remove timeout callback.
            handler.removeCallbacksAndMessages(null);
            try {
              future.set(SessionToken.CREATOR.fromBundle(resultData));
            } catch (RuntimeException e) {
              // Fallback to a legacy token if we receive an unexpected result, e.g. a legacy
              // session acknowledging commands by a success callback.
              createFallbackLegacyToken.run();
            }
          }
        });
```

**Comment by marcbaechinger** [comment]
Closing this as we don't need further changes to work around invalid app behavior. See comment above.
