### ISSUE TITLE
Is it possible to have some global download requirements but skip them for a particular download?

### ISSUE THREAD

**Issue by kelmer44** [androidx/media#637]
Our app has a configurable setting to download only if not on a metered network. However if you are indeed in a metered network you can request to download anyway for a particular download. So if you're on 4G and click on download, you get a dialog asking whether to actually start the download considering that you are on metered network. 

The naive approach is to just change requirements but the user might have more queued downloads that should not be downloaded over metered network. So the idea is to bypass the requirement on this particular piece of content.

**Comment by tianyif** [comment]
Hi @kelmer44,

Thanks for the question! We have an existing opening enhancement https://github.com/google/ExoPlayer/issues/9819 which requests the similar. The potential fix is not trivial I'm afraid, we will be tracking this request internally and planning it in the near future.
