### ISSUE TITLE
Can't play the hls url

### ISSUE THREAD

**Issue by FongMi** [androidx/media#641]
### Version

Media3 1.1.1

### More version details

This url can't play by media3
But potplayer can play
https://prd-vcache.edge-global.akamai.tvb.com/v5/newsbks/_definst_/smil:news/inews1/20230906/archive_26_752814_1280_720_1500k_cht_proenv_can.smil/playlist.m3u8?hdnea=ip=0.0.0.0~st=1694068426~exp=1694154826~acl=/v5/newsbks/_definst_/smil:news/inews1/20230906/archive_26_752814_1280_720_1500k_cht_proenv_can.smil/*~hmac=3fdb46813e7776f763eb008f3b7ceaaab83a992d9b42491f4a8fad99bd679129

[sample.zip](https://github.com/androidx/media/files/12546470/sample.zip)

### Devices that reproduce the issue

Xiaomi 13

### Reproducible in the demo app?

Yes

### Reproduction steps

Play the attached media in the demo app

### Expected result

can play

### Actual result

failed

### Media

https://prd-vcache.edge-global.akamai.tvb.com/v5/newsbks/_definst_/smil:news/inews1/20230906/archive_26_752814_1280_720_1500k_cht_proenv_can.smil/playlist.m3u8?hdnea=ip=0.0.0.0~st=1694068426~exp=1694154826~acl=/v5/newsbks/_definst_/smil:news/inews1/20230906/archive_26_752814_1280_720_1500k_cht_proenv_can.smil/*~hmac=3fdb46813e7776f763eb008f3b7ceaaab83a992d9b42491f4a8fad99bd679129

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by FongMi** [comment]
![image](https://github.com/androidx/media/assets/3471963/0f410a78-c5a2-4d6f-ae09-ee6aea0932be)

**Comment by icbaker** [comment]
I tried to reproduce this but I get a 403 HTTP error instead. Please make the content available without authentication failures and we can take another look.

**Comment by FongMi** [comment]
I have download it
[sample.zip](https://github.com/androidx/media/files/12552191/sample.zip)

**Comment by icbaker** [comment]
I tried VPNing to Taiwan: Still see 403 errors.

I tried using the files provided, but the stream is incomplete, and when I ask ExoPlayer to play the playlist.m3u8 file it tries to load `chunklist_b1404000_ao_slCantonese_t64Q2FudG9uZXNl.m3u8` which is not present.

**Comment by FongMi** [comment]
Thanks for your test.
