### ISSUE TITLE
Update IMA SDK to 3.31.0, apps targeting API 34 could crash on Android 14 devices

### ISSUE THREAD

**Issue by alarochelle** [androidx/media#642]
### Version

Media3 1.1.1

### Devices that reproduce the issue

All devices running Android 14 on apps targeting API 34

### Devices that do not reproduce the issue

All devices running Android 14 on apps targeting API 33 or less

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Play any media with ads using the IMA SDK on an app targeting API 34
2. The app will crash 
![image](https://github.com/androidx/media/assets/22030235/45bc0624-0bff-4bfb-b29a-2aa979d885bd)

See also https://groups.google.com/g/ima-sdk/c/XCrb5a5WiYI?pli=1

### Expected result

The app does not crash

### Actual result

The app crashes because the IMA SDK is not >=3.31.0 which fixes this crash on apps targeting API 34.

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by alarochelle** [comment]
After testing in the Media3 demo, can confirm that this is no longer the case with IMA SDK `3.30.3` which is the version currently used in Media3 `1.1.0`.. I'll close this.

**Comment by icbaker** [comment]
You can also upgrade the version that your app uses at runtime using Gradle constraints, you generally don't need to wait for us to release a new version of media3 that depends on the later version (unless there are binary incompatibilities between the versions): https://docs.gradle.org/current/userguide/dependency_constraints.html
