### ISSUE TITLE
Make DefaultMediaNotificationProvider more customizable

### ISSUE THREAD

**Issue by tzugen** [androidx/media#65]
I want to customize the smallIcon as well as the `setShowActionsInCompactView()`.
Unfortunately I can't extend the DefaultMediaNotificationProvider because it is marked private in the package.

So the only solution I found was to copy the code from DefaultMediaNotificationProvider.java to my project and then change it there.

But that is not very nice, and if upstream it is changed, we won't get the changes.

**Comment by marcbaechinger** [comment]
Closing as this is fixed and will be included in `1.0.0-beta01` which is on its way to be released.
