### ISSUE TITLE
How can we create a Picture   and Picture effect using Transformer

### ISSUE THREAD

**Issue by pawaom** [androidx/media#655]
How can we create a Picture   and Picture effect using Transformer

I have checked this question using image as background of video  

https://github.com/androidx/media/issues/579

However we want have a video placed over video similar to the effect discussed in that question 

Can this be achieved using Transformer and how can we manage the audio of both or multiple videos

**Comment by dway123** [comment]
We're actively working on achieving this by adding a [video compositor](https://github.com/androidx/media/blob/main/libraries/effect/src/main/java/androidx/media3/effect/DefaultVideoCompositor.java), but this isn't fully integrated into Transformer yet. I expect this to be available before the end of this year.

**Comment by pawaom** [comment]
I forgot to ask it earlier , can we see the preview in the player as well, also will there be an option to place the overlay video at any desired position on the screen, also how can we manage the duration when we can display the overlay video, for example we have a 50 second long background video and an overlay video of 15 seconds long which we ay want to show from the 20th second of original video to the 35th second video can this also be achieved, will it support multiple overlay videos and how will the OpenGL shaders effects work with these videos

**Comment by dway123** [comment]
For what it's worth, I think my answers here may be less useful for now, until this feature is fully integrated/launched, as I can't provide code links for now to show how you might achieve the features you're asking for in these questions.

> can we see the preview in the player as well

This is something we're working on but might take some more time after we finish supporting preview for export

> will there be an option to place the overlay video at any desired position on the screen

Yes, this will be supported.

> how can we manage the duration when we can display the overlay video, for example we have a 50 second long background video and an overlay video of 15 seconds long which we ay want to show from the 20th second of original video to the 35th second video can this also be achieved

There will be a settings object that allows you to manage this by setting a frame's location and alpha, based on its timestamp and inputId

> will it support multiple overlay videos

Yes

> how will the OpenGL shaders effects work with these videos

You will be able to apply effects either to the input video frames either before they're composited (to each individual video), or later to the one output video stream's frames after they're composited
