### ISSUE TITLE
Get access to public functions in MediaDrm that are not exposed to ExoMediaDrm

### ISSUE THREAD

**Issue by shanujshekhar** [androidx/media#659]
Hey,
I'm trying to understand how does one use a function from APIs in `MediaDrm` that are not part of `ExoMediaDrm` .
- This is in regards to [MediaDrm#removeOfflineLicense](https://developer.android.com/reference/android/media/MediaDrm#removeOfflineLicense(byte[])) API that does not exist in ExoMediaDrm for our APIs to consume.

**Comment by icbaker** [comment]
Would it make sense to add a method like `OfflineLicenseHelper.removeLicense(byte[])`? In general I would expect most apps to use `OfflineLicenseHelper` for managing downloaded licenses, rather than directly interacting with an `ExoMediaDrm` instance. If you're using `ExoMediaDrm` directly, could you add a bit of detail about exactlly what your setup looks like?

(this may in turn require adding a similar method to `ExoMediaDrm` as part of the implementation, but I just want to make sure we're working downwards from the API requirements rather than upwards from the API offered by the platform `MediaDrm` class)

**Comment by shanujshekhar** [comment]
Yes, it would help adding `OfflineLicenseHelper.removeLicense(byte[])` in OfflineLicenseHelper but it would also be helpful if we have `removeOfflineLicenses` in `ExoMediaDrm` too so that we can leverage that API incase we already have access to `ExoMediaDrm`.

The setup for our `ExoMediaDrm` is that we are offering the custom `ExoMediaDrm` using [DefaultDrmSessionManager.Builderl#setUuidAndExoMediaDrmProvider](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/drm/DefaultDrmSessionManager.Builder.html#setUuidAndExoMediaDrmProvider(java.util.UUID,com.google.android.exoplayer2.drm.ExoMediaDrm.Provider)) in the `DefaultDrmSessionManager` which the `OfflineLicenseHelper` uses.

On a side note, I was also looking at this API to get offline licenses IDs ([MediaDrm#getOfflineLicenseKeySetIds()](https://developer.android.com/reference/android/media/MediaDrm#getOfflineLicenseKeySetIds())) which would be helpful for our use case. This API is also not available in `ExoMediaDrm` or `OfflineLicenseHelper`, so it would be really helpful if we can have access to it also

**Comment by shanujshekhar** [comment]
We use Widevine L1 and alternate Widevine integration and we would like to have the functionality of removing offline licenses for both integration. 

We use `OfflineLicenseHelper` to download license for L1 and we don't interact with `ExoMediaDrm` directly.
But for the alternate Widevine integration, we directly depend on `ExoMediaDrm` APIs to override and call `CDM Native` APIs

**Comment by shanujshekhar** [comment]
Based on our offline discussion with @icbaker, created created a PR https://github.com/shanujshekhar/media/pull/1 that adds the functionality that we would like to have in ExoMediaDrm.

However, I do have a follow-up question on the offline licenses stored on the device. On launch of our app, I see 255 offline licenses using [MediaDrm#getOfflineLicenseKeySetIds()](https://developer.android.com/reference/android/media/MediaDrm#getOfflineLicenseKeySetIds()), do all these licenses refer to our app or could they be associated with other apps on device too that uses MediaDrm.

Please let me know if you need anything else from my side.

**Comment by icbaker** [comment]
> However, I do have a follow-up question on the offline licenses stored on the device. On launch of our app, I see 255 offline licenses using [MediaDrm#getOfflineLicenseKeySetIds()](https://developer.android.com/reference/android/media/MediaDrm#getOfflineLicenseKeySetIds()), do all these licenses refer to our app or could they be associated with other apps on device too that uses MediaDrm.

@rrfrias PTAL at this part

**Comment by rrfrias** [comment]
> On launch of our app, I see 255 offline licenses using [MediaDrm#getOfflineLicenseKeySetIds()](https://developer.android.com/reference/android/media/MediaDrm#getOfflineLicenseKeySetIds()), do all these licenses refer to our app or could they be associated with other apps on device too that uses MediaDrm.

This is a bug in MediaDrm code. Right now, all offline licenses are displayed but this will be corrected in an upcoming release.

**Comment by icbaker** [comment]
https://github.com/androidx/media/pull/675 is merged
