### ISSUE TITLE
Notification disappear

### ISSUE THREAD

**Issue by BoikoIlya** [androidx/media#661]
### Version

Media3 1.0.0

### More version details

After about hour of background listening the notification disappear, but music is playing, if i remove app from task manager music stop

### Devices that reproduce the issue

Samsung m32  android 13

### Devices that do not reproduce the issue

samsung a70 android 11 dont face with this problem 

### Reproducible in the demo app?

Yes

### Reproduction steps

listen music in background about hour

### Expected result

notification shouldn`t disappear

### Actual result

.

### Media

.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by rohitjoins** [comment]
Thanks for reporting the issue.

I recommend adding an `EventLogger` and reproducing the issue. Once the issue occurs, please upload the file produced by `adb bugreport`. This will allow us to identify the root cause of the problem.

**Comment by BoikoIlya** [comment]
> Thanks for reporting the issue.
> 
> I recommend adding an `EventLogger` and reproducing the issue. Once the issue occurs, please upload the file produced by `adb bugreport`. This will allow us to identify the root cause of the problem.

You need whole this zip file called dumpstate, 33mb ?

**Comment by rohitjoins** [comment]
Yes, you can zip and email us the file on [android-media-github@google.com](mailto:android-media-github@google.com).
