### ISSUE TITLE
[Request] Update IMA SDK to the latest version

### ISSUE THREAD

**Issue by devno44** [androidx/media#665]
Regarding the issue bellow, please update IMA SDK to the latest version. This is a very serious bug and needs to be fixed urgently. Otherwise there will be problems updating target SDK to version 34.
https://groups.google.com/g/ima-sdk/c/XCrb5a5WiYI

Thank you !

**Comment by rohitjoins** [comment]
Hi @devno44,

We have [bumped](https://github.com/androidx/media/commit/b4d03a95154dbc688570217d5f67c97946a3c469) the version of IMA SDK. This will be released in our upcoming release.

Btw, you don't need to wait for a media3 release and can bump the version locally. Please see https://docs.gradle.org/current/userguide/dependency_constraints.html.
