### ISSUE TITLE
Download Tracks From An HLS Stream And Play Offline

### ISSUE THREAD

**Issue by mylesandre1124** [androidx/media#670]
I'm having an issue where I will download an HLS stream and select tracks (720p and subtitles) with the DefaultTrackSelector for offline play. There wasn't a issue when using Exoplayer version 2.18.5. In fact, when downloading a video with Media3 version 1.1.1, the video will play when downgrading back to Exoplayer 2.18.5. In version 1.1.1, I found that the video would play if `downloadHelper.clearTrackSelections(periodIndex)` was commented out, however, all track selections would be downloaded which isn't what we want. The download and track selection code is the exact same between 2.18.5 and 1.1.1 but 1.1.1 refuses to play.

After downloading the video, turning off wifi and attempting to play it, I get a connection error. I verified that the stream keys when downloading the video are the same as when I would attempt to play the video offline. I did notice that when not clearing the track selections, a "0.0.0" stream key would be included and the video would play; when clearing the track selections, "0.0.0" would not be in the stream keys list and the video would not play. I'm not sure the significance as to why a "0.0.0" key would matter to playback and I'm trying to figure out what I should do to get the video to play. 

        for (periodIndex in 0 until downloadHelper.periodCount) {
            downloadHelper.clearTrackSelections(periodIndex)
            downloadHelper.addTrackSelection(periodIndex, builder.build())
        }

I set the MediaSource and DataSource Factories according to the documentation:
 

    val mediaSourceFactory = DefaultMediaSourceFactory(context)
        .setDataSourceFactory(cacheDataSourceFactory)

    val builder = ExoPlayer.Builder(
        this,
        renderersFactory!!
    )
    builder
        .setTrackSelector(trackSelector)
        .setMediaSourceFactory(mediaSourceFactory)
        .setLoadControl(loadControl)

    player = builder.build()

The error:

```
internalError [eventTime=95.53, mediaPos=0.00, window=0, loadError                                                                                                      
  androidx.media3.datasource.cronet.CronetDataSource$OpenException: iq: Exception in CronetUrlRequest: net::ERR_PROXY_CONNECTION_FAILED, ErrorCode=11, InternalErrorCode=-130, Retryable=false
   at androidx.media3.datasource.cronet.CronetDataSource.open(CronetDataSource.java:581)
   at androidx.media3.datasource.DefaultDataSource.open(DefaultDataSource.java:272)
   at androidx.media3.datasource.cache.CacheDataSource.openNextSource(CacheDataSource.java:798)
   at androidx.media3.datasource.cache.CacheDataSource.open(CacheDataSource.java:611)
   at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
   at androidx.media3.datasource.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
   at androidx.media3.datasource.DataSourceInputStream.open(DataSourceInputStream.java:64)
   at androidx.media3.exoplayer.upstream.ParsingLoadable.load(ParsingLoadable.java:180)
   at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:414)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
   at java.lang.Thread.run(Thread.java:1012)
Caused by: iq: Exception in CronetUrlRequest: net::ERR_PROXY_CONNECTION_FAILED, ErrorCode=11, InternalErrorCode=-130, Retryable=false
   at org.chromium.net.impl.CronetUrlRequest.onError(:com.google.android.gms.dynamite_cronetdynamite@231818044@23.18.18 (190400-0):5)
```

Be aware that I am proxying the app here but an attempt to call out to the internet is still made when not proxying

**Comment by marcbaechinger** [comment]
> androidx.media3.exoplayer.upstream.ParsingLoadable.load(ParsingLoadable.java:180)

Given the exception is thrown by a `ParsingLoadable` I think to mean this is a request for an HLS playlist rather than for media. 

Can you repro this with your media in the main demo app when [add the link to the HLS stream in the demo app](https://developer.android.com/guide/topics/media/exoplayer/demo-application#1-editing)? Is it specific to your stream? When trying a random HLS stream in the demo app this works well for me in flight mode.

If you can repro with the demo app, can you provide us with a URL to the media and provide some repro steps and observations, so we can check ourselves?

**Comment by mylesandre1124** [comment]
After looking into the demo app, I found that stream keys weren't being added to the MediaItem when being set to the controller. Before, in normal ExoPlayer, we would rely on retrieving the cached media item from the `DownloadManager` and `HlsMediaSource.Factory::createMediaSource` and then call `setMediaSource` on the player but with the addition of the controller, it was necessary to set the stream keys when calling `setMediaItem` on it.

Thanks for the help

**Comment by marcbaechinger** [comment]
Nice find! Thanks for the update!
