### ISSUE TITLE
Send CustomData with MediaItem to Cast Receiver

### ISSUE THREAD

**Issue by JonWatson** [androidx/media#690]
We are attempting a `CastPlayer` Sender implementation.  We use `CastPlayer.setMediaItem()` to set the `MediaItem` for playback. 

We would like to send an Authentication Token(String) along with the Content ID so that the Cast Receiver can make an authenticated API call to retrieve the necessary data for playback.

What would be the appropriate way of sending a "sensitive" String like this to the Cast Receiver?  Can it be done by using the `MediaItem.Builder`?  

In the non-CastPlayer version, where you interact with the `RemoteMediaClient` directly for loading, we used to be able to send `customData` via `MediaLoadOptions` passed to the `load()` command.  But I cannot find an analogous API/functionality in the `CastPlayer`.

**Comment by NikSatyr** [comment]
you'd likely need to create a custom implementation of `com.google.android.exoplayer2.ext.cast.MediaItemConverter` (its media3 counterpart to be exact), and tune its `toMediaQueueItem(mediaItem: MediaItem)` to something like this:

```
return MediaQueueItem.Builder(mediaInfo)
            .setCustomData(/* your token wrapped in JSONObject */)
            .build()
```

this MediaItemConverter should then be injected into `CastPlayer`'s constructor

**Comment by marcbaechinger** [comment]
> What would be the appropriate way of sending a "sensitive" String like this to the Cast Receiver?


I can't give you reliably information about how the Android Cast sender SDK sends data to a cast device I'm afraid. You would have to contact the Cast team to get such details of how this works.

Without relying on the SDK, I think the most secure approach would be that the Android app doesn't see this authentication string at all and it is not transmitted from the android app to the receiver app. 

Sounds like you have a custom receiver that receives this string and then uses it accordingly to connect with https. I wonder whether that should be implemented in the cast receiver app by using whatever DRM solutions are available there?

You can also encrypt the string in the Android app and then decrypt it again in the receiver app? Here again, I'm not the right person to consult you with this in detail.

**Comment by JonWatson** [comment]
Thank you both.  The `MediaItemConverter` was the bridge we needed.  This does indeed allow us to receive a `customData` in the Load Request on the Receiver
