### ISSUE TITLE
The exoplayer is in a paused state, the surface has been released. At this time, dequeue graphic buffer from surface failed, causing mediacodec to report 0x80000000 Error

### ISSUE THREAD

**Issue by captain81** [androidx/media#698]
### Version

ExoPlayer 2.15.1

### Devices that reproduce the issue

all devices

### Devices that do not reproduce the issue

no

### Reproducible in the demo app?

No

### Reproduction steps

1.The exoplayer is in a paused state
2.The surface has been released at this time. 
3.ExoPlayer will still dequeue input buffer and output buffer from modiacodec. At this time, dequeue graphic buffer from surface failed, causing mediacodec to report 0x80000000 Error

### Expected result

Normal playback

### Actual result

 dequeue graphic buffer from surface failed，playback error

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by microkatz** [comment]
@captain81 

It would be helpful to see a stack trace and logs. Would you be able to share a [bug report](https://developer.android.com/studio/debug/bug-report) taken while reproducing your issue? If you cannot send it publicly then please send it to android-media-github@google.com with the subject
`Issue #698`. Please also update this issue to indicate you've done this.

In addition, how are you "releasing" the surface. Are you just releasing the object and resources that ExoPlayer's renderers are using? Or are you calling one of the Player's methods such as clearTextureView, setVideoTextureView, setVideoSurfaceView, clearVideoSurfaceView, etc?

**Comment by microkatz** [comment]
@captain81 

I'm closing this issue as there has not been a response to my query. If you are continuing to hit this issue then please reopen but with the additional information asked for.

I think that if you call one of the Player methods for removing surfaces then you won't hit the issue you are reporting. Frames will just be successfully decoded and thrown out.
