### ISSUE TITLE
How to prevent Chromecast from hiding UI controls after couple of seconds of playing audio only

### ISSUE THREAD

**Issue by abdurahmanadilovic** [androidx/media#705]
I noticed when I cast to a Chromecast-enabled device with the Media3 setup, and I play only audio, Chromecast hides the UI controls after a couple of seconds, leaving a dark screen with just the app name in the middle. 

Is there a way to customize this?

**Comment by icbaker** [comment]
It sounds like you're referring to the UI behaviour on the chromecast itself? That's not directly controlled by ExoPlayer - it's the behaviour of the [default receiver](https://developers.google.com/cast/docs/web_receiver#default_media_web_receiver). Given that in that link it says the following, I suspect this isn't possible:

> you **cannot customize any of the UI** in the Default Media Web Receiver
