### ISSUE TITLE
java.lang.ArrayStoreException: java.lang.Object[] cannot be stored in an array of type com.oplus.tbl.exoplayer2.upstream.Allocation[] at clearAllocationNodes

### ISSUE THREAD

**Issue by captain81** [androidx/media#714]
### Version

ExoPlayer 2.14.0

### More version details

java.lang.ArrayStoreException: java.lang.Object[] cannot be stored in an array of type com.oplus.tbl.exoplayer2.upstream.Allocation[] at com.oplus.tbl.exoplayer2.source.SampleDataQueue.clearAllocationNodes(SampleDataQueue.java:4) at com.oplus.tbl.exoplayer2.source.SampleDataQueue.reset(SampleDataQueue.java:1) at com.oplus.tbl.exoplayer2.source.SampleQueue.reset(SampleQueue.java:2) at com.oplus.tbl.exoplayer2.source.SampleQueue.release(SampleQueue.java:1) at com.oplus.tbl.exoplayer2.source.ProgressiveMediaPeriod.onLoaderReleased(ProgressiveMediaPeriod.java:2) at com.oplus.tbl.exoplayer2.upstream.Loader$ReleaseTask.run(Loader.java:1) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) at java.lang.Thread.run(Thread.java:1012)

### Devices that reproduce the issue

All

### Devices that do not reproduce the issue

No

### Reproducible in the demo app?

Yes

### Reproduction steps

play video

### Expected result

No crash

### Actual result

crash

### Media

NO

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by tianyif** [comment]
Hi @captain81,

The implementation of the method `clearAllocationNodes` has changed since ExoPlayer 2.14.0 (eg. https://github.com/google/ExoPlayer/commit/c3b470f308487d28d132fa6e23be56c37e5ce91f), could you please upgrade the library version and see if this is still an issue?
