### ISSUE TITLE
It is easy to OOM

### ISSUE THREAD

**Issue by Ysj001** [androidx/media#715]
media3 version: 1.1.1

1. In default settings the `DefaultLoadControl#minBufferMs `  == 50 seconds
2. In `DefaultLoadControl#shouldContinueLoading` the minimum time is determined preferentially over the maximum memory size
3. In `Allocation`, byte arrays of java heap memory are used

![图片](https://github.com/androidx/media/assets/38207969/94619b9d-aabe-4c12-ac04-c854198add0d)

**Comment by tonihei** [comment]
If you are configuring `DefaultLoadControl` to prefer the `minBufferMs` over target memory size, then `DefaultLoadControl` will just follow your instructions and may cause OOM errors if `minBufferMs` is chosen too high. This is all working as expecting I believe. If you want to always enforce a maximum memory limit to avoid OOM errors, then you need to leave `prioritizeTimeOverSizeThresholds` at its default value of `false`.

**Comment by Ysj001** [comment]
Is it possible to replace the byte array in `Allocation` with a `ByteBuffer#allocateDirect` in a future version to avoid taking up too much java heap memory?
