### ISSUE TITLE
Video Player is Blank, but the Audio is playing

### ISSUE THREAD

**Issue by HakimBlaze10** [androidx/media#716]
### Version

Media3 1.1.1

### Devices that reproduce the issue

Realme X
OnePlus Nord CE 2 Lite

### Reproducible in the demo app?

Yes

### Reproduction steps

Play a video from an online source.
Play a video from the raw folder locally

### Expected result

The media plays successfully

### Actual result

Audio plays but the video player only shows blank screen.
Component used is PlayerControlView and ExoPlayer.
The PlayerControlView buttons also tend to disappear after 4 seconds.

### Media

https://befriendsapp.in/ar/video/itachi.mp4
raw > sample.mp4

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by tianyif** [comment]
Hi @HakimBlaze10,

I couldn't reproduce this issue with demo app on Pixel 4. So it is likely to be specific to the devices you mentioned, for example, the video codec is not supported by those devices. What did the log say when you reproduced?
