### ISSUE TITLE
How to implements video chapters like youtube in exoplayer

### ISSUE THREAD

**Issue by KothamireNarendra** [androidx/media#717]
How to implements video chapters like youtube in exoplayer, So I want to have UI like youtube, showing segmented timeline, also they have list images for those chapters with duration label and even they scroll as user drags on timeline 
eg
https://www.youtube.com/watch?v=pvkTC2xIbeY&ab_channel=YouTubeMarketingwithtubics

**Comment by icbaker** [comment]
This sounds like UI customization beyond that offered by our UI components, so you would need to build it yourself: https://developer.android.com/guide/topics/media/ui/playerview#customization

**Comment by KothamireNarendra** [comment]
K thanks for reply but, can you guide me, which API I could use that would give me required callbacks for given timeline segments
