### ISSUE TITLE
Playback gets stuck at the ad point when using IMA SDK to play movies with .srt format subtitles.

### ISSUE THREAD

**Issue by Hiwensen** [androidx/media#720]
### Version

ExoPlayer 2.19.1

### More version details

The issue also can be reproduced with ExoPlayer 2.18.5

### Devices that reproduce the issue

It can be reproduced on all my devices. Looks like it'snot a device-specific issue
* Pixel 2 running Android 11

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Adding the following sample to the `media.exolist.json` file
```
 {
        "name": "playback stuck with srt subtitle",
        "uri": "https://manifest.staging-public.tubi.io/6526b9fa-0c02-4a6d-9fff-4a8ef70dc4e8/de7zyvhkdb.m3u8?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjZG5fcHJlZml4IjoiaHR0cHM6Ly9ha2FtYWkudHViaS1zdGFnaW5nLnZpZGVvIiwiY291bnRyeSI6IlVTIiwiZGV2aWNlX2lkIjoiYmRkZDEwNGYtYjgxYS00ZmUwLTk4ZTgtNGI0ZDMyZWI3ODBiIiwiZXhwIjoxNjk3MjAwMjAwLCJwbGF0Zm9ybSI6IkFORFJPSUQiLCJ1c2VyX2lkIjo3Mzk3NDExfQ.vy4K8bpX_pOD5Pfc52pzrqLylejz9A9-m-CTNP9TMEM&manifest=true",
        "ad_tag_uri": "https://run.mocky.io/v3/d3c23db8-aaf8-43a4-9690-3398a0f0f10f",
        "subtitle_uri": "http://s.adrise.tv/d2b870dd-7374-45d5-9f13-f543bf61a991.srt",
        "subtitle_mime_type": "application/x-subrip",
        "subtitle_language": "en"
      }
```
2. Play the added sample video from the beginning. The ad points are 00:00:10s, 00:00:20s, 00:00:30s
3. Wait and play to the 20s without seeking.

### Expected result

Video, audio, and subtitles all play normally.

### Actual result

The video frame gets stuck, no audio, and the subtitles continue to play.
No error logs.
After fast-forwarding, this issue disappeared.

### Media

Not applicable.
Below are the URLs for testing.

Video URL:    
https://manifest.staging-public.tubi.io/6526b9fa-0c02-4a6d-9fff-4a8ef70dc4e8/de7zyvhkdb.m3u8?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjZG5fcHJlZml4IjoiaHR0cHM6Ly9ha2FtYWkudHViaS1zdGFnaW5nLnZpZGVvIiwiY291bnRyeSI6IlVTIiwiZGV2aWNlX2lkIjoiYmRkZDEwNGYtYjgxYS00ZmUwLTk4ZTgtNGI0ZDMyZWI3ODBiIiwiZXhwIjoxNjk3MjAwMjAwLCJwbGF0Zm9ybSI6IkFORFJPSUQiLCJ1c2VyX2lkIjo3Mzk3NDExfQ.vy4K8bpX_pOD5Pfc52pzrqLylejz9A9-m-CTNP9TMEM&manifest=true

Subtitle URL:
http://s.adrise.tv/d2b870dd-7374-45d5-9f13-f543bf61a991.srt

AdTag URL:
https://run.mocky.io/v3/d3c23db8-aaf8-43a4-9690-3398a0f0f10f

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by Hiwensen** [comment]
@icbaker 
Thank you for getting back to me.
I double-checked it can reproduce with the JSON snippet I proposed.
There is no issue with your JSON snippet.
The difference between the two JSONs is your ad_tag_uri returned ads(full midrolls), but mine have two empty midrolls. 

The critical points to reproduce the issue are:
* Playback to the second ad point without manually seeking 
* No ads at these two ad points(ad empty).

Let's say, the ad point is at the 10 seconds and the 20 seconds, and if no ads are returned at these two ad points, then the video frame will be stuck at the 20 seconds.

The demo app has `VMAP empty midroll` and `VMAP full, empty, full midrolls` samples, the JSON snippet I proposed is `VMAP empty, empty, empty midrolls` sample which can reproduce the issue.
<img width="461" alt="Screenshot 2023-10-12 at 16 09 44" src="https://github.com/androidx/media/assets/14145498/8e1a0f2c-9a7c-438e-a33a-669b458731f0">

I am not an IMA SDK user, and I don't know whether the IMA SDK supports the scenario I mentioned.

**Context**
I'm following this doc(https://developer.android.com/guide/topics/media/exoplayer/ad-insertion#client-using-third-party)
implementing a custom AdsLoader that wraps our ads SDK.
We use our own ad server to play real-time bidding ads. We will pre-set some ad points and only know whether ads are filled after requesting the ad server a few seconds before the ad points(sometimes the ad point was filled with ads, sometimes the ad points are empty), and meet this issue.
I found this issue can also be reproduced in the demo app with IMA SDK applying the same scenario, then raised this issue.

**Comment by Hiwensen** [comment]
Below is the video, it gets stuck at the 20th second and stops moving forward, while the subtitles and playback progress are still moving forward. After fast forward, the video playback returns to normal.

https://github.com/androidx/media/assets/14145498/f78f408f-c1cb-4fa7-a46e-c436f8601d5d

**Comment by icbaker** [comment]
Thanks, I can now repro with your original example (not sure what was different yesterday, sorry about that) - I will investigate.

I'm also able to repro with your IMA URI and our content (the MKV link I posted above).

I'm **not** able to repro with our `VMAP empty midroll` example.

I **am** able to repro with our `VMAP full, empty, full midrolls` example.

**Comment by icbaker** [comment]
I'm going to close this because the fix described above will soon become the default behavior, and it doesn't seem worth spending time to investigate a bug in the old code that will soon be unused/deleted.

**Comment by Hiwensen** [comment]
@icbaker [DefaultMediaSourceFactory.experimentalUseProgressiveMediaSourceForSubtitles()](https://developer.android.com/reference/androidx/media3/exoplayer/source/DefaultMediaSourceFactory#experimentalUseProgressiveMediaSourceForSubtitles(boolean)) fixed the issue, thanks so much!
