### ISSUE TITLE
1.2 alpha2 changelog missing change reference.

### ISSUE THREAD

**Issue by Tolriq** [androidx/media#721]
### Version

Media3 pre-release (alpha, beta or RC not in this list)

### Devices that reproduce the issue

1.2 alpha 2 / beta 1

Changelog does not mention https://github.com/androidx/media/commit/3cf9c08dca1b16a84195aa5d01e134a4ea07bee4  took me some time to find the commit and adapt.

### Reproducible in the demo app?

Yes

### Reproduction steps

Update to 1.2 alpha and previous code no more compile

### Expected result

Code compile or changes is mentioned in the changelog.

### Actual result

Does not compile

### Media

N/A

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by microkatz** [comment]
@Tolriq,

Thank you for reporting this issue! We are working to address adding it to be included in new revisions of the release notes. Once that is complete, we will add it to this changelog list, https://github.com/androidx/media/releases/tag/1.2.0-alpha02.

**Comment by microkatz** [comment]
The release notes have been updated in the main branch and https://github.com/androidx/media/releases/tag/1.2.0-alpha02 has been updated as well. Thank you for reporting this!
