### ISSUE TITLE
Preview rotate scale AspectRatio and other such effects in ExoPlayer

### ISSUE THREAD

**Issue by pawaom** [androidx/media#729]
I was reading the documentation 

[here ](https://developer.android.com/guide/topics/media/transformer/transformations)

And also found [this question ](https://github.com/androidx/media/issues/551)

We can manage trim, speed, volume and VideoEffects in preview , but how can we show transformations like  rotation , Scaling and Aspect Ratio 

I have used the demo app for Transformation and the  
 
`getDebugPreviewSurfaceView`  https://github.com/androidx/media/blob/3f366109b7e5cbf7b7e5b46e8b923e167e9ae893/demos/transformer/src/main/java/androidx/media3/demo/transformer/TransformerActivity.java#L806

does provide the Transformation preview, but can we control the playback process like the exoplayer it self like play or pause it and apply changes as we preview the video, similar to many video editor apps

**Comment by claincly** [comment]
Currently we do support setting video effects through `ExoPlayer.setVideoEffects()`, and you can use the same set of effects you used in `Transformer` there in ExoPlayer.

Note however, we don't currently support updating effects while paused. That is, if you pause and set a new effect, the new effect will not show on the paused frame, but it'll show after you resume playing. We know it's an issue and we are working on it.

Please take a try and see how it goes!

**Comment by pawaom** [comment]
we can manage to show these effects using GLSurfaceView , if ExoPlayer.setVideoEffects(), works , which is an implementation similar to GLES ,  I think it can be achieved easily but dont know how to use these with GLSurfaceView

**Comment by claincly** [comment]
You could just use a plain `SurfaceView` for this, ExoPlayer will handle the GL interactions. 

> you mentioned we don't currently support updating effects while paused does this work on exoplayer or getDebugPreviewSurfaceView

No, it won't work.
