### ISSUE TITLE
Allow showing bitmap or text overlay and other effects  for specific duration 

### ISSUE THREAD

**Issue by pawaom** [androidx/media#731]
### [REQUIRED] Use case description
Allow showing bitmap or text overlay and other effects   for specific duration Say for example we have a 50 second long video and we want to show a bitmap or text overlay from 10th second to 20th second , this feature should be supported

This feature should be available for 
1) bitmap overlay 
2) Text overlay 
3) Video (PIP) overlay
4) Effects using OpenGL
5) Music overlay

### Proposed solution
Similar muxer solutions are already available

1) https://github.com/linkedin/LiTr
2) https://github.com/natario1/Transcoder
3) The google Youtube Create app  already provides such solutions
https://play.google.com/store/search?q=youtube%20create&c=apps

### Alternatives considered
the above mentioned muxer can be used but inbuild solution will be helpful .

This  missing features limit the option to develop a better video editor app compared to existing competition.

**Comment by droid-girl** [comment]
Thank you for the request. These features are on our roadmap. Please follow this issue for more updates.

**Comment by pawaom** [comment]
A Time Frame of development  will be helpful , please include these important features at the earliest, after studying various codes on github it seems to be a muxer related issue 

these might be useful
https://www.sisik.eu/blog/android/media/mix-audio-into-video
https://www.sisik.eu/blog/android/media/add-text-to-video

specially handling duration etc

**Comment by droid-girl** [comment]
We are unable to share a specific deadline for this feature. We will provide you with a more specific timeline as soon as we can.

**Comment by pawaom** [comment]
I read the  
[OverlaySettings.java](https://github.com/androidx/media/blob/main/libraries/effect/src/main/java/androidx/media3/effect/OverlaySettings.java)

in the main branch compared to 1.1.1 release and it provides various options like  
useHdr
alphaScale
backgroundFrameAnchor
overlayFrameAnchor
scale
rotationDegrees

If they can add  further options to manage these changes with time  based on 
1) how much time (in terms of seconds ) we can use the rotation degrees or scale , alpha etc
2) based on background time at what time we start and end showing the overlay. 

It will be really helpful which can help us to show animations of the overlay with these features,
