### ISSUE TITLE
Can we get the current frame or current time stamp that is being processed by the Transformer 

### ISSUE THREAD

**Issue by pawaom** [androidx/media#737]
Can we get the current frame or current time stamp that is being processed by the Transformer 

We are trying to add watermark on video at specific time , can we get the current frame or timestamp that is being processed based on which we can show or hide the watermark for that specific duration.

**Comment by droid-girl** [comment]
Hi @pawaom,
You can try using [`TimestampWrapper`](https://github.com/androidx/media/blob/3f366109b7e5cbf7b7e5b46e8b923e167e9ae893/libraries/effect/src/main/java/androidx/media3/effect/TimestampWrapper.java#L31) effect. Here is a quick example:
```
GlEffect timeWrappedEffect = new TimeStampWrapper(glEffect, startTimeUs, endTimeUs)
```

The `TimestampWrapper` might also help to solve some of the requests from the issue [731](https://github.com/androidx/media/issues/731) like Bitmap and TextOverlay support. 
The `TimestampWrapper` has some limitations and will not work in combination with some other effects.

**Comment by pawaom** [comment]
thanks will give it a try and look if it is useful

**Comment by pawaom** [comment]
I doesnot work as expected 

I am trying following code 

 ```
public void TransformVideo() {
        ImmutableList.Builder<Effect> effects = new ImmutableList.Builder<>();
        try {

            GlEffect timeWrappedEffect = new TimestampWrapper(createOverlayEffect(), 1000, 10000);
          // effects.add((reateOverlayEffect(),));
            effects.add((timeWrappedEffect));
        } catch (PackageManager.NameNotFoundException e) {
            throw new RuntimeException(e);
        }
        try {
            outputPath = createOutputFile().getAbsolutePath();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        MediaItem inputMediaItem = new MediaItem.Builder().setUri(VideoUri).setClippingConfiguration(
                new MediaItem.ClippingConfiguration.Builder()
                        .setStartPositionMs(1000)
                        .setEndPositionMs(25000)

                        .build()).build();

        MediaItem audioMediaItem2 = new MediaItem.Builder().setUri(AudioUri).setClippingConfiguration(
                new MediaItem.ClippingConfiguration.Builder()
                        .setStartPositionMs(1000)
                        .setEndPositionMs(25000)
                        .build()).build();


        Transformer transformer =
                new Transformer.Builder(Own_Media_Transform.this)
                        .setTransformationRequest(
                                new TransformationRequest.Builder().build())
                        .addListener(transformerListener)
                        .build();



        EditedMediaItem.Builder editedMediaItemBuilder = new EditedMediaItem.Builder(inputMediaItem);
        EditedMediaItem.Builder editedMediaItemBuilder2 = new EditedMediaItem.Builder(audioMediaItem2);
        editedMediaItemBuilder.setEffects(new Effects(createAudioProcessorsFromBundle(), effects.build()));
        List<EditedMediaItem> editedMediaItems = new ArrayList<>();
        editedMediaItems.add(editedMediaItemBuilder.build());

        //  editedMediaItems.add(editedMediaItemBuilder2.build());

        List<EditedMediaItem> editedAudioMediaItems = new ArrayList<>();
        editedAudioMediaItems.add(editedMediaItemBuilder2.build());

        EditedMediaItemSequence VideoSequence = new EditedMediaItemSequence(editedMediaItems);
        EditedMediaItemSequence audioSequence = new EditedMediaItemSequence(
                editedAudioMediaItems, /* isLooping= */ false);


        Composition composition = new Composition.Builder(ImmutableList.of(VideoSequence, audioSequence))
                .build();


        transformer.start(composition, outputPath);
        ProgressHolder progressHolder = new ProgressHolder();
        mainHandler = new Handler(Looper.getMainLooper());
        mainHandler.post(
                new Runnable() {
                    @Override
                    public void run() {
                        if (transformer != null
                                && transformer.getProgress(progressHolder) != PROGRESS_STATE_NOT_STARTED) {
                            progressIndicator.setProgress(progressHolder.progress);
                            mainHandler.postDelayed(/* r= */ this, /* delayMillis= */ 500);
                        }
                    }
                });
    }
 ```

When we directly pass the `effects.add((reateOverlayEffect(),)); `it shows the logo

but when we use 

 ` GlEffect timeWrappedEffect = new TimestampWrapper(createOverlayEffect(), 1000, 10000);
            effects.add((timeWrappedEffect));`

The video is created but the logo is not shown

Also IF there is better documentation it will help in solving various issues, There have been lot of improvements from version 1.1.1 to 1.2.0 it will help developers

**Comment by andrewlewis** [comment]
`TimestampWrapper` takes start and end times in microseconds so this is passing 10 ms and 100 ms -- should those be multiplied by 1000 or is that not working either?

By the way, custom `GlShaderProgram`s and implementations of `BaseGlShaderProgram` receive the input frame presentation time in `queueInput` in case you want to write effects with time varying behavior without using `TimestampWrapper` (see also the [source](https://github.com/androidx/media/blob/main/libraries/effect/src/main/java/androidx/media3/effect/TimestampWrapperShaderProgram.java) for timestamp wrapper implementation for an example of using this).

Thanks for the feedback on documentation. This should get better over time. We are still making quite a lot of additions/changes/improvements and will have more time to invest in documentation as the APIs mature.

**Comment by pawaom** [comment]
@andrewlewis  thanks for the info, as you can see we used  
```
 
MediaItem.ClippingConfiguration.Builder()
                       .setStartPositionMs(1000)
                       .setEndPositionMs(25000)
                       .build()).build(); 
```

to trim the video and audio so the assumption was it should have worked in a similar way 

I will look in the `TimestampWrapper` `BaseGlShaderProgram ` etc  for further details 

My assumption is this should work for video overlay (Picture in picture) mode also  and other effects , hopefully this feature will work on audio overlay feature also

Again thanks for the info, Please provide documentation update at the earliest.
