### ISSUE TITLE
Activating and deactivating of ExoPlayer's AudioProcessor 

### ISSUE THREAD

**Issue by MrBzik** [androidx/media#739]
Hi. I am implementing AudioProcessor for a feature, that is not needed all the time. So I am not sure my audioProcessor should always be active. 
It seems that if I won't set it as active when configure() function is called internally (every time a new stream is being played), manually setting it afterwards for the playing stream won't take effect. getOutput() and queueInput() not called. 
Is there a way to do this?

```
    override fun configure(inputAudioFormat: AudioProcessor.AudioFormat): AudioProcessor.AudioFormat {

         ...

//        isActive = true

        return inputAudioFormat
    }
  
```

**Comment by tonihei** [comment]
You can do some manual reconfiguration if needed by overriding `AudioSink.configure`. See https://github.com/androidx/media/issues/418 where this has been discussed before. I'm not sure if that fully covers you feature request or not. 

Fully dynamic changes mid-playback are currently not supported (see also https://github.com/google/ExoPlayer/issues/10896 where this has been asked before).

Please let us know if there is another remaining question or if you would like to file a specific feature request that would be useful for your case.  (Assigning to @Samrobbo who knows a bit more about the processing pipelines and potential future plans)

**Comment by MrBzik** [comment]
Hi. I looked into discussion about audio sink. I am not sure what I should do with audio sink's configure if mid-playback manipulations are not supported. Or will it allow me to force reconfiguration any time, when media item is already playing (and activating audio processor, maybe also causing audio discontinuity)?

**Comment by tonihei** [comment]
No, the reconfiguration in the linked thread only works at item transitions, not at any time. If you need to make dynamic changes, I'd suggest to keep your processor running until the next configure call and simply return the input data without modification.
