### ISSUE TITLE
Can't build demo-transformer due to missing CompositionPlayer in CompositionPreviewActivity

### ISSUE THREAD

**Issue by kolyneh** [androidx/media#741]
### Version

Media3 `main` branch

### Devices that reproduce the issue

All devices.

### Reproducible in the demo app?

Yes

### Reproduction steps

Run the demo: `demo-transformer` .

### Expected result

Provide `androidx.media3.transformer.CompositionPlayer`.

### Actual result

In `CompositionPreviewActivity` we can't import `androidx.media3.transformer.CompositionPlayer` since it's missing.

If `CompositionPlayer` is ready to be imported then make it public.

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by droid-girl** [comment]
The fix is already on the way

**Comment by droid-girl** [comment]
In the meantime, you could comment out `CompositionPreviewActivity` from the Manifest file and comment out the content of `CompositionPreviewActivity`. It should allow you to compile the demo app

**Comment by kolyneh** [comment]
Thanks.

**Comment by droid-girl** [comment]
Should be fixed now with the latest commit. Thank you for reporting the issue
