### ISSUE TITLE
How can I get per frame video data when play rtsp stream ?

### ISSUE THREAD

**Issue by AnyLifeZLB** [androidx/media#742]
How can I get per frame video data when play rtsp stream ?  We want to use AI to analyze it

**Comment by tonihei** [comment]
The actual video frames are not generally available during normal playback because they are directly sent to the output surface. 

However, you can specify video effects via `ExoPlayer.setVideoEffects`, which gives you access to the frames in OpenGL. (see `GlEffect` and existing subclasses of it).
