### ISSUE TITLE
onPlayWhenReadyChanged with wrong state when using player.setPauseAtEndOfMediaItems(true);

### ISSUE THREAD

**Issue by theBlbDan** [androidx/media#744]
### Version

Media3 1.1.1

### Devices that reproduce the issue

Pixel 8 Pro
Pixel 6 Pro API 33 Emulator

### Reproducible in the demo app?

Not tested

### Reproduction steps

Migrated from ExoPlayer 2.18.7 to Media3 1.1.1.  Extending MediaSessionService based on the example in the [Media3 documentation](https://developer.android.com/guide/topics/media/session/mediasessionservice).

Provide a list of media items to play back.
Set ```player.setPauseAtEndOfMediaItems(true);```
Push play.

### Expected result

Unless the user interacts with the Player UI, such as pressing the pause button, the ```playbackState``` parameter should reflect the proper reason, in this case when the current track ends it should be  ```Player.PLAY_WHEN_READY_CHANGE_REASON_END_OF_MEDIA_ITEM```.

I use this to determine what to do if the player only wants the current track played, or to continue to play the next track.

	@Override
	public void onPlayWhenReadyChanged(boolean playWhenReady, int playbackState) {
		Player player = BibleAudioPlayer.this.player;
		if (player == null) return;

		boolean continuousIsChecked = continuousToggleSwitch.isChecked();
		boolean repeatIsChecked = repeatToggleSwitch.isChecked();
		if (playbackState == Player.PLAY_WHEN_READY_CHANGE_REASON_END_OF_MEDIA_ITEM) {
			if (!(continuousIsChecked || repeatIsChecked)) {
				player.seekTo(0);
			} else {
				player.play();
			}
		}
	}

### Actual result

When providing a list of media items and having ```player.setPauseAtEndOfMediaItems(true);``` and the current track ends, ```onPlayWhenReadyChanged()``` is called with ```playbackState``` == ```Player.PLAY_WHEN_READY_CHANGE_REASON_USER_REQUEST``` when it should be ```Player.PLAY_WHEN_READY_CHANGE_REASON_END_OF_MEDIA_ITEM```

### Media

The issue is indifferent to the media items.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by tonihei** [comment]
I can no longer reproduce this and I think it was already fixed by https://github.com/androidx/media/commit/4ebe630a80296cbb4437336a50abccb39da978f7 last week.

**Comment by theBlbDan** [comment]
@tonihei Is there a build I can test this on?

**Comment by tonihei** [comment]
It should be part of the 1.2.0-rc01 release later this week.

**Comment by theBlbDan** [comment]
@tonihei 1.2.0-rc01 seems to have resolved the problem.  Thank you.
