### ISSUE TITLE
How to customize notification icon on Android 13+

### ISSUE THREAD

**Issue by dabluck** [androidx/media#751]
Hi, 

I would like to achieve the following on Android 13+. 

- respond to bluetooth headset SEEK_TO_NEXT and SEEK_TO_PREVIOUS commands
- show custom drawable for previous/next icons in media notification

It seems that this is catch 22. 

If we remove seek_to_previous/seek_to_next commands from available commands in a ForwardingPlayer, then the default icons are hidden in the media notification, and we can add a custom command that basically does the same thing. But then a bluetooth headset sending the command will be ignored.

If we add seek_to_next/seek_to_previous to the available commands, the system always puts its own drawable icon.

![Screenshot_1697807548](https://github.com/androidx/media/assets/1688770/367725e8-2167-4bf6-acd1-7ade8228082f)

The system icons do not represent the action it's going to take which is a rewind / fast forward rather than skipping to the next media item. How can I either suppress these buttons or change the icons?

This is how every podcast app works so I'm guessing it should be supported. I saw some other issues addressed similar problems but I couldn't see an easy answer so bringing it up here.

Thanks!

**Comment by tianyif** [comment]
Hi @dabluck,

> The system icons do not represent the action it's going to take which is a rewind / fast forward rather than skipping to the next media item.

For clarifying, did you mean that the actions you hope to have are skipping to previous / next, but the system icons for these actions are actually rewinding / fasting forward? I think the buttons `|<` and `>|` in your screenshot do stand for skipping to previous / next, and the icons for rewinding and fasting forward (eg. seek back / forward 10s) are something like `<<` and `>>`.

Or do you still want to customize the icons for skipping to previous / next to something else?

**Comment by dabluck** [comment]
@tianyif this can be closd, the functionality I needed was added with the `MediaSession.Callback.onMediaButtonEvent(Intent)` API in 1.2
