### ISSUE TITLE
Exoplayer low latency CMAF

### ISSUE THREAD

**Issue by alfonsoramosa** [androidx/media#752]
Hi,

I can see in the list of supported formats, that CMAF is already supported https://exoplayer.dev/supported-formats.html

We are looking into reducing the latency of our live streams going into low latency with CMAF over DASH + Widevine as DRM

Will Exoplayer support that out of the box in any AndroidTv device (where Widevine is mandatory), or it needs any kind of support from the device or chipset?

Thank you

**Comment by icbaker** [comment]
This should just work. Whether a stream is low-latency and whether it's protected with DRM are fairly orthogonal and handled separately within the player.

I'm going to close this. If you try this and something doesn't work please file a new issue with full info and repro instructions.
