### ISSUE TITLE
1.2.0 beta1 not compliant with Google Play policies.

### ISSUE THREAD

**Issue by fourofspades** [androidx/media#755]
### Version

Media3 pre-release (alpha, beta or RC not in this list)

### More version details

Media3 1.2.0-beta01

### Devices that reproduce the issue

N/A  Google Play policy issue.

### Devices that do not reproduce the issue

None

### Reproducible in the demo app?

Yes

### Reproduction steps

Publish an app on the Google Play store using 1.2.0-beta01

### Expected result

App is compliant with Google Play policies

### Actual result

App Status: Rejected Your app has been rejected and wasn't published due to the policy issue(s) listed below. If you submitted an update, the previous version of your app is still available on Google Play.

Issue found: Voice commandsMedia AppsYour app does not respond (no music played or error message shown) after issuing a voice command.

### Media

My app is already accepted in the store using 1.2.0-Alpha2.  I updated to 1.2.0-Beta1, making no other changes, and the app is not compliant.  This suggests something has changed in the library that is upsetting Google Play policy scanning.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by fourofspades** [comment]
Reverting to 1.20 alpha 2, no other changes and Google happily accepted the build with no issues.

**Comment by ChernyshovYuriy** [comment]
I can assure there is no issue with latest release.
I do use latest release and my app supported on Automotive OS, TV and Mobile.
I found the same problem on other release (can't recall, maybe 1.1 or earlier) and it turned out the issue was indeed on my side.
What I would suggest is - test your app with voice commands. You might be surprised :-)

**Comment by fourofspades** [comment]
Hmm, something odd is going on.  When I issue the following ADB command, my app responds correctly to the search query

am start -a "android.media.action.MEDIA_PLAY_FROM_SEARCH" -e query "listen to Radio X on My App"  

Which suggests my app is OK, it also works from voice, but less predictable, which is why I use the ADB.   The fact remains, I am unable to update to 1.2.0beta01 as it's always rejected by google, downgrading to 1.1.0alpha2 and Google Play is happy.  Upgrading again, Google are upset.   I have repeated this 4 times, and the same result each time.   All I change is the Media3 library version in my gradle and the version number of my app.

Will try some other things, but it's all very weird for me.

**Comment by ChernyshovYuriy** [comment]
What about responding to a simple commands like Play, Pause, Stop?
I use a real automotive target with real voice commands, sorry, can't help with adb simulation in this case.

**Comment by fourofspades** [comment]
Play, Pause, Skip Forward, Skip back all work as voice commands, via Android Auto, and via Bluetooth headset controls.

**Comment by icbaker** [comment]
Can you please try updating to rc01 and see if the issue still persists?

**Comment by fourofspades** [comment]
No issues publishing to release track using 1.2.0-rc01.   Really not sure what was going on.  Everything appeared to be compliant my end, and there we no changes between builds that were accepted and builds that were rejected, other the media3 version,  It was very consistent using 1.2.0-beta02, it would always fail, rolling back it would always pass.

A couple of things to note, that may be relevant.   Targeting SDK34, and also, the builds would only be rejected when pushed to Open Testing and Release tracks (not Internal Test Track).

Anyway, my customer release is now using 1.2.0rc01 without any issues, so whilst I have no idea what was going on, it seem to have been resolved somewhere within Google...
