### ISSUE TITLE
Custom extras in MediaMetadataCompat not getting populated in "extras" field of MediaMetadata

### ISSUE THREAD

**Issue by Sachin-Radhakrishnan** [androidx/media#756]
I am trying to migrate one of my applications to media3 with the service components still using legacy implementation (old media libs)

Inside the service components, some custom keys are getting added into the MediaMetadataCompat, but it is not getting populated in the "extras" field of MediaMetadata (extra is coming as null). Why is it so ?

I am using 1.2.0-beta01 version of media3-session library.

**Comment by icbaker** [comment]
The conversion from `MediaMetadataCompat` to `MediaMetadata` is implemented here:

https://github.com/androidx/media/blob/c16accb81673393530ce37dcee9b2276631ebd42/libraries/session/src/main/java/androidx/media3/session/MediaUtils.java#L435-L436

It uses known keys in `MediaMetadataCompat` to populated named/typed fields in `MediaMetadata`, but doesn't propagate unknown key/values into `MediaMetadata.extras`.

Can you provide a bit of context about what info you need to propagate across? Is it keys that are defined on `MediaMetadataCompat` but that don't have a matching field in `MediaMetadata`, or is it completely custom keys in `MediaMetadataCompat`? It's not obvious to me that `MediaMetadataCompat` is intended to support completely custom keys.

**Comment by Sachin-Radhakrishnan** [comment]
@icbaker Yes, it is the keys that are defined in `MediaMetadataCompat `that does not have a matching field in `MediaMetadata`.

Standard keys were used to populate most of the values in `MediaMetadataCompat `, but there are some situations where some custom keys have been used to pass on some values.

Please find the sample code snippet below

```
val builder=MediaMetadataCompat.Builder()
builder.putString(MediaMetadataCompat.METADATA_KEY_TITLE,"520")
builder.putString(MediaMetadataCompat.METADATA_KEY_DISPLAY_SUBTITLE,"AM")
builder.putString("radio_station_frequency_in_hertz","500000")
builder.build()
```

We are expecting "radio_station_frequency_in_hertz" to be part of the `MediaMetadata.extras.` 

Migrating the service code to use **media3** APIs is beyond our control, so it will be better if such custom fields were also included as part of `MediaMetadata.extras`. 

Why can't the entire bundle of `MediaMetadataCompat ` be included as part of `MediaMetadata.extras` just for backward compatibility? This will help us to continue using **media3** APIs.

**Comment by Sachin-Radhakrishnan** [comment]
@icbaker @tianyif Any update on this? Can we expect a fix?

**Comment by tianyif** [comment]
Hi @Sachin-Radhakrishnan, I'm working on a solution to this.

**Comment by tianyif** [comment]
The fix was submitted, and it will be appear in the dev branch shortly.
