### ISSUE TITLE
Getting 'DashManifestStaleException' for a  dash live stream that is working on other players

### ISSUE THREAD

**Issue by pritiverma22** [androidx/media#759]
We are facing an issue where for a dash live stream, we are getting 'DashManifestStaleException' after 11-12 minutes of playback. 
The stream is working fine on web players though like bitmovin player or DashJs player.

Test Stream: MediaURL extracted from this url: https://beta-invidi.serversideai.com/dash/view/1511a5c6-a235-4354-9f50-a6a993e60cb2?api-key=0c2a3d28-127e-4059-bf16-a5db6cd6a830&tag=FirstParty,FP-nowtilus
The source stream have SCTE markers for ad break of duration 60s after every 2 minutes. So, stream contains content and  ads inserted in between.

App logs and network logs from charles have been placed at google drive link: https://drive.google.com/drive/folders/16Yh2cliq_0jAqSEexvVpiypCSjQLp6iP

Please find attached the screenshot of the error from application log:
<img width="1200" alt="Screenshot_ErrorFromAppLogs" src="https://github.com/androidx/media/assets/15367097/ccb0415b-012f-4d65-a01e-68f50c931184">

From charles, when looking at the manifest we could not figure out anything wrong.
So, could not find out why Exoplayer is returning this 'DASHManifestStale' exception. 

Can you please help us in understanding what could be the root issue here and  if/how this can be fixed at our end.

**Comment by marcbaechinger** [comment]
Sorry for my late response. 

When I load the MediaURL from the URI above I get a 404. The resource probably has expired. Can you please provide this again? 

Do you see this behaviour when you have the metadata renderer not setup?  Something like this should do the trick:

```
new DefaultRenderersFactory(context.getApplicationContext()) {
      @Override
      protected void buildMetadataRenderers(Context context, MetadataOutput output,
          Looper outputLooper, @ExtensionRendererMode int extensionRendererMode,
          ArrayList<Renderer> out) {
        // do nothing
      }
    }
```

If that works without metadata then it's in the metadata renderer. We'd need the stream agin to look into this.

**Comment by pritiverma22** [comment]
Hello @marcbaechinger 
Thankyou for your response. Please try now with URL: https://beta-invidi.serversideai.com/dash/view/1511a5c6-a235-4354-9f50-a6a993e60cb2?api-key=0c2a3d28-127e-4059-bf16-a5db6cd6a830
Extract mediaURL from this, it is working now.
In order to get ads, please play stream from any of below locations only :
USA, sweden, Germany.
(you may need to use VPN to simulate location if your location is other than this list)

**Comment by icbaker** [comment]
The `IndexOutOfBoundsException` stack trace in https://github.com/androidx/media/issues/759#issuecomment-1831025476 looks similar-ish to the one reported in https://github.com/google/ExoPlayer/issues/10838, which was fixed in https://github.com/google/ExoPlayer/commit/de2ad14f46f4790063dfef849ba8cc0069f6106e and [cherrypicked](https://github.com/google/ExoPlayer/commit/7d221150a3851300bf8f96fb9ca8b6c2604474ae) into 2.19.0. Can you try updating your ExoPlayer version to check the issue still reproduces on the latest version? (note that the latest available exoplayer2 version is 2.19.1, which corresponds to media3 1.1.1, while the latest media3 version is 1.2.0 (with no corresponding exoplayer2 version)).

**Comment by PriyankaPrabhu** [comment]
Hi @pritiverma22
I am facing the same issue of Stale Manifest
Did you find any solution for this

**Comment by AnujaK1** [comment]
Hi @pritiverma22, got similar issue, is there any solution to this?
