### ISSUE TITLE
Ad UI now showing up if Player is used with new PlayerView

### ISSUE THREAD

**Issue by anupamkumar12** [androidx/media#760]
We use `ExoPlayer` with IMA integration to deliver content/ad. The Player UI is extension of `FrameLayout` just like `PlayerView` or `StyledPlayerView` provided by `Exoplayer`, I’ll call it as `PlayerView`. `CorePlayer` warps `Exoplayer`. The `Exoplayer` is created as part of initializing `CorePlayer`.

Under the hood, `CorePlayer` can be transferred from one `PlayerView` to another `PlayerView`, resulting in seamless playback and developing new experiences.

For example a `PlayerView` is created as part of watch now as shown in Content_watchnow.png, which creates a new `CorePlayer`/`ExoPlayer` and start playback. On user interaction, a `VideoActivity` is launched which populates a new `PlayerView` but we are able to transfer and bind the existing `CorePlayer`/`Exoplayer` to VideoActivity's `PlayerView` and continue playback without any interruption as seen in content_VideoActiivity.png. 

The same is true for ad playback using IMA, the one problem is the UI elements (count down timer/ Learn more) is not displayed after transferring the CorePlayer/ExoPlayer. As shown in ad_watchnow.png and ad_VideoActivity.png. 
The `AdEventListener` callbacks for quartile are received during the content playback. Exoplayer itself correctly identifies the ad/content playback so we are able to show content UI when content starts even though we keep receiving ad quartile events.

The problem seems to be the inability of updating IMA ads sdk with new container where ad playback needs to take place or where IMA can show its UI. 

Is there a way to either update IMA SDK about new container or save/restore ad state with a new player/IMA sdk object. Is there any other way to mitigate this issue.

**Content_WatchNow**
![Content_WatchNow](https://github.com/androidx/media/assets/11477349/9cfb1bc8-cb67-4ecf-b797-71070f87c140)

**Content_VideoActivity**
![Content_VideoActivity](https://github.com/androidx/media/assets/11477349/5e358c0b-5b7e-4216-b454-e2b2eb97b2ab)

**Ad_WatchNow**
![Ad_WatchNow](https://github.com/androidx/media/assets/11477349/8b2c6185-9ff1-4dde-8d6c-4bda8f039f90)

**Ad_VideoActivity**
![Ad_VideoActivity](https://github.com/androidx/media/assets/11477349/0488e469-61a5-49a2-b34e-b43a7dc12636)

**Comment by icbaker** [comment]
> The problem seems to be the inability of updating IMA ads sdk with new container where ad playback needs to take place or where IMA can show its UI.
> 
> Is there a way to either update IMA SDK about new container or save/restore ad state with a new player/IMA sdk object. Is there any other way to mitigate this issue.

This sounds like a question for the IMA SDK folks rather than ExoPlayer (we only maintain the ExoPlayer IMA extension). I suggest you ask over here: https://groups.google.com/g/ima-sdk
