### ISSUE TITLE
Preview thumbnails on DASH - Any sample stream?

### ISSUE THREAD

**Issue by alfonsoramosa** [androidx/media#769]
Hi,

we are looking into adding thumbnails preview to our DASH streams (live, catchup, vod) using a solution based on
https://dashif-documents.azurewebsites.net/DASH-IF-IOP/pull/341/DASH-IF-IOP.html#thumbnails

Is it there any test stream that already has the thumbnails available, so we can try it with Exoplayer?

If you have experience with this topic, your feedback is more than welcome 

Thank you!

**Comment by icbaker** [comment]
We don't generally manufacture test streams, and I'm not aware of any test streams beyond those in our demo app. This issue tracker is mostly focussed on the playback of content, rather than it's preparation.
