### ISSUE TITLE
How to override notificatoin play button

### ISSUE THREAD

**Issue by BoikoIlya** [androidx/media#771]
i have audio focus change listener 

```
class AudioFocusChangeListener @Inject constructor(
    private val playerCommunication: PlayerCommunication
): AudioManager.OnAudioFocusChangeListener {

    override fun onAudioFocusChange(focusChange: Int) {
        when (focusChange) {
            AudioManager.AUDIOFOCUS_LOSS_TRANSIENT -> playerCommunication.map(PlayerCommunicationState.Pause)

            AudioManager.AUDIOFOCUS_LOSS -> playerCommunication.map(PlayerCommunicationState.Pause)

            AudioManager.AUDIOFOCUS_GAIN -> playerCommunication.map(PlayerCommunicationState.Resume)

        }
    }
}
```

and 

```
interface AudioFocusChange {

    fun requestAudioFocus()

    fun abandonAudioFocus()

    class BelowApi26(
        private val audioFocusChangeListener: AudioFocusChangeListener,
        private val audioManager: AudioManager
    ): AudioFocusChange {

        override fun requestAudioFocus() {
            audioManager.requestAudioFocus( audioFocusChangeListener, AudioManager.STREAM_MUSIC, AudioManager.AUDIOFOCUS_GAIN)
        }

        override fun abandonAudioFocus() {
            audioManager.abandonAudioFocus(audioFocusChangeListener)
        }
    }

    @RequiresApi(Build.VERSION_CODES.O)
    class AboveApi25(
        private val audioManager: AudioManager,
        private val audioFocusRequest: AudioFocusRequest
    ): AudioFocusChange {


        override fun requestAudioFocus() {
            audioManager.requestAudioFocus(audioFocusRequest)
        }

        override fun abandonAudioFocus() {
            audioManager.abandonAudioFocusRequest(audioFocusRequest)
        }
    }
}
```  

this is how i build AudioFocusRequest
```
                AudioFocusRequest.Builder(AudioManager.AUDIOFOCUS_GAIN)
                    .setAudioAttributes(
                        android.media.AudioAttributes.Builder()
                            .setUsage(android.media.AudioAttributes.USAGE_GAME)
                            .setContentType(android.media.AudioAttributes.CONTENT_TYPE_MUSIC)
                            .build()
                    )
                    .setAcceptsDelayedFocusGain(true)
                    .setOnAudioFocusChangeListener(audioFocusChangeListener)
                    .build()
           
```

i want to call abandonAudioFocus in my AudioFocusChange interface when i press pause on notification. How to make that? Or exist other options?

**Comment by icbaker** [comment]
> i want to call abandonAudioFocus in my AudioFocusChange interface when i press pause on notification. How to make that? Or exist other options?

If you want to know when the player becomes paused you can listen to [`Player.Listener.onPlayWhenReadyChanged`](https://developer.android.com/reference/androidx/media3/common/Player.Listener#onPlayWhenReadyChanged(boolean,int)). See also https://developer.android.com/guide/topics/media/exoplayer/listening-to-player-events

**Comment by BoikoIlya** [comment]
> > i want to call abandonAudioFocus in my AudioFocusChange interface when i press pause on notification. How to make that? Or exist other options?
> 
> If you want to know when the player becomes paused you can listen to [`Player.Listener.onPlayWhenReadyChanged`](https://developer.android.com/reference/androidx/media3/common/Player.Listener#onPlayWhenReadyChanged(boolean,int)). See also https://developer.android.com/guide/topics/media/exoplayer/listening-to-player-events

if i will abandon audio focus when player is paused it is wrong. because for example  it plays video in other app and audio focus listener will be triggered set  pause , after i close video it will not resume music because listener was abandoned. i need to abandon only when i set pause from notification. that is why i asking this question.

**Comment by BoikoIlya** [comment]
> > > i want to call abandonAudioFocus in my AudioFocusChange interface when i press pause on notification. How to make that? Or exist other options?
> > 
> > 
> > If you want to know when the player becomes paused you can listen to [`Player.Listener.onPlayWhenReadyChanged`](https://developer.android.com/reference/androidx/media3/common/Player.Listener#onPlayWhenReadyChanged(boolean,int)). See also https://developer.android.com/guide/topics/media/exoplayer/listening-to-player-events
> 
> if i will abandon audio focus when player is paused it is wrong. because for example i play video in other app and audio focus listener will be triggered set pause , after i close video it will not resume music because listener was abandoned. i need to abandon only when i set pause from notification. that is why i asking this question.

i am sorry for my question, i investigated that i dont need all this i just can add this when build ExoPlayer instance
  ```
.setAudioAttributes(
                AudioAttributes.Builder()
                    .setUsage(C.USAGE_MEDIA)
                    .setContentType(C.AUDIO_CONTENT_TYPE_MUSIC)
                    .build()
                ,true)
```
