### ISSUE TITLE
Need ffmpeg aar 

### ISSUE THREAD

**Issue by Hamamas** [androidx/media#775]
Could you please provide me with the FFmpeg AAR file or direct me to the appropriate source where I can obtain it

**Comment by icbaker** [comment]
Instructions for building the ffmpeg extension are here: https://github.com/androidx/media/tree/release/libraries/decoder_ffmpeg#build-instructions-linux-macos

We have no plans to distribute an AAR for this.

**Comment by Hamamas** [comment]
I ask if someone have the aar to send it to me
