### ISSUE TITLE
How to set the icon of the media notification?

### ISSUE THREAD

**Issue by neonwarge04** [androidx/media#776]
I can't seem to find this anywhere in the demo-session sample in the main branch. The iconography used in Android Notification is always set to play button. 

Question:

- How do I set a different icon in the notification?
- How do I show the title of my application in the notification? Is that possible?
- Is this described somewhere in documentation?

![Screenshot from 2023-10-28 21-33-31](https://github.com/androidx/media/assets/3163716/ce2a5deb-830c-42de-bcec-2b2ac484119f)

Even the sample in demo-session (main branch) doesn't have any title and its not clear in the sample how to change the branding in notification:

![Screenshot from 2023-10-28 21-46-06](https://github.com/androidx/media/assets/3163716/1294fada-9c95-4964-a7f7-95def268abb7)

I saw this article reference somewhere in other questions but it is a bit stale article https://android-developers.googleblog.com/2020/08/playing-nicely-with-media-controls.html. The project reference is UAMP and not using the Jetpack Media3

**Comment by marcbaechinger** [comment]
You can override the drawables of the `DefaultMediaNotificationProvider` which is document in the [class level javadoc](https://developer.android.com/reference/androidx/media3/session/DefaultMediaNotificationProvider#drawables) of the same.

Something like this in your resource folder:

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
  <drawable name="media3_notification_small_icon">@drawable/my_custom_icon</drawable>
</resources>
```

Regarding the app name I think the system knows the name of the app. I quickly checked API 29 and there the app name is displayed at the top left of the notification. 

Your screenshot seems to be API 33 or 34 and apparently the app name is not displayed.

I'm closing this issue. Please open a new issue if you think something is wrong with that implementation.

API 29:

![image](https://github.com/androidx/media/assets/584321/9160c9b6-4d95-47f3-9414-eb8b9da12bd5)
