### ISSUE TITLE
Can we use DefaultVideoCompositor  to overlay video over Image background  

### ISSUE THREAD

**Issue by pawaom** [androidx/media#781]
Can we use DefaultVideoCompositor  to overlay video over Image background  

 Suppose we have a image as the background and we want to overlay video over it , how can this be achieved 

Can we see an example of the implementation, if image is not supported , how do we use this class for overlaying video over video

I have looked for documentation but could not find one 

An example would be helpful,

**Comment by dway123** [comment]
Yes, you can use `DefaultVideoCompositor` to overlay videos over images.

To do so, use `Transformer`, where the input `Composition` has multiple `sequences`. The first `sequence` (on the top) can have the video, and the second sequence (on the bottom) can have the image. You can use a `VideoCompositorSettings` like in [this test](https://github.com/androidx/media/blob/72b7019578f3051e1bec826cf0ac401a86d818dc/libraries/transformer/src/androidTest/java/androidx/media3/transformer/TransformerMultiSequenceCompositionTest.java#L159-L203) to place the image/video as you'd like over the other image/video.
