### ISSUE TITLE
Exoplayer Clearkey DRM

### ISSUE THREAD

**Issue by AmarnathCJD** [androidx/media#790]
[manifest.txt](https://github.com/androidx/media/files/13257617/manifest.txt)

Still Unable to Play The MPD using ClearKey

```
Playback error
    androidx.media3.exoplayer.ExoPlaybackException: Unexpected runtime error
    Caused by: android.media.MediaCodec$CryptoException: Decryption Error: ERROR_DRM_NO_LICENSE
    No hidl drm factories found
    Failed to find passthrough drm factories
    uuid=[e2719d58a985b3c9 781ab030af78d30e] Failed to make drm plugin: 4
    
 ```
 
 **Full Code:** https://gist.github.com/AmarnathCJD/35e9d2ef3c1e0a11d1b470346df6405d
 
**MPD:** 
**Key:** bc0aaa542e06b1816fea83b30d26be2c
**KeyId:** afa116dde11a5b0882404230854616be

The following work perfectly in html using the following code:

```
jwplayer("myElement").setup({
                file: "https://bpprod6linear.akamaized.net/bpk-tv/irdeto_com_Channel_464/output/manifest.mpd", type: "dash",
                drm: {
                    "clearkey": {
                        "keyId": "afa116dde11a5b0882404230854616be", "key": "bc0aaa542e06b1816fea83b30d26be2c"
                    }
                }
});
```
manifest of mpd is attatched Along
What am I missing here?
PS: sorry for this is the 3rd issue, keeps closing so.

**Comment by AmarnathCJD** [comment]
Ok got it
There is a diffrence between base64 encoded and hex base64 encoded strrings


Now how to implement quality selector ?
without using xml

**Comment by icbaker** [comment]
> There is a diffrence between base64 encoded and hex base64 encoded strrings

It sounds like you've resolved the clearkey issue? I think you've realised that your example code is incorrectly treating `bc0aaa542e06b1816fea83b30d26be2c` as a UTF-8 string when converting it to base64, when instead you should be treating it as a hex string. 

Your incorrect code converts `"bc0aaa542e06b1816fea83b30d26be2c"` to `YmMwYWFhNTQyZTA2YjE4MTZmZWE4M2IzMGQyNmJlMmM` (I used https://base64.guru/converter).

Treating the input has hex gives you the following base64 instead: `vAqqVC4GsYFv6oOzDSa+LA` (using https://base64.guru/converter/encode/hex) which then needs to be changed to `vAqqVC4GsYFv6oOzDSa-LA` to be URL safe.

> Now how to implement quality selector ?

Not sure what this means, please file a new issue with complete information if you still need assistance on this as it doesn't sound related to your clearkey question.
