### ISSUE TITLE
I/ACodec: codec does not support config operating rate (err -2147483648)

### ISSUE THREAD

**Issue by zohaibmushwani** [androidx/media#800]
I have developed a custom curve view that provides speed values, and I'm using an FFmpeg wrapper in an Android application to apply these speed values to video segments. The primary goal is to enable variable playback speed for video segments in our front-end application.

I encountered an issue where I couldn't change the speed beyond a certain point. Specifically, I observed an error related to the operating rate in the logs.
I/ACodec: codec does not support config operating rate (err -2147483648)

I am speeding up or down the video using a handle and runnable for each segment and the next speed change is called after the time needs to be taken by segment. Still, I am facing issues after the speed does not change after some segments according to my speed list for the video.

I need to speed up or down the video from 0.1 to 10x.

**Comment by rohitjoins** [comment]
Hi @zohaibmushwani,

Thank you for reaching out to us. However, I have noticed that the log you provided is from the Android platform and not directly related to our library. We do not provide support for Android platform, as our focus is on ensuring the seamless functioning of our library itself.

If you could provide more context about the media3/ExoPlayer API you're using I will able to assist you further.

Thanks,

**Comment by zohaibmushwani** [comment]
I am using media3 exoplayer to play videos with variable speed, but the playback speed does not change according to my settings. I tried to adjust the playback speed from 0.1x to 10x, but the player native code keeps reporting this log: _`[I/ACodec: codec does not support config operating rate (err -2147483648)]`_.I think there is something wrong with the library code that prevents it from changing the speed in such a short time.

What is the playback limit of media3 exoplayer? How can I increase it if it is too low for my purpose? Do I need to compile or modify the source code of the library?

My requirement is to speed up or slow down the video up to 10x or 0.1x, and change it frequently in a short period of time.

**Comment by rohitjoins** [comment]
Are you using `Player.setPlaybackSpeed(float speed)` to set the playback speed? Please try to give more details about the APIs you're using, the settings you're using and how often are you trying to update the speed, etc. 

> What is the playback limit of media3 exoplayer?

The only limitation is to not have a playbackSpeed of `0`.

**Comment by zohaibmushwani** [comment]
I have created the segments of video after interval 200-1000 milli seconds so overall video is divided in a list of interval, 
0,1 | 1,2 | 2,3 | and so on and each segment has a speed from 0.1x to 1x and 1x to 10x the slow and fast speed, as available in video editing applications the slow-motion using curve.

I am updating the speed after each segment by calling speed changing from the handler duration = INTERVAL/speed
and also I am changing the seekbar integrated in my custom view.
I am getting that error in logs **"I/ACodec: codec does not support config operating rate (err -2147483648)"**.

`val segments = listOf(
    Pair(0.0f, 1.3f),
    Pair(1.3f, 2.5f), 
    Pair(2.5f, 3.8f), 
    Pair(3.8f, 5.0f), 
    Pair(5.0f, 6.3f), 
    Pair(6.3f, 7.5f), 
    Pair(7.5f, 8.8f), 
    Pair(8.8f, 10.0f), 
    Pair(10.0f, 12.0f), 
    Pair(12.0f, 13.5f), 
    Pair(13.5f, 14.0f), 
    Pair(14.0f, 15.5f) 
)`

`val speedList = listOf(0.3f, 0.5f, 1.0f, 1.6f, 2.5f, 3.0f, 4.0f, 5.5f, 6.6f, 7.7f,8.7f,9.5f) `

**Comment by andrewlewis** [comment]
You can probably ignore logging like `codec does not support config operating rate` as it's unlikely to be directly relevant to what you are trying to do -- the codec's operating rate is just a hint to tell the codec what resources to reserve so it can decode at a requested speed, but a given codec implementation may decode faster or slower and ExoPlayer/the app is generally responsible for when frames are actually presented.

> Still, I am facing issues after the speed does not change after some segments according to my speed list for the video.

Are you saying that when using `player.setPlaybackSpeed` sometimes the speed change takes effect and sometimes it doesn't?
