### ISSUE TITLE
Custom extras in MediaMetadata not getting populated in MediaMetadataCompat

### ISSUE THREAD

**Issue by zzmgoing** [androidx/media#802]
### Version

Media3 1.1.1

### Devices that reproduce the issue

All

### Reproducible in the demo app?

Yes

### Reproduction steps

1. client use media3
val mediaMetadata = MediaMetadata.Builder().setExtras(bundleOf("my_custom_key" to "my value")).build()
val mediaItem = MediaItem.Builder().setMediaMetadata(mediaMetadata).build()
2. sdk use media
android.media.session.MediaController#registerCallback(android.media.session.MediaController.Callback) 
android.media.session.MediaController.Callback#onMetadataChanged
MediaMetadataCompat does not contain "my_custom_key"
3. i found
androidx.media3.session.MediaUtils#convertToMediaMetadataCompat
MediaMetadata extras are not processed

### Expected result

I saw this issue has been solved [756](https://github.com/androidx/media/issues/756), but my problem is exactly the opposite of this one.

### Actual result

MediaMetadataCompat does not contain "my_custom_key" in onMetadataChanged method

### Media

Not applicable

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by rohitjoins** [comment]
Fix was submitted to the main branch 6df2408.
