### ISSUE TITLE
Using FLAG_ALLOW_NON_IDR_KEYFRAMES along with DefaultMediaSourceFactory

### ISSUE THREAD

**Issue by spirgiuz** [androidx/media#814]
Hello,

We would like to use the DefaultMediaSourceFactory, because we are interested in using ClippingConfiguration. But we also mainly use HLS and for our streams FLAG_ALLOW_NON_IDR_KEYFRAMES is needed. We're having trouble setting the flag on the DefaultMediaSourceFactory. We set it as so:
```
val extractorsFactory = DefaultExtractorsFactory()
extractorsFactory.setTsExtractorFlags(DefaultTsPayloadReaderFactory.FLAG_ALLOW_NON_IDR_KEYFRAMES)
val mediaSourceFactory = DefaultMediaSourceFactory(this, extractorsFactory)
val player = ExoPlayer.Builder(this)
     .setMediaSourceFactory(mediaSourceFactory)
     .build()
```

But from debugging we see the flag is not set. I've looked into it a bit and it seems in this line the HlsMediaSourceFactory is created:
https://github.com/androidx/media/blob/35219ee5e58c1feb5cc76b455153d48bf8560342/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/source/DefaultMediaSourceFactory.java#L698

and the HlsMediaSourceFactory constructor ignores the ExtractorsFactory set in DefaultMediaSourceFactory and just creates its own:
https://github.com/androidx/media/blob/35219ee5e58c1feb5cc76b455153d48bf8560342/libraries/exoplayer_hls/src/main/java/androidx/media3/exoplayer/hls/HlsMediaSource.java#L164

Is there a way to use both a ClippingConfiguration and set FLAG_ALLOW_NON_IDR_KEYFRAMES ?

**Comment by icbaker** [comment]
> the HlsMediaSourceFactory constructor ignores the ExtractorsFactory set in DefaultMediaSourceFactory

This is [documented](https://developer.android.com/reference/androidx/media3/exoplayer/source/DefaultMediaSourceFactory#DefaultMediaSourceFactory(android.content.Context,androidx.media3.extractor.ExtractorsFactory)) on the `DefaultMediaSourceFactory(Context, ExtractorsFactory)` constructor that you're using (emphasis mine):
> An `ExtractorsFactory` used to extract **progressive media** from its container.

An HLS stream is **not** progressive media (progressive media is a single simple media file, e.g. an MP3 file).

----

> Is there a way to use both a ClippingConfiguration and set FLAG_ALLOW_NON_IDR_KEYFRAMES ?

Currently the only way is to define your own `MediaSource.Factory` that duplicates the `ClippingConfiguration` handling from `DefaultMediaSourceFactory` (i.e. wrap the inner `MediaSource` in a `ClippingMediaSource`):

https://github.com/androidx/media/blob/3f366109b7e5cbf7b7e5b46e8b923e167e9ae893/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/source/DefaultMediaSourceFactory.java#L522-L535

https://github.com/androidx/media/issues/185 tracks a larger improvement that would add `ClippingConfiguration` support to `HlsMediaSource.Factory` and avoid the need for this custom `MediaSource.Factory` implementation.
