### ISSUE TITLE
Video Playback Error_3015_Fatalerror

### ISSUE THREAD

**Issue by jasujakaran** [androidx/media#815]
User/s observed the below Error on Android and Smart TV. (impacted LG TV)

Video Playback Error_3015_Fatalerror

Could you please update me on the -

1. When this error is likely to occur?
2. What can be done to prevent these types of errors?
3. Please share the link that has a list of all the Exo player Error codes and their description.

Thank You

Karan Jasuja

**Comment by marcbaechinger** [comment]
> Error_3015_Fatalerror

That doesn't look like an error code from Media3. Please find the ExoPlayer error codes [here](https://github.com/androidx/media/blob/release/libraries/common/src/main/java/androidx/media3/common/PlaybackException.java#L96-L237).

Please add some more details to make your report actionable. This would include a bug report (or at a minimum a stack trace), link to media, the OS version and the device model. We can not help you with the provided information.

As I said over in the ExoPlayer issue tracker: there is a template that you can follow to make your request actionable and processes more quickly. Filling it saves you more time to get an answer than it takes you to write it down. 

Here is a link so you can consult the template as a time saver hack: https://github.com/androidx/media/issues/new?assignees=&labels=question%2C+needs+triage&projects=&template=question.md&title=
