### ISSUE TITLE
MediaNotification.Provider.handleCustomAction never get called

### ISSUE THREAD

**Issue by kevinguitar** [androidx/media#82]
Hi media team 👋 

I'm integrating the new `MediaNotification.Provider` abstraction, but I realized the `handleCustomAction()` is never called because of the implementation in `MediaSessionService.onStartCommand`.

https://github.com/androidx/media/blob/850bd69dddca45915199f221d48573fca3fc790b/libraries/session/src/main/java/androidx/media3/session/MediaSessionService.java#L346

The `session` field is required here, but since the `DefaultActionFactory.createCustomAction()` doesn't provide any uri to the intent, the `session` field will always be null for custom actions, and there's no way to provide a customize action factory.

**media3 Version**: 1.0.0-alpha03

**Comment by marcbaechinger** [comment]
Thanks for reporting! 

This is fixed to some extend in the main branch, but you are right that the URI needs to be added to the `Intent` also. We will provide a fix for that to include the URI properly.

**Comment by kevinguitar** [comment]
@marcbaechinger  Thanks for replying! Looking forward to the new releases 🙌

**Comment by marcbaechinger** [comment]
I'm closing for now as this is fixed in the upcoming release.
