### ISSUE TITLE
Could any one send me ffmpeg extension for media3 i really need it for my project and i couldn't find it
My operation system is windows 

### ISSUE THREAD

**Issue by Hamamas** [androidx/media#822]

**Comment by marcbaechinger** [comment]
The ffmpeg extension can be foiund here: https://github.com/androidx/media/tree/release/libraries/decoder_ffmpeg

If there is something else you need to know, please file a new issue and narrow down your question a bit after having investigating a bit for yourself.

**Comment by haijialiu** [comment]
here is my build:
https://github.com/haijialiu/exoplayer-extension
but I don't know how to use it on media3. 
According to https://developer.android.com/guide/topics/media/exoplayer/mappings?hl=zh-cn
androidx.media3.decoder haven't ffmpeg in my project.
