### ISSUE TITLE
Multicast ABR Support in Media3

### ISSUE THREAD

**Issue by efrep** [androidx/media#828]
I am working on a project that involves streaming multimedia content via multicast ABR (Adaptive Bitrate Streaming). I was wondering if anyone could provide information on whether Media3 currently supports this functionality or if there are future plans to incorporate it.

I have reviewed the available documentation, but I haven't found specific details about multicast ABR support. I would appreciate any guidance, resources, or examples that you can share on this topic.

**Comment by tonihei** [comment]
Have you tried playing your stream already to see if it works and adapts between formats? ExoPlayer supports adaptive streaming with DASH, HLS and SmoothStreaming (see https://developer.android.com/guide/topics/media/exoplayer/supported-formats#adaptive-streaming) and also provides a `UdpDataSource` to read data via UDP. If you see any specific combination that doesn't work as expected, please provide more detailed reproductions steps.
