### ISSUE TITLE
Exoplayer is not switching to Dolby Atmos representation from Dolby 5.1

### ISSUE THREAD

**Issue by TomaszKowalik** [androidx/media#832]
Hi,

We are experiencing issues with ExoPlayer 2.18.1. We are using it for our web app on Android devices like smart TVs with Android or set-top boxes like Firestick 4K.
We are testing DASH streams that have audio tracks encoded with EC-3, which include Dolby Atmos.

This is how the AdaptationSet looks in the manifest:

```
<AdaptationSet id="2" group="1" contentType="audio" lang="en" minBandwidth="384000" maxBandwidth="576000" segmentAlignment="true" audioSamplingRate="48000" mimeType="audio/mp4" codecs="ec-3" startWithSAP="1">
      <AudioChannelConfiguration schemeIdUri="tag:dolby.com,2014:dash:audio_channel_configuration:2011" value="F801"/>
```

and we have two representations for it:

```
<Representation id="audio_eng_1=384000" bandwidth="384000">
      </Representation>
      <Representation id="audio_eng_1=576000" bandwidth="576000">
        <SupplementalProperty schemeIdUri="tag:dolby.com,2018:dash:EC3_ExtensionType:2018" value="JOC"/>
        <SupplementalProperty schemeIdUri="tag:dolby.com,2018:dash:EC3_ExtensionComplexityIndex:2018" value="16"/>
      </Representation>
    </AdaptationSet>
```

After starting the stream on a device capable of streaming Dolby Atmos, I can see that Dolby Atmos is set for the first second of the stream, and then it downgrades to 384000 Representation and never changes again. What might be the reason? We were checking it on various devices, verified that they are able to stream Dolby Atmos audio, and from what I observed, the track is being selected correctly. It is selecting track, with two formats:

![Screenshot 2023-11-22 164520](https://github.com/androidx/media/assets/91945472/0a34019f-b8ec-4f12-8f0b-58019399f5ef)

Not quite sure what might be wrong?

**Comment by tianyif** [comment]
Hi @TomaszKowalik,

> After starting the stream on a device capable of streaming Dolby Atmos, I can see that Dolby Atmos is set for the first second of the stream

Do you mean that the player **initially selected** to play the Dolby Atmos but soon it was switched to Dolby 5.1 later? It sounds like the behavior of the adaptive selection based on the current network conditions and the state of the buffer. 

But if you still think there is something not right, could you please send us the [bug reports](https://developer.android.com/studio/debug/bug-report). If you're unable to share it publicly, please send them to android-media-github@google.com with the subject `Issue #832`. Please also update this issue to indicate you've done this, and we can take a closer look.

Thanks!

**Comment by TomaszKowalik** [comment]
Hi @tianyif,  thanks for the answer! Yes, but the problem is that after it downgrades to Dolby 5.1, it never scales up again to Dolby Atmos, regardless of network conditions. And I would rather expect that it initially selects the Dolby 5.1 track and then scales up to Dolby Atmos.

Also, when we are testing the same assets on different platforms with different players under the same network conditions, they are scaling up correctly to Dolby Atmos. I created the bug report and sent it to you via email.

**Comment by tianyif** [comment]
Hi @TomaszKowalik,

Except for the network conditions, we also [evaluate](https://github.com/google/ExoPlayer/blob/r2.18.1/library/core/src/main/java/com/google/android/exoplayer2/trackselection/AdaptiveTrackSelection.java#L462-L468) if there are enough buffered data to switch up the quality. Originally I thought if the live offset you set was too short, but with realising you were using 2.18.1, which is a version already includes an [improvement](https://github.com/google/ExoPlayer/commit/9d463725fb33523e9c15fae8cf0d7ac3c86e9d6c) for all the live offsets, so there might be the other reason (not sure if still related to the buffered data) that causes your issue. To investigate this, would it be possible for you to send us your stream so we can take a closer look in the code?

And for the first switching down after starting, we can check if there were load errors on the initial atmos track, as this might exclude that track from being selected for a while. But I didn't find the `EventLogger` logs from your bug report, could you please send us another one including them?
