### ISSUE TITLE
metadata is not getting generated with Transformer setEncodingProfileLevel API

### ISSUE THREAD

**Issue by zling123** [androidx/media#834]
I am using [demo-transformer](https://github.com/androidx/media/tree/release/demos/transformer).
**The problem is when we set Profile and Level using [setEncodingProfileLevel](https://github.com/androidx/media/blob/4f5038bc07c06910b74e53408b3866dfe8dbc43d/libraries/transformer/src/main/java/androidx/media3/transformer/VideoEncoderSettings.java#L148), We don't see metadata in output mp4 by using mediainfo.exe. When we don't set profile and level, metadata gets generated.** 
Could you help me check it?

- URI to test content
    [HDR (HDR10) H265 limited range video (encoding may fail)](https://storage.googleapis.com/exoplayer-test-media-1/mp4/samsung-s21-hdr-hdr10.mp4)

- My code change
![image](https://github.com/androidx/media/assets/53868865/1c99f01c-4d87-4ab7-af5e-3d3c68a8388c)

- Original Metadata
![image](https://github.com/androidx/media/assets/53868865/b5b29e43-3f4d-47ae-9679-32389bacac34)

- Transformed Metadata
![image](https://github.com/androidx/media/assets/53868865/dbd1bc81-6f65-46b3-833b-cccb141b8b22)

**Comment by tof-tof** [comment]
From your message, i'm assuming there are no other transformations being applied. 

For the sample video you mention, the HDR metadata is not in the headers, but rather in the bitstream. (i.e. It is dynamic metadata that potentially changes per frame, rather than static metadata that is usually stored in the header atoms). The transcoding pipeline currently doesn't support preserving the dynamic metadata, so in short. this is intended behavior.

**Comment by andrewlewis** [comment]
Just to add to Tof's comment, based on your comment that:

> The problem is when we set Profile and Level using [setEncodingProfileLevel](https://github.com/androidx/media/blob/4f5038bc07c06910b74e53408b3866dfe8dbc43d/libraries/transformer/src/main/java/androidx/media3/transformer/VideoEncoderSettings.java#L148), We don't see metadata in output mp4 by using mediainfo.exe. When we don't set profile and level, metadata gets generated.

... and the note about not having other transformations, I'd guess that when you don't set the profile/level you are getting transmuxing behavior (no decode/re-encode). When you set custom video encoder settings that prevents transmuxing ([check here](https://github.com/androidx/media/blob/4f5038bc07c06910b74e53408b3866dfe8dbc43d/libraries/transformer/src/main/java/androidx/media3/transformer/DefaultEncoderFactory.java#L337)), and so the stream gets decoded and re-encoded. In this case, to have metadata in the output file the encoder needs to support `FEATURE_HdrEditing` and then the encoder itself is responsible for generating new static/dynamic HDR metadata itself depending on the format (for [HEVCProfileMain10HDR10](https://developer.android.com/reference/android/media/MediaCodecInfo.CodecProfileLevel#HEVCProfileMain10HDR10) it would just be static metadata, but for [HEVCProfileMain10HDR10Plus](https://developer.android.com/reference/android/media/MediaCodecInfo.CodecProfileLevel#HEVCProfileMain10HDR10Plus) there would be dynamic metadata as well). Transformer doesn't generate or propagate HDR metadata itself (and it can't really, for efficiency reasons).
