### ISSUE TITLE
Can I crop a video using a shape?

### ISSUE THREAD

**Issue by laewoong** [androidx/media#839]
I want to clip a video as a rounded shape like the compose code below.
Is it possible to clip a video as a shape and composite it with another video?
(I found the code to composite videos together.)

```
Box(
    modifier = Modifier
        .fillMaxSize()
        .clip(RoundedCornerShape(16.dp))
        .background(black)
)
```

<img width="373" alt="스크린샷 2023-11-24 오후 8 21 32" src="https://github.com/androidx/media/assets/97138127/2a585025-0252-40fc-ba73-87890c52c8c2">

**Comment by dway123** [comment]
Sorry no, we don't currently have an easy, built-in way to crop a rounded shape (We just have `Crop` and `Presentation`, which both create only non-rounded rectangles). 

While a bit complicated, you could generate a way to do this clip, by generating a `Bitmap` or `Drawable` that serves as an alpha mask, with just the rounded corners, to overwrite the frame contents on the edges of Video2. From there, you may need to create a custom shader program somewhat like `OverlayShaderProgram`, to apply this overlay. It would be nice if this could just work via `BitmapOverlay` or `TextureOverlay` `GlEffect`s, but I'm not sure we can apply alpha masks easily using those classes at the moment.

(@tof-tof in case of more overlays thoughts)

**Comment by laewoong** [comment]
Thanks for the reply!
I'll look into it further with the information you provided.

**Comment by tof-tof** [comment]
to add to @dway123's comment, you can just use the `BitmapOverlay` effect on your video if you have a `Bitmap` or `Drawable` that serves as an alpha mask, with just the rounded corners, to overwrite the frame contents on the edges of Video2. No need to create an new ShaderProgram, you can even use [static create method](https://github.com/androidx/media/blob/4f5038bc07c06910b74e53408b3866dfe8dbc43d/libraries/effect/src/main/java/androidx/media3/effect/BitmapOverlay.java#L146) for static (doesn't change on every timestamp) overlays to avoid having to implement the interface

**Comment by laewoong** [comment]
@tof-tof Thanks for the reply!
Could you provide some sample code how I can set the mask option in BitmapOverlay?
Or could you share a link related it?
I can't find any related methods in OverlaySettings.

```
 OverlayEffect(
  ImmutableList.Builder<TextureOverlay>().add(
      BitmapOverlay.createStaticBitmapOverlay(
          BitmapFactory.decodeResource(context.resources, R.drawable.rounded_corners_res),
          OverlaySettings.Builder().???
      )
  ).build()
```
Thanks!!

**Comment by tof-tof** [comment]
Hi, so to create rounded corners, you would have to provide a image file that has a opaque rounded square in the middle where you're content goes and transparent everywhere else for the video between the sharp corner and the rounded corners can come through. you can create a bitmap like this in free tools like gimp. 

googling around i also see [`RoundedBitmapDrawable`](https://developer.android.com/reference/androidx/core/graphics/drawable/RoundedBitmapDrawable) which could provide a much simpler solution. (We have a `DrawableOverlay` class that takes Drawables rather than bitmaps in)

**Comment by laewoong** [comment]
@tof-tof I understand that I need to prepare a rounded bitmap.
But I didn't understand that using just a BitmapOverlay would result in a clipped video.

In the code below, I think I've implemented everything you've described,
but the result is not outputting the way I want.

Am I missing something?

<img width="636" alt="sample" src="https://github.com/androidx/media/assets/37465905/1344a8b4-434f-4206-ac2a-62aa7a009f75">


### short version source code
```
@OptIn(UnstableApi::class)
suspend fun composeVideo(
    context: Context,
    backgroundVideoUrl: String,
    overlayVideoUrl: String
) {
    val backgroundMediaItem = EditedMediaItem.Builder(MediaItem.fromUri(backgroundVideoUrl))
        ...
        .build()

    val overlayMediaItem = EditedMediaItem.Builder(MediaItem.fromUri(overlayVideoUrl))
        ...
        .build()

    val compositionVideoEffects: List<Effect> = ImmutableList.of(
        ...,
        OverlayEffect(
            ImmutableList.of(
                BitmapOverlay.createStaticBitmapOverlay(
                    // prepare a rounded bitmap
                    Bitmap.createBitmap(
                        overlayVideoSize,
                        overlayVideoSize,
                        Bitmap.Config.ARGB_8888
                    ).apply {
                        Canvas(this)
                            .drawRoundRect(
                                0f, 0f, overlayVideoSize.toFloat(), overlayVideoSize.toFloat(),
                                overlayVideoRadius, overlayVideoRadius,
                                Paint(Paint.ANTI_ALIAS_FLAG).apply {
                                    color = Color.BLACK
                                }
                            )
                    },
                    OverlaySettings.Builder().build()
                )
            )
        )
    )

    ...
    val composition: Composition = Composition.Builder(
        ...
        .setEffects(
            Effects(
                ImmutableList.of(),
                compositionVideoEffects
            )
        )
        ...
        .build()

    ...
}
```

### full source code
```
@OptIn(UnstableApi::class)
suspend fun composeVideo(
    context: Context,
    backgroundVideoUrl: String,
    overlayVideoUrl: String
) {

    val backgroundVideoSize = 1000
    val overlayVideoSize = 500
    val overlayVideoRadius = overlayVideoSize * 0.2f

    val backgroundMediaItem = EditedMediaItem.Builder(MediaItem.fromUri(backgroundVideoUrl))
        .setRemoveAudio(true)
        .setEffects(
            Effects(
                listOf(),
                listOf(
                    Presentation.createForWidthAndHeight(
                        backgroundVideoSize,
                        backgroundVideoSize,
                        Presentation.LAYOUT_SCALE_TO_FIT_WITH_CROP
                    )
                )
            )
        )
        .build()

    val overlayMediaItem = EditedMediaItem.Builder(MediaItem.fromUri(overlayVideoUrl))
        .setRemoveAudio(true)
        .setEffects(
            Effects(
                listOf(),
                listOf(
                    Presentation.createForWidthAndHeight(
                        overlayVideoSize,
                        overlayVideoSize,
                        Presentation.LAYOUT_SCALE_TO_FIT_WITH_CROP
                    )
                )
            )
        )
        .build()

    val compositionVideoEffects: List<Effect> = ImmutableList.of(
        Presentation.createForWidthAndHeight(
            backgroundVideoSize, backgroundVideoSize, Presentation.LAYOUT_SCALE_TO_FIT
        ),
        OverlayEffect(
            ImmutableList.of(
                BitmapOverlay.createStaticBitmapOverlay(
                    Bitmap.createBitmap(
                        overlayVideoSize,
                        overlayVideoSize,
                        Bitmap.Config.ARGB_8888
                    ).apply {
                        Canvas(this)
                            .drawRoundRect(
                                0f, 0f, overlayVideoSize.toFloat(), overlayVideoSize.toFloat(),
                                overlayVideoRadius, overlayVideoRadius,
                                Paint(Paint.ANTI_ALIAS_FLAG).apply {
                                    color = Color.BLACK
                                }
                            )
                    },
                    OverlaySettings.Builder().build()
                )
            )
        )
    )

    val compositorSettings: VideoCompositorSettings =
        object : VideoCompositorSettings {
            override fun getOutputSize(inputSizes: List<Size>): Size {
                return inputSizes[1]
            }

            override fun getOverlaySettings(
                inputId: Int,
                presentationTimeUs: Long
            ): OverlaySettings {
                return OverlaySettings.Builder().build()
            }
        }

    val composition: Composition = Composition.Builder(
        ImmutableList.of(
            EditedMediaItemSequence(
                ImmutableList.of(
                    overlayMediaItem
                )
            ),
            EditedMediaItemSequence(
                ImmutableList.of(
                    backgroundMediaItem
                )
            )
        )
    )
        .setEffects(
            Effects(
                ImmutableList.of(),
                compositionVideoEffects
            )
        )
        .setVideoCompositorSettings(compositorSettings)
        .build()

    val transformer = Transformer.Builder(context)
        .setVideoMimeType(MimeTypes.VIDEO_H265)
        .build()

    val outputPath =
        "${context.externalCacheDir}${File.separator}${System.currentTimeMillis()}.mp4"

    withContext(AndroidUiDispatcher.Main) {
        transformer.start(composition, outputPath)
    }
}
```

**Comment by tof-tof** [comment]
the following lines look suspicious 
```Paint(Paint.ANTI_ALIAS_FLAG).apply {
                                    color = Color.BLACK```

why have you set the color to black? surely this should be Color.transparent to let the overlay though in the middle? 

thinking this through again though the bitmap mask idea may not work as intended as there is no way to see what is behind the rounded corners (i.e. the blue area) with a static overlay mask. If you could get the video frames into RoundedBitmaps, you could composite them using overlays, but this may be complex

**Comment by laewoong** [comment]
When you said to use "a opaque rounded square in the middle" , I thought you meant something like [PorterDuff.Mode](https://developer.android.com/reference/android/graphics/PorterDuff.Mode).

Thanks for the reply!

**Comment by tof-tof** [comment]
Hmmm [Destination in](https://developer.android.com/reference/android/graphics/PorterDuff.Mode#DST_IN) from that website you linked look pretty good, but the overlay frame (the rounded rect overlay you created) have to be the "destination image" in they speak of, and video2 would be the "source image".  If you have a way to composite two videos together using these modes, you could overlay the black frame onto video1 to create `video1a` say, then composite video 1a and video 2 together using the PorterDuff.Mode.Destination_In. don't think our compositing supports these modes yet though...

**Comment by dway123** [comment]
While it's not great to need to do this, you could make a custom implementation of `OverlayShaderProgram` (and all the overlay effect shaders) by copy/pasting them, and modify the shader's [`getMixColor`](https://github.com/androidx/media/blob/main/libraries/effect/src/main/java/androidx/media3/effect/OverlayShaderProgram.java#L184-L190) to something like the following:
```
vec4 getMixColor(vec4 videoColor, vec4 overlayColor) {
  // Simulates something like PorterDuff.Mode.DST_IN.
  if(overlayColor.a == 0) {
    return vec4(0.0, 0.0, 0.0, 0.0); // transparent
  } else {
    return videoColor;
  }
}
```

That should allow you to achieve your intended effect, though I admit it is quite inconvenient for now.
