### ISSUE TITLE
sometimes SeekBar is not showing in the Notification

### ISSUE THREAD

**Issue by graymind75** [androidx/media#84]
Hi
I'm currently writing a Music Player that streams the music from the network
The issue I am facing is sometimes seekBar is not showing in the Notification
is there a solution to set it in Service? or It's a bug?

also, `MediaMetadata.Builder.setArtworkUri` seems not working. I had to set `NotificationBuilder.setLargeIcon` manually to show artwork.

![player](https://user-images.githubusercontent.com/22690689/172627470-acb9836e-61e1-4c8b-b646-f6861a223f30.jpg)

**Comment by graymind75** [comment]
>  A media needs to be seekable. Can you check whether the media that doesn't show the seekbar is seekable? Alternatively please provide a media URI for such a stream.

Yes, It's seekable. the problem is sometimes randomly seekbar not showing but the solution is to pause the Player and then it shows up
the same song playing that seekbar was hidden before:
![photo_2022-06-09_00-01-15](https://user-images.githubusercontent.com/22690689/172701485-8cf1fc2f-bef4-4f67-b322-2a0ae22c9cd9.jpg)

This is such a great API that you guys developing, Thanks.

**Comment by Kyant0** [comment]
`MediaMetadata.Builder.setArtworkUri` is still not working in the 1.0.0-beta01

**Comment by graymind75** [comment]
> `MediaMetadata.Builder.setArtworkUri` is still not working in the 1.0.0-beta01

Yes, it's not working for me either
Unfortunately, in `1.0.0-beta01` after seeking another media item, the title and artist do not change to new MediaMetadata values. The manual solution, as I earlier pointed is a pause and then play again.
SeekBar does not show the first time, but after pausing and resuming after. It's visible and works like a charm.

**Comment by marcbaechinger** [comment]
@Kyant0 

The session demo app is using [`MediaMetadata.Builder.setArtworkUri`](https://github.com/androidx/media/blob/release/demos/session/src/main/java/androidx/media3/demo/session/MediaItemTree.kt#L83) and I am pretty sure I was looking at notifications that display a background image.

Can you check whether this works for you with the session demo app, then check whether you do the same with your app? If you still see that this is not working, please open a different issue that is about that specific problem and explain in a bit more detail what you are doing when building the media item and setting it to the player.

**Comment by Kyant0** [comment]
@graymind75 I migrated from `Service` to `MediaLibraryService`, it worked! Splendid!
