### ISSUE TITLE
BitmapOverlay constructor should be public

### ISSUE THREAD

**Issue by steelbytes** [androidx/media#851]
BitmapOverlay constructor should be public so I can subclass it.  I can't see a good reason to not have it public

**Comment by lazydevpro** [comment]
is there an ETA when the next release is coming? because its been month and that issue is still there.

**Comment by tof-tof** [comment]
@microkatz should be able to give more details upon this

**Comment by microkatz** [comment]
@lazydevpro 

1.2.1 was released yesterday and so you should have the fix on that tag on the release branch.

The fix was added in this commit, https://github.com/androidx/media/commit/f0d24cbf5871cfe21d47acf0944e57a8eb0eaf4a

Thank you for your patience!
