### ISSUE TITLE
Create ExoPlayer

### ISSUE THREAD

**Issue by yoobi** [androidx/media#852]
Hello,

I couldn't find anything in the doc or others forums
Is there any issue using `ApplicationContext` to create the ExoPlayer instance ? 
I wish to create a single instance of ExoPlayer in my application. Therefore using`ExoPlayer.Builder(applicationContext )`

Thanks

**Comment by marcbaechinger** [comment]
Using `context.getApplicationContext()` is fine it is even a good practice in cases that you mention. It makes sure to not leak a reference to a context coming from an activity that is destroyed already.

However, even when building the player with an application context, the player needs to be released when your application goes into background unless you are housing the player in a foreground service. When your activity/app goes into background without a service, resources like codec instances need to be released. Please see the [lifecycle methods of the `PlayerActivivty`](https://github.com/androidx/media/blob/release/demos/main/src/main/java/androidx/media3/demo/main/PlayerActivity.java#L146C26-L187) of the main demo app.
