### ISSUE TITLE
Non-linear Stretch - for stretching with less distortion

### ISSUE THREAD

**Issue by jan-kleks** [androidx/media#857]
### [REQUIRED] Use case description
Android devices come in many screen sizes and movies are filmed in various formats as well. That is why, an effective method for resizing videos which strikes a balance between cropping and stretching with minimal distortion might be of great use for those who would like to fill their display's space. 

See:

- [Video demo of how the feature works](https://www.youtube.com/watch?v=EZIa4bbmSUA)

- [Non-linear Stretch example for 16:9 screens](https://www.youtube.com/watch?v=KGBDB0hIjY4)

- [Text description with images](https://web.archive.org/web/20220223072951/https://madvrenvy.com/wp-content/uploads/Envy-Setup-Guide-NLS.pdf)

Also, combined with automatic black bars detection, NLS could let people watch movies which often change aspect ratios, in one format (for example, IMAX-enhanced videos). 

### Proposed solution
- Here you can find, for instance, an implementation of the NLS feature for mpv-player: https://github.com/mpv-player/mpv/issues/12856#issuecomment-1802651122

- An interesting article about a method taking into account video content when resizing: https://www.researchgate.net/publication/336713086_Video_Retargeting_Trade-off_between_Content_Preservation_and_Spatio-temporal_Consistency

**Comment by tonihei** [comment]
Can you comment on where in the pipeline you want to integrate the stretching logic? 

The standard way of stretching/cropping the video is via Android's built-in logic in the UI layer where the `View` can specify its size and the rest follows from there. Media3 provides the `AspectRatioFrameLayout` with 4 different options to choose from to handle the standard ways of stretching/cropping videos. If you want to change the logic there, feel free to use the class and amend the logic as needed. If it comes down to some generic parameter that can be passed in via the constructor and is generally useful, please also feel free to send a PR with such a change. 

The second option is to actually process the video output itself to a different output size. You can specify effects via `ExoPlayer.setVideoEffects` and include a combinations of existing effects (e.g. `ScaleAndRotateTransformation` / `Crop`) or write your own custom shader if needed.
