### ISSUE TITLE
Some m3u8 keeps always buffering

### ISSUE THREAD

**Issue by elrufoelrufo** [androidx/media#860]
### Version

Media3 1.2.0

### More version details

We have checked in the last exoplayer1, exoplayer2, and Media3. Some m3u8 keeps always buffering in exoplayer2 and Media3. These m3u8 work well in exoplayer 1. 

### Devices that reproduce the issue

We have this issue in all devices tested : 

- Samsung s23 Ultra
- Pixel 3a
- Pixel 6a

### Reproducible in the demo app?

Yes

### Reproduction steps

Play the m3u8 URL demo app, the playback keeps buffering. 

### Expected result

The url should be played.

### Actual result

The playback status keeps buffering.

### Media

We will send the url by email.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by tonihei** [comment]
The reason playback never starts is that your TS files declare that they contain an H264 stream, but never include any samples for it. So the player is loading and waiting for H264 data before starting playback. This can be fixed in two ways:
 - Use an HLS multivariant playlist that includes the "codecs" declaration for just the audio. This allows the player to know that there is no H264 stream.
 - Configure the extrsactor used by the player to ignore the H264 declaration with `HlsMediaSource.Factory.setExtractorsFactory(new DefaultHlsExtractorsFactory(DefaultTsPayloadReaderFactory.FLAG_IGNORE_H264_STREAM, true))`.

**Comment by elrufoelrufo** [comment]
We have checked using the flag DefaultTsPayloadReaderFactory.FLAG_IGNORE_H264_STREAM and is not working for us, continue buffering.  We have checked that  

Find below our code in android.media3 demo:

 
````
private MediaSource.Factory createMediaSourceFactory() {
    DefaultDrmSessionManagerProvider drmSessionManagerProvider =
        new DefaultDrmSessionManagerProvider();
    drmSessionManagerProvider.setDrmHttpDataSourceFactory(
        DemoUtil.getHttpDataSourceFactory(/* context= */ this));
    ImaServerSideAdInsertionMediaSource.AdsLoader.Builder serverSideAdLoaderBuilder =
        new ImaServerSideAdInsertionMediaSource.AdsLoader.Builder(/* context= */ this, playerView);

    DefaultExtractorsFactory extractorsFactory = new DefaultExtractorsFactory()
        .setTsExtractorFlags(DefaultTsPayloadReaderFactory.FLAG_IGNORE_H264_STREAM);


    if (serverSideAdsLoaderState != null) {
      serverSideAdLoaderBuilder.setAdsLoaderState(serverSideAdsLoaderState);
    }
    serverSideAdsLoader = serverSideAdLoaderBuilder.build();
    ImaServerSideAdInsertionMediaSource.Factory imaServerSideAdInsertionMediaSourceFactory =
        new ImaServerSideAdInsertionMediaSource.Factory(
            serverSideAdsLoader,
            new DefaultMediaSourceFactory(/* context= */ this,extractorsFactory)
                .setDataSourceFactory(dataSourceFactory));
    return new DefaultMediaSourceFactory(/* context= */ this)
        .setDataSourceFactory(dataSourceFactory)
        .setDrmSessionManagerProvider(drmSessionManagerProvider)
        .setLocalAdInsertionComponents(
            this::getClientSideAdsLoader, /* adViewProvider= */ playerView)
        .setServerSideAdInsertionMediaSourceFactory(imaServerSideAdInsertionMediaSourceFactory);
  }`

Please, could you help us?

Thanks for your help.
