### ISSUE TITLE
When without extra setting, the MediaMetadata can't read the flac format music.

### ISSUE THREAD

**Issue by haijialiu** [androidx/media#861]
Hello,
I have been trying to play the format flac music and use foregroundService. I just declare:
```
android:foregroundServiceType="mediaPlayback"
            android:exported="true"
```
without any setting, but theMediaMetadata can work on ogg format music and it can't read the title or others details infos( the album pictrure can display).
so what can I do?
Thanks.

**Comment by tonihei** [comment]
Could you provide some more details on which parts of our libraries you are using? Are you using ExoPlayer, MediaSession, MediaSessionService, ...? 

It sounds as if you are relying on metadata that is stored inside the media files and you observe that some OGG files provide metadata you expect and some FLAC files don't?  If this is correct and expect the metadata to be there, could you share the file so we can see if this is a parsing issue or feature request? 

Outside of the information from the media files, you can also manually provide `MediaMetadata` with `MediaItem.Builder.setMediaMetadata`.

**Comment by tonihei** [comment]
Closing due to lack of new information.
