### ISSUE TITLE
sound in debug preview

### ISSUE THREAD

**Issue by steelbytes** [androidx/media#863]
I'm unable to find a way to get sound with the debug preview.

**Comment by steelbytes** [comment]
My app applies video overlay that has to be sync with the audio.  currently have to render 30 seconds or more then playback then tweak a settings in my ui and repeat.  painful.

**Comment by droid-girl** [comment]
The current preview that we use in our Transformer is mainly used for debugging and diagnostics. We will not be adding audio playout to the debug preview as video transformation does not go at the same rate as audio. 
The team is working on adding new functionality that will make it possible to preview a composition before exporting it. I hope that will make your workflow easier.
