### ISSUE TITLE
Building Media Player From A Raw Resource

### ISSUE THREAD

**Issue by PythonVader** [androidx/media#868]
.I am Filing this To request addition of the .buildRawResourceUri() as part of the Stable API. 
I am building a simple ExoPlayer as an Audio Media Player from a Raw resource, adding this will require UnstableApi.

This will Allow us to build ExoPlayer from a Raw file stored locally or on an App's LocalDatabase.

Thank you

**Comment by PythonVader** [comment]
The Use of Unstable Api will require me to Mark all classes that use the Player with @UnstableApi

**Comment by tonihei** [comment]
> The Use of Unstable Api will require me to Mark all classes/UI that use the Player with @UnstableApi

You'd only need to mark the method (or even local variable) that uses the unstable API call. 

> I am Filing this To request addition of the .buildRawResourceUri() as part of the Stable API

That sounds reasonable if that's what's blocking you from only using stable APIs. The location of the method is not ideal though. I'll investigate this further and see what we can do.

**Comment by tonihei** [comment]
> I'll investigate this further and see what we can do.

It turns out, we also support the official Android resource ids and it's preferable to use those. You also don't need to use a Media3 util method to generate them as you can use 
```
new Uri.Builder()
    .scheme(ContentResolver.SCHEME_ANDROID_RESOURCE)
    .path(resourceId)
    .build()
```

Given this, I'm actually going to deprecate `buildRawResourceUri` and our own scheme as it's redundant.

**Comment by tonihei** [comment]
I assume this answers your question and I'll close this issue.
