### ISSUE TITLE
ac3 eac3 sound format

### ISSUE THREAD

**Issue by radyoof** [androidx/media#871]
En son sürümde eca3 ses formatında mkv uzantılı exoplayer filmi. Film oynuyor ama ses yok. eca3 ve eca ses formatını tanımıyor. ne yapmamız gerekiyor

exoplayer movie with mkv extension in eca3 audio format in the latest version. The movie is playing but there is no sound. eca3 and eca do not recognize the audio format. what do we need to do

**Comment by tonihei** [comment]
ExoPlayer supports the handling of both ac3 and eac3, but not all devices may support these formats. If something is not working, you'd need to provider more details about the problem (device, test media, reproduction steps at least)

**Comment by radyoof** [comment]
the problem persists. AC3 5.1 audio does not play in mkv extension video. Other applications use the same exoplayer, the same phone produces sound, but the exoplayer ac3 I have does not produce sound. The problem is where am I making a mistake?
