### ISSUE TITLE
Closed caption with srt format disappeared and reappeared when set experimentalUseProgressiveMediaSourceForSubtitles to true

### ISSUE THREAD

**Issue by Hiwensen** [androidx/media#879]
### Version

ExoPlayer 2.19.1

### More version details

It also happened on 2.18.5

### Devices that reproduce the issue

* Pixel 2 running Android 11
* Pixel 7a running Android 14
As far as my understanding, this is not a device specific issue.

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Check out the release-v2 branch of ExoPlayer;
2. Add another sample to `media.exolist.json`.
```
{
        "name": "test subtitle issue",
        "uri": "https://manifest.staging-public.tubi.io/6526b9fa-0c02-4a6d-9fff-4a8ef70dc4e8/de7zyvhkdb.m3u8?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjZG5fcHJlZml4IjoiaHR0cHM6Ly9jbG91ZGZyb250LnR1Ymktc3RhZ2luZy52aWRlbyIsImNvdW50cnkiOiJVUyIsImRldmljZV9pZCI6IjI2NjQ0NWMxLTcxMjgtNWE1OC04ZDJkLTNiMDdkODkxOTI5OSIsInBsYXRmb3JtIjoiQU5EUk9JRCIsInVzZXJfaWQiOjAsImV4cCI6MTcwNTEyMzM4M30.ab7_S6VYjaCmbmQ8r8XsfNw0tZJhITYf-ehwH_frR4Y&manifest=true",
        "subtitle_uri": "https://s.adrise.tv/d2b870dd-7374-45d5-9f13-f543bf61a991.srt",
        "subtitle_mime_type": "application/x-subrip",
        "subtitle_language": "en"
 }
```
3. Set experimentalUseProgressiveMediaSourceForSubtitles to true at `PlayerActivity.createMediaSourceFactory()`.
<img width="1252" alt="Screenshot 2023-12-09 at 12 48 19" src="https://github.com/androidx/media/assets/14145498/41644442-b3e7-42b2-8e7e-000471097905">

4. Run the ExoPlayer code, select the newly added sample and start to play from the beginning.

### Expected result

All the subtitle segments show up.

### Actual result

If the display start time of the subtitle segment is equal to the display end time of the previous subtitle segment, the subtitle segment is not displayed.
The following subtitle segments doesn't show up.
`(dynamic music)`, `(guns firing)`,`(gun firing)`, `(Angie panting)`, `- Shit.`,`(dark ominous music)`, `Oh, fuck! (crying)`, `(tense rumbling music)`
<img width="374" alt="Screenshot 2023-12-09 at 12 53 52" src="https://github.com/androidx/media/assets/14145498/4eb79743-1337-48d2-83ab-92ea6ac171d1">

**Why I use experimentalUseProgressiveMediaSourceForSubtitles?**
Please check https://github.com/androidx/media/issues/720 for details.

**Way to fix this issue**
Change the line 113 at SubripDecoder.java from `cueTimesUs.add(parseTimecode(matcher, /* groupOffset= */ 1));` to `cueTimesUs.add(parseTimecode(matcher, /* groupOffset= */ 1) + 1);` can fix this issue,  not sure if there is a better way to fix this.

### Media

```
{
        "name": "test subtitle issue",
        "uri": "https://manifest.staging-public.tubi.io/6526b9fa-0c02-4a6d-9fff-4a8ef70dc4e8/de7zyvhkdb.m3u8?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjZG5fcHJlZml4IjoiaHR0cHM6Ly9jbG91ZGZyb250LnR1Ymktc3RhZ2luZy52aWRlbyIsImNvdW50cnkiOiJVUyIsImRldmljZV9pZCI6IjI2NjQ0NWMxLTcxMjgtNWE1OC04ZDJkLTNiMDdkODkxOTI5OSIsInBsYXRmb3JtIjoiQU5EUk9JRCIsInVzZXJfaWQiOjAsImV4cCI6MTcwNTEyMzM4M30.ab7_S6VYjaCmbmQ8r8XsfNw0tZJhITYf-ehwH_frR4Y&manifest=true",
        "subtitle_uri": "https://s.adrise.tv/d2b870dd-7374-45d5-9f13-f543bf61a991.srt",
        "subtitle_mime_type": "application/x-subrip",
        "subtitle_language": "en"
 }
```

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment]
Can you please retry with the latest version of the library (media3 1.2.0)? There were lots of changes to subtitle handling between 1.1.1 (which corresponds to ExoPlayer 2.19.1) and 1.2.0 so before investigating further it would be good to check this hasn't already been resolved. There is no ExoPlayer version corresponding to media3 1.2.0.

**Comment by Hiwensen** [comment]
> Can you please retry with the latest version of the library (media3 1.2.0)? There were lots of changes to subtitle handling between 1.1.1 (which corresponds to ExoPlayer 2.19.1) and 1.2.0 so before investigating further it would be good to check this hasn't already been resolved. There is no ExoPlayer version corresponding to media3 1.2.0.

Will do that and get back to you later.

**Comment by icbaker** [comment]
Please update this issue when you've tried on 1.2.0 - thanks!

**Comment by Hiwensen** [comment]
> Please update this issue when you've tried on 1.2.0 - thanks!

Hi, I confirmed can't reproduce this issue on media3 1.2.0. 
Thank you!
