### ISSUE TITLE
Get quality in p like 180p 240p 360p

### ISSUE THREAD

**Issue by ahmedaa6122** [androidx/media#880]
How get quality of video in format 180p, 240p,... etc . I use track selection and I get format.width and format.hight and I need get like youtube format . Thanks.

**Comment by icbaker** [comment]
Assuming your [content is progressive](https://en.wikipedia.org/wiki/Progressive_scan) (which it presumably is if you want the 'p' suffix), you should just be able to do: 

```
String heightWithP = format.height + "p";
```

i.e. 180p content is just content with 180 lines, i.e. a height of 180.
