### ISSUE TITLE
Reason behind FOREGROUND_SERVICE_MEDIA_PLAYBACK

### ISSUE THREAD

**Issue by ChernyshovYuriy** [androidx/media#881]
Hello team,

Could you please explain in a bit greater details the reason behind FOREGROUND_SERVICE_MEDIA_PLAYBACK and what uses cases it covers? Isn't just foreground service not enough?

https://developer.android.com/reference/android/Manifest.permission#FOREGROUND_SERVICE_MEDIA_PLAYBACK

The reason behind this question is Google Store asks a video to demonstrate how this permission works. A bit odd as of me to introduce an extra permission to later ask to show how it works ...

**Comment by icbaker** [comment]
I'm afraid the permission you've linked to is part of the Android framework, and not part of the `androidx.media3` library (which this GitHub tracker serves). We are not the right people to answer your question. If you think the documentation needs clarifying, I suggest you file an issue in the Android framework issue tracker: https://source.android.com/docs/setup/contribute/report-bugs#filing-a-bug
