### ISSUE TITLE
Can't run lib-extractor unit test on latest main branch

### ISSUE THREAD

**Issue by ybai001** [androidx/media#884]
I'm running lib-extractor unit test, e.g. mp4Sample(), mp4SampleWithAc3Track(), mp4SampleWithAc4Track() in Mp4ExtractorTest.java.

After I click the green arrow to run the specific test case, I got below output:

> Task :lib-extractor:testDebugUnitTest FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':lib-extractor:testDebugUnitTest'.
> No tests found for given includes: [androidx.media3.extractor.mp4.Mp4ExtractorTest.mp4SampleWithAc4Track](--tests filter)
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 4s
148 actionable tasks: 1 executed, 147 up-to-date
10:25:25 AM: Execution finished ':lib-extractor:testDebugUnitTest --tests "androidx.media3.extractor.mp4.Mp4ExtractorTest.mp4SampleWithAc4Track"'.

Do you have any suggestion on how to fix this issue?

Android Media Version: latest code on main branch
Device: Pixel 5 with Android 13

Development Environment 1:
- Android Studio Version: Giraffe 2022.3.1 Patch 4
- AGP Version: 8.0.1
- Gradle JDK: jbr-17 (I didn't change the setting in Android Studio)

Development Environment 2:
- Android Studio Version: Hedgehog 2023.1.1
- AGP Version: 8.0.1
- Gradle JDK: jbr-17 (I didn't change the setting in Android Studio)

The purpose of mine is to add a new test case and test asset for pull request https://github.com/androidx/media/pull/875. Before that, I'd like to make sure my dev environment is correct. Previously I can do the similar thing for ExoPlayer 2.x but I don't know why I failed in running a unit test for Media 3.  Any help is appreciated.

**Comment by ybai001** [comment]
Three more findings:

1. If I run all the tests in Mp4ExtractorTest together (144 cases, click the green arrow beside "public final class Mp4ExtractorTest {"), this issue disappears. Does it mean I can't run single test case in Media 3? I remember I can do it in ExoPlayer 2.x.

2. If I run all the tests in Mp4ExtractorTest, all cases will fail due to line-break characters. For example,
```
Actual data doesn't match dump file: extractordumps/mp4/sample_18byte_nclx_colr.mp4.0.dump
To update the dump file, change DumpFileAsserts#DUMP_FILE_ACTION to WRITE_TO_LOCAL (for Robolectric tests) or WRITE_TO_DEVICE (for instrumentation tests) and re-run the test.
diff (-expected +actual): (line contents match, but line-break characters differ)
  at androidx.media3.test.utils.DumpFileAsserts.assertOutput(DumpFileAsserts.java:172)
  at androidx.media3.test.utils.DumpFileAsserts.assertOutput(DumpFileAsserts.java:99)
  at androidx.media3.test.utils.ExtractorAsserts.assertOutput(ExtractorAsserts.java:461)
  at androidx.media3.test.utils.ExtractorAsserts.assertBehavior(ExtractorAsserts.java:404)
  at androidx.media3.test.utils.ExtractorAsserts.assertBehavior(ExtractorAsserts.java:357)
  at androidx.media3.extractor.mp4.Mp4ExtractorTest.mp4Sample18ByteNclxColr(Mp4ExtractorTest.java:119)
```
Is it normal? How to fix it?

3. If I change
`private static final @DumpFilesAction int DUMP_FILE_ACTION = COMPARE_WITH_EXISTING;`
to
`private static final @DumpFilesAction int DUMP_FILE_ACTION = WRITE_TO_DEVICE;`
I can't find dump files in folder /storage/emulated/0/Android/data/androidx.media3.demo.main.
If I change to
`private static final @DumpFilesAction int DUMP_FILE_ACTION = WRITE_TO_LOCAL;`
everything is OK.

**Comment by ybai001** [comment]
> Three more findings:
> 
> 1. If I run all the tests in Mp4ExtractorTest together (144 cases, click the green arrow beside "public final class Mp4ExtractorTest {"), this issue disappears. Does it mean I can't run single test case in Media 3? I remember I can do it in ExoPlayer 2.x.
> 2. If I run all the tests in Mp4ExtractorTest, all cases will fail due to line-break characters. For example,
> 
> ```
> Actual data doesn't match dump file: extractordumps/mp4/sample_18byte_nclx_colr.mp4.0.dump
> To update the dump file, change DumpFileAsserts#DUMP_FILE_ACTION to WRITE_TO_LOCAL (for Robolectric tests) or WRITE_TO_DEVICE (for instrumentation tests) and re-run the test.
> diff (-expected +actual): (line contents match, but line-break characters differ)
>   at androidx.media3.test.utils.DumpFileAsserts.assertOutput(DumpFileAsserts.java:172)
>   at androidx.media3.test.utils.DumpFileAsserts.assertOutput(DumpFileAsserts.java:99)
>   at androidx.media3.test.utils.ExtractorAsserts.assertOutput(ExtractorAsserts.java:461)
>   at androidx.media3.test.utils.ExtractorAsserts.assertBehavior(ExtractorAsserts.java:404)
>   at androidx.media3.test.utils.ExtractorAsserts.assertBehavior(ExtractorAsserts.java:357)
>   at androidx.media3.extractor.mp4.Mp4ExtractorTest.mp4Sample18ByteNclxColr(Mp4ExtractorTest.java:119)
> ```
> 
> Is it normal? How to fix it?
> 
> 3. If I change
>    `private static final @DumpFilesAction int DUMP_FILE_ACTION = COMPARE_WITH_EXISTING;`
>    to
>    `private static final @DumpFilesAction int DUMP_FILE_ACTION = WRITE_TO_DEVICE;`
>    I can't find dump files in folder /storage/emulated/0/Android/data/androidx.media3.demo.main.
>    If I change to
>    `private static final @DumpFilesAction int DUMP_FILE_ACTION = WRITE_TO_LOCAL;`
>    everything is OK.

For above item 2, it is due to EOL conversion. I have solved it. Please ignore this part. Thanks.

**Comment by ybai001** [comment]
> The extractor tests are mostly parameterized with `ParameterizedRobolectricTestRunner`. Unfortunately there's a bug (possibly in Android Studio or Android Gradle Plugin?) that means it's not possible to run a single method of these tests. This is tracked internally as b/155773419. You can also file an externally visible bug here: https://developer.android.com/studio/report-bugs (if you do this, please reply here with a link, so I can link it to the internal one).
> 
> I don't believe this is a media3-specific issue, I expect you will see the same behaviour on the tip of the exoplayer dev-v2 branch. It's possible that last time you were working on these tests either Android Studio/AGP wasn't buggy in this way, or it was before [google/ExoPlayer@cfa8e19](https://github.com/google/ExoPlayer/commit/cfa8e19f772d3dc6750066ae1fcd397b31a67528) which switched to using parameterization.
> 
> The different `WRITE_` values of `DUMP_FILE_ACTION` are intended to be used for Robolectric (`WRITE_TO_LOCAL`) and instrumentation (`WRITE_TO_DEVICE`) - since there isn't a 'device' for Robolectric tests. `Mp4ExtractorTest` is a Robolectric test, so it's expected that `WRITE_TO_LOCAL` is the one that works.

@icbaker , it's very clear! Everything can be explained now. I'll submit an external bug tomorrow.

**Comment by ybai001** [comment]
@icbaker, I have created the external bug at https://issuetracker.google.com/issues/316040980.

And as you said, I ran single unit test case long ago (About Feb, 2020, https://github.com/google/ExoPlayer/pull/6971), which is actually before using parameterization ([google/ExoPlayer@cfa8e19], Apr, 2020)

**Comment by icbaker** [comment]
Thanks, I'll close this issue since there's no changes planned in the media3 library for this.
