### ISSUE TITLE
5 secondes freeze 

### ISSUE THREAD

**Issue by Julansetech83** [androidx/media#886]
### Version

Media3 1.2.0

### More version details

Hello, i am currently facing an issue with the 2.19.1 version : when i start a live streaming hls video, the player freeze 5 seconds before playing...
Can i have a tip to avoid that and play the video as soon as i opened it ? 
Best regards

### Devices that reproduce the issue

I am on an android TV box , chromecast and phillips tv

### Reproducible in the demo app?

No

### Reproduction steps

Open an hls live streaming video

### Expected result

Video start as soon as i play it

### Actual result

freeze 5 seconds before starting

### Media

https://test.everstream.tv/channels/540/1004/master.m3u8

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment]
The provided link starts playback ~immediately in the demo app on my Pixel 7a.

You say you can't reproduce in the demo app, which I understand to mean you tried the demo app and saw the playback start immediately (like me). Therefore I suggest you spend some time looking at the differences between the demo app and your app - based on the information provided so far this doesn't seem like an issue with the library.
