### ISSUE TITLE
Music Notification Artwork Not Showing

### ISSUE THREAD

**Issue by re-ovo** [androidx/media#9]
![image](https://user-images.githubusercontent.com/21152113/143439797-35a840a7-28dd-4bd1-825a-1861463d4a19.png)
I set the artworkUrl, but it doesn't show anything. Did I set it wrong?

My MediaItemBuilder:
```Kotlin

               addMediaItem(
                            MediaItem.Builder()
                                .setMediaId(track.id.toString())
                                .setMediaMetadata(
                                    MediaMetadata.Builder()
                                        .setTitle(track.name)
                                        .setArtist(track.ar.joinToString(", ") { ar -> ar.name })
                                        .setMediaUri(Uri.parse("$RainMusicProtocol://music?id=${track.id}"))
                                        .setArtworkUri(Uri.parse(track.al.picUrl))
                                        .build()
                                )
                                .build()
               )

 ```

**Comment by ojw28** [comment]
None of the UI components load from the `artworkUri` field currently, so you have to use `setArtworkData`. That's obviously bad for playlists though, since there will be a large amount of associated memory usage.

This is something we should address for 1.0.0 stable, so I'll mark it as a bug. We'll need to make sure our approach is compatible with image caching libraries (e.g., Glide), without mandating use of one. For internal devs, see [Internal ref: cr/383239306] for some previous discussion about this.

**Comment by re-ovo** [comment]
Is there any progress?

**Comment by marcbaechinger** [comment]
We added a Bitmap loader with [this commit](https://github.com/androidx/media/commit/b59869ede3b2a7f403963ab397081476a53cdbb9). It is already part of the released alpha version. 

Did you try after updating and it did not work. Please let us know if this is the case.

**Comment by re-ovo** [comment]
Do I need extra code to make it work? I'm using alpha03 and it still doesn't work

**Comment by marcbaechinger** [comment]
Closing as this will be in the next release that is coming soon.

**Comment by DevinDuricka** [comment]
I'm having a similar issue as the original bug, but local artwork seems to not show.

Here is my `MediaMetadata`
```
val mediaMetaData = MediaMetadata.Builder().apply {
                        setAlbumTitle(audiobook.audiobookTitle)
                        setAlbumArtist(audiobook.audiobookAuthor)
                        setGenre(audiobook.audiobookGenre)
                        setArtworkUri(audiobook.imgThumbnail) //Doesn't work -> content://com.android.externalstorage.documents/tree/primary%3AAudiobooks/document/primary%3AAudiobooks%2FCreativity%2C%20Inc%2FCreativity%2C%20Inc-Cover.jpg
                        //setArtworkUri(Uri.parse("https://m.media-amazon.com/images/I/51vXKxIu6xL._SL500_.jpg")) //Works
                        setTitle(track.chapters.getOrNull(index)?.chapterName?.trim() ?: track.track.trackTitle ?: audiobook.audiobookTitle)
                    }.build()
```


When I try to set the artwork via a `content://` Uri, the notification artwork is missing. (I use the same Uri in other areas of the app)  
```
setArtworkUri(audiobook.imgThumbnail) //Doesn't work -> content://com.android.externalstorage.documents/tree/primary%3AAudiobooks/document/primary%3AAudiobooks%2FCreativity%2C%20Inc%2FCreativity%2C%20Inc-Cover.jpg
```

When I use a `https://` reference, it shows the artwork in the notification. I'm not storing a url to the artwork though, so it's not really a viable solution. The above example was just for testing purposes.

Am I doing something wrong? (Or does this necessitate a separate bug?)
