### ISSUE TITLE
Equivalent of `MediaController.ControllerCallback.onPlaylistChanged`?

### ISSUE THREAD

**Issue by chvp** [androidx/media#90]
I can't seem to find an equivalent of `media2`'s [`MediaController.ControllerCallback.onPlaylistChanged`](https://developer.android.com/reference/androidx/media2/session/MediaController.ControllerCallback#onPlaylistChanged\(androidx.media2.session.MediaController,%20java.util.List%3Candroidx.media2.common.MediaItem%3E,%20androidx.media2.common.MediaMetadata\)) in `media3`. At least `Player.Listener` doesn't seem to contain a similar method. An easy way to get all the `MediaItem`s within `Player` also doesn't seem to exist?

**Comment by chvp** [comment]
Thanks, you're right that I was mostly looking for `onTimelineChanged`. It's not clear to me that that was what I was looking for from the Javadoc of `onTimelineChanged` itself. A `Timeline` is a concept that I've never had to come in contact with before, so I don't think it's very clear what a Timeline change entails for people just reading the Javadoc.

**Comment by marcbaechinger** [comment]
That's right. We went from `queue` (androidx.media) to `playlist` (androidx.media2) to `timeline` (androidx.media3). The last converges with the `Player` interface that is the new API that's available via the Media3 controller. We converge with the `ExoPlayer` API with this. Please accept my apologies for the confusion.

**Comment by chvp** [comment]
No problem, just wanted to let you know that the documentation might not be entirely clear for people not as familiar with the project.

Anyway, my issue has been fixed, so I'm closing this issue.
