### ISSUE TITLE
ERROR_CODE_UNSPECIFIED

### ISSUE THREAD

**Issue by wishygupta** [androidx/media#900]
While playing a DASH live video I encountered with this exception.
What could be the issue for it?
<img width="1055" alt="Screenshot 2023-12-15 at 4 18 40 PM" src="https://github.com/androidx/media/assets/9713225/16f2eaba-1d1e-485f-831a-6c04e522b504">

**Comment by icbaker** [comment]
* What version of the library are you using (so we can look up exact line numbers in the stack trace)?
* Please include the stack trace in plaintext so we don't need to manually transcribe the symbol names.

From the information provided it looks like maybe you've specified an override via `DefaultTrackSelector.ParametersBuilder.setSelectionOverride` for a renderer that has no tracks mapped to it.

Please provide more information about how you've configured the player.
