### ISSUE TITLE
 How to gather HAR(HTTP Archive) file with Media3(ExoPlayer)?

### ISSUE THREAD

**Issue by crystal-s-han** [androidx/media#902]

**Comment by crystal-s-han** [comment]
I'm unable to find / search from github or official docs or anywhere, how to gather HAR file for Media3(ExoPlayer). Please help how I can do.

**Comment by icbaker** [comment]
ExoPlayer currrently has no built-in way to record its network traffic to a [HAR file](https://en.wikipedia.org/wiki/HAR_(file_format)). We don't plan to build this into the library as it would require extremely deep integration with the HTTP stacks we interact with, and probably couldn't be successfully built without hooking into their implementation details. Given that, the best approach is probably to wire your app/device's networking through a proxy like Charles (where you can record the HTTP traffic) - but such a set up is beyond the scope of this issue tracker and not specific to ExoPlayer or media3, so you are best off looking for instructions elsewhere.
