### ISSUE TITLE
Add MediaItem.localConfiguration.tag to DownloadRequest

### ISSUE THREAD

**Issue by yoobi** [androidx/media#912]
### Use case description
Hello, I'm currently adding some information into `MediaItem.localConfiguration.tag` but when I transform this mediaItem to a `DownloadRequest` I can't pass the `tag` to it. I know there is `data` which is a `ByteArray` but isn't really practical.

### Proposed solution
Add a new parameter or change the type of `data` as `Any?`, `Bundle` or `Serializable` would give a smoother experience to go from `MediaItem` to `DownloadRequest` and `DownloadRequest` to `MediaItem`

**Comment by oceanjules** [comment]
Hello @yoobi,

Thank you for your suggestion, however, there is a limitation to your proposed solution.

The `download.request.data` needs to be written to a database as per:

https://github.com/androidx/media/blob/f6fe90f30ba022c7e04e14a3dc5c28c568a4d1e2/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/offline/DefaultDownloadIndex.java#L327

... and so it can't be any random object


However, if you have a Bundle already, you can easily [convert it to byte[]](https://stackoverflow.com/questions/14281339/byte-array-to-bundle) and back. Hope that helps.
