### ISSUE TITLE
Why can't it play the 2nd video link?

### ISSUE THREAD

**Issue by VenomDino** [androidx/media#915]
I have these two MKV files links.

1) https://cdn.fogplix.com/x264.mkv
2) https://cdn.fogplix.com/x265.mkv

But Media3 ExoPlayer can't play 2nd video link but it is playing 1st video link successfully. Now I want to play the 2nd video link. Is there any extension or any way to play the 2nd video link?

**Comment by rohitjoins** [comment]
Hi @VenomDino,

I'm able to play both MKV files on our demo app. Please add more information using our [template](https://github.com/androidx/media/blob/release/.github/ISSUE_TEMPLATE/bug.yml) for bugs. 

Reopen with more information and would be happy to look at it.
