### ISSUE TITLE
OfflineLicenseHelper renewLicense causes ERROR_DRM_LICENSE_PARSE

### ISSUE THREAD

**Issue by isaacchiang-kkstream** [androidx/media#919]
Hi, 

I am using ExoPlayer for offline playback. So far I have successfully downloaded the DRM content and played it offline.

However, when I want to renew the offline license through the renewLicense method of OfflineLicenseHelper, after the license expires (both playbackRemainingSec & licenseRemainingSec are 0), ExoPlayer return the [ERROR_DRM_LICENSE_PARSE](https://github.com/androidx/media/files/13757626/ERROR_DRM_LICENSE_PARSE.txt) error on this line:
```
private void onKeyResponse(Object request, Object response) {
    ...
    byte[] keySetId = mediaDrm.provideKeyResponse(sessionId, responseData);   // <= issue
    ...
}
```

The strange thing is that if I renew the license before it expires, the above line doesn't throw an exception. I made sure the DRM provider enabled the "can_renew" feature so that I could receive a response from it. 

My question is, **can I call the renewLicense method after the license expires?** Thanks and looking forward to your reply.

[ContentInfo.json](https://github.com/androidx/media/files/13757653/ContentInfo.json)
[WVcdm_error.txt](https://github.com/androidx/media/files/13757684/WVcdm_error.txt)

Testing Device: Redmi 10
Testing Device OS: Android 13

<img width="325" alt="截圖 2023-12-22 下午6 45 33" src="https://github.com/androidx/media/assets/83625736/49b5e62d-c361-43fd-860e-4ba7ac4fe37e">

**Comment by icbaker** [comment]
This is really a question about Widevine implementation details, rather than Media3 (since we just forward calls like this down to the platform `MediaDrm` API, which forwards them on to the Widevine implementation on the device). If you're a Widevine partner you can also get support directly from them: https://www.widevine.com/contact.

**Comment by isaacchiang-kkstream** [comment]
Thanks for the explanation. I'll look for support through the link you provided.
