### ISSUE TITLE
[FR] Request long press to spped up the playback.

### ISSUE THREAD

**Issue by peerless2012** [androidx/media#924]
### [REQUIRED] Use case description
Add support for change the speed for long press.

### Proposed solution
Add touche event listener for ControllerView, when down speed up, when up or cancel set the speed to pre.

### Alternatives considered
If there is a way to config the long press speed is better.

**Comment by icbaker** [comment]
I'm afraid this level of customization is outside the intended scope of our UI components, which are meant to offer a UI for relatively simple playback use-cases, and so we're not going to implement this change in the library.

From https://developer.android.com/guide/topics/media/ui/customization:
> For any further customization, app developers are expected to implement their own UI components.

**Comment by peerless2012** [comment]
But the speed is hardcode in media3 is from 0.25x to 2x,

The string array resource fro `exo_controls_playback_speeds`, if I want to enpand to `3.0x`, I should define my `exo_controls_playback_speeds` string array to override the `media3` resources?
