### ISSUE TITLE
Get Currently video Height quality

### ISSUE THREAD

**Issue by ahmedaa6122** [androidx/media#937]
I need after select vide quality using trackSelector,  I need to get currently video height quality , how I can do that's?

**Comment by icbaker** [comment]
I assume this is a follow-up to https://github.com/androidx/media/issues/880.

You can listen to [`Player.Listener.onVideoSizeChanged`](https://developer.android.com/reference/androidx/media3/common/Player.Listener#onVideoSizeChanged(androidx.media3.common.VideoSize)).

See more info about listening to player events: https://developer.android.com/guide/topics/media/exoplayer/listening-to-player-events
