### ISSUE TITLE
Playback resumption implementation problem

### ISSUE THREAD

**Issue by BoikoIlya** [androidx/media#943]
I don`t exactly understand playback resumption. As i understood i need to save for example current queue in db. and then when app is killed i press play button in notification and callback will be triggered.

```
 override fun onPlaybackResumption(
        mediaSession: MediaSession,
        controller: MediaSession.ControllerInfo,
    ): ListenableFuture<MediaSession.MediaItemsWithStartPosition> {  
```

But to fetch tracklist from my db i need coroutine. that a problem. I cant fetch tracks from db. Am i get it wrong?

Or exist other way to save and fetch track list? maybe smth like db from media 3 lib i don`t know. Help pls

**Comment by marcbaechinger** [comment]
Using coroutines shouldn't be a problem I think. The callback method returns a `Future` that you don't need to immediately resolve. Instead return the future and complete it after your coroutine has loaded the data from the database.

There is a a [Kotlin extension](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.future/) that helps using Futures in Kotlin also by converting to suspend methods or `Deferred` to Futures.

A search for ['using Futures with Coroutines'](https://www.google.com/search?q=using+Futures+with+Coroutines&oq=using+Futures+with+Coroutines&gs_lcrp=EgZjaHJvbWUyBggAEEUYQDIGCAEQRRg50gEINzIyMmowajGoAgCwAgA&sourceid=chrome&ie=UTF-8) probably helps some further also.
