### ISSUE TITLE
Migration documentation missing on Android Dev website

### ISSUE THREAD

**Issue by Tolriq** [androidx/media#949]
Now that many issues in media3 session have been addressed I wanted to look again in migrating, but all the docs about the migration are no more available.

https://developer.android.com/guide/topics/media/media3/getting-started/migration-guide

And all others returns 404.

The links have not been updated anywhere including at the bottom of https://developer.android.com/media/media3 so I suppose this is more a publishing issue than an new place for that documentation.

**Comment by marcbaechinger** [comment]
Thanks for reporting. 

I found it here: https://developer.android.com/media/media3/exoplayer/migration-guide
I'll check what happened. I think there should a redirect when pages are moved.

**Comment by Tolriq** [comment]
I did not find that one thanks, for the record all images on that one are broken too.

To avoid opening an issue just for that can you confirm the doc part https://developer.android.com/media/media3/exoplayer/migration-guide#PlayerNotificationManager that I can fully manage the notification & media session outside of media3 LibraryService? As in my case it's handled at higher level with the media session to work with other players, transcoding abstractions and multi platform, as I'd like to need to keep my abstraction at the center point and can't really use the Media3 one for multi platform.

**Comment by Tolriq** [comment]
Well basically everything is abstract, modular and optional including the local player via ExoPlayer and the AA support via MediaBrowserCompat.

The goal is to migrate MBC to `MediaLibraryService` but it's in a different module than the one that manage the `MediaSession` and the notification, and I'd like to be able to keep it that way. Seems it should be possible.

For the moment everything works perfectly and there's no need to migrate, but I suppose (hope) that Android Auto will one day support `MediaLibraryService` and pagination and improve things.

**Comment by marcbaechinger** [comment]
Looks like the docs are now available again including the images: https://developer.android.com/media/media3/exoplayer/migration-guide

Thanks for reporting! I'm closing this issue.

I think it should be possible to have a modular design. At least service and callback are more separated in Media3 thank before. I can't think of a modularization that you were able to do with `MediaBrowserService` but not with `MediaLibraryuService`.

Please open a specific issue for this if you find such a problem.

**Comment by Tolriq** [comment]
Thanks for doc and answers, will plan a test for the migration then.
