### ISSUE TITLE
Crash when using both media3 and exoplayer2

### ISSUE THREAD

**Issue by phongbm** [androidx/media#95]
My project use both media3 and exoplayer2. I use exoplayer2 before, and now I want to use media3 (keep exoplayer2 because I don't want to refactor project). When I run app, it crash with log:
```
 Caused by: java.lang.ClassCastException: com.google.android.exoplayer2.ui.AspectRatioFrameLayout cannot be cast to androidx.media3.ui.AspectRatioFrameLayout
```

![Screenshot 2022-06-27 111534](https://user-images.githubusercontent.com/7350399/175858946-a89f8936-2dbf-412b-94b0-21ec0b19dd39.png)

How do fix that?
Thanks.

**Comment by lemontmoon** [comment]
you cannot use exoplayer2 libraries together with media3 player libraries,, I had the same problem. It looks like theese two libraries and not compatible together.

**Comment by marcbaechinger** [comment]
I'd recommend migrating to `androidx.media3`. Using both libraries in the same project is not something we provide support for. I can't see any benefit in using both libraries and saving time with refactoring seems like this will bite you sooner or later. The stack trace above tells us it's is rather sooner than later. 

I'd take the time you invest in writing questions to forums for refactoring your code which is a sustainable investment into your project compared to investing time in moving your project into difficult waters with using both libs at a time.

I leave the issue open for a while in case someone else wants to support you.
