### ISSUE TITLE
Multiple MediaItems Play

### ISSUE THREAD

**Issue by daniello-fillthegapp** [androidx/media#960]
Hi, Is it possible for media3 ExoPlayer to play multiple items at the same time? 

I need to play 3 sounds at the same time but they don't have to be synchronised. 

I have been researching and came to the conclusion that previous methods that could be used to achieve that purpose are deprecated, like: AudioMixer or AudioSink...

**Comment by tianyif** [comment]
Hi @daniello-fillthegapp,

Thanks for asking! As you said, your three audio media don't have to be synchronized, then we'd suggest you simply to use three ExoPlayer instances. Hope this helps!
