### ISSUE TITLE
README for extensions (FFMPEG) is not clear

### ISSUE THREAD

**Issue by JaroslavHerber** [androidx/media#961]
The README shows how to build an extension like FFMPEG for some architectures. But what's next?
After executing build_ffmpeg.sh it lets the developer in the rain... What are next steps?

Which of those generated files (.../jni/ffmpeg/android-libs/) should be used for the exoplayer? Looks like they are in .a format - but shouldn't it be .so format? So there was an error or some wrong params that aren't mentioned in the README? What to do with them?

I see many other questions from other users about this, but I don't see a (good) solution. It would be nice, if there was an official/clean way to do this.

I know, you don't want to describe basic dev knowledge, how to include modules the right way. But it also looks like "the basic way" is not really practicable with ExoPlayer/Media3. Can you help with this?

**Comment by rohitjoins** [comment]
Hi @JaroslavHerber,

Have you seen the [link](https://developer.android.com/media/media3/exoplayer/troubleshooting#how-can-i-get-a-decoding-library-to-load-and-be-used-for-playback) in the README page for trouble shooting?

**Comment by JaroslavHerber** [comment]
Yes. But none of my questions are answered on those page.

**Comment by rohitjoins** [comment]
The troubleshooting doc mentions about:

```
You should see .so files appear in the libs subdirectory of the library's path for each supported architecture after following the steps in the README.
```

Please add any specific question you have on following the README and what specifically you want to be included?
