### ISSUE TITLE
Different Colors in Transparent, BitmapOverlay in Media Transformer

### ISSUE THREAD

**Issue by ihrishix** [androidx/media#967]
Hey,

Using a transformer, I'm using a Bitmap Overlay to put an overlay on the Video.
The output video has different overlay colors, compared to the passed bitmap.

This only happens when the bitmap has somewhat transparent elements (Like 80% transparency). 

Expected Result - (Red line is the overlay bitmap)
![image](https://github.com/androidx/media/assets/55173065/eed5caae-fd7f-404a-ae46-ac0f1df4211b)

Actual Result - 
![image](https://github.com/androidx/media/assets/55173065/704ff2ad-0655-48a3-a514-5e097073b117)

**Comment by dway123** [comment]
Hello @ihrishix , thank you for reporting this. Can you please confirm which branch you're currently using?

And if it's not the main branch, could you please see if you can also reproduce this on the main branch? In particular, please make sure you're on the main branch, after [this commit](https://github.com/androidx/media/commit/a2a4ef5f40f0c7a36dd9d3687271514d5b17c8c2), which affects alpha in overlays, from November 30, 2023. Note that this commit is not included in the current release branch.

**Comment by dway123** [comment]
If it does still reproduce with that commit, please share your alpha bitmap, and I can see whether this is due to some premultiplied alpha issue that the mentioned commit somehow didn't fix.
