### ISSUE TITLE
PlayerNotificationManager.Builder Unable to Unregister the Notifcation Listener

### ISSUE THREAD

**Issue by DolaKrishnan08** [androidx/media#968]
Hello,

In Media3 PlayerNotificationManager.Builder we can set NotificationListener using setNotificationListener(PlayerNotificationManager.NotificationListener)

 override fun onNotificationPosted(
            notificationId: Int,
            notification: Notification,
            ongoing: Boolean,
        ) {
            super.onNotificationPosted(notificationId, notification, ongoing)
        }

        override fun onNotificationCancelled(notificationId: Int, dismissedByUser: Boolean) {
            super.onNotificationCancelled(notificationId, dismissedByUser)
        }

Is there a way to unregister the Listener?

**Comment by microkatz** [comment]
Hello @DolaKrishnan08,

Would it work to just remove the player from the PlayerNotificationManager by doing setPlayer(null)? In that case the MSG_START_OR_UPDATE_NOTIFICATION or MSG_UPDATE_NOTIFICATION_BITMAP messages handled by the looper will just be no-ops.

**Comment by DolaKrishnan08** [comment]
When User Try to close the app In Service I will clear all instance with Notification here the code 
@Inject constructor(
    val context: Context,
    private val sessionToken: MediaSessionCompat.Token,
    private val builder: PlayerNotificationManager.Builder,
) {
private var notificationManager: PlayerNotificationManager? = null

    fun buildNotificationManager(notificationListener: PlayerNotificationManager.NotificationListener) {
        val mediaController = MediaControllerCompat(context, sessionToken)

        with(builder) {
            setChannelNameResourceId(R.string.notification_channel_name)
            setChannelDescriptionResourceId(R.string.notification_channel_description)
            setMediaDescriptionAdapter(DescriptionAdapter(mediaController))
            setNotificationListener(notificationListener)
        }
        notificationManager = builder.build()
        notificationManager?.let {
            with(it) {
                setUseStopAction(true)
                setUseNextAction(true)
                setUsePreviousAction(true)
                setUseRewindAction(false)
                setUsePlayPauseActions(true)
                setUseFastForwardAction(false)
                setMediaSessionToken(sessionToken)
                setSmallIcon(R.mipmap.your_music)
            }
        }
    }

    fun hideNotification() {
        notificationManager?.setPlayer(null)
        notificationManager = null
    }

    fun showNotificationForPlayer(
        player: Player,
    ) {
        notificationManager?.setPlayer(player)
    }
    }
    Since we set the PlayerNotificationListener in builder There is no such way to make the listener "NULL"
    1. Even After HideNotification Trigger, which makes setPlayer(null) still Service is Ongoing Due to Listener.
    2. If I don't use PlayerNotification.Listener Same Process Works Fine no Issues at all.
    
    Note: I want Listener to listen when user swipe the Notication & to Start the ForeGround Service When i Try to use Listener the Service is Not Destroying and Listener is Active.

**Comment by DolaKrishnan08** [comment]
Hi @microkatz 
Thank You, It Worked!!
