### ISSUE TITLE
Skip silence option?

### ISSUE THREAD

**Issue by krisdb** [androidx/media#970]
I read that there is a skip silence option in Exoplayer:

https://github.com/google/ExoPlayer/issues/4401

However, I don't see it in the source code:

https://github.com/androidx/media/blob/release/libraries/common/src/main/java/androidx/media3/common/PlaybackParameters.java

and I can only set the playback speed and pitch.

**Comment by microkatz** [comment]
Hi @krisdb,

You can use the ExoPlayer API setSkipSilenceEnabled. https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/ExoPlayer.java#L1557

Hopefully that works for you!

**Comment by krisdb** [comment]
Thanks, that works great.
