### ISSUE TITLE
Media item downloaded repeatedly when repeat mode is Player.REPEAT_MODE_ONE

### ISSUE THREAD

**Issue by lovegaoshi** [androidx/media#979]
Hi all, I'm running into an [issue previously reported for exoplayer2 in 2020](https://github.com/google/ExoPlayer/issues/8038) with the current [media3 gl demo](https://github.com/lovegaoshi/media): when I use repeat mode == Player.REPEAT_MODE_ONE, the media source is requested repeatably throughout the playback. I [added in okHttpClientFactory ](https://github.com/lovegaoshi/media/blob/8f4aafe53e0fc6ac9cc03cc705a6f6e6e2015b82/demos/gl/src/main/java/androidx/media3/demo/gl/MainActivity.java#L179)as mentioned in the 2020 issue since it does caching, though I still saw the repeated requests.

screenshot of the repeated mediaSource requests:
![image](https://github.com/androidx/media/assets/106490582/ec0e0266-6efd-41c8-8165-d905c8aab3bf)

I also attempted to [add a cache factory to the exoplayer](https://exoplayer.dev/customization.html#caching-data-loaded-from-the-network) but couldnt see anything in the cache dir:
![image](https://github.com/androidx/media/assets/106490582/6bbdd68e-6ae9-4499-9c32-9ea5d9730334)

I'm new to android media3 and completely lost, really appreciate if anyone can point me to the right direction, could be my code is not working as intended at all? Many thanks in advance!

**Comment by marcbaechinger** [comment]
It's correct to use a `CacheDataSource.Factory`.

I think in the code sample you give above you are injecting a `CacheDataSource.Factory` into the `DefaultMediaSourceFactory` that then is used to build the player. 

The `DefaultMediaSourceFactory` however is only used to create a `MediaSource` if you use the `MediaItem` based API like `player.setMediaItems(mediaItem)`. If you use `player.setMediaSource(mediaSource)` as in you code above, then you need to make sure that the `mediaSource` argument has been created with the `CacheDataSource.Factory` as well.

From the code above I can't see how the source is constructed, but I think it may be that the source you set is still using a data source that is not wrapped by a `CachedDataSource`.

Can you check if caching work when you either use `player.setMediaItem(mediaItem)` or then constuctor the media source with a `CacheDataSource.Factory`?

**Comment by lovegaoshi** [comment]
Thanks for the reply and the clarification! Once I correctly [append the UpstreamDataSourceFactory as a HttpDataSource.Factory](https://developer.android.com/media/media3/exoplayer/customization#caching-data) to my `cacheFactory` and use my `cacheFactory` to construct the mediaSource, I had caching correctly functioning and no repeated source requests. 

my working repo in case anyone is interested: https://github.com/lovegaoshi/media/commit/b414f0162d4c4ebfe139f340bf185d0a0f2a855a
