### ISSUE TITLE
播放异常跳过

### ISSUE THREAD

**Issue by HuShanquan3** [androidx/media#982]
https://gitee.com/misrhu/no/blob/master/guide_video.mp4 (gitee存储的视频要下载，不能在线播放)
这个视频用exoplayer开头10s会卡住，好像是自动跳过了静音部分，又好像是exoplayer的bug，使用ijkplayer就是正常的。

**Comment by microkatz** [comment]
Hi! Please provide complete information as requested in the issue template. The issue template can
be found [here](https://github.com/androidx/media/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug.yml).
If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report)
or test content publicly, please send them to android-media-github@google.com with the subject
`Issue #982`. Please also update this issue to indicate you've done this.

Also if you could translate your request title and description into English then that would be most helpful in our debugging of your issue.

**Comment by microkatz** [comment]
Also it would be easier if you could send the mp4 file to the [android-media-github@google.com](mailto:android-media-github@google.com) with the subject `Issue #982` if you are not able to attach it publicly to this github issue.
