### ISSUE TITLE
How does an external client connect to a MediaLibraryService?

### ISSUE THREAD

**Issue by aljohnston112** [androidx/media#986]
I have partially implemented a MediaLibraryService and can start it without any crashes or other issues, however, in my Activity (the "external client" here), I do not see how to connect to the MediaLibraryService without having to create a session token, so I am wondering, does the MediaController.Builder use the SessionToken to look for an already running MediaLibraryService with the given ComponentName? How is an external client supposed to know the ComponentName so they can connect to it? Are they able to find it via an Intent that matches the given actions declared in the intent-filter for the service?

**Comment by aljohnston112** [comment]
I seem to have verified via debugging that the Activity, despite making another session token, does indeed connect to the MediaLibraryService that has been started by the application.

There is one weird thing that may be a bug and, if so, I can add an issue for it. When a controller calls setMediaItem, the session's onAddMediaItems is called. setMediaItems says that it clears the playlist, so how is onAddMediaItems supposed to know if the call was from setMediaItems or one of the addMediaItem(s) methods?

**Comment by marcbaechinger** [comment]
Android makes sure there is only a single instance of a given service running at the same time.

> How is an external client supposed to know the ComponentName so they can connect to it? Are they able to find it via an Intent that matches the given actions declared in the intent-filter for the service?

Yes. An app [can query](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/SessionToken.java#L387) the `PackageManager` for services that other apps have in their manifest when `exported=true`.

> so how is onAddMediaItems supposed to know if the call was from setMediaItems or one of the addMediaItem(s) methods in which the playlist should not be cleared?

I think the library handles this for the user. There is `Callback.onSetMediaItems()` that by default delegates to `onAddMediaItems` and the calls `player.setMediaItems(items, windowIndex, startPositionMs)`.
