### ISSUE TITLE
Close caption menu with the Unknown label for the Português language

### ISSUE THREAD

**Issue by elimasword** [androidx/media#988]
### Version

Media3 1.2.0

### Devices that reproduce the issue

Pixel 6 running Android 14

### Reproducible in the demo app?

Not tested

### Reproduction steps

In my application, we are creating a fullscreen player view where we create a builder of the exoplayer and pass the media that we want to play into it. In that media, we have close captions in two languages, we have English and Português.
When the player is loaded and I click on the close captions button to open the menu to select the languages I get the options "None", "English" and "Unknown", this last one is not correct.

![Screenshot 2024-01-17 at 09 26 10](https://github.com/androidx/media/assets/97467204/d637e8e8-5039-4cfe-b2ae-7d53f0a50d97)

After doing some debugging, I noticed that in the `DefaultTrackNameProvider` existed this chunk of code in which the returning language string is empty 

![Screenshot 2024-01-17 at 09 17 37](https://github.com/androidx/media/assets/97467204/d98fcc58-f225-41c9-8416-ce22b69419b5)

Is it possible for the fallback here to be the `format.language` value and not an empty language, and rely on the values of the language labels defined in the captions of the media?

### Expected result

Have the correct language labels in the menu of the close captions

### Actual result

Have the "Unknown" label for "Português" language

### Media

![Screenshot 2024-01-17 at 09 26 10](https://github.com/androidx/media/assets/97467204/254aadc1-0d4d-4ff3-877f-9864f0ae8b6d)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by microkatz** [comment]
Hello @elimasword,

The Format.language in that section of code from your screencapture shouldn't have "português" as that is not a valid IETF BCP 47 language tag. It should be "pt". 

I tested that if the format.language was "pt" then languageLocale.getDisplayName would return "português".

Can I ask what media you are trying to play and if you may provide it? It may be that the media is providing an incorrect language tag value in its manifest or container.

**Comment by elimasword** [comment]
Ok yes, we have an issue there but shouldn't in these cases where the `languageName` is empty the return be the value that we have in `format.language` to avoid displaying "Unknown"

**Comment by microkatz** [comment]
A commit was pushed that should hopefully address your issue! If the language name's display name is not identified, then a modified string is provided which includes the language name. Hopefully this helps your use case! It was released in 1.3.1. 

If not then please open up a new issue. Thanks!
