### ISSUE TITLE
Reason why onMetadata would not be called?

### ISSUE THREAD

**Issue by Tolriq** [androidx/media#989]
ExoPlayer 1.2.0

I'm struggling to understand why I can't get `onMetadata` to be properly called in my app for Icy data.

It works correctly in the demo app, so it's probably caused by something I do but there's very little documentation about this.

As a test I only use 
```
 addMediaSource(ProgressiveMediaSource.Factory(DefaultHttpDataSource.Factory())
                    .createMediaSource(MediaItem.fromUri(uri)))

```

And I still don't get the  `onMetadata` called, `onMediaMetadataChanged` is called with everything null only once at media start all the other callbacks about timeline or trackschanged properly works.

**Comment by icbaker** [comment]
Can you debug what happens here (and specifically if you see a non-null result from `IcyHeaders.parse(...)`)?

https://github.com/androidx/media/blob/0ae7a6bd600b0c2cbee9b06c94991a73ea5bac58/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/source/ProgressiveMediaPeriod.java#L1037-L1043

If that's null, that would explain why you're not seeing ICY metadata bubbling out. If that's the case, you could try using `CronetDataSource`, which [the demo app does by default](https://github.com/androidx/media/blob/0ae7a6bd600b0c2cbee9b06c94991a73ea5bac58/demos/main/src/main/java/androidx/media3/demo/main/DemoUtil.java#L56), in case that results in different behaviour?

If you're seeing a non-null result there then the ICY metadata must be getting lost later in the chain.

**Comment by Tolriq** [comment]
Just tested via debugger and the datasource is properly wrapped for Icy

![image](https://github.com/androidx/media/assets/932609/6b59e2a2-28f2-448c-91e5-5aa0287140f8)

I tested to remove Cronet in demo app too and it still works.

**Comment by Tolriq** [comment]
@icbaker any more hint about where I should look? Got frequent requests to support this.

**Comment by icbaker** [comment]
Would you be able to provide steps we can use to reproduce (ideally a URL that repros the issue in the demo app) - that will likely be the quickest way to investigate what's going on here.

Please either post it here or send it to android-media-github@google.com with the subject `Issue #989`. Please also update this issue to indicate you’ve done this.

**Comment by Tolriq** [comment]
This is the thing everything works in the demo app this is not tied to the url but to how the data bubble up and something I do with the extractors or the renderers or something on how I initialize ExoPlayer.

____

But I've just tried again to untangle the code and figured out, maybe there's room for some notes in the docs about metadata requiring a MetadataRenderer :(

I'm using a custom `AudioOnlyRendererFactory` so as per most example I did not add the mandatory `MetadataRenderer(metadataRendererOutput, eventHandler.looper)` that would collect the metadata and call the event.

I can't find any doc mentioning that, it would have probably helped me a little figuring out this, I certainly did not thought about checking that part for the callback in the listener.

**Comment by icbaker** [comment]
If you attach an `EventLogger` do you see the metadata track logged with `supported=NO`? That would be an indication that you were missing a renderer for it: https://developer.android.com/media/media3/exoplayer/debug-logging

**Comment by Tolriq** [comment]
Yes it's present but just under there's 
```
Metadata [
 IcyHeaders: name="Drone Zone: Atmospheric ambient space music. Serve Best Chilled. Safe with most medications. [SomaFM]", genre="Techno Ambient Space", bitrate=256000, metadataInterval=16000
 ]
```
So I completely missed the group above since the data was in the log I assumed it was seen.

Anyway this is clearly an end user error but not that easy to figure out with current docs when searching about icy or metadata in it.

**Comment by icbaker** [comment]
Glad you got it resolved! In general once apps start customising the available renderers it can get a bit fiddly.

I'm guessing (?) you followed the `audioOnlyRenderersFactory` example here? https://developer.android.com/media/media3/exoplayer/shrinking#specify-renderers

I've just extended those docs with an explicit caveat that by removing a text and metadata rendererer you won't get subtitles or in-stream metadata like ICY - hopefully that helps someone in future :)

**Comment by Tolriq** [comment]
From the exoplayer page a very very very long time ago but yes the same context.

Thanks for the updated doc, not sure if it's tied to your last changes but the Kotlin examples for renderer and extractor are broken in that linked page.

**Comment by icbaker** [comment]
Thank you for pointing that out! The markdown source for the page had the rest of the snippet, but it was being truncated at the first `<` during rendering. The same problem affected lots of other media3 code snippets too - I just submitted a change that I think (hope) has fixed all of them. Please do let us know if you spot more broken code examples.
