### ISSUE TITLE
Advertise playback capabilities with fine-grained access control.

### ISSUE THREAD

**Issue by akhilesh-dubey** [androidx/media#990]
Hi,

While going through the Media3 [migration guide](https://developer.android.com/media/media3/exoplayer/migration-guide), I came across the statement: "**Advertise playback capabilities with fine-grained access control.**". I am trying to understand this but due to lack of documentation, unable to get the real meaning of this. 

### Question:

- Could you elaborate on the intended meaning of the above statement?
- What specific playback capabilities are introduced in Media3 that can be leveraged for playback?

I would greatly appreciate your answer on this.

**Comment by marcbaechinger** [comment]
> "Advertise playback capabilities with fine-grained access control."

'Playback capabilities' means 'available commands' assigned to a controller. 'fine-grained' means that an app can define a different set of available commands for each Media3 controller when the controller connects (and possibly change them during the controller is connected).  See this section [in the documentation also](https://developer.android.com/media/media3/session/control-playback#available-commands) that tells how you can define the commands for a specific controller.

> What specific playback capabilities are introduced in Media3 that can be leveraged for playback?

This is basically what the `Player` interface offers. Compared to `MediaControllerCompat` the Media3 `MediaController` has methods that are not available to `MediaControllerCompat`. An example is track selection parameters.

When using `ExoPlayer` a `MediaController` has the capabilities of `ExoPlayer`. Both implement the `Player` interface and all methods are available by the default set of available commands. 

You can skim through [the `Player` interface](https://github.com/androidx/media/blob/release/libraries/common/src/main/java/androidx/media3/common/Player.java) to see what Media3 offers when using `ExoPlayer`.

Some apps don't use `ExoPlayer`. In such a case some functionality of the `Player` interface may not be available. An app then should set the available commands of each controller to what the custom `Player` implementation supports.

**Comment by akhilesh-dubey** [comment]
Understood, Thanks a lot @marcbaechinger for detailed explanation.
