### ISSUE TITLE
The MediaSessionService never destroyed When I Open App I can see Old Data.

### ISSUE THREAD

**Issue by DolaKrishnan08** [androidx/media#998]
Starting the Service from Actvity
```
  val intent = Intent(this, YourMusicService::class.java)
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                startForegroundService(intent)
            } else {
                startService(intent)
            }
```
Once User Swipe the Notification or Trigger Stop Action in PlayerNotificationManager

The Listener from PlayerNotificationManager.NotificationListener Need to Start the Foreground Service With Notification and listen and user notification actions.
```
override fun onNotificationPosted(
            notificationId: Int,
            notification: Notification,
            ongoing: Boolean,
        ) {
            super.onNotificationPosted(notificationId, notification, ongoing)
            android.util.Log.d("AVInfo", "Service 100 triggered")
             if (ongoing) {
                 ContextCompat.startForegroundService(
                     this@YourMusicService,
                     Intent(applicationContext, this::class.java)
                 )
                 startForeground(NotificationConstants.NOTIFICATION_ID, notification)
             }
        }

        override fun onNotificationCancelled(notificationId: Int, dismissedByUser: Boolean) {
            super.onNotificationCancelled(notificationId, dismissedByUser)
            stopService()
        }
        
         fun stopService() {
            mediaSession.run {
                player.stop()
                player.release()
                release()
            }
            stopSelf()
    }
    override fun onDestroy() {
        stopForeGround()
        hideNotification()
        super.onDestroy()
    }
    
    private fun stopForeGround() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
            stopForeground(STOP_FOREGROUND_REMOVE)
        } else {
            stopForeground(true)
        }
    }
    
    fun hideNotification() {
        playerNotificationManager?.setPlayer(null)
        playerNotificationManager= null
    }
```
        MediaSessionService never destroyed, How we can Destroy the service?

**Comment by marcbaechinger** [comment]
You start the `MediaSessionService` by [building a `MediaController`](https://developer.android.com/media/media3/session/connect-to-media-app)  that then binds to the service.

The documentation section about the [Service lifecycle explains how to stop the service](https://developer.android.com/media/media3/session/background-playback#service-lifecycle).

**Comment by DolaKrishnan08** [comment]
Hello @marcbaechinger 
1. In My App I'm not using MediaController so I think this won't bind to the Service.
2. As Document Suggested I'm clearing all instance when onDestroy is Triggered 

fun stopService() {
            mediaSession.run {
                player.stop()
                player.release()
                release()
            }
            stopSelf()
    }
    override fun onDestroy() {
        stopForeGround()
        hideNotification()
        super.onDestroy()
    }
    
    private fun stopForeGround() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
            stopForeground(STOP_FOREGROUND_REMOVE)
        } else {
            stopForeground(true)
        }
    }
    fun hideNotification() {
        playerNotificationManager?.setPlayer(null)
        playerNotificationManager= null
    }

**Comment by marcbaechinger** [comment]
The intended use of `MediaSessionService` is to be started with a controller and to use the controller to control playback. If based on your experience you choose to do your own thing this is fine, but I don't think we can extensively support you with this endeavor I'm afraid.

I'd recommend using the `MediaSessionService` with a controller.  But surely, that decisions is yours.

The `MediaSessionService` implementation aims to make things easier for users that don't want to build their own service and hence don't need to read through the [extensive foreground service documentation](https://developer.android.com/develop/background-work/services/foreground-services). Users that want to/have to read this documentation find that `stopSelf` is a no-op in the case the service is still running in the foreground. So you'd have to call `stopForeGround()` before calling `stopSelf()`?

When not requiring a controller, I think I'd just create my own `Service` implementation and refrain from using `MediaSessionService`. This may be easier than bending `MediaSessionService` your way. Certainly we are convinced that using `MediaSessionService` in the intended way is the easiest approach and benefits developers that want to build a media app.

**Comment by DolaKrishnan08** [comment]
Hello @marcbaechinger 
I Got Your Point It's Best to use MediaController  when the service is MediaSessionService may be I will looks in to this, But Once MediaSessionService is Started as Normal Service with startForeGroundService(ServiceName) In OnStartCommand I am pushing PlayerNotificationManager with startForeground(NotificationConstants.NOTIFICATION_ID, notification)

Once User is Closing the App From OnDestroy I'm calling StopService(Service) where I Clear All Instance and **stopForegound** like private fun stopForeGround() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
            stopForeground(STOP_FOREGROUND_REMOVE)
        } else {
            stopForeground(true)
        }
    }
    
    After This I'm calling **stopSelf()** Notification was cleared But Service is Not Destroying Any Suggestions on This Would Help me lot, Thank You!!
